### ISSUE TITLE
Stream NEVER Loading

### ISSUE THREAD

**Issue by johnrobledo** [fuatakgun/eufy_security#100]
Stream takes forever to buffer, even with RTSP. Sometimes it won't load at all, just keep buffering. HELP! Would like to know when the thumbnail updates and if I can manually set the time interval for it to update. If it updates by motion, that is fine. PS. the eufy security addon is showing some error logs

**Comment by johnrobledo** [comment]
Here is the rewritten issue
**Describe the bug**
Stream not loading on Lovelace UI
**To Reproduce**
Steps to reproduce the behavior:
1. Go to lovelace
2. Click on camera card

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
Expected stream to start playing, instead just keeps loading.

**Hardware Information about Home Assistant
Raspberry Pi 4 running HassOS on an NVME m.2 ssd

**Hardware Information about Cameras
- Camera Model - EufyCam 2 with HomeBase 2
- Live Streaming Protocol: RTSP or P2p - RTSP

**Additional context**
Have also tried p2p streaming...same problem

**Comment by johnrobledo** [comment]
Also, how do i set it to automatically stop streaming....it just keeps going and if I manually call service it does nothing

**Comment by fuatakgun** [comment]
So, you have the ability to see the video now? Please share all updates before moving on.

Stopping stream is done through calling respective services. There is stop rtsp and stop p2p service calls. Or you can use turn on/off camera which picks rtsp/p2p automatically

**Comment by johnrobledo** [comment]
Yes...it is working really nicely! Thank you for your help! So I will
either need to manually stop it or I could create an automation stopping it
after 3 minutes correct?

>

**Comment by johnrobledo** [comment]
Unfortunately, it will not set the streaming sensor state to false when I
call stop camera...the live stream stops as it shows black, but the sensor
is still true

**Comment by johnrobledo** [comment]
And sometimes, it will keep playing

**Comment by fuatakgun** [comment]
So, before jumping into second problem, i have two installations of HA, one for development purposes for developing these integrations one for production purposes used across home.

Dev box is using 2021.10.6 version, production os 2021.10.3.

Normal streaming without WebRTC works in prod but not in dev. Which ha version you are using?

**Comment by johnrobledo** [comment]
I'm using the production version.

**Comment by johnrobledo** [comment]
And I still can't stop the webrtc camera

**Comment by johnrobledo** [comment]
Anyway - Happy Halloween!

**Comment by leonardpitzu** [comment]
I have the same issue with the latest betas - video stream is not playing at all. Latest working version was 2021.10 but sadly i don't know which revision.

**Comment by johnrobledo** [comment]
yes....Mr. Akgun was helping me with WebRTC but then i had problems with
stoppin the camera too! Try WebRTC

**Comment by johnrobledo** [comment]
Hi ....just wondering if you figured out what my problem was

**Comment by johnrobledo** [comment]
update...It briefly worked and then continued...i turned of RTSP but it says it is still using RTSP. It also says streaming sensor True when it is off.

**Comment by fuatakgun** [comment]
this issue seems to be new version of HA, somehow it is failing to show the stream. 
example issue;
- https://community.home-assistant.io/t/cameras-not-showing-live-stream/352820

So far, we have a workaround to stick with webrtc, I will keep this in low priority but continue to investigate.

**Comment by johnrobledo** [comment]
But i am on WebRTC...my problem is that the streaming sensor doesn't change
to false when the stream is off

**Comment by fuatakgun** [comment]
Ok, got it, today, if p2p or rtsp stream forcibly ended by camera/homebase, we are not receiving any event so integration is not aware of it is ended.

There are many users tricking it via calling stop p2p livestream or stop rtsp.

New version, i will introduce a mechanism to catch up this.

If you still have issues on this even after calling stop, please share your cameras following README and let me know their names.

**Comment by leonardpitzu** [comment]
I have tried as well the webrtc and streaming never works - i can't get a video output in HA.
I read  that HA 2021.11 introduces some webrtc support - did you look into this? Would this be something that makes life easier?

**Comment by fuatakgun** [comment]
https://community.home-assistant.io/t/realtime-camera-streaming-without-any-delay-webrtc/258216/343?u=fuatakgun

Please check my previous message about my request

**Comment by fuatakgun** [comment]
hi all, any shared camera on this issue? As there are many shared ones, it is hard me to keep track names. if you have shared, please put names here, if not, share please

**Comment by johnrobledo** [comment]
No not yet...it doesnt update the streaming sensor even when I call stop
RTSP or P2P

**Comment by fuatakgun** [comment]
if you want to get help, you need to read through messages. I have been asking if you want to share your camera or if you shared shared, name of it. do not just answer part of the message and dismiss the rest

**Comment by fuatakgun** [comment]
I am merging this issue with this: https://github.com/fuatakgun/eufy_security/issues/100
if you think you have a separate issue, follow README and create an issue with shared camera info.

**Comment by johnrobledo** [comment]
Of course! I ma so sorry for disregarding them...I will share now....they
are 3 eufy cam 2s from john

**Comment by johnrobledo** [comment]
I will share them in a couple hours and let you know when they are shared
