### ISSUE TITLE
Eufy Garage Control Cam

### ISSUE THREAD

**Issue by jamesheadms** [fuatakgun/eufy_security#1001]
This camera is able to open/shut the Chamberlain garage door via the eufy app.  Are we able to feed the switch through the eufy integration in HA to control the opener through Hassio?  

Tell me what you need and how to find it in logs.  

Thanks.

**Comment by fuatakgun** [comment]
I will release it on the new version, please test it and let me know.

I have already one shared device with me but the owner is sleeping now and I do not want to open the garage door in the middle of night :)

**Comment by jamesheadms** [comment]
Ha ha!

Thank you!!

**Comment by Williamysays** [comment]
@jamesheadms, confirmed working on T8453 by enabling entities for "door 1/2 open" currently testing master branch!
![Screenshot_20231128_073148_One UI Home](https://github.com/fuatakgun/eufy_security/assets/111204453/45e0d23f-c177-44b4-b953-a899e2ba04d2)

**Comment by fuatakgun** [comment]
thanks for the update, hopefully I will release the master branch into a version soon.
but if you are not stream focused, you can already get everything from master

**Comment by Williamysays** [comment]
@GHanthorn , you can update to the master branch via redownloading the addon in HACS on the top right, it will keep your devices / entities where they were in my experience since I didn't uninstall,  you will have to enable entities under diagnostic for the device!

**Comment by fuatakgun** [comment]
What version of integration are you seeing inside HACS for eufy security?

**Comment by fuatakgun** [comment]
You are not on master version of integration, please get latest version using HACS and create a new issue if needed.

You can also get the beta version, all is released under one beta version.

**Comment by jamesheadms** [comment]
Works great for me, thank you!
