### ISSUE TITLE
Unable to change Security Modes (i.e. Home, Away)

### ISSUE THREAD

**Issue by mattsmithuk** [fuatakgun/eufy_security#1002]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Since updating, the alarm_control_panel services do not change the security mode of any of my cameras. I normally use Node-Red with the Home Assistant Websocket nodes for my automations. But nor can I get my alarm modes to change in the Developer Tools -> Services page of Home Assistant. I also can't get the eufy_security.alarm_arm_custom services to work. 

This was working fine previously.

**To reproduce**

1. Go to 'Developer Tools -> Services'
2. Select 'Alarm Control Panel: Arm Away'
3. Choose Target device
4. No change in security mode

**Expected behavior**

Using alarm_control_panel.arm_away/home/disarm change security mode on the target device.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Container
- Home Assistant Core Version: core-2023.11.2
- Eufy Security Add-on Version: eufy-security-ws v1.7.1
- Eufy Security Integration Version: 7.7.4

Hardware Information;
- Camera Model: eufyCam 2C, IndoorCam C24, IndoorCam P24

- Live Streaming Protocol (RTSP/P2P):  N/A

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624):

[https://pastebin.com/C2kmsvj6](https://pastebin.com/C2kmsvj6)

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

```
2023-11-20 13:22:58.713  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-11-20 13:23:00.967  INFO  Connected to station T8010N23214525C6 on host 192.168.1.138 and port 22309 
2023-11-20 13:23:00.990  INFO  Connected to station T8020P11233301CA on host 192.168.1.72 and port 15515 
2023-11-20 13:23:01.160  INFO  Connected to station T8410P3121321F89 on host 192.168.1.167 and port 20119 
2023-11-20 13:23:01.987  INFO  Connected to station T8400P312203059E on host 192.168.1.227 and port 20119 
2023-11-20 13:23:03.135  INFO  Push notification connection successfully established 
```

- Would you share your device with me in case further debugging required? (Yes/No):
Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by fuatakgun** [comment]
thanks for the logs but it only captures loading information of the entity.

Please get more while taking the aforementioned actions to see what is going on behind the scenes, call respective services using home assistant UI (not node red please) and share new logs

**Comment by mattsmithuk** [comment]
I've looked again and it doesn't seem like the devices have any entities in which to target the Arm commands at. I've look at the the device pages for the cameras in the settings page and confirmed this. 

![Screenshot 2023-11-24 124210](https://github.com/fuatakgun/eufy_security/assets/37830884/45f8e6a4-1b78-4247-823e-f43d484247a3)
![Screenshot 2023-11-24 124244](https://github.com/fuatakgun/eufy_security/assets/37830884/8c6574e4-b88b-4c13-96aa-33075ac9d6e1)

**Comment by fuatakgun** [comment]
Can i see the device page listing all sensors?

**Comment by mattsmithuk** [comment]
Is this what you meant? Of note, the Guard Mode and Current Mode diagnostics are both Unavailable
![Screenshot 2023-11-24 183636](https://github.com/fuatakgun/eufy_security/assets/37830884/aa990c96-2c3b-4025-86c7-23a93c146105)
![Screenshot 2023-11-24 183708](https://github.com/fuatakgun/eufy_security/assets/37830884/b834640a-fcef-4803-995d-a414ea4ed2ae)
![Screenshot 2023-11-24 183744](https://github.com/fuatakgun/eufy_security/assets/37830884/99de8d2b-d166-40b2-8df7-dca55efdf3b1)
![Screenshot 2023-11-24 183810](https://github.com/fuatakgun/eufy_security/assets/37830884/d1eb215b-cb01-40a7-a79c-1d8dc8a54464)
![Screenshot 2023-11-24 183831](https://github.com/fuatakgun/eufy_security/assets/37830884/4c20192a-abac-4580-b5d3-137ec8f6a121)

**Comment by fuatakgun** [comment]
Just enable them

**Comment by mattsmithuk** [comment]
They are not disabled. They are not available at all. If I could enable them, I would have already

**Comment by DerHerzog7** [comment]
Also having this issue

**Comment by crom80** [comment]
I 've the same problem. Before some days a had problems to set the guard Mode at one camera. The ither camera this function was there. So I deleted the eufy integration an add a new eufy integration. After this, my support fir guard mide was gone. Its nit available anymore.

**Comment by fuatakgun** [comment]
@mattsmithuk , so you have checked entity settings page and they are enabled??

**Comment by crom80** [comment]
@fuatakgun: Thanks for this hint. This solves my problem. The eufy show hidden entities. I ve selected the guard Mode entity and was able to activate this entity. Now I can change the guard Mode. Thanks a lot

**Comment by mattsmithuk** [comment]
@fuatakgun for some reason they were disabled by the integration. I've been successfully able to manually enable each of them.
