### ISSUE TITLE
Can not add S330 Doorbell

### ISSUE THREAD

**Issue by Pleeriezer** [fuatakgun/eufy_security#1003]
Hello,

I have HAS 2023.11.2 and Eufy security add on ver 1.3.0 for my Eufy S330 Doorbell

Installed it and configure it with no errors : 

https://i.imgur.com/N3Zh4Dm.jpg

https://i.imgur.com/1EQ3TyT.jpg

https://i.imgur.com/AVZQNvS.jpg

Then  I go to then go to Settings → Devices and add integration for Eufy Security to add the accessories but I am getting an error :  

https://i.imgur.com/1mjuuyF.jpg

It says that the device can not added to the userinterface.
It must be adressed in the YAML config

How can I add the Eufy doorbell?

**Comment by fuatakgun** [comment]
Please follow the exact steps listed on readme.

And disable 2fa to ease the initial process

**Comment by Pleeriezer** [comment]
Thanks for the quick replt.

At 5 the manual is saying 5- Put Eufy Security Add-on IP Address (127.0.0.1 for Supervised installation) and configured port (default 3000) and click Submit.

I can not fill in a IP?

https://imgur.com/rndkq1t

At 7 the manual says to put the IP from the RTSP Simple Server Add-On in I can not fil it in?

https://imgur.com/fH6dWry

**Comment by Pleeriezer** [comment]
Thanks for the reply.

In the readme it says :  

5- Put Eufy Security Add-on IP Address (127.0.0.1 for Supervised installation) and configured port (default 3000) and click Submit.

I can not put a IP in?

https://imgur.com/fH6dWry

At 7 :  

7- If you have installed RTSP Simple Server Add-On, please put its IP Address and Port into Integration Configuration page.

The same problem?

Thanks and greetings,

Erik.

**Comment by fuatakgun** [comment]
1. I want you to read the README carefully, you are adding the wrong integration (eufy), you should add Eufy Security.
![image](https://github.com/fuatakgun/eufy_security/assets/11085566/25542e98-9122-4e66-96e1-9017f32b36a9)

2. Disable 2FA using your eufy mobile app other way around, we might face different issues, you can enable them back later on,

**Comment by fuatakgun** [comment]
Order wise
1. Install Eufy Security Add-on
2. Install RTSP Simple Server Add-on
3. Install Eufy Security Integration

**Comment by Pleeriezer** [comment]
Thanks for pointing me at the right direction!
I made a mistake by installing the wrong add on.

Installed it now but getting a error message : 

https://imgur.com/jsv1xRg

Can you tell me what is wrong?

**Comment by Pleeriezer** [comment]
Hello Fuat,

I am still having problems and I don't know how to solve them would you help me?

Thanks and greetings Erik

Met vriendelijke groet,

Erik Kottier
