### ISSUE TITLE
Eufy Doorbell E340 entities missing

### ISSUE THREAD

**Issue by frenchish** [fuatakgun/eufy_security#1005]
Go to Settings -> Devices & Services -> Eufy Security integration -> Go into devices -> Select doorbell 

![image](https://github.com/fuatakgun/eufy_security/assets/12625698/74d169e0-06a2-47e7-9e9f-0be9d414b5d8)

In the Image, I was expecting to see more sensors available for the doorbell am I missing something?

DoorBell: E340 dual (T8214)
Hub: Homebase 3 (doorbell connected to this)

Thanks

**Comment by Thazar** [comment]
I can confirm this. Same on my doorbell.
![image](https://github.com/fuatakgun/eufy_security/assets/35781515/3278073f-4996-4ced-a474-f7c52fd126c4)

**Comment by fuatakgun** [comment]
please work with bropat for new device support requests, integration would get them automatically afterwards.
