### ISSUE TITLE
s220 cam don't work

### ISSUE THREAD

**Issue by d4nm0** [fuatakgun/eufy_security#1007]
Hello, 
I have two solar s220 cam. I can't get them to work properly.
They both display fixed images. 
But the image doesn't change. 
![image](https://github.com/fuatakgun/eufy_security/assets/20597792/af793f96-5997-444f-b54f-e72671e74f33)
![image](https://github.com/fuatakgun/eufy_security/assets/20597792/ccda1724-57f6-4a6e-939d-c35c2226e115)

**Comment by fuatakgun** [comment]
create a proper bug record
