### ISSUE TITLE
Download video

### ISSUE THREAD

**Issue by hrqiang** [fuatakgun/eufy_security#1009]
**Is your feature request related to a problem? Please describe.**
eufy-security-client has start stop download commands. I hope there is a way to download video.

**Describe the solution you'd like**
 e.g. whenever there is motion detect, download video.
Or I can setup a cron job download periodly.

**Describe alternatives you've considered**
Use ioBroker

**Additional context**
eufy-security-ws client.ts has start_download command, but not able to get it working.

**Comment by fuatakgun** [comment]
As far as i know, after latest encryption application from eufy, this is not possible anymore. Please double check with bropat first, if feasible, i would be happy to do it
