### ISSUE TITLE
days_since_last_charging stay -1

### ISSUE THREAD

**Issue by werbi64** [fuatakgun/eufy_security#1010]
hello,

since I fully charged my eufycam 2 Pro camera the status days_since_last_charging has remained at -1 for several days.

OS : 11.1
Supervised & core: 2023.11.3
Eufy Security ws Add-on Version: 1.7.1
Eufy Security Integration Version: 7.7.4

![Capture d’écran du 2023-11-24 19-06-22](https://github.com/fuatakgun/eufy_security/assets/118385034/a51ee0c7-2fd1-48ac-ae95-4ac511a8991b)

bonne soirée

**Comment by fuatakgun** [comment]
sorry, I do not know why this is happening and I cannot solve with no information.

You can enable debug logs, check if the value is `-1` coming from add-on or the integration is breaking the original value.

If the add-on is giving wrong information, inform bropat over his repository.
If integration is breaking this, create a proper bug record.
