### ISSUE TITLE
Connection to Eufy Security add-on is broken, retrying in background!

### ISSUE THREAD

**Issue by akicker** [fuatakgun/eufy_security#1020]
**Describe the bug**
Connection to Eufy Security add-on is broken, retrying in background!
Add-On only survives when Watchdog enabled! Else runs into **Killed** after some minutes

Hardware Information;
- Camera Model: EufyCam 2C

- Debug Logs from Home Assistant 
  Connection to Eufy Security add-on is broken, retrying in background!

- Protocol:
Timeout on /addons/402f1039_eufy_security_ws/stats request
10:03:19 – (FEHLER) Home Assistant Supervisor
Failed to to call /addons/402f1039_eufy_security_ws/stats -
10:02:50 – (FEHLER) Home Assistant Supervisor 

- Logs from Eufy Security Add-on (if Watchdog is disabled):
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-11-28 13:50:37.860  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-11-28 13:52:30.623  INFO  Connected to station T8010N2321140CB1 on host 10.0.0.31 and port 12690 
2023-11-28 13:52:45.150  INFO  Disconnected from station T8010N2321140CB1 
2023-11-28 13:54:10.260  INFO  Connected to station T8010N2321140CB1 on host 10.0.0.31 and port 17087 
2023-11-28 13:54:34.956  INFO  Push notification connection successfully established 
**Killed**
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

- System Info
Core 2023.11.3
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231030.2
Addon: 1.7.1

**Comment by fuatakgun** [comment]
You need to check OS logs to understand why it is killed and work with bropat to find out if he can help, but i cannot
