### ISSUE TITLE
Add on crashes on boot "Killed"

### ISSUE THREAD

**Issue by handcraftedcc** [fuatakgun/eufy_security#1024]
**Describe the bug**

Add on crashes on boot (see log below). "Killed"

**To reproduce**

Start addon
In logs you will see some boot info and then "killed"

**Expected behavior**

Add on boots and stays on

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: 2023.11.3
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: 7.7.4

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue

2023-11-29 08:41:52.120 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-29 08:41:52.122 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
Documentation
Configuration
Log
eufy-security-ws
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-11-29 14:23:10.335  DEBUG [undefined.constructor] Loaded API 
{
  apieBase: 'https://security-app.eufylife.com',
  country: 'US',
  username: 'redacted 
  persistentData: {
    user_id: 'redacted 
    email: 'redacted 
    nick_name: 'dom***',
    device_public_keys: {},
    clientPrivateKey: 'redacted 
    serverPublicKey: 'redacted 
  }
}
2023-11-29 14:23:10.614  DEBUG [EufySecurity._initializeInternals] Load previous login_hash 
{
  login_hash: 'redacted 
}
2023-11-29 14:23:10.887  DEBUG [EufySecurityServer.start] Starting server on host 0.0.0.0, port 3000 
2023-11-29 14:23:10.958  INFO  [EufySecurityServer.start] Eufy Security server listening on host 0.0.0.0, port 3000 
2023-11-29 14:23:11.000  DEBUG [HTTPApi.login] Login and get an access token 
{
  token: null,
  tokenExpiration: null,
  options: {
    force: false
  }
}
2023-11-29 14:23:11.076  DEBUG [HTTPApi.request] Api request 
{
  method: 'post',
  endpoint: 'v2/passport/login_sec',
  responseType: undefined,
  token: null,
  data: {
    ab: 'US',
    client_secret_info: {
      public_key: redacted
    },
    enc: 0,
    email: 'redacted
    password: '[***]',
    time_zone: -21600000,
    transaction: 'redacted 
  }
}
Killed
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

- Would you share your device with me in case further debugging required? (Yes/No): ?

**Comment by akicker** [comment]
same problem see Connection to Eufy Security add-on is broken, retrying in background! #1020

**Comment by handcraftedcc** [comment]
@akicker did you get yours figured out?

**Comment by akicker** [comment]
No, problem still pending :-(Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Handcrafted Media ***@***.***> Datum: 01.12.23  23:16  (GMT+01:00) An: fuatakgun/eufy_security ***@***.***> Cc: Guss ***@***.***>, Mention ***@***.***> Betreff: Re: [fuatakgun/eufy_security] Add on crashes on boot "Killed" (Issue
  #1024) 
@akicker did you get yours figured out?

**Comment by fuatakgun** [comment]
Please reach out to bropat if you are sure that your operating system is now killing the add-on for some other reason

**Comment by handcraftedcc** [comment]
After giving my instance more ram and CPUs it fixed the issue!

**Comment by akicker** [comment]
Disabling SQLite Web Addon did help 👍

**Comment by fuatakgun** [comment]
I have SQLite add-on and it is not causing any issues.

So, please check your OS, add-on is being killed externally.
