### ISSUE TITLE
HA login notification after click preview

### ISSUE THREAD

**Issue by meden199** [fuatakgun/eufy_security#103]
I followd the complete installation.
Now i have on my lovelace a Screenshot from the last capture from my eufy doorbell camera.
When I  click on the Screenshot HA shows a failure message: ### "Login attempt or request with invalid authentication from"  and nothing happens.

All entity's are loaded and are OK.

**Comment by fuatakgun** [comment]
root cause is unknown, following over here: https://github.com/fuatakgun/eufy_security/issues/102
closed as duplicate
