### ISSUE TITLE
Eufy Security Base Alarm Trigger not working in Automation

### ISSUE THREAD

**Issue by Adam-Kay** [fuatakgun/eufy_security#104]
### Describe the bug
Eufy Alarm base is not triggering inside an automation I made. The action was meant to flash a light, as a test. This light does flash correctly if I press "Run Actions" so I know it's not the light having the problem.

### To Reproduce
1. Go to _Configuration -> Automations_
2. Click on _Add Automation_
3. Click on _Start with an empty automation_
4. Add a trigger:
    **Type**: Device
    **Device**: Eufy Base
    **Trigger**: Eufy Base Triggered
    **Duration**: 00:00:00
5. Add an action:
    **Type**: Device
    **Device**: Office Light (or any other light)
    **Action**: Flash Office Light
6. Click _Run Actions_ to test. Lights should flash.
7. Save automation and exit
8. Trigger alarm on Eufy Base either with a Service Call or by manually triggering it by standing in a motion sensor in an alarmed state. Neither of these methods will trigger the automation and the lights will not flash for some reason.
    
### Expected behavior
The actions should run when the alarm is triggered by any means. In this case, the Office Light or some other light should flash.

### Screenshots
![image](https://user-images.githubusercontent.com/10010491/140655000-d6dc033c-ea94-418e-b356-b194c5706621.png)

![image](https://user-images.githubusercontent.com/10010491/140655016-9fe549a2-f5dd-4c3a-859d-d3f0bee72273.png)

### Hardware Information about Home Assistant
Home Assistant 2021.11.1 running on Raspberry Pi 3b

### Additional context
It is my first time really doing anything with HA so I can appreciate perhaps I have configured something wrong, it would be good to figure out if I have misconfigured the automation somehow.
Edit: The automation seems to work if I set the trigger to ".. armed home" or "... armed away", just not when "Triggered", which I assume means the alarm triggered

**Comment by fuatakgun** [comment]
I need to start listening events from here: https://github.com/bropat/eufy-security-ws#alarm-event

**Comment by fuatakgun** [comment]
should be fixed latest version released minutes ago

**Comment by fuatakgun** [comment]
![image](https://user-images.githubusercontent.com/11085566/142939790-32dd7949-a741-46f2-98b4-9658bc807e5f.png)

**Comment by Adam-Kay** [comment]
Hi! This is working more than before now, but unfortunately my automation is not triggering when the alarm is triggered, but rather when I punch the code into the Eufy panel to turn the alarm off.

Do you know what might be going on?
