### ISSUE TITLE
Cannot lock or unlock T8520

### ISSUE THREAD

**Issue by kebel87** [fuatakgun/eufy_security#1040]
Whenever I try to lock or unlock my 8520 smart lock, I get an error message and lock doesn't lock/unlock. However, the state is reported correctly, it's only the commands that doesn't work.

Try to lock or unlock

**Expected behavior**

The smart lock should lock/unlock.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 
Version	core-2023.12.3
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
User	root
Virtual Environment	false
Python Version	3.11.6
Operating System Family	Linux
Operating System Version	6.1.63-haos
CPU Architecture	x86_64
Timezone	America/Toronto
Configuration Directory	/config

- Home Assistant Core Version: 
- Eufy Security Add-on Version: Current
- Eufy Security Integration Version: Current

Hardware Information;
-t8520 smart lock

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 08:11:38 (1 occurrences)
Last logged: 08:11:38

[139627264832064] {'type': 'result', 'success': False, 'messageId': 'device.set_property.f41ee406df4a470a81708de86558d076', 'errorCode': 'unknown_error'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 112, in _async_unlock
    await entity.async_unlock(**_add_default_code(entity, service_call))
  File "/config/custom_components/eufy_security/lock.py", line 59, in async_unlock
    await self.product.set_property(self.metadata, False)
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 64, in set_property
    await self.api.set_property(self.product_type, self.serial_no, metadata.name, value)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 187, in set_property
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_property, domain=product_type.name, serial_no=serial_no, name=name, value=value))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 333, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'device.set_property.f41ee406df4a470a81708de86558d076', 'errorCode': 'unknown_error'}

  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

2023-12-17 13:11:38.295  ERROR Unexpected error 
 Error  Public key is not valid for specified curve
details:
{
  code: 'ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY'
}
error stack:
• errors:405 NodeError
    node:internal/errors:405:5

• diffiehellman:167 dhComputeSecret
    node:internal/crypto/diffiehellman:167:11

• utils.ts:549 getAdvancedLockKey
    usr/src/app/node_modules/eufy-security-client/src/p2p/utils.ts:549:25

• utils.ts:669 getLockP2PCommand
    usr/src/app/node_modules/eufy-security-client/src/p2p/utils.ts:669:39

• station.ts:4419 lockDevice
    usr/src/app/node_modules/eufy-security-client/src/http/station.ts:4419:46

• eufysecurity.ts:1149 setDeviceProperty
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:1149:31

• task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5

• message_handler.ts:209 handle
    usr/src/app/node_modules/eufy-security-ws/src/lib/device/message_handler.ts:209:17

• server.ts:125 receiveMessage
    usr/src/app/node_modules/eufy-security-ws/src/lib/server.ts:125:21

- Would you share your device with me in case further debugging required? (Yes/No):

Yes/No, depending on when debugging would occur.

**Comment by koolin** [comment]
I also have this same issue with a T8520 (S230)

**Comment by fuatakgun** [comment]
please check with bropat about eufy-security-ws error, integration cannot handle errors if they are failing on add-on.
