### ISSUE TITLE
Support for 'Indoor Cam S350' - T8416

### ISSUE THREAD

**Issue by colinmeer** [fuatakgun/eufy_security#1042]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem, I do not think the 'Indoor Cam S350' was ever supported in this add-on.

**Describe the solution you'd like**
I would like to be able to have the same options as the other camera's that are supported by this add-on.

**Describe alternatives you've considered**
I have not considered alternatives because I do not think there are?

**Additional context**
[Link to the official eufy product page](https://eu.eufy.com/products/t8416321)

**Comment by cheesefather** [comment]
I second this - please add support, mine is connected via Wifi rather than the HB3 and only shows debug sensors - thanks.

**Comment by fuatakgun** [comment]
please work with bropat over here: https://bropat.github.io/eufy-security-client/#/supported_devices
