### ISSUE TITLE
[Bug!] Cannot install Eufy integration

### ISSUE THREAD

**Issue by lancercncs1** [fuatakgun/eufy_security#1043]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

I had been able to use the Eufy security integration and view my streams (albeit slowly since I do not use WebRTC). for my outdoor camera. However, the integration entities and camera feed stopped working one day. The HA integration add-on states that it "failed to set up"

1. Go to Settings ---> Devises & Services --> 
2. The Eufy Security add-on fails to set up

**Expected behavior**

The integration should install and the entities + camera feed should be working.
**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervise- d - Core):   Home Assistant OS 11.2, 	supervisor-2023.12.0
- Home Assistant Core Version: core-2023.12.3
- Eufy Security Add-on Version:  1.3.0
- Eufy Security Integration Version: It cannot install

Hardware Information;
- Camera Model:
 Eufy Security Solocam S40 

- Live Streaming Protocol (RTSP/P2P): 
RTSP although (apparently) I am unable to extract the RTSP stream URL for this particular model.

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 9:42:30 AM (1 occurrences)
Last logged: 9:42:30 AM

Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 71, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 147, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 324, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.b5c06399464343b7a367a4cd69b0f3fb', 'errorCode': 'schema_incompatible'}

- Would you share your device with me in case further debugging required? (Yes/No):
Only as a last resort.

**Additional context**

I think that's everything. I greatly appreciate your help with this issue. Thank you!

**Comment by fuatakgun** [comment]
Update to add-on latest version

**Comment by lancercncs1** [comment]
This was indeed the issue. Thank you very much fuatakgun!
