### ISSUE TITLE
Config flow chokes on reconfigure (v 8.0)

### ISSUE THREAD

**Issue by ronaldt80** [fuatakgun/eufy_security#1049]
**Describe the bug**

When attempting to reconfigure the integration there is an error message (server error 500) on the config flow

**To reproduce**

1. Go to integrations
2. Click on eufy security 
3. Scroll down to configure 

**Expected behavior**

The normal config flow

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- HA-OS 11.2
- Home Assistant Core Version: 2023.12.3
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: 8.0.0

Hardware Information;
- Camera Model: doorbell T8210

- Live Streaming Protocol (RTSP/P2P):  p2p

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
-
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 09:36:39 (4 occurrences)
Last logged: 09:49:24

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 255, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1868, in async_create_flow
    return handler.async_get_options_flow(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/config_flow.py", line 62, in async_get_options_flow
    return EufySecurityOptionFlowHandler(config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/config_flow.py", line 33, in __init__
    vol.Optional(ConfigField.rtsp_server_port.name, default=self.config.rtsp_server_port): cv.port,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: rtsp_server_port
```

  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
N/A
- Would you share your device with me in case further debugging required? (Yes/No):
Not device related

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.
![Screenshot_20231224-094228](https://github.com/fuatakgun/eufy_security/assets/53364332/f07ff917-ffa5-462a-bf12-ee771234c959)

**Comment by V4ler1an** [comment]
I came to report the same issue. Had to restore from backup to roll back after installing v8. In addition, I noticed my P2P > RTSP streaming failed on all cameras. Clicking the link to start stream would go to PREPARING for a few seconds then back to IDLE. Due to a port conflict I setup my RTSP Simple Server add-on with port 8558 instead of 8554. I wondered if this had created a problem with this update?

**Comment by chris173972** [comment]
![Screenshot 2023-12-25 013642](https://github.com/fuatakgun/eufy_security/assets/5174337/270afcd8-ada2-479a-b660-c959d3bdbdaf)

**Comment by fuatakgun** [comment]
Uninstalling and installing back should fix it until i can fix the issue.

**Comment by braddunlap** [comment]
> Uninstalling and installing back should fix it until i can fix the issue.

Thanks, but unfortunately this did not work for me.

Has anyone else got this workaround to work?

**Comment by csese0701** [comment]
Not working for me by uninstalling and installing again.

**Comment by davmantor** [comment]
Same here! Stream is working just fine but can't open the config to expose things like battery %

**Comment by V4ler1an** [comment]
> Uninstalling and installing back should fix it until i can fix the issue.

I too had a problem rolling back. Thought I must have done something wrong. At first I tried a partial restore of just the Eufy Security add-on using the default HA built in backup but the add-on still said v8. I restored a full VM backup in the end.

**Comment by fuatakgun** [comment]
If you want to rollback, do it via hacs, v8 is about custom integration not add-on.

**Comment by V4ler1an** [comment]
Ok thanks, doesn't look like HACS custom integrations are available for partial backup restore so I'll try the integration uninstall reinstall in future.

**Comment by tne7laa** [comment]
+1 Got the same problem. 
What solved for me is:
- in HACS go to Eufy Security integration and click for 'Redownload' and select version 7.7.4
- Restart Home Assistant

**Comment by mhl66** [comment]
Sorry, 7.7.4 to 7.7.1 have the same problem. For my EUFY Homebase with four cameras (eufyCam 2C), all the buttons are broken (24 Entities are not available ("Reset Alarm", "Start P2P Stream" ... "RTSP Stream URL"...) in the integration, they are hidden.

**Comment by 4webat** [comment]
Hello same problem here, version 7.7.4 doesnt work! And version 8.0 doesnt work :(

**Comment by ronaldt80** [comment]
> Sorry, 7.7.4 to 7.7.1 have the same problem. For my EUFY Homebase with four cameras (eufyCam 2C), all the buttons are broken (24 Entities are not available ("Reset Alarm", "Start P2P Stream" ... "RTSP Stream URL"...) in the integration, they are hidden.

You can enable them easily

**Comment by mhl66** [comment]
> > Sorry, 7.7.4 to 7.7.1 have the same problem. For my EUFY Homebase with four cameras (eufyCam 2C), all the buttons are broken (24 Entities are not available ("Reset Alarm", "Start P2P Stream" ... "RTSP Stream URL"...) in the integration, they are hidden.
> 
> You can enable them easily

No, unfortunately not - they are hidden, because they are **not available** (i.e. can´t be enabled, of course).

@ronaldt80 **That´s why I wrote "broken"**, you know... :-(

**Comment by fuatakgun** [comment]
@ronaldt80 , I am banned from home assistant community for a month for some other irrelevant point, so please expect no response from me over the forum :-)

I will work on fixing these stuff

**Comment by V4ler1an** [comment]
Thank you Fuat, we are most grateful. Happy New Year to you :)

**Comment by ronaldt80** [comment]
> @ronaldt80 , I am banned from home assistant community for a month for some other irrelevant point, so please expect no response from me over the forum :-)
> 
> I will work on fixing these stuff

A one month ban? Sounds a bit harsh, take it that's why you packed your bags? Anyway,  didn't see this response until now but dropped you an email with a big thanks for all your efforts and support over the years. Hope we can continue to benefit from your drive on GitHub.

**Comment by hillshome** [comment]
Same issue here rolling back doesn't work. Any update on the fix?

**Comment by fuatakgun** [comment]
get v8.0.1, it is finally fixed

**Comment by ronaldt80** [comment]
Brilliant! It works. Finally able to turn of the native streaming again!

**Comment by V4ler1an** [comment]
> get v8.0.1, it is finally fixed

Sorry but this didn't go well for me Fuat. None of my streams work now and I can see it's because the 'Stream URL' has returned to the default port of 8554 when I was using 8558 to avoid a port conflict:
![Stream URL](https://github.com/fuatakgun/eufy_security/assets/134781183/35aa3ee3-9968-4261-b3e9-ad1380550377)

My RTSP Simple Server add-on is configured as this. Yet you can see from the logs when I restart it, it ignores it and still starts up running on 8554: I've tried to change the port to something different then back to 8558 but no change. Also tried full HASSIO restarts.
![image](https://github.com/fuatakgun/eufy_security/assets/134781183/55e5c0a1-6ed6-4e2e-aad6-645b5d26c172)
![image](https://github.com/fuatakgun/eufy_security/assets/134781183/0c9a6b58-cf99-4e25-88bc-3df4a0b839fb)

I tried adding the port to the end of the IP address in eufy security hub configuration but it just appends 8554 to the URL:
![image](https://github.com/fuatakgun/eufy_security/assets/134781183/c58db565-a28d-4bf0-aa79-9f9dc1d04364)
![image](https://github.com/fuatakgun/eufy_security/assets/134781183/a6089b70-016e-4b8f-8631-5f7970e9ac21)

Also my web sockets add-on still says 1.7.1, am I missing something or is that expected?
![image](https://github.com/fuatakgun/eufy_security/assets/134781183/ae0fa1b6-01b1-40c2-ad9c-7649e1ab0255)


I'm going to roll back, any suggestions?

**Comment by fuatakgun** [comment]
@V4ler1an , you are not supposed to use rtsp add-on anymore, check readme

**Comment by hankfic** [comment]
Having the same problem as V4ler1an. I'm using the RTSP add-on as per the readme suggests due to the wired doorbell cam being P2P only.

**Comment by V4ler1an** [comment]
My Eufy P2P cameras are now back working through my WebRTC lovelace cards. This time, out of caution I uninstalled the RTSP Simple Server add-on before running the update.

What was a little frustrating... I didn't pick up on the fact RTSP Simple Server was no longer a requirement because when originally clicking on the Eufy Security integration in HACS, where it says 'Pending update' highlighted in blue. The readme still says v7.7.4 at the top and still references the requirement for the RTSP Simple Server. None of the v8.0.1 changes are in those notes.

**Comment by V4ler1an** [comment]
> @V4ler1an , you are not supposed to use rtsp add-on anymore, check readme

One useability issue I would like to highlight at least where using the WebRTC cards is concerned (through P2P > gotortc). Previously if I had just opened a dashboard page with a WebRTC card on it and clicked 'Start P2P Stream' the feed would come up on the card fairly quickly with no further input, as long as I didn't wait to long after first opening the dashboard page. Now I notice that after starting the stream I must also click the 'error' link in the top right of the WebRTC card or I wait quite a long time for the stream to display. This threw me at first, making me think it wasn't working. Is there any way this behaviour could be improved?  E.g... open dashboard page, click start stream, no further input needed.
