### ISSUE TITLE
Eufy Camera Automations

### ISSUE THREAD

**Issue by snyhomesec** [fuatakgun/eufy_security#105]
Hi. 

Firstly I want to say thank you for making these integrations possible. We would all be lost without it.
Ok, so my issue.

I have 2 Eufy camera's setup on the Eufy app and they are now visible within Home Assistant using your add on. The problem I have is with automation.

I am trying to setup an automation where; _If motion is detected, switch a light on_. However it does not seem to be functioning. 

I believe I have followed the correct setup instructions and have read similar issues, however my issue seems to be slightly different. 
Here is a screenshot of my Sensors from one of the cameras:

![image](https://user-images.githubusercontent.com/93717940/141106984-ad505da1-a3f6-443f-9772-9ec59b378369.png)

When motion is detected by the cameras (either by person sensor or motion sensor), the states do actually turn to `True`, indicating that Home Assistant is receiving the notifications. But when trying to use this as a Trigger in automations, nothing happens. I have also tried using a different device to trigger the automation (such as a door sensor) and the automation works fine.
Here are screenshots of my automation settings:

![image](https://user-images.githubusercontent.com/93717940/141107694-b953ee1b-b701-43a3-a7e2-2c437a0dd667.png)

![image](https://user-images.githubusercontent.com/93717940/141108378-36ee77c4-d600-4273-a5c9-850eadd23d9b.png)

I'm not sure where I could be going wrong so I'm wondering if you can help.

**Hardware Information about Home Assistant**
Running Home Assistant OS 6.6, on a Raspberry PI 3 Model B+

**Hardware Information about Cameras**
2X Eufy Cam 2C
Eufy Homebase2

**Additional context**
- I have created a separate account for HA integrations, and shared the cameras with the new account.
- The "eufy_security_addon" log shows no issues and: "**INFO** Push notification connection successfully established"

If there's anything else I've missed out, please let me know.

Thank You

Sny

**Comment by fuatakgun** [comment]
there is an issue in integration about states, please use like this:

![image](https://user-images.githubusercontent.com/11085566/141134951-6405931b-16e1-436a-9696-6e161d846359.png)

**Comment by snyhomesec** [comment]
**Perfect!!**

Issue resolved. Thank you for your assistance with that. I appreciate you guys alot.

Sny
