### ISSUE TITLE
Add Support for E340 Floodlight Camera and Doorbells? (T8425 and T8214)

### ISSUE THREAD

**Issue by DNARNA** [fuatakgun/eufy_security#1052]
Thank you so much for this integration! I just got three E340 floodlight cameras and have the S380 Homebase 3 and two E340 doorbell cameras but none of these are supported yet. Any chance of adding these so I can integrate them into HA?

Thanks!

**Comment by playerfreak** [comment]
With the s380 giving the cam 24/7 recording, hopefully we get streaming to HA

**Comment by DNARNA** [comment]
I hope so!  I see that https://github.com/bropat/eufy-security-ws is stating as of today that E340 support will be implemented in the next release!  Hopefully the doorbell camera isn't far behind.

**Comment by fuatakgun** [comment]
whenever eufy-security-client and eufy-security-ws are updated and released, you would get the new functionality, nothing needed from my end
