### ISSUE TITLE
Is 7.7.4 to 8.0.0 a move to the beta?

### ISSUE THREAD

**Issue by Colorado4Wheeler** [fuatakgun/eufy_security#1054]
I'm using 7.7.4 and while doing my regular HACS updates I saw this add-on was wanting to update but did read "This change relies on go2rtc configuration. Please wait until a new version is released and do not get from master", so I'm assuming that 8.0.0 is still in development and I should not pull the trigger.

My question is more around the go2rtc and other changes - will it be a simple upgrade to 8.x when it's finalized or will it be better to just remove the current version entirely and start over?  That warning sound ominous!  The old version used RTSP Simple Server so I don't know if it's a big deal or not.

Thanks for this amazing extension, I have a LOT of things tied to it so I want to be deliberate in updating!

**Comment by dan-riley** [comment]
You want to use this version of WebRTC instead (you can add it as a custom repository in HACS, and uninstall the old one):  https://github.com/fuatakgun/WebRTC

This post and some comments later on are useful: https://community.home-assistant.io/t/eufy-security-integration/318353/2056

**Comment by fuatakgun** [comment]
it is time to move to version 8 if you are interested in more stable streaming, if it is already good enough for you, stay with v7 but it will not be updated.
