### ISSUE TITLE
Feature Request: Add support for Eufy Solar Wall Light Camera S120

### ISSUE THREAD

**Issue by menno-h** [fuatakgun/eufy_security#1058]
Hi,

Thanks for this integration!

I have an Eufy Solar Wall Light S120. After adding the Eufy Security Integration I do see my device in Home Assistant. However there are no controls and the sensors are limited to: Debug (device) and Debug (station). There is no "Motion detected" etc. like other supported devices.

Can you add sensor "Motion detected" and controls "light: on/off/toggle" and "Guard Mode: Home/Away/Schedule/Custom...." , if the latter is possible without a Home Base,

Kind regards,
Menno

**Comment by fuatakgun** [comment]
Check with eufy-security-client library to include support for new devices
