### ISSUE TITLE
the preset positions of the S340 should interact with other devices

### ISSUE THREAD

**Issue by googie0815** [fuatakgun/eufy_security#1059]
**Is your feature request related to a problem? Please describe.**
If a motion sensor or another camera detects movement, the camera should move to one of the 4 preset positions.

**Describe the solution you'd like**
I have 2 motion sensors in the garden, 2 SoloCam S220 and 1 SoloCam S340. For example, if motion sensor #1 detects movement, the S340 should move to the preset position 2. If the SoloCam S220 #2 detects a movement, the S340 should move to the preset position 3.

**Comment by 51av0sh** [comment]
Is this a bug or a feature request? I didn't know this integration had that capability.

**Comment by fuatakgun** [comment]
I do not understand what is the ask here? you can setup automations on home assistant or setup inside eufy app.
