### ISSUE TITLE
Sensors and Images are not updating as expected.

### ISSUE THREAD

**Issue by MechEng70** [fuatakgun/eufy_security#106]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
The Eufy App provides notifications on events.  There are three settings for notifications:

1. Most Efficient - only text
2. Full Effect - text, then thumbnail (if applicable)
3. Include Thumbnail - text AND thumbnail (if applicable)

Over the past several days, have tried number 2 and 3 for 24 periods.  There is not consistently in when the images from either or any of the following products arrive in HA.
T8124 - (QTY: 3) - SoloCam S40
T8200 - (QTY:1) - Doorbell
T8112 - (QTY: 3) - eufyCamE
T8002 - (QTY: 1) - HomeBase E

Security Settings: Home and Away
HomeBase E
Home: Record Video and Push Notification are set for outdoor (qty: 1) T8112
Away: Record Video and Push Notification are set for all (qty: 3) T8112
Doorbel, SoloCam S40l:
Home: Record Video and Push Notification are set (QTY: 3) T8124 and (QTY: 1) T8200

**Expected behavior**
Expect the sensors to update based on motion or person detect to correspond to the Eufy Official app.  

**Screenshots**
Screen depicting the S40s not updating on HA:
![Screenshot_20211112-130612](https://user-images.githubusercontent.com/11697710/141535701-de3dff70-fd94-44e0-be54-1709cf3cff86.jpg)

Eufy App
![Screenshot_20211112-130600](https://user-images.githubusercontent.com/11697710/141535713-7842f458-8e35-4f6e-992e-258951466a6a.jpg)

Screenshot depicting the Backyard updated and only the backyard sensor updated:
![Screenshot_20211112-130707](https://user-images.githubusercontent.com/11697710/141535792-942250f1-0cab-467a-a5a6-ec6345a6483d.jpg)

Eufy App with updated backyard:
![Screenshot_20211112-130659](https://user-images.githubusercontent.com/11697710/141535838-3540dad4-442b-44db-bf10-0b4a377fe814.jpg)

**Hardware Information about Home Assistant
Home Assistant 2021.11.1
Operating System Family | Linux
Operating System Version | 5.4.0-90-generic
CPU Architecture | x86_64
Host Operating System | Ubuntu 20.04.3 LTS
Update Channel | stable
Supervisor Version | supervisor-2021.10.8

**Comment by fuatakgun** [comment]
i should debug this locally to understand if these events are coming to add-on. If they are not coming, we should ask from @bropat over here: https://github.com/bropat/eufy-security-client

if they are coming, I should fix this.

Can you also check add-on logs? Please start with a clean slate, restart add-on and reload integration later on.

**Comment by MechEng70** [comment]
Will do.  However, I just checked after loading the latest addon and the motion and person detection is working.  
I will change the log capability and let it run to see if there is any other issues.

**Comment by MechEng70** [comment]
Latest update is working.
