### ISSUE TITLE
Unable to cofigure integrationn

### ISSUE THREAD

**Issue by 51av0sh** [fuatakgun/eufy_security#1063]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

I'm unable to configure the integration after adding it. I've tried removing the integration and ad-on, restarting and adding back. When I click on Configure I get:

> Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

[home-assistant_eufy_security_2024-01-03T03-03-49.485Z.log](https://github.com/fuatakgun/eufy_security/files/13815394/home-assistant_eufy_security_2024-01-03T03-03-49.485Z.log)

Looking at the logs it would appear to be a port conflict. I see "AttributeError: rtsp_server_port" 

**To reproduce**

1. Go to 'Integrations'
2. Click on 'Eufy Security'
3. Click Configure

**Expected behavior**

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: 2023.12.4
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: 8.0.0

Hardware Information;
- Camera Model: Indoor Cam Mini

- Live Streaming Protocol (RTSP/P2P): n/a

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output): 

- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by 51av0sh** [comment]
In case it matters I'm using the WebRTC-Camera integration as well. I also have docker Wyze Bridge installed and I think there might be a conflict somewhere. I'm attaching a screenshot of the ports that ad-on is using but I did have to change the RTSP port for the docker Wyze bridge as something else I have was using that port already (I assumed it was the WebRTC-Camera integration).

**Comment by ronaldt80** [comment]
Identical to #1049 , please close
