### ISSUE TITLE
mse: streams: streams: unsupported scheme: [Serial No] error

### ISSUE THREAD

**Issue by Craig-97** [fuatakgun/eufy_security#1064]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**
Home assistant camera streaming from 2K Doorbell or 2C Pro camera no longer works. I haven't changed anything from my side of things and it has stopped working showing the error in the below screenshot.

1. eufy securty add-on installed
2. eufy-security-ws installed with homebase serial no configured
3. 127.0.0.1 address configured with Eufy Security add on
4. All devices are shown as expected.
5. Try to start P2P stream on any device and see the below error.

![image](https://github.com/fuatakgun/eufy_security/assets/41014229/eb5635e6-aa45-423b-974a-bca2bc0dbb77)

**Expected behavior**

Live feed shows from the cameras 

**Live Streaming Protocol (RTSP/P2P): **
P2P

**Debug Logs from Home Assistant**
[home-assistant_eufy_security_2024-01-03T17-49-26.586Z.log](https://github.com/fuatakgun/eufy_security/files/13821936/home-assistant_eufy_security_2024-01-03T17-49-26.586Z.log)

**Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):**

![image](https://github.com/fuatakgun/eufy_security/assets/41014229/28cbc57d-f7d7-40b9-ac0a-414ebe29b7a4)

**Comment by fuatakgun** [comment]
This means that the go2rtc version is not the required one and the existing one doesn't support the newly added streaming capability. Go2rtc might be overridden by manual add-on installation or bundled with frigate add-on. But this is beyond my limit, you have to figure it out yourself.

**Comment by Craig-97** [comment]
> This means that the go2rtc version is not the required one and the existing one doesn't support the newly added streaming capability. Go2rtc might be overridden by manual add-on installation or bundled with frigate add-on. But this is beyond my limit, you have to figure it out yourself.

Has there been an update somewhere that has broken this? 
All I want to do is show my cameras on a home assistant page and be able to press to show a live feed and to stop it. Is there a better solution than what I am doing?

**Comment by fuatakgun** [comment]
I am working on the remaining issue.
