### ISSUE TITLE
binary_sensor atributes states are not correctly set

### ISSUE THREAD

**Issue by Zeunas** [fuatakgun/eufy_security#107]
binary_sensor attributes need to be fixed, as for example a device_class: motion instead of reporting "Clear" or "Detected" is reporting "True" or "False" and which affects some automations that rely on the device_class: motion. 

One way to test this is when creating an automation, instead of selecting the trigger type to be a "State" but a "device" and in my case a Doorbell and its motion sensor - When the sensor is triggered the automation doesn't start.

This also happens with doorbell button push. 

I basically have to create separate binary_sensor templates with the binary_sensors of this Integration as triggers.

I'm a noob in this but I wonder if it's the actually formatting of the State? Or properties? Does all the data that go in these binary sensors need to be here? As far as I'm aware the camera attributes already include all of this data.

**Comment by fuatakgun** [comment]
yes, this is a known issue, but I do not want to publish and break it for all users, rather I will introduce a new option to fix this and enable it by default for new installations.

to overcome this, rather than relying device states, you should rely on state directly and check for True and False.

**Comment by Zeunas** [comment]
Got it! Thank you I'll keep an eye out for this update.

Yes I am relying on True and False states but rather have a second binary sensor to display clear or detected on Lovelace, with the template I mentioned above.

**Comment by fuatakgun** [comment]
i dont have any issue regarding to having correct state in frontend, they behave as motion sensors but their internal state is wrong. from CX perspective, it should be working fine

**Comment by mikedrawback** [comment]
This does not affect automations but I wanted the motion sensors to say 'Detected' or 'Clear' like they usually do. I tried fixing this with customization but the device class is already set as 'motion' by default. Why doesn't the frontend display them according to the device class?

**Comment by fuatakgun** [comment]
i have introduced a new config option to fix this, it is off by default, you should enable it so this will be fixed.

**Comment by mikedrawback** [comment]
looks good, thank you!
