### ISSUE TITLE
Install docu for 8.0.0 with all needed integrations and add-ons?

### ISSUE THREAD

**Issue by emufan** [fuatakgun/eufy_security#1070]
I used the version < 8.0.0 now for years, but I'm completely lost with the new set-up and completely missing an at least somehow guide for installation. Most probably I'm only too stupid, but as in more or less every step, I don't know, what to do or where is could be explained.

I installed the fork from WebRTC. O.k. (Idea, some marker or whatever else to distinguish the fork from master in HACS would be helpfull). But then?

![image](https://github.com/fuatakgun/eufy_security/assets/22775515/637c203f-61b9-4418-9eb4-c55ca1f6cb90)

?

And Do I need the add-on as well?

![image](https://github.com/fuatakgun/eufy_security/assets/22775515/32f524ed-c328-439e-97cf-0e833868c9bb)

?

And there I stopped, because I don't find any doc or howto set-up.

**Comment by ronaldt80** [comment]
You dont need the addon
