### ISSUE TITLE
T8410 lost Connection to HA

### ISSUE THREAD

**Issue by AnuGihub** [fuatakgun/eufy_security#1073]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**
Camera Pan&Tilt (T8410) lost Connection to HA.
after restart or unplugging the device the Device lost Connection to HA. Cant control anything over HA.
Also the Device lost connection after a few hour, when using it to much over HA.

**To reproduce**
enabled/ disabeld device over HA. Press PTZ over 30 times. After a while (few Hours) or unplug and replug it lost connection to HA.
Waiting for about 6 hours and it worked again.

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 
- Home Assistant Core Version: core-2024.1.2
- Eufy Security Add-on Version:  1.7.1
- Eufy Security Integration Version: 8.0.0

Hardware Information;
- Camera Model: T8410

- Live Streaming Protocol (RTSP/P2P): 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No):

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by fuatakgun** [comment]
to be honest, I have the same camera and having similar issues, but we need to generate debug logs from add-on and share them with bropat over his repository. This issue is not coming from integration. Can you share the logs with him?
