### ISSUE TITLE
Device Support: T8970

### ISSUE THREAD

**Issue by LucaBors** [fuatakgun/eufy_security#1076]
Hi, external siren t8970 has been relasead by Eufy. The device is recognized by Addon but there's no way to trigger siren.
The error is:
Failed to call service button/press. {'type': 'result', 'success': False, 'messageId': 'device.reset_alarm.07f255530a63477abe52ec25be4c9005', 'errorCode': 'device_not_supported'}

Thank you.

**Comment by fuatakgun** [comment]
Is it supported by eufy-security-client library, did you check?

**Comment by fuatakgun** [comment]
https://bropat.github.io/eufy-security-client/#/supported_devices

I do not think it is supported, check with eufy-security-client first
