### ISSUE TITLE
Smart Lock T8510

### ISSUE THREAD

**Issue by timleeds15** [fuatakgun/eufy_security#1079]
Smart lock T8510 works in Home Assistant but won't carry over into homekit via bridge integration

**Comment by fuatakgun** [comment]
This goes beyond my scope, I have no information about homekit, sorry.

Please check with home assistant community

**Comment by timleeds15** [comment]
This was an issue on my part, I fixed it this morning, I had to use a separate HASS Bridge for the lock instead of trying to add it with all my other devices. Once I did that, it added perfectly. Thanks!
