### ISSUE TITLE
File .ts and .log files in a dedicated folder

### ISSUE THREAD

**Issue by Zeunas** [fuatakgun/eufy_security#108]
Since I install this integration I've seen the the "config" folder being completely full of "eufy_security-Txxxxxxxxxxxxxxx.ts" and "ffmpeg-11111111-111111.log" files. 

1. Can these files be automatically stored in a dedicated eufy folder?
2. Can these files be purged from the system after x amount of time?

Unless I am missing something here I don't think there is an option to actually avoid having all of these files being created directly under "config" folder.

**Comment by fuatakgun** [comment]
Please go through readme file, i will soon remove file based p2p streaming support

**Comment by Zeunas** [comment]
I see! That's what you meant by the comment on your readme. Super! Thanks and keep up the good work ;)

**Comment by fuatakgun** [comment]
Yeap, install RTSP add on and you will be free of files and have much more faster streaming. Moreover, check WebRTC, your experience will be upgraded

**Comment by Zeunas** [comment]
I have it installed and enabled it on the integration but doesn't seem to work for the 1080 battery doorbell. I'll give it another try.

I suppose I can delete the .rs and .log files manually?
