### ISSUE TITLE
Add T8B00 Camera (SoloCam C210) Support

### ISSUE THREAD

**Issue by chris173972** [fuatakgun/eufy_security#1084]
**Is your feature request related to a problem? Please describe.**
Unable to view stream from T8B00 Camera (SoloCam C210). 

**Describe the solution you'd like**
Add T8B00 Camera (SoloCam C210) support to the project so the camera can be controlled and streamed within the project

![Screenshot 2024-01-14 175942](https://github.com/fuatakgun/eufy_security/assets/5174337/7e215fbf-6faa-4a25-be54-1b9efbfa50de)

**Comment by fuatakgun** [comment]
please work with bropat at add support for new devices
