### ISSUE TITLE
Guard Mode Names don't match

### ISSUE THREAD

**Issue by Ringo982** [fuatakgun/eufy_security#1086]
Hello
i have searched in open/closed issues but i cannot find an answer to my question.
My problem is simple: i have defined on Eufy App for my S380 HomeBase a new mode called NIGHT.
When i activate it from the APP i notice that on HA side the Mode is called CUSTOM 1.
There is a way to change the name CUSTOM 1 into NIGHT, or configure HA to replicate names i set on the APP? Because if i configure more than one custom mode it is very difficult to remember which is what..

Can u help please?

Thanks so much!!

**Comment by fuatakgun** [comment]
yes, there is, under configuration panel. but this is not configured per device, it is a global setting

![image](https://github.com/fuatakgun/eufy_security/assets/11085566/f7966cd9-6bb6-4f9e-a898-9497e9a302cd)

**Comment by Ringo982** [comment]
> yes, there is, under configuration panel. but this is not configured per device, it is a global setting
> 
> ![image](https://private-user-images.githubusercontent.com/11085566/296979204-f7966cd9-6bb6-4f9e-a898-9497e9a302cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTQxNTAsIm5iZiI6MTcwNTM5Mzg1MCwicGF0aCI6Ii8xMTA4NTU2Ni8yOTY5NzkyMDQtZjc5NjZjZDktNmJiNi00ZjllLWE4OTgtOTQ5N2U5YTMwMmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4MzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOGZmMmRlNzRmODFmOWZmY2VmYmYyNWI3OTgxMDcxNjY3NzcwMTQwMTBmZGQxMTFhYmQ3OTkwOWY3ZTg0ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XsMPQ1u0ElgrY3hrlnC2LDHszAIN63Ck702-NPzNZjk)

@fuatakgun sorry but it doesn't work.... i changed Custom 1 into Night in the configuration panel. I saved, rebooted the entire HA instance, but when i set on the APP Night mode i still see on HA Custom 1....

**Comment by fuatakgun** [comment]
show me where you see HA Custom 1

**Comment by fuatakgun** [comment]
I have configured like this;

![image](https://github.com/fuatakgun/eufy_security/assets/11085566/24750e39-954c-42fc-8257-c284279b09b6)

And I see it is rendered like this;
![image](https://github.com/fuatakgun/eufy_security/assets/11085566/21befcdf-3aa9-4cec-86c0-0c33868fc18b)

**Comment by Ringo982** [comment]
<img width="434" alt="image" src="https://github.com/fuatakgun/eufy_security/assets/35301477/3d12924c-630c-4b1f-9f55-0bacbeb6ad31">

<img width="848" alt="image" src="https://github.com/fuatakgun/eufy_security/assets/35301477/b3dbfaec-f397-4521-b82e-2836f041aa8a">

<img width="815" alt="image" src="https://github.com/fuatakgun/eufy_security/assets/35301477/1562cc29-63be-4df4-87bc-98bfa68b61bc">

**Comment by fuatakgun** [comment]
Check alarm_control_panel, not the sensor. Sensor is representing the real value we fetch from device.
Alarm Control Panel is the representation of it.
![image](https://github.com/fuatakgun/eufy_security/assets/11085566/7a092aa7-0a6d-4bb8-865a-60f4caadec40)

**Comment by Ringo982** [comment]
ah ok thank u !!

**Comment by fuatakgun** [comment]
can we close this now? did you already validate it?

**Comment by Ringo982** [comment]
yes it works, thank u very much!
