### ISSUE TITLE
Add support for Video Doorbell E340 (T8214)

### ISSUE THREAD

**Issue by LXZ993** [fuatakgun/eufy_security#1088]
**Is your feature request related to a problem? Please describe.**
Cant see any features from the camera only the integrated Homebase can be seen.
![image](https://github.com/fuatakgun/eufy_security/assets/143541165/122fab7b-0164-43ea-8dfe-ab4790a41f64)

**Describe the solution you'd like**
Would be happy if you could add this doorbell to the project.

**Comment by fuatakgun** [comment]
Please check readme and validate if this camera is already supported.
