### ISSUE TITLE
No image showing when camera is not streaming

### ISSUE THREAD

**Issue by johnrobledo** [fuatakgun/eufy_security#109]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Using WebRTC, when the camera is not streaming, no image is showing up, just a gray box.

**To Reproduce**
1. Use WebRTC
2. Set camera to off
3. See bug

**Expected behavior**
Image supposed to show up when the camera is off.

**Screenshots**
![Opera Snapshot_2021-11-14_144947_ffpu46yg581p0rc4y923mqj9yw91zh3t ui nabu casa](https://user-images.githubusercontent.com/90490139/141699947-6b823953-3677-4194-b421-f1383ceb623f.png)

**Hardware Information about Home Assistant
rasberry pi 4 running on M.2NVME SSD
**Hardware Information about Cameras
EufyCam 2 with RTSP and WebRTC

**Additional context**

**Comment by fuatakgun** [comment]
is this repetitive and happening for all cameras or just a specific model?

Can you also check camera attributes from developer tools for pictureUrl?

**Comment by johnrobledo** [comment]
it seems to be happening for all 3 of my eufycam 2's
where do I find the attributes?

**Comment by fuatakgun** [comment]
Check screenshots below in order

![Screenshot_2021-11-14-22-59-50-131_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/141700299-1282cffe-5f43-4bf8-8347-6ddc53d759a0.jpg)

![Screenshot_2021-11-14-23-00-09-672_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/141700304-2a3adbff-3996-438e-aaf7-d4df906d41e1.jpg)

![Screenshot_2021-11-14-23-00-22-701_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/141700305-0437f460-1762-4c34-ae80-2d8d69c1bb76.jpg)

**Comment by johnrobledo** [comment]
It appears to be missing: here is the code
`state:
  name: Backyard
  model: T8114-Z
  serialNumber: T8114P612106073E
  hardwareVersion: T8114-Z
  softwareVersion: 4.5.8
  stationSerialNumber: T8010P1320481D36
  enabled: true
  state: 1
  battery: 59
  batteryTemperature: 22
  lastChargingDays: -1
  lastChargingTotalEvents: 49
  lastChargingRecordedEvents: 0
  lastChargingFalseEvents: 49
  batteryUsageLastWeek: 0
  motionDetected: false
  personDetected: false
  personName: ''
  antitheftDetection: false
  autoNightvision: true
  ledStatus: false
  motionDetection: true
  rtspStream: false
  watermark: 2
  wifiRSSI: -70
  motionDetectionType: 0
  motionDetectionSensivity: 46
  microphone: true
  speaker: true
  speakerVolume: 92
  audioRecording: true
  powerSource: 0
  powerWorkingMode: 0
  notificationType: 1
  rtspUrl: rtsp://admin:admin@10.0.0.120/live0
  liveStreamingStatus: null
  start livestream at initialize: false
properties:
  name:
    value: Backyard
    timestamp: 1636689393000
  model:
    value: T8114-Z
    timestamp: 1636689393000
  serialNumber:
    value: T8114P612106073E
    timestamp: 1636689393000
  type:
    value: 9
    timestamp: 1636689393000
  hardwareVersion:
    value: T8114-Z
    timestamp: 1636689393000
  softwareVersion:
    value: 4.5.8
    timestamp: 1635114742000
  stationSerialNumber:
    value: T8010P1320481D36
    timestamp: 1636689393000
  lastChargingDays:
    value: -1
    timestamp: 1636689393000
  lastChargingFalseEvents:
    value: 49
    timestamp: 1636689393000
  lastChargingRecordedEvents:
    value: 0
    timestamp: 1636689393000
  lastChargingTotalEvents:
    value: 49
    timestamp: 1636689393000
  batteryUsageLastWeek:
    value: 0
    timestamp: 1636689393000
  speakerVolume:
    value: 92
    timestamp: 1635963017000
  motionDetectionType:
    value: 0
    timestamp: 1635963013000
  watermark:
    value: 2
    timestamp: 1635963017000
  statusLed:
    value: false
    timestamp: 1635963013000
  autoNightvision:
    value: true
    timestamp: 1635963017000
  powerWorkingMode:
    value: 0
    timestamp: 1635963013000
  rtspStream:
    value: true
    timestamp: 1636067424000
  microphone:
    value: true
    timestamp: 1635963017000
  audioRecording:
    value: true
    timestamp: 1635963017000
  wifiRSSI:
    value: -72
    timestamp: 1636916195051
  enabled:
    value: true
    timestamp: 1635963013000
  batteryTemperature:
    value: 22
    timestamp: 1636065909000
  motionDetectionSensivity:
    value: 46
    timestamp: 1635963017000
  state:
    value: 1
    timestamp: 1635963013000
  speaker:
    value: true
    timestamp: 1635963017000
  powerSource:
    value: 0
    timestamp: 1635963017000
  motionDetection:
    value: true
    timestamp: 1635963017000
  battery:
    value: 60
    timestamp: 1636072518000
  antitheftDetection:
    value: false
    timestamp: 1635963017000
  notificationType:
    value: 1
    timestamp: 1635963017000
  motionDetected:
    value: false
    timestamp: 0
  personDetected:
    value: false
    timestamp: 0
  personName:
    value: ''
    timestamp: 0
friendly_name: Backyard
entity_picture: >-
  /api/camera_proxy/camera.backyard?token=ed6b99f4f05ab88f2d13379a6d6516ab5312d22380f1a7a95d8db3e1bd12d30a
supported_features: 3
`

**Comment by fuatakgun** [comment]
Hmm, if it is not coming from add-on, we are much limited here. I remember some users were reporting sd card based recording cameras and missing snapshot images. Was it working in previous version?

When you have time, check this: https://github.com/fuatakgun/eufy_security/issues/50

**Comment by johnrobledo** [comment]
It was working for a little bit and it does have local storage on the home base...just started this issue today

**Comment by johnrobledo** [comment]
should i factory reset the camera and add again?

**Comment by fuatakgun** [comment]
i can debug tomorrow if you can share it following readme

**Comment by johnrobledo** [comment]
ok
I will share now and await your response
It is a EufyCam 2 named Backyard

**Comment by johnrobledo** [comment]
I went ahead and shared them

**Comment by fuatakgun** [comment]
I see that you own Garage and Backyard with identical software on it. Garage has `pictureUrl` but Backyard does not have it. Before we continue, can you factory reset as you suggested and you can create an issue here if it is still not resolved: https://github.com/bropat/eufy-security-client

**Comment by fuatakgun** [comment]
just one callout, rather than calling this as `when camera is off` let's call this as `when camera is not streaming`.

`camera is off` might be understood as `camera is disabled`

**Comment by johnrobledo** [comment]
Okay thanks! I will reset when i get home and create an additional issue if it remains the same

**Comment by skank01** [comment]
Having same issue, but not with my doorbell

**Comment by skank01** [comment]
Is this something should go to bropat?
@johnrobledo if you past that pictureurl do you see the picture?
I guess not...
I dont get it anyway, although thumbnails are enabled

**Comment by LordNex** [comment]
Question. I noticed the pictureURL goes to an AmazonWS server. Does that URL change each time or is it always the same. I'd like to base some notification on it but if it changes each time I'll have to figure out some template.

**Comment by fuatakgun** [comment]
For each notification, you receive a brand new URL, old one dies out. Sometimes z url comes from amazon, sometimes it is Eufy endpoint

**Comment by fuatakgun** [comment]
@skank01 , if attribute goes missing it should go to @bropat, you are right

**Comment by fuatakgun** [comment]
Resolving this, please comment back if anything i can do

**Comment by LordNex** [comment]
Yea I believe this is resolved. Although the streaming issue is still there. Do you think you’ll be able to resolve the streaming or should I look at getting a different doorbell? Again thanks to both of you for your help and hard work. I do appreciate it!


On Nov 28, 2021, at 2:15 PM, Fuat Akgün ***@***.***> wrote:

﻿

Closed #109<https://github.com/fuatakgun/eufy_security/issues/109>.

**Comment by skank01** [comment]
@fuatakgun i still dont have an image though, although before moving to new version it was ok

**Comment by fuatakgun** [comment]
> @fuatakgun i still dont have an image though, although before moving to new version it was ok

Let's track this as a separate issue, i believe you had confirmed that you have pictureUrl attribute for camera, right?

**Comment by skank01** [comment]
Thats true

**Comment by skank01** [comment]
For the doorbell T8210 all is good
For the camera T8114 its not, it was before the  update 0.5.0 , so i truly think something broke with the version from ws 0.5.0 and up

**Comment by LordNex** [comment]
﻿I can confirm that I do get a static image and a pictureURL path that is viewable in a browser. So as far as this specific issue, looks resolved to me.

Again still have issues with restarting the stream but I said screw it and bought 2 Armcrest AD410’s and am just going to install the YouuuFeeee at the in-laws 😎

On Nov 29, 2021, at 12:46 PM, Fuat Akgün ***@***.***> wrote:

﻿

Any you confirmed that these pictureUrl is accessible from browser? if it is accessible, it is a problem of home assistant cannot reach that URL. if it is anot accessible by browser, it is an issue from eufy, i am not sure i can do anything

**Comment by LordNex** [comment]
﻿
﻿I can confirm that I do get a static image and a pictureURL path that is viewable in a browser. So as far as this specific issue, looks resolved to me.

Again still have issues with restarting the stream but I said screw it and bought 2 Armcrest AD410’s and am just going to install the YouuuFeeee at the in-laws 😎

On Nov 29, 2021, at 12:46 PM, Fuat Akgün ***@***.***> wrote:

﻿

Any you confirmed that these pictureUrl is accessible from browser? if it is accessible, it is a problem of home assistant cannot reach that URL. if it is anot accessible by browser, it is an issue from eufy, i am not sure i can do anything
