### ISSUE TITLE
T825 cam has only 2 entities

### ISSUE THREAD

**Issue by nazarenodistefano** [fuatakgun/eufy_security#1094]
I've added 4 cams: T825 and T8B00 has only 2 entities (Debug (device) and Debug (station))
T8410 instead has a lot of entities and I can control it very well.
Do you know why I cant' configure other cam model like the T8410?

**Comment by fuatakgun** [comment]
if it has only 2 entities, it means that it is not supported by add-on, please reach out to add-on owner for support.
