### ISSUE TITLE
so, giving this a second thought, I see that camera snapshot is being updated regularly while streaming or when generate_image is called.

### ISSUE THREAD

**Issue by bkr1969** [fuatakgun/eufy_security#1099]
so, giving this a second thought, I see that camera snapshot is being updated regularly while streaming or when generate_image is called.
but this snapshot is stored under camera entity.
on the webrtc card example I shared, the logic is working like this;
- if the camera is not streaming, show the poster (image.last_event -> this is not camera snapshot, this is last motion trigger event)
- if the the camera is steraming, show the webrtc steram.

If you want, you can switch your webrtc card into this below;

```
type: custom:webrtc-camera
entity: camera.entrance
poster: camera.entrance
```

_Originally posted by @fuatakgun in https://github.com/fuatakgun/eufy_security/issues/1074#issuecomment-1909651534_

**Comment by fuatakgun** [comment]
What is this supposed to mean?

**Comment by bkr1969** [comment]
This response does not make sense to me. If I add ```entity:``` to my card, I get a ```"Cannot find URL for 'any camera I choose'"```.  I still have an image on one camera that is a month old.  I have followed the description exactly but nothing changes. Can you please give the exact configuration for a card that will include a current snapshot image?  I am happy to give you access to my specific camera if that helps.

**Comment by fuatakgun** [comment]
If you want this to be logical to you, then you have to be precise and clear.

The initial issue is that the camera snapshot is storing latest image when it is streaming or when generate_image is called 

I checked the code and validated that it is working as described initially.

**Comment by bkr1969** [comment]
But it is not.  This is as precise as I can be.
1. If a snapshot is being stored, where is it stored and how do I access it? It is NOT showing up as my poster.
2. Can you simply post the EXACT configuration you used in your example: https://private-user-images.githubusercontent.com/11085566/210083674-bbf082ab-5f20-4d1c-ab61-e687c7ce7506.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMTI3NzAsIm5iZiI6MTcwNjIxMjQ3MCwicGF0aCI6Ii8xMTA4NTU2Ni8yMTAwODM2NzQtYmJmMDgyYWItNWYyMC00ZDFjLWFiNjEtZTY4N2M3Y2U3NTA2Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE5NTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MzMwZWVlOWExODQ2MDEyMmQyN2Q0MjBkYTYzOWNmMzQ3OGUzM2I3OWE0NDBjYzkyYjBmYWRhYzkwNTlmZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t-4UocMoREMUwfY1HG-vO-J2nltI7PMTatKZMD8pc40

Without knowing the code, I cannot tell if there is an issue with my camera model, my configuration, or my code.  All I know is that it DOES NOT work as your example does.

**Comment by fuatakgun** [comment]
Can you post webrtc card code?

**Comment by bkr1969** [comment]
```
  - type: custom:webrtc-camera
    url: rtsp://BackYardCamera1:Password@xxx.xx.x.xxx/live1
    poster: camera.backyard
    ui: true
```

**Comment by fuatakgun** [comment]
You are not using this integration for streaming, you are directly streaming from rtsp endpoint, which is not going through my integration.

So, don't expect a solution from this integration, but if i were you, i would create a generic camera with RTSP url and use that camera entity for webrtc camera and everything would work fine.

**Comment by bkr1969** [comment]
That mostly works, except the configuration for the generic camera asks for a URL for the still image and I don't know what to use there. Thank you for your help with this.

**Comment by fuatakgun** [comment]
If you want to use my initial suggestion, you need to call rtsp stream service to start streaming, so the rest would work fine. But not much needed

**Comment by bkr1969** [comment]
It will stream just fine, but I have a dummy image for the snapshot now.  I cannot use the rtsp URL (generic camera won't accept).  What do I use for the URL of the still image?
![image](https://github.com/fuatakgun/eufy_security/assets/42385989/5981d9b5-dbe8-4a05-b7ca-8a7130a89951)

**Comment by fuatakgun** [comment]
Just put some image from the internet, it will not be visible to you on webrtc (hopefully)

**Comment by bkr1969** [comment]
No.  As soon as the streaming is stopped, whatever image I use as a placeholder comes back.

**Comment by fuatakgun** [comment]
Let's rollback to initial idea and use the camera entity from my integration and use respective services to start stop stream

**Comment by bkr1969** [comment]
Tell me exactly what you want me to do.

**Comment by bkr1969** [comment]
OK.  I don't know if this helps or not.  I tried using the ```camera.snapshot``` service.  If I call it on the actual camera, it snaps the same stale image I've been seeing for the past month (stream is on when I call the service).  If I call it on the generic camera I created, I get a blank (broken) image place holder.  Shouldn't a snapshot grab what is coming through the stream?
