### ISSUE TITLE
Support for S340

### ISSUE THREAD

**Issue by casperleenheer** [fuatakgun/eufy_security#1102]
Will the S340 be supported in the future? I see it is implemented in Bropats eufy-security-ws, but I don't understand how it works: my understanding is that you are using the docker container and this project is as a wrapper. Will the device be supported when you take the latest release from Bropat or is it working differently?

**Comment by fuatakgun** [comment]
bropat will release a new add-on version and integration would hopefully support it out of the box.

If not, please reach out to me with the specific issue.
