### ISSUE TITLE
RTSP Streaming - Always On?

### ISSUE THREAD

**Issue by Jazzik777** [fuatakgun/eufy_security#111]
Not sure if this is the right place to post this, so forgive me if not.

Just setup and installed a couple of Eufy 2C cameras. All working well, but the camera that I've been using to test with to integrate into HA using this integration now appears to be "stuck" with RTSP Streaming as the permenant state. 

calling the service camera.turn_off doesnt seem to have any effect. I've uninstalled the integration, reinstalled it, stopped the RTSP addon, stop WebRTC, turned everything off, reboot the camera, rebooted the base station, but this state seems to be stuck permenantly. I even disabled RTSP on the camera, but the integration turns it back on and the state remains the same. Any help would be appreciated.

camera.backyard
state: Streaming - rtsp

state:
  name: Backyard
  model: T8113-Z
  serialNumber: XX
  hardwareVersion: T8113-Z
  softwareVersion: 5.2.7
  stationSerialNumber: XX
  enabled: true
  state: 1
  battery: 79
  batteryTemperature: 22
  lastChargingDays: -1
  lastChargingTotalEvents: 1
  lastChargingRecordedEvents: 1
  lastChargingFalseEvents: 0
  batteryUsageLastWeek: 0
  motionDetected: false
  personDetected: false
  personName: ''
  antitheftDetection: false
  autoNightvision: true
  ledStatus: false
  motionDetection: true
  rtspStream: true

**Comment by fuatakgun** [comment]
this is the most valid place :)

can you enable RTSP from mobile app and wait for 3 minutes, restart add-on and reload integration (or restart HA)

**Comment by Jazzik777** [comment]
Hey thanks for coming back to me, still same. The camera does appear to be working, but I'm conscious that it might be streaming constantly (my thumbnails update every 10 seconds) which is going to use the batteries up real fast

![image](https://user-images.githubusercontent.com/53336917/141784025-646580f0-8f22-4198-8ab8-b901561dc7fa.png)

**Comment by fuatakgun** [comment]
RTSP cannot stream forever, there is a time limit (around 3 minutes) and I have built the integration around it.
I have 2C indoor cameras and tested this before releasing.

**Comment by Jazzik777** [comment]
so if I close home assistant and ignore it for 10 minutes those cameras should go back to idle?

**Comment by fuatakgun** [comment]
integration never sends start_rtspstream automatically, it should be triggered by an automation or a button event.
motion events are triggering rtsp stream, independent to HA
but you can give a try to your proposal

**Comment by Jazzik777** [comment]
> integration never sends start_rtspstream automatically, it should be triggered by an automation or a button event. motion events are triggering rtsp stream, independent to HA but you can give a try to your proposal

Currently there were no events on my phone app so nothing triggering on the official eufy app to record events, but the entity state remained "RTSP - Streaming"

I've just turned my cameras to face a wall, and closed my HA apps and the phone eufy app. Will leave for 10minutes and recheck the entity state.

**Comment by Jazzik777** [comment]
Unfortunately still the same, and I've not looked at the cameras, either through the app or through HA since closing everything down 10minute ago.

Sorry, not sure if this is normal behaviour, are you able to confirm that the cameras should revert back to "idle"?
![image](https://user-images.githubusercontent.com/53336917/141789953-e72f7ca3-6498-4783-ae2f-e6a3b4d3a1fc.png)

**Comment by fuatakgun** [comment]
in this stage, can you try to restart add-on and reload the integration?

**Comment by Jazzik777** [comment]
Yeap sure.

Restarted Addon: boot logs
![image](https://user-images.githubusercontent.com/53336917/141790910-eb4048dc-0993-4070-bb42-32b0a181d291.png)

Reload integration:
![image](https://user-images.githubusercontent.com/53336917/141790873-0b1b1321-1ea6-4845-bf0a-4824acc903d0.png)

**Comment by fuatakgun** [comment]
please double check this, webrtc might be asking to restart RTSP every time it ends. I have experienced this issue NOW and this had resolved it.

![image](https://user-images.githubusercontent.com/11085566/141791789-0afc6ae3-4b27-45e2-9a1b-eb496a39afc4.png)

**Comment by Jazzik777** [comment]
This is how I am currently setup:
![image](https://user-images.githubusercontent.com/53336917/141792082-c344a771-e9ce-44c7-aa13-cfd12603fb78.png)

happy to remove the RTSP addon if necessary.

Currently, I do not have WebRTC running

**Comment by fuatakgun** [comment]
hey, diaable auto start, webrtc is the king :-)

**Comment by Jazzik777** [comment]
Ok, so... heres where I am at now.

RTSP P2P addon enabled
Auto Start - Disabled
WebRTC installed and running

The webRTC output currently comes up blank, though it was working a few minutes ago? I'm assuming this is a timeout. However, calling service "camera.turn_on" does nothing. This is the same whether using the entity or the rtsp://172.16.1.128/live0 url (confirmed as working with VLC)

HA entity cameras show thumbnail, and status "Streaming - rstp"
![image](https://user-images.githubusercontent.com/53336917/141795937-17ae4b42-3259-4b8c-a8c1-b8f568bef7f7.png)

Clicking the HA camera does nothing, if I enable the auto-start on click, it starts the camera.

Cannot currently use conditional windows to turn on the webRTC camera by monitoring the streaming state because it is always "True"

P.s. thanks again fo your help here, and for doing some great work on this integration.. everything seems like it "should" be great. Just having some teething trouble I'm sure.

**Comment by Jazzik777** [comment]
Update:

![image](https://user-images.githubusercontent.com/53336917/141798682-f2db154e-1ff4-4e30-847e-a0778e89ad50.png)

Both options for cameras working, RTSP addon in use, auto-start disabled, but streaming status still sticks on true.

![image](https://user-images.githubusercontent.com/53336917/141798791-23a9d5ee-0f06-44aa-a014-94780f3c49de.png)

**Comment by Jazzik777** [comment]
Might be making progress :)

**Comment by Jazzik777** [comment]
Right so progress is happening:

![image](https://user-images.githubusercontent.com/53336917/141800408-a42878e6-4b53-4100-8a1e-237afe017e8f.png)



I created this as a test with both of my rtsp webrtc cameras on, eventually it times out, and just presents black no video. (probably the 3 minutes you mentioned previously), if I press the "on" button below (call service camera.turn_on) and refresh the cameras start working.. GOOD stuff. However, there doesnt appear to be a way for me to monitor their status with the streaming status still always being true, regardless of whether the cameras are showing live rtsp, or the failed video black screen.

**Comment by fuatakgun** [comment]
if you want, you can share your cameras following readme and let me know the names over here, i can see the problem

**Comment by Jazzik777** [comment]
I've cobbled together a work around to toggle them and it appears to be working, but I would prefer to be able to see the streaming status as intended. I've sent you an invite to see the cameras. Only have two currently so either or is presenting me with the same issues.

**Comment by fuatakgun** [comment]
can you send an email to me @Jazzik777 using `fuatakgun@gmail.com`

**Comment by Jazzik777** [comment]
> can you send an email to me @Jazzik777 using `fuatakgun@gmail.com`

you should already have it

**Comment by fuatakgun** [comment]
I have many cameras shared with me, I want to get connected with you in private to get serial ID of your device :)

I have 3 backyard cameras :)

**Comment by Jazzik777** [comment]
> I have many cameras shared with me, I want to get connected with you in private to get serial ID of your device :)
> 
> I have 3 backyard cameras :)

Oh I see... of course durr :-)

Emailed you over outside of the board.

**Comment by fuatakgun** [comment]
@Jazzik777 can you update this thread and resolve later on?

**Comment by Jazzik777** [comment]
I'd get it done for you now if I knew how to do it :-D

**Comment by Jazzik777** [comment]
Resolved, Fuat is so incredibly helpful!

**Comment by Jazzik777** [comment]
Done :)
