### ISSUE TITLE
Removed camera entities can not be removed

### ISSUE THREAD

**Issue by eikowagenknecht** [fuatakgun/eufy_security#1112]
**Describe the bug**

I had to replace one of my cameras. So I removed the old one and added the new one. Unfortunately, the old one is still in Home Assistant, despite not being in the Eufy app any more.

I tried deleting the "device" from Home Assistant. Still the Entities remain. And I can't delete those, because they are "not manageable from UI":

![grafik](https://github.com/fuatakgun/eufy_security/assets/1475672/3ce9a16a-0221-4eb1-b6a1-037a7540ed57)

How to ger rid of these things so I can properly set up the new ones with the same names again?

**Expected behavior**

Deleted camera is deleted in HA as well.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: core-2024.2.5
- Eufy Security Add-on Version: eufy-security-ws (1.7.1)
- Eufy Security Integration Version: 8.0.1

**Comment by fuatakgun** [comment]
go to device and delete the device 

![image](https://github.com/fuatakgun/eufy_security/assets/11085566/99486e23-b4ec-4776-a305-aae17fed02fa)

**Comment by eikowagenknecht** [comment]
I did that already before opening the issue. It did delete the device, but none of the entities.

I only managed to fix it by directly editing the HA device storage json.
