### ISSUE TITLE
Ability to add custom modes to smart home integrations for Eufy Security Home Base

### ISSUE THREAD

**Issue by Adam-Kay** [fuatakgun/eufy_security#112]
### Is your feature request related to a problem? 
Not really, I would just like to arm my Eufy Base into custom modes using the HomeKit integration through Home Assistant.

### Describe the solution you'd like
In addition to the Home, Away, and Off states that are present on the smart device, it would be cool if we could enable a custom option to appear there also, in my case, Bedtime.

### Describe alternatives you've considered
I'm not really sure what the alternative is, you could send an event to HA with an automated script and have it do it that way with a service call I suppose.

### My options in the Eufy app:
<img src="https://user-images.githubusercontent.com/10010491/141863950-d0e06657-95b0-45f7-b782-e3e4124ecc46.png" alt="alt text" width="400">

### My current options in HomeKit, through HA. The "Bedtime" mode or any custom modes are missing.
<img src="https://user-images.githubusercontent.com/10010491/141864004-0be5a7bb-bff8-42c9-bc99-be2eec536775.png" alt="alt text" width="400">

**Comment by fuatakgun** [comment]
give a try to these services: https://github.com/fuatakgun/eufy_security/blob/master/README.md#12-station-services

**Comment by fuatakgun** [comment]
Not sure about homekit, in my case, i can add custom modes using mobile app and can set these using these services.

**Comment by Adam-Kay** [comment]
Yes, I have the custom modes added in the app, shown in the screenshot I have "Bedtime", which is a custom mode. 
Is there any way to edit the Eufy Base device to add this extra switch in the smart home integration?
Is it because of the device type it's added as? Like an Alarm Panel or something?

**Comment by fuatakgun** [comment]
Yes, home base is added as alarm panel.

This is my screenshot ![IMG_20211116_194231.jpg](https://user-images.githubusercontent.com/11085566/142046188-7e5d37cd-95d2-444f-9c3d-f2112194d1e0.jpg)

**Comment by fuatakgun** [comment]
You can set home, away and disarm using front end. You can set custom ones using service calls.

**Comment by fuatakgun** [comment]
Ok, now i have understood your ask, alarm base in home assistant can support 3 modes out of the box. Custom ones cannot be surfaced to home kit.

We can introduce an action button to trigger them to surface in home kit, in case you are interested, let me know.

--reopening in case you need--

**Comment by Adam-Kay** [comment]
That sounds good! I would be happy to have an action button in HK instead of adding to the switch is not possible.

I know there is a way to add multiple switches to one device in HK through adding items as "Accessories" to another device. I wonder if we would be able to add this action button as an Accessory to the Eufy base. If not, separate works fine too.

Example: 
![image](https://user-images.githubusercontent.com/10010491/142048746-72f42d0a-559e-4c0e-ae1e-c7b50c63d9f9.jpeg)

**Comment by fuatakgun** [comment]
Lets follow from https://github.com/fuatakgun/eufy_security/issues/145

Please check my last post there and share your thinking.
