### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by sythesigh** [fuatakgun/eufy_security#1122]
This is a weird one as it hasn’t actually stopped working.. all is good, but every now and then, I get this notification: 
![IMG_0694](https://github.com/fuatakgun/eufy_security/assets/107685183/3f9cb2cb-bb96-4385-b10d-d21edec265c2)

Any ideas?

**Comment by stijnb1234** [comment]
+1, my Home Assistant is running very slow with the add-on enabled and loses connection a lot. When I disable the add-on, everything runs smoothly again.

**Comment by superpower10** [comment]
+1

**Comment by stijnb1234** [comment]
@fuatakgun Could you look into this?

**Comment by fuatakgun** [comment]
Folks, let's be mindful for a minute and explain to me how I can look at this?

There is a bug template to be used and you are just dismissing it and expecting me to find the problem with no information.

Please follow the bug template and create a new issue
