### ISSUE TITLE
Camera entity is missing after a fresh install

### ISSUE THREAD

**Issue by satyambaba** [fuatakgun/eufy_security#114]
**Describe the bug**
Due to recent issues, I did a fresh install of the eufy security integration (including the eufy security add-on and rtsp simple server add-on) today. Camera entities are not created for any of my cameras (2 Indoor pan & tilt 2K camera and 1 battery powered 1080p doorbell). Please note that, all other entities are created except camera entities. In earlier installation, camera entities were created for all my cameras.

**To Reproduce**
1. Remove Eufy Security Integration
2. Remove Eufy Security from HACS
3. Restart HA
4. Download Eufy Security from HACS
5. Install Eufy Security Integration
6. Configure with "localhost" 
7. Devices are detected, all other entities are created except camera entities

**Expected behavior**
Camera entities should be created.

**Screenshots**
Please see the screenshot for my doorbell camera. All entities are there except for the camera entity. There should have been an entity  named "camera.doorbell" which is missing here
![Capture](https://user-images.githubusercontent.com/6833101/141968974-d63c6d2c-0200-4bbf-aac5-e479d7b2f951.PNG)

**Hardware Information about Home Assistant**
Home Assistant Blue

**Hardware Information about Cameras**
1. 2 x T8410 Indoor Pan & Tilt 2K Eufy Camera - RTSP
2. 1 x T8222-Z Battery 1080P Doorbell Camera - P2P

**Comment by fuatakgun** [comment]
Can you also publish logs from eufy security add on?

**Comment by fuatakgun** [comment]
Please follow this thread: https://github.com/bropat/eufy-security-ws/issues/44

You can rollback previous version of add-on until this is resolved

**Comment by satyambaba** [comment]
> Please follow this thread: [bropat/eufy-security-ws#44](https://github.com/bropat/eufy-security-ws/issues/44)
> 
> You can rollback previous version of add-on until this is resolved

Thanks a lot for your help and this wonderful integration. I'll wait for the fix. Cheers!

**Comment by fuatakgun** [comment]
Updated add-on with latest release, please give it a try

**Comment by chriscolden** [comment]
Came here to say I had an issue where it broke after updating from 2021.11.1 to 2021.11.4, or at least that's when I noticed the issue. I've just grabbed the update in supervisor and restarted the integration and all it working again.

Thank you for the quick resolution.

**Comment by fuatakgun** [comment]
What is your add on version @chriscolden ?

**Comment by chriscolden** [comment]
I'm on 0.5.3 now.

**Comment by fuatakgun** [comment]
Perfect good news

**Comment by cjeri** [comment]
I'm having similar problems. Two of my entities disappeared out of the blue (screenshot below).

Tried restarting the add on, yet no luck

<img width="1035" alt="Screenshot 2021-11-16 at 19 21 46" src="https://user-images.githubusercontent.com/22331663/142051573-d60469e4-7dda-4be0-9478-f481beb0fed7.png">

Log shows the following:

2021-11-16 19:17:30.232  ERROR Message error 
 StationNotFoundError  No station with serial number: T8420N6021151255!
details:
{
  name: 'StationNotFoundError'
}
error stack:
• eufysecurity.ts:294 getStation
    node_modules/eufy-security-client/src/eufysecurity.ts:294:15
• message_handler.ts:36 handle
    src/lib/device/message_handler.ts:36:32
• server.ts:46 device
    src/lib/server.ts:46:34
• server.ts:98 receiveMessage
    src/lib/server.ts:98:58
• server.ts:57 <anonymous>
    src/lib/server.ts:57:53
• events.js:400 emit
    events.js:400:28
• websocket.js:1022 receiverOnMessage
    node_modules/ws/lib/websocket.js:1022:20
• events.js:400 emit
    events.js:400:28
• receiver.js:522 dataMessage
    node_modules/ws/lib/receiver.js:522:14
• receiver.js:440 getData
    node_modules/ws/lib/receiver.js:440:17
2021-11-16 19:17:30.754  ERROR Stations - Generic Error: 
 TypeError  Cannot read property 'length' of null
error stack:
• session.ts:1546 updateRawStation
    node_modules/eufy-security-client/src/p2p/session.ts:1546:37
• session.ts:98 P2PClientProtocol
    node_modules/eufy-security-client/src/p2p/session.ts:98:14
• station.ts:49 Station
    node_modules/eufy-security-client/src/http/station.ts:49:27
• eufysecurity.ts:329 handleHubs
    node_modules/eufy-security-client/src/eufysecurity.ts:329:33
• eufysecurity.ts:130 <anonymous>
    node_modules/eufy-security-client/src/eufysecurity.ts:130:50
• events.js:400 emit
    events.js:400:28
• api.ts:297 updateDeviceInfo
    node_modules/eufy-security-client/src/http/api.ts:297:30
• eufysecurity.ts:453 refreshCloudData
    node_modules/eufy-security-client/src/eufysecurity.ts:453:9
• message_handler.ts:22 handle
    src/lib/driver/message_handler.ts:22:17
2021-11-16 19:17:30.809  ERROR Stations - Generic Error: 
 TypeError  Cannot read property 'length' of null
error stack:
• session.ts:1546 updateRawStation
    node_modules/eufy-security-client/src/p2p/session.ts:1546:37
• session.ts:98 P2PClientProtocol
    node_modules/eufy-security-client/src/p2p/session.ts:98:14
• station.ts:49 Station
    node_modules/eufy-security-client/src/http/station.ts:49:27
• eufysecurity.ts:329 handleHubs
    node_modules/eufy-security-client/src/eufysecurity.ts:329:33
• eufysecurity.ts:130 <anonymous>
    node_modules/eufy-security-client/src/eufysecurity.ts:130:50
• events.js:400 emit
    events.js:400:28
• api.ts:297 updateDeviceInfo
    node_modules/eufy-security-client/src/http/api.ts:297:30
• eufysecurity.ts:453 refreshCloudData
    node_modules/eufy-security-client/src/eufysecurity.ts:453:9
• message_handler.ts:22 handle
    src/lib/driver/message_handler.ts:22:17

**Comment by cjeri** [comment]
Just upgraded to 0.5.3 and it seems to have solved the issue. Thanks!
