### ISSUE TITLE
No Audio :-(

### ISSUE THREAD

**Issue by MorreMor** [fuatakgun/eufy_security#1146]
hi,
i have the stream but I have no audio with webrtc

**Comment by kmil4** [comment]
Same. Commenting so I can follow this

**Comment by Martijnvanoijen** [comment]
Same issue here :)

**Comment by robbinjanssen** [comment]
same here, is there any data/debug info we can provide?
Audio does work when I open the RTSP stream in for example VLC.

**Comment by fuatakgun** [comment]
I tried to have audio for p2p streaming earlier. It failed because either home assistant was not able to handle two incoming stream data parallelly or my skills were not up to it :-)

So, it is better to have some stream without audio than no stream at all.
