### ISSUE TITLE
Map "Night" to native Home Assistant alarm state instead of Custom 2

### ISSUE THREAD

**Issue by Ged-fi** [fuatakgun/eufy_security#1150]
In #145 alarm_night was mapped to Custom 2 in Eufy. 

However, Eufy and Home Assistant both "natively" support Night mode so the current mapping is unintuitive and requires creating a Custom alarm mode when Night would work better. 

Home Assistant, especially using Mushroom cards will not display "Night" correctly with the current Custom mapping. Neither will Eufy display "Night". 

Please reconsider mapping "alarm_night" natively to Night in Eufy.

If the Custom 2 mapping is required for Home Kit for some weird reason, consider adding an option "map night to Custom 2" in the configuration instead.

**Comment by fuatakgun** [comment]
Thanks for the idea and I agree that it looks unintuitive at first but we ended up in this state after finding out that Night is not a fixed node across all models. Sharing a picture below from my home base 2.



Please check your home base's night mode if it is deletable, if yes, it is just another custom config so it means not everyone has it on their system.

**Comment by Ged-fi** [comment]
Ah, I can confirm that "Night" is actually deletable on my model, so it does qualify as a custom config!  As such, I agree with the current slightly un-intuitive implementation.  

Sorry for the extra work in looking at this feature request.  I suggest it can be closed.

**Comment by Emptyless** [comment]
Not sure if related but I'm trying to get "Night" mode to work in Homekit but the Home app remains stuck on "Arming...". I have two custom modes in the Eufy app (custom_1 => Morning, custom_2 => Night) and named them correspondingly as overrides in the Eufy Home Assistant integration. In the Home app, all modes but Night mode work. When selecting Night mode in the Home app, the Home Assistant state and the Eufy app get updated but the Home app remains, stuck - any thoughts on what could cause that?

**Comment by DerHerzog7** [comment]
> Not sure if related but I'm trying to get "Night" mode to work in Homekit but the Home app remains stuck on "Arming...". I have two custom modes in the Eufy app (custom_1 => Morning, custom_2 => Night) and named them correspondingly as overrides in the Eufy Home Assistant integration. In the Home app, all modes but Night mode work. When selecting Night mode in the Home app, the Home Assistant state and the Eufy app get updated but the Home app remains, stuck - any thoughts on what could cause that?
> 
> edit: nevermind, I figured out that I should use the const declarations from the [homeassistant/core](https://github.com/home-assistant/core/blob/6dc5a9efde614d51b8b1f87d92da1aa5079a8c0a/homeassistant/const.py#L484) (`Override name for custom Guard mode 2`: `armed_night`): ![image](https://github.com/user-attachments/assets/5047de02-89b6-4da2-96ba-4975cd6093bb) but leaving the comment open for others to find

Did this work for you? I've used some converluted dual security modules with Alarmo to get this to work, but would be much easier if Night mode would just work automatically.
