### ISSUE TITLE
change guard mode - Connection KO

### ISSUE THREAD

**Issue by floow77** [fuatakgun/eufy_security#1151]
**Describe the bug**

I can't change guard mode from HA. 

**To reproduce**

service: alarm_control_panel.alarm_arm_away
target:
  entity_id: alarm_control_panel.homebase

**Expected behavior**

armed away

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):   Home Assistant OS
- Home Assistant Core Version:  core-2024.5.5
- Eufy Security Add-on Version: 1.8.0-2
- Eufy Security Integration Version: 8.0.2

Hardware Information;
- Camera Model: Homebase 2 + Eufycam 2C

 
- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
`2024-05-25 21:07:55.724	WARN	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.sendPing] Heartbeat check failed for station T8010N12345666666. Connection seems lost. Try to reconnect...
2024-05-25 21:07:55.727	INFO	eufy-security-ws:eufy-security-client	[http] [Station.onDisconnect] Disconnected from station T8010N12345666666
2024-05-25 21:08:25.792	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Tried all hosts, no connection could be established to station T8010N12345666666.
2024-05-25 21:08:25.796	INFO	eufy-security-ws:eufy-security-client	[http] [Station.onTimeout] Timeout connecting to station T8010N12345666666
2024-05-25 21:08:55.814	ERROR	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] All address lookup tentatives failed. {
  stationSN: 'T8010N12345666666'
}`

**Comment by Mattheinrichs** [comment]
Same here with an S330. I'm trying to snooze notifications, and I couldn't find a working method (Snooze service, set the snooze time and mode manually, and lastly - changing the guard mode).

**Comment by mrhelder** [comment]
I also have this issue with my HomeBase 2 and Video Doorbell Battery 2k

**Comment by fuatakgun** [comment]
Integration cannot do anything to fix this issue because add-on is having issues communicating with the cameras and integration is just a presentation layer for add-on.

Please simplify your network setup if there is any VLAN or different restrictions and try again to better understand the issue.

At last resort, feel free to reach out to bropat to deep dive on communication issues.
