### ISSUE TITLE
Floodlight Cam E340

### ISSUE THREAD

**Issue by barney34** [fuatakgun/eufy_security#1157]
### Discussed in https://github.com/fuatakgun/eufy_security/discussions/1156

<div type='discussions-op-text'>

<sup>Originally posted by **barney34** June  6, 2024</sup>
Would it be possible to add enable/ disable to the Floodlight for the E340.   There are times when we are in the backyard when we still need recording of activity at the pool but dont need the flood.   It would be great if I could turn off the floodlight when say our pool pump is on via a Homeassistant automation</div>

**Comment by barney34** [comment]
or motion activated llumination toggle

**Comment by barney34** [comment]
Bropat says: 
This functionality is already available (property lightSettingsEnable).”

**Comment by fuatakgun** [comment]
Do you see it under debug sensor attributes?

**Comment by barney34** [comment]
O yes it’s there thank you.  No I’ll try to figure out how to toggle it with an action

**Comment by fuatakgun** [comment]
Please share the attributes data here

**Comment by barney34** [comment]
name: Backyard Camera
model: T8425
serialNumber: T8425T11233803C5
hardwareVersion: 0.0.0.0
softwareVersion: 1.5.7.0
type: 47
stationSerialNumber: T8030P1323330EBA
wifiRssi: -45
wifiSignalLevel: 4
enabled: true
nightvision: 2
statusLed: false
motionDetection: true
motionDetectionSensitivity: 5
motionDetectionTypeHuman: true
motionDetectionTypeHumanRecognition: true
motionDetectionTypePet: false
motionDetectionTypeVehicle: false
motionDetectionTypeAllOtherMotions: false
motionDetectionRange: 0
motionDetectionRangeStandardSensitivity: 5
motionDetectionRangeAdvancedLeftSensitivity: 3
motionDetectionRangeAdvancedRightSensitivity: 3
motionDetectionTestMode: false
motionDetected: false
motionTracking: true
motionAutoCruise: false
motionOutOfViewDetection: true
personDetected: false
personName: ''
watermark: 2
petDetected: false
soundDetected: false
cryingDetected: false
light: false
microphone: true
speaker: true
speakerVolume: 80
audioRecording: true
videoStreamingQuality: 3
videoRecordingQuality: 3
lightSettingsEnable: true
lightSettingsBrightnessManual: 1
lightSettingsBrightnessMotion: 1
lightSettingsBrightnessSchedule: 50
lightSettingsMotionTriggered: true
lightSettingsMotionActivationMode: 0
lightSettingsMotionTriggeredTimer: 180
notificationType: 2
rotationSpeed: 5
imageMirrored: false
notificationPerson: true
notificationPet: true
notificationAllOtherMotion: true
notificationIntervalTime: 60
autoCalibration: true
dualCamWatchViewMode: 0
snooze: false
snoozeTime: 0
identityPersonDetected: false
strangerPersonDetected: false
vehicleDetected: false
dogDetected: false
dogLickDetected: false
dogPoopDetected: false
detectionStatisticsWorkingDays: 124
detectionStatisticsDetectedEvents: 91253
detectionStatisticsRecordedEvents: 7119

**Comment by fuatakgun** [comment]
If I ask you to modify a file locally and restart your home assistant instance, can you do it?

File: custom_components/eufy_security/const.py , after line 135 which starts with `light = EntityDescription`, add this line below;

```
lightSettingsEnable = EntityDescription(id=auto(), category=EntityCategory.CONFIG)
```

**Comment by fuatakgun** [comment]
to be released in next version
