### ISSUE TITLE
Sensors not updating

### ISSUE THREAD

**Issue by adam-cobb** [fuatakgun/eufy_security#116]
I am seeing issues over the last few days where the sensors are not updating for my cameras and doorbell. So the ringing sensor, person detector etc. If I reload the integration or restart HA it updates, but otherwise it's not getting any updates it seems. The Eufy app itself is notifying me so seems fine that end.

I have a separate account setup as you advise, purely connected to HA.

Appreciate there's not a lot to go on here, but happy to send any info that would help - I'm running the following version of the HACS integration - be15a00.

Nothing appears in my logs when things happen (doorbell ring, motion events etc.)

**Comment by adam-cobb** [comment]
Just realised I was running a fairly old version (0.3.3) of the eufy_security_addon. So i'll upgrade that see if it helps....

**Comment by MechEng70** [comment]
I have found version 0.5.3 to work well with the sensors.

**Comment by fuatakgun** [comment]
Thanks @MechEng70 for updates. What about you @adam-cobb

**Comment by dannycb1987** [comment]
Hmm, I also notice no changes at doorbell sensors, addons up to date.

**Comment by adam-cobb** [comment]
It seems to be OK now generally I think, it's a bit inconsistent but that seems to be on the Eufy side as I sometimes don't get notifications from the Eufy app either
