### ISSUE TITLE
Eufy Security & JS-Zwave both using port 3000

### ISSUE THREAD

**Issue by MuppetRus** [fuatakgun/eufy_security#1168]
Hi,
Novice here and I added Eufy Security this week and its clashing with port 3000 on my JS Wave setup that also uses port 3000 if I disable either the Eufy Security then my Wave lights work and the Eufy Security add on stops and vice a versa......any pointers of how to fix this would be much appreciated.

Kind regards
Bruce

**Comment by fuatakgun** [comment]
Please reach out to bropat as he is driving the add-on development and I don't have any control over port management

**Comment by MuppetRus** [comment]
Will do thank you very much

Sent from Gmail
***@***.***
