### ISSUE TITLE
unable to remove camera from integration

### ISSUE THREAD

**Issue by Gronda74** [fuatakgun/eufy_security#1175]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

I have removed a camera from my Eufy Homebase. I have checked the Eufy security account online and the camera is no longer listed in the account. The camera is still listed in Home Assistant and when I try to delete the camera I get an error message of: 

Eufy Security - Error
Device is still accessible on account, cannot be deleted!

**To reproduce**

Steps to reproduce the behaviour:
1. Go to 'Settings > Devices & Services > Eufy Security'
2. Click on 'Devices'
3. Select the camera that is no longer linked to the Homebase and click Delete
4. The camera isn't deleted
5. A notification is listed that the device is still accessible on account, cannot be deleted

**Expected behavior**

The camera should be deleted.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS
- Home Assistant Core Version: core-2024.7.2
- Eufy Security Add-on Version: eufy-security-ws (1.8.0-2)
- Eufy Security Integration Version: 8.0.2

Hardware Information;
- Camera Model: S300 (eufycam 3c)

- Live Streaming Protocol (RTSP/P2P): RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
 
[home-assistant.log](https://github.com/user-attachments/files/16197664/home-assistant.log)
 

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
2024-07-12 17:33:49.043	INFO	eufy-security-ws:eufy-security-client	[http] [Station.onConnect] Connected to station T8170T1023310CF3 on host 192.168.1.254 and port 21723
2024-07-12 17:34:19.950	INFO	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Initiated closing of connection to station T8170T1023310CF3 for saving battery.
2024-07-12 17:34:19.951	INFO	eufy-security-ws:eufy-security-client	[http] [Station.onDisconnect] Disconnected from station T8170T1023310CF3
2024-07-12 17:35:02.126	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 47356 code: 1006 reason: Abnormal Closure
2024-07-12 17:35:42.821	ERROR	eufy-security-ws:eufy-security-client	[http] [HTTPApi.getVoices] Get Voices - Response code not ok {
  code: 20028,
  msg: 'Failed to request.',
  data: {
    code: 20028,
    msg: 'Failed to request.',
    data: null
  },
  deviceSN: 'T8161P102236121C'
}

- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by migueldc73** [comment]
I got the same issue. Upgraded my homebase from 2 to 3, bought new cameras, removed the old ones in my account.
But here in HA, I can't delete the removed devices.

**Comment by fuatakgun** [comment]
Go to the device page and click delete?

**Comment by Gronda74** [comment]
That’s what I did, went to the device page, clicked delete, got the error message. The camera is not in the account.

**Comment by fuatakgun** [comment]
Error from add-on?

**Comment by Gronda74** [comment]
It seems to be. Oddly the camera isn't showing in my Devices list when I go there first. But if I go into the integration it shows as a device and then click on delete and nothing happens but the error message then shows in the notifications and the device is then showing in the Devices list. When I click on the "known issues" for the integration it brings me here to github.

**Comment by migueldc73** [comment]
So, my old EUFY devices could finally be removed after someone bought the old set and added them to their account. It seems that the cloud only then effectively releases them after some other account adds them.
My 2cts, the problems are not related to this integration, but to the EUFY cloud.

**Comment by dblevins21** [comment]
Same issue here. Removed 2 cameras from my eufy account but cannot delete them from HA. I receive the same error message as previously mentioned in this thread. I can confirm that logging into my Eufy account online confirms that both cameras in question are not active on my account. Please advise!

**Comment by fuatakgun** [comment]
sorry folks, I do not have any advice other than disabling your cameras. if add-on is passing these cameras to the integration, integration would of course add them to home assistant.
