### ISSUE TITLE
Homebase needed?

### ISSUE THREAD

**Issue by ivovdgrift** [fuatakgun/eufy_security#118]
Possibly a stupid question. Do I need a homebase for this addon to work in HA? I currently only own a wired doorbell, and was hoping to hook that up to Home Assistant.

Anyways, thanks for the great work on the addon, really appreciated!!

**Comment by ivovdgrift** [comment]
Thanks, I have :)

Unfortunately the logs keep telling me no devices found.

`2021-11-17 14:31:39.637  INFO Eufy Security server listening on port 3000 
2021-11-17 14:31:41.026  INFO No stations found. 
2021-11-17 14:31:41.338  INFO No devices found. 
2021-11-17 14:31:41.657  INFO Push notification connection successfully established `

I created an additional account to which I shared my doorbell, as a guest, not an admin (is that needed?). If i log onto the app on that account, I can successfully see the doorbell.

**Comment by fuatakgun** [comment]
give it a try with admin rights

**Comment by ivovdgrift** [comment]
I have, unfortunately same issue. I have this doorbell https://us.eufylife.com/products/t8200
Is there anything else I could try?

**Comment by fuatakgun** [comment]
Try to remove the devices from new account and share them back again with admin rights. This had solved many issues earlier.

**Comment by ivovdgrift** [comment]
@fuatakgun , that solved it :) Thank you so much for the help!
