### ISSUE TITLE
Smart Lock T85L0 detected but not working

### ISSUE THREAD

**Issue by Rhys79** [fuatakgun/eufy_security#1182]
Smart lock model T85L0 is detected, but does not connect, and show up with alarm controls (Online, Reset and Trigger alarm 1 & 2) rather than lock controls.

Debug Device -

Properties
name: Front Door
model: T85L0
serialNumber: T85L07102424096C
hardwareVersion: V2
softwareVersion: 1.0.6.7
type: 201
stationSerialNumber: T85L07102424096C
Commands

Debug -

Properties
name: Front Door
model: T85L0
serialNumber: T85L07102424096C
type: 201
hardwareVersion: V2
softwareVersion: 1.0.6.7
connected: false
Commands

**Comment by vedusmar** [comment]
Yeah I have the same issues

**Comment by fuatakgun** [comment]
work with bropat to add support. https://bropat.github.io/eufy-security-client/#/supported_devices

it is not supported
