### ISSUE TITLE
Deprecated alias

### ISSUE THREAD

**Issue by GeertLaer** [fuatakgun/eufy_security#1185]
I get this out of my logs:

Logger: homeassistant.backports.enum
Source: helpers/deprecation.py:197
First occurred: 5:05:32 PM (1 occurrences)
Last logged: 5:05:32 PM

StrEnum was used from eufy_security, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'eufy_security' custom integration

and:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 5:05:36 PM (19 occurrences)
Last logged: 5:05:36 PM

Detected code that calls async_forward_entry_setup for integration, eufy_security with title: 0.0.0.0 and entry_id: 44aff8fa1340a37dc8c86a99e151a6d7, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.
Detected code that calls async_forward_entry_setup for integration eufy_security with title: 0.0.0.0 and entry_id: 44aff8fa1340a37dc8c86a99e151a6d7, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by fuatakgun** [comment]
should be fixed long ago
