### ISSUE TITLE
Add support for Indoor Cam C220 (T8W11P) - (The new Indoor Cam E220 (T8410; Indoor Cam Pan&Tilt 2K))

### ISSUE THREAD

**Issue by jonnykking** [fuatakgun/eufy_security#1189]
Just picked up the newer Eufy C220 Indoor Security Camera and noticed there is no support for this one yet. Any future plans to add it? Currently the integration picks it up but does not have most of the features. 
![Screenshot 2024-08-20 161539](https://github.com/user-attachments/assets/746fe5df-2cbc-4584-8285-92ce1ef0c876)

Thanks for your awesome project. Have a great day :)

**Comment by baget** [comment]
Joining this request too

**Comment by TomerZa** [comment]
Also have the same issue

**Comment by wrowlands3** [comment]
Exactly the same with the Indoor Cam C210 (T8419)

**Comment by MBerantzino** [comment]
Just chiming in - I also have 2x Indoor Cam C210 and would love support for this.

**Comment by ptums** [comment]
Also joining in on this request :)

**Comment by Adribreezy** [comment]
Same here, join on this request 👍

**Comment by Mytonn** [comment]
+1

**Comment by ferguilo** [comment]
+1

**Comment by grex023** [comment]
C210 and C220 +1

**Comment by TomCZK** [comment]
+1 
would appreciate privacy mode switch at least C220

**Comment by fuatakgun** [comment]
work with bropat to add support. https://bropat.github.io/eufy-security-client/#/supported_devices
