### ISSUE TITLE
Feature Request: Eufy doorbell button service

### ISSUE THREAD

**Issue by itaysp** [fuatakgun/eufy_security#119]
Hey,
It would be nice to have (I'm not sure if it's possible) a service to trigger a doorbell press event on the device itself.

Scenario:
A generic button is connected to HA.
On a button press it will trigger the doorbell service,
and the outcome should be as I pressed the original doorbell button.

Currently I can change the state of the 'doorbell_ringing_sensor' to True, and trigger the doorbell event automations,
but I would like to also receive a notification in the eufy app and to get the homebase ring.

I'm not sure it's possible.. And if not, maybe at least adding a service for the homebase ring is possible?

Thanks

**Comment by fuatakgun** [comment]
First is definitely not possible :-)
Second, do you have a feature in homebase ring? i didn't know that, as i own 2c cameras, no doorbell

**Comment by itaysp** [comment]
yes, the homebase can act like a Chime
![image](https://user-images.githubusercontent.com/6291848/142437371-0ecd84f2-85b9-4ade-886d-e7f7c4bbcae7.png)

A dorbell press can even trigger the my Echo dot (and echo show with a video)

**Comment by fuatakgun** [comment]
Homebase can act like a chime, but there is no action (button) to initiate a chime.

i checked the middleware if this is supported and there is nothing about it here: https://github.com/bropat/eufy-security-ws

Please open a new issue there if this is doable

**Comment by itaysp** [comment]
Thanks!
