### ISSUE TITLE
Motion Sensors (T8910) not communicating with HA

### ISSUE THREAD

**Issue by RaiTech-Dev** [fuatakgun/eufy_security#1192]
**Describe the bug**

Motion Sensors are detecting on the Eufy app and homebase but not able to see the motion detection in HA. Only items having the issue are the motion sensors. All other items look to be working. 

**To reproduce**

1) trigger the motion sensor 
2) confirm the motion was detected in the Eufy app
3) check the device on Home Assistant under devices and logbook. No entry was made. 

Hardware Information;
-Motion Sensors (T8910)  

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:63
integration: Eufy Security (documentation, issues)
First occurred: 11:04:31 PM (1 occurrences)
Last logged: 11:04:31 PM

Error doing job: Exception in callback WebSocketClient._on_close(<Task cancell...client.py:62>>) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 81, in _on_close
    self.close_callback(future)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 317, in _on_close
    _LOGGER.debug(f"on_close - executed - {future} = {future.exception()}")
                                                      ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 63, in _process_messages
    async for msg in self.socket:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 376, in __anext__
    msg = await self.receive()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 307, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 681, in read
    return await super().read()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

- Would you share your device with me in case further debugging required? (Yes/No):Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.
[home-assistant_eufy_security_2024-08-21T05-12-54.445Z.log](https://github.com/user-attachments/files/16686273/home-assistant_eufy_security_2024-08-21T05-12-54.445Z.log)
[home-assistant_eufy_security_2024-08-21T05-12-54.445Z.log](https://github.com/user-attachments/files/16686277/home-assistant_eufy_security_2024-08-21T05-12-54.445Z.log)

**Comment by gonzoweb-git** [comment]
I have exactly the same problem with a newly added sensor only.
The existing motion sensors are the same model (T8910) and the same firmware (2.0.1.1).
These work fine.
The new sensor shows "This entity is unavailable" on all entities

**Comment by gonzoweb-git** [comment]
> I have a similar problem with a newly added sensor only. The existing motion sensors are the same model (T8910) and the same firmware (2.0.1.1). These work fine. The new sensor shows "This entity is unavailable" on all entities. Motion is showing detected in the logbook. 

UPDATE: This seems to be connected with the Homeassistant version update. The update was done a few days ago before the sensor was added. 
A complete shutdown and restart of the Homeassistant Virtual Machine has activated the sensors and they are now working fine.

**Comment by RaiTech-Dev** [comment]
Issue has been resolved
