### ISSUE TITLE
HA eufy-security-ws camera not stream and not show motion event

### ISSUE THREAD

**Issue by githubsharezone** [fuatakgun/eufy_security#1195]
I have eufy home base with 5 cameras and various window and motion sensors 

the sensors work correctly but the cameras do not, neither does the motion detection nor the streaming work if I want to view it from home assistant. I followed the procedure by installing go2rtc webrtc . I can see them for a moment but afterwards the status remains in preparing and it no longer works I have to restart the whole raspberry 

can you help me?

Translated with DeepL.com (free version)

**Comment by Ascariota** [comment]
Same issue
