### ISSUE TITLE
RTSP Simple Server Add-on installtion dose not work

### ISSUE THREAD

**Issue by Sprocket02** [fuatakgun/eufy_security#1197]
I had the addon installed for a long time. After a few errors, I wanted to reinstall it. Now I get the following error message. I have the current (stable 2024.8.3) standard installation of HA running on a Raspberry 4.

Add-on could not be installed
Can't install aler9/rtsp-simple-server:v0.17.6: 404 Client Error for http+docker://localhost/v1.45/images/create?tag=v0.17.6&fromImage=aler9%2Frtsp-simple-server&platform=linux%2Farm64: Not Found ("manifest for aler9/rtsp-simple-server:v0.17.6 not found: manifest unknown: manifest unknown")

**Comment by ghariosk** [comment]
Experiencing the same

**Comment by RikSt** [comment]
Same here

**Comment by wtrdk** [comment]
I experience the same problem.

**Comment by Jayseaa** [comment]
Same problem here

**Comment by fuatakgun** [comment]
But why do we need this add-on anymore? I noticed that there are wrong references in readme file, but steps are clear, no more rtsp simple add-on

**Comment by Sprocket02** [comment]
> But why do we need this add-on anymore? I noticed that there are wrong references in readme file, but steps are clear, no more rtsp simple add-on

Sorry, but which steps are clear? The documentation still refers to the addon. What do I have to do to make it work without the addon?

**Comment by fuatakgun** [comment]
Where is it listed as required?
1. Eufy add-on 
2. Go2rtc add-on (replaces rtsp simple server add-on)
3. Integration itself
4. Dashboard setup


![Screenshot_2024-10-04-16-20-41-885_com.github.android-edit.jpg](https://github.com/user-attachments/assets/c65da797-eed0-4c18-9a20-0e8ec3e1d709)
