### ISSUE TITLE
Battery status not updating when charging

### ISSUE THREAD

**Issue by derekoharrow** [fuatakgun/eufy_security#1199]
**Describe the bug**

I have a T8210 Eufy doorbell. When in use the integration shows the correct battery percentage. However, when I put the doorbell on charge, the battery status doesn't change in the integration. It does update in the Eufy IOS app.

**To reproduce**

1. Check battery charge status
2. Put doorbell on charge
3. See battery status doesn't update in integration, but does in Eufy app.

**Expected behavior**

Battery status in the integration should update when charging, like it does in the IOS app.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):  Docker container
- Home Assistant Core Version: core-2024.9.1
- Eufy Security Add-on Version: 
- Eufy Security Integration Version: v8.0.3

Hardware Information;
- Camera Model: T8210 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - **See attached eufy.txt file**.
  
- Would you share your device with me in case further debugging required? (No):

[eufy.txt](https://github.com/user-attachments/files/16923051/eufy.txt)

**Comment by sloanlipman** [comment]
I'm seeing the same behavior in the solo cam S230. Both the battery percentage and the times that the cameras are charging via solar power are different in Home Assistant

**Comment by sloanlipman** [comment]
I'm seeing the same behavior in the solo cam S230. Both the battery percentage and the times that the cameras are charging via solar power are different in Home Assistant

**Comment by msevestre31** [comment]
Hi

I have 3 2C cameras and a home base 2.
2 of my 2C are plugged to solar panels.
I am also observing this "non updating" behavior in HA while the eufy app was showing the proper information.

Actually, I found out that, in HA, the battery % level is updating only when the charging state is updating (Eufy app is getting real time data from the homebase with no issue).

It is obvious in HA if you look the Charging status & Battery Percentage data of a same camera in the same graph.

<img width="1490" alt="Capture d’écran 2024-10-13 à 20 01 25" src="https://github.com/user-attachments/assets/668d07f6-fa4a-4d4c-973c-8499a4f677ea">

**Comment by fuatakgun** [comment]
I am facing the same issue and I do not how to fix or the root cause of the issue, my observations;
- it is not updated into add-on when battery level has been updated, add-on relies on push notifications and this is not received via push.
- it could be updated via cloud pull but not sure.
- in any case, integration is behaving as a middleware between add-on and home assistant, you should get consultation from bropat if this is somehow fixable.
