### ISSUE TITLE
Lock not updating states

### ISSUE THREAD

**Issue by johnrobledo** [fuatakgun/eufy_security#120]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
My Eufy Lock (Set up by Fuat) is not reflecting the correct state but is correctly opening/locking the lock.

**To Reproduce**

**Expected behavior**
Expected lock to change to open when open

**Screenshots**

**Hardware Information about Home Assistant
Rasberry Pi 4 on SSD running HassOS
**Hardware Information about Cameras
Eufy Smart Lock touch with wifi bridge

**Additional context**

**Comment by boctok** [comment]
I was just about to post this same issue. I was in the process of setting up a notification automation for the door lock after a certain time at night, but the lock does not provide the state. I can lock and unlock from the entity page, but nothing is reflected in the entity state.

**Comment by johnrobledo** [comment]
strange...lets hope Mr. Akgun sees this

**Comment by fuatakgun** [comment]
Let's work on this issue on weekend, i need one of yours locks to be shared with me :-)

And please be at home, i don't want to lock/unlock while you are away :-)

**Comment by johnrobledo** [comment]
Ok np...i will share it (Front Door) and don't work about unlocking it...i live in a gated community and can lock the doorknob

**Comment by NeoSaigon** [comment]
I can't lock/unlock from home assistant neither.  All the entities show up, lock/unlock doesn't work and states aren't updated.  Battery is updated properly however.  I'm available if you need the lock.

**Comment by johnrobledo** [comment]
Hi...just wondering if you could work on it today

**Comment by boctok** [comment]
> I can't lock/unlock from home assistant neither. All the entities show up, lock/unlock doesn't work and states aren't updated. Battery is updated properly however. I'm available if you need the lock.

If you look at the lock entity, and click on the settings (upper right corner), do you see the "Lock" and "Unlock" options? I can lock and unlock by clicking one of those. I have a custom button card (HACS, "button card") that I'd like to use, but it requires the state of the lock, which I cannot get.

![entity front door lock](https://user-images.githubusercontent.com/5306739/142740302-772f1a1d-71e8-484e-add2-080b5eb091fe.png)
![lock settings](https://user-images.githubusercontent.com/5306739/142740321-6d7f8415-1a20-4690-98b5-6c8b6dc59834.png)
![door lock card](https://user-images.githubusercontent.com/5306739/142740325-80d86470-d33c-4fe1-8622-eaf8ed7ae071.png)

**Comment by NeoSaigon** [comment]
![eufy](https://user-images.githubusercontent.com/2953750/142740427-4872a4a2-089a-4b02-92ae-05e5cb68fc98.png)

Yeah, the entities show up fine, but they don't do anything

**Comment by johnrobledo** [comment]
Hi guys...can you create a separate issue? This one is about not seeing the state, not being unable to lock/unlock

**Comment by fuatakgun** [comment]
@johnrobledo , can i work on it now?

**Comment by fuatakgun** [comment]
> Hi guys...can you create a separate issue? This one is about not seeing the state, not being unable to lock/unlock

they are somehow related, we can fix together

**Comment by fuatakgun** [comment]
fixed in latest version, thanks @johnrobledo , I had unlocked and locked 1 cycle.

**Comment by johnrobledo** [comment]
Thanks so much
