### ISSUE TITLE
Failed to unload 

### ISSUE THREAD

**Issue by Ascariota** [fuatakgun/eufy_security#1204]
Since the last update my integration work at the startup but after I have "Failed to unload" and work only if I restart all HA.

Eufy Version 
8.0.3
Core
2024.9.1
Supervisor
2024.09.1
Operating System
13.1
Frontend
20240906.0

Logs :

`2024-09-14 19:29:47.193	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleDataControl] Handle DATA CONTROL - CMD_NOTIFY_PAYLOAD StorageInfo HB3 update {
  stationSN: 'T8030P2323330CC9',
  body: {
    body_version: 1,
    storage_days: 274,
    storage_events: 54741,
    con_video_hours: 0,
    format_transaction: '',
    format_errcode: 0,
    hdd_info: {
      serial_number: '50026B775409B4C3',
      disk_path: '/dev/sda',
      disk_size: 122880,
      system_size: 2099,
      disk_used: 70359,
      video_used: 64739,
      video_size: 105937,
      cur_temperate: 41,
      parted_status: 1,
      work_status: 0,
      hdd_label: 'hdd_157CDA432ED504F970B534445AA954D3',
      health: 0,
      device_module: 'KINGSTONSV300S37A120G',
      hdd_type: 1
    },
    move_disk_info: {
      disk_path: '',
      disk_size: 0,
      disk_used: 0,
      part_layout_arr: [],
      data: []
    },
    emmc_info: {
      disk_nominal: 0,
      disk_size: 15974,
      system_size: 3158,
      disk_used: 2953,
      data_used_percent: 19,
      swap_size: 2048,
      video_size: 10299,
      video_used: 22,
      data_partition_size: 12932,
      eol_percent: 1,
      work_status: 0,
      health: 0
    }
  }
}
2024-09-14 19:29:47.194	DEBUG	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 532... {
  stationSN: 'T8030P2323330CC9',
  remoteAddress: '10.0.4.27',
  remotePort: 27672,
  dataType: 'CONTROL',
  seqNo: 532
}
2024-09-14 19:34:24.509	DEBUG	eufy-security-ws:eufy-security-client	[push] [PushClient.sendHeartbeat] Push client - Sending heartbeat... {
  streamId: 139
}
2024-09-14 19:34:24.510	DEBUG	eufy-security-ws:eufy-security-client	[push] [PushClient.buildHeartbeatPingRequest] Push client - heartbeatPingRequest {
  streamId: 139,
  request: '{"last_stream_id_received":139}'
}
2024-09-14 19:34:24.531	DEBUG	eufy-security-ws:eufy-security-client	[push] [PushClient.handleHeartbeatAck] Push client - Heartbeat acknowledge {
  message: '{"tag":1,"object":{"lastStreamIdReceived":138}}'
}`

**Comment by daandb93** [comment]
Same issue here.

**Comment by hacshacdgacs** [comment]
Same here, my cameras are unable to restart their rtsp stream because of this error

**Comment by ancjsd** [comment]
Same issue here.

**Comment by SnitchRiver** [comment]
Same issue here

**Comment by Blueion76** [comment]
Same issue on my end

**Comment by tateu** [comment]
If you're comfortable editing code:

https://github.com/fuatakgun/eufy_security/blob/a8ad909f9bf984c6a5b38b62de0ddb3a7c2a9396/custom_components/eufy_security/__init__.py#L69

change

```
unloaded = await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
to
unloaded = await hass.config_entries.async_unload_platforms(config_entry, PLATFORMS)
```

on my system, it is located here: /usr/share/hassio/homeassistant/custom_components/eufy_security

but I'm running on Debian, not HAOS

**Comment by fuatakgun** [comment]
@tateu could you please raise a pull request with this change?

**Comment by fuatakgun** [comment]
raised a PR and merged it, will be released soon
