### ISSUE TITLE
Can't show video feed

### ISSUE THREAD

**Issue by Inrego** [fuatakgun/eufy_security#121]
**Describe the bug**
I've recently added my first device - a 2k battery doorbell with homebase. I've set it up following your guide, and I get the entities and all. The camera lovelace card also shows the snapshot from the recording last time a person was detected.
Since it's a battery doorbell (doesn't support RTSP I think), I've also installed the RTSP add-on.

When I call `eufy_security.start_livestream`, the default camera view goes completely grey, while the WebRTC card shows the following error:
`ERROR: NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="hvc1.016000"') is unsupported.`

**To Reproduce**
1. Set up 2k battery doorbell
2. Follow setup instructions from readme.md
3. Call `eufy_security.start_livestream`

**Expected behavior**
Camera feed to stream

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Eufy 2k battery doorbell
- Live Streaming Protocol: P2p with RTSP addon in HA.

**Comment by fuatakgun** [comment]
Can you check doorbell streaming quality with low?

**Comment by Inrego** [comment]
Didn't change anything. Any other recommended settings? Didn't actually look through much of it, so it's all on default.

**Comment by Inrego** [comment]
Wait now I'm seeing errors in log about ffmpeg not running.

```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 673, in ping
await self._send_frame(message, WSMsgType.PING)
File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 650, in _send_frame
self._write(header + message)
File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 660, in _write
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-11-18 22:09:26 ERROR (Thread-66) [custom_components.eufy_security] eufy_security Doorbell video_thread exception: [Errno 32] Broken pipe- traceback: Traceback (most recent call last):
File "/config/custom_components/eufy_security/camera.py", line 162, in write_bytes_to_ffmeg
self.ffmpeg.process.stdin.write(frame_bytes)
BrokenPipeError: [Errno 32] Broken pipe
2021-11-18 22:09:26 ERROR (Thread-66) [custom_components.eufy_security] eufy_security Doorbell - video ffmpeg error - ffmpeg is not running
```

**Comment by fuatakgun** [comment]
this is about h265 and it is not supported by webrtc and currently, native streaming inside Home Assistant is not working for the integration.

Please follow here: https://github.com/fuatakgun/eufy_security/issues/102

**Comment by Inrego** [comment]
Ok, so just to be clear. Right now, it's not possible to get the camera feed to HA? Which is also fine, since it looke like you're working on it. Just curious if I missed a workaround.

**Comment by fuatakgun** [comment]
Using webrtc, you can have low quality (h264 codec) video stream. If your camera supports h265 media codec, it is not supported by WebRTC. Otherwise, you have to wait for native HA streaming
