### ISSUE TITLE
Motion detection not kicking in on Solocam S230

### ISSUE THREAD

**Issue by sloanlipman** [fuatakgun/eufy_security#1210]
If I walk in front of one of my cameras and see that the IR light kicks in, but the integration is not picking up motion on one of my cameras (the other one seems like it might be picking it up).  In other words, the "Motion detected" and "Person detected" sensors but are off.

**To reproduce**

1) Go to settings
2)  Click Devices & services
3) Open the Eufy security integration
4)  Choose one of the devices
5) Walk in front of the camera.
6) Observe that the sensor states don't change.

**Expected behavior**
The motion/person sensors turn on.

**Additional information**

Home Assistant Installation Type (OS - Supvervised - Core):
Home Assistant OS

Home Assistant Core Version:
core-2024.9.2

Eufy Security Add-on Version:
1.9.0

Eufy Security Integration Version:
8.0.4

Hardware Information;

Camera Model: Solocam S230

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
[home-assistant_eufy_security_2024-09-21T01-39-25.332Z.log](https://github.com/user-attachments/files/17082408/home-assistant_eufy_security_2024-09-21T01-39-25.332Z.log)

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No):
No

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by fuatakgun** [comment]
Did you enable full push notifications on the mobile app for motion events?

**Comment by sloanlipman** [comment]
I have automations set up to only put me on one of the 3 custom modes. 2 and 3 give me notifications, but 1 does not. I was testing this in 2 and 3. One of my cameras was sending me push notifications AND was updating the state in HA. The other camera did neither.

**Comment by fuatakgun** [comment]
The integration fully relies on push notifications for events (motion, person etc).

Can you confirm if you are receiving notifications into your mobile app from the second one?

**Comment by sloanlipman** [comment]
According to my settings, I should have been getting push notifications when I was testing this. It looks like the camera that's not working not only isn't sending notifications, it doesn't look like it's saving any recordings in the Eufy Security app.

**Comment by sloanlipman** [comment]
According to my settings, I should have been getting push notifications when I was testing this. It looks like the camera that's not working not only isn't sending notifications, it doesn't look like it's saving any recordings in the Eufy Security app. 

Update: no idea what I did, but my camera is saving events on the Eufy Security app now. Since the other cameras are working fine with this integration, the questionable one should hopefully be good now.

**Comment by sloanlipman** [comment]
@fuatakgun while I'm on the topic though, I'm noticing that the reported battery percentage as well as the charging state aren't matching what I see in the Eufy app. Let me know if you want me to open a separate issue for this.
