### ISSUE TITLE
Doorbell send speak message and person recognition

### ISSUE THREAD

**Issue by heula** [fuatakgun/eufy_security#1212]
Hello everyone,

I am a Homey user who is slowly transferring everything to Home Assistant.
I have transferred almost everything from Eufy security to Home Assistant but there are two things that I do not see in Home Assistant at the moment.
Maybe I did not look properly and missed them but I miss the option to send a pre-recorded message to the doorbell when someone rings the doorbell.
I would like to send a pre-recorded message when someone is home but also when I am not home.
In Homey I can easily select this option and it works fine.
Is this already possible in Home Assistant?

The second option that I miss is recognizing people that I have set as known persons in the Eufy app.
I do not yet see an option that when someone rings the doorbell and is a known person, it can be said via TTS that a certain person is at the door or that a notification can indicate that person x has been seen.
I am also used to being able to use this option via Homey.

I hope these options can be used in Eufy security for Home Assistant too.

Thanks.
![2024-09-24 17_57_16-Homey 2023 Alex en Astrid](https://github.com/user-attachments/assets/12508d3b-e700-4435-b9a7-e7956e89b078)

**Comment by fuatakgun** [comment]
You are right, both of these are missing in the home assistant implementation. Sadly, having it on one ecosystem will not make it happen automatically in another ecosystem.

**Comment by heula** [comment]
Are there any plans to implement this in the (near) future?
For now I still use Homey for missing parts but hope to be able to switch to Home Assistant only one day.
This does not depend on the Eufy addon alone. 😉 

Thanks.

**Comment by elvenstof** [comment]
+1 having the camera/doorbell as tts targets would be great.
