### ISSUE TITLE
[Question]: Where to enter captcha? (and also 2FA)

### ISSUE THREAD

**Issue by RogerHartmann** [fuatakgun/eufy_security#1217]
I need some help how to enter the captcha. Also 2FA would be required, although I just disabled 2FA for now.

I have confirmed I can log into the eufy mobile app with my account. I get these log entries when I try in HomeAssistant:

2024-09-27 16:41:26.634 INFO eufy-security-ws:eufy-security-client [main] [EufySecurity._initializeInternals] Authentication properties changed, invalidate saved cloud token.
2024-09-27 16:41:28.120 INFO eufy-security-ws Eufy Security server listening on host 0.0.0.0, port 3000
2024-09-27 16:41:28.270 INFO eufy-security-ws:eufy-security-client [http] [HTTPApi.login] Please send requested captcha to proceed with authentication

but I do not get any captcha question in HomeAssistant. Neither in the browser, nor in the HomeAssistant mobile app. Nothing in HomeAssistant->Settings.
https://github.com/bropat/eufy-security-ws/issues/320#issuecomment-2130424699 suggested to change the
password in the eufy mobile app to trigger such a question. I did this, but also no success.

I have installed eufy-security-ws v1.9.0 in HomeAssistant core 2024.9.3.

thanks for hints, suggestions, ....

**Comment by LongTimeAgoNL** [comment]
Sadly I encountered the same issue when setting up everything. The captcha is nowhere to be found.

**Comment by RogerHartmann** [comment]
thanks for the hints @LongTimeAgoNL , I cana at least check the "trusted device name" topic. I do not have an eufy base station, I would directly connect to cameras. Or do I need such an eufy base station?

**Comment by RogerHartmann** [comment]
after I entered the "trusted device name", for some reason, I did not have to do the captcha... so I am now connected to the camera, which is also named "station" (which should answer the station question of mine above).
So it looks like it is working now, but I have no idea if that is only temporarily or will do so longer....
