### ISSUE TITLE
Stuck on Installation (No Log Info)

### ISSUE THREAD

**Issue by rampaigewow** [fuatakgun/eufy_security#122]
Hi I am having trouble with installation.

I've added my Eufy account info (email, password, and country)...Saved...But when I check the logs page there is nothing. I keep hitting refresh and nothing shows up.

I tried using my Eufy Admin account. I've also tried using a shared eufy guest account (That would be specifically for HA if I got it to work).

Are there troubleshooting steps for this?

**Comment by fuatakgun** [comment]
Are you sure you had started the add on? There should be something visible there

**Comment by rampaigewow** [comment]
Ya know...I used to always  joke about how when most people have IT issues, the first question help desk usually asks is, "Is the device plugged in?" - I always that was funny.

I think I had one of those moments here....Nope, I never started it. I hit start and sure enough everything was there.

Thanks for the help, back to setup!
