### ISSUE TITLE
Add support for Eufy smart lock C33 (Model No. T85L0)

### ISSUE THREAD

**Issue by tommytaoli** [fuatakgun/eufy_security#1220]
**Is your feature request related to a problem? Please describe.**
Eufy smart lock C33 (Model No. T85L0) unsupported

**Describe the solution you'd like**

Similar Diagnostic functionality support as other smart lock device

**Describe alternatives you've considered**
N/A

**Additional context**
Current version can detect device from eufy security but it's missing lock/unlock functionalities. 
![image](https://github.com/user-attachments/assets/496aa9e1-69db-4803-9e21-824adaa410ec)

**Comment by fuatakgun** [comment]
Can you check diagnostic entities? They should be disabled, please enable and send another screenshot

**Comment by tommytaoli** [comment]
Here are the list of the entities in diagnostic:
![image](https://github.com/user-attachments/assets/7cc99f8f-daa6-4226-b9ce-29fcc9d7a797)

It's missing lock, lock status, and battery percentage.

**Comment by fuatakgun** [comment]
Please work with bropat to add support.
https://bropat.github.io/eufy-security-client/#/supported_devices
