### ISSUE TITLE
quick response how to know the voice_id of custom messages

### ISSUE THREAD

**Issue by Joerivanrokeghem** [fuatakgun/eufy_security#1222]
hi,

how to find the voice_id of custom messages? I can't find them in the debug log. Or in older issues.

thanks!

**Comment by Joerivanrokeghem** [comment]
fix:

in the eufy app select the quick response as auto answer when someone is ringing the doorbell.
then check the add on log for ringAutoResponseVoiceResponseVoice. the number next to it will be the voice_id.
afterwards you can disable the setting of auto answer in the app.

**Comment by gvago** [comment]
Important to mention that to find the voice_id. You'll need to decode base64.
I just had to do this and wrote an article for anyone needing assistance. 
https://medium.com/@guyvago/how-to-use-custom-voice-recordings-with-eufy-doorbell-in-home-assistant-297a2e84e848

**Comment by gvago** [comment]
Definitely. I actually thought about branching and adding this auto discovery, convertion and option and adding my contribution to your great work. It might still happen.
