### ISSUE TITLE
Constant  Reconfiguration needed

### ISSUE THREAD

**Issue by nmeliasp** [fuatakgun/eufy_security#1224]
I'm constantly being asked to  reconfigure this integration. Eufy Security: Captcha is being asked for every minute. My environment is below

Core
2024.10.2
Supervisor
2024.10.2
Operating System
13.2
Frontend
20241002.3

**Comment by mpino61** [comment]
i have the same problem, I enter the captcha correctly but it keeps asking for a new one.

**Comment by emiljust** [comment]
Same here

**Comment by mgscox** [comment]
Same

**Comment by skwho** [comment]
The same issue as well 😓😓

**Comment by GorySawduster** [comment]
Same here.

**Comment by cm-mojo** [comment]
+1

**Comment by Reachushere** [comment]
And me

**Comment by zynfox** [comment]
Log details (WARNING)
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 7:39:11 PM (1 occurrences)
Last logged: 7:39:11 PM

Detected that custom integration 'eufy_security' sets option flow config_entry explicitly, which is deprecated at custom_components/eufy_security/config_flow.py, line 27: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/fuatakgun/eufy_security/issues

Logger: homeassistant.config_entries
Source: config_entries.py:668
First occurred: 7:34:18 PM (4 occurrences)
Last logged: 7:39:05 PM

Config entry '127.0.0.1' for eufy_security integration could not authenticate: Captcha code is required, please revalidate on Integrations page


Logger: homeassistant
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:63
integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 7:34:59 PM (3 occurrences)
Last logged: 7:38:44 PM

Error doing job: Exception in callback WebSocketClient._on_close() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 81, in _on_close
    self.close_callback(future)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 317, in _on_close
    _LOGGER.debug(f"on_close - executed - {future} = {future.exception()}")
                                                      ~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 63, in _process_messages
    async for msg in self.socket:
        await self._on_message(msg)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_ws.py", line 412, in __anext__
    msg = await self.receive()
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_ws.py", line 334, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_websocket/reader_c.py", line 112, in read
  File "aiohttp/_websocket/reader_c.py", line 109, in aiohttp._websocket.reader_c.WebSocketDataQueue.read
asyncio.exceptions.CancelledError

![image](https://github.com/user-attachments/assets/e6ca61e4-ad7b-4765-8900-bc1c4c44e8b1)

**Comment by fuatakgun** [comment]
This is not the debug log, it is an error log, I need full debug log

**Comment by cm-mojo** [comment]
2024-12-13 07:39:29.250	INFO	eufy-security-ws:eufy-security-client	[http] [HTTPApi.login] Please send requested captcha to proceed with authentication
2024-12-13 07:40:02.282	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 57114 code: 1000 reason: Normal Closure
2024-12-13 07:41:08.537	ERROR	eufy-security-ws:eufy-security-client	[http] [HTTPApi.login] Login - Response code not ok {
  code: 26006,
  msg: 'Email address or password incorrect.',
  data: {
    code: 26006,
    msg: 'Email address or password incorrect.',
    data: null
  }
}
2024-12-13 07:41:41.570	INFO	eufy-security-ws	Client disconnected with ip: 127.0.0.1 port: 51342 code: 1000 reason: Normal Closure
2024-12-13 07:41:56.757	INFO	eufy-security-ws:eufy-security-client	[http] [HTTPApi.login] Please send requested captcha to proceed with authentication

**Comment by cm-mojo** [comment]
This is the log with debug enabled

**Comment by cm-mojo** [comment]
I've renewed the credentials and it's working for me, even though no changes have been made to the password

**Comment by fuatakgun** [comment]
@cm-mojo , but the issue was very specific in your logs, login details were incorrect, not related to captcha.

```
msg: 'Email address or password incorrect.',
```

**Comment by cm-mojo** [comment]
The error was a captcha error in the front end though

**Comment by fuatakgun** [comment]
> The error was a captcha error in the front end though. It's only when you look at the logs that you actually see it was a password error

yes, inevitably, websites have to protect theirselves to abuse.
you might get a captcha when trying to login first time because you are first time user.
you might get a captcha when you fail multiple times because it has to validate that you are not a robot to let you try again.

this is a generic implementaton across login pages.

**Comment by thomasdg** [comment]
> I've renewed the credentials and it's working for me, even though no changes have been made to the password

How did you do so? I looked around but for some reason couldn't find it... Thanks!

**Comment by emiljust** [comment]
I changed up my password for the eufy app and changed it in the HA add-on and that did the trick for me!

**Comment by bato2000** [comment]
How can I change the password in the plugin? I can't find a way. Thank you very much.

**Comment by bato2000** [comment]
> Please help. How to change a password? Have the same problem. Changed home base and password, and now Home Assistant have an error I I cannot get eufy security working in HA

Good morning, you have to follow these steps and from there you can change the password.

![Image](https://github.com/user-attachments/assets/8799a7be-1ce8-41a2-bc85-d613da425791)
![Image](https://github.com/user-attachments/assets/5d8a1054-fc0b-49d3-9da3-980d73ea2af1)
![Image](https://github.com/user-attachments/assets/32196aeb-1d36-4c1e-b345-71751cf88b1a)

**Comment by GregAndryszczak** [comment]
Thanks. I found it yesterday late evening and now everything works



W dniu pt., 4 kwi 2025 o 10:12 bato2000 ***@***.***>
napisał(a):
