### ISSUE TITLE
Eufy Smart Lock C30 Detected in Home Assistant but Unable to Lock/Unlock - Only Debug Sensors Available

### ISSUE THREAD

**Issue by jeannicolasreyt** [fuatakgun/eufy_security#1227]
Thank you so much for your work. Here is the information relating to my issue. 

**Describe the bug**

I purchased a Eufy Smart Lock C30. I followed your tutorial to include it to my home assistant instance. Although the lock seems to be discovered, I can't lock or unlock. The only sensors are "Debug (device)" and "Debug (Station)". The five entities are disabled, and they are " Connected", "Reset Alarm" x2 and "Trigger Alarm" x2.

**To reproduce**

Adding the lock to HA.

**Expected behavior**

I expected to be able to lock and unlock.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Supervised
- Home Assistant Core Version: core-2024.10.2
- Eufy Security Add-on Version: 1.9.1
- Eufy Security Integration Version: 8.0.4

Hardware Information;
Smart Lock C30

- Would you share your device with me in case further debugging required? (Yes/No): Yes

Thanks so much!

**Comment by pipolaq** [comment]
Same problem here, with a C210. Recognized (I can choose the room) but nothing except the entities you mention @jeannicolasreyt !

**Comment by cheathj** [comment]
Same here anyone have ideas?

**Comment by fuatakgun** [comment]
please check Diagnostics sensors if there is any disabled entities if they are disabled, enable them and use them.
if there is no entity, work with bropat to add support. https://bropat.github.io/eufy-security-client/#/supported_devices
