### ISSUE TITLE
Not showing any additional devices 

### ISSUE THREAD

**Issue by byjdk** [fuatakgun/eufy_security#1233]
So I am unable to detect any other eufy products that I use in Home Assistant. The cameras are functional on the Eufy app, but for example my 2k pan and tilt indoor camera isnt appearing. Only 3 out of the 9 are visible.

**Comment by fuatakgun** [comment]
please check if you have shared the devices with your home assistant add-on account. furthermore, there is nothing I can do, you can read add-on logs if there is any error but integration itself does not skip any device intentionally.
