### ISSUE TITLE
image.XXXX_event_image really long delay

### ISSUE THREAD

**Issue by bvdkerkhof** [fuatakgun/eufy_security#1235]
When using the example automation with a captured image it is taking a long time before the image is being captured. The automation is too fast and sending an old image with the notification.

Is it possible to make this quicker at motion detection, or should we add a delay.

**Comment by rodgers86** [comment]
In the setup guide there is an alternative trigger you can use. L for your automation. That should solve the issue

**Comment by fuatakgun** [comment]
to be honest, we are relying on add-on to inform us on image changes, so I can do nothing from integration end.

you can ask bropat if there is anything can be done to make it faster.
