### ISSUE TITLE
Sensors for S3 Pro

### ISSUE THREAD

**Issue by tkirchbaum** [fuatakgun/eufy_security#1236]
I have added a new S3 Pro camera to my already working integration with various cameras, but I don’t see any sensors other than debug on/off. Will this cameras settings be updated or am I missing something?  Thanks!

**Comment by misc2000** [comment]
same here. I have a setup with 4x the new S3Pro (T8162) and a doorbell (T8210C).
Currently I only can use the doorbell in HA because the S3Pro Cams are shown in the integration but only with the debug sensor. Is there any change to support this new Cam type in the near future...
Thanks

**Comment by suds32** [comment]
Same here would be very keen to see if the S3 pro will be added ie fully supported

Thanks

**Comment by fuatakgun** [comment]
work with bropat to add support. https://bropat.github.io/eufy-security-client/#/supported_devices

**Comment by hedegren** [comment]
Same here, only a few sensors shows up.
<img width="696" alt="Screenshot 11" src="https://github.com/user-attachments/assets/cb98a6f8-1cc3-4d55-92cb-39a2fa3d0842" />
