### ISSUE TITLE
HA 2024.11

### ISSUE THREAD

**Issue by larsoss** [fuatakgun/eufy_security#1237]
Logger: homeassistant.const
Bron: helpers/deprecation.py:222
Eerst voorgekomen: 10:44:57 (6 gebeurtenissen)
Laatst gelogd: 10:45:05

STATE_ALARM_ARMED_AWAY was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_AWAY instead, please report it to the author of the 'eufy_security' custom integration
STATE_ALARM_ARMED_HOME was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'eufy_security' custom integration
STATE_ALARM_DISARMED was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'eufy_security' custom integration
STATE_ALARM_TRIGGERED was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.TRIGGERED instead, please report it to the author of the 'eufy_security' custom integration

**Comment by alexh3o** [comment]
I also have:
```
Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 22:44:45 (1 occurrences)
Last logged: 22:44:45

Config was used from eufy_security, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'eufy_security' custom integration

```
and
```
Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/__init__.py:210
integration: Alarm control panel (documentation, issues)
First occurred: 22:44:50 (1 occurrences)
Last logged: 22:44:50

Entity None (<class 'custom_components.eufy_security.alarm_control_panel.EufySecurityAlarmControlPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.
```

**Comment by z-master42** [comment]
Config see #1231 
Deprecated constants see #1240

**Comment by Dzoker2** [comment]
HI, same issue here.

TY

**Comment by misc2000** [comment]
same here after updating HA to 2024.11

**Comment by toto25550** [comment]
Hello
Same warning since last update

**Comment by fuatakgun** [comment]
fixed in latest revision, thanks

**Comment by z-master42** [comment]
I think this is still unfixed.

```
Logger: homeassistant.components.alarm_control_panel Source: components/alarm_control_panel/__init__.py:210 integration: Alarm control panel (documentation, issues) First occurred: 22:44:50 (1 occurrences) Last logged: 22:44:50 Entity None (<class 'custom_components.eufy_security.alarm_control_panel.EufySecurityAlarmControlPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.
```

**Comment by akicker** [comment]
+1

**Comment by Dzoker2** [comment]
Confirming too

`Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/__init__.py:210
integration: Alarm control panel (documentation, issues)
First occurred: 15:14:05 (8 occurrences)
Last logged: 15:14:20

Entity None (<class 'custom_components.eufy_security.alarm_control_panel.EufySecurityAlarmControlPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.'

**Comment by fuatakgun** [comment]
can you open a separate issue? I had focused on initial one only. just move into a new in an easy way.

**Comment by fuatakgun** [comment]
anyway, fixed it, give it a try after new revision is released

**Comment by z-master42** [comment]
That was fast. Thanks.

**Comment by Dzoker2** [comment]
Looks like fixed.

Thank you
