### ISSUE TITLE
3 new WARNINGS after updating to HA Core 2025.11

### ISSUE THREAD

**Issue by akicker** [fuatakgun/eufy_security#1239]
After updating to HA Core 2025.11 new warnings:

Logger: homeassistant.components.alarm_control_panel
Quelle: components/alarm_control_panel/__init__.py:210
Config was used from eufy_security, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'eufy_security' custom integration

Logger: homeassistant.const
Quelle: helpers/deprecation.py:222
STATE_ALARM_ARMED_AWAY was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_AWAY instead, please report it to the author of the 'eufy_security' custom integration
STATE_ALARM_ARMED_HOME was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'eufy_security' custom integration
STATE_ALARM_DISARMED was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'eufy_security' custom integration
STATE_ALARM_TRIGGERED was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.TRIGGERED instead, please report it to the author of the 'eufy_security' custom integration

Logger: homeassistant.components.alarm_control_panel
Quelle: components/alarm_control_panel/__init__.py:210
Entity None (<class 'custom_components.eufy_security.alarm_control_panel.EufySecurityAlarmControlPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.

**Comment by z-master42** [comment]
Dublicate of #1237.

**Comment by fuatakgun** [comment]
thanks, it is fixed
