### ISSUE TITLE
Please use releasess instead of git commits

### ISSUE THREAD

**Issue by MJHeijster** [fuatakgun/eufy_security#124]
**Is your feature request related to a problem? Please describe.**
I keep getting updates in HACS due to readme.md updates like https://github.com/fuatakgun/eufy_security/commit/3ddbb3ea92dcf37b0ca18325d134b1ea09737b29

**Describe the solution you'd like**
Please link updates to HACS with releases like other addons.

**Comment by fuatakgun** [comment]
Please check open issues before creating a new one: https://github.com/fuatakgun/eufy_security/issues/110
