### ISSUE TITLE
RTSP Simple Server Add-on

### ISSUE THREAD

**Issue by jwhengeveld** [fuatakgun/eufy_security#1241]
When installing the RTSP Simple Server Add-On in HAOS (through this repo: https://github.com/fuatakgun/rtsp_simple_server) 

I get this error:

`"Can't install aler9/rtsp-simple-server:v0.17.6: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=v0.17.6&fromImage=aler9%2Frtsp-simple-server&platform=linux%2Famd64: Not Found ("manifest for aler9/rtsp-simple-server:v0.17.6 not found: manifest unknown: manifest unknown")"`

On HAOS installed in a TrueNas docker environment. On a Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz

**Comment by jwhengeveld** [comment]
Used a different repo. Original repo does not work anymore

**Comment by fuatakgun** [comment]
Why do we need this add-on anymore? You should use go2rtc instead of this.

**Comment by jwhengeveld** [comment]
Forked it and changed the repo to the correct MediaMTX repo - https://github.com/jwhengeveld/rtsp_simple_server

And for the why, i understood that i needed to install the RTSP simple server addon if i wanted to convert Eufy P2P streams to RTSP streams. Can you convert Eufy P2P to RTSP with Go2RTC?

**Comment by fuatakgun** [comment]
hey, I removed anything about rtsp simle server from readme, webrtc custom integration with bundled go2rtc binary or go2rtc add-on would be enough
