### ISSUE TITLE
Add support for the: 4G LTE Cam S330 (T86P2)

### ISSUE THREAD

**Issue by dspooren** [fuatakgun/eufy_security#1245]
Please can you add support for the: 4G LTE Cam S330 (T86P2)?

Camera is not supported yet in Home Assistant

![not-supported](https://github.com/user-attachments/assets/33c5b22e-fd8c-47a8-91e4-0d2bb0e86986)

**Comment by dspooren** [comment]
Anyone has this cam working in Home Assistant?

**Comment by fuatakgun** [comment]
work with bropat to add support. https://bropat.github.io/eufy-security-client/#/supported_devices

it is not supported

**Comment by kilian-f-za** [comment]
Hello, will the camera be integrated in the future? So are you still involved in integration or will the camera not be supported?

**Comment by kilian-f-za** [comment]
Hello, will the camera be integrated in the future? So are you still involved in integration or will the camera not be supported?
