### ISSUE TITLE
Changing the guard mode does not update the camera setting anymore, I noticed this today Nov 14th 2024

### ISSUE THREAD

**Issue by mcderd-coder** [fuatakgun/eufy_security#1246]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**
Changing the guard mode does not update the camera setting anymore

**To reproduce**
Change the guard mode and then check in the Eufy app and you will see the guard mode has not changed

As above

**Expected behavior**
Guard mode should change on camera when it is changed in this add-on

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 
- OS
- Home Assistant Core Version: 
- 2024.11.1
- Eufy Security Add-on Version: 
- 1.9.1
- Eufy Security Integration Version:
- I do not know where to find this

Hardware Information;
- Camera Model:
E220

- Live Streaming Protocol (RTSP/P2P): 
RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: 14:02:22 (4 occurrences)
Last logged: 14:02:22

Logs I am sure when it says HA Core 2025.11 they mean 2024.11

STATE_ALARM_ARMED_AWAY was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_AWAY instead, please report it to the author of the 'eufy_security' custom integration
STATE_ALARM_ARMED_HOME was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'eufy_security' custom integration
STATE_ALARM_DISARMED was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'eufy_security' custom integration
STATE_ALARM_TRIGGERED was used from eufy_security, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.TRIGGERED instead, please report it to the author of the 'eufy_security' custom integration

**Comment by fuatakgun** [comment]
this is an warning, not error, it cannot cause an issue on the behavior. you.

If you have an actual error, please open a bug with proper logs. 

the above warning has been fixed in latest version
