### ISSUE TITLE
homeassistant.requirements.: Requirements for eufy_security not found: ['websocket-client==1.4.2', 'aiortsp==1.3.7'].

### ISSUE THREAD

**Issue by pragmaticivan** [fuatakgun/eufy_security#1252]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

The component is not working on the latest version of HA and HASS

HACS_VERSION=2.0.1
homeassistant/home-assistant:2024.11.2

Error:
homeassistant.requirements.: Requirements for eufy_security not found: ['websocket-client==1.4.2', 'aiortsp==1.3.7'].

**Comment by gmta** [comment]
A temporary workaround is to install the required version manually if you have access to the environment that HA is running in:
```bash
pip install aiortsp==1.3.7
```

**Comment by fuatakgun** [comment]
working on this

**Comment by fuatakgun** [comment]
v8.0.5 should fix this
