### ISSUE TITLE
T85D0 Eufy Smart Lock

### ISSUE THREAD

**Issue by andresmattei** [fuatakgun/eufy_security#1254]
Requesto to add T85D0 Smart Lock unlocking and lcking feature.

Debug (device) attributes:

Properties
> name: Front Door
> model: T85D0
> serialNumber: T85D0K1024260CFC
> hardwareVersion: 1.0.0.1
> softwareVersion: 2.0.4.8
> type: 202
> stationSerialNumber: T85D0K1024260CFC

Commands
Voices
> Unknown

Debug (station) attributes:

Properties
> name: Front Door
> model: T85D0
> serialNumber: T85D0K1024260CFC
> type: 202
> hardwareVersion: 1.0.0.1
> softwareVersion: 2.0.4.8
> connected: false

Commands
Voices
> Unknown

**Comment by fuatakgun** [comment]
work with bropat to add support. https://bropat.github.io/eufy-security-client/#/supported_devices
