### ISSUE TITLE
Videostreaming is not working although go2rtc should be buildin

### ISSUE THREAD

**Issue by Kolbi** [fuatakgun/eufy_security#1273]
**Describe the bug**

Videostreaming is not working although go2rtc should now be buildin in HASSIO ( https://www.home-assistant.io/integrations/go2rtc/ ). Refering to this point https://github.com/fuatakgun/eufy_security?tab=readme-ov-file#2-install-go2rtc-add-on this should be obsolete with latest HASSIO version?

Or does the settings needs to be modified? Anyone got it working without installing https://github.com/AlexxIT/WebRTC or https://github.com/AlexxIT/WebRTC ?

**Comment by fuatakgun** [comment]
go2rtc support is incorporated into home assistant natively, but you still have to install go2rtc add-on.
HA will communicate with go2rtc natively but not relevant of eufy_security use case
