### ISSUE TITLE
Lovelace Alarm Card - Alarm Status not updating (Doorbell and HomeBase)

### ISSUE THREAD

**Issue by rampaigewow** [fuatakgun/eufy_security#129]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
I saw someone write a similar bug for Locks. I apologize if I should not have opened a new issue.

I am having an issue with the Lovelace UI - Alarm Cards. I have one for my Eufy HomeBase and one for my Eufy Doorbell. Both cards display the status of the alarm as "Armed Home". When I click the "Disarm" button, the Alarm status does not change on the cards and the option to Disarm does not go away. I cannot re-arm the alarms; however, in my Eufy app, I notice that the status of the Alarm DOES change to disarmed. The only way for me to re-arm the alarm is through my Eufy app.

For the Home Base (T8010P13204426D1 ) disarm, when I check the EUFY logs, I DO see the status change, even when done via the Eufy app.

> 2021-11-22 13:54:33.188  INFO Eufy Security server listening on port 3000 
> 2021-11-22 13:54:34.310  INFO Connected to station T8010P13204426D1 on host 10.0.0.73 and port 28594 
> 2021-11-22 13:54:34.338  INFO Connected to station T8200N2020500CB5 on host 10.0.0.81 and port 28594 
> 2021-11-22 13:54:34.926  INFO Push notification connection successfully established 
> 2021-11-22 13:56:11.967  INFO Alarm mode for station T8010P13204426D1 changed to: HOME 
> 2021-11-22 13:56:38.774  INFO Alarm mode for station T8010P13204426D1 changed to: DISARMED
> 

For the Eufy Door Bell (T8200N2020500CB5), there is not status change at all shown in the logs, even when done through the Eufy app.

**To Reproduce**
1. Go to 'Lovelace Dashboard - Alarm Cards'
2. Click on 'Disarm'
3. Alarm status does not change in the interface, but DOES actually change through Eufy.

**Expected behavior**
When alarm is disarmed - Status should change to disarmed and show in the Interface. Then, the card should give option to Arm Home or Arm away.

**Screenshots**
Not sure if any are needed, please let me know what would be helpful.

**Hardware Information about Home Assistant

HA installed on Win 10 latpops running VirtualBox:

Version | core-2021.11.5
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.75
CPU Architecture | x86_64
Timezone | America/New_York

Host Operating System | Home Assistant OS 6.6
Update Channel | stable
Supervisor Version | supervisor-2021.10.8
Docker Version | 20.10.8
Disk Total | 30.8 GB
Disk Used | 4.2 GB
Healthy | true
Supported | true
Board | ova
Supervisor API | ok
Version API | ok

**Hardware Information
Eufy Home Base and Wired 2k Doorbell

**Comment by fuatakgun** [comment]
have you enabled to receive notifications for security modes for `switch modes by schedule, geofencing, from app`?

**Comment by rampaigewow** [comment]
Sorry forgot to turn them back on for that last test (I’ve been trying to play around with Eufy settings, but no luck. 

When I had push notifications on, it’s the same thing. The alarm disarms, but the Lovelace card does not change and I can’t rearm it. 

The odd thing is for a bit, I disabled all push notifications and it worked for about a day with no issues. I could arm, disarm, arm away, etc and the notifications were disabled.  

It never worked with the doorbell (only disarm option) but maybe that’s because it doesn’t have push notifications for status changes like the home base does. 

> 2021-11-22 14:42:18.257  INFO Received push notification for changing guard mode 
> {
>   guard_mode: 1,
>   current_mode: 1,
>   stationSN: 'T8010P13204426D1'
> }
> 2021-11-22 14:44:18.796  INFO Alarm mode for station T8010P13204426D1 changed to: DISARMED 
> 2021-11-22 14:44:21.573  INFO Received push notification for changing guard mode 
> {
>   guard_mode: 63,
>   current_mode: 63,
>   stationSN: 'T8010P13204426D1'
> }

**Comment by fuatakgun** [comment]
i can debug if you can share the devices with me

**Comment by fuatakgun** [comment]
Resolving due to inactivity
