### ISSUE TITLE
Enable entity_category feature

### ISSUE THREAD

**Issue by stefanroelofs** [fuatakgun/eufy_security#131]
**Is your feature request related to a problem? Please describe.**
Now there is quite a long list of entities in my auto generated lovelace interface for my Eufy doorbell.

**Describe the solution you'd like**
Set the correct entity_category for all entities.
For example for my T8210 doorbell you could clasify like this:

_**entity_category: none**_
- camera.deurbel
- binary_sensor.deurbel_motion_sensor
- binary_sensor.deurbel_person_detector_sensor
- binary_sensor.deurbel_ringing_sensor

_**entity_category: config**_
- binary_sensor.deurbel_audio_recording
- binary_sensor.deurbel_auto_night_vision
- binary_sensor.deurbel_enabled
- binary_sensor.deurbel_motion_detection_enabled
- binary_sensor.deurbel_status_led_enabled

_**entity_category: diagnostic**_
- sensor.deurbel_battery
- sensor.deurbel_codec
- sensor.deurbel_detected_person_name
- binary_sensor.deurbel_streaming_sensor
- sensor.deurbel_streaming_source_address
- sensor.deurbel_streaming_source_type
- sensor.deurbel_wifi_rssi

**Additional context**
Info about the feature here:
https://developers.home-assistant.io/docs/core/entity/

Furthermore, the `deurbel_enabled` entity now is a binary sensor. 
When I execute the `eufy_security.enable` and `eufy_security.disable` services, this entity changes. 
Why not make this a switch, instead of a sensor?

Thanks!

**Comment by fuatakgun** [comment]
hey, do you want to do this? I am open any help and contribution?

**Comment by stefanroelofs** [comment]
I've never done any work on an integration, but I'll have a look. See if I can manage it.

**Comment by stefanroelofs** [comment]
I've got it working! 😎 
I changed my binary sensors so some of them have the Diagnostic catagory:
![image](https://user-images.githubusercontent.com/37924749/144742236-cf8ef681-8ae2-4f39-b859-41d2ecc9e6b7.png)

However, I use a ENTITY_CATEGORY_DIAGNOSTIC constant from homeassistant.const.
This constant will be deprecated in the next release, and replaced with the EntityCategory enumeration in helpers.entity.py

I propose we wait for the 2021.12 release and then use the new enumeration.

**Comment by fuatakgun** [comment]
Wow, good news, thanks for checking on this. Please let me know if you need any support.

**Comment by fuatakgun** [comment]
Thanks for PR, it is all working well.

![Screenshot_2021-12-15-21-28-07-722_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/146260361-6b36c3dc-c426-4b3b-8d5e-bf10804215c9.jpg)

![Screenshot_2021-12-15-21-28-17-721_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/146260371-6dff362f-3626-4586-9260-f5775943b040.jpg)
