### ISSUE TITLE
Battery sensor showing wrong value

### ISSUE THREAD

**Issue by kauthmbt** [fuatakgun/eufy_security#132]
**Describe the bug**
After updating from 0.3.3 to the latest addon (0.5.5) & HACS version the battery is constantly showing 0%.

**To Reproduce**
1. Updating to latest addon + integration

**Expected behavior**
Battery sensor showing the correct percentage.

**Screenshots**
![2021-11-23 155310](https://user-images.githubusercontent.com/74350030/143054340-7d75ac86-d845-49d2-8f5d-b277167ae2d3.jpg)

**Hardware Information about Home Assistant**
Pi4
Home Assistant OS 6.6
core-2021.11.5

**Hardware Information about Cameras**
- T8210
- Live Streaming Protocol: RTSP

**Additional context**
I already tried a fallback and reinstalled the old addon(s) from a backup (both Eufy security WS addon + integration). After a reboot the battery sensor will immediately show the correct percentage again:

![2021-11-23 163051](https://user-images.githubusercontent.com/74350030/143054452-cb6aa767-dfc1-4857-897d-af872c33e3a7.jpg)

**Comment by kauthmbt** [comment]
Did another verification over a longer period and I discovered that periodically the correct value is shown but afterwards it turns to zero again.
![Screenshot_20211127-150615~2](https://user-images.githubusercontent.com/74350030/143685045-443edd78-2284-4c5d-a0a6-c7f821c635ef.png)

The problem seems to be related to the addon because even without updating the HACS Integration it appears after a short time.

Could you please give me a hint if I should directly open an issue at eufy-security-ws ?

**Comment by fuatakgun** [comment]
Any logs from add-on? I suppose you are having similar issue here: https://github.com/fuatakgun/eufy_security/issues/141

**Comment by kauthmbt** [comment]
this is the most recent logging:

`2021-11-26 16:40:36.729  INFO Eufy Security server listening on port 3000 
2021-11-26 16:40:38.559  INFO Connected to station T8010 on host 192.X.X.X and port 21034 
2021-11-26 16:40:40.019  INFO Push notification connection successfully established 
2021-11-27 11:09:45.117  INFO Disconnected from station T8010 
2021-11-27 11:09:50.329  INFO Connected to station T8010 on host 192.X.X.X and port 27611 
2021-11-28 14:43:36.366  INFO Client disconnected with ip: ::ffff:172.30.32.1 port: 44366 code: 1006 reason:  
2021-11-28 14:43:36.373  INFO Client disconnected with ip: ::ffff:172.30.32.1 port: 43410 code: 1006 reason:  
2021-11-29 02:31:34.249  WARN Station T8010 - Heartbeat check failed. Connection seems lost. Try to reconnect... 
2021-11-29 02:31:34.253  INFO Disconnected from station T8010 
2021-11-29 02:32:09.450  WARN Station T8010 - Tried all hosts, no connection could be established 
2021-11-29 02:32:09.454  INFO Timeout connecting to station T8010 
2021-11-29 02:32:19.523  INFO Connected to station T8010 on host 192.X.X.X and port 26635 
2021-11-29 09:03:21.636  INFO Client disconnected with ip: ::ffff:172.30.32.1 port: 49032 code: 1006 reason:  `

**Comment by fuatakgun** [comment]
You can see that you are having connection issues to base station (or doorbell) from add on. This is mostly due to network, but if you think your network is stable enough, you need to create an issue to eufy-security-ws repository, this goes beyond my skills.

**Comment by kauthmbt** [comment]
Yes - I see.
But even after a successful restart without connection issues it still shows "0%"
```
2021-11-29 20:23:45.609  INFO Eufy Security server listening on port 3000 
2021-11-29 20:23:47.173  INFO Connected to station T8010 on host 192.x.x.x and port 11294 
2021-11-29 20:23:49.047  INFO Push notification connection successfully established 
```

![eufy4](https://user-images.githubusercontent.com/74350030/143942358-5cb25be3-1641-4225-8bfa-0d64d237b7c9.jpg)

Anyway - I created an issue to eufy-security-ws repository. Thanks for taking a look into it.

**Comment by isabellaalstrom** [comment]
I'm having the same issue. Could you please link the issue over at the other repo @kauthmbt ?

**Comment by kauthmbt** [comment]
@isabellaalstrom - sure: 
[https://github.com/bropat/eufy-security-ws/issues/57](url)

**Comment by fuatakgun** [comment]
I will keep this issue open, but there is nothing I can do until it is resolved by @bropat , let's see his reaction and

**Comment by kauthmbt** [comment]
@fuatakgun - can you please assist? 
As bropat is asking me for a debug log from you addon: can I do it by myself or do I need to share my cam with you for debugging as you mentioned in your README?
Thanks in advance.

**Comment by kauthmbt** [comment]
@fuatakgun I kindly ask for your support:
I activated the debug logging in the addon and delivered the results to bropat. The problem is that the protocol log window from the addon only shows a limited number of log entries making the log details incomplete for an analysis when using copy & paste.
How can I achieve to get the full logging details for delivery?
Thanks in advance!

**Comment by fuatakgun** [comment]
@kauthmbt can you get latest version of add-on and share your status?

**Comment by kauthmbt** [comment]
@fuatakgun I updated to latest version yesterday but the general situation is still the same:
![image](https://user-images.githubusercontent.com/74350030/148503639-08e73ea4-2d27-416f-a7cc-1b82cae1b63a.png)

**Comment by fuatakgun** [comment]
Yes makes sense, following readme please select correct email address to share and email me serial number :-) so i can find out easily yours one.

**Comment by fuatakgun** [comment]
Let me resolve this, as there is not much left to do from my end. When it is fixed, I will release a new version for this issue.
