### ISSUE TITLE
No integration in configuration

### ISSUE THREAD

**Issue by LukaszZdunek** [fuatakgun/eufy_security#133]
6.3.5 After restart, go to Configuration - Integrations page and click on Add Integration

In Integrations i can't see Eufy Sec
![empty](https://user-images.githubusercontent.com/53077569/143323745-2e3da486-03d0-4471-acf3-bba4aaf69173.png)
urity

**Comment by MtenHoorn** [comment]
I have the same problem. Followed all the installation steps but after restart i cannot find the Eufy Security integration

**Comment by jeffproe** [comment]
Same.  Can't find the integration, nor the RTSP add-on.

**Comment by fuatakgun** [comment]
HACS has caching, you need to clear your browser cache to get newest list.

Moreover, do not mix integrations and add-ons, they are totally different from both installation and management perspective.

**Comment by trullock** [comment]
Ughh just had the same problem. Blooody HACS cache. Thanks @fuatakgun
