### ISSUE TITLE
Missing sound for p2p streaming - After resolving stability issues, add sound back

### ISSUE THREAD

**Issue by lukas-sieber** [fuatakgun/eufy_security#134]
**Is your feature request related to a problem? Please describe.**
Yes as per https://github.com/fuatakgun/eufy_security/issues/76#issuecomment-978134012

**Describe the solution you'd like**
After resolving stability issues, please return sound back (Now disabled due to stability issues with streams)

**Describe alternatives you've considered**
Alternative is current state with no sound

**Additional context**
Connected with https://github.com/fuatakgun/eufy_security/issues/76#issuecomment-978134012

**Comment by fuatakgun** [comment]
I hope we can reach to this point :) sometime

**Comment by fuatakgun** [comment]
finally, we are there, as using TCP based solution, I can dream about adding sound into p2p

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/592

**Comment by e3ndr** [comment]
Has this been fixed yet? I still have no sound when using P2P and am unable to start RTSP on my [T8222](https://us.eufy.com/products/e8222113).
