### ISSUE TITLE
Have a warning while starting rtsp stream to enable it first

### ISSUE THREAD

**Issue by lukas-sieber** [fuatakgun/eufy_security#135]
**Is your feature request related to a problem? Please describe.**
As described inside https://github.com/fuatakgun/eufy_security/issues/76#issuecomment-968369109 there are new ways how to start streaming with RTSP disabled (Previously it was auto-enabled/disabled)

**Describe the solution you'd like**
Print warning when using the old way, with explanation what to do. Update documentation.

**Describe alternatives you've considered**
Ask implementer or revers engineer it. Here I mean to discover how behavior changed

**Additional context**
It's related to bug: https://github.com/fuatakgun/eufy_security/issues/76#issuecomment-968369109

**Comment by fuatakgun** [comment]
![image](https://user-images.githubusercontent.com/11085566/146066953-8da3b18d-03cb-4ffb-976e-5e71ba3b9953.png)


please get latest version, this should work now
