### ISSUE TITLE
Installation with HACS

### ISSUE THREAD

**Issue by KJThaDon** [fuatakgun/eufy_security#136]
I feel like I am missing something on the initial install...What is this IP and port related to?

I am trying to use for my 2 locks, but cannot get past this screen.

HA running on VM
https://i.ibb.co/kKSwpD5/Screenshot-16.png

**Comment by fuatakgun** [comment]
Please go through readme first, you will find all your answers there.

**Comment by KJThaDon** [comment]
> 

Thank you. I did try localhost - 3000 several times. It sits there loading for minutes before giving the message "Unknown error occurred"
