### ISSUE TITLE
Trigger doorbell/camera to start recording (by for example hue outdoor motion sensor)

### ISSUE THREAD

**Issue by rickleka** [fuatakgun/eufy_security#139]
Is there an option (send msg?) to trigger the doorbell to start recording?

For example, doorbell normally triggers on motion/persons within 5 meters. Having a hue outdoor motion sensor at the entrance of my yard at 12 meters. Would be nice to have the option to send a command to the doorbell to start recording.
Eufy suggests a similar solution with their own motion detector so maybe it is possible with some commands already..

**Comment by fuatakgun** [comment]
You should start live stream and record using HA commands but it will definitely take 3 to 5 seconds to start capturing, so you will miss initial part

**Comment by rickleka** [comment]
sorry to be not clear enough, I would like to trigger a recording on the doorbell/homebase/eufy app itself. 

so a hue motion sensor can trigger a record that I can see in the eufy app (just like normal recordings captured by de doorbell itself)

**Comment by fuatakgun** [comment]
Ah, got it, can you ask this to eufy-security-ws repository to build this function? Later on, i can add this functionality to home assistant.
