### ISSUE TITLE
Cannot log into add-on

### ISSUE THREAD

**Issue by jameshhood** [fuatakgun/eufy_security#142]
**Describe the bug**
After following the instructions provided for installation, I cannot login to my eufy account. It just gives me a 401 unauthorized.

**To Reproduce**
1. Follow install instructions
2. After adding integration to HACS and adding integration check logs in supervisor

**Hardware Information about Home Assistant
Raspberry Pi3

**Additional context**
I have tried uninstalling the add-ons and re-adding them with no luck.
I have verified that I can log into my Eufy account online
I have removed 2 step authentication

**Comment by fuatakgun** [comment]
Merged into https://github.com/fuatakgun/eufy_security/issues/140
