### ISSUE TITLE
Devices unavailable work around, sort of...

### ISSUE THREAD

**Issue by boctok** [fuatakgun/eufy_security#143]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
On reboot, all devices are unavailable. The only thing that gets them back is to go to - Configuration, Integrations, Eufy Security, Configuration and change the IP address (from or to "localhost" or the actual IP) and submit, Things will work until the next reboot, which requires the change again.

**To Reproduce**
1. On reboot, all devices become unavailable.
2. Requires changing IP/localhost in Integration configuration.

**Expected behavior**

**Screenshots**
![Eufy Integration config](https://user-images.githubusercontent.com/5306739/144109213-f09f1be9-06b4-4b49-b880-9a1b936fb705.png)

**Hardware Information about Home Assistant
Everything is the latest release
**Hardware Information about Cameras
- Camera Model: Various Eufy cameras
- Live Streaming Protocol: RTSP or P2p

**Additional context**
Not sure what causes this. Everything is assigned with static IP addresses. Simply after reboot, all devices are unavailable, change that one thing in config and all are instantly available, no reboot required.

**Comment by fuatakgun** [comment]
When you restart, add on startup is not synced with home assistant integration initialization and this causes `unavailable` entities. What you are triggering via doing this is causing a refresh on integration which successfully communicates with add on.

So, you can just reload integration and same thing would happen.

I am working on;
- starting up add-on in correct time, so integration can communicate with it at startup
- while communicating with add-on, double check if all connected as sometimes add on us taking time to load all devices into memory.
