### ISSUE TITLE
Link the "arm_night" mode to a custom mode on Eufy security

### ISSUE THREAD

**Issue by lpaso** [fuatakgun/eufy_security#145]
The Alarm entity in HA has 4 modes by default, and 3 of them (home, away and disabled) are linked to native Eufy security modes.
The fourth on (night) is not accessible by the integration, and it would be great to link this mode (night) to a custom one on Eufy.

Is there a way to add the "night" mode on the entity and to link it to a custom mode on Eufy ?

Thanks

**Comment by fuatakgun** [comment]
you should use respective services mentioned in README.

https://github.com/fuatakgun/eufy_security#12-station-services

**Comment by lpaso** [comment]
Well, sorry, but I don't understand how that answer helps :)
Indeed, I can make use custom services to have a custom mode activated, but the "night" mode still does not appear in the homebase alarm panel  on HA. Or maybe I don't understand what you mean and how to use the custom services to enable the night mode on the homebase alarm panel on HA ?

**Comment by fuatakgun** [comment]
home assistant front end card does only support 3 modes, disarm, home and away.

If you want to switch to night mode, which should be a custom mode in eufy app, just call `alarm_arm_custom1` or `alarm_arm_custom2` or `alarm_arm_custom3` service. Find out the correct number :)

**Comment by lpaso** [comment]
Indeed, the card does only support these 3 modes, but the underlying services (and hence the Homekit integration) does support other modes, as the night mode I was refering to ;)
For example, the "manual alarm" integration offers all 4 modes, which are then accessible to Homekit.

Right now, using the alarm_control_panel.alarm_arm_night service on the homebase alarm panel does nothing. I was suggesting that this service might enable a custom mode on Eufy, hence redering it usable on Homekit for example.

**Comment by lpaso** [comment]
Hopefully my last explanation was more clear and helpful :D

**Comment by lpaso** [comment]
There's even a fifth mode on the alarm control panel : arm_vacation. Maybe another custom mode could be liked to this mode too ?

**Comment by fuatakgun** [comment]
I see but I do not have control on services exposed to HomeKit, we rather agreed this solution here: https://github.com/fuatakgun/eufy_security/issues/112

You can build a custom switch yourself until I finish developing this.

**Comment by lpaso** [comment]
Don't you have control to what alarm_control_panel modes you are using on the Homebase alarm control panel ? Just like we can enable these modes on the "manual alarm" integration ? Am I wrong ?

**Comment by lpaso** [comment]
Here the complete list of states accessible when creating an alarm panel : 
- armed_custom_bypass
- armed_home
- armed_away
- armed_night
- armed_vacation
- disarmed
- triggered

Right now, only armed_home, armed_away, disarmed and triggered are exposed by your integration.
There's still room to expose the 3 last states ;)

**Comment by fuatakgun** [comment]
By default configuration, Eufy supports home, away and disarmed. Skipping geofencing and schedule because they are rule sto switch between other modes, rather than being an actual mode.

So, users can create 3 more custom modes and if I understand correctly, you want me to map `Night` mode to `Custom1`, right?

**Comment by lpaso** [comment]
Using configuration, we could also have Vacation mapped to Geofencing for example.
Personnally, I'd be using only the night mode, but I guess there's a lot of people that would like to get Eufy modes linked to native states (and native services) instead of relying on dedicated services.

**Comment by fuatakgun** [comment]
I understand it now, I would prefer to implement to do this by `opt in` method using configuration rather than enabling it for all by default. Makes sense for you?

**Comment by lpaso** [comment]
> I understand it now, I would prefer to implement to do this by `opt in` method using configuration rather than enabling it for all by default. Makes sense for you?

Totally ! That's even how I imagined this ;)

**Comment by fuatakgun** [comment]
I might be jumping into conclusion too early because of historical questions and issues. I should break the bias.

**Comment by lpaso** [comment]
> I might be jumping into conclusion too early because of historical questions and issues. I should break the bias.

No problem 😉

**Comment by fuatakgun** [comment]
Coming back here, are you fine to map night and vacation modes to custom1 and custom2 respectively?

Other way around will be too much time consuming for me?

**Comment by lpaso** [comment]
> Coming back here, are you fine to map night and vacation modes to custom1 and custom2 respectively?
> 
> Other way around will be too much time consuming for me?

That’s fine by me ! So, we forget the settings and opt-in ?

**Comment by fuatakgun** [comment]
Yes, having settings should be implemented for each base and individual camera systems, which includes lots of changes

**Comment by lpaso** [comment]
OK, no problem 😉

**Comment by fuatakgun** [comment]
releasing a new version, please get it and update here with your results.

**Comment by fuatakgun** [comment]
please comment back, resolving for now

**Comment by lpaso** [comment]
Hello ! I just updated, and I may be missing something but the panel didn’t change and I still got only 3 modes available : disabled, home and away. Is there anything I can do to refresh maybe ?

**Comment by fuatakgun** [comment]
note to myself: be a good housekeeper and inform users how to enable new functionality :) Please enable according to below screenshot.

![image](https://user-images.githubusercontent.com/11085566/149518807-efe82d3a-7d1d-4f9b-8a82-c058153ae3d4.png)

**Comment by lpaso** [comment]
Ok, that’s better, but it seems the « night » profile has been connected to the Custom2, and Vacation to Custom3, and Custom1 does seem connected to « arm with custom bypass » 😅
Is there any chance you connect the modes the way we talked earlier or is that a deliberated move ?

**Comment by lpaso** [comment]
If it’s deliberated, that’s not an issue, I’ll just copy my « night » profile to custom2 😉

**Comment by fuatakgun** [comment]
I had to follow a rule and followed alphabetical ordering :)
ByPass -> Custom1
Night -> Custom2
Vacation -> Custom3

**Comment by lpaso** [comment]
Also, another « issue » : when selecting the custom modes, the change is not passed to HomeKit, but is passed using the default modes. When changing the mode from Homekit, the action is passed to HomeAssistant, but there seems to be an acknowledgment missing as it still displays « activating… » instead of the mode selected.

**Comment by lpaso** [comment]
> I had to follow a rule and followed alphabetical ordering :)
> ByPass -> Custom1
> Night -> Custom2
> Vacation -> Custom3

Ok, ni problem 😉

**Comment by fuatakgun** [comment]
> Also, another « issue » : when selecting the custom modes, the change is not passed to HomeKit, but is passed using the default modes. When changing the mode from Homekit, the action is passed to HomeAssistant, but there seems to be an acknowledgment missing as it still displays « activating… » instead of the mode selected.

I am not sure how HomeKit integration is fetching custom modes, all I can do is to test locally and it seems to be working inside HA, right?

**Comment by lpaso** [comment]
> I had to follow a rule and followed alphabetical ordering :)
> ByPass -> Custom1
> Night -> Custom2
> Vacation -> Custom3

Ok, no problem 😉

**Comment by lpaso** [comment]
> > Also, another « issue » : when selecting the custom modes, the change is not passed to HomeKit, but is passed using the default modes. When changing the mode from Homekit, the action is passed to HomeAssistant, but there seems to be an acknowledgment missing as it still displays « activating… » instead of the mode selected.
> 
> I am not sure how HomeKit integration is fetching custom modes, all I can do is to test locally and it seems to be working inside HA, right?



> > Also, another « issue » : when selecting the custom modes, the change is not passed to HomeKit, but is passed using the default modes. When changing the mode from Homekit, the action is passed to HomeAssistant, but there seems to be an acknowledgment missing as it still displays « activating… » instead of the mode selected.
> 
> I am not sure how HomeKit integration is fetching custom modes, all I can do is to test locally and it seems to be working inside HA, right?

Yup, Homekit apart, it seems OK

**Comment by fuatakgun** [comment]
Let's revive this, i believe overriding bypass, night and vacation state names with custom ones causing this issue in homekit end.

Given that you have home kit locally, can you change visible custom names in integration options as Bypass, Night and Vacation, and refresh the integration, and let's see how it goes

**Comment by lpaso** [comment]
I just did that and it’s the same, « activating… » instead of acknowledging the Night mode. Just like there was no return from the command when on night mode (as there’s no « bypass » or « vacation » in Homekit I can’t say if it’s the same for other modes 😉)

**Comment by fuatakgun** [comment]
Got it, sorry not being able to help further. I would create couple of input booleans to control these states through homekit, if i were you.

**Comment by wereldreiziger** [comment]
> I had to follow a rule and followed alphabetical ordering :) ByPass -> Custom1 Night -> Custom2 Vacation -> Custom3

How can I change Night into custum 1 instead of custom 2? Im new to HA sorry...

![Image](https://github.com/user-attachments/assets/c54a1fe7-33b7-4c98-8762-0fd980fe9baf)

**Comment by Adam-Kay** [comment]
> _@wereldreiziger_ - How can I change Night into custum 1 instead of custom 2? Im new to HA sorry...

You can't unfortunately. I would go into your Eufy Security app and just create a filler security mode and _then_ create the Night/Bedtime mode, so that your filler mode becomes Custom 1 and then your Night mode is Custom 2. 

In my app, the order is:
```
Home, Away, Off, Filler Mode, Bedtime, (etc)
                 ↑Custom1     ↑Custom2
```
