### ISSUE TITLE
T8423 Flood Light Cam 2 Pro not working

### ISSUE THREAD

**Issue by modem123pk** [fuatakgun/eufy_security#147]
**Describe the bug**  
Live Streaming is not working for Flood Light Cam 2 pro. 

**To Reproduce**  
Follow the steps to install and add a Floodlight cam 2 pro as a camera. RTSP works like a camera, when you enable and disable it, you can view it in WebRTC, however, when you click on the camera, it doesn't stream or turn on for Flood Light Cam 2 pro.

**Expected behavior**  
A clear and concise description of what you expected to happen. The other python eufy-security libraries are also failing while requesting the  RTSP stream. For e.g.  see the logs below from the python Eufy Security library

------------------
Camera Name: %s Front Door
Serial Number: %s XXXXX
Station Serial Number: %s XXXXXX
Last Camera Image URL: %s https://zhixin-security-pr.s3.us-west-2.amazonaws.com/thumb/2021/12/01/station/<snip>
Starting RTSP Stream
Stream URL: %s rtmp://p2p-vir-6.eufylife.com/hls/<snip>
------------------
Camera Name: %s Garage
Serial Number: %s T8423NXXXXXX
Station Serial Number: %s T8423XXXXXXXX
Last Camera Image URL: %s https://zhixin-security-pr.s3.us-west-2.amazonaws.com/thumb/2021/12/01/station/<snip>
Starting RTSP Stream
Unexpected error

I think the support for this has to be added and I am not sure which protocol it's using. Let me know if I can pull that information somehow to provide here. 

**Screenshots & Logfiles**  
Erro message:
Logger: homeassistant
Source: custom_components/eufy_security/alarm_control_panel.py:136
Integration: Eufy Security (documentation, issues)
First occurred: 10:33:10 PM (1 occurrences)
Last logged: 10:33:10 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 56, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 136, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Camera Model : T8423 
- Live Streaming Protocol: RTSP or P2p : Don't know 

**Additional context**

**Comment by fuatakgun** [comment]
please engage with this repository to add support for your model. it is not supported as of now;
https://github.com/bropat/eufy-security-client#known-working-devices
Please let me know when it is done, until then, I am not able to help

**Comment by modem123pk** [comment]
I can open a new ticket if needed. It seems like it's failing for all the
Eufy Cameras that I have.

See the log below for the T814.



Logger: homeassistant
Source: custom_components/eufy_security/alarm_control_panel.py:136
Integration: Eufy Security (documentation
<https://github.com/fuatakgun/eufy_security>, issues
<https://github.com/fuatakgun/eufy_security/issues>)
First occurred: 6:13:31 PM (8 occurrences)
Last logged: 6:13:38 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/eufy_security/__init__.py", line 56, in update
    coordinator.async_set_updated_data(coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py",
line 287, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py",
line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line
486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line
519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line
492, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py",
line 136, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1


Regards,

--
 Omair Manzoor
***@***.***

"It is not the degrees you hold, but the mind you possess". -UmZ

**Comment by CodebyADHawk** [comment]
Hi. The streaming issue with the Floodlight Pro 2 is now addressed in the upstream repository/project.

https://github.com/bropat/eufy-security-client/issues/75

Can this be integrated into the HA Eufy Security component as well?

Many thanks!

**Comment by CodebyADHawk** [comment]
I think both the client and the web socket implementation have been updated with support - not 100% sure though. Are there any other pieces that are needed for the integration to be updated? Many thanks for your time and efforts.

**Comment by fuatakgun** [comment]
after this vacation period, i will test it locally to be sure that everything is working for at least my setup (nothing broken :-) ) i will update the version and release it.
