### ISSUE TITLE
Stuck during setup

### ISSUE THREAD

**Issue by evenflow73** [fuatakgun/eufy_security#149]
Hi,

I've installed HomeAssistant OS 6.6 on Raspbery pi 4, trying to add Homebase 2 with 2 connected 2C pro Eufycams  to my system.

1. followed the instructions, created a 2nd Eufy account and shared my devices with the new account.
2. installed the Eufy Security WS Addon and entered my credentials.
3. seems like I don't get connected, as the log only says:

INFO Eufy Security server listening on port 3000 

Does it make sense to continue the installation process?

Anything I can do or try?

Thanks!

**Comment by fuatakgun** [comment]
that is it, no more logs?
if that is the case, try to remove shared devices from your account and add them back.
that solves many issues

**Comment by evenflow73** [comment]
Thanks.  Removing / adding the devices back  & setting a new password did the trick.

Further down the road, added the Eufy Security Rep via HACS:

<img width="1192" alt="Screenshot 2021-12-03 at 09 31 56" src="https://user-images.githubusercontent.com/95384630/144572859-074dbcd0-9456-4283-8581-d80e73d7f6d4.png">

Process being slightly different, than you described: downloaded (no install option), restarted HA :

<img width="1142" alt="Screenshot 2021-12-03 at 09 48 25" src="https://user-images.githubusercontent.com/95384630/144573368-bf70fce4-86ba-4b72-bb4a-9301cfe49fba.png">

There's no EUFY integration available in configuration/integrations:

<img width="531" alt="Screenshot 2021-12-03 at 09 35 20" src="https://user-images.githubusercontent.com/95384630/144573492-d8492489-a791-483c-bfa7-05919a116f49.png">

I do see the homebase controller showing up in the available integrations:

<img width="314" alt="Screenshot 2021-12-03 at 09 34 33" src="https://user-images.githubusercontent.com/95384630/144573565-2c763d87-e602-4bf1-b246-49768161fb91.png">

But clicking the configure button, it says "accessory already paired with another device".
(This integration  has always been in the "available integrations" section. The only time I could configure it was when I did a reset of the homebase, but from that point I couldn't  add any devices (cams) or access it via the eufy app anymore)

Your support is highly appreciated. 
Thanks,

**Comment by evenflow73** [comment]
it was just a cache thing! 

SOLVED and... working! 

Great work and thanks for this wonderful integration!
