### ISSUE TITLE
Unable to use a gmail address with a + sign

### ISSUE THREAD

**Issue by tompijls** [fuatakgun/eufy_security#151]
I used following email address to create a 2nd account on eufy to be used for this addon. testemail+EUFYHA@gmail.com

Its a gmail feature to leverage unlimited aliases. It works on eufy, but the addon failed to login (no clear error in log file). 

using an email address without + solved the issue

Low prio but it took me some time to figure out hence sharing

**Comment by fuatakgun** [comment]
do you have some basic docker experience? if yes, can you check if can you start docker with this email address following this example? I am not sure if they can be passed as environment variable, let me know your testing output.

```
docker run -it -e USERNAME=testemail+EUFYHA@gmail.com -e PASSWORD=password_goes_here -p 3000:3000 bropat/eufy-security-ws:0.6.0
```

**Comment by tompijls** [comment]
Hey,

the docker command runs fine and connects to the station. Tried again in HA to see if i wasn't impatient, but there it still fails.

Again, very low priority issue, i created another account without + sign and all is good. (maybe just mention it in the docs for now?)

**Comment by mattsmallman** [comment]
I have this working with gmail + address using the docker config specified albeit latest version.

**Comment by fuatakgun** [comment]
Thanks for sharing @mattsmallman , i didn't change anything :-) happy to hear it's working

**Comment by fuatakgun** [comment]
@tompijls do you want to double check?

**Comment by tompijls** [comment]
Apologies for the delay. It seems to work now and connecting to the homebase. This can be closed
