### ISSUE TITLE
WebRTC giving error: type provided is unsupported

### ISSUE THREAD

**Issue by dumbo0001** [fuatakgun/eufy_security#152]
I just follow your installation steps in the README. I could integrate my Eufy 2K battery powered doorbell successfully.
I tried viewing the p2p stream using WebRTC but got the following error:
```
ERROR: NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="hvc1.016000"') is unsupported.
```

The integration is configured as the screenshot in README:
* Use RTSP Add on: checked
* Video analyze duration: 2 (tried default 1.2 and 1 as well)
* Auto start stream on click: unchecked

Not sure if it is a WebRTC issue or from this integration or if I am missing some configuration.

**Screenshots**
![image](https://user-images.githubusercontent.com/4154280/144705589-886d48ee-e48d-43b9-874d-191e77988822.png)

**Hardware Information about Home Assistant**
Home Assistant Core Version: core-2021.10.6
Operating SystemVersion: 6.5

**Hardware Information about Cameras**
- Eufy 2K Battery Powered Doorbell (T8210)
- P2P

**Comment by fuatakgun** [comment]
Following README, have you set camera streaming quality as LOW?

**Comment by dumbo0001** [comment]
After setting the `Video Encoding Format` to `Low` in the Eufy app it works .. Thanks 😊
I can't find it being documented in the `README` or did I miss that section?

**Comment by fuatakgun** [comment]
You are right, i have removed it by some reason, i will fix it.

In essence, higher quality streaming options are using h265 as video codec and it is not supported by with WebRTC. Having a low streaming quality guarantees that video codec is h264.

I will update readme accordingly.

**Comment by fuatakgun** [comment]
Let's keep this open as a reminder to me :-)

**Comment by fuatakgun** [comment]
Readme is updated with this information
