### ISSUE TITLE
Add services to set "working mode" per camera

### ISSUE THREAD

**Issue by ricco24** [fuatakgun/eufy_security#156]
**Is your feature request related to a problem? Please describe.**
On all my cameras i have working mode set to "Optimal Battery Life". But when i leaving house or going to sleep it will be nice set all my cameras to "Optimal Surveillance" mode. But Eufy native global security modes (Home, Away ...) doesn't have this functionality.

**Describe the solution you'd like**
Ability to setup "working mode" (from Power Manager) per camera via HA services call. Then i can setup desired functionality with automation/node red.

**Comment by fuatakgun** [comment]
thanks for creating this issue. This requires a supported functionality from underlying library. Please create an issue here first: https://github.com/bropat/eufy-security-ws

When it is delivered by eufy-security-ws, I can continue here.

**Comment by ricco24** [comment]
OK. I create new issue here: https://github.com/bropat/eufy-security-ws/issues/59

**Comment by ricco24** [comment]
@fuatakgun as mentioned [here](https://github.com/bropat/eufy-security-ws/issues/59) underlying library already has this functionality.

**Comment by fuatakgun** [comment]
Until i implement underlying services, you can give a try using send_message service. 

More information here: https://github.com/fuatakgun/eufy_security/issues/71

**Comment by ricco24** [comment]
Great, with send_message service it works!
```
service: eufy_security.send_message
data:
  message: >-
    {
      "messageId": "message_id_do_not_add_value_here", 
      "command": "device.set_property",
      "name": "powerWorkingMode",
      "serialNumber": "YOUR_SERIAL_NUMBER_GOES_HERE", 
      "value": 0 (battery) | 1 (surveillance) | 2 (custom) 
    }
```

**Comment by fuatakgun** [comment]
Perfect, let's keep this issue open until i implement a service and sensor for this

**Comment by fuatakgun** [comment]
please get latest version, test and comment here. 
I will reopen this issue if needed, for further specific select requests, create separate issues.

![image](https://user-images.githubusercontent.com/11085566/146029163-c4de61c6-4f2a-4588-9295-e17a8c88ea7c.png)
