### ISSUE TITLE
Enable Event Triggers / Status Reads from Battery Level on Entry Sensor

### ISSUE THREAD

**Issue by TheRealStark** [fuatakgun/eufy_security#158]

**Comment by TheRealStark** [comment]
Attributes:

`state:
  name: Barn Door
  model: T8900
  serialNumber: T8900P0021332A18
  hardwareVersion: 0.0.1
  softwareVersion: 0.1.0gb
  stationSerialNumber: T8010P1321181FF0
  state: 1
  batteryLow: false
  wifiRSSI: -42
  sensorOpen: false
  sensorChangeTime: 1639255486
  type: 2
  wifiRssi: -64
properties:
  name:
    value: Barn Door
    timestamp: 1639230242000
  model:
    value: T8900
    timestamp: 1639230242000
  serialNumber:
    value: T8900P0021332A18
    timestamp: 1639230242000
  type:
    value: 2
    timestamp: 1639230242000
  hardwareVersion:
    value: 0.0.1
    timestamp: 1639230242000
  softwareVersion:
    value: 0.1.0gb
    timestamp: 1635193082000
  stationSerialNumber:
    value: T8010P1321181FF0
    timestamp: 1639230242000
  batteryLow:
    value: false
    timestamp: 1639230537505
  sensorOpen:
    value: true
    timestamp: 1639230116000
  chirpTone:
    value: 0
    timestamp: 1639230116000
  chirpVolume:
    value: 14
    timestamp: 1639230116000
  sensorChangeTime:
    value: 1639230241
    timestamp: 1639230116000
  state:
    value: 1
    timestamp: 1639230116000
  wifiRssi:
    value: -42
    timestamp: 1639230537775
  wifiSignalLevel:
    value: 4
    timestamp: 1639230537775
friendly_name: Barn Door Sensor Open
device_class: door`

**Comment by TheRealStark** [comment]
Here is a screenshot of the Eufy app.  It appears to be able to retrieve a battery percentage / number of bars remaining?

![d358f7e5-309f-4007-bbce-5ed9e5bb7c59](https://user-images.githubusercontent.com/92559968/145691604-4ca29d2b-a5d0-4728-8648-d53e6ce973db.jpg)

**Comment by fuatakgun** [comment]
as you can see from device state, it is only exposed `batteryLow: false`, which means we do not know the level, rather an indicator. We can build a sensor around this, if you need explicit battery level, you should create a request over here: https://github.com/bropat/eufy-security-client

**Comment by TheRealStark** [comment]
Yeah, I noticed that.  It would be great if for now we can have an event trigger when batteryLow = true :)
I will post on the bropat about a battery level request for sure.  Thanks again @fuatakgun !

**Comment by fuatakgun** [comment]
Please get latest version and check if you have this binary sensor.

**Comment by TheRealStark** [comment]
I pulled the latest version but don't see any additional sensors available within the device.

**Comment by fuatakgun** [comment]
my bad, try again now

**Comment by TheRealStark** [comment]
It appears!  We'll find out if it works when the battery gets low!  Thanks again for being so incredibly responsive!

**Comment by jouster1974** [comment]
I've also recently got some sensors and can see the status being true/false in a standard status in  a glace card...but when trying to read an open/close status to trigger automation, there seems to be no way to take his value and feed from it...any ideas...happy to test anything...currently on latest versions of both.  

As you can see on the screengrab below, the entry sensor status is set to open with a true/false identifier.....but I cant see a way to read that state anywhere after multiple attempts

![image](https://user-images.githubusercontent.com/15368005/162841716-2b8ddbb0-76ca-4273-8c21-444e5e14206e.png)

**Comment by TheRealStark** [comment]
I managed to get it to work using the State trigger type for the binary sensor:
![image](https://user-images.githubusercontent.com/92559968/162968096-e97a51a7-4ec4-4ad6-83e3-c3c80e3640f5.png)

I had to have it go from False to True in order for it to trigger my automation.  Hope this helps!

**Comment by jouster1974** [comment]
I've managed to sort this with plenty of trial and error and b looking through the logbook.  Discovered that a sensor had been created called 

sensor.front_door_entry_sensor

so used that instead and now I can get icons to change basis the state of the door....perfect...now to see if battery can be done this way too
