### ISSUE TITLE
Pass video to homekit

### ISSUE THREAD

**Issue by air720boarder** [fuatakgun/eufy_security#17]
This integration is amazing! That said, when I share these cameras over HomeKit - I see a log error that says 'stream source not found'. Anything that can be done to overcome this? Would love to just use Home.app for everything, including cameras!

**Comment by fuatakgun** [comment]
You should first enable rtsp/livestream, then stream can be accessible. If
you can set this inside homekit, you can access the stream.

**Comment by fuatakgun** [comment]
if you can expose these services to homekit and call them before trying to view stream, it should work.
