### ISSUE TITLE
[Support] Toggle camera RTMP on the fly

### ISSUE THREAD

**Issue by pierrecle** [fuatakgun/eufy_security#175]
**Is your feature request related to a problem? Please describe.**
To respect my own privacy at home, I would like to turn RTMP while there is someone at home/in a room.

**Describe the solution you'd like**
The ideal solution would be to turn rtmp streaming on/off on the fly per camera.

**Describe alternatives you've considered**
Streaming a blurred/black screen would be a acceptable alternative.

**Comment by fuatakgun** [comment]
Hey, there are multiple services and switches there to enable rtsp streaming option, have you checked them?

**Comment by pierrecle** [comment]
> Hey, there are multiple services and switches there to enable rtsp streaming option, have you checked them?

Thanks for your reply.
Yes I checked the RTSP settings. Thing is, I don't want to turn off the stream on the camera (RTSP setting), I want frigate to analyze my camera images even if I'm at home (I have some automation - lights/heating - based on presence in a room etc). I just want to prevent a human to see the camera images when I'm at home, so in my opinion, being able to stop re-streaming on the fly is the only solution to ensure my family's privacy.

**Comment by fuatakgun** [comment]
So, you can calll rtsp_stop, it shouldn't stop it for all clients but only for home assistant?

**Comment by pierrecle** [comment]
If I'm right `rtsp_stop` will stop RSTP for the camera and not for client (I'm using Eufy cameras).

**Comment by fuatakgun** [comment]
start/stop rtsp livestream should not effect camera, please give it a try

**Comment by pierrecle** [comment]
Ho I'm so sorry, I posted the issue on the wrong project, I would post it on frigate .
Once again, I'm so sorry.

**Comment by fuatakgun** [comment]
No worries :-)
