### ISSUE TITLE
Captcha correct but still not want to accept it..

### ISSUE THREAD

**Issue by xXDjMikeXx** [fuatakgun/eufy_security#176]
**Describe the bug**
I am setting this up the first Time, both Addons running with no Errors, but it always fails at the Captcha

**To Reproduce**

Enter the Captcha, it will load few seconds and then it says "Only a single instance is allowed."
and this at the integration: "Warning: Captcha required - Go to Configurations page for Eufy Security Integration to enter the code"

**Hardware Information about Home Assistant

Home Assistant 2021.12.3

**Comment by briandonahue** [comment]
Thanks for this - noticed 2FA was being triggered but there was nowhere to enter the code.  Created guest account with no 2FA and set up with that and the install instructions worked perfectly.

**Comment by MrBasque** [comment]
Exactly the same issue here. 

2FA was already disabled, I tried the guest account per your suggestion and some outcome "Only a single instance is allowed."

I do receive a mail with a six digit code, but no place to enter that code
