### ISSUE TITLE
HomeBase 2 not disarming

### ISSUE THREAD

**Issue by leonardpitzu** [fuatakgun/eufy_security#180]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
I have a HomeBase2 with 3 EufyCam 2 connected to it.
I have an automation which sounds like this:

- when the house is empty enable motion detection and enable `arm_away`
- when somebody arrives at home enable `disarmed` and disable motion detection

**To Reproduce**
goto Services and arm/disarm the system. If arming works, disarming does not work and vice versa.

**Expected behavior**
The surveillance system shall change the state between armed and disarmed.

**Screenshots**
calling the service
<img width="1221" alt="Screenshot 2021-12-20 at 10 42 04" src="https://user-images.githubusercontent.com/4321813/146738104-f8c74d41-8235-4249-8117-b43b5a4de0ff.png">

but the state remains `armed_away`
<img width="660" alt="Screenshot 2021-12-20 at 10 42 41" src="https://user-images.githubusercontent.com/4321813/146738174-0cab2814-6426-4f2b-8729-5fa70345f74e.png">

**Hardware Information about Home Assistant
docker container on synology NAS (x86 CPU)

**Hardware Information about Cameras
- Camera Model: EufyCam2 + HomeBase 2
- Live Streaming Protocol: RTSP

**Additional context**
Logs:
`2021-12-20 10:35:49 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - WebSocket message sent. {"messageId": "set_guard_mode", "command": "station.set_guard_mode", "serialNumber": "T8010P2320503511", "mode": 63}
2021-12-20 10:35:49 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'result', 'success': True, 'messageId': 'set_guard_mode', 'result': {}}`

**Comment by fuatakgun** [comment]
please restart add-on, reload integration, execute service call and share your add-on logs

**Comment by leonardpitzu** [comment]
I had to remove the add-on and the extension, reboot HA and setup again the add-on and the extension. Now it seems to be working... Weird.
As such please close the issue. If something comes up i will reopen it and attach the logs.
