### ISSUE TITLE
Charging status not changing

### ISSUE THREAD

**Issue by Zeunas** [fuatakgun/eufy_security#181]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
New "Charging status" sensor always "charging" even when doorbell is not charging.

**To Reproduce**
Disconnect doorbell from charging point and see sensor behaviour.

**Expected behavior**
Sensor to change to "not charging"

**Screenshots**
![SmartSelect_20211220-164652_Home Assistant](https://user-images.githubusercontent.com/71456261/146803399-e9d50052-6a06-41b5-88e9-b71d4c3fd2a5.jpg)

**Hardware Information about Home Assistant
Raspberry pi4

**Hardware Information about Cameras

Battery Doorbell 2

**Additional context**
Never seen this sensor with any other status than "charging" since the 1st version that created this sensor.
Current adon version 1.1.0

**Comment by fuatakgun** [comment]
I was just hoping no one would notice it :-)

**Comment by Zeunas** [comment]
I did wonder if you were trying to lay low 😅 for me it's something useful as I have the doorbel plugged to a solar panel and I am monitoring its effectiveness, later I may even use it for some useful automations. No rush! Merry Xmas and happy new year!

**Comment by fuatakgun** [comment]
I had to drop binary sensor as there are more than 2 state for charging sensor, created a `select` entity. 

PS: this is ready-only.

![image](https://user-images.githubusercontent.com/11085566/149554066-80c102a1-b35d-4ad9-9150-b4868de6145b.png)

**Comment by fuatakgun** [comment]
please comment back if you notice issues

**Comment by Zeunas** [comment]
Working great so far. I have created a binary sensor from it. Thanks ;)
