### ISSUE TITLE
States don't update

### ISSUE THREAD

**Issue by juite** [fuatakgun/eufy_security#183]
Hi,

I installed this integration. I see that there has been done a lot of work. Thanks for that. 

I have a question. When ringing the doorbel I don't see the state is changing to true. I set the Cloud scan interval to 2 seconds. But this did not help. The same for al the other states. 

What I would like to get working is to present a streaming video based on a trigger on a AppleTv via Homekit.

Maybe somebody can help me.

Thanks

**Comment by fuatakgun** [comment]
tracking issue: https://github.com/fuatakgun/eufy_security/issues/183

**Comment by fuatakgun** [comment]
you are right about your finding, I am also expecting this to be fixed from underlying library.

**Comment by fuatakgun** [comment]
if it is same for all other sensors, then I need logs from add-on and home assistant logs.

**Comment by juite** [comment]
Hi Fuat,

Here the log of Add-On:

*************************************************************************************
2021-12-28 07:29:57.719  WARN Station @@@ - Heartbeat check failed. Connection seems lost. Try to reconnect... 
2021-12-28 07:29:57.720  INFO Disconnected from station @@@ 
2021-12-28 07:30:02.775  INFO Connected to station @@@ on host 192.168.@@@ and port 27955 
2021-12-28 07:44:34.575  INFO Disconnected from station @@@ 
2021-12-28 07:45:09.589  WARN Station @@@ - Tried all hosts, no connection could be established 
2021-12-28 07:45:09.590  INFO Timeout connecting to station @@@
2021-12-28 07:45:20.182  INFO Connected to station @@@ on host 192.168.@@@ and port 12942 
2021-12-28 07:46:48.612  INFO Disconnected from station @@@ 
2021-12-28 07:47:08.644  INFO Connected to station @@@ on host @@@@@and port 62840 
2021-12-28 15:43:49.670  INFO Push notification token is expiring, renew it. 
2021-12-28 15:43:49.726  ERROR Status return code not 200 
{
  status: 400,
  statusText: 'Bad Request',
  data: {
    error: {
      code: 400,
      message: 'Invalid JSON payload received. Unknown name "fid": Cannot find field.\n' +
        'Invalid JSON payload received. Unknown name "appId": Cannot find field.\n' +
        'Invalid JSON payload received. Unknown name "authVersion": Cannot find field.\n' +
        'Invalid JSON payload received. Unknown name "sdkVersion": Cannot find field.',
      status: 'INVALID_ARGUMENT',
      details: [
        {
          '@type': 'type.googleapis.com/google.rpc.BadRequest',
          fieldViolations: [
            {
              description: 'Invalid JSON payload received. Unknown name "fid": Cannot find field.'
            },
            {
              description: 'Invalid JSON payload received. Unknown name "appId": Cannot find field.'
            },
            {
              description: 'Invalid JSON payload received. Unknown name "authVersion": Cannot find field.'
            },
            {
              description: 'Invalid JSON payload received. Unknown name "sdkVersion": Cannot find field.'
            }
          ]
        }
      ]
    }
  }
}
2021-12-28 15:43:49.736  ERROR Generic Error: 
 Error  FID Token renewal failed with error: Bad Request
error stack:
• service.ts:134 renewFidToken
    node_modules/eufy-security-client/src/push/service.ts:134:23
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• service.ts:164 renewPushCredentials
    node_modules/eufy-security-client/src/push/service.ts:164:16
• service.ts:512 _open
    node_modules/eufy-security-client/src/push/service.ts:512:32
• service.ts:531 <anonymous>
    node_modules/eufy-security-client/src/push/service.ts:531:17
2021-12-28 15:43:50.429  INFO Push notification connection successfully established 

*************************************************************************************

How would you like to receive the HA log? bigger then 2GB..

Thanks.

**Comment by fuatakgun** [comment]
Just for some clarity, events like ringing, motion detection and crying are detected through push notifications, so increased cloud updates will not an impact. I feel like there is an issue in regards to support of add-on, a lot of errors are raised there.

Can you please work with @bropat over eufy-security-ws repository?also please double check if your devices are supported following readme file.

**Comment by juite** [comment]
Thanks. I will check @bropat.

2FA is not enabled. And I think it is the captcha. It doesnot show up. Even not after disabe and enable again...

**Comment by fuatakgun** [comment]
Please restart add on and reload integration later on and share the logs again from add on.

**Comment by juite** [comment]
Done…
![127AFC00-2C9F-4995-8027-ED86ED83965F](https://user-images.githubusercontent.com/365238/147702587-69857dc1-13db-49c0-9fdf-d141b240fc0e.jpeg)

**Comment by SvenVerheesen** [comment]
Hi,

I am experiencing the same problems as described above.

**Comment by fuatakgun** [comment]
These reconnections are not normal, can you create an issue under eufy-security-ws repository and link it also here?

**Comment by fuatakgun** [comment]
I just re-tested locally, captcha is working fine for me. Please update here, until then resolving here.

**Comment by BinaryShrub** [comment]
![image](https://user-images.githubusercontent.com/10691501/149385124-a0921860-5ea6-4a84-ac05-8ca596609d93.png)
I'm also getting this when trying to setup
