### ISSUE TITLE
Person Detection should include Motion Detection

### ISSUE THREAD

**Issue by kenni** [fuatakgun/eufy_security#184]
First: Thanks a lot for a great integration, it's really nice being able to have my Eufy cameras integrated in Home Assistant :)

After trying to understand and get the motion detection sensors to work for a couple of hours with a lot of trial-and-error, I have a suggestion for improving usability of the Motion sensors. Logically, if a person is detected, there must have been motion. Therefore, it would make sense to *always* enable the "Motion Sensor" in HA, whenever the "Person Detector Sensor" is enabled. It makes it logically easier to understand and easier to implement for everyone who wants to use the built-in sensor for controlling lights during daytime (without video recording enabled) and for surveillance at night (with video recording enabled).

I understand that it is probably just how the Eufy API is implemented (I haven't looked), but if so, it would make sense to implement a helper/fixer-function in the HA integration. The recording action on the camera must necessarily be triggered internally by the motion sensor, after which it captures the video frames and does its image processing on it to detect a person. So the fact that it doesn't pass on the basic motion detection trigger is just incorrect IMHO - and it caused great confusion when trying to set it up in HA.

I hope you'll consider this, in the meantime I'll go ahead and add both sensors to all of my flows :)

Thanks in advance.

**Comment by fuatakgun** [comment]
thanks for bringing this up, let's start working eufy notifications, there are two types of notifications;
- person is detected
- motion (not person) is detected
so, in essence, motion sensor means there is something noticed but it is not classified as person. so, rather than merging person into motion, we can create a new global sensor to include all types of motions (motion, person, pet), what do you think?

**Comment by kenni** [comment]
Yes, that sounds like a fine approach - if there's a global motion sensor including everything, it is more obvious to newcomers that the standard motion (not person) sensor doesn't include all motions.

**Comment by fuatakgun** [comment]
global_motion_sensor is created, please get latest version

**Comment by kenni** [comment]
Thanks, @fuatakgun , I've updated to v2.2.0 and got the global sensor, but it doesn't seem to work - it only include motions from generic (not person) motions?

When "Record Video" is disabled in "Security Mode Settings", the global sensor works as expected:
<img width="506" alt="Screenshot 2022-01-16 at 00 03 42" src="https://user-images.githubusercontent.com/486971/149640600-515c0b70-07d8-4d49-9831-6fefdeb58e35.png">

However, when "Record Video" is enabled in "Security Mode Settings" and a person is detected, the global sensor is *not* updated:
<img width="506" alt="Screenshot 2022-01-16 at 00 02 29" src="https://user-images.githubusercontent.com/486971/149640593-8d3eb5bd-8f97-49a5-87e5-dde0a705669d.png">

Any idea what's going on? Thanks.

**Comment by fuatakgun** [comment]
Thanks for getting back on this. I need to check locally to understand the issue.

Video recording is required to distinguish people vs motion, but it is just a requirement of Eufy, i can do nothing about it .

**Comment by fuatakgun** [comment]
please get master version to test, should be fixed now (hopefully)

**Comment by kenni** [comment]
@fuatakgun - Confirmed - Issue fixed in v2.2.2 :) Thanks!
