### ISSUE TITLE
Battery Doorbell start p2p streaming

### ISSUE THREAD

**Issue by marek-nereca** [fuatakgun/eufy_security#185]
**Describe the bug**
ffmpeg does not start

**To Reproduce**
1. In automation call service eufy_security.start_p2p_livestream with entity doorbell
2. Go to device info
3. sensor.doorbell_streaming_source_address is empty

**Expected behavior**
sensor.doorbell_streaming_source_address should have value eufy_security-T8210xxxxxxxx.m3u8 but is empty

**Screenshots**
<img width="350" alt="image" src="https://user-images.githubusercontent.com/45018033/147077454-2357b736-53d6-4fc4-b560-198855e3bdee.png">

**Hardware Information about Home Assistant
Raspberry pi4

**Hardware Information about Cameras
- Camera Model: Battery Doorbell T8210
- Live Streaming Protocol: P2p

**Additional context**
In logs is message about sending websocket message to start streaming, but there is no log message about start_p2p or start_ffmpeg. 
It worked just one time right after integration installation. But i was not able to start ffmpeg again. Maybe problem is that set_is_streaming is called only in constructor and not in start_p2p_livestream. But i'm not familiar with your codebase yet.... I hope i just doing something wrong...

My goal is play media media-source://media_source/local/eufy_security-T8210xxxxxxx.m3u8 on google nest display since official integration have 25 second delay.

**Comment by fuatakgun** [comment]
Hey, i see that you are using file based streaming rather than rtsp add-on one. Please follow README, install rtsp server add on and configure integration accordingly and keep me updated.

**Comment by marek-nereca** [comment]
Hi, i managed to turn on rtsp and also webrtc. But it behaves wierdly. 
I have automation which call start_p2p_livestream and after 30 seconds call stop_p2p_livestream for doorbell entity.
here is lovelace view for doorbell
```
  - title: Doorbell
    path: doorbell
    icon: mdi:bell
    badges: []
    cards:
      - type: conditional
        conditions:
          - entity: binary_sensor.doorbell_streaming_sensor
            state: 'True'
        card:
          type: custom:webrtc-camera
          entity: camera.doorbell
```
my exceptation is that player will show stream for 30 seconds after automation is triggered and then player goes away.
(I dont need to start streaming by tap from lovelace card)
And it work, but some time (~10seconds) after stopping from automation streaming start again. I wonder what initiate streaming, maybe webrtc player? Surely not an automation... 

Things get worse after some time. Streaming sensor is true but there is no video in webrtc player.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/45018033/147212595-ec2edb8f-4e7c-43cd-8134-35abb1aad53d.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/45018033/147212421-bc69b8b4-7f28-49e6-90c8-0f273179bb2d.png">

In this state automation still work in meaning that 30 seconds after trigger goes Streaming Sensor to false. But there is no video in webrtc player...

this is in error log:
2021-12-23 10:37:18 ERROR (Thread-22) [custom_components.eufy_security] eufy_security Doorbell video_thread exception: [Errno 32] Broken pipe- traceback: Traceback (most recent call last):
  File "/config/custom_components/eufy_security/camera.py", line 161, in write_bytes_to_ffmeg
    self.ffmpeg.process.stdin.write(frame_bytes)
BrokenPipeError: [Errno 32] Broken pipe

Reloading of integration does not help. I have to restart home assistant.

**Comment by fuatakgun** [comment]
be sure to disable this option below;
![image](https://user-images.githubusercontent.com/11085566/147222105-9d5c3ab2-c545-4198-9423-be2a2f9d54a5.png)

**Comment by fuatakgun** [comment]
I also prefer to merge this into https://github.com/fuatakgun/eufy_security/issues/126

Let me know if it is ok?

**Comment by marek-nereca** [comment]
Disabling Auto Start on Click helped a lot. Now it is much more stable. But still i have to restart HA sometimes.
I'm looking forward to new release, thank you for your help.
And yes it is ok to merge it. Thanks again.
