### ISSUE TITLE
Cannot import name 'EntityCategory'

### ISSUE THREAD

**Issue by dpomnean** [fuatakgun/eufy_security#186]
**Describe the bug**
HASS logs reporting 

```
Unable to prepare setup for platform eufy_security.binary_sensor: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform eufy_security.sensor: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform eufy_security.switch: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform eufy_security.select: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
```

**Hardware Information about Home Assistant
Pi4
core-2021.11.5
Eufy HACS version 1.1.0
bropat docker container version 0.6.0

**Hardware Information about Cameras
- Doorbell T8210
- Floodlight T8422
- Homebase T8010

**Additional context**

I tried this configuration setting enabled/disabled still getting same error

 **Fix Binary Sensor States (True/False to On/Off)**

Doing a locate on entity.py on my server, I found it in a different location under 

```
/opt/hass/custom_components/eufy_security/entity.py
```

I could create a symlink as a workaround but wanted to get your thoughts first.

**Comment by fuatakgun** [comment]
I believe your HA version is old, i am on 2021.12.0 and it is working fine

**Comment by fuatakgun** [comment]
I also see that entitycategory is in correct place.

https://github.com/home-assistant/core/blame/72d8882c7986d1cb869795c10603a6a1052ed28b/homeassistant/helpers/entity.py

**Comment by fuatakgun** [comment]
Symlink would not work, we need original HA entity class, not from this integration

**Comment by dpomnean** [comment]
Yeah I was afraid of that. I will try upgrading later tonight and will reply back if it is working or not.

**Comment by fuatakgun** [comment]
If you want to avoid the upgrade, try to get only the specific file from home assistant repository, we need only some strings from there

**Comment by dpomnean** [comment]
Instead of fiddling with workarounds I updated to the latest version 2021.12.5 and it is working correctly.
