### ISSUE TITLE
Home/away arm/disarm services not available?

### ISSUE THREAD

**Issue by marcuswhit** [fuatakgun/eufy_security#187]
I have installed the package as per the readme, and using NodeRed I am able to change the security mode for my homebase to one of the custom modes I've setup.  But oddly enough I can't see the option for enabling home or away mode... I was expecting to see an `alarm_arm_home` or `alarm_guard_home`?

![image](https://user-images.githubusercontent.com/2963426/147400811-9e2dec33-d7b5-4f50-b598-e10a37bccf57.png)

**Comment by fuatakgun** [comment]
They are under `alarm control panel` domain
