### ISSUE TITLE
I want to be able to turn on the alarm of my cameras

### ISSUE THREAD

**Issue by Wummeke** [fuatakgun/eufy_security#190]
Hi, could you add a switch to the cameras so I can trigger the (anti-theft) alarm on them from Home-Assistant?
A few nights ago my parents got a unwanted visitor. Luckily nothing happend, but he got caught on camera. I would like to supply my parents with a button in HA or even a actual button which make the alarm on the camera's go off.

Thanks!

**Comment by fuatakgun** [comment]
is this request to trigger the alarm sound on cameras or enable/disable anti theft alarm?

**Comment by Wummeke** [comment]
Well, if you could do both, that would be even better of course. But I was hoping for triggering the alarmsound.

**Comment by hipsi** [comment]
I too would love this ability. I have 2x indoor 2K cams, and the home security system. I would like to be able to activate the alarm tone on the cameras when when the system is in alarm state, which can't be done from the Eufy app because the cameras don't work with the Homebase.

**Comment by fuatakgun** [comment]
new services are introduced;
- alarm_trigger_for_camera_with_duration
- reset_alarm_for_camera

**Comment by fuatakgun** [comment]
```
service: eufy_security.alarm_trigger_for_camera_with_duration
data:
  duration: 10
target:
  entity_id: camera.entrance
```

```
service: eufy_security.reset_alarm_for_camera
data: {}
target:
  entity_id: camera.entrance
```
