### ISSUE TITLE
Reflect names of custom states on alarm panel

### ISSUE THREAD

**Issue by ShayGus** [fuatakgun/eufy_security#192]
**Is your feature request related to a problem? Please describe.**
Right now the predefined states on the alarm panel are out of sync with what the app is actually offering.
For example Night isn't available on the app.
Also when defining custom states in the app, user will usually give them names, so it would be great to be able to arm the alarm with those names.
In addition right now even without the names, custom alarm states such custom1 do not appear as an option to choose in the alarm panel.

**Describe the solution you'd like**
1. The ability to arm custom alarm states from the alarm panel.
2. The names of the custom alarm definitions should be as defined by the user in the eufy security app instead of just being called custom1 or custom2.

**Describe alternatives you've considered**
Right now the only alternative is to define my own panel and calling those services with a button press

**Additional context**
![image](https://user-images.githubusercontent.com/2332415/147872785-68558273-f226-4301-8fa3-3edef9595eec.png)

**Comment by fuatakgun** [comment]
merging into https://github.com/fuatakgun/eufy_security/issues/145
