### ISSUE TITLE
set the volume of the indoor chime?

### ISSUE THREAD

**Issue by atv2016** [fuatakgun/eufy_security#193]
Many eufy devices, like the doorbell for example, have a variable named chimeHomebaseRingtoneVolume: 12

I'm trying to adjust the volume of the homebase ringtone, but it doesn't seem to update in the app (different account of course).

I tried using switch.doorbell.indoor_chime and others, and although it accepts a new value, it doesn't reflect in the app (haven't tested in real life but assume it will not update the volume.

**Comment by fuatakgun** [comment]
How did you try to accomplish this?

**Comment by atv2016** [comment]
I just set the variable in developer tools.
________________________________

**Comment by fuatakgun** [comment]
i don't think it would work, there should be either a service call or a button or a select entity. Setting a state of an entity manually will be overridden in next cycle.

Ok, i will create a select entity for this.

**Comment by atv2016** [comment]
Seems there is a entity called: switch.doorbell_indoor_chime. Can i somehow call the set the state attributes (if i look in developer tools i see all states, as below (excerpt) :

 chimeHomebaseRingtoneVolume: 12
  chimeHomebaseRingtoneType: 0
  notificationType: 2
  notificationRing: 1
  notificationMotion: 1

**Comment by atv2016** [comment]
So I just figured out if you choose device in an action and choose doorbell you can just choose to turn the indoor chime off. 

Great, except I don’t see the volume actually going down. Not sure if it’s working or not.

**Comment by fuatakgun** [comment]
a new entity is created as `Chime Volume`, you can use this `select` entity to set the volume

**Comment by fuatakgun** [comment]
![image](https://user-images.githubusercontent.com/11085566/149561059-647dd633-069a-4cd9-9c88-6cc25c1efa39.png)
