### ISSUE TITLE
Preview stream of Doorbell 2k Battery Powered

### ISSUE THREAD

**Issue by Jo-Jo1987** [fuatakgun/eufy_security#198]
Hi Currently i am able to see the thumbnail and the stream whenever something got detected.

I would like to pop-up the doorbell camera just like a normal camera just to break in and see the RTSP or P2P stream.

But unfortunately this does not seem to work yet with this Eufy Doorbell 2k Battery Powered

Can this be fixed please?

Thanks in advance,
https://www.youtube.com/watch?v=xrV_-3ygtAo this guy also explains your addon which is working good! But he doesn't get the doorbells working in a live stream fashion as well. So hopefully this can be builtin!

**Comment by fuatakgun** [comment]
Hey, rather than using built in streaming functionality of home assistant, use webrtc custom component. it is much more faster and reliable.

**Comment by Jo-Jo1987** [comment]
I tried to use that. But i don't know why this way does not work:

type: 'custom:webrtc-camera'
entity: camera.generic_stream

**Comment by fuatakgun** [comment]
You should use camera.entrance or whatever your camera entity name. I am sure it is not generic_stream.

**Comment by Jo-Jo1987** [comment]
I used my entity which is right> camera.voordeur

**Comment by fuatakgun** [comment]
Then what is the error?

**Comment by Jo-Jo1987** [comment]
ERROR : Can't get url for camera.voordeur

**Comment by fuatakgun** [comment]
You should start streaming first and then you will see the video. Please follow README.

**Comment by Jo-Jo1987** [comment]
![image](https://user-images.githubusercontent.com/45689992/148127004-a50ca1ee-04f4-49ae-8103-a1df3c8434c3.png)

Then i return to the lovelace card, and it cannot load

**Comment by Jo-Jo1987** [comment]
![image](https://user-images.githubusercontent.com/45689992/148127059-0923f6f0-a5cb-423b-84ad-dcfcd071146c.png)

**Comment by Jo-Jo1987** [comment]
2022/01/04 21:54:40 I [0/0] [RTSP] [conn 172.30.32.1:46952] closed
2022/01/04 21:54:41 I [0/0] [RTSP] [conn 172.30.32.1:47030] opened
2022/01/04 21:54:41 I [0/0] [path T8210P64214716FE] created
2022/01/04 21:54:41 I [0/0] [path T8210P64214716FE] runOnDemand command started
2022/01/04 21:54:51 I [0/0] [path T8210P64214716FE] runOnDemand command stopped
2022/01/04 21:54:51 I [0/0] [path T8210P64214716FE] destroyed
2022/01/04 21:54:51 I [0/0] [RTSP] [conn 172.30.32.1:47030] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:54:51 I [0/0] [RTSP] [conn 172.30.32.1:47030] closed
2022/01/04 21:56:17 I [0/0] [RTSP] [conn 172.30.32.1:47576] opened
2022/01/04 21:56:17 I [0/0] [path T8210P64214716FE] created
2022/01/04 21:56:17 I [0/0] [path T8210P64214716FE] runOnDemand command started
2022/01/04 21:56:17 I [0/0] [RTSP] [conn 172.30.32.1:47586] opened
2022/01/04 21:56:18 I [0/0] [RTSP] [conn 172.30.32.1:47592] opened
2022/01/04 21:56:18 I [0/0] [RTSP] [session 928234204] opened by 172.30.32.1:47592
2022/01/04 21:56:18 I [1/0] [RTSP] [session 928234204] is publishing to path 'T8210P64214716FE', 1 track with TCP
2022/01/04 21:56:18 I [1/0] [RTSP] [session 520065697] opened by 172.30.32.1:47576
2022/01/04 21:56:18 I [1/0] [RTSP] [session 776660797] opened by 172.30.32.1:47586
2022/01/04 21:56:18 I [1/1] [RTSP] [session 776660797] is reading from path 'T8210P64214716FE', 1 track with TCP
2022/01/04 21:56:18 I [1/1] [RTSP] [session 128061595] opened by 172.30.32.1:47576
2022/01/04 21:56:18 I [1/2] [RTSP] [session 128061595] is reading from path 'T8210P64214716FE', 1 track with TCP
2022/01/04 21:56:24 I [1/2] [RTSP] [conn 172.30.32.1:47576] closed
2022/01/04 21:56:24 I [1/2] [RTSP] [session 520065697] closed
2022/01/04 21:56:24 I [1/1] [RTSP] [session 128061595] closed
2022/01/04 21:56:27 I [1/1] [RTSP] [conn 172.30.32.1:47652] opened
2022/01/04 21:56:27 I [1/1] [RTSP] [session 152142191] opened by 172.30.32.1:47652
2022/01/04 21:56:27 I [1/1] [RTSP] [session 341593612] opened by 172.30.32.1:47652
2022/01/04 21:56:27 I [1/2] [RTSP] [session 341593612] is reading from path 'T8210P64214716FE', 1 track with TCP
2022/01/04 21:56:32 I [1/2] [RTSP] [conn 172.30.32.1:47652] closed
2022/01/04 21:56:32 I [1/2] [RTSP] [session 152142191] closed
2022/01/04 21:56:32 I [1/1] [RTSP] [session 341593612] closed
2022/01/04 21:56:36 I [1/1] [RTSP] [conn 172.30.32.1:47662] opened
2022/01/04 21:56:36 I [1/1] [RTSP] [session 485259801] opened by 172.30.32.1:47662
2022/01/04 21:56:36 I [1/1] [RTSP] [session 832591645] opened by 172.30.32.1:47662
2022/01/04 21:56:36 I [1/2] [RTSP] [session 832591645] is reading from path 'T8210P64214716FE', 1 track with TCP
2022/01/04 21:56:37 I [1/2] [RTSP] [conn 172.30.32.1:47586] closed
2022/01/04 21:56:37 I [1/1] [RTSP] [session 776660797] closed
2022/01/04 21:56:42 I [1/1] [RTSP] [conn 172.30.32.1:47662] closed
2022/01/04 21:56:42 I [1/1] [RTSP] [session 485259801] closed
2022/01/04 21:56:42 I [1/0] [RTSP] [session 832591645] closed
2022/01/04 21:56:52 I [0/0] [path T8210P64214716FE] runOnDemand command stopped
2022/01/04 21:56:52 I [0/0] [path T8210P64214716FE] destroyed
2022/01/04 21:56:52 I [0/0] [RTSP] [conn 172.30.32.1:47592] closed
2022/01/04 21:56:52 I [0/0] [RTSP] [session 928234204] closed
2022/01/04 21:57:10 I [0/0] [RTSP] [conn 172.30.32.1:47872] opened
2022/01/04 21:57:10 I [0/0] [path T8210P64214716FE] created
2022/01/04 21:57:10 I [0/0] [path T8210P64214716FE] runOnDemand command started
2022/01/04 21:57:20 I [0/0] [path T8210P64214716FE] runOnDemand command stopped
2022/01/04 21:57:20 I [0/0] [path T8210P64214716FE] destroyed
2022/01/04 21:57:20 I [0/0] [RTSP] [conn 172.30.32.1:47872] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:57:20 I [0/0] [RTSP] [conn 172.30.32.1:47872] closed
2022/01/04 21:57:22 I [0/0] [RTSP] [conn 172.30.32.1:47948] opened
2022/01/04 21:57:22 I [0/0] [path T8210P64214716FE] created
2022/01/04 21:57:22 I [0/0] [path T8210P64214716FE] runOnDemand command started
2022/01/04 21:57:26 I [0/0] [RTSP] [conn 172.30.32.1:48006] opened
2022/01/04 21:57:30 I [0/0] [RTSP] [conn 172.30.32.1:48014] opened
2022/01/04 21:57:32 I [0/0] [path T8210P64214716FE] runOnDemand command stopped
2022/01/04 21:57:32 I [0/0] [path T8210P64214716FE] destroyed
2022/01/04 21:57:32 I [0/0] [RTSP] [conn 172.30.32.1:48014] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:57:32 I [0/0] [RTSP] [conn 172.30.32.1:48014] closed
2022/01/04 21:57:32 I [0/0] [RTSP] [conn 172.30.32.1:47948] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:57:32 I [0/0] [RTSP] [conn 172.30.32.1:47948] closed
2022/01/04 21:57:32 I [0/0] [RTSP] [conn 172.30.32.1:48006] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:57:32 I [0/0] [RTSP] [conn 172.30.32.1:48006] closed
2022/01/04 21:58:53 I [0/0] [RTSP] [conn 172.30.32.1:48456] opened
2022/01/04 21:58:53 I [0/0] [path T8210P64214716FE] created
2022/01/04 21:58:53 I [0/0] [path T8210P64214716FE] runOnDemand command started
2022/01/04 21:59:03 I [0/0] [path T8210P64214716FE] runOnDemand command stopped
2022/01/04 21:59:03 I [0/0] [path T8210P64214716FE] destroyed
2022/01/04 21:59:03 I [0/0] [RTSP] [conn 172.30.32.1:48456] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:59:03 I [0/0] [RTSP] [conn 172.30.32.1:48456] closed
2022/01/04 21:59:05 I [0/0] [RTSP] [conn 172.30.32.1:48546] opened
2022/01/04 21:59:05 I [0/0] [path T8210P64214716FE] created
2022/01/04 21:59:05 I [0/0] [path T8210P64214716FE] runOnDemand command started
2022/01/04 21:59:15 I [0/0] [path T8210P64214716FE] runOnDemand command stopped
2022/01/04 21:59:15 I [0/0] [path T8210P64214716FE] destroyed
2022/01/04 21:59:15 I [0/0] [RTSP] [conn 172.30.32.1:48546] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:59:15 I [0/0] [RTSP] [conn 172.30.32.1:48546] closed
2022/01/04 21:59:47 I [0/0] [RTSP] [conn 172.30.32.1:48808] opened
2022/01/04 21:59:47 I [0/0] [path T8210P64214716FE] created
2022/01/04 21:59:47 I [0/0] [path T8210P64214716FE] runOnDemand command started
2022/01/04 21:59:51 I [0/0] [RTSP] [conn 172.30.32.1:48818] opened
2022/01/04 21:59:51 I [0/0] [RTSP] [conn 172.30.32.1:48822] opened
2022/01/04 21:59:55 I [0/0] [RTSP] [conn 172.30.32.1:48856] opened
2022/01/04 21:59:57 I [0/0] [path T8210P64214716FE] runOnDemand command stopped
2022/01/04 21:59:57 I [0/0] [path T8210P64214716FE] destroyed
2022/01/04 21:59:57 I [0/0] [RTSP] [conn 172.30.32.1:48818] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:59:57 I [0/0] [RTSP] [conn 172.30.32.1:48818] closed
2022/01/04 21:59:57 I [0/0] [RTSP] [conn 172.30.32.1:48808] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:59:57 I [0/0] [RTSP] [conn 172.30.32.1:48808] closed
2022/01/04 21:59:57 I [0/0] [RTSP] [conn 172.30.32.1:48856] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:59:57 I [0/0] [RTSP] [conn 172.30.32.1:48856] closed
2022/01/04 21:59:57 I [0/0] [RTSP] [conn 172.30.32.1:48822] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 21:59:57 I [0/0] [RTSP] [conn 172.30.32.1:48822] closed
2022/01/04 21:59:59 I [0/0] [RTSP] [conn 172.30.32.1:48910] opened
2022/01/04 21:59:59 I [0/0] [path T8210P64214716FE] created
2022/01/04 21:59:59 I [0/0] [path T8210P64214716FE] runOnDemand command started
2022/01/04 22:00:09 I [0/0] [path T8210P64214716FE] runOnDemand command stopped
2022/01/04 22:00:09 I [0/0] [path T8210P64214716FE] destroyed
2022/01/04 22:00:09 I [0/0] [RTSP] [conn 172.30.32.1:48910] ERR: source of path 'T8210P64214716FE' has timed out
2022/01/04 22:00:09 I [0/0] [RTSP] [conn 172.30.32.1:48910] closed

**Comment by Jo-Jo1987** [comment]
fixed, it was the quality i forgot to set to low streaming quality and also video codec

Is there a way that when the thumbnail is pressed in the devices page it can also open up the stream?

**Comment by Jo-Jo1987** [comment]
![image](https://user-images.githubusercontent.com/45689992/148131760-a9d561ca-b504-47ca-9dff-28750abfe2e6.png)
Above is 
type: grid
square: false
columns: 1
cards:
  - type: entities
    entities:
      - entity: sensor.voordeur_detected_person_name
        name: Detected Person Name
      - entity: binary_sensor.voordeur_motion_sensor
        name: Motion Sensor
      - entity: binary_sensor.voordeur_ringing_sensor
        name: Ringing Sensor
    title: Voordeur
  - type: picture-entity
    entity: camera.voordeur

Second one : 
type: custom:webrtc-camera
entity: camera.voordeur

**Comment by fuatakgun** [comment]
Happy to hear that you have resolved. About streaming inside popup, i don't have a solution in place yet but even i have, i would always stick with webrtc because of speed.

**Comment by Jo-Jo1987** [comment]
I noticed thanks a lot! I love this integration. Would appreciate if that would also be done with the Xiaomi Mi Gateway Camera chuangmi.gateway.ipc011 and that there will be a P2P support option in the future

**Comment by fuatakgun** [comment]
Big thanks go to @bropat, maintainer of web socket library which enabled communication between home assistant and eufy.

https://ko-fi.com/bropat

**Comment by apeeters** [comment]
> fixed, it was the quality i forgot to set to low streaming quality and also video codec

@Jo-Jo1987 Can you please share which changes you made to fix this?

**Comment by Jo-Jo1987** [comment]
I use p2p and using the integration of bropat.

With these settings:
![image](https://user-images.githubusercontent.com/45689992/168534403-6a69b05d-cdf7-4894-86ee-7cf4e28871ea.png)


Fix binary states helped me in order to make an automation on top. That google will tell me when there was movement detected.
And then i can see the thumbnail . And if i click i can see it P2P and not RTSP which is adviced.

**Comment by Jo-Jo1987** [comment]
Change in the options the on/off to true and false.

You will be able to get that working again too
