### ISSUE TITLE
Host Lockup upon starting streams

### ISSUE THREAD

**Issue by jbrukardt** [fuatakgun/eufy_security#20]
Upon starting the stream from the developer services menu, the host locks up within a minute or two, and HA stalls on next startup until the Eufy Security integration is disabled, the host rebooted, and then re-enabled after a clean HA boot.   

8 Cameras, all T8400 2k indoor cams 

Home assistant supervised, debian 10, running in a proxmox vm.    Host system is an i5 NUC.

**Comment by fuatakgun** [comment]
I had relied on ayncio (non threaded) event loop to listen web socket for data streams and generate the video file at the same time. And all of these things are happening at the same thread with main home assistant which is processor consuming for our hardware. So, next steps are;
- create a thread for incoming video messages
- create a thread for processing accumulated video messages to create video file

On the other hand, it is possible that I am quite newbie to asyncio and i am missing fundamentals of it.

**Comment by fuatakgun** [comment]
Assuming these cameras work in 2k stream mode, can you try with lowering stream quality, so  i can find correct problem to focus on.

**Comment by isabellaalstrom** [comment]
@fuatakgun Should I lower to low or medium? I have auto right now.

**Comment by fuatakgun** [comment]
let's start with low and we can increase progressively? thanks

**Comment by jbrukardt** [comment]
Gathering data on this, mine was also set to auto.    I'm recording my CPU use as I add a camera one at a time to see where the threshold that causes lockup is.   

Oddly, the method of getting the stream to work (call camera-turnoff, camera-turnon) does not seem to cause lockup, nor major increased cpu usage (about 5% per active stream on my i5-6500te).    Its only when you manually start the stream using Eufy Security: Start Live Stream that the lockup occurs.

**Comment by fuatakgun** [comment]
Thanks for your input, it seems to be an issue of encoding 2k video under HA thread. I have updated codebase to support threading so that HA will not be impacted with video encoding, please get latest updates and let me know your result with low/medium/high quality.

**Comment by jbrukardt** [comment]
The ffmpeg error about h265 is interesting, i wonder if "low" uses h.264 and thats more easily consumable.   H265 takes a lot more cpu to decode

**Comment by fuatakgun** [comment]
at code level, there are 2 codecs, either h265 or h264. https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/camera.py#L340

I have updated README section with our findings : https://github.com/fuatakgun/eufy_security/blob/master/README.md#troubleshooting

Can you share error log about H265 from ffmpeg?

**Comment by dpomnean** [comment]
I believe this is where the h264/h265 encoding is set in the eufy app for 2k encoding. I believe if you set that option to low, it works fine


![Screenshot_20210726-122956](https://user-images.githubusercontent.com/17032114/127025213-ce12afc6-5182-4699-beb2-b8c033f3bd5a.png)

**Comment by fuatakgun** [comment]
> The ffmpeg error about h265 is interesting, i wonder if "low" uses h.264 and thats more easily consumable. H265 takes a lot more cpu to decode

at code level, there are 2 codecs, either h265 or h264. https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/camera.py#L340

I have updated README section with our findings : https://github.com/fuatakgun/eufy_security/blob/master/README.md#troubleshooting

Can you share error log about H265 from ffmpeg?

**Comment by fuatakgun** [comment]
I am not able to reproduce this using your camera locally, please test with latest codebase if this issue still persists.

**Comment by jbrukardt** [comment]
The new methodology of separating the threads results in a higher overall CPU increase (34% per stream).   

A strange side effect is that the three minute limitation is no longer in place.  Streams will play as long as you leave them open without closing

It appears to be much stabler though, as noted.   No lockups identified

**Comment by fuatakgun** [comment]
You should not have any issues regarding to limitation as your cameras are always on power. I was expecting only battery powered cameras should have this limitation.

On the other hand, consuming of cpu power, we dont have anything in place other than using lower quality as h265 is very cpu intensive.

**Comment by jbrukardt** [comment]
Closing this issue,   For those experiencing excessive CPU, dropping the quality to low in the app brings it down to less than 2% of my CPU per stream.
