### ISSUE TITLE
Can't get it done...

### ISSUE THREAD

**Issue by dbbdark1990** [fuatakgun/eufy_security#201]

**Comment by dbbdark1990** [comment]
in edit mode i see live feed:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/94994900/148269622-3f291692-b33c-418b-88bc-3fc46dabfd09.png">

Code : 
type: conditional
conditions:
  - entity: binary_sensor.entrance_streaming_sensor
    state: 'False'
card:
  type: picture-entity
  entity: camera.voordeur
  tap_action:
    action: call-service
    service: camera.turn_on
    service_data: {}
    target:
      entity_id: camera.voordeur


in non edit mode i see nothing:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/94994900/148269688-de362c67-511d-4f67-b036-b5544fb9a63b.png">

Code:

type: conditional
conditions:
  - entity: binary_sensor.voordeur_streaming_sensor
    state: 'True'
card:
  type: custom:webrtc-camera
  entity: camera.voordeur

**Comment by fuatakgun** [comment]
1- to get rid if files, enable rtsp server add on in options (following readme)
2- for conditional cards, you are using `entrance` as camera name, replace it.

**Comment by verwirrrung** [comment]
I have tons of the eufy_security-T8200N00195030C99xx.ts files and the RTSP server add on is already enabled. Can I manually delete these?

![image](https://user-images.githubusercontent.com/71836292/148283440-e2fcdec9-13e7-4fef-a8d6-d339d894c5b4.png)

![image](https://user-images.githubusercontent.com/71836292/148283743-62d7b195-2b5f-4ad4-a65e-84035cb16d69.png)

**Comment by fuatakgun** [comment]
Yes, they are generated before you had enabled rtsp server add-on

**Comment by verwirrrung** [comment]
dang! you are quick! and you are right, looking at the timestamp, they were created before I enabled the add-on... Thanks!

**Comment by dbbdark1990** [comment]
> 1- to get rid if files, enable rtsp server add on in options (following readme) 2- for conditional cards, you are using `entrance` as camera name, replace it.

oeps sorry for 2- change it but still disapair when i close the edit page

**Comment by fuatakgun** [comment]
did not get your last message?

**Comment by fuatakgun** [comment]
please update here to make the problem clear, until then closing
