### ISSUE TITLE
Can't get live image on doorbell in lovelace (TCP port not avail?)

### ISSUE THREAD

**Issue by atv2016** [fuatakgun/eufy_security#202]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Clicking on the lovelace card does not give me the live doorbell. Other frontend stuff seems to work ok.

**To Reproduce**
1. Go to 'Lovelace card'
2. Click on 'Doorbell image'
3. Scroll down to 'n/a'
4. See error (see screenshots)

**Expected behavior**
Live image

**Screenshots**
See attached

**Hardware Information about Home Assistant
Runs on laptop in VM

**Hardware Information about Cameras
- Camera Model 
Eufy battery 2K doorbell
- Live Streaming Protocol: RTSP or P2p
P2P is enabled

**Additional context**
Whole bunch of errors in the logs, not sure if significant. FFmpeg i have enabled in configuration.yaml by doing ffmpeg: , no parameters.

**Comment by atv2016** [comment]
![Screenshot 2022-01-05 at 22 30 22](https://user-images.githubusercontent.com/16917203/148299351-3cbf3b49-df64-43c8-8221-6248f50e6ac6.png)
![Screenshot 2022-01-05 at 22 31 00](https://user-images.githubusercontent.com/16917203/148299358-71c5c1e0-a0c0-4813-ab7f-88cd80bfb2bf.png)

**Comment by fuatakgun** [comment]
This is a know issue: https://github.com/fuatakgun/eufy_security/issues/102

Until this is resolved, you can use webrtc integration which is more reliable and faster.

**Comment by atv2016** [comment]
I am using webrtc integration :-)

**Comment by fuatakgun** [comment]
Can you try to reload the integration? You seem to have too many errors there

**Comment by atv2016** [comment]
Just reloaded. I'm now getting these only:
![Screenshot 2022-01-05 at 22 39 48](https://user-images.githubusercontent.com/16917203/148299794-249ebcea-75ff-4fa0-bb80-0c871c05b462.png)

**Comment by fuatakgun** [comment]
Can you give more details for first and second errors?

**Comment by atv2016** [comment]
I take it back, i get all error messages again.
In order :

The first 2 seem to be related to the eufy alarm panel:
1. Task exception never retrieved:
![Screenshot 2022-01-05 at 22 44 08](https://user-images.githubusercontent.com/16917203/148300572-09c7746a-3200-4e8e-8255-60edf0aa5d92.png)

2. Error adding entities to ...
![Screenshot 2022-01-05 at 22 45 03](https://user-images.githubusercontent.com/16917203/148300643-d6599c66-0f0c-4576-9552-1b0f595af78f.png)

3. Error ffmpeg not running

![Screenshot 2022-01-05 at 22 48 55](https://user-images.githubusercontent.com/16917203/148300796-806d9508-f76e-444b-b6e1-c325f04b3421.png)

4. Doorbell video thread exception..

![Screenshot 2022-01-05 at 22 50 44](https://user-images.githubusercontent.com/16917203/148300964-72da3147-c859-40ac-8167-b965a6fce393.png)


5. FFmpeg already running!

![Screenshot 2022-01-05 at 22 51 46](https://user-images.githubusercontent.com/16917203/148301073-8612932a-4488-4533-b855-079f03a5e37d.png)

6. Stop ffmpeg exception:
![Screenshot 2022-01-05 at 22 52 55](https://user-images.githubusercontent.com/16917203/148301185-46702e65-a3f5-40ac-a280-0e3ef9dd22d3.png)

I'm sure most of them are related somehow and can all be condensed in one error. The installation went fine and i see no problems on the frontend, so not sure what these are about.

Thanks for helping out.

**Comment by atv2016** [comment]
Maybe i need to remove the ffmpeg: from my configuration.yaml ? I think i read somewhere it's not needed anymore. Maybe that's what's causing those errors?

**Comment by fuatakgun** [comment]
Ffmpeg is one issue and alarm control panel is another one.

You can disable alarm control panel so it will not generate errors until we fix it.

For ffmpeg, cam you confirm if you are able to run ffmpeg over ssh under hassos or ubuntu (not in docker)

**Comment by atv2016** [comment]
just trying to find out how to disable protected mode and log in to the container. Also just added ffmpeg_bin /usr/bin/ffmpeg to the configuration and restarted, see if that fixes anything.

**Comment by atv2016** [comment]
ok, so adding the ffmpeg_bin /usr/bin/ffmpeg parameters to ffmpeg: gave me video, works great. One down.
i see streaming - p2p in the screenshot, so that's good.

I do see that after watching live video stream when i go back to the autogenerated lovelace dashboard the regular eufy card doesn't display a screenshot as it normally would, just is grey. Not sure why.

I still get the doorbell stop ffmpeg exception and doorbell video thread exception errors though, might have something to do with that.

**Comment by fuatakgun** [comment]
please share your camera with me over eufy mobile app following instructions from README file, i will take a look at the issue.

**Comment by fuatakgun** [comment]
let's resolve this and create a separate one, this is getting longer and untrackable.
