### ISSUE TITLE
FFMPEG not loading

### ISSUE THREAD

**Issue by MattHoy** [fuatakgun/eufy_security#203]
**Describe the bug**
I can't play the doorbell stream or the sample rtsp stream to play, log keeps recording:
`eufy_security Doorbell - video ffmpeg error - ffmpeg is not running
`and
`eufy_security Doorbell video_thread exception: [Errno 32] Broken pipe- traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/camera.py", line 161, in write_bytes_to_ffmeg self.ffmpeg.process.stdin.write(frame_bytes) BrokenPipeError: [Errno 32] Broken pipe
`
**Hardware Information about Home Assistant
## System Health

version | core-2021.12.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v8
arch | aarch64

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
healthy | true
supported | true
board | rpi4-64
installed_addons | Terminal & SSH (8.10.0), Let's Encrypt (4.12.0), NGINX Home Assistant SSL proxy (3.1.0), ESPHome (1.15.3), Mosquitto broker (6.0.1), UniFi Network Application (1.1.3), Actron Que/Neo Air Conditioner (2021.12.2), Eufy Security Add-on (0.7.0), RTSP Simple Server Add-on (v0.17.6)

</details>

**Hardware Information about Cameras
- Hardwired Eufy 2k Doorbell Camera
- Live Streaming Protocol: P2P

**Additional context**
I have enabled 
`ffmpeg:
`
in my configuration.yaml and rebooted several times, but I am running the containerised RPI4 Home Assistant and cannot verify if it is actually available.

**Comment by atv2016** [comment]
I have exactly the same issues, I spoke to the author yesterday. See issue opened yesterday. And it’s spamming the logs, especially the task exception not retrieved.

**Comment by MattHoy** [comment]
It is not the same. You're running home assistant directly, I'm running the containerized version. You can just install ffpmeg and point to the bin for it, I cannot.

**Comment by atv2016** [comment]
I am talking the same issues. As they are exactly the same as yours I would say they are related, you don’t agree?

So you don’t run in a vm, you run it in docker yourself?

**Comment by MattHoy** [comment]
Just because we have the same error log, doesn't mean the cause or resolution is the same. I am running home assistant OS and supervisor, you are not. 

I understand you are trying to be helpful but please stick to your own unrelated issue thread as you don't appear to be very familiar with HA or nix.

**Comment by fuatakgun** [comment]
It might be or might mot be same issue but errors are right.

In background, when you start p2p streaming, incoming bytes are used to generate video stream using ffmpeg. And both errors say that either ffmpeg or rtsp server closes the connection and integration is not able to publish chunks anymore.

For both of you, please share your devices with me following readme file and i will take a look this evening (eu timezone)

**Comment by fuatakgun** [comment]
if you have portainer, you can ssh into home assistant docker or underlying OS to validate if ffmpeg is accessible.

**Comment by fuatakgun** [comment]
I am using supervised installation, must be very similar to your use case @MattHoy .

![image](https://user-images.githubusercontent.com/11085566/148530229-401ad7da-d9b4-42ec-967e-48698f9e5a7c.png)

**Comment by MattHoy** [comment]
I'm running hassio, I think the only way to access that is this:
https://developers.home-assistant.io/docs/operating-system/debugging/

**Comment by MattHoy** [comment]
```
Welcome to Home Assistant OS.

Use `ha` to access the Home Assistant CLI.
# docker exec -it homeassistant /bin/bash
bash-5.1# ffmpeg
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.1 (Alpine 10.3.1_git20210424) 20210424
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --enable-vulkan --enable-libsoxr --enable-libwebp --enable-libaom --disable-debug
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
bash-5.1#
```
Okay, ffmpeg looks good, not sure what the issue is then. Let me know if I can provide any further info

**Comment by fuatakgun** [comment]
@MattHoy , I need to access your camera to debug this issue, if you are interested, please follow README and drop me an email with serial number (too many shared devices :) )

**Comment by tcarroll177** [comment]
@fuatakgun Did this get fixed? Still trying to figure out how to ad dmy camera's, thank you!
