### ISSUE TITLE
Best way to cast camera stream to tv/media player?

### ISSUE THREAD

**Issue by atv2016** [fuatakgun/eufy_security#204]
What's the best way to do this ? Cast ? any example configuration ?

**Comment by atv2016** [comment]
If I try the camera.doorbell in combination with camera play_stream it says camera does not support play_stream function.

I can try the webrtc service call but that seems to need a rtsp link. And I use p2p.

would appreciate if you could test some of these out. I’d really love to cast the video doorbell to a mediaplayer.

**Comment by fuatakgun** [comment]
if you use RTSP Server add on and start streaming over P2P, it will generate a RTSP stream URL for you, go for webrtc.

**Comment by atv2016** [comment]
Cool. Where can I find this rtsp url?

**Comment by fuatakgun** [comment]
```
sensor.entrance_streaming_source_address
```

it will be available when streaming had started. my example: rtsp://192.168.178.34/live1

**Comment by atv2016** [comment]
Nice. 

So do I need to have setup a stream on the camera (eufy battery doesn’t support rtsp stream) or is one generated with the addon?

thanks again

**Comment by fuatakgun** [comment]
For p2p based cameras, rtsp stream will be generated using rtsp server add-on.

**Comment by atv2016** [comment]
thanks Fuat

So how do I know what is a p2p based camera? It “seems” I only get this p2p streaming message with the doorbell. With 2Cs or indoor eufy I don’t see that.

so for those that don’t I need to switch in the rtsp option in storage correct? And then that state variable will be updated?

**Comment by fuatakgun** [comment]
If your camera supports RTSP, which is enabled using mobile app, please do so and your streaming will much more reliable in home assistant.

Enabling rtsp doesn't mean storing them to anywhere, you can just enable it, that's it.

P2P based cameras mean, cameras which don't support RTSP. For these cameras, we are imitating mobile app as if you click on play button on your camera and device is sending video bytes to receiver and receiver glues everything together to generate video.

**Comment by atv2016** [comment]
> If your camera supports RTSP, which is enabled using mobile app, please do so and your streaming will much more reliable in home assistant.

Will do. Will i have to change anything in the setup of the integration or will it pick up things automatically using the sensor.streaming address ?

> P2P based cameras mean, cameras which don't support RTSP. For these cameras, we are imitating mobile app as if you click on play button on your camera and device is sending video bytes to receiver and receiver glues everything together to generate video.

That makes sense. I thought P2P was supposed to be better then RTSP but so far my results with P2P have been way inferior to the other cams.

Thanks again Fuat!

**Comment by fuatakgun** [comment]
you might need to restart add-on and reload the integration to catch up with reality.

P2P is not good as RTSP as i am generating video bytes inside home assistant, which is not meant to be :) more layers into system, more fragile it gets.

**Comment by atv2016** [comment]
Many thanks. Owe you a few beers.

Few more questions if you'd be so kind as to help me understand.

1. If i have a username and password enabled for the RTSP stream in the app, i assume that will be shown in the streaming source sensor as well?

2. I have RTSP enabled in the app, i have continuous enabled rather then events. There is also a continuous option outside of RTSP, i assume that's meant for local storage (as the RTSP menu already has that enabled) ?

3. As they are storing continuous, i would expect the sensors to have the streaming address for the 2C's, but it says false. When i click the camera on the eufy app the sensor still stays false (although the aforementioned RTSP url + password is in the data). Same for the doorbell camera (but that of course has no RTSP stream and uses p2p)


Summary
1. So i guess the 2c's and the doorbell will only populate the streaming source sensor if i click on them in homeassistant?
2. If that's the case how would webrtc dash cast work ? 

I am currently triggering on binary_sensor.doorbell_ringing_sensor and then use the sensor.doorbell_streaming_source_address in the webrtc.dash_cast service as the RTSP url, but will it be filled ? Does the ringing sensor somehow fill the RTSP sensor ?

**Comment by atv2016** [comment]
Now whenever i go to the conditional card i see this:

![Screenshot 2022-01-07 at 12 04 00](https://user-images.githubusercontent.com/16917203/148541947-0e8e27aa-46e7-41a6-88d5-b9082b0475aa.png)

P2P seems unstable. Might have to do with errors i got in my logs.

**Comment by fuatakgun** [comment]
for the coffee, please do over here for @bropat: https://ko-fi.com/bropat

As you own 2c cameras, why are you bothering with P2P, I would fully go with native RTSP from cameras.

**Comment by gerardsyd** [comment]
@atv2016 any luck with this in the end? I want to set this up. I can get it casting but get an error message saying android TV doesn't support this service.
