### ISSUE TITLE
localhost - says Host/Port is wrong

### ISSUE THREAD

**Issue by geidorei** [fuatakgun/eufy_security#205]
Hi folks - have moved over to this integration as one I was using now doesn't work.

All ok with installation etc until I setup Eufy Security on integrations; when I enter localhost into Host IP address I get a message saying Host/Port is wrong. I have logged into internet hub and tried the 3 'unknown' IP addresses but it didn't like them either.

Obviously I am doing something wrong??

Any help appreciated, thanks.

**Comment by fuatakgun** [comment]
please share logs from add-on

**Comment by geidorei** [comment]
Hi - log as below:

2022-01-07 10:33:47 ERROR (MainThread) [custom_components.eufy_security.config_flow] eufy_security Exception in login : 200, message='Invalid response status', url=URL('ws://localhost:3000') - traceback: Traceback (most recent call last):
  File "/config/custom_components/eufy_security/config_flow.py", line 98, in _test_credentials
    await eufy_ws.connect()
  File "/config/custom_components/eufy_security/websocket.py", line 41, in connect
    self.ws: aiohttp.ClientWebSocketResponse = (await self.session.ws_connect(self.base, autoclose=False, autoping=True, heartbeat=60))
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 792, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('ws://localhost:3000')

**Comment by fuatakgun** [comment]
These logs are from home assistant, i am interested of logs from eufy security ws add on under supervisor menu.

**Comment by geidorei** [comment]
Hi - deleted and started again, now got a lot further than before. Issue now with Eufy Home Assistant MQTT Bridge as below, and I've no idea....

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.24.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.12.8
 Home Assistant Supervisor: 2021.12.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:10:33] INFO: Exporting log level for nodejs: info
[15:10:34] INFO: Symlinking data dir
[15:10:34] INFO: Running 'eval' commands
[15:10:34] INFO: Generating config.yml from options.json
[15:10:34] INFO: Image build with version 0.2.24
[15:10:34] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Found device: Doorbell (T8210P0020302787 - type: T8210) {"timestamp":"2022-01-07T15:10:41.214Z"}
info: No credentials found -> register new... {"timestamp":"2022-01-07T15:10:46.502Z"}
(node:352) UnhandledPromiseRejectionWarning: Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR
    at PushRegisterService.<anonymous> (/app/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-07T15_10_47_654Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.

**Comment by fuatakgun** [comment]
You are mixing add-on, the one you are trying to install owned by a different repository, not by me.

I suggest you to ask help from the owner, i won't be able to help.

**Comment by geidorei** [comment]
I was following yours, oh no, have I installed the wrong one? I will do a check....

**Comment by fuatakgun** [comment]
Go to readme of this repository, you will find screenshots to follow

**Comment by geidorei** [comment]
Thanks for you help - will have a gander later and let u know.....
