### ISSUE TITLE
Error: Camera Send Status RTSP/1.0 404 stream not found 

### ISSUE THREAD

**Issue by tcarroll177** [fuatakgun/eufy_security#208]
Using EUFY indoor camera's I followed the steps and they were working to stream, now I keep getting an error on all 4 of them saying Error: Camera Send StatusRTSP/1.0 404 Stream Not Found - Restart Connection 

I have tried restarting the cameras, Home assisstant, deleting and re-adding but have had no luck. Any suggestions?

<img width="517" alt="Screen Shot 2022-01-11 at 2 12 17 PM" src="https://user-images.githubusercontent.com/97417397/149006882-561bf3d1-6e8c-4623-b3c7-b85debb9875b.png">
<img width="508" alt="Screen Shot 2022-01-11 at 2 12 27 PM" src="https://user-images.githubusercontent.com/97417397/149006884-0fba61a3-53a0-4966-b71c-ccf57ce84a78.png">

**Comment by fuatakgun** [comment]
You should have a sensor as sensor.entrance_streaming_source_address.

Please share it here and check if you can play it with vlc media player.

I am assuming you are calling start/stop livestream services :-)

**Comment by tcarroll177** [comment]
Sorry I am quite new at using home assistant so struggling to make this work. I copied what you had and changed entrance to backyard which is the name of my eufy cam this is what I received. I am trying to have my cameras stream on the dashboard. this is the error that I got now. Maybe I am a bit lost,  I have followed every other step and can see my eufy cam's in the devices and all the features that can be controlled 

<img width="555" alt="Screen Shot 2022-01-11 at 2 49 51 PM" src="https://user-images.githubusercontent.com/97417397/149011909-c11e677e-58cf-4ed3-abb8-15c8fa23ef30.png">

<img width="536" alt="Screen Shot 2022-01-11 at 2 48 49 PM" src="https://user-images.githubusercontent.com/97417397/149011904-05256062-e149-4fc0-ba13-ec9067cc630b.png">

**Comment by Rontruong** [comment]
I have the same problem. I think it started after the december release. I'm running on a NUC + docker + supervisor. 

I enabled live streaming via RTSP and was able to stream over VLC player. Looking at my logs, I don't see anything interesting. Only thing I see is this?

2022-01-11 12:51:42 WARNING (MainThread) [haffmpeg.core] FFmpeg is already running!

After messing around a bit. It looks like half my cameras work and the other half is running into 
Error: Camera Send Status RTSP/1.0 404 stream not found

I'll report back if I notice any new logs.

**Comment by fuatakgun** [comment]
apparently, integration is not very good at handling ffmpeg process yet. Let me merge these into here: https://github.com/fuatakgun/eufy_security/issues/203
