### ISSUE TITLE
Too many attributes lead to very large size of home_assistant_v2.db

### ISSUE THREAD

**Issue by eikowagenknecht** [fuatakgun/eufy_security#209]
**Describe the bug**
This integration has way too many informations on every sensor entity, for example:

camera:
![image](https://user-images.githubusercontent.com/1475672/149182399-2fa0a196-3029-4be1-bd71-e6887450ee59.png)
binary_sensor person detection:
![image](https://user-images.githubusercontent.com/1475672/149183298-720270f4-3091-45e4-ad3f-b066a867a42b.png)
etc.

In fact it seems to save all attributes on every sensor it creates.

Also there is much noise like static attributes in there like

```
  states:
    '0': Station
    '1': Camera
    '2': Sensor
    '3': Floodlight
    '4': Camera E
    '5': Doorbell
    '7': Battery Doorbell
    '8': Camera 2
    '9': Camera 2c
    '10': Motion Sensor
    '11': Keypad
    '14': Camera 2 Pro
    '15': Camera 2c Pro
    '16': Battery Doorbell 2
    '30': Indoor Camera
    '31': Indoor Camera PT
    '32': Solo Camera
    '33': Solo Camera Pro
    '34': Indoor Camera 1080
    '35': Indoor Camera PT 1080
    '37': Floodlight 8422
    '38': Floodlight 8423
    '39': Floodlight 2
    '44': Outdoor Camera 1080P No Light
    '45': Outdoor Camera 2k
    '46': Outdoor Camera 1080P
    '50': Lock Basic
    '51': Lock Advanced
    '52': Lock Basic No Finger
    '53': Lock Basic Advanced No Finger
    '60': Solo Camera Spotlight 1080p
    '61': Solo Camera Spotlight 2k
    '62': Solo Camera Spotlight Solar
```

While having this massive data dump may be convenient in some cases, it generates way too many state updates and everytime the whole record is saved, like this (showind only 2 of some thousand updates of only 1 sensor):
![image](https://user-images.githubusercontent.com/1475672/149182803-00e7f4b7-f1e2-42c3-8171-c22f74aea945.png)

This amounts to >100MB in my home_assistant_v2.db file.

**Expected behavior**
Only the needed information should be stored in the matching entries. All other attributes should be removed.

**Comment by fuatakgun** [comment]
this is a very valid callout, I would say, let's publish these attributes once per device. Today, there are many entities per one device and each entities are carrying these attributes. Would it make sense?

**Comment by eikowagenknecht** [comment]
Sounds reasonable. I also think that quite some stuff in there can be completely removed as it's static and could just be put on a documentation page. I'll have a closer look later and think about which attributes could be attached to which sensor.

**Comment by fuatakgun** [comment]
Many of attributes are defining the device and possible options. I am using these options to set the `select` entity's options, they are useful but definitely not needed to be duplicated in a lot of places :-)

**Comment by eikowagenknecht** [comment]
I started with looking at the Base units attributes. Here are my thoughts:

**Base entity**

>  name: Basis *******

Should be used as the default friendly name and not repeated in attribute

>  model: T8001
>  serialNumber: *******
>  hardwareVersion: P1
>  softwareVersion: 2.1.8.5

ok

>  lanIpAddress: 192.168.*******
>  macAddress: 8C:*******

What is this used for? I think the streaming addresses are in the "rtspStreamUrl" attributes of the cameras. Can probably be removed.

>  currentMode: 1

Seperate entity

>  guardMode: 1

Seperate entity

>  connected: true

Should be reflected as "unreachable" state of the base instead of an attribute

>  type: 0

No idea what this is. Can be removed? Seperate entity otherwise.

>  timeFormat: 0

No idea what this is. Can be removed? Seperate entity otherwise.

>  alarmVolume: 26

Seperate entity

>  alarmTone: 1

Seperate entity

> promptVolume: 10

Seperate entity

>  notificationSwitchModeSchedule: false
  notificationSwitchModeGeofence: false
  notificationSwitchModeApp: false
  notificationSwitchModeKeypad: false
  notificationStartAlarmDelay: false

No idea what this is. Can be removed? Seperate entities otherwise.

>  p2pLiveStreamingStatus: false

Seperate entity

>  rtspLiveStreamingStatus: false

Seperate entity

Is this helpful? I'd do that breakdown for one of my camera devices as well then.

**Comment by fuatakgun** [comment]
I don't think i would have time to work on this, separating attributes one by one, rather stick with having attributes once per device. You can raise a follow up PR if you are interested to work on this

**Comment by fuatakgun** [comment]
in essence, camera would be fine, but there are some users out there, using locks, motion/contact sensors, home base stations.
I am checking if the specific entity is main entity for device and publishing attributes accordingly.
a new version is released, please get it.

**Comment by eikowagenknecht** [comment]
LGTM, thank you! This will reduce a lot of database noise.

![image](https://user-images.githubusercontent.com/1475672/149533658-af278d5e-47ed-4e1c-979d-587f9648aa44.png)

**Comment by fuatakgun** [comment]
Thanks for bringing up

**Comment by FuzzyMistborn** [comment]
I really think there needs to be a better way to handle the attributes for cameras and alarm_panels (at least those are the ones I'm seeing being the worst offenders).  I have multiple cameras and now scrolling through my states page is an absolute chore.  I'd like to switch off using ioBroker for a simpler setup (and the nice integration) but honestly this is kinda a dealbreaker for me.
