### ISSUE TITLE
No motion/person detection on eufycam2 

### ISSUE THREAD

**Issue by Jastroger** [fuatakgun/eufy_security#21]
I got this running using the docker image of "https://github.com/bropat/eufy-security-ws/". The camera is showing the stream but I never got any motion detected. The eufy app is showing detected motions. There are 4 cams configured but none is sending motion alerts. See screenshots of home-assistant:

![image](https://user-images.githubusercontent.com/46408699/126865699-fb9fc729-c763-4391-97f5-bbc71a513428.png)
![image](https://user-images.githubusercontent.com/46408699/126865705-799d0d42-e889-4f67-9223-94debe88cb89.png)

Maybe i configured something wrong or this is an issue.

**Comment by Jastroger** [comment]
As always after testing for days.... I updated the repository and now it seems to work.

**Comment by fuatakgun** [comment]
Can you check if there are any logs or errors captured?

Also, you example camera has 3 percent battery and mine stops capturing events in this low level battery state. I assume rest of your cameras are not like this.
