### ISSUE TITLE
Support http2 calls

### ISSUE THREAD

**Issue by skank01** [fuatakgun/eufy_security#210]
Reminder to add https://www.python-httpx.org/ support

**Comment by fuatakgun** [comment]
my own cameras do not have this problem, so I won't be able to test this, update here if you are volunteer to share your camera.

**Comment by skank01** [comment]
Shared

**Comment by fuatakgun** [comment]
assuming camera named `tuin` is yours, you need to give admin permission.

**Comment by skank01** [comment]
Better now?
I couldnt shareo nly "tuin"?

**Comment by fuatakgun** [comment]
thanks, better now. but that URL does not make sense at all. Your latest captured picture is from 24th April 2021. I do not think that Eufy is storing these pictures more than couple of days in AWS. 

your picture URL: https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/thumb/2021/04/24/station/T8010XXX
my picture URL:  https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/thumb/2022/01/16/station/T8010XXX

@bropat , any idea why this might happen?

**Comment by fuatakgun** [comment]
moreover, I tried to access with http2 and it generated the same error.

```
import httpx
client = httpx.Client(http2=True)  
r = client.get('https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/thumb/2021/04/24/station/T8010XXX')
print(r)
```

it generated `<Response [404 Not Found]>`

**Comment by fuatakgun** [comment]
resolving this as this is not related to http2 support, you can remove sharing your cameras and share my findings with @bropat while creating an issue on his repository. I am not sure if this is related anything software.

**Comment by skank01** [comment]
Huh whats the problem then?
I told you i havent got a picture anymore and you guys said it was related to this.
So i dunno whats wrong

You and bropat pointed to this...

**Comment by fuatakgun** [comment]
I am really having hard time to follow you, you look like you are asking why we pointed you on this direction.

Do not forget this is an open source project and everyone here is working on volunteering based, so there is no place to hold responsible anyone. We think it might be reason and we were wrong.

I am not comfortable at all working with you with your overall attitude.

**Comment by bropat** [comment]
To clarify: The solution with http2 was related to the error `204 No Content` and not to `404 Not Found`.

In this case, the problem is with Eufy. We cannot pick up what is no longer there.

**Comment by fuatakgun** [comment]
By any chance, you (@bropat) might know why @skank01 is having very old pictureUrl?

**Comment by skank01** [comment]
Thx both you guys @bropat and @futakgun for keeping an eye on investigating this !
Yeah its like the pictureUrl isnt updating anymore or smth, maybe thats why i dont see it anymore?

**Comment by bropat** [comment]
@fuatakgun If I knew, I would have said it already. ;)

**Comment by bropat** [comment]
> Yeah its like the pictureUrl isnt updating anymore or smth, maybe thats why i dont see it anymore?

Exactly. It is now so old that it has already been deleted from the Eufy Cloud and so you get the `404 Not Found` error.
Only Eufy knows why it is no longer updated.

**Comment by fuatakgun** [comment]
@skank01 in your mobile app, do you get notifications including picture?

**Comment by skank01** [comment]
> @skank01 in your mobile app, do you get notifications including picture?

Good one, it seems not.
Strange
Movementdetection is on though (all motions)

I just tested the movement stuff, but it doesnt detect my movement anymore...
i then looked to my modus, which says im home, maybe thats the reason
