### ISSUE TITLE
Service for device.quick_response

### ISSUE THREAD

**Issue by Bafnek** [fuatakgun/eufy_security#211]
Hi there,

As requested I put this here as an issue.

I would like to have the option to send quick responses (the custom ones in particular) through Home Assistant, based on certain events (like doorbell press). For example I thought it would be fun to trigger some custom recorded (novelty) quick responses on a doorbell press on certain occasions.

With your help I figured out it is possible to send out quick responses on the Eufy doorbell through Home Assistant with the eufy_security.send_message service. I added it to a script. (Below for reference to anyone who is interested)

alias: Doorbell Response 3
sequence:
  - service: eufy_security.send_message
    data:
      message: |-
        {
          "messageId": "message_id_do_not_add_value_here", 
          "command": "device.quick_response",
          "serialNumber": "your_serial_no",
          "voiceId": 3,
          "value": true
        }
mode: single
I have recorded three custom quick reponses, but they do not have the voiceID values 4, 5 and 6. So this is not a solution for the purpose I have for it. It would be fun to have this included in your custom integration!

**Comment by fuatakgun** [comment]
Can you dump your video doorbell state attributes? I am curious if we can find the list of IDs?

**Comment by Bafnek** [comment]
You mean the information below?

inherited:
  type: DEVICE_TYPE.BATTERY_DOORBELL
  category: DOORBELL
  state:
    name: Doorbell
    model: T8210
    serialNumber: T8210XXXXX
    hardwareVersion: T8210
    softwareVersion: 2.2.3.3
    stationSerialNumber: T8010XXXX
    enabled: true
    state: 1
    battery: 0
    batteryTemperature: 9
    lastChargingDays: 1
    lastChargingTotalEvents: 3397
    lastChargingRecordedEvents: 1877
    lastChargingFalseEvents: 1520
    batteryUsageLastWeek: 0
    motionDetected: false
    personDetected: false
    personName: ''
    ringing: false
    autoNightvision: false
    motionDetection: true
    watermark: 1
    wifiRSSI: -60
    pictureUrl: >-
      https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/thumb/2022/01/14/station/
    type: 7
    motionDetectionType: 2
    speakerVolume: 100
    ringtoneVolume: 0
    audioRecording: true
    powerWorkingMode: 2
    recordingEndClipMotionStops: true
    recordingClipLength: 120
    recordingRetriggerInterval: 2
    videoStreamingQuality: 5
    videoWDR: true
    chimeIndoor: false
    chimeHomebase: false
    chimeHomebaseRingtoneVolume: 26
    chimeHomebaseRingtoneType: 1
    notificationType: 2
    notificationRing: 1
    notificationMotion: 0
    motionDetectionSensitivity: 5
    statusLed: false
    chargingStatus: 1
    wifiSignalLevel: 4
    p2pLiveStreamingStatus: false
    rtspLiveStreamingStatus: false
    wifiRssi: -60
  properties:
    name:
      value: Doorbell
      timestamp: 1641656160000
    model:
      value: T8210
      timestamp: 1641656160000
    serialNumber:
      value: T8210XXXXX
      timestamp: 1641656160000
    type:
      value: 7
      timestamp: 1641656160000
    hardwareVersion:
      value: T8210
      timestamp: 1641656160000
    softwareVersion:
      value: 2.2.3.3
      timestamp: 1629120480000
    stationSerialNumber:
      value: T8010XXXXX
      timestamp: 1641656160000
    lastChargingDays:
      value: 0
      timestamp: 1642002819000
    lastChargingFalseEvents:
      value: 43
      timestamp: 1642005916000
    lastChargingRecordedEvents:
      value: 84
      timestamp: 1642005916000
    lastChargingTotalEvents:
      value: 127
      timestamp: 1642005916000
    batteryUsageLastWeek:
      value: 0
      timestamp: 1641656160000
    pictureUrl:
      value: >-
        https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/thumb/
      timestamp: 1642005894000
    recordingClipLength:
      value: 120
      timestamp: 1639497155000
    recordingRetriggerInterval:
      value: 2
      timestamp: 0
    recordingEndClipMotionStops:
      value: true
      timestamp: 0
    notificationType:
      value: 2
      timestamp: 1633593392000
    notificationRing:
      value: 1
      timestamp: 1633593392000
    notificationMotion:
      value: 0
      timestamp: 1633593392000
    enabled:
      value: true
      timestamp: 1633592963000
    chimeIndoor:
      value: false
      timestamp: 1633592971000
    ringtoneVolume:
      value: 0
      timestamp: 1639927212000
    videoWdr:
      value: true
      timestamp: 1633592971000
    statusLed:
      value: false
      timestamp: 1638800976000
    battery:
      value: 0
      timestamp: 1642006105006
    speakerVolume:
      value: 100
      timestamp: 1633592971000
    videoStreamingQuality:
      value: 5
      timestamp: 1635950916000
    wifiRssi:
      value: -60
      timestamp: 1641571787000
    wifiSignalLevel:
      value: 4
      timestamp: 1640271669000
    motionDetectionType:
      value: 2
      timestamp: 1637696452000
    chimeHomebase:
      value: false
      timestamp: 1638629038000
    motionDetection:
      value: true
      timestamp: 1633592971000
    motionDetectionSensitivity:
      value: 5
      timestamp: 1633636196000
    chimeHomebaseRingtoneVolume:
      value: 26
      timestamp: 1633592971000
    chargingStatus:
      value: 1
      timestamp: 1642006105006
    chimeHomebaseRingtoneType:
      value: 1
      timestamp: 1638629033000
    watermark:
      value: 1
      timestamp: 1633593083000
    state:
      value: 1
      timestamp: 1640934325000
    audioRecording:
      value: true
      timestamp: 1633592971000
    autoNightvision:
      value: false
      timestamp: 1633593077000
    powerWorkingMode:
      value: 2
      timestamp: 1633593091000
    batteryTemperature:
      value: 9
      timestamp: 1641571787000
    motionDetected:
      value: false
      timestamp: 0
    personDetected:
      value: false
      timestamp: 0
    personName:
      value: ''
      timestamp: 0
    ringing:
      value: false
      timestamp: 1642005245482
  properties_metadata:
    name:
      key: device_name
      name: name
      label: Name
      readable: true
      writeable: false
      type: string
    model:
      key: device_model
      name: model
      label: Model
      readable: true
      writeable: false
      type: string
    serialNumber:
      key: device_sn
      name: serialNumber
      label: Serial number
      readable: true
      writeable: false
      type: string
    type:
      key: device_type
      name: type
      label: Type
      readable: true
      writeable: false
      type: number
      states:
        '0': Station
        '1': Camera
        '2': Sensor
        '3': Floodlight
        '4': Camera E
        '5': Doorbell
        '7': Battery Doorbell
        '8': Camera 2
        '9': Camera 2c
        '10': Motion Sensor
        '11': Keypad
        '14': Camera 2 Pro
        '15': Camera 2c Pro
        '16': Battery Doorbell 2
        '30': Indoor Camera
        '31': Indoor Camera PT
        '32': Solo Camera
        '33': Solo Camera Pro
        '34': Indoor Camera 1080
        '35': Indoor Camera PT 1080
        '37': Floodlight 8422
        '38': Floodlight 8423
        '39': Floodlight 2
        '44': Outdoor Camera 1080P No Light
        '45': Outdoor Camera 2k
        '46': Outdoor Camera 1080P
        '50': Lock Basic
        '51': Lock Advanced
        '52': Lock Basic No Finger
        '53': Lock Basic Advanced No Finger
        '60': Solo Camera Spotlight 1080p
        '61': Solo Camera Spotlight 2k
        '62': Solo Camera Spotlight Solar
    hardwareVersion:
      key: main_hw_version
      name: hardwareVersion
      label: Hardware version
      readable: true
      writeable: false
      type: string
    softwareVersion:
      key: main_sw_version
      name: softwareVersion
      label: Software version
      readable: true
      writeable: false
      type: string
    stationSerialNumber:
      key: station_sn
      name: stationSerialNumber
      label: Station serial number
      readable: true
      writeable: false
      type: string
    battery:
      key: 1101
      name: battery
      label: Battery percentage
      readable: true
      writeable: false
      type: number
      unit: '%'
      min: 0
      max: 100
    batteryTemperature:
      key: 1138
      name: batteryTemperature
      label: Battery Temperature
      readable: true
      writeable: false
      type: number
      unit: °C
    wifiRssi:
      key: 1142
      name: wifiRssi
      label: Wifi RSSI
      readable: true
      writeable: false
      type: number
      unit: dBm
    wifiSignalLevel:
      key: custom_wifiSignalLevel
      name: wifiSignalLevel
      label: Wifi Signal Level
      readable: true
      writeable: false
      type: number
      min: 0
      max: 4
      states:
        '0': No signal
        '1': Weak
        '2': Normal
        '3': Strong
        '4': Full
    enabled:
      key: 99904
      name: enabled
      label: Camera enabled
      readable: true
      writeable: true
      type: boolean
      commandId: 1035
    autoNightvision:
      key: 1013
      name: autoNightvision
      label: Auto Nightvision
      readable: true
      writeable: true
      type: boolean
    statusLed:
      key: 1716
      name: statusLed
      label: Status LED
      readable: true
      writeable: true
      type: boolean
      commandId: 6014
    motionDetection:
      key: 1011
      name: motionDetection
      label: Motion Detection
      readable: true
      writeable: true
      type: boolean
    watermark:
      key: 1214
      name: watermark
      label: Watermark
      readable: true
      writeable: true
      type: number
      states:
        '1': 'Off'
        '2': 'On'
    state:
      key: 1131
      name: state
      label: State
      readable: true
      writeable: false
      type: number
      states:
        '0': Offline
        '1': Online
        '2': Manually disabled
        '3': Offline low battery
        '4': Remove and readd
        '5': Reset and readd
    lastChargingDays:
      key: charging_days
      name: lastChargingDays
      label: Days since last charging
      readable: true
      writeable: false
      type: number
      default: 0
    lastChargingFalseEvents:
      key: charging_missing
      name: lastChargingFalseEvents
      label: False Events since last charging
      readable: true
      writeable: false
      type: number
      default: 0
    lastChargingRecordedEvents:
      key: charging_reserve
      name: lastChargingRecordedEvents
      label: Total Events since last charging
      readable: true
      writeable: false
      type: number
      default: 0
    lastChargingTotalEvents:
      key: charing_total
      name: lastChargingTotalEvents
      label: Total Events since last charging
      readable: true
      writeable: false
      type: number
      default: 0
    batteryUsageLastWeek:
      key: battery_usage_last_week
      name: batteryUsageLastWeek
      label: False Events since last charging
      readable: true
      writeable: false
      type: number
      unit: '%'
      min: 0
      max: 100
      default: 0
    motionDetected:
      key: custom_motionDetected
      name: motionDetected
      label: Motion detected
      readable: true
      writeable: false
      type: boolean
    personDetected:
      key: custom_personDetected
      name: personDetected
      label: Person detected
      readable: true
      writeable: false
      type: boolean
    ringing:
      key: custom_ringing
      name: ringing
      label: Ringing
      readable: true
      writeable: false
      type: boolean
    pictureUrl:
      key: cover_path
      name: pictureUrl
      label: Last Camera Picture URL
      readable: true
      writeable: false
      type: string
    speakerVolume:
      key: 1230
      name: speakerVolume
      label: Speaker Volume
      readable: true
      writeable: true
      type: number
      min: 0
      max: 100
    ringtoneVolume:
      key: 1708
      name: ringtoneVolume
      label: Ringtone Volume
      readable: true
      writeable: true
      type: number
      min: 0
      max: 100
    audioRecording:
      key: 1288
      name: audioRecording
      label: Audio Recording
      readable: true
      writeable: true
      type: boolean
    motionDetectionType:
      key: 1252
      name: motionDetectionType
      label: Motion Detection Type
      readable: true
      writeable: true
      type: number
      states:
        '0': Humans only
        '2': All motions
    motionDetectionSensitivity:
      key: 1276
      name: motionDetectionSensitivity
      label: Motion Detection Sensitivity
      readable: true
      writeable: true
      type: number
      min: 1
      max: 5
    powerWorkingMode:
      key: 1246
      name: powerWorkingMode
      label: Power Working Mode
      readable: true
      writeable: true
      type: number
      states:
        '0': Balance Surveillance
        '1': Optimal Surveillance
        '2': Custom Recording
        '3': Optimal Battery Life
    chargingStatus:
      key: 2111
      name: chargingStatus
      label: Charging Status
      readable: true
      writeable: false
      type: number
      states:
        '1': Charging
        '2': Unplugged
        '3': Plugged
    recordingClipLength:
      key: 1249
      name: recordingClipLength
      label: Recording Clip Length
      readable: true
      writeable: true
      type: number
      min: 5
      max: 120
      default: 60
      unit: sec
    recordingRetriggerInterval:
      key: 1250
      name: recordingRetriggerInterval
      label: Recording Clip Length
      readable: true
      writeable: true
      type: number
      unit: sec
      min: 2
      max: 60
      default: 2
    recordingEndClipMotionStops:
      key: 1251
      name: recordingEndClipMotionStops
      label: Recording end clip early if motion stops
      readable: true
      writeable: true
      type: boolean
      default: true
    videoStreamingQuality:
      key: 1705
      name: videoStreamingQuality
      label: Video Streaming Quality
      readable: true
      writeable: true
      type: number
      states:
        '0': Auto / Low Encoding
        '1': Low / Low Encoding
        '2': Medium / Low Encoding
        '3': High / Low Encoding
        '5': Auto / High Encoding
        '6': Low / High Encoding
        '7': Medium / High Encoding
        '8': High / High Encoding
    videoWdr:
      key: 1704
      name: videoWdr
      label: WDR
      readable: true
      writeable: true
      type: boolean
    chimeIndoor:
      key: 1703
      name: chimeIndoor
      label: Indoor Chime Enabled
      readable: true
      writeable: true
      type: boolean
    chimeHomebase:
      key: 1702
      name: chimeHomebase
      label: Homebase Chime Enabled
      readable: true
      writeable: true
      type: boolean
    chimeHomebaseRingtoneVolume:
      key: 1717
      name: chimeHomebaseRingtoneVolume
      label: Homebase Chime Ringtone Volume
      readable: true
      writeable: true
      type: number
      min: 1
      max: 26
    chimeHomebaseRingtoneType:
      key: 1718
      name: chimeHomebaseRingtoneType
      label: Homebase Chime Ringtone Type
      readable: true
      writeable: true
      type: number
      states:
        '0': Default
        '1': Silent
        '2': Beacon
        '3': Chord
        '4': Christmas
        '5': Circuit
        '6': Clock
        '7': Ding
        '8': Hillside
        '9': Presto
    notificationType:
      key: 1710
      name: notificationType
      label: Notification Type
      readable: true
      writeable: true
      type: number
      states:
        '1': Most Efficient
        '2': Include Thumbnail
        '3': Full Effect
      commandId: 6020
    notificationRing:
      key: 1710
      name: notificationRing
      label: Notification Ring detected
      readable: true
      writeable: true
      type: boolean
    notificationMotion:
      key: 1710
      name: notificationMotion
      label: Notification Motion detected
      readable: true
      writeable: true
      type: boolean
custom:
  is_streaming: false
  stream_source_type: ''
  stream_source_address: ''
  codec: h264
  is_rtsp_streaming: false
  is_p2p_streaming: false
entity_picture: >-
  /api/camera_proxy/camera.doorbell?token=XXXX
friendly_name: Doorbell
supported_features: 3

**Comment by fuatakgun** [comment]
Thanks, it is not here, i need to send a command first to find list of recorded voices and let user to choice from the list.

I believe your is not urgent for you as you are already fine with current solution, right?

**Comment by Bafnek** [comment]
It's not urgent in any way. Would just be a fun addition for some occasions. Thanks for looking into it!

**Comment by paulharman** [comment]
Can anyone help me to get this working with node red please?  I'd love to be able to do custom responses, but the standard ones will do for now

**Comment by satyambaba** [comment]
> Thanks, it is not here, i need to send a command first to find list of recorded voices and let user to choice from the list.
> 
> I believe your is not urgent for you as you are already fine with current solution, right?

Hi, I'll also be interested in using custom responses. Currently, I can successfully use pre recorded voice responses (voiceId: 1, 2 and 3), however I am unable to use custom responses (they are not 4, 5, 6). In case you get some free time, can you please look in to this? Thanks a lot in advance.

**Comment by paulharman** [comment]
@satyambaba don't suppose you've done it with nodered? I can't work out how to do it

**Comment by satyambaba** [comment]
> @satyambaba don't suppose you've done it with nodered? I can't work out how to do it

No, I have not done it using nodered. Can you please point me in the right direction?

**Comment by Bafnek** [comment]
Not sure if I understand you correctly, but this is how it is currently working for the standard quick responses. For the custom quick responses there is still no solution afaik.

I created a script for each quick response:

```
alias: Doorbell Quick Response 1
sequence:
  - service: eufy_security.send_message
    data:
      message: |-
        {
          "messageId": "message_id_do_not_add_value_here", 
          "command": "device.quick_response",
          "serialNumber": "YOURSN", #Fill in your T8210 no.
          "voiceId": 1 #Should be either 1, 2 or 3
          "value": true
        }
mode: single
```
I guess you could do the rest in NodeRed. Just let it run the script as an action based on the triggers you have in mind (most likely doorbell press?).

**Comment by satyambaba** [comment]
> Not sure if I understand you correctly, but this is how it is currently working for the standard quick responses. For the custom quick responses there is still no solution afaik.
> 
> I created a script for each quick response:
> 
> ```
> alias: Doorbell Quick Response 1
> sequence:
>   - service: eufy_security.send_message
>     data:
>       message: |-
>         {
>           "messageId": "message_id_do_not_add_value_here", 
>           "command": "device.quick_response",
>           "serialNumber": "YOURSN", #Fill in your T8210 no.
>           "voiceId": 1 #Should be either 1, 2 or 3
>           "value": true
>         }
> mode: single
> ```
> 
> I guess you could do the rest in NodeRed. Just let it run the script as an action based on the triggers you have in mind (most likely doorbell press?).

I am using the same script for standard responses. I thought there is a workaround for custom quick responses in Nodered, that's why I asked. Anyways, it is clear now, thanks for your help!

FYI, I tried each voiceID, from 4 to 106, hoping that the custom  quick response would work. However, It didn't work, which led me to believe that voiceID for a custom quick response might actually be a randomly generated number. In API docs, following code is mentioned to get doorbell quick response voices, however I am not aware about how to execute this to get a response (my guess is that it would be probably a json response).

```yaml
interface {
  messageId: string;
  command: "device.get_voices";
  serialNumber: string;
}
```

**Comment by Bafnek** [comment]
Yes, well about checking all those IDs; I’ve noticed that at a certain
number of tries the eufy_security.send_message stops working in its
entirety (so neither for the ids 1,2&3)and you either need to wait for a
while for it to be available again. It seems to get overloaded or something.

**Comment by Bafnek** [comment]
Wow, great work. I can confirm this works!

**Comment by amosyuen** [comment]
So, I think probably the desired changes to this integration is to expose the voice IDs more easily. We should have doorbells  send the `device.get_voices` command and store the results in the `properties_metadata`.

It would also be great to add a service for playing the quick response that just takes a voice ID to make this functionality more discoverable.

@fuatakgun What do you think? Also do you have time to do this? I can try making the changes and a pull request if you're busy.

**Comment by satyambaba** [comment]
> Looks like the IDs are randomly generated for each new voice file. I got this working. You can find the voice files by sending the `device.get_voices` command as a message and look at the response. Detailed steps below:
> 
> 1. Uncomment on_message debug statement in `eufy_security/coordinator.py`:
> 
> ```python
>     async def on_message(self, message):
>         payload = message.json()
>         message_type: str = payload["type"]
>         _LOGGER.debug(f"{DOMAIN} - on_message - {payload}") # <-- uncomment this
> ```
> 
> 2. Turn on debug logging in configuration
> 
> ```yaml
> logger:
>   logs:
>     custom_components.eufy_security: debug
> ```
> 
> 3. Restart Home Assistant
> 4. Send `device.get_voices` command
> 
> ```yaml
> - service: eufy_security.send_message
>   data:
>     message: |-
>       {
>         "messageId": "",
>         "command": "device.get_voices",
>         "serialNumber": "<serial_no>"
>       }
> ```
> 
> 5. Find voice ID in response in logs. Each entry will have a `desc` attribute which is the name of the quick response. Find the corresponding `voice_id` attribute for the quick repsonse you want to use.
> 6. Send the voice ID in the `device.quick_response` command:
> 
> ```yaml
> - service: eufy_security.send_message
>   data:
>     message: |-
>       {
>         "messageId": "",
>         "command": "device.quick_response",
>         "serialNumber": "<serial_no>",
>         "voiceId": <voice_id>,
>         "value": true
>       }
> ```

@amosyuen, thanks a lot for this. For me, this wasn't a straight forward process as I had hoped. I had only one custom quick response added and I wanted to get the voice ID for that. First time I sent device.get_voices command, it gave me a single voice id 419 with a different name (desc) that wasn't event saved in my account.

Then I deleted my only custom quick response and re-added a new one. This time when I sent device.get_voices command, I was able to get the correct voice id with correct name (desc).

I then decided to add two more custom quick commands (the limit is 3). And I sent device.get_voices command again. I again got voice id 419. Since then, each time I try, I always get only one voice id, 419. I even took a break for a day thinking that frequent commands are causing false results as eufy server is blocking them. However, when I tried again today, I received the same voice id 419.

Then I thought of doing a little experiment, I deleted all three custom quick responses and added a new one, assuming that it works only when there is only one custom quick response saved. However, this time my assumption proved to be wrong and I again got 419 as voice id.

I don't know what other factors are causing this behavior. I also tried while doorbell camera was streaming, but to no avail. Also tried while a custom quick response was in action, no luck with this as well.

Are you consistently able to get right voice ids?

@Bafnek, can you please check if you are able to get correct voice ids consistently?

Thanks a lot for your help in advance!

**Comment by satyambaba** [comment]
> For me it consistently returns all the voice IDs including the predefined ones (1,2,3) as well as the 3 extra ones. I deleted and added a voice ID and it works fine for me.
> 
> Curious what doorbell version you have? I have the 1080p wired version.

I have the battery operated version of Eufy 1080p doorbell camera.

**Comment by satyambaba** [comment]
> ```yaml
> service: eufy_security.send_message
>   data:
>     message: |-
>       {
>         "messageId": "",
>         "command": "device.get_voices",
>         "serialNumber": "<serial_no>"
>       }
> ```

I guess I figured it out. Whenever the Eufy app was running on the phone, sending device.get_voices command gave the wrong results. If Eufy app is not running, it gives correct and consistent results. I tested it repeatedly and it worked every time. Maybe some day, if this becomes a feature of this integration, we can use this info as instruction/precaution.

**Comment by amosyuen** [comment]
> > ```yaml
> > service: eufy_security.send_message
> >   data:
> >     message: |-
> >       {
> >         "messageId": "",
> >         "command": "device.get_voices",
> >         "serialNumber": "<serial_no>"
> >       }
> > ```
> 
> I guess I figured it out. Whenever the Eufy app was running on the phone, sending device.get_voices command gave the wrong results. If Eufy app is not running, it gives correct and consistent results. I tested it repeatedly and it worked every time. Maybe some day, if this becomes a feature of this integration, we can use this info as instruction/precaution.

Are you using the same account on the phone as in HA? If you are you should use a different account for HA. See https://github.com/fuatakgun/eufy_security#3-troubleshooting

**Comment by satyambaba** [comment]
> > > ```yaml
> > > service: eufy_security.send_message
> > >   data:
> > >     message: |-
> > >       {
> > >         "messageId": "",
> > >         "command": "device.get_voices",
> > >         "serialNumber": "<serial_no>"
> > >       }
> > > ```
> > 
> > 
> > I guess I figured it out. Whenever the Eufy app was running on the phone, sending device.get_voices command gave the wrong results. If Eufy app is not running, it gives correct and consistent results. I tested it repeatedly and it worked every time. Maybe some day, if this becomes a feature of this integration, we can use this info as instruction/precaution.
> 
> Are you using the same account on the phone as in HA? If you are, you should use a different account for HA. See https://github.com/fuatakgun/eufy_security#3-troubleshooting

No, I am using two different accounts - one main account on phone and another is a secondary account with which cameras are shared.

**Comment by amosyuen** [comment]
I tried having the eufy app open when sending the command, but mine still returns all the voice IDs. Maybe it has something to do with the doorbell being wired vs wireless also.

**Comment by amosyuen** [comment]
> ```yaml
> 
>       {
>         "messageId": "",
>         "command": "device.quick_response",
>         "serialNumber": "<serial_no>",
>         "voiceId": <voice_id>,
>         "value": true
>       }
> ```

Sounds like you are setting the voiceId as a string instead of a number?

Make sure you are doing

```
      {
        "messageId": "",
        "command": "device.quick_response",
        "serialNumber": "<serial_no>",
        "voiceId": 1,
        "value": true
      }
```
      
not

```
      {
        "messageId": "",
        "command": "device.quick_response",
        "serialNumber": "<serial_no>",
        "voiceId": "1",
        "value": true
      }
```

**Comment by jilleischen** [comment]
Hello @amosyuen,
Thank you for your quick response.
The "voiceId" is indeed a number without quotes.
The "value" is set to true, but I sill do not get standard (1,2,3) or custom (xxxxx) quick responses to play through my wireless Eufy.
