### ISSUE TITLE
motion / person detection mismatch

### ISSUE THREAD

**Issue by eikowagenknecht** [fuatakgun/eufy_security#213]
Just a quick hint: https://github.com/fuatakgun/eufy_security/blob/e433205193a59431454f14be21a3a759c413b932/custom_components/eufy_security/const.py#L451

This should be person* instead of motion*

**Comment by eikowagenknecht** [comment]
Also: Why is the motion sensor in "sensors" and the person sensor in "diagnostics" while the detected person name is also in "sensors"?

![image](https://user-images.githubusercontent.com/1475672/149572087-3d2aa1a5-8382-4afd-b65e-cc2aeb5b782c.png)

**Comment by fuatakgun** [comment]
I didn't pay a lot attention, it was a contribution from one of the users, you can fix the categories if you are interested.

**Comment by fuatakgun** [comment]
Btw, thanks for pointing out
