### ISSUE TITLE
Eufy Security addon cannot be found in HACS

### ISSUE THREAD

**Issue by tmchow** [fuatakgun/eufy_security#215]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
On Step 6 of the instructions, I cannot find the "Eufy Security" addon in HACS:

**To Reproduce**
1. Go to HACS
2. Tap "Explore + Download repositories"
3. Type "eufy"
4. notice no results

**Expected behavior**
Step 6 of install instructions indicate i should be able to find this?

**Screenshots**
![image](https://user-images.githubusercontent.com/517103/149635936-4be06c3a-e611-438c-b0c9-c45f4423c358.png)

**Comment by fuatakgun** [comment]
Please double read the instructions.

Add-ons are meant to be used inside supervisor.

Integrations are meant to be used inside HACS.

**Comment by ciryon** [comment]
I think @tmchow  meant "repository could not be found in HACS". I had the same issue, but just waited a couple of minutes and then it appeared in the list.

**Comment by fuatakgun** [comment]
HACS is refreshing all the repositories in a scheduled manner and because of github's limiting, it can take time to get the whole list. It is how HACS is working but you can always install it manually but too much hassle :-)

**Comment by tmchow** [comment]
I made a mistake in my original issue report, @ciryon was right in what I meant. It's now showing, I wasn't waiting long enough.

**Comment by DenisBY** [comment]
> Please double read the instructions.
> 
> Add-ons are meant to be used inside supervisor.
> 
> Integrations are meant to be used inside HACS.

What if I don't use supervisor? Is there a way to install add-on somehow manually?
