### ISSUE TITLE
eufy_security does not generate unique IDs.

### ISSUE THREAD

**Issue by julet85** [fuatakgun/eufy_security#218]
I'm getting the following error when toggling audio recording settings on my Eufy wired doorbell

`Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:592
Integration: Switch (documentation, issues)
First occurred: 7:22:58 PM (2 occurrences)
Last logged: 7:22:58 PM

Platform eufy_security does not generate unique IDs. ID eufy_security_T8200N0019350A33_audio_recording_switch already exists - ignoring switch.doorbell_audio_recording
Platform eufy_security does not generate unique IDs. ID eufy_security_T8400P202118051E_audio_recording_switch already exists - ignoring switch.garage_audio_recording`

I have 2 cameras (doorbell + indoor camera). Any ideas how to resolve this? I have tried reinstalling the integration.

**Comment by fuatakgun** [comment]
This week be fixed in new versions but not an blocker issue, everything should work fine

**Comment by fuatakgun** [comment]
fixed in v2.2.2
