### ISSUE TITLE
Eufy Motion Sensor - Binary sensor states

### ISSUE THREAD

**Issue by boctok** [fuatakgun/eufy_security#22]
One thing I noticed while trying to set up an automation using the binary switch motion detector entity, checking the logs, it goes from "false" (no motion detected) to "unavailable". I don't see any records of "true" or any motion detected, even though it shows up in the Eufy app.

_Originally posted by @boctok in https://github.com/fuatakgun/eufy_security/issues/15#issuecomment-885754190_

**Comment by fuatakgun** [comment]
can you confirm if changes are states happening in similar times? it can be an issue of mapping of eufy states into HA states.
let's assume it is False now as there is no motion, is it switching into unavailable instead of True when there is motion?
of vice versa?

**Comment by boctok** [comment]
I will check it now and get back to you shortly.

**Comment by boctok** [comment]
Maybe not. It didn't change from 'false'. I guess that would mean that it simply isn't getting any state from the sensor.

Here is the info from the sensor state in developer tools:

`name: Front Motion Sensor
model: T8910
serialNumber: T8910P0020150C3D
hardwareVersion: 0.0.1
softwareVersion: 2.0.1.1
stationSerialNumber: T8010P13203100C9
batteryLow: false
motionDetected: false
motionSensorPIREvent: 1627302197000
motionDetection: false
friendly_name: Front Motion Sensor Motion Sensor
device_class: motion`

compared with the state from the doorbell motion sensor:

`name: Doorbell
model: T8210
serialNumber: T8210P00204134E3
hardwareVersion: T8210
softwareVersion: 2.2.3.3
stationSerialNumber: T8010P13203100C9
enabled: true
state: 1
battery: 73
batteryTemperature: 38
lastChargingDays: 11
lastChargingTotalEvents: 923
lastChargingRecordedEvents: 512
lastChargingFalseEvents: 411
batteryUsageLastWeek: 17
motionDetected: false
personDetected: false
personName: ''
ringing: false
autoNightvision: true
ledStatus: true
motionDetection: true
watermark: 2
wifiRSSI: -45
pictureUrl: https://security-app.eufylife.com/v1/s/g/ayK1Szi0s
friendly_name: Doorbell Motion Sensor
device_class: motion`

**Comment by fuatakgun** [comment]
please let your motion sensor with my eufy account so I can debug.
I also need you around to initiate motion events.
I am located in Luxembourg, +2 timezone. I have next one hour or tomorrow 20:00 to 21:00.

**Comment by boctok** [comment]
How do I share it?

**Comment by fuatakgun** [comment]
apparently, only cameras are shareable between accounts, I will try to improve this blindly, hopefully we can make it

**Comment by boctok** [comment]
Would the states from the MQTT entities be of any help? I did see that those are "on" or "off", but that may just be within that integration. Those do trigger, by the way, but I know nothing about how to set up MQTT automations etc.

**Comment by fuatakgun** [comment]
Please enable excessive logging following last section here: https://github.com/fuatakgun/eufy_security#troubleshooting
later, share your logs. Try to generate some motion events on your sensor and share your logs later on, we can make it work

**Comment by pethans** [comment]
I was able to trigger the binary sensor for motion on my 2k indoor camera using the settings below. The sensor stays “true” for 10 seconds and then takes 3 minutes to “re-arm” ignoring any motion during that window. My cameras are also enrolled in HomeKit which triggers the motion sensor with no re-arming delay, which is how I was able to verify this. 
1. In eufy app for camera settings (gear), enable motion detection and notifications for motion on each desired camera
2. In eufy app for security (guard mode), select a mode that has notifications checked. 

I hope there is a way to do this without notifications, because when cameras are “disarmed” there is no option to enable notifications, which differs from the HomeKit behavior wherein motion sensing is always on regardless of guard mode. Also perhaps the three-minute delay is a self-imposed window to prevent notifications overflow, or hopefully there is another way to eliminate or shorten this.

**Comment by fuatakgun** [comment]
I am using like this;
- notifications are enabled on main and guest account
- use guest account in home assistant
- disable notifications in Android permission settings on my phone

**Comment by Fogest** [comment]
Hey just chiming in here to mention my motion sensor doesn't work either and can help with any information you require as well. 

I am trying to have the motion camera turn on lights in a room when it detects motion but there seems to be no way to do this with a Eufy Motion sensor currently. I can't even get it to show up in Google Assistant (and it's officially supported), only the Homebase shows up there.

**Comment by fuatakgun** [comment]
I need you to enable excessive logging for the integration and trigger some events from motion sensor and share your logs from home assistant regarding. This will be first step.

**Comment by Fogest** [comment]
That log corresponds to a single motion sensing trigger. I have no idea why it has multiple "false" trigger events and one "true", but that is one trigger that generated all those.

**Comment by boctok** [comment]
I think the true values may indicate that "motionDetect**ion**" is enabled, which appears to be different from "motionDetect**ed**", which is always showing false.

**Comment by Fogest** [comment]
Ah yes I do see there is a difference there. Unclear though why it would be indicating that is a "property change" as the property was not changed by me. Also weird how it keeps throwing motion detection "false" despite it sending a notification to the contrary. 

Looking at my other logs of motion triggers it looks like it is the same pattern every time. `motionDetected = false`, and `motionDetection = true`

So for some reason it seems like the `motionDetection` flag is the one indicating whether it is detecting movement. Because in some cases `motionDetection` is showing as `false`. Whereas `motionDetected` never seems to change from `false`.

**Comment by fuatakgun** [comment]
thanks for investigation, so individual motion sensor should use motionDetection rather than motionDetected, now it is clear, but I believe this is a mistake. actions;
- create an issue on eufy-security-client to fix the event name
- come up with a solution for existing situation

**Comment by Fogest** [comment]
Yes that seems correct and it does seem to point to a naming error coming from the eufy-security-client

**Comment by boctok** [comment]
I don't think it is a naming error. The phone app allows for motion detection to be turned off or on. There is also a timeout period after a detection event in which it will not register another motion event. I believe that it is simply indicating if motion detection is enabled, then indicating that the camera or sensor has entered the period in which detection is disabled, and subsequently, when it was re-enabled.

**Comment by fuatakgun** [comment]
@bropat , it would be nice to get your opinion on this. when motion sensor receives an motion event, `motionDetection` is toggling between True and False but `motionDetected` is always False.

This looks contradicting with camera but you know better internal dynamics.

**Comment by Fogest** [comment]
@boctok In my case I have 0 second delay set for the motion triggering cooldown so this may explain why the log messages are all happening at the same time then.

**Comment by boctok** [comment]
Another interesting thing I noticed while looking through the logs is that sometimes, the URL for the snapshot of the last activity is https://security-app.eufylife.com/imageName and at other times, it is https://zhixin-security-pr.s3.us-west-2.amazonaws.com/ etc.

**Comment by fuatakgun** [comment]
> I don't think it is a naming error. The phone app allows for motion detection to be turned off or on. There is also a timeout period after a detection event in which it will not register another motion event. I believe that it is simply indicating if motion detection is enabled, then indicating that the camera or sensor has entered the period in which detection is disabled, and subsequently, when it was re-enabled.

I would rely on enabled/disabled attribute rather than `motionDetection` but @bropat would answer better.

**Comment by fuatakgun** [comment]
please get latest version of codebase and retry and share your results. resolve if possible.

**Comment by boctok** [comment]
Looks like the "motionDetected" reported a 'true'...
`2021-08-10 23:49:01 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - T8114P02202745B6 motionDetected True - {'name': 'temp', 'model': 'T8114', 'serialNumber': 'T8114XXXXXXXXXXX', 'hardwareVersion': 'eufy2_v', 'softwareVersion': '2.7.4', 'stationSerialNumber': 'T8010XXXXXXXXXXX', 'enabled': True, 'state': 1, 'battery': 87, 'batteryTemperature': 32, 'lastChargingDays': 0, 'lastChargingTotalEvents': 2, 'lastChargingRecordedEvents': 2, 'lastChargingFalseEvents': 0, 'batteryUsageLastWeek': 0, **'motionDetected': True,** 'personDetected': False, 'personName': '', 'antitheftDetection': False, 'autoNightvision': True, 'ledStatus': True, 'motionDetection': True, 'rtspStream': True, 'watermark': 2, 'wifiRSSI': -33, 'pictureUrl': 'https://security-app.eufylife.com/image', 'motionDetectionType': 2, 'motionDetectionSensivity': 20, 'microphone': True, 'speaker': True, 'speakerVolume': 92, 'audioRecording': True, 'powerSource': 0, 'powerWorkingMode': 0, 'notificationType': 3, 'type_raw': 9, 'type': 'DEVICE_TYPE.CAMERA2', 'category': 'CAMERA'}
2021-08-10 23:49:01 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'motion detected', 'serialNumber': 'T8114XXXXXXXXXXX', 'state': True}}`

**Comment by boctok** [comment]
I checked the state within developer tools, since I have this one camera sitting on my desk waiting to be mounted and sure enough, I can trigger the state between off and on by moving my hand in front of the camera.

**Comment by bropat** [comment]
> @bropat , it would be nice to get your opinion on this. when motion sensor receives an motion event, `motionDetection` is toggling between True and False but `motionDetected` is always False.
> 
> This looks contradicting with camera but you know better internal dynamics.

@fuatakgun That is a typing error on my part. It will be fixed in the next release.
I only implemented the motion sensor by reverse engineering the code without really being able to test it. 

If someone has such a device and could share it with me for a short time, I could check everything and implement missing features.

**Comment by fuatakgun** [comment]
I asked this earlier but user was not able to find sharing option and i thought it is not shareable

**Comment by boctok** [comment]
It isn't shareable individually, like the cameras. In order to share it, I'd have to share everything and that's not a good option.
![tempFileForShare_20210811-073412](https://user-images.githubusercontent.com/5306739/129022697-bdbe60d3-e2a0-41a1-9c7b-b527bcc290a4.jpg)

**Comment by boctok** [comment]
Two entries are created in the log when I trigger the motion sensor. One concerning motionDetection and the other motionDetected:
`2021-08-11 08:18:36 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - T8910P0020150C3D motionDetection False - {'name': 'Front Motion Sensor', 'model': 'T8910', 'serialNumber': 'T8910P0020150C3D', 'hardwareVersion': '0.0.1', 'softwareVersion': '2.0.1.1', 'stationSerialNumber': 'T8010P13203100C9', 'batteryLow': False, 'motionDetected': False, 'motionDetection': False, 'motionSensorPIREvent': 1628680956000, 'type_raw': 10, 'type': 'DEVICE_TYPE.MOTION_SENSOR', 'category': 'MOTION_SENSOR'}
2021-08-11 08:18:36 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'property changed', 'serialNumber': 'T8910P0020150C3D', 'name': 'motionDetection', 'value': False, 'timestamp': 1628684316714}}`

`2021-08-11 08:18:36 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - T8910P0020150C3D motionDetected False - {'name': 'Front Motion Sensor', 'model': 'T8910', 'serialNumber': 'T8910P0020150C3D', 'hardwareVersion': '0.0.1', 'softwareVersion': '2.0.1.1', 'stationSerialNumber': 'T8010P13203100C9', 'batteryLow': False, 'motionDetected': False, 'motionDetection': False, 'motionSensorPIREvent': 1628680956000, 'type_raw': 10, 'type': 'DEVICE_TYPE.MOTION_SENSOR', 'category': 'MOTION_SENSOR'}
2021-08-11 08:18:36 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'motion detected', 'serialNumber': 'T8910P0020150C3D', 'state': False}}`

**Comment by bropat** [comment]
Hi,

this will be fixed in eufy-security-client version 1.1.0 (to be released today).

**Comment by bropat** [comment]
> It isn't shareable individually, like the cameras. In order to share it, I'd have to share everything and that's not a good option.
> ![tempFileForShare_20210811-073412](https://user-images.githubusercontent.com/5306739/129022697-bdbe60d3-e2a0-41a1-9c7b-b527bcc290a4.jpg)
> If there is anything I could do to pull info from it and post it, I would be happy to.

Yeah you must release the station where the unit is registered.

**Comment by fuatakgun** [comment]
> @boctok In my case I have 0 second delay set for the motion triggering cooldown so this may explain why the log messages are all happening at the same time then.

Can you test latest codebase and share your findings?

**Comment by boctok** [comment]
As far as I know, I have the latest. I don't see any notification that there is a new one.

**Comment by fuatakgun** [comment]
so, you should have an entity named `Front Motion Sensor Motion Sensor`, right? Do you see any activity when you trigger motion event?

**Comment by boctok** [comment]
`2021-08-12 07:37:45 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - T8910XXXXXXXXXXX motionDetection False - {'name': 'Front Motion Sensor', 'model': 'T8910', 'serialNumber': 'T8910XXXXXXXXXXX', 'hardwareVersion': '0.0.1', 'softwareVersion': '2.0.1.1', 'stationSerialNumber': 'T8010XXXXXXXXXXX', 'batteryLow': False, 'motionDetected': False, 'motionDetection': False, 'motionSensorPIREvent': 1628767232000, 'type_raw': 10, 'type': 'DEVICE_TYPE.MOTION_SENSOR', 'category': 'MOTION_SENSOR'}
2021-08-12 07:37:45 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'property changed', 'serialNumber': 'T8910XXXXXXXXXXX', 'name': 'motionDetection', 'value': False, 'timestamp': 1628768265024}}`

`2021-08-12 07:37:45 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - T8910XXXXXXXXXXX motionDetected False - {'name': 'Front Motion Sensor', 'model': 'T8910', 'serialNumber': 'T8910XXXXXXXXXXX', 'hardwareVersion': '0.0.1', 'softwareVersion': '2.0.1.1', 'stationSerialNumber': 'T8010XXXXXXXXXXX', 'batteryLow': False, 'motionDetected': False, 'motionDetection': False, 'motionSensorPIREvent': 1628767232000, 'type_raw': 10, 'type': 'DEVICE_TYPE.MOTION_SENSOR', 'category': 'MOTION_SENSOR'}
2021-08-12 07:37:45 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'motion detected', 'serialNumber': 'T8910XXXXXXXXXXX', 'state': False}}`

**Comment by fuatakgun** [comment]
but I do not see any event here which arrives as True. This is contradicting with this: https://github.com/fuatakgun/eufy_security/issues/22#issuecomment-896192283

**Comment by boctok** [comment]
That was from one of the cameras, which had also, up to that point, not given a result of true.

**Comment by boctok** [comment]
From the camera Model# T8114

`2021-08-12 08:18:23 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - T8114XXXXXXXXXXX motionDetected False - {'name': 'temp', 'model': 'T8114', 'serialNumber': 'T8114XXXXXXXXXXX', 'hardwareVersion': 'eufy2_v', 'softwareVersion': '2.7.4', 'stationSerialNumber': 'T8010XXXXXXXXXXX', 'enabled': True, 'state': 1, 'battery': 100, 'batteryTemperature': 22, 'lastChargingDays': 1, 'lastChargingTotalEvents': 6, 'lastChargingRecordedEvents': 6, 'lastChargingFalseEvents': 0, 'batteryUsageLastWeek': 0, 'motionDetected': False, 'personDetected': False, 'personName': '', 'antitheftDetection': False, 'autoNightvision': True, 'ledStatus': True, 'motionDetection': True, 'rtspStream': True, 'watermark': 2, 'wifiRSSI': -29, 'pictureUrl': 'https://security-app.eufylife.com/v1/s/g/lLhAIKurt', 'motionDetectionType': 2, 'motionDetectionSensivity': 20, 'microphone': True, 'speaker': True, 'speakerVolume': 92, 'audioRecording': True, 'powerSource': 0, 'powerWorkingMode': 0, 'notificationType': 3, 'type_raw': 9, 'type': 'DEVICE_TYPE.CAMERA2', 'category': 'CAMERA'}
2021-08-12 08:18:23 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'motion detected', 'serialNumber': 'T8114XXXXXXXXXXX', 'state': False}}`

**Comment by boctok** [comment]
My apologies. I thought the issue was with motion detection in general, because until a few days ago, none of my cameras were providing any motion detection events either. Again, I apologize.

**Comment by fuatakgun** [comment]
no worries, do you still have these issues regarding to non-functional motion sensors for cameras? Person & motion detection is well working for me.

**Comment by boctok** [comment]
They kind of worked before, but until a few days ago, I couldn't use them as triggers for automations. I will stick to the motion detector from now on.

**Comment by boctok** [comment]
The motion sensor will initially produce this:
`2021-08-15 20:10:06 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - T8910XXXXXXXXXXX motionDetection True - {'name': 'Front Motion Sensor', 'model': 'T8910', 'serialNumber': 'T8910XXXXXXXXXXX', 'hardwareVersion': '0.0.1', 'softwareVersion': '2.0.1.1', 'stationSerialNumber': 'T8010XXXXXXXXXXX', 'batteryLow': False, 'motionDetected': False, 'type_raw': 10, 'type': 'DEVICE_TYPE.MOTION_SENSOR', 'category': 'MOTION_SENSOR', 'motionSensorPIREvent': 1629071335000, 'motionDetection': True}
2021-08-15 20:10:06 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'property changed', 'serialNumber': 'T8910XXXXXXXXXXX', 'name': 'motionDetection', 'value': True, 'timestamp': 1629072605657}}`

so, it is registering something, but when I check states, I'm wasn't sure which value it was using, because the state was always false.

`name: Front Motion Sensor
model: T8910
serialNumber: T8910XXXXXXXXXXX
hardwareVersion: 0.0.1
softwareVersion: 2.0.1.1
stationSerialNumber: T8010XXXXXXXXXXX
batteryLow: false
motionDetected: false
type_raw: 10
type: DEVICE_TYPE.MOTION_SENSOR
category: MOTION_SENSOR
motionSensorPIREvent: 1629071335000
motionDetection: false
friendly_name: Front Motion Sensor Motion Sensor
device_class: motion`

Was it using motionDetection or motionDetected?

So, I went and pulled it down and brought it to my desk so that I could refresh the state while I was causing a motion event. It is clearly changing the **motionDetection** attribute, but the state is still false, so maybe it is using **motionDetected** as the state attribute, but that isn't the one being updated. See image:
![Motion detector](https://user-images.githubusercontent.com/5306739/129497961-70e71592-3a0a-4039-bf4b-ade4967595b0.PNG)

**Comment by bropat** [comment]
@boctok 

This was a BUG that was fixed in version 1.1.0 of the driver (eufy-security-client).
The correct attribute is in any case `motionDetected`.

In any case, you should use eufy-security-ws version 0.4.1.

**Comment by boctok** [comment]
As far as I can see, eufy-security-ws version 0.4.1 isn't available in HA yet. I'll keep an eye out for it.

**Comment by fuatakgun** [comment]
That is on me, i need to test it throughly and probably include newly added
versions, please follow it closely but do not expect very soon, on vacation
:-)

**Comment by boctok** [comment]
Enjoy yourself!

**Comment by Fogest** [comment]
So if I wanted to use this motion sensor to do something like turning on a light in a room and keeping that light on while it detects motion say every 5 minutes, I'd have to have notifications on for this? Is there any workaround or way around having to have the devices notifications on? This works fine for cameras for me as they don't detect motion nearly as often as I will want this motion sensor detecting it.

**Comment by boctok** [comment]
That's the way it seems to work for mine. I tried with "React to motion" unchecked and the stater never changed. I tried it with "React to motion" checked, but "Push notification" unchecked and the state never changed. It will only change the state if "React to motion" and "Push notification" are both checked. I'm not sure if @fuatakgun can work some sort of magic and make it only update the state on HA, but I kind of doubt it, because it's a push notification. HA and your phone get the same notification.

**Comment by fuatakgun** [comment]
Maybe you can have one account to hold all cameras and motion sensors to use with HA and have a separate one for your mobile app without motion sensor. 

I have just built the bridge between eufy security ws and HA, magic comes from @bropat

**Comment by bropat** [comment]
Yesterday I bought a motion sensor. As soon as it arrives I will take a closer look at it to understand if I can do some magic. ;)

**Comment by sjikkervisje** [comment]
I just installed this a couple days ago, I have the 2k Battery Doorbell from Eufy and motion sensor is not showing correctly. It does not produce any updates in HA regarding motion detection.
![image](https://user-images.githubusercontent.com/1422692/131214792-f132c809-f6d8-42f8-9e8e-4e0c1afe09a3.png)

**Comment by sjikkervisje** [comment]
I found out that with the wireless doorbell the motion sensor entities do work however, it depends on how you setup your Eufy device in the App. If set to all motion, only the motion sensor works and the person detector sensor doesn't. If you set it to Persons only then the normal motion sensor doesn't work. I was hoping that both would work regardless of the setting in the app you so you could have a combination of motion or motion and person simultaniously.

![image](https://user-images.githubusercontent.com/1422692/131311482-bac67ccd-dce8-433f-bdd4-46874eff3c6e.png)

**Comment by fuatakgun** [comment]
FYI: this thread is about `physical motion sensor` by Eufy, not about motion and person sensing features of cameras/doorbells.

**Comment by fuatakgun** [comment]
@sjikkervisje  , thanks for your findings, can we continue over here: https://github.com/fuatakgun/eufy_security/issues/49

I believe they are directly related

**Comment by fuatakgun** [comment]
> That's the way it seems to work for mine. I tried with "React to motion" unchecked and the state never changed. I tried it with "React to motion" checked, but "Push notification" unchecked and the state never changed. It will only change the state if "React to motion" and "Push notification" are both checked. I'm not sure if @fuatakgun can work some sort of magic and make it only update the state on HA, but I kind of doubt it, because it's a push notification. HA and your phone get the same notification.

back to here, we know that our integration relies on push notifications for events, if we are not able to receive any push notifications, there is no way around this. @bropat , do you foresee a solution here other than adding the motion sensor into integration specific eufy account?

**Comment by bropat** [comment]
After I received the motion sensor, I checked how it works and unfortunately I have to inform you that the motion notification can only be integrated via the push notifications. There is no other interface that is openly accessible, not even via the P2P interface to the station.
I would not buy this sensor (have returned it).

**Comment by fuatakgun** [comment]
Thanks for update, i will close the issue, @boctok , please go with a separate account if you are worried about number of push notifications.
