### ISSUE TITLE
Host/Port is wrong

### ISSUE THREAD

**Issue by jgeorge1983** [fuatakgun/eufy_security#222]
Hey,

I am running HA via docker, installed via HACS.  When I try to install the integration using my docker IP and port 3000 I get the error:
_Host/Port is wrong_

I ran this command in docker switching my email and password in:
docker run -it -e USERNAME=email -e PASSWORD=password -p 3000:3000 bropat/eufy-security-ws:X.Y.Z
and got the following error:
_Status: Downloaded newer image for bropat/eufy-security-ws:0.7.0
docker: Error response from daemon: failed to create endpoint thirsty_montalcini on network bridge: failed to add the host (veth6d3b1b0) <=> sandbox (veth0c7d468) pair interfaces: operation not supported.
ERRO[0025] error waiting for container: context canceled_ 

Any thoughts on the last bit?

**Comment by dpomnean** [comment]
What hardware, OS are you using?

**Comment by jgeorge1983** [comment]
SOrry, I am using a Raspberry Pi 4, runnin gRaspberry 10 Buster

**Comment by dpomnean** [comment]
When was the last time you rebooted your raspberry pi? It's strange because I'm running a pi 4 without this issue. Have. you tried uninstalling, reinstalling docker?

**Comment by dpomnean** [comment]
Can you confirm the image is there? Yeah it would stop any containers running but you should be able to get them running easily again with your docker compose or docker run commands

```
docker images
```

**Comment by jgeorge1983** [comment]
yes, i can see the image is there

bropat/eufy-security-ws                             0.7.0          68971a8a14b3   3 weeks ago     127MB

I didnt download it 3 weeks ago, presume thats the publish date?

**Comment by dpomnean** [comment]
Yeah thats when the image was created on Bropat's side. Can you gather some more info?

```
docker --version
uname -a
```

**Comment by jgeorge1983** [comment]
Docker version 20.10.12, build e91ed57
Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

**Comment by dpomnean** [comment]
Seems like an issue with some outdated libraries possibly on your pi. Someone had similar issue on his repo.

https://github.com/bropat/eufy-security-ws/issues/47

**Comment by jgeorge1983** [comment]
Cool, thanks, i'll take a look!
