### ISSUE TITLE
ERROR Create push credentials Error: 

### ISSUE THREAD

**Issue by BillyBobMills** [fuatakgun/eufy_security#223]
Hi

I have had this integration working on a Pi4 for the last few weeks with no issues. This was upgraded from a working Pi3 installation.

I have a battery doorbell, a keypad and some sensors on my eufy account.

Today I have removed some door and motion sensors from my Eufy account using the app.

On looking at the integration in HA to try to remove these devices it was in an error state. I first tried to restart the add on but this now shows errors in the log (below).

I have tried the following to get this working and the same error continues.

Uninstall Add on and Integration. Delete the eufy security folder from the custom_components folder.
Reinstall Add on and Integration. 
Restart homebase.
Create a new Eufy admin account. Shared cameras to this account and verified the account works by logging into the eufy app with it.
The log shows it is getting a new token when i switch users in the config. 
Tried a different port in the config.
Checked country code (GB) and password in add on. If i change the code or password i get the code is not valid or an authentication error in the add on log.
Disabling other add ons that are running. 

This is what i am seeing in the add on log? Any pointers? Thanks.

2022-01-18 14:25:38.055  INFO  Eufy Security server listening on port 3000 
2022-01-18 14:25:39.657  INFO  Connected to station T8010PXXXXXXXXXXX on host 192.X.X.X and port 14598 
2022-01-18 14:25:45.869  ERROR registerFid - Error: 
 RequestError  connect ECONNREFUSED 0.0.0.0:443
details:
{
  code: 'ECONNREFUSED',
  timings: undefined
}
error stack:
• index.js:1183 _makeRequest
    node_modules/got/dist/source/core/index.js:1183:19
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• index.js:334 <anonymous>
    node_modules/got/dist/source/core/index.js:334:17
2022-01-18 14:25:45.887  ERROR registerFid - Status return code not 200 
{
  status: undefined,
  statusText: undefined,
  data: undefined
}
2022-01-18 14:25:45.892  ERROR registerFid - Generic Error: 
 Error  FID registration failed with error: undefined
error stack:
• service.ts:87 registerFid
    node_modules/eufy-security-client/src/push/service.ts:87:23
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

....................................................................................

    node_modules/eufy-security-client/src/push/service.ts:576:17
2022-01-18 14:27:19.942  INFO  Push notification connection closed 
2022-01-18 14:27:19.944  ERROR Push notifications are disabled, because the registration failed! 
2022-01-18 14:27:19.945  INFO  Retry to register/login for push notification in 40 seconds...

**Comment by BillyBobMills** [comment]
Sorted.
Pi-Hole is to blame!

**Comment by fuatakgun** [comment]
Perfect, i like this kind of difficult but solved issues :-)

**Comment by BillyBobMills** [comment]
It took me far too long to figure this one out :-(

I'm yet to see if it happens again on a HA restart and I need to add a uri to the pi hole whitelist.

I just disabled pi hole whilst starting the add on to test it and have since enabled pi hole again.

Everything is back to working as it was before :-)

**Comment by DarthDestroyer** [comment]
Can confirm the issue!

With disabled pihole it just works fine, but i cant find a souce for that!

Its not in the logs if and which url gets blocked... any infos about that?
