### ISSUE TITLE
Battery level and ringing sensor stopped working when upgrading from 1.1.0 to 2.2.x

### ISSUE THREAD

**Issue by trullock** [fuatakgun/eufy_security#227]
**Describe the bug**
Since upgrading from 1.1.0 to 2.2.0 and then 2.2.2 the battery reports 0% and the ringing sensor never changes from False

**To Reproduce**
1) View battery sensor entity, always 0%
2) Press doorbell, ringing sensor never changes from False

**Expected behavior**
Battery should report value
Doorbell ringing should go True when pressed

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Eufy 2k Battery

**Additional context**
All was working fine in 1.1.0

I updated to 2.2.0 when I saw the new version and from then it was broken. I've completely removed the configuration and HACS integration and readded it, but its still the same.
The doorbell does ring, the homebase works, my Eufy app sends me a push etc.

Let me know what additional debug I can provide and I will

Thanks

**Comment by fuatakgun** [comment]
I need error logs if any, if not, debug logs please, at least for ringing sensor.

For battery, there is an open issue here: https://github.com/bropat/eufy-security-ws/issues/57

**Comment by trullock** [comment]
Sorry, can you humour me on how to provide these?

Also, it is possible for me to downgrade to 1.1.0 to see if it starts working agian? its not available in the release list inside HACS, only 2+ is

Re new tickets, will move converstaion there 👍

**Comment by apeeters** [comment]
Linking issue #324 here.
