### ISSUE TITLE
Integration stops reacting to service calls

### ISSUE THREAD

**Issue by RolandGoud** [fuatakgun/eufy_security#228]
The integration was working fine... could start/stop camera with service calls. Now a day later it stopped responding to my service calls. For some reason i got it working again, but after an hour of getting cards up and making automations the enitities stopped responding to any service calls. Now my camera's are stuck on streaming - rtsp (eufy cam 2) and streaming - p2p (wireless doorbell, since this doen not have rtsp)

**To Reproduce**
1. Neither camera.turn_off or Eufy Security: Stop Live Stream over RTSP respond to any of my camera's

Im running an RPI4 (with 8gb i think)

Restarting the homebase does reset the rtsp camera to idle, but the p2p streaming is still frozen on streaming. And the entities do not respond to the server calls.

**Comment by fuatakgun** [comment]
Can you try to restart add on and then reload the integration? Or can you check if there is any error logs?

**Comment by RolandGoud** [comment]
restarting the add-on and integration seem to help.

i got no errors in the log (not for the add-on nore the integration), just the standard in the overall log:

WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by fuatakgun** [comment]
Lets keep this open

**Comment by gr8er1mark** [comment]
I think I may have a similar issue. I have the Eufy 1080p wireless doorbell with HA on RPI 4 8GB.

All of the entities seem to stop updating after a couple of hours. If I check the log for the add on it still appears to be connected with no errors. When the entities stop updating the only way I seem to be able to get everything working again is to restart the add on and the reload the integration. Then within a few hours the entities seem to stop updating again and I habe to repeat the process.

**Comment by fuatakgun** [comment]
please track over here: https://github.com/bropat/eufy-security-ws/issues/73

**Comment by ronaldt80** [comment]
I just closed the issue. Assuming you have similar errors in the add-on the solution seems to be a rebuild/reinstall of the add-on/container.
