### ISSUE TITLE
Info: Eufy Alarm Modes

### ISSUE THREAD

**Issue by bearkiter** [fuatakgun/eufy_security#229]
I'm having trouble getting any alarm modes other than "Home Arm", "Away Arm" and "Disarmed" working.
I'm only new to HA but have used many different commercial automation systems in the past.

EG: I have a mode called "Night" on the Eufy app (Named to match the "Night Mode" I found in the button objects) however I can't see how this can be mapped/used in the alarm dashboard object.

Any guidance would be appreciated.

**Comment by fuatakgun** [comment]
in lovelace, you have to select extra modes manually so they will be visible.

![image](https://user-images.githubusercontent.com/11085566/150850339-c671979d-9515-4943-a4bd-d414c746bf7c.png)

**Comment by bearkiter** [comment]
They've been set to show on lovelace, they will not set, it seems the modes don't match what Eufy reports.

If I select any additional modes to display on the card they don't work


________________________________
