### ISSUE TITLE
Lock shows up but events aren't populating

### ISSUE THREAD

**Issue by bzzlghtyr** [fuatakgun/eufy_security#23]
I'm not sure if it's just a matter of it not being supported as I'm very new to all of this, but the Eufy Lock (T8520) is discovered as a device with 2 entities in Home Assistant: a camera in Idle status and a battery.

Is this device currently supposed to be supported or is it just automatically adding as a camera due to being connected to my Eufy account? I wanted to build automations based on locked status.

**Comment by fuatakgun** [comment]
As of not, it is not supported, I will try to add support blindly, Can you share device state from Developer Tools -> States -> Pick the lock device and share the attributes of device

**Comment by fuatakgun** [comment]
can you get latest codebase and double check if locks are still showed up?

**Comment by fuatakgun** [comment]
Resolving due to inactivity
