### ISSUE TITLE
Integrations and platforms could not be set up

### ISSUE THREAD

**Issue by K3str3l** [fuatakgun/eufy_security#230]
**Describe the bug**
When starting HA I see the following notification:
`The following integrations and platforms could not be set up:

eufy_security.binary_sensor
eufy_security.sensor
eufy_security.switch
eufy_security.select
Please check your config and logs.`

In the logs i see the following:
`Logger: homeassistant.setup
Source: setup.py:316
First occurred: 18:19:02 (4 occurrences)
Last logged: 18:19:02

Unable to prepare setup for platform eufy_security.binary_sensor: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform eufy_security.sensor: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform eufy_security.switch: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
Unable to prepare setup for platform eufy_security.select: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).`

**To Reproduce**
Start HA

**Expected behavior**
4 sensors to be loaded

**Hardware Information about Home Assistant
Home Assistant Core
Version core-2021.10.3

Operating System
Version 6.4

**Hardware Information about Cameras
- Camera Model: T8210
- Live Streaming Protocol: RTSP

**Additional context**
When installing eufy security I cannot use port 3000 as i get a message to say it is already in use - I have selected port 3001, and installation is allowed to proceed. 
I have also uninstalled the intergration; the addon;  rtsp addon and webrtc integration, deleted the folder config\custom_components\eufy_security, and reinstalled - but with the same result

**Comment by fuatakgun** [comment]
Your home assistant version is too old, please update to 2012.12.xx at least.

**Comment by K3str3l** [comment]
thanks! That has resolved the issue - great intergration too!
