### ISSUE TITLE
Doorbell battery sensor not showing correct value on T8210

### ISSUE THREAD

**Issue by TuomasPakkanen** [fuatakgun/eufy_security#234]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Battery level sensor is showing 0, even though there are plenty of battery left. Battery powered doorbell model T8210. Seems to sometimes show the correct battery level but most of the time it is just zero.

![image](https://user-images.githubusercontent.com/7880089/150677213-602fda8a-54f7-4d94-8587-4f26781cd4a5.png)

**To Reproduce**
Setup is done via instructions, nothing special in that really.

**Expected behavior**
Correct battery percentage shown in the battery level sensor.

**Hardware Information about Home Assistant
HAOS 7.1, HA CORE 2021.12.9, Raspberry PI4 4gb

**Hardware Information about Cameras
- Camera Model T8210
- Live Streaming Protocol: P2P

**Comment by TuomasPakkanen** [comment]
Quick comment: battery shows OK in the Eufy app.

**Comment by kauthmbt** [comment]
@TuomasPakkanen 
The logfiles for this problem was headed over to Bropat as he maintains eufy-security-ws.
You could follow the latest progress over here: https://github.com/bropat/eufy-security-ws/issues/57
