### ISSUE TITLE
Enabled/Disabled service does not work on the T8410 model

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#238]
Hi @fuatakgun 
the service enabled / disabled command no longer seems to work for the T8410 webcam that I was using correctly until some previous release. Has something changed?

     - service: eufy_security.enable
       target:
         entity_id:
           - camera.xxx

Even the on / off switch fails to send the command and returns to the previous position.

On the T8400, however, it works correctly

Thanks

**Comment by SmartM-ui** [comment]
By removing the integration and reinstalling it, the problem appears to be solved

**Comment by fuatakgun** [comment]
I don't think it was related to integration, it could be related to addon, next time this will happen (i hope never) please double check add-on logs.
