### ISSUE TITLE
Calling service "device.stop_livestream" results in error message

### ISSUE THREAD

**Issue by cRemE-fReSh** [fuatakgun/eufy_security#24]
Hi,
thanks for that great solution. The integration of live streams is a major benefit of this integration! Well done.

One Remark. 
Calling service "stop_livestream" (via P2P) results in an error message in the log file:
![grafik](https://user-images.githubusercontent.com/42785404/127059117-8fbe64f5-d430-41e5-a82b-5448bb0cc442.png)
The same happens calling the "start" service.

Nevertheless, start/stop_rtsp works great.

It seems to be a missmatch between the latest versions of the addon and the integration.
Integration version: c1ebecd
Addon version: the latest :-)

Kind regards
Fabian

**Comment by nenadmilano** [comment]
Same here but also with start_livestream, also latest add-on and latest integration from HACS:

![063ECC59-758C-4B14-B4EE-DF0C48C4A8E2](https://user-images.githubusercontent.com/32328649/127065876-ce647c82-529d-4664-b80d-d5a1a31023bc.jpeg)

**Comment by fuatakgun** [comment]
This is a strange error.
Integration and add-on are independent between each other, so it is ok to have different versions.
I actually just created a wrapper file around add-on, core part of it coming directly from here: https://github.com/bropat/eufy-security-ws/
I have been updating integration every day for last couple of days.

**Comment by fuatakgun** [comment]
I have updated a new integration version, this should be fixed by that.

**Comment by nenadmilano** [comment]
Can confirm that it is working for me now! Thank you very much!

**Comment by conorlap** [comment]
I'm getting the following errors in Home Assistant logs:

> 2021-07-28 08:31:48 ERROR (SyncWorker_1) [custom_components.eufy_security] eufy_security Doorbell FFMpegVideoHandlerThread exception: I/O operation on closed file- traceback: Traceback (most recent call last):
> 
> 
>   File "/config/custom_components/eufy_security/camera.py", line 407, in run
> 
> 
>     self.camera.ffmpeg.process.stdin.write(frame_bytes)
> 
> 
> ValueError: I/O operation on closed file

**Comment by fuatakgun** [comment]
You should first give a status, have you updated integration and add-on? if you are using 2k, have you downgraded the quality? did you check all troubleshooting steps here? https://github.com/fuatakgun/eufy_security/#troubleshooting and https://github.com/fuatakgun/eufy_security/#known-bugsissues

**Comment by conorlap** [comment]
Hey fuatakgun, yes I've updated the integration and I'm running the latest 'bropat/eufy-security-ws' etc. I've used a separate Eufy account and set streaming quality to low in the Eufy app.
I've restarted everything and ran both eufy_security.start_livestream & eufy_security.stop_livestream several times to troubleshoot.

**Home Assistant Logs:**

> 2021-07-28 09:41:58 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream eufy_security-T8200NXXXXXXX.m3u8
> 2021-07-28 09:42:18 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream eufy_security-T8200NXXXXXXX.m3u8
> 2021-07-28 09:42:48 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream eufy_security-T8200NXXXXXXX.m3u8
> 2021-07-28 09:43:28 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream eufy_security-T8200NXXXXXXX.m3u8
> 2021-07-28 09:43:28 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream eufy_security-T8200NXXXXXXX.m3u8

 **bropat-eufy-server Logs:**

2021-07-28 07:26:24.767  INFO Connected to station T8200NXXXXXXX on host 192.168.0.50 and port 19314 
2021-07-28 07:27:45.347  ERROR Message error 
 LivestreamAlreadyRunningError  Livestream for device T8200NXXXXXXX is already running

details:
{
  name: 'LivestreamAlreadyRunningError'

m

error stack:
• message_handler.ts:116 handle
    src/lib/device/message_handler.ts:116:31
• server.ts:46 device
    src/lib/server.ts:46:34
• server.ts:98 receiveMessage
    src/lib/server.ts:98:58
• server.ts:57 <anonymous>
    src/lib/server.ts:57:53
• events.js:375 emit
    events.js:375:28
• websocket.js:970 receiverOnMessage
    node_modules/ws/lib/websocket.js:970:20
• events.js:375 emit
    events.js:375:28
• receiver.js:517 dataMessage
    node_modules/ws/lib/receiver.js:517:14
• receiver.js:435 getData
    node_modules/ws/lib/receiver.js:435:17
• receiver.js:143 startLoop
    node_modules/ws/lib/receiver.js:143:22
2021-07-28 08:42:14.329  ERROR Message error 
 LivestreamAlreadyRunningError  Livestream for device T8200NXXXXXXX is already running

details:
{
  name: 'LivestreamAlreadyRunningError'

m

error stack:
• message_handler.ts:116 handle
    src/lib/device/message_handler.ts:116:31
• server.ts:46 device
    src/lib/server.ts:46:34
• server.ts:98 receiveMessage
    src/lib/server.ts:98:58
• server.ts:57 <anonymous>
    src/lib/server.ts:57:53
• events.js:375 emit
    events.js:375:28
• websocket.js:970 receiverOnMessage
    node_modules/ws/lib/websocket.js:970:20
• events.js:375 emit
    events.js:375:28
• receiver.js:517 dataMessage
    node_modules/ws/lib/receiver.js:517:14
• receiver.js:435 getData
    node_modules/ws/lib/receiver.js:435:17
• receiver.js:143 startLoop
    node_modules/ws/lib/receiver.js:143:22

2021-07-28 08:43:15.294  ERROR Message error 
 LivestreamNotRunningError  Start of livestream for device T8200NXXXXXXX was not also requested by this client
details:
{
  name: 'LivestreamNotRunningError'

m
error stack:
• message_handler.ts:123 handle
    src/lib/device/message_handler.ts:123:31
• server.ts:46 device
    src/lib/server.ts:46:34
• server.ts:98 receiveMessage
    src/lib/server.ts:98:58
• server.ts:57 <anonymous>
    src/lib/server.ts:57:53
• events.js:375 emit
    events.js:375:28
• websocket.js:970 receiverOnMessage
    node_modules/ws/lib/websocket.js:970:20
• events.js:375 emit
    events.js:375:28
• receiver.js:517 dataMessage
    node_modules/ws/lib/receiver.js:517:14
• receiver.js:435 getData
    node_modules/ws/lib/receiver.js:435:17
• receiver.js:143 startLoop
    node_modules/ws/lib/receiver.js:143:22

**Comment by fuatakgun** [comment]
if you started the live stream but somehow restarted home assistant later on, you are not allowed to stop livestream as your client ID will be different. 
- Disable integration
- Stop add on
- Restart your cameras (to be sure that they are actually not live streaming
- Restart add on
- Enable integration

This issue might happen any time, if you turned it on, only you can turn it off with same client id.

**Comment by conorlap** [comment]
I've just tried all the above steps and still getting the same errors, strange!

**Comment by fuatakgun** [comment]
when you restart your integration, what was the initial state of camera? streaming or idle?

**Comment by conorlap** [comment]
When I restart the integration it shows under state as streaming yeah

**Comment by fuatakgun** [comment]
it means that your camera is already streaming, you can click on camera image and see the live stream but you are not allowed to stop it. I do not know how and why it is streaming by default.

**Comment by fuatakgun** [comment]
if you need help here, share your camera with me, it will be easy to debug.
if you are located in EU, use my personal account: fuatakgun@gmail.com
if you are located in US, use test account: eufydeveloper@gmail.com

**Comment by conorlap** [comment]
I have just shared my doorbell camera with you. 
I installed the latest version but still getting the following error in Home Assistant:

2021-07-28 21:17:04 ERROR (SyncWorker_8) [custom_components.eufy_security] eufy_security Doorbell FFMpegVideoHandlerThread exception: I/O operation on closed file- traceback: Traceback (most recent call last):
  File "/config/custom_components/eufy_security/camera.py", line 408, in run
    self.camera.ffmpeg.process.stdin.write(frame_bytes)
ValueError: I/O operation on closed file

**Comment by fuatakgun** [comment]
Can you share with admin rights?

**Comment by fuatakgun** [comment]
please get latest codebase (couple of minutes ago) of integration, I fixed it temporarily by integration but it is better to fix this from add-on. long term solution: https://github.com/bropat/eufy-security-client/issues/33

**Comment by conorlap** [comment]
Fantastic, it's working now!! 🥳 Thank you so much!! Much appreciated 😁
