### ISSUE TITLE
No stations found, No devives found

### ISSUE THREAD

**Issue by dewoert** [fuatakgun/eufy_security#242]
My new Eufy Battery Doorbell 2K with HomeBase 2 can't be found in the Add-on.
I created (2) extra accounts, shared camera (doorbell) with advanced options.
When I log into the (iphone) app with those accounts, the camera shows up nicely.

When I use one of those account in the HA Add-on, all I get is the following in de logging:
`2022-01-26 18:12:27.421  INFO  No stations found.`
`2022-01-26 18:12:27.541  INFO  No devices found.`
`2022-01-26 18:12:28.125  INFO  Push notification connection successfully established `

Also tried to get it working in HomeBridge, the Plugin for Eufy gives there also the "No stations and No devices found" error.

I could share the camera if needed to help troubleshoot this issue.

**Comment by fuatakgun** [comment]
Please confirm if you are using correct county code. If you are sure, please create issue under eufy-security-ws repository, i can not be helpful further.

**Comment by spaceboy76** [comment]
in the same situation. i created an issue https://github.com/bropat/eufy-security-ws/issues/74

**Comment by dewoert** [comment]
Following https://github.com/bropat/eufy-security-ws/issues/74 for this issue.
