### ISSUE TITLE
Picture Glance cards no longer retaining most recent image, reverts back to an older image.

### ISSUE THREAD

**Issue by boctok** [fuatakgun/eufy_security#243]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Just noticed that the "snapshot" image on my dashboard won't change from an image from several weeks ago. I can click on the Picture Glance card and it will update for a few seconds, but then it reverts back to the previous old image. Maybe not storing the new image?

**To Reproduce**
1. Go to Dashboard
2. Click on Picture Glance card of Eufy camera (in this case, the doorbell "T8210")
3. Picture Glance card will show current image for a few seconds. but then revert to older image.

**Expected behavior**
The cards used to update to the most recent image.

**Screenshots**

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- T8210
- Live Streaming Protocol: RTSP is configured, but I've given up on getting live streaming to work for now. This camera (T8210) does not support RTSP, so it must be p2p.

**Additional context**
I don't know if this was caused by an update during the last couple of weeks or not. Nothing else has changed on my HA.

**Comment by boctok** [comment]
I did find this in my logs after clicking on the card a few times.

`Logger: custom_components.eufy_security
Source: custom_components/eufy_security/camera.py:209
Integration: Eufy Security (documentation, issues)
First occurred: 4:53:41 PM (1 occurrences)
Last logged: 4:53:41 PM

eufy_security Doorbell video_thread exception: [Errno 32] Broken pipe- traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/camera.py", line 207, in write_bytes_to_ffmeg self.ffmpeg.process.stdin.write(frame_bytes) BrokenPipeError: [Errno 32] Broken pipe`

**Comment by fuatakgun** [comment]
I feel like this is related to ongoing add on issue?

**Comment by tunisiano187** [comment]
Same problem for me if you need inputs
