### ISSUE TITLE
ffmpeg log files created in config even after RTSP add-on

### ISSUE THREAD

**Issue by Noob25930** [fuatakgun/eufy_security#246]
**Describe the bug**
I have a doorbell and multiple cameras which are not RTSP. Using P2P along with RTSP add on like mentioned in the readme. All cameras are working properly but after each instance of viewing the live feed, ffmpeg log files are being created in my config folder.

**To Reproduce**
1. Click on the camera to start stream and then stop it after viewing.
2. Click on file editor to see config folder
3. ffmpeg log file created for each instance of streaming.

**Expected behavior**
Either no files created or deleted after

**Screenshots**
Camera not playing
 
![image](https://user-images.githubusercontent.com/97673068/151363567-b06b0cd1-6450-4924-ab0f-1aed5dc3b4b0.png)

Camera playing
 
![image](https://user-images.githubusercontent.com/97673068/151363642-5f040e05-e1f5-46b9-abe5-c57c73a7b617.png)

Log file created ffmpeg-XXXXXXX-XXXXX.log

![image](https://user-images.githubusercontent.com/97673068/151362636-f88813fd-60cb-4966-82c7-1db9fa5f9d0b.png)

Integration settings

![image](https://user-images.githubusercontent.com/97673068/151362929-c9c10b38-2fa2-412b-baad-4ccd566650c9.png)

**Hardware Information about Home Assistant
Home assistant 2021.12.10

**Hardware Information about Cameras
- Camera Model 2C and T8210 Doorbell
- Live Streaming Protocol: P2P

**Additional context**
I do realize that 2C supports RTSP but choose P2P because of reliability. For some reason my RTSP streams are very inconsistent at starting up. The doorbell does not have RTSP. Regardless, both devices are creating these log files and I delete them manually each day. Please help with this matter if you can or if you need anything else I can provide that. Thank you again to everyone involved in making this integration possible. I know it takes alot of work.

**Comment by fuatakgun** [comment]
Ok, i will create a new setting to enable this explicitly and keep it disabled by default

**Comment by Noob25930** [comment]
Thank you. Will be waiting.

**Comment by jackielegs98** [comment]
Have this issue, was this fixed?

**Comment by fuatakgun** [comment]
introduced a config option to make log generation optional, please get latest version of add-on and integration, post back your results
