### ISSUE TITLE
Binary sensor give me true or false state and not on or off

### ISSUE THREAD

**Issue by mattheeussen** [fuatakgun/eufy_security#247]
**Describe the bug**
Binary sensor give me true or false state and not on or off

**Expected behavior**
on or off state, cant get my automations to work with true or false state

**Screenshots**
https://i.ibb.co/KyqdD2F/deurbel2.png
https://i.ibb.co/hgCVgfP/deurbel.png

**Hardware Information about Home Assistant
Pi4

**Hardware Information about Cameras
- Camera Model
doorbell
C2

**Comment by mattheeussen** [comment]
i'm sorry, i have been fighting with it all day. its that easy!

**Comment by fuatakgun** [comment]
it is on me, to turn on this by default. I just want to be sure that existing users, who already painfully created automations will not be impacted with my decisions.

**Comment by mattheeussen** [comment]
no worries, i'm very happy, keep up the good work
