### ISSUE TITLE
Feature Request: Panic Alarm Mode

### ISSUE THREAD

**Issue by ianmen** [fuatakgun/eufy_security#251]
Hi,

I'm very thankfull for this addon and frequently use it!

One of the functions that I would see as an improvement is the panic alarm. From my Eufy Security keypad I can trigger the panic alarm by pressing the red button. Once this happens the alarm entity exposed to home assistant doesn't change.

Would there be any way to expose the panic alarm state to home assistant either trough the alarm entity or a dedicated binary sensor?

Many thanks again for the integration!

**Comment by fuatakgun** [comment]
done
