### ISSUE TITLE
Camera not showing after new integration

### ISSUE THREAD

**Issue by LordTama** [fuatakgun/eufy_security#254]
I have freshly configured an indoor Cam Pan&Tilt Eufy camera on HASS. Everything is ok on the iphone app.
Everything is installed according to procedure.
No error message in logs for the integration "Eufy Security Addon" and "RTSP Simple Server Addon" but the image and stream is not showing in lovelace.

![Sans titre](https://user-images.githubusercontent.com/21343645/152267514-8d22fbc2-1265-4a65-a665-5c68d74f4455.png)

**Hardware Information about 
Home Assistant OS 7.2
core-2022.2.0

**Hardware Information about Cameras
- Camera Model : indoor Cam Pan&Tilt
- Live Streaming Protocol: P2p (HomeKit integration enabled)

**Comment by LordTama** [comment]
Logger: frontend.js.latest.202202020
Source: components/system_log/__init__.py:190
First occurred: 02:38:17 (6 occurrences)
Last logged: 02:49:20

https://mecatama.duckdns.org/lovelace/default_view:0:0 Uncaught
https://mecatama.duckdns.org/lovelace-home/0:0:0 Uncaught
https://mecatama.duckdns.org/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524311:6:34168 NotSupportedError: Cannot define multiple custom elements with the same tag name

**Comment by LordTama** [comment]
Logger: frontend.js.latest.202202020
Source: components/system_log/__init__.py:190
First occurred: 02:38:17 (6 occurrences)
Last logged: 02:49:20

https://example.org/lovelace/default_view:0:0 Uncaught
https://example.org/lovelace-home/0:0:0 Uncaught
https://example.org/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524311:6:34168 NotSupportedError: Cannot define multiple custom elements with the same tag name

**Comment by fuatakgun** [comment]
This message looks unrelated to Integration, it is about custom-mod lovelace card.

**Comment by LordTama** [comment]
Okay. I was not sure about the error message. But the first message is still true. How can I try to investigate my issue. For example is it possible to test the rtsp server with VLC ? To know if it’s an issue with the add on, the rtp server, the display ?

**Comment by fuatakgun** [comment]
give me couple of days, there are many bigger impacting issues ongoing :)

**Comment by rabbit52068** [comment]
I've similar issue as well. I can control the camera like turn on the spot light etc. but it just won't show any images. I've installed both the "Eufy Security Addon" and "RTSP Simple Server Addon" without issues, however I didn't actually activate the RTSP in the Eufy app, could that be the reason why? Thanks in advance for you help.
