### ISSUE TITLE
Integration is not working (locked, mqtt, no devices etc)

### ISSUE THREAD

**Issue by bearkiter** [fuatakgun/eufy_security#258]
Everything was working perfectly for about 3 weeks, then for no reason I could see I get:

2022-02-06 14:45:11.802  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-06 14:45:15.638  ERROR MQTT Error 
 Error  Connection refused: Not authorized
details:
{
  code: 5
}
error stack:
• client.js:1386 MqttClient._handleConnack
    node_modules/mqtt/lib/client.js:1386:17
• client.js:547 MqttClient._handlePacket
    node_modules/mqtt/lib/client.js:547:12
• client.js:436 work
    node_modules/mqtt/lib/client.js:436:12
• client.js:450 writable._write
    node_modules/mqtt/lib/client.js:450:5
• _stream_writable.js:409 doWrite
    node_modules/readable-stream/lib/_stream_writable.js:409:139
• _stream_writable.js:398 writeOrBuffer
    node_modules/readable-stream/lib/_stream_writable.js:398:5
• _stream_writable.js:307 Writable.write
    node_modules/readable-stream/lib/_stream_writable.js:307:11
• readable:754 ondata
    node:internal/streams/readable:754:22
• node:events:390 emit
    node:events:390:28
• readable:315 addChunk
    node:internal/streams/readable:315:12
2022-02-06 14:45:15.693  INFO  MQTT connection closed 
2022-02-06 14:45:16.816  INFO  No stations found. 
2022-02-06 14:45:17.576  INFO  No devices found. 
2022-02-06 14:45:17.903  INFO  Push notification connection successfully established 
2022-02-06 14:45:30.584  INFO  No stations found. 
2022-02-06 14:45:31.321  INFO  No devices found. 

All entities offline.

Have tried reinstalling addon, repo and integration. No luck.

**Comment by fuatakgun** [comment]
Do you have any add blocker? This looks an issue a blocked network connection to eufy servers.

**Comment by bearkiter** [comment]
Rolled back to .8 and working again for now.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bearkiter** [comment]
.7

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dMopp** [comment]
Same issue here. In addition, my Account seems to be blocked:(

**Comment by bearkiter** [comment]
HASSOS on RPi 4, core downgraded along with Eufy Addon (12/21 core and 0.7.0 eufy) works.

Upgrade both, addon breaks. Will try today only upgrading the addon and leaving the core on older, or upgrading the core and leaving the addon unpatched to differentiate.

**Comment by TEF2one** [comment]
Same here everything working fine for moth and since the last update everything is now unavailable...

**Comment by san84** [comment]
Same issue with core 2022.2.2 and addon 0.8.

**Comment by fuatakgun** [comment]
I am on 2022.2.0 for Home Assistant and 0.8.0 of add-on and all is working, apparently, something has changed on core but i will be able to take a look only tomorrow (EU) evening. Please rollback to earlier core version if you need this add-on.

**Comment by JimGeersinga** [comment]
Same problem here after updating to HA 2022.2.0 and Eufy 0.8.0 no station and devices found

2022-02-06 22:22:40.279  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-06 22:22:41.594  INFO  MQTT connection successfully established 
2022-02-06 22:22:41.794  INFO  No stations found. 
2022-02-06 22:22:41.891  INFO  No devices found. 
2022-02-06 22:22:42.198  INFO  Push notification connection successfully established 
2022-02-06 22:32:42.178  INFO  No stations found. 
2022-02-06 22:32:42.251  INFO  No devices found.

**Comment by fuatakgun** [comment]
Hi all, please get latest version of add-on 0.8.1 and latest home assistant would work fine. There was no change in integration or core, it was mainly due to 0.8.0 version of add-on, should be fixed now. All is working on my local with 2022.2.2 and 0.8.1.

**Comment by fuatakgun** [comment]
Triple checked with new install, restarted addon with reloaded integration and restarted raspberry pi, all is working fine.

**Comment by bearkiter** [comment]
Updated as suggested, broken again. Reverting to previous versions.

**Comment by bearkiter** [comment]
Once core and addon updated, rpi rebooted.
Add on starts- no errors, but fails to discover any entities.

**Comment by fuatakgun** [comment]
if you have issues with no shared devices, can you use your main account to validate this is not a device sharing issue?

**Comment by bearkiter** [comment]
using main account,. creating new sharing account to re-test

**Comment by TEF2one** [comment]
Juste updated to 8.1 an restarted, no error in logs but still no stations nor devices found

**Comment by fuatakgun** [comment]
No device issue was supposed to be fixed by 0.8.0 version. Please check here: https://github.com/bropat/eufy-security-ws/issues/74

**Comment by san84** [comment]
Addon is working again with 0.8.1 (thank you!), but still no stations/devices found.Country: CH

**Comment by rpartapsing** [comment]
same issue here, all worked fine until today:

2022-02-07 09:04:11.074  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-07 09:04:12.334  INFO  No stations found. 
2022-02-07 09:04:12.443  INFO  No devices found. 
2022-02-07 09:04:12.698  INFO  Push notification connection successfully established 
2022-02-07 09:09:03.554  INFO  No stations found. 
2022-02-07 09:09:03.640  INFO  No devices found. 
2022-02-07 09:10:45.016  INFO  Client disconnected with ip: 192.168.178.149 port: 52756 code: 1006 reason:  
2022-02-07 09:11:03.167  INFO  No stations found. 
2022-02-07 09:11:03.258  INFO  No devices found. 
2022-02-07 09:21:03.609  INFO  No stations found. 
2022-02-07 09:21:03.711  INFO  No devices found.

Core: 2022.2.3 add-on version 0.8.1

**Comment by fuatakgun** [comment]
Please follow here: https://github.com/bropat/eufy-security-ws/issues/74 
or create a new one under `eufy-security-ws` as I dont have anyway to help here.

**Comment by Beer17HWAM** [comment]
Tried to share devices with an old Eufy app (version 2.4.0) on Android. Same results. No stations found. No devices found.
When can we expect an update??

**Comment by dMopp** [comment]
Since my account is unlogged, its working fine with latest Version. I created a second account and shared my home, working fine!

**Comment by Beer17HWAM** [comment]
> Since my account is unlogged, its working fine with latest Version. I created a second account and shared my home, working fine!

I did the same but it's not working for me:

docker run -it --privileged -e USERNAME=xx@xxxx.com -e PASSWORD=xxxx -p 3300:3000 bropat/eufy-security-ws:0.8.1
2022-02-07 11:31:20.162  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-07 11:32:09.292  INFO  Client disconnected with ip: 172.17.0.1 port: 60844 code: 1006 reason:  
2022-02-07 11:33:41.922  INFO  No stations found. 
2022-02-07 11:33:42.350  INFO  Push notification connection successfully established 
2022-02-07 11:33:42.465  INFO  No devices found. 
2022-02-07 11:34:11.521  INFO  No stations found. 
2022-02-07 11:34:12.043  INFO  No devices found.

**Comment by dMopp** [comment]
Did you logged into the app once and accepted the invitation?

**Comment by Beer17HWAM** [comment]
Yes. In the app I see the share home. I also logged off the account in the
app and restarted the docker.

**Comment by dMopp** [comment]
Oh okay, then i have no idea. :(

**Comment by Beer17HWAM** [comment]
How can I fill the country if I run a docker.

docker run -it --privileged -e USERNAME=xx@xxxx.com -e PASSWORD=xxxx -p 3300:3000 bropat/eufy-security-ws:0.8.1

I use local port 3300 because port 3000 is already used on my Raspberry pi4.

**Comment by dMopp** [comment]
COUNTRY=DE

**Comment by Palmke** [comment]
@dMopp what configuration do you use when starting the `ws` container? Also, blocked, how? Is eufy actively blocking users now?

So far I really don't think something is wrong with `eufy-security-ws` as you're the living proof and I also have no issues.

**Comment by dMopp** [comment]
Iam not starting it manually, iam using the „addon“ way in HASS. And i dont know. I got an error 401 in my app for few days. Maybe a bug, maybe not :/

**Comment by fuatakgun** [comment]
Releasing a new version following bropat's release but i will not be able to test it.

**Comment by rpartapsing** [comment]
no worries I can it on my part

**Comment by fuatakgun** [comment]
Released new version, installed it, working main functionality, looks ok.

**Comment by rpartapsing** [comment]
I guess it takes some time before hacs recognizes a new version is available for the Eufy Security Add-on.
So I ran the container instead:
docker run -it --privileged -e USERNAME=foo -e PASSWORD=bar -e COUNTRY=NL -p 3000:3000 bropat/eufy-security-ws:0.8.2 
Go this log:

```
Status: Downloaded newer image for bropat/eufy-security-ws:0.8.2
2022-02-07 17:57:20.093  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
Exception in PromiseRejectCallback:
/usr/src/app/node_modules/eufy-security-client/build/http/api.js:224
        return types_1.AuthResult.OK;

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/usr/src/app/node_modules/eufy-security-client/build/http/api.js:440
            switch (await this.authenticate()) {
                               ^

RangeError: Maximum call stack size exceeded
2022-02-07 17:57:20.324  ERROR Error: 
 RangeError  Maximum call stack size exceeded
error stack:
• CallSitesHelper.ts:27 FormatStackTrace
    node_modules/tslog/src/CallSitesHelper.ts:27:16

• CallSitesHelper.ts:59 prepareStackTrace
    node_modules/tslog/src/CallSitesHelper.ts:59:31

• errors:141 maybeOverridePrepareStackTrace
    node:internal/errors:141:29

• errors:115 prepareStackTrace
    node:internal/errors:115:5

• CallSitesHelper.ts:81 getCallSites
    node_modules/tslog/src/CallSitesHelper.ts:81:15

• LoggerHelper.ts:50 getCallSites
    node_modules/tslog/src/LoggerHelper.ts:50:35

• LoggerWithoutCallSite.ts:376 _buildLogObject
    node_modules/tslog/src/LoggerWithoutCallSite.ts:376:55

• LoggerWithoutCallSite.ts:333 _handleLog
    node_modules/tslog/src/LoggerWithoutCallSite.ts:333:40

• LoggerWithoutCallSite.ts:258 debug
    node_modules/tslog/src/LoggerWithoutCallSite.ts:258:28


2022-02-07 17:57:20.328  ERROR Status return code not 200 
{
  status: undefined,
  statusText: undefined
}
2022-02-07 17:57:20.335  ERROR Error: 
 Error  `input` must not start with a slash when using `prefixUrl`
error stack:
• index.js:484 normalizeArguments
    node_modules/got/dist/source/core/index.js:484:23

• create.js:112 got
    node_modules/got/dist/source/create.js:112:39

• api.ts:492 request
    node_modules/eufy-security-client/src/http/api.ts:492:43

• api.ts:168 authenticate
    node_modules/eufy-security-client/src/http/api.ts:168:58

• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

• api.ts:455 request
    node_modules/eufy-security-client/src/http/api.ts:455:21

• api.ts:112 getApiBaseFromCloud
    node_modules/eufy-security-client/src/http/api.ts:112:30

• api.ts:143 authenticate
    node_modules/eufy-security-client/src/http/api.ts:143:25

• api.ts:455 request
    node_modules/eufy-security-client/src/http/api.ts:455:21

• api.ts:112 getApiBaseFromCloud
    node_modules/eufy-security-client/src/http/api.ts:112:30


2022-02-07 17:57:20.338  ERROR Status return code not 200 
{
  status: undefined,
  statusText: undefined
}
2022-02-07 17:57:20.339  ERROR Token error 
{
  method: 'get',
  endpoint: '/domain/NL'
}
2022-02-07 17:57:23.683  INFO  No stations found. 
2022-02-07 17:57:23.935  INFO  No devices found. 
2022-02-07 17:57:25.232  INFO  Push notification connection successfully established
```

**Comment by rpartapsing** [comment]
btw this is only for cams connected to the homebase unit. (I have cams for outside and motion sensors)
I also have Eufy Ip cams, they dont have this issue.

**Comment by bearkiter** [comment]
Got mine working after basically expunging all plugins, integrations etc completely and starting from scratch on the 8.1 update. Will test new version tonight. Thanks to contributor for fast responses, coffee tip incoming if you're set up for it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kobioneil** [comment]
2022-02-07 23:00:45.824  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-07 23:00:49.783  INFO  Connected to station T8010N13202418F1 on host 10.0.0.46 and port 16104 
2022-02-07 23:00:49.852  INFO  Connected to station T8021P1021260DBF on host 10.0.0.16 and port 18687 
2022-02-07 23:00:50.027  INFO  Connected to station T8410P20202205A8 on host 10.0.0.220 and port 19011 
2022-02-07 23:00:50.356  INFO  Connected to station T8400P2020460BE4 on host 54.219.251.168 and port 14052 
2022-02-07 23:00:50.375  INFO  Connected to station T8400P20204601DB on host 35.162.187.157 and port 10274 
2022-02-07 23:00:50.511  INFO  MQTT connection successfully established 
2022-02-07 23:00:50.585  INFO  Successfully registered to MQTT notifications for lock T8510Q1021260FCB 
2022-02-07 23:00:56.168  ERROR Status return code not 200 
{
  status: 423,
  statusText: 'Locked'
}
2022-02-07 23:00:56.185  INFO  No stations found.


Same here, Im running on HomeAssistant Blue. Ever since upgrade, it seems to constantly get stuck right here

**Comment by san84** [comment]
Thank you vry much for the new release - highly appreciated. It‘s actually the first time I can see the eufy cameras in HA.
I haven‘t managed to get RTSP/WebRTC video streams though… working on it.
Where is your KoFi link or similar?

**Comment by hunt350** [comment]
> I guess it takes some time before hacs recognizes a new version is available for the Eufy Security Add-on. So I ran the container instead: `docker run -it --privileged -e USERNAME=foo -e PASSWORD=bar -e COUNTRY=NL -p 3000:3000 bropat/eufy-security-ws:0.8.2` Retrieved this log:
> 
> ```
> Status: Downloaded newer image for bropat/eufy-security-ws:0.8.2
> 2022-02-07 17:57:20.093  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
> Exception in PromiseRejectCallback:
> /usr/src/app/node_modules/eufy-security-client/build/http/api.js:224
>         return types_1.AuthResult.OK;
> 
> RangeError: Maximum call stack size exceeded
> Exception in PromiseRejectCallback:
> /usr/src/app/node_modules/eufy-security-client/build/http/api.js:440
>             switch (await this.authenticate()) {
>                                ^
> 
> RangeError: Maximum call stack size exceeded
> 2022-02-07 17:57:20.324  ERROR Error: 
>  RangeError  Maximum call stack size exceeded
> error stack:
> • CallSitesHelper.ts:27 FormatStackTrace
>     node_modules/tslog/src/CallSitesHelper.ts:27:16
> 
> • CallSitesHelper.ts:59 prepareStackTrace
>     node_modules/tslog/src/CallSitesHelper.ts:59:31
> 
> • errors:141 maybeOverridePrepareStackTrace
>     node:internal/errors:141:29
> 
> • errors:115 prepareStackTrace
>     node:internal/errors:115:5
> 
> • CallSitesHelper.ts:81 getCallSites
>     node_modules/tslog/src/CallSitesHelper.ts:81:15
> 
> • LoggerHelper.ts:50 getCallSites
>     node_modules/tslog/src/LoggerHelper.ts:50:35
> 
> • LoggerWithoutCallSite.ts:376 _buildLogObject
>     node_modules/tslog/src/LoggerWithoutCallSite.ts:376:55
> 
> • LoggerWithoutCallSite.ts:333 _handleLog
>     node_modules/tslog/src/LoggerWithoutCallSite.ts:333:40
> 
> • LoggerWithoutCallSite.ts:258 debug
>     node_modules/tslog/src/LoggerWithoutCallSite.ts:258:28
> 
> 
> 2022-02-07 17:57:20.328  ERROR Status return code not 200 
> {
>   status: undefined,
>   statusText: undefined
> }
> 2022-02-07 17:57:20.335  ERROR Error: 
>  Error  `input` must not start with a slash when using `prefixUrl`
> error stack:
> • index.js:484 normalizeArguments
>     node_modules/got/dist/source/core/index.js:484:23
> 
> • create.js:112 got
>     node_modules/got/dist/source/create.js:112:39
> 
> • api.ts:492 request
>     node_modules/eufy-security-client/src/http/api.ts:492:43
> 
> • api.ts:168 authenticate
>     node_modules/eufy-security-client/src/http/api.ts:168:58
> 
> • task_queues:96 processTicksAndRejections
>     node:internal/process/task_queues:96:5
> 
> • api.ts:455 request
>     node_modules/eufy-security-client/src/http/api.ts:455:21
> 
> • api.ts:112 getApiBaseFromCloud
>     node_modules/eufy-security-client/src/http/api.ts:112:30
> 
> • api.ts:143 authenticate
>     node_modules/eufy-security-client/src/http/api.ts:143:25
> 
> • api.ts:455 request
>     node_modules/eufy-security-client/src/http/api.ts:455:21
> 
> • api.ts:112 getApiBaseFromCloud
>     node_modules/eufy-security-client/src/http/api.ts:112:30
> 
> 
> 2022-02-07 17:57:20.338  ERROR Status return code not 200 
> {
>   status: undefined,
>   statusText: undefined
> }
> 2022-02-07 17:57:20.339  ERROR Token error 
> {
>   method: 'get',
>   endpoint: '/domain/NL'
> }
> 2022-02-07 17:57:23.683  INFO  No stations found. 
> 2022-02-07 17:57:23.935  INFO  No devices found. 
> 2022-02-07 17:57:25.232  INFO  Push notification connection successfully established
> ```

I have the same issue , any solution ?

**Comment by johnjoemorgan** [comment]
@hunt350 following @bearkiter 's advice I deleted the HACS and Add-On components.  Restarted and reinstalled the Add-On.  I got a similar error message to you.  In configuration I input my secondary (guest) admin details and clicked the "reset to defaults" in the network section and saved and restarted the add-on.  All errors went away and I installed the HACS part and everything's back.

**Comment by leonardpitzu** [comment]
Same issue for me. App is V.4 and i have correctly shared my "home". I am clueless as to what to do although it seems some have had more success at fixing this so it might not even be a bug but some misconfiguration...
`ERROR Status return code not 200 
{
  status: 423,
  statusText: 'Locked'
}`

**Comment by air720boarder** [comment]
Looks like this was just fixed in broplat's .84 release: https://github.com/bropat/ioBroker.eusec/issues/228

**Comment by fuatakgun** [comment]
I have tested new version locally, all is fine, updated the add-on version, please download latest version of add-on. (0.8.4)

**Comment by DivanX10** [comment]
> I have tested new version locally, all is fine, updated the add-on version, please download latest version of add-on. (0.8.3)

I tried it. I managed to pass the captcha, the integration worked

**Comment by DivanX10** [comment]
Strange behavior with a captcha. Updated Home Assistant to version 2022.4 and requested a captcha again. I entered everything correctly, a captcha error message appeared, but the integration itself started. It's like integration is launched bypassing the captcha

**Comment by Jo-Jo1987** [comment]
I updated to 0.83 and using v 2.24.

Re-registered my device
      
2022-02-09 09:54:01.244  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-09 09:54:03.223  INFO  No stations found. 
2022-02-09 09:54:03.363  INFO  No devices found. 
2022-02-09 09:54:04.062  INFO  Push notification connection successfully established 
2022-02-09 09:54:51.203  INFO  No stations found. 
2022-02-09 09:54:51.265  INFO  No devices found. 

Still the issue persistst.

I tried using my docker IP (i use supervised) But it will not work with localhost or the Docker IP at the moment.

I did see that when i go to the EUFY app i needed to do a captcha.

Although, in home assistant i do not get any request for putting in a captcha.

**Comment by Jo-Jo1987** [comment]
Any breaking changes on this one?

**Comment by bearkiter** [comment]
Broken again after 7.4 core update. Haven't investigated yet.

**Comment by johnjoemorgan** [comment]
I found that on restart after update I got no devices found.  I clicked through to 'system options' for the integration,  the option for "Enable newly added entities." was already selected but by clicking UPDATE I got my camera and base station back.  

After subsequent restarts for other matters I need to go through this process again.

**Comment by fuatakgun** [comment]
Please get latest version of addon and try again

**Comment by Jo-Jo1987** [comment]
If i try to add your addon from the supervisor store:
https://github.com/fuatakgun/eufy_security_addon

I get a unknown message from now on? 

I removed the integration until it was fixed. And now i add the plugin, and i can't seem to see it in the add on store.

**Comment by JimGeersinga** [comment]
My app got updated to version 4.0 and after I reloaded the addon and integration it all worked again. 
Thanks for your hard work!
