### ISSUE TITLE
camera.turn_off functionality discussion

### ISSUE THREAD

**Issue by Jellyfrog** [fuatakgun/eufy_security#26]
It would be really great if this supported the service camera.turn_off/on. 
Or by other means supported turning on/off the camera. 
Maybe it's already supported and in that case some pointers in the right direction would be lovely since I came up empty. 

Thanks for a good plugin!

**Comment by fuatakgun** [comment]
Updated readme about these information; https://github.com/fuatakgun/eufy_security/blob/master/README.md#services

**Comment by Jellyfrog** [comment]
Thanks! It didn't show because I used the phone app for some reason =/

However am a bit confused, according to: https://www.home-assistant.io/integrations/camera/#service-turn_off
>Turn off camera. Not all camera models support this service, please consult individual camera page.

So I send;
```yaml
service: camera.turn_off
target:
  entity_id: camera.kitchen
```
And nothing happens.

And as far as I understand by:
https://github.com/fuatakgun/eufy_security/blob/ca287e316a40a9d873d81efa90bc25ea41080e98/custom_components/eufy_security/camera.py#L273-L277
It simply turns off the stream? Am I missing something?

**Comment by Jellyfrog** [comment]
I did some more digging and what we need to send is `device.enable_device` (https://github.com/bropat/eufy-security-ws#enabledisable-device)

I can create a PR if you want @fuatakgun 

PS: Only you can reopen issues :)

**Comment by fuatakgun** [comment]
that is correct, it is not enabling/disabling camera as most of battery operated cameras are sleeping all the time unless;
- stream requested
- motion detected
I am mostly using turn_on and turn_off for enabling/disabling streams
there are levels of switches;
- camera should be enabled
- stream should be activated
I have seen some cameras with out enabling functionality, let's discuss on this more.

**Comment by Jellyfrog** [comment]
My use case is that I wanted to control this option of my camera:
![DFFFA531-EF28-461F-B142-EE07C995A405](https://user-images.githubusercontent.com/759887/127484979-4fc34ea8-a93a-4f12-8a1a-10d0031b1713.jpeg)

That's why I was a but surprised on how the feature was implemented :)

**Comment by fuatakgun** [comment]
what about introducing a new service as enable/disable and keep the existing ones for backward compatibiltiy?

**Comment by Jellyfrog** [comment]
I'm up for any solution!
Me personally I would implement a new feature for stopping streaming instead, it makes more sense if the service does what it's documented to do, backwards compatibility you should start to care about when you tag release 1.0.0 :)

**Comment by fuatakgun** [comment]
I am a very bad developer in terms of increasing version numbers :-) this is my 3rd integration and all of them are designed in quick and dirty way, without specific versioning.

**Comment by jbrukardt** [comment]
> what about introducing a new service as enable/disable and keep the existing ones for backward compatibiltiy?

I support this.   Those of us with always on cameras inside our houses like to completely turn off the camera sometimes, not only stopping the stream, but disabling live view as well.    The camera disable/enable service would do that.

**Comment by Jellyfrog** [comment]
In the mean time, call the service like so:

```yaml
service: eufy_security.send_message
data:
  message: >-
    {"messageId": "enable_camera", "command": "device.enable_device",
    "serialNumber": "TXXXXXXXXXXXXXX", "value":true}
```
You can find your serialnumber in the logs:
>2021-07-29 15:38:21.608  INFO Connected to station TXXXXXXXXXXXXXX on host xx.xx.xx.xx and port 11487

**Comment by fuatakgun** [comment]
What is the rationale to disable the camera? (Out of curiosity)

**Comment by Jellyfrog** [comment]
> What is the rationale to disable the camera? (Out of curiosity)

Don't want it on at all when I'm home, it was this way or controlling its physical power :)

**Comment by jbrukardt** [comment]
> > What is the rationale to disable the camera? (Out of curiosity)
> 
> Don't want it on at all when I'm home, it was this way or controlling its physical power :)

very important after the eufy debaucle that randomly gave other users full control of a bunch of folks cameras a couple months back.

**Comment by fuatakgun** [comment]
> > > What is the rationale to disable the camera? (Out of curiosity)
> > 
> > Don't want it on at all when I'm home, it was this way or controlling its physical power :)
> 
> very important after the eufy debaucle that randomly gave other users full control of a bunch of folks cameras a couple months back.   

There is a point but if integration can enable/disable it, it means it is still controllable externally, not a final solution. If that happens again, think about cutting down power :-)

**Comment by jbrukardt** [comment]
From a security engineer perspective, you're absolutely right.   But from a wife-approval factor.... having the cameras visibly off (no light, pan/tilt ones rolled up) is worth a lot.

**Comment by Jellyfrog** [comment]
> But from a wife-approval factor.... having the cameras visibly off (no light, pan/tilt ones rolled up) is worth a lot.

This.

**Comment by fuatakgun** [comment]
enable and disable services are integrated, please get the latest codebase
