### ISSUE TITLE
Integration missing

### ISSUE THREAD

**Issue by vlumikero** [fuatakgun/eufy_security#261]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
After updating to 2022.2.0 the integration has disappeared. I can no longer find it in the installed integrations list, nor the "Set up new integration" menu.

**To Reproduce**
Installed addon/HACS/integration. Upgraded to 2022.2.0 and onwards.

**Screenshots**
![Screenshot 2022-02-07 at 21 46 15](https://user-images.githubusercontent.com/13744614/152869435-e315c10d-cc1f-4b7c-8caf-70d392767428.png)

**Hardware Information about Home Assistant
RPi 3B+

**Hardware Information about Cameras
- Camera Model: T8200 (Wired doorbell)
- Live Streaming Protocol: P2p

**Additional context**

**Comment by fuatakgun** [comment]
please double check if you have installed it using HACS

**Comment by vlumikero** [comment]
I have.
