### ISSUE TITLE
I can't pass the captcha

### ISSUE THREAD

**Issue by DivanX10** [fuatakgun/eufy_security#262]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
After updating the Eufy Security integration v2.2.3, my Home Assistant asked me to confirm the integration.
**Integration requires reconfiguration. At least one of your integrations requires reconfiguration to continue functioning.**
You need to enter a captcha.  I enter the captcha correctly many times, but every time I write that the captcha was entered incorrectly (I attach screenshots). Is there any way to remove the captcha? Why do I need a captcha?

**Screenshots**
![image](https://user-images.githubusercontent.com/64090632/152862152-60045f6c-0cab-4aab-9779-bc4e6255f0b0.png)
![image](https://user-images.githubusercontent.com/64090632/152862166-aff15ba1-8c61-4c47-8478-a7e1b47a4e25.png)

![image](https://user-images.githubusercontent.com/64090632/152872882-610d0aef-d86c-4541-9df6-2f011f56d3d2.png)
![image](https://user-images.githubusercontent.com/64090632/152872898-aba45472-68eb-400c-8747-a7bd301a5bf0.png)

![image](https://user-images.githubusercontent.com/64090632/152873178-158e295c-6a64-4fa5-ba96-adbc67507509.png)
![image](https://user-images.githubusercontent.com/64090632/152873211-8772e165-1299-4383-bd5d-14730caed711.png)

![image](https://user-images.githubusercontent.com/64090632/152873347-e7b49f7c-f9c6-49e5-b476-b714b3a3b7f6.png)
![image](https://user-images.githubusercontent.com/64090632/152873211-8772e165-1299-4383-bd5d-14730caed711.png)

![image](https://user-images.githubusercontent.com/64090632/152873651-3628c47f-4de7-4bdc-9627-022ebc703d0a.png)
![image](https://user-images.githubusercontent.com/64090632/152873211-8772e165-1299-4383-bd5d-14730caed711.png)

![image](https://user-images.githubusercontent.com/64090632/152887962-962468e6-5987-4c43-84ef-a7f5a73a9343.png)
![image](https://user-images.githubusercontent.com/64090632/152873211-8772e165-1299-4383-bd5d-14730caed711.png)

**Comment by air720boarder** [comment]
Same, in a death loop of captcha's that keep yelling at me!

**Comment by air720boarder** [comment]
May be related to this: https://github.com/bropat/ioBroker.eusec/issues/228

**Comment by fuatakgun** [comment]
Hang on, solution is coming from bropat, i will test it when he is done a d release the new version

**Comment by fuatakgun** [comment]
let's track over here: https://github.com/fuatakgun/eufy_security/issues/258
