### ISSUE TITLE
Homebase not showing up in devices

### ISSUE THREAD

**Issue by nwootton** [fuatakgun/eufy_security#268]
**Describe the bug**
When (re-)installing the Eufy Security integration, existing devices are found, but the Homebase is not. Previous versions of the HACS Eufy Security Add-on showed both the Doorbell and Homebase.

**To Reproduce**
1. Delete Eufy Security Integration
2. Restart HA
3. Add Integration, enter 'Eufy' under search term and select integration
4. Enter either localhost or leave as 0.0.0.0 in configuration dialogue for 'Host IP Address'. Leave 'Port' unchanged as 3000.
5. Submit
6. Dialogue pop-up showing 'We found the following devices' - only doorbell listed
7. Assign doorbell device to area and finish
8. New integration appears in dashboard with 1 device and 24 entities.

**Expected behavior**
When devices are listed in Step 6 above, I expect to also see the Homebase and the ability to add that to an area as well. I then expect to see the integration list 2 drives and extra entities.

**Screenshots**
![Screenshot 2022-02-10 at 12 29 15](https://user-images.githubusercontent.com/7591978/153411069-e803892a-0679-4f35-b9e5-dfa40c6d94b4.png)

![Screenshot 2022-02-10 at 12 29 24](https://user-images.githubusercontent.com/7591978/153411088-e4a1d58a-93e3-4235-a5fb-a99ad9991e13.png)

**Hardware Information about Home Assistant
HA running on Intel NUC

## System Health

version | core-2022.2.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4798
Installed Version | 1.22.0
Stage | running
Available Repositories | 1045
Downloaded Repositories | 34

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 109.3 GB
disk_used | 12.1 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Check Home Assistant configuration (3.9.0), Z-Wave JS (0.1.53), AppDaemon 4 (0.8.1), SSH & Web Terminal (10.0.2), Home Assistant Google Drive Backup (0.105.2), TasmoBackup (1.04.26), MariaDB (2.4.0), Zigbee2mqtt (1.23.0-1), Eufy Security Add-on (0.8.3), RTSP Simple Server Add-on (v0.17.6)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 22
views | 20
mode | storage

</details>

**Hardware Information about Cameras
- Homebase 2
- Battery 2k Doorbell - T8210

**Additional context**
Eufy Security Add-on is running v0.83.
Logs show no errors.
```
2022-02-10 12:26:56.081  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-10 12:27:01.573  INFO  Connected to station T8010P2320491D30 on host 192.168.20.51 and port 11706 
2022-02-10 12:27:01.937  INFO  Push notification connection successfully established 
```

HA Logs show the following error:
```
2022-02-10 12:26:16 ERROR (MainThread) [frontend.js.latest.202202030] http://192.168.1.155:8123/frontend_latest/app.19214a15.js:1387:486059 TypeError: null is not an object (evaluating 't.parentElement.tagName')
/config/custom_components/eufy_security/config_flow.py:193: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  eufy_ws.ws.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2022-02-10 12:26:28 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
    await self.set_devices()
  File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
    if await self.async_get_device_properties() is False:
  File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
    for device in self.devices.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

I have tried using 'localhost' and leaving the device as '0.0.0.0' without success.

Previous versions of the Eufy Security platform - Add-on & integration have happily shown the Homebase. Account being used is a secondary account specifically created for use in HA. Account can login and be used in apps.

Apps all show the Homebase and device:
Android Eufy App - 3.5.1_1159(EU)
IPad Eufy App - 4.0.1_867

Homebase is v 2.1.8h subsystem 1.3.0.9 - no outstanding firmware updates

**Comment by nwootton** [comment]
This appeared in the add-on logs:

```
2022-02-10 12:27:01.937  INFO  Push notification connection successfully established 
2022-02-10 13:19:12.094  INFO  Push notification token is expiring, renew it. 
2022-02-10 13:19:12.884  ERROR renewFidToken - Status return code not 200 
{
  status: 400,
  statusText: 'Bad Request',
  data: {
    error: {
      code: 400,
      message: 'Invalid JSON payload received. Unknown name "fid": Cannot find field.\n' +
        'Invalid JSON payload received. Unknown name "appId": Cannot find field.\n' +
        'Invalid JSON payload received. Unknown name "authVersion": Cannot find field.\n' +
        'Invalid JSON payload received. Unknown name "sdkVersion": Cannot find field.',
      status: 'INVALID_ARGUMENT',
      details: [
        {
          '@type': 'type.googleapis.com/google.rpc.BadRequest',
          fieldViolations: [
            {
              description: 'Invalid JSON payload received. Unknown name "fid": Cannot find field.'
            },
            {
              description: 'Invalid JSON payload received. Unknown name "appId": Cannot find field.'
            },
            {
              description: 'Invalid JSON payload received. Unknown name "authVersion": Cannot find field.'
            },
            {
              description: 'Invalid JSON payload received. Unknown name "sdkVersion": Cannot find field.'
            }
          ]
        }
      ]
    }
  }
}
2022-02-10 13:19:12.899  ERROR renewFidToken - Generic Error: 
 Error  FID Token renewal failed with error: Bad Request
error stack:
• service.ts:135 renewFidToken
    node_modules/eufy-security-client/src/push/service.ts:135:23
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• service.ts:165 renewPushCredentials
    node_modules/eufy-security-client/src/push/service.ts:165:16
• service.ts:534 _open
    node_modules/eufy-security-client/src/push/service.ts:534:32
• service.ts:553 <anonymous>
    node_modules/eufy-security-client/src/push/service.ts:553:17
2022-02-10 13:19:27.363  INFO  Push notification connection successfully established 
```

**Comment by Jo-Jo1987** [comment]
i am facing the same, there are issues with the bropat eufy security addon plugin it seems

**Comment by synio-wesley** [comment]
One thing I noticed is that you can now share devices or the whole home in the app. I tried adding an account where I shared the whole home, and there it didn't work. But it looks like it does work when I use the account where I have all the devices shared separately.

**Comment by fuatakgun** [comment]
Please get latest version of addon and try again
