### ISSUE TITLE
battery 2k doorbell progress update

### ISSUE THREAD

**Issue by dpomnean** [fuatakgun/eufy_security#27]
I have been using the latest iterations of this and I have to say, great work @fuatakgun! You are doing a great job with this custom integration. I have been using the start_livestream and stop_livestream services with the npm install version of the eufy-security-ws. I for some reason get weird errors some other people are having but no issue with npm of the same version, but its hard to report them because I get inconsistent logs. Might be due to being on pi 4? h265 is currently not working for me but h264 encoding (can be set via eufy app in device settings > video quality > video encoding format > Low), has been working without issue and am able to start/stop without HA crashing, with the streaming quality setting set to auto.

One thing I am noticing, and I don't think I can capture any log for this, but when I start the stream, it seems to open and close a few times. Those video stream times seem to be through out the day as it gets closer to the current time, like it's trying to catch up to the current time and finally starts streaming live. I am getting about a 10-15 second delay but that is a known issue.

Edit: I forgot to mention, I am able to stream past the 3 minute mark. I am currently at the 5 minute mark and has not stopped yet.

**Comment by fuatakgun** [comment]
Thanks for summary, live streaming relies on video encoding and it requires a lot data to generate the first visible chunks. So, file can be created quickly but it is still not ready for view, that is because you are seeing this weird experience.
