### ISSUE TITLE
Add homebase reboot action

### ISSUE THREAD

**Issue by synio-wesley** [fuatakgun/eufy_security#272]
**Is your feature request related to a problem? Please describe.**
Every few days, my homebase starts to act up and stops sending some notifications. For example, I still receive 'door close' notifications, but 'door open' notifications are gone. After rebooting the homebase, everything starts working again...

**Describe the solution you'd like**
I can see homebase reboot functionality in `eufy-security-ws`. Can this be added to the HA add-on? Check here: https://github.com/bropat/eufy-security-ws/blob/d93101c71f4c6b65061e6c2091c0192c21f3d3e9/docs/api_cmds.md#reboot-station

**Describe alternatives you've considered**
I'm rebooting it manually through the app now when I notice it stops working. But I would like to automate it to restart it automatically once per day using Node-RED.

**Additional context**
No additional context.

**Comment by fuatakgun** [comment]
you can always send these commands manually to the station, you dont need explicit service or button to be developed :) at least you will be unblocked :)

How to do: https://github.com/fuatakgun/eufy_security/discussions/179#discussion-3755508

**Comment by synio-wesley** [comment]
> you can always send these commands manually to the station, you dont need explicit service or button to be developed :) at least you will be unblocked :)
> 
> How to do: [#179 (comment)](https://github.com/fuatakgun/eufy_security/discussions/179#discussion-3755508)

Ok cool, I'll check it out !

**Comment by synio-wesley** [comment]
> > you can always send these commands manually to the station, you dont need explicit service or button to be developed :) at least you will be unblocked :)
> > How to do: [#179 (comment)](https://github.com/fuatakgun/eufy_security/discussions/179#discussion-3755508)
> 
> Ok cool, I'll check it out !

Alright, it works! :-)

For others using Node-RED, this JSONata payload works:

```json
{
   "message": $string(
       {
           "messageId":"test",
           "command":"station.reboot",
           "serialNumber":"T8010XXXXXXXX"
       }
   )
}
```

(replace with actual serial number)
