### ISSUE TITLE
getaddrinfo ENOTFOUND mtalk.google.com

### ISSUE THREAD

**Issue by gbrown09** [fuatakgun/eufy_security#273]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
When starting up the add-on I get this error over and over and it causes the integration to not work properly:
2022-02-11 18:37:17.554  ERROR onSocketError: 
 Error  getaddrinfo ENOTFOUND mtalk.google.com
details:
{
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'mtalk.google.com'
}
error stack:
• node:dns:71 onlookup
    node:dns:71:26

**To Reproduce**
1. Go to Add-on in configurations
2. Click on logs
4. See 

**Expected behavior**
Add-on to start up correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/3360055/153652242-956ecca3-6bf0-43a6-b4a1-eba110140750.png)

**Comment by fuatakgun** [comment]
Any Adguard or pihole setup? it looks like failing to connect to endpoint.

**Comment by gbrown09** [comment]
I have pihole but I already checked and its letting it through
![image](https://user-images.githubusercontent.com/3360055/153656850-441b7162-a99e-48f4-a5a1-bd46482677df.png)

**Comment by fuatakgun** [comment]
Try disabling it and give it a try, it is too much to investigate to blockers, let's go clean first

**Comment by gbrown09** [comment]
Disabled it and still getting that error. It's weird cause it was working fine, only thing I did was update. But I went back to the previous version and it was the same thing

**Comment by gbrown09** [comment]
If it's any help here is what the integration says:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
    await self.set_devices()
  File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
    if await self.async_get_device_properties() is False:
  File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
    for device in self.devices.values():
AttributeError: 'NoneType' object has no attribute 'values'

But I think that is due to the Add-on not starting up right

**Comment by fuatakgun** [comment]
integration error is not pointless now as it is not able to receive any value.

Can you ping this endpoint from cli of addon container?

**Comment by gbrown09** [comment]
Nope, I actually can't ping it from my desktop either

**Comment by gbrown09** [comment]
Not sure what fixed it but it's working now. Thanks for the help

**Comment by fuatakgun** [comment]
Can you please check now if you can ping? Was it a transitient error or we chased something pointless :-)
