### ISSUE TITLE
T8500 Lock status not updating

### ISSUE THREAD

**Issue by Fallen-Kingdoms** [fuatakgun/eufy_security#274]
With the change in the lock.py script to use return self.device.state.get("locked") the T8500 lock no longer updates as it still seems to use "lockStatus" for it's status call. A simple check on the device model to decide which call it should use will fix this.

@property
    def is_locked(self):
        if(self.device.model == "T8500"):
            return self.device.state.get("lockStatus")
        return self.device.state.get("locked")

I've tested it with my T8500 lock and it is working again but don't have a T8520 lock to test against to make sure it works for that version aswell

**Comment by Fallen-Kingdoms** [comment]
I 2.2.4 for the hacs integration and 0.8.3 for the addon version

**Comment by ZerdaFawkes** [comment]
> With the change in the lock.py script to use return self.device.state.get("locked") the T8500 lock no longer updates as it still seems to use "lockStatus" for it's status call. A simple check on the device model to decide which call it should use will fix this.
> 
> @Property def is_locked(self): if(self.device.model == "T8500"): return self.device.state.get("lockStatus") return self.device.state.get("locked")
> 
> I've tested it with my T8500 lock and it is working again but don't have a T8520 lock to test against to make sure it works for that version aswell

I am having the same issue as well. I just tested this fix with my T8510 and it works perfectly. Thank you.

**Comment by jarocks** [comment]
Can doubly confirm this works with the T8510
