### ISSUE TITLE
T8510 Lock Support?

### ISSUE THREAD

**Issue by eroji** [fuatakgun/eufy_security#277]
I tried reading the docs but I can't make much sense of it for getting to work with the T8510 lock I have. It did mention that WiFi locks are not supported. Is this still the case? If it is supported what exactly would I need to get the integration working?

**Comment by fuatakgun** [comment]
did you give a try? It should be straight forward to install and try and share your findings. There are many people out there using the locks.

**Comment by harishvelli** [comment]
I have a T8510 (bluetooth) connected via a T8021 (WIFI Bridge). It is constantly showing unlocked and the lock function does not trigger a response. Happy to share logs if you can let me know how to export it.

**Comment by fuatakgun** [comment]
please test with `v2.2.9
` of integration
