### ISSUE TITLE
Cant sign in - "invalid token" ?

### ISSUE THREAD

**Issue by Erisvaenget27** [fuatakgun/eufy_security#278]
Solved by creating a new account!

**Comment by DivanX10** [comment]
> Solved by creating a new account!

how often do I need to create new accounts? I already have two accounts created and new tokens are required for both accounts

```
2022-02-21 00:47:15.804  INFO  Authentication properties changed, invalidate saved cloud token. 
2022-02-21 00:47:15.821  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-21 00:47:17.331  INFO  Switching to another API_BASE (https://security-app-eu.eufylife.com) and get new token. 
2022-02-21 00:47:19.469  INFO  Push notification connection successfully established 
2022-02-21 00:47:19.575  INFO  Connected to station T8410PXXXXXXXXX on host 192.168.1.68 and port 26651
```

![image](https://user-images.githubusercontent.com/64090632/154872622-571b7b2a-2fe1-4b8e-8b45-6102ee36b2e6.png)

**Comment by fuatakgun** [comment]
thanks for updating back here. These values are all imposed by eufy cloud servers, we don't have direct controls why they are needed and how they are used.

**Comment by joegmc** [comment]
Apologies if this is a different issue. I am building a Home Assistant server for the first time and im having a little trouble setting up the your addon. i have attached screenshots of the Eufy Security Add-On config and log page. Any help would be greatly appreciated.

Cheers

![Config Screenshot](https://user-images.githubusercontent.com/72952993/161206565-f35560f3-6b9b-4388-bf6b-68c1337a01fa.png)
![Log Screenshot](https://user-images.githubusercontent.com/72952993/161206568-f47c5488-dc2e-4b71-b81a-ad8e2504b35a.png)

**Comment by jobjen02** [comment]
> Apologies if this is a different issue. I am building a Home Assistant server for the first time and im having a little trouble setting up the your addon. i have attached screenshots of the Eufy Security Add-On config and log page. Any help would be greatly appreciated.
> 
> Cheers
> 
> ![Config Screenshot](https://github.com/assets/72952993/f35560f3-6b9b-4388-bf6b-68c1337a01fa) ![Log Screenshot](https://github.com/assets/72952993/f47c5488-dc2e-4b71-b81a-ad8e2504b35a)

I have the same error
