### ISSUE TITLE
T8113 Battery status/percentage not updating 

### ISSUE THREAD

**Issue by KnalleArie** [fuatakgun/eufy_security#279]
Eufy camera T8113-Z is not updating the battery percentage anymore, it is stuck on 99%.
Connection with Eufy server is working because the snapshots from the camera's are coming through and are visible in Home Assistant. Also the battery info from my Eufy doorbell is coming through with the correct percentage.

I have stopt the services and also rebooted Home Assistant but no change in status.

![image](https://user-images.githubusercontent.com/90277356/154702536-d7eaa9a3-040d-4b6c-9646-5541bff28e0f.png)

Eufy security addon 0.8.4
Home Assistant OS 7.4
Core 2022.2.8

**Comment by clintkilday** [comment]
Same issue here.

Fully charged all of my cameras, and now their battery percentages are stuck at 0%.

**Comment by kauthmbt** [comment]
Unfortunately it is still the same problem reported before in  
[#132](https://github.com/fuatakgun/eufy_security/issues/132) 

For me in my doorbell it looks like battery percentage is "correct" until an event occurs. In that case it drops to 0%. Restarting add-on & Integration fixes it until next event.
I am a bit struggling with manual debugging as there are so many log entries produced that my session is dropping lines making this incomplete to analyze.

**Comment by dominick369** [comment]
Same issue here. @kauthmbt description and workaround are spot on.

**Comment by fuatakgun** [comment]
Please work this out with @bropat and I will release a new version of add-on whenever it is resolved there.

**Comment by mzelmanovich** [comment]
+1

**Comment by prnewman** [comment]
I discovered that 99% appears in the Eufy Security app as well, so it needs to be fixed on their end. I just added a conditional to the entity row.

**Comment by smartmatic** [comment]
I‘ve the same isseu. I‘ve fully charged the camera but the integration does not recognize it.

**Comment by olivierdj** [comment]
My battery status is also not updating, model T8210.
Eufy add on is updated to the latest version. Reloaded integration, Rebooted, restarted HA, no change. Battery level is stuck at 14%. Doorbell is currently just recharged and is at 100% charge level according to the Eufy app.

**Comment by pascalkrielen** [comment]
Also my T8210 battery remains 100% in HA, but 19% in Eufy App.
I do see wifi signal vary, so it does read information from the doorbell, but for some reason batterylevel is not reported correctly to HA.

**Comment by yavinmaster** [comment]
Same issue for me on a T8210 - stuck on 100% in HA but updating correctly in the Eufy App.

**Comment by kauthmbt** [comment]
Must be something different other than "my" stated problem above from February.
For me it is working now since the fixing from bropat...

**Comment by yavinmaster** [comment]
Interestingly, I've been playing with this integration today (trying to get the video to play properly from the T8210).  Previously all of the other sensors appeared to be working fine and I was using person detection and doorbell presses in automations.  I eventually found that I was missing ffmpeg: from my configuration.yaml and that was causing my video issues.  After adding this, the battery status is now showing correctly.  Time will tell if it continues to update.

**Comment by smartmatic** [comment]
> I eventually found that I was missing ffmpeg: from my configuration.yaml and that was causing my video issues.

Is ffmpeg a must for this integration?

**Comment by pascalkrielen** [comment]
> Interestingly, I've been playing with this integration today (trying to get the video to play properly from the T8210). Previously all of the other sensors appeared to be working fine and I was using person detection and doorbell presses in automations. I eventually found that I was missing ffmpeg: from my configuration.yaml and that was causing my video issues. After adding this, the battery status is now showing correctly. Time will tell if it continues to update.

@yavinmaster , can you share some details about this, so I (and others with the battery reporting issue) may be able to get this working ?

**Comment by yavinmaster** [comment]
I've taken another look at this today and the battery monitor isn't working correctly but something is happening.  So after I was playing around two weeks ago to get video to work, the battery value updated.  Looking at again, it then didn't update again until yesterday.
I've tried making various service calls to see if I can find out what is triggering the update but nothing appears to work.  I'll continue to try to see if I can find what prompts the update.

**Comment by Koal4** [comment]
Same problem (for a while)

Model: Eufy wifi doorbell chime

What I noticed when I restart Home Assistant nothing happens (does not update).
But when I completely restart the VM (running proxmox) it does update. I recently migrated from a RPI installation to Proxmox and even on the RPI I experienced the same behavior (restarting HA does not update / completely restart the RPI it does update).

Perhaps this is some extra info which could be relevant. Happy to provide logs or assistant providing info if needed.

**Comment by derekoharrow** [comment]
I am having the same issue. 

Out of curiosity, I've installed iobroker and the bropay eufy integration in there, and that is reporting the battery percentages just fine.

**Comment by Koal4** [comment]
> bropay eufy integration

Might give it a go as well. But these names are confusing lol

**Comment by kloodhu** [comment]
same for me. T8210 battery is not updating.

**Comment by fuatakgun** [comment]
while I am also impacted, some of you need to spend some time with @bropat to investigate this. I am very short on bandwidth. I will release a new version if it is fixed
