### ISSUE TITLE
clear old files when p2p streaming is ended

### ISSUE THREAD

**Issue by fuatakgun** [fuatakgun/eufy_security#28]
they are created in root directory of home assistant.

**Comment by dpomnean** [comment]
Can we keep the log files if a debug flag is set or else delete everything. Unless we want to keep the log files for X days.

**Comment by fuatakgun** [comment]
Feasible but i am not too worried about log files rather worried about video files. If you leave streaming open for a long period of time, it can consume the whole space

**Comment by skank01** [comment]
I have the same problem, space is filling up with eufy videos

[url=https://ibb.co/D4jm9fF][img]https://i.ibb.co/H79RtTy/eufy.jpg[/img][/url]

**Comment by fuatakgun** [comment]
i would like to eliminate creating files at all, try to server on the fly, probably via internal rtsp server

**Comment by fuatakgun** [comment]
my proposal to install a secondary add on to use streaming server, I have created discussion here, please contribute: https://github.com/fuatakgun/eufy_security/discussions/31

**Comment by fuatakgun** [comment]
I will not spend time on clearing old files as I will deprecate it, I have updated codebase to support option to migrate to RTSP solution. please get latest codebase and go through readme file.
