### ISSUE TITLE
Camera Unavailable after host reboot

### ISSUE THREAD

**Issue by rfnovo** [fuatakgun/eufy_security#280]
When rebooting the entire host (not only the supervisor), all the cameras become unavailable until I reload the integration:

It seems that the integration loads before the Add Ons:

eufy_security - Event received but device is missing, maybe not connected
7:49:57 PM – (ERROR) Eufy Security (custom integration) - message first occurred at 6:35:33 PM and shows up 160 times

eufy_security Garage video_thread exception: [Errno 32] Broken pipe- traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/camera.py", line 209, in write_bytes_to_ffmeg self.ffmpeg.process.stdin.write(frame_bytes) BrokenPipeError: [Errno 32] Broken pipe
6:41:06 PM – (ERROR) Eufy Security (custom integration) - message first occurred at 6:40:32 PM and shows up 2 times

Config entry '0.0.0.0' for eufy_security integration not ready yet: Exception: Host/port is not reachable 0.0.0.0 3000!; Retrying in background
6:35:18 PM – (WARNING) config_entries.py

**Comment by rpitera** [comment]
I have the same issue, or at least I did have it.  Now after the last update, I can't seem to get my cameras at all.  I'll come back with some logs.

**Comment by fuatakgun** [comment]
please retest and comment back here
