### ISSUE TITLE
Stream error if camera.turn_off not used

### ISSUE THREAD

**Issue by rfnovo** [fuatakgun/eufy_security#282]
Stream from a P2P camera works just fine (using RTSP integration), but if I close the window or move away without the "camera.turn_off" command, the streaming remain active and after some times it seems to get "stuck". Camera status remains "Streaming - p2p", but I can see the streaming. In order for the camera stream to work again I have to reload the integradion.

Those are the errors from the add-ons:

2022-02-21 14:43:14.390  ERROR Message error 
 LivestreamNotRunningError  Livestream for device T8422N0021060C0A could not be stopped, because it is not running
error stack:
• message_handler.ts:145 handle
    src/lib/device/message_handler.ts:145:31
• server.ts:50 device
    src/lib/server.ts:50:34
• server.ts:102 receiveMessage
    src/lib/server.ts:102:58
• server.ts:61 <anonymous>
    src/lib/server.ts:61:53
• node:events:520 emit
    node:events:520:28
• websocket.js:1137 receiverOnMessage
    node_modules/ws/lib/websocket.js:1137:20
• node:events:520 emit
    node:events:520:28
• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14
• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17
• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22

2022/02/21 14:42:53 I [-1/0] [RTSP] [conn 172.30.32.1:46444] opened
2022/02/21 14:42:53 I [-1/0] [path T8422N0021060C0A] created
2022/02/21 14:42:53 I [-1/0] [path T8422N0021060C0A] runOnDemand command started
2022/02/21 14:43:03 I [-1/0] [RTSP] [conn 172.30.32.1:46444] ERR: source of path 'T8422N0021060C0A' has timed out
2022/02/21 14:43:03 I [-1/0] [RTSP] [conn 172.30.32.1:46444] closed
2022/02/21 14:43:03 I [-1/0] [path T8422N0021060C0A] runOnDemand command stopped
2022/02/21 14:43:03 I [-1/0] [path T8422N0021060C0A] destroyed
2022/02/21 14:43:04 I [-1/0] [RTSP] [conn 172.30.32.1:46454] opened
2022/02/21 14:43:04 I [-1/0] [path T8422N0021060C0A] created
2022/02/21 14:43:04 I [-1/0] [path T8422N0021060C0A] runOnDemand command started
2022/02/21 14:43:13 I [-1/0] [RTSP] [conn 172.30.32.1:46472] opened
2022/02/21 14:43:14 I [-1/0] [path T8422N0021060C0A] runOnDemand command stopped
2022/02/21 14:43:14 I [-1/0] [path T8422N0021060C0A] destroyed
2022/02/21 14:43:14 I [-1/0] [RTSP] [conn 172.30.32.1:46472] ERR: source of path 'T8422N0021060C0A' has timed out
2022/02/21 14:43:14 I [-1/0] [RTSP] [conn 172.30.32.1:46472] closed
2022/02/21 14:43:14 I [-1/0] [RTSP] [conn 172.30.32.1:46454] ERR: source of path 'T8422N0021060C0A' has timed out
2022/02/21 14:43:14 I [-1/0] [RTSP] [conn 172.30.32.1:46454] closed
2022/02/21 14:43:23 I [-1/0] [RTSP] [conn 172.30.32.1:46482] opened
2022/02/21 14:43:23 I [-1/0] [path T8422N0021060C0A] created
2022/02/21 14:43:23 I [-1/0] [path T8422N0021060C0A] runOnDemand command started
2022/02/21 14:43:27 I [-1/0] [RTSP] [conn 172.30.32.1:46488] opened
2022/02/21 14:43:31 I [-1/0] [RTSP] [conn 172.30.32.1:46492] opened
2022/02/21 14:43:33 I [-1/0] [path T8422N0021060C0A] runOnDemand command stopped
2022/02/21 14:43:33 I [-1/0] [path T8422N0021060C0A] destroyed
2022/02/21 14:43:33 I [-1/0] [RTSP] [conn 172.30.32.1:46488] ERR: source of path 'T8422N0021060C0A' has timed out
2022/02/21 14:43:33 I [-1/0] [RTSP] [conn 172.30.32.1:46488] closed
2022/02/21 14:43:33 I [-1/0] [RTSP] [conn 172.30.32.1:46492] ERR: source of path 'T8422N0021060C0A' has timed out
2022/02/21 14:43:33 I [-1/0] [RTSP] [conn 172.30.32.1:46492] closed
2022/02/21 14:43:33 I [-1/0] [RTSP] [conn 172.30.32.1:46482] ERR: source of path 'T8422N0021060C0A' has timed out
2022/02/21 14:43:33 I [-1/0] [RTSP] [conn 172.30.32.1:46482] closed

[ffmpeg-20220221-080931.log](https://github.com/fuatakgun/eufy_security/files/8110099/ffmpeg-20220221-080931.log)

**Comment by fuatakgun** [comment]
streaming stops after some `unknown` time by the device itself, and sometimes, integration is not informed by this specific action. as streaming has already been closed on device end, sending `turn_off` does not add any value. what happens if you call `turn_on` in this state?

**Comment by rfnovo** [comment]
when this happens, turn_off or stop_p2p_livestream will not work. Only way to get camera working again is to reload the integration.

**Comment by fuatakgun** [comment]
I have included a fix to turn off the stream, in case no more bytes are arrived, please comment back if you still have this issue
