### ISSUE TITLE
Pan & Tilt control for Solo IndoorCam P24

### ISSUE THREAD

**Issue by luisiam** [fuatakgun/eufy_security#286]
Looks like we can send raw command using `eufy_security.send_message` service and pan & tilt control seems to be supported by the `eufy-security-client` library. Can anyone point me to the correct syntax on how to control pan & tilt using the `eufy_security.send_message` service?

Will be great if this plugin can create some sort of entity to control pan & tilt in home assistant. Thank you.

**Comment by fabianluque** [comment]
Here's the message for moving the camera (replace serial number with your camera SN):

```
service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "cmdPanAndTiltUp", 
      "command": "device.pan_and_tilt",
      "serialNumber": "T8410XXX",
      "direction": 3
    }
```

Possible values for direction:

```
ROTATE360 = 0
LEFT = 1
RIGHT = 2
UP = 3
DOWN = 4
```

**Comment by luisiam** [comment]
It works perfectly. Thank you. Is it possible to have it implemented as button with the integration?

**Comment by fuatakgun** [comment]
yes, it is, let's move this into enhancement bucket.

**Comment by fuatakgun** [comment]
a new version is released with 5 new services;
- ptz_up
- ptz_down
- ptz_right
- ptz_left
- ptz_360

**Comment by luisiam** [comment]
Great! Any documentation on how to use it? i.e. what variable do we need to pass into the service and in what format?

**Comment by jeroenterheerdt** [comment]
this works great, you just need to specify the entity_id in the data.
