### ISSUE TITLE
Error on install, Linked to missing files in repo.

### ISSUE THREAD

**Issue by Charles-Garrison** [fuatakgun/eufy_security#288]
When following installation guide, I get to section 6.4, step 6.  When I click on the integration, I get the error, "config flow could not be loaded: [object Object]".  When I look at the file structure in "custom_components", there are four files missing (config_flow.py, const.py, coordinator.py, entity.py).  I manually added them from the git repository and am able to continue successfully.  Any idea why HACS is not bringing them over?

Here is my system configuration information:

Version | core-2022.2.9
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.92-v8
CPU Architecture | aarch64
Host Operating System | Home Assistant OS 7.4
Update Channel | stable
Supervisor Version | supervisor-2022.01.1
Docker Version | 20.10.9
Disk Total | 57.8 GB
Disk Used | 9.5 GB
Healthy | true
Supported | true
Board | rpi4-64
Supervisor API | ok
Version API | ok
Installed Add-ons | Studio Code Server (4.1.0), Check Home Assistant configuration (3.10.0), Mosquitto broker (6.0.1), Node-RED (11.0.3), Z-Wave JS (0.1.54), Terminal & SSH (9.3.0), Eufy Security Add-on (0.8.4), RTSP Simple Server Add-on

**Comment by andymk3** [comment]
Exactly the same error here.

**Comment by fuatakgun** [comment]
as you can see in the latest release zip file, all files exist there (https://github.com/fuatakgun/eufy_security/releases/tag/v2.2.4).

This is a temporary issue happening inside HACS, and this should be transient, if you uninstall and install back, it should work fine. Moreover, you can always install manually.

**Comment by andymk3** [comment]
@Charles-Garrison I had some other issues with HACS recently, such as integrations not updating or installing correctly. I have just disabled IPV6 in HA and it appears to have fixed all my problems that I was having. Might be worth a try.

**Comment by Charles-Garrison** [comment]
@andymk3 It's interesting that you say that - it seems like we're having parallel issues in many ways, but I also just upgraded from a RPi4 to a NUC.  I'm not using IPV6 anyway, so I disabled based on your recommendation and we'll see how it goes.  Thanks for the tip!
