### ISSUE TITLE
No station- no device found 

### ISSUE THREAD

**Issue by soundiesam** [fuatakgun/eufy_security#289]
Hi, 

trying to get my Eufy 2k doorbell setup. When I get to the step of checking the log on the Eufy security add on I am getting 
![2FF2F8FB-DA61-438F-B687-2E80CFB2914E](https://user-images.githubusercontent.com/20504413/156880970-dd088c06-ed5b-4746-8bfb-01993761007d.jpeg)

am I messing up a previous step. The only thing I think might be wrong is I’m in the Uk but if I put uk in country it doesn’t work. 

I added my main account to the Eufy Security Addon and was able to get my camera through. But with my secondary account I was unable to get access. The cameras are shared with this account though

**Comment by fuatakgun** [comment]
have you tried `GB` as country code?

**Comment by soundiesam** [comment]
I get this when i put in GB: 
<img width="681" alt="Screenshot 2022-03-07 at 12 55 01" src="https://user-images.githubusercontent.com/20504413/157038566-a00ecf2f-45d5-4502-88c0-68b830d405d7.png">

**Comment by soundiesam** [comment]
I am no getting the same error with US

**Comment by soundiesam** [comment]
The error im now getting is:
<img width="1078" alt="Screenshot 2022-03-07 at 15 15 55" src="https://user-images.githubusercontent.com/20504413/157062047-94922fb9-d2f3-4924-bfe0-25fa0e07d83a.png">

**Comment by jgeorge1983** [comment]
Sorry to piggyback on this, i am getting the same error.
I am running HomeAssistant through docker and eufy-security-ws throught its own container.
Where are you updating the contry code?

**Comment by fuatakgun** [comment]
I believe this should have been resolved by now, please reopen if needed.
