### ISSUE TITLE
Error demuxing stream battery doorbell 2k

### ISSUE THREAD

**Issue by dpomnean** [fuatakgun/eufy_security#29]
On the battery doorbell 2k, I am running the latest code release. Trying with the docker version of eufy-security-ws 0.3.3. When I restart the container and turn on p2p livestream, it will fail to play the recording and return this in the HA logs. Nothing in the eufy-security-ws logs and when I close out the stream and reopen it, it will play for about 12 or so seconds then start spinning, and restarts the stream like it is playing the same 12 or so seconds. 

```
2021-07-29 23:38:12 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream:
2021-07-29 23:38:13 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream:
2021-07-29 23:38:14 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream:
```

**Comment by fuatakgun** [comment]
please get latest codebase, I strongly suggest using RTSP add-on based solution. In any case, you can share your camera and I can debug the problem.

**Comment by dpomnean** [comment]
I think we can close this. Using the new docker container for the rtsp streaming loads the live feed really fast now. So far so good, I will test and play around with it more for the 2k battery doorbell.
