### ISSUE TITLE
Feature Request: Sounding the alarm on mini speakers and other devices

### ISSUE THREAD

**Issue by TugayArslan** [fuatakgun/eufy_security#290]
**Is your feature request related to a problem? Please describe.**
Homebase sound sometimes is not good enough and also the person who entered the house can unplug it. I would like to utilize other audio devices in the house to increase the effectiveness.

**Describe the solution you'd like**
Automation checks alarm status and then plays alarm on other audio devices like google mini speakers etc.

**Describe alternatives you've considered**
Playing alarm audio in spotify.

**Comment by fuatakgun** [comment]
there is an event for homebase, you can use this as a trigger in your automation to have additional audio notifications.

![image](https://user-images.githubusercontent.com/11085566/157037482-3b04cc7d-f061-47e2-81bb-b9445b66af07.png)

**Comment by fuatakgun** [comment]
you have to manually create some automations to do so, we cannot take care of this inside this integration.
