### ISSUE TITLE
Battery Status of "4" not known

### ISSUE THREAD

**Issue by MechEng70** [fuatakgun/eufy_security#291]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
SoloCam S40 - Solar Powered

```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/select.py:114
Integration: Eufy Security (documentation, issues)
First occurred: 12:37:49 PM (2 occurrences)
Last logged: 12:37:49 PM

eufy_security - North - Carlson - eufy_security_T8124E_charging_status_select - select init missing value error - value: 4 - values_to_states: {'1': 'Charging', '2': 'Unplugged', '3': 'Plugged'} - states_to_values: {'Charging': '1', 'Unplugged': '2', 'Plugged': '3'}
eufy_security - South - Paula - eufy_security_T8124_charging_status_select - select init missing value error - value: 4 - values_to_states: {'1': 'Charging', '2': 'Unplugged', '3': 'Plugged'} - states_to_values: {'Charging': '1', 'Unplugged': '2', 'Plugged': '3'}

```

**Expected behavior**

**Screenshots**

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Camera Model - SoloCamS40
- Live Streaming Protocol: RTSP

**Additional context**

**Comment by fuatakgun** [comment]
Please raise the issue to `eufy-security-ws` repository as I am expecting `state value` to exist in `expected values`.
Current state value is 4.
Possible state values are 1:Charging, 2:Unplugged and 3:Plugged. This list should include 4 too.
