### ISSUE TITLE
Not showing correct state for Smart Lock T8520 since latest eufy-security-client updates (1.6.0+)

### ISSUE THREAD

**Issue by beezel** [fuatakgun/eufy_security#298]
Thanks for this awesome integration!
I've noticed that it does not seem to show the correct state for the Smart Lock Touch Wifi T8520 since @bropat has updated features in 1.6.0+ in https://github.com/bropat/eufy-security-client. 

From the HASS UI I only am able to "lock" or "unlock" but with no accurate state detection.

Please let me know if this is expected behavior or if I have encountered and error and need to submit logs. I am also not sure if this is related to your code or bropat's eufy-security-ws.

I am running everything in containers:
hass:  2022.3.3
eufy-security-ws: 0.8.4
eufy-security: 2.2.4

**Comment by fabianluque** [comment]
I experience this sometimes. If I reload the integration, state is shown properly.

**Comment by beezel** [comment]
> I experience this sometimes. If I reload the integration, state is shown properly.

Thanks @fabianluque , I will definitely give this a try. It does seem to be a bit hit or miss.

**Comment by fuatakgun** [comment]
please share your device following README and let me know when I can debug

**Comment by fabianluque** [comment]
@fuatakgun I haven’t been experiencing this for a few months now.

**Comment by fuatakgun** [comment]
nice to hear and sorry for being unresponsive :)

**Comment by fabianluque** [comment]
@fuatakgun No worries! Glad you’re back!

**Comment by fuatakgun** [comment]
please test with `v2.2.9
` of integration

**Comment by jem** [comment]
Hooray! It works nicely with both locks. Thank you so much!
