### ISSUE TITLE
Changed IP of HA Now Eufy Security won't connect

### ISSUE THREAD

**Issue by tlman12** [fuatakgun/eufy_security#299]
I Changed the IP address of my Home assistant device but the Eufy Security Addon keeps trying to connect to the old IP.

`Logger: homeassistant.config_entries
Source: config_entries.py:335
First occurred: 4:54:09 PM (1 occurrences)
Last logged: 4:54:09 PM

Config entry 'localhost' for eufy_security integration not ready yet: Exception: Host/port is not reachable 192.168.1.11 3000!; Retrying in background`

The IP address is now 192.168.1.12 and I can't find any configs anywhere that reference the old IP. I've tried uninstalling both the Eufy Security Integrations and reset all the settings but it still tries to connect to the old IP.

Where can I find this reference?

**Comment by tlman12** [comment]
> Same thing happened to me. The solution I found was to disable the IPV6 from the router and eufy HA integration start working again.
> 
> good luck

that seems like an odd fix especially since the server and client integration are hosted (in my case) on the same device currently. I made a mistake by not installing it targeting local host in the first place. I'm tempted to just change the device IP back but the curiosity in me makes me want to actually fix it in case I decide to split the server and the client at some point in the future. 

It's just weird, after completely uninstalling the integrations and re-installing them I can't figure out where it's pulling this old info.

**Comment by fuatakgun** [comment]
I believe this should have been resolved by now, please reopen if needed.
