### ISSUE TITLE
Installation steps, step number 2 link not working

### ISSUE THREAD

**Issue by bachoo786** [fuatakgun/eufy_security#3]
Hi

I have tried to follow your installation steps, however the link in step 2 is not working I.e. https://github.com/bropat/eufy-security-ws` and I get this error:
![Screenshot_20210629-003755_Chrome](https://user-images.githubusercontent.com/6251030/123716411-6ce8ce80-d872-11eb-971a-53460f12695e.png)

Can you please help?

Thanks.

**Comment by fuatakgun** [comment]
Sorry, it was a wrong quatotion mark issue, fixed now.

**Comment by bachoo786** [comment]
Thanks @fuatakgun . Just wondering how is your solution different from bropat's eufy-security-ws? I see in your documentation you are providing on how to install bropat's eufy-security-ws only? or am I missing something?

**Comment by fuatakgun** [comment]
This integration is using @bropat's web socket implementation and bring the data into home assistant. What he has delivered is a node based server without connecting any specific consumers or clients. This integration is closing the bridge :-)

**Comment by bachoo786** [comment]
ah right fair enough thanks

**Comment by bachoo786** [comment]
@fuatakgun steps 9 and 10. How can I add the integration on HA? is it via HACS or do I need the Node Red Integration installed via HACS on my HA? sorry its a little confusing for me.

**Comment by fuatakgun** [comment]
Add repository link to HACS and install over there, restart your HA instance to pick up latest custom_components folder and set up integration from integrations page.

Node red is an external automation engine, i have used it as an example here because if you have node red, it means you have node and npm had setup already.

**Comment by fuatakgun** [comment]
are you able to install it? please share your findings

**Comment by bachoo786** [comment]
> are you able to install it? please share your findings

I haven't yet installed it but will do shortly and will report back.

**Comment by bachoo786** [comment]
so I just installed it but on HA I cannot find it under integrations. I installed it as per your instructions via HACS and I also rebooted my machine as my HA is running on docker.

**Comment by fuatakgun** [comment]
Do you have any other eufy related integrations active? I am a bit worried
that they might be using the same name :)

**Comment by bachoo786** [comment]
nope just checked I have no other eufy integrations except for yours.

here is a snapshot of my integrations page when I search for eufy: 
![image](https://user-images.githubusercontent.com/6251030/124105680-5fdb0380-da5b-11eb-9d92-4a0898aa139d.png)

**Comment by fuatakgun** [comment]
can you check your logs if there is any error? and please double check if
you have custom_components/eufy_security folder created.

**Comment by bachoo786** [comment]
no errors in my log and the folder eufy_security is created under custom_components.

**Comment by fuatakgun** [comment]
only possibility is that home assistant is installing runtime dependencies
captured here:
https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/manifest.json#L9

let's wait for some time and try again.

**Comment by fuatakgun** [comment]
Can you let us know outcome? Is this still happening?
