### ISSUE TITLE
Home Assistant DB filling with P2P

### ISSUE THREAD

**Issue by rfnovo** [fuatakgun/eufy_security#300]
Hi, when streaming P2P cameras (Eufy Floodlight, Doorbell), for every time I stream, my home-assistant_v2.db file increases about 5MB/second, as if the stream content was being added to the DB, what would not make any sense.

This does NOT happens with native RTSP cameras (C24).

**Comment by Daneish** [comment]
I have this exact issue with my 2K Battery Doorbell. As a workaround I had to disable the `eufy_security_[cameras_serialNumber]_event_received` event type from my recorder.

However, I thought having it disabled could be causing other stability problems and was hoping the issue may have been resolved in updates to the Eufy Security integration/add-ons; so 6 days ago I re-enabled it in recorder, and the issue has returned.

In the 6 days, `eufy_security_xx_event_received` has had 25,000 events totalling 515MB. 

My recorder is set to the default retention period of 10 days, but my doorbell would only stream for a few minutes each day. I haven't confirmed the exact database growth, but these numbers roughly fit with rfnovos calculations of about 5MB/s.

I'm not sure what the events are, but they appear to be a contain buffer information in JSON format. The `event_data` starts with `{"type":"Buffer","data":[` followed with 30,000 to 100,000 characters.

While the workaround for disabling events from recorder does work, ideally we would not need to do that. This issue could be effecting other Eufy Security users with their database exploding in size, but they may not be aware of it happening, or what was causing it.

@rfnovo, if you wanted to implement the workaround (if you haven't already) you can add the following to your configuration.yaml:
````
recorder:
  exclude:
    event_types:
      - eufy_security_[insert_your_cameras_serialNumber]_event_received
````

fuatakgun, thank you for this great integration, it has been great being able to add my doorbell in as the last piece of my IoT puzzle into HA!

Are you aware of this issue, and should this data be added to the database at such a rate?

Do you know if implementing the work around to disable event from recorder could cause any stability issues, with the integration or add-ons?

I'm running all of the add-ons recommended in the readme, all at the latest versions. My setup:
````
Eufy Security Integration (through HACS): 2.2.4
WebRTC Camera Integration (through HACS): 2.2.0
Eufy Security Add-on: 0.8.4
RTSP Simple Server Add-on: 0.17.6
HA Core: 2022.3.5
HA Supervisor: 2022.03.5
HA OS: 7.4
Compute: Raspberry Pi 4b 4GB
Camera: T8210 2K Battery Doorbell with T8010 HomeBase 2.
````
Please let me know if I can provide any further information or testing to help resolve the issue.

**Comment by fuatakgun** [comment]
thanks a lot for deep dive investigation and summary.
this event is far from `needed to be stored in DB`, it is chunks of video bytes coming from devices and I am putting all together to generate video inside home assistant.

can one you raise a PR to include this into README so other users would learn more on this.

**Comment by fuatakgun** [comment]
deprecated event usages in new version, feel free to comment back after upgrading into new version of integration

**Comment by Daneish** [comment]
Sorry it took me so long to get back to you. Thanks very much, that's a great solution! I have removed the recorder exclude events from my config and confirmed the integration is no longer generating the events.  

> include this into README

Regarding documentation, I thought the Readme could be improved a little and I was thinking of rewriting and reorganising some of it. Would that be useful?
