### ISSUE TITLE
Support for Eufy Doorbell Dual (T8213)

### ISSUE THREAD

**Issue by bart-jansen** [fuatakgun/eufy_security#303]
Setup the new doorbell, followed every step, but it looks like there is no support for the new T8213 doorbell yet:

`
eufy_security - Exception - process_messages: 91 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 56, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 67, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 296, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 245, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 390, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.9/enum.py", line 384, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.9/enum.py", line 702, in __new__ raise ve_exc ValueError: 91 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"T8213XXXXXXXXX","properties":{"name":{"value":"BartBell","timestamp":1648406372000},"model":{"value":"T8213","timestamp":1648406372000},"serialNumber":{"value":"T8213XXXXXXXXX","timestamp":1648406372000},"type":{"value":91,"timestamp":1648406372000},"hardwareVersion":{"value":"P1","timestamp":1648406372000},"softwareVersion":{"value":"0.1.2.1","timestamp":1648230609000},"stationSerialNumber":{"value":"T8010PXXXX","timestamp":1648406372000}}}}', extra='')
`

It seems like it is able to connect to the homebase fine and it does add two motion sensors:
![image](https://user-images.githubusercontent.com/6081141/160642440-483b7786-6061-411a-8ada-b846daada162.png)

Any suggestions or things I could help out with to add support for T8213?

**Comment by rajeshkannan31** [comment]
@fuatakgun

I have same issue. Anything we could do get all the entities of dual camera doorbell via this integration? Thanks for your help.

**Comment by mattheeussen** [comment]
Hello, i have the same issue. I only see Global Motion sensor. but its not triggered

**Comment by bart-jansen** [comment]
As a workaround, I changed the DeviceType of the original DoorBell from _5_ to _91_, since the Dual Doorbell seems to have 91 as a DeviceType.

In these two locations:
https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/generated/DeviceType.py#L1 https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/const.py#L263

Does seem to get a bit further in the process with extra entities:
![image](https://user-images.githubusercontent.com/6081141/162413039-21f47fdd-b564-49e1-9d8d-d394d95a05dd.png)

None of them seem to properly function however :(

**Comment by derjungewilde** [comment]
Hi I got my Doorbell Dual today and I have the same problem. will keep an eye on this issue here...

**Comment by mecolmg** [comment]
Presumably @bart-jansen 's Doorbell Dual is the Battery version, as my Wired version seems to have DeviceType=93. Adding this device type and its mapping to a doorbell in https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/const.py results in the same half-working state that @bart-jansen got. Namely, the camera does not appear to stream.

**Comment by fabianluque** [comment]
It's probably worth requesting support for this doorbell in https://github.com/bropat/eufy-security-client.

**Comment by ejpenney** [comment]
That's already been done: https://github.com/bropat/eufy-security-client/issues/126

**Comment by mattheeussen** [comment]
Hello, i update the conf files and tried device type 5, 91, 93 i only get the function "global motion sensor" but its not triggered.
what did you get to work?

**Comment by beareogaming** [comment]
just wanted to bump this, could we get a new version, the security client updated today?

**Comment by ejpenney** [comment]
I was wondering if I could make these changes locally maybe submit a PR, but I'm not comprehending how it sets the dependency on the security client.  In any event, even with the above changes I'm not getting any video so I suspect something else needs to be modified.  Anyone having any luck getting the dual camera working with HASS?

**Comment by be04376** [comment]
Hi I got my Doorbell Dual today and I have the same problem.

**Comment by thehedgefrog** [comment]
@fuatakgun having the same issue with a Dual Battery, although it seems to be supported.  Sure I'm missing something.

**Comment by be04376** [comment]
The addon upgrade to version 0.9.1 fixed the issue for me.
All entities seems to have loaded, didn't test the camera feed or the motion sensors yet

**Comment by cdnninja** [comment]
Are you able to retest on the latest version to see if it works?

**Comment by thehedgefrog** [comment]
I get the same exact thing as @mattheeussen - also always clear in the history and no ability to stream.

**Comment by mattheeussen** [comment]
ok, very strange. i walked outside and my automation worked. 
now if i check the Global Motion Sensor is see the triggers and it seems to be working.
strange because i didn't update or do anything with HA anymore for a few days now?

i don't know if the live stream works because i didn't set that up.

**Comment by seandop** [comment]
For me, Global Motion Sensor does appear to trigger based on motion whereas "Motion Sensor" does not. For what that's worth.... I still have no camera or stream entity since the 2.2.6 update.

**Comment by thehedgefrog** [comment]
Any updates?

**Comment by fuatakgun** [comment]
if this is a new device, it has to be added here https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/const.py#L326

I will work on this and release a new version of integration
