### ISSUE TITLE
Support for SmartDrop (T8790)

### ISSUE THREAD

**Issue by jonackey** [fuatakgun/eufy_security#304]
I only recently received mine and attempted without luck to add it to Home Assistant using this integration but could not get it to work. I do not have the HomeBase 2 yet, but I should be receiving it towards the end of the month.

Given that the SmartDrop has different features than a camera, but kind of operates like a door lock it will likely require some additional API commands.

https://us.eufylife.com/products/t8790

**Comment by fuatakgun** [comment]
can you confirm that `eufy-security-ws` repository can support this? If not, you need to work with repository owner to include missing features and I will be glad to help later on.
