### ISSUE TITLE
cannot add integration after installing it from HACS

### ISSUE THREAD

**Issue by alamoudimoh** [fuatakgun/eufy_security#305]
I have installed everything according to the guide, however, when i want ot install the addon, i cannot find it

4- After restart, go to Configuration - Integrations page and click on Add Integration

**Comment by joeljody77** [comment]
yep same here as well. could see it yesterday but no dice today.

**Comment by Lowlander61** [comment]
Same for me, unable to find the eufy security intergration

**Comment by gmsantosti** [comment]
Same issue for me:

Steps 6.1: Completed
![image](https://user-images.githubusercontent.com/7746238/165249483-0eec26b9-7943-4e19-9f58-15da736f1834.png)

Steps 6.2: Completed
![image](https://user-images.githubusercontent.com/7746238/165249645-348c7888-66ab-4495-9fb2-c1ad836f077a.png)

Step 6.3: Pending
![image](https://user-images.githubusercontent.com/7746238/165249739-4326e9c7-fc89-43f7-a10d-8b38a99a3d05.png)

**Comment by wssrobs** [comment]
I had this problem and reloaded the HA integrations page in my browser. Then the Eufy integration appeared.

**Comment by gmsantosti** [comment]
> I had this problem and reloaded the HA integrations page in my browser. Then the Eufy integration appeared.

How exactly did you reloaded the HA integrations page (I assume it was not a simple page refresh, was it?)? I already tried uninstalling and installing the add-ons, restarting my HA multiple times and still did not show-up...

**Comment by joeljody77** [comment]
For me it was a case of updating home assistant to get it to show up.

**Comment by gmsantosti** [comment]
> For me it was a case of updating home assistant to get it to show up.

I'm running the latest version, see below:
![image](https://user-images.githubusercontent.com/7746238/165383987-17aae2fe-1631-4e99-ab33-d688de6d6dc9.png)

**Comment by joeljody77** [comment]
Not sure if this helps but im not on latest.
![Uploading Screenshot_20220427-074443_Home Assistant.jpg…]()

**Comment by gmsantosti** [comment]
I tried downgrading to 2022.4.2 and installing both add-ons again, same issue at step 6.3 ("Eufy Security did not show up when adding a new integration") :(

**Comment by gmsantosti** [comment]
@fuatakgun , do you have any idea/suggestion?

**Comment by joeljody77** [comment]
Not sure what else to try. Ya port not conflicting with anything else on home assistant? Got me beat why i had same issue it now showing then when i updated it showed up.

**Comment by joeljody77** [comment]
You did install via HACS im assuming?

**Comment by esowers** [comment]
@gmsantosti Trying clearing your browser's cache and then refreshing.

**Comment by stoniwankenobii** [comment]
> @gmsantosti Trying clearing your browser's cache and then refreshing.



> @gmsantosti Trying clearing your browser's cache and then refreshing.

Just tried this and can confirm it brings it back up without having to downgrade HA version.

**Comment by stoniwankenobii** [comment]
> @gmsantosti Trying clearing your browser's cache and then refreshing.



> @gmsantosti Trying clearing your browser's cache and then refreshing.

Just tried this and can confirm it brings it back up without having to downgrade HA version.

**Comment by joeljody77** [comment]
Excellent.  I'm glad someone was able to help them. Good to know for future reference.

**Comment by gmsantosti** [comment]
Hi all,

I highly appreciate all help and suggestions, but unfortunately cleaning the cache did not work for me, below some screenshots of my current situation:

1) Add-ons:
![image](https://user-images.githubusercontent.com/7746238/165886906-4a260a43-b2bd-45ef-94da-0765d874db54.png)
![image](https://user-images.githubusercontent.com/7746238/165886934-5306435f-eb0c-4a6b-abdd-e9e3993cdc9f.png)
![image](https://user-images.githubusercontent.com/7746238/165887107-c8d4bb14-235d-4453-a4a6-fd30e488d19c.png)
![image](https://user-images.githubusercontent.com/7746238/165887130-e36963c6-301e-4f64-8c67-45fbaecf565a.png)
![image](https://user-images.githubusercontent.com/7746238/165887145-06c99abf-fa66-4064-9735-a6de2f9da838.png)

2) Add New Integration:
![image](https://user-images.githubusercontent.com/7746238/165887193-140fd6e8-66d1-4491-90b6-82c64e601a2c.png)

**Comment by fuatakgun** [comment]
Please show that integration is installed from HACS ui. You have provided that you have everything about add-on other than integration.

**Comment by gmsantosti** [comment]
> Please show that integration is installed from HACS ui. You have provided that you have everything about add-on other than integration.

It worked! 
![image](https://user-images.githubusercontent.com/7746238/166852457-403c4360-3ffa-4561-aac1-5b557ff10b39.png)
