### ISSUE TITLE
Add COUNTRY env-variable in docker example

### ISSUE THREAD

**Issue by bvermolen** [fuatakgun/eufy_security#309]
When you are not located in the US and you are following the Installation Guide in the README, you will get stuck on the docker-image for EufySecurity. 

To specify another country, this must be added to the environment variables. Like this:
```docker run -it -e USERNAME=email@address.com -e PASSWORD=password_goes_here -e COUNTRY=UK -p 3000:3000 bropat/eufy-security-ws:X.Y.Z```

Can this be updated in the README.

**Comment by cdnninja** [comment]
Are you able to create a pull request with the details?

**Comment by bvermolen** [comment]
Yes, will do that.
