### ISSUE TITLE
Spotlight Support for Solo OutdoorCam C24 (T8441)

### ISSUE THREAD

**Issue by luisiam** [fuatakgun/eufy_security#313]
I am researching to add the Solo OutdoorCam C24 (T8441) to my home. Even though it is not on the official support device list, seems like it is already working with the integration. The only thing is that the spotlight is not supported with this integration but it is already supported by the [eufi-security-client](https://github.com/bropat/eufy-security-client) library. Is it possible to add support for the spotlight? Or is it possible to toggle the spotlight using the `eufy_security.send_message` service?

Reference: https://github.com/bropat/eufy-security-client/issues/123

**Comment by ping-localhost** [comment]
Relevant ticket has been resolved (via https://github.com/bropat/eufy-security-client/commit/1903146f59428eb6a518be1dbc19228d4f53f5ff) and the fix will be released in the next version. After that it might be nice if `eufy_security` could expose the toggle within Home Assistant.

**Comment by ping-localhost** [comment]
Version 2.1.0 has been released. The spotlight toggle now exists in `eufy-security-client` for this camera.

**Comment by ping-localhost** [comment]
It is not a new device, it already existed, but the spotlight toggle was never exposed as `bropat/eufy-security-client` didn't know that it was possible.

**Comment by jkyselak** [comment]
After the update I can see the new switch "Light" and I am able to turn the light on but unfortunately not off. Turning the light off only works through the Eufy app.

**Comment by ping-localhost** [comment]
Now that you mention it, I have the same issue. I'll make an issue in the relevant repository. How odd.

**Comment by fuatakgun** [comment]
I will release the new version of add-on when it is fixed by eufy-security-client repository
