### ISSUE TITLE
Unable to get homebase2 to connect with addon

### ISSUE THREAD

**Issue by rridenour** [fuatakgun/eufy_security#318]
I am following your guide to the letter and everything goes in ok. but when I start the add-on this is what the log states.

2022-04-26 00:43:00.052  ERROR P2PClientProtocol.lookup(): station: T8010Pxxxxxxxxxxxxx - All address lookup tentatives failed. 
2022-04-26 00:43:00.054  INFO  Timeout connecting to station T8010Pxxxxxxxxxx.

It does this every 10 seconds. my homebase2 is currently wired to the router.  The eufy integration does pick up the entities. But the addon will not connect.

Any help would be appreciated.  Do I need to go into the router and forward any ports?

The integration does work to some degree but I can't stream the camera of course due to the not connecting error.  I have shared devices with admin rights with another account.  So these entities are found and it goes straight to success.

**Comment by rachaelburke-krb** [comment]
Same issue here
HA 2022.5.3 on HassOS
Eufy Security Add-on v0.8.4
HACS Eufy Security Integration v2.2.4

Was working briefly when first set up yesterday, now no video streaming and out of date camera entities.

**Comment by fuatakgun** [comment]
Please log-in using your new account in respective mobile app to validate that new account has full access to all shared devices. If the issue still persists, creating a new account also solved it many times. If you still have the issue, please create an issue over here: https://github.com/bropat/eufy-security-client
