### ISSUE TITLE
Unable to connect to new Doorbell

### ISSUE THREAD

**Issue by buzurk26** [fuatakgun/eufy_security#319]
Hi, Recently purchased a Eufy Doorbell 2k wired and its all setup and working well
Running the latest version of HAS and your addon however i cannot get it to work.

Wondering where to first look?
Are there any special firewall requirements between the doorbell and the HAS server? Assume just tcp/3000 ?

My doorbell is on a different (iot) vlan to the HA instance, looks like some others have had this issue and only resolved it by putting the doorbell on the same VLAN as the HA instance, I dont really want to do this, i have 80 other devices on IOT vlan all working well with HA

Is it possible to put my doorbells LAN IP into the code somewhere so it dosnt have to do a lookup?

```
2022-04-28 10:57:00.726  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-04-28 10:57:16.683  INFO  Push notification connection successfully established 
2022-04-28 10:57:22.617  ERROR P2PClientProtocol.lookup(): station: T8200************** - All address lookup tentatives failed. 
2022-04-28 10:57:22.619  INFO  Timeout connecting to station T8200**************
2022-04-28 10:57:42.626  ERROR P2PClientProtocol.lookup(): station: T8200************** - All address lookup tentatives failed. 
2022-04-28 10:57:42.627  INFO  Timeout connecting to station T8200************** 
2022-04-28 10:58:07.638  ERROR P2PClientProtocol.lookup(): station: T8200************** - All address lookup tentatives failed. 
```

**Comment by rridenour** [comment]
It is not your setup. I am connected  to my router all in the same network .  Have had the same issue.  Same failed lookup.  Everything works except the camera live streaming.  Hopefully some one will get back to us soon with a fix.

**Comment by buzurk26** [comment]
I cant get any of it to work, the doorbell not coming through at all.

My doorbell is reserved a lan IP, can i hard code the IP into this code anyway, will that remove the error?

**Comment by rridenour** [comment]
I just did the entire installation instructions all the way through to the end and when I set up the eufy integretion it found the doorbell and the entities. Like I said the live streaming is the only thing affected by the error that I can tell. I believe that is due to the homebase or chime not getting an ip address logged into the HA system so I do not have an address to feed the webrtc integration. But I am able to send notifications to my android tv and alexa to make TTS announce that someone is at the door.

**Comment by rridenour** [comment]
It is the same one you used in the eufy app.

**Comment by buzurk26** [comment]
Yeah i think there is a bigger issue

I went and got a different model doorbell (namely because iw anted the new dual cam one)

Moved it all to same network as my HAS (same subnet) and same error in logs and now entities come down to HAS :(

**Comment by rridenour** [comment]
Yeah well I do know the dual cam is not supported yet

**Comment by beareogaming** [comment]
just wanted to bump this, could we get a new version, the security client updated today

**Comment by buzurk26** [comment]
Mine updated to 0.91 today and it now connects - Thanks @fuatakgun
