### ISSUE TITLE
Cannot control T8520 Lock with latest 0.9.0 docker container

### ISSUE THREAD

**Issue by luisiam** [fuatakgun/eufy_security#322]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Lock entity is not available after updating to 0.9.0 eufy-security-ws docker container. It resumes working after downgrading to 0.8.4.

**To Reproduce**
1. Update to 0.9.0 eufy-security-ws docker container.

**Expected behavior**
Lock entity to be available

**Hardware Information about Home Assistant
Docker container 2022.4.7

**Hardware Information
T8520

**Comment by sami-shakir** [comment]
This has baffled me the last few days but not enough to warrant looking into until today. Can confirm that in 0.9.0+, it still connects to the locks and entities are still there, the only issue was the lock entity was unavailable. I can still see battery etc.

**Comment by luisiam** [comment]
Yes. The battery sensor is still there. Just the lock entity is gone.

**Comment by bamzero** [comment]
I only just installed this yesterday, was wondering why I could only see the battery entity. Downgraded to 0.8.4 and have the lock as well as battery now.

I also have 2 irrelevant entities that I assume are related to Eufy cameras, global motion sensor and streaming sensor. Is that normal? I've just disabled them anyway.

BTW, just tried 0.9.1 and still no lock entity.

**Comment by sami-shakir** [comment]
> I also have 2 irrelevant entities that I assume are related to Eufy cameras, global motion sensor and streaming sensor. Is that normal? I've just disabled them anyway.

Yeah, the locks have motion sensors on them, it worked the first time I opened the box and tried it. It's supposed to be there so that the lock would light up the keys when you approach, but has never worked since.

**Comment by calvinbui** [comment]
Downgrading the ws container to 0.8.4 brings back the lock entity. @bropat should this issue be created over in https://github.com/bropat/eufy-security-ws?

**Comment by jdilly** [comment]
There was a breaking change in eufy-security-ws 0.9.0 / eufy-security-client 2.0.0 that requires an update to the eufy-security integration. I wasn't able to get the integation to add a lock entity for my T8500 until I made this change, and I'm pretty sure it's needed for at least most other device types as well.

In const.py:

```
    def set_properties(self, properties: dict):
        self.properties = properties
        self.type_raw = get_child_value(self.properties, "type.value")
        type = DEVICE_TYPE(self.type_raw)
        self.type = str(type)
        self.category = DEVICE_CATEGORY.get(type, "UNKNOWN")
```

"type.value" should now be just "type". The updated function should look like:

```
    def set_properties(self, properties: dict):
        self.properties = properties
        self.type_raw = get_child_value(self.properties, "type")
        type = DEVICE_TYPE(self.type_raw)
        self.type = str(type)
        self.category = DEVICE_CATEGORY.get(type, "UNKNOWN")
```
