### ISSUE TITLE
Cannot receive video footage on a Eufy Video Doorbell 1080p

### ISSUE THREAD

**Issue by Ardor2005** [fuatakgun/eufy_security#323]
**Describe the bug**
I am experiencing an issue where my Eufy Video Doorbell 1080p does not deterministically stream content to Home Assistant. It will stream images of passer-by objects sometimes (but not video) and often it will not send any footage to Home Assistant (but will show full video on the Eufy Security App). 

I tried enabling live-streaming via P2P with the AddOn, but that only worked the first time I tried it. But I would still prefer if I could just preview a few seconds of video footage whenever the doorbell detects motion.

**To Reproduce**
1. Follow the installation steps and integrate Eufy Video Doorbell 1080p with Home Assistant.
2. Add a card for the device
3. Observe the issue described above

**Expected behavior**
I expect the device to stream a few seconds of video to Home Assistant whenever it detects motion.

**Hardware Information about Cameras
- Eufy Video Doorbell 1080p
- Live Streaming Protocol: P2P (doorbell does not support RTSP)

Thank you in advance for taking the time for my issue.

**Comment by Slmii** [comment]
I am trying to do the same, after motion detection to start streaming with P2P. Any ideas how to do this? The only way I could find it to have a Picture Entity with a Call to Service, but that also doesnt work for me.

**Comment by fuatakgun** [comment]
If your camera is not streaming 24/7 and should stream on demand as you requested, starting stream itself takes 2-3 seconds at least and home assistant 's reaction would be 1-2 seconds, you are at least 5 second delay.

After that, calling respective streaming services should give you the stream in home assistant.

**Comment by fuatakgun** [comment]
resolving
