### ISSUE TITLE
Update eufy-security-ws to 0.9.x

### ISSUE THREAD

**Issue by eikowagenknecht** [fuatakgun/eufy_security#324]
When can this be done? The battery bug is supposed to be fixed there (along with many others):

https://github.com/bropat/eufy-security-ws/issues/57#event-6528066794

**Comment by jdilly** [comment]
I copied the eufy-security-addon config to my local add-on folder and incremented the eufy-security-ws version to 0.9.1. Just had to make one change to the eufy-security integration to get the lock entity for my T8500 added to HA after the eufy-security-ws upgrade:
https://github.com/fuatakgun/eufy_security/issues/322#issuecomment-1126903959

I only have the T8500 lock, so not sure if other changes might be needed for other device types, but this was the only major breaking change that I had to resolve.

**Comment by msettlemeyer** [comment]
@jdilly , any documentation online on how to do this?

**Comment by cdnninja** [comment]
This has been merged.
