### ISSUE TITLE
Integration pulls through all entities but no camera.

### ISSUE THREAD

**Issue by jgeorge1983** [fuatakgun/eufy_security#325]
Hi,

I am running homeassistant though docker, I have set up the eufy security ws, and connected both.

The integration pulls back sensors, configuration and diagnostic entities but not camera.XXXX entity.
I have a wired 2k doorbell, 3 2c's and a pan and tilt, and no camera.entity pulls through

The cameras are shared to this account with full admin credentials as well as push notifications.  I am at a bit of a loss.
I have unshared and reshared.
removed and readded the integration
recreated the ws docker

But still the camera entities dont come through.

Any ideas why it would miss just those ones?

**Comment by jgeorge1983** [comment]
elwing00, you life saver, there they are.  thank you very much.

one more thing though,  what card do i need to stream them from HA?

**Comment by elwing00** [comment]
I haven't figured that out yet :) - I just moved from the old MQTT add-on to a full docker install and used the "new" method.  It's been slow going because of stuff going on in my personal life, but I plan on trying to figure it out more next week.

**Comment by jgeorge1983** [comment]
So as far as i can tell, you insall RTSP simple server.
Then in HACS install WEBRTC Camera
Then install the WEBRTC Camera integration.

Then from here I am using the camera's RTC link from the app not the EUFY integration, not sure if that is right or wrong but it works.

**Comment by jdilly** [comment]
I can't be positive because I don't have a eufy camera (only device is a T8500 that I just installed today), but I'm pretty sure this will fix your issue as well:
https://github.com/fuatakgun/eufy_security/issues/322#issuecomment-1126903959
