### ISSUE TITLE
Just a thanks!

### ISSUE THREAD

**Issue by dsjackson** [fuatakgun/eufy_security#33]
I just wanted to thank you for all your efforts.  2K wired doorbell plus two 2C cameras all working well with the latest release.

**Comment by fuatakgun** [comment]
Thanks for feedback, enjoy

**Comment by apokha1** [comment]
I can confirm, it is working for my 2K wired doorbell too. However, after installing this custom_integration, the HA server when I restart, stucks at the message, "Home Assistant is starting, not everything will be available until it is finished."

If I disable the integration and restart, it boots up fine. Not much in the log for help, except an error for "demuxing stream"

**Comment by fuatakgun** [comment]
I am having a similar issue about initial startup. Can you share your live stream delay?

**Comment by Jellyfrog** [comment]
Seeing the same, here is one error from startup:

```
2021-08-04 23:39:07 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/eufy_security/camera.py", line 317, in async_start_rtsp
dummy = self.state
File "/config/custom_components/eufy_security/camera.py", line 209, in state
self.set_is_streaming()
File "/config/custom_components/eufy_security/camera.py", line 246, in set_is_streaming
async_call_later(self.hass, 0, self.state_changed)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1223, in async_call_later
return async_track_point_in_utc_time(hass, action, dt_util.utcnow() + delay)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1199, in async_track_point_in_utc_time
cancel_callback = hass.loop.call_later(delta, run_action, job)
AttributeError: 'NoneType' object has no attribute 'loop'
```

**Comment by fuatakgun** [comment]
@Jellyfrog i believe you had enabled `preload stream`, is that correct?

**Comment by Jellyfrog** [comment]
> @Jellyfrog i believe you had enabled `preload stream`, is that correct?

No idea what that is. Cannot find anything about it?

**Comment by fuatakgun** [comment]
In video streaming window inside home assistant, there is a checkbox in top right, can you check if it is enabled for any of cameras?

**Comment by Jellyfrog** [comment]
> In video streaming window inside home assistant, there is a checkbox in top right, can you check if it is enabled for any of cameras?

Have no such window as far as I know. I did disable all enitys for this plugin. Only need to control on/off really. Which this plugin is a bit overkill for :) but that's for another ticket.
