### ISSUE TITLE
Home Assistant is dropping some motion sensor events

### ISSUE THREAD

**Issue by bdnstn** [fuatakgun/eufy_security#334]
Running Home Assistant (HA OS in docker container) I get more motions detected and reported in the Eufy App than are reported in HA.

I expect the motion detection to be the same in HA and the Eufy App.

Here is HA Logbook. Note there are only 2 motion detections.

![image](https://user-images.githubusercontent.com/24848173/168580676-76d4f93a-328e-4073-bbda-beab62b7591e.png)

Here is motion detection from the Eufy App. Note motion at 3:04, 2:10, 2:04 and 12:03 are missing from the logbook. Motion at 2:53(54) and 5:10 are reported properly.

![image](https://user-images.githubusercontent.com/24848173/168581336-69f73244-7dce-4c6f-9d1b-ca44d110bc0c.png)

I am running HA on a fast Windows machine running Virtual Box, which runs the HA OS.

The cameras are Eufy 2c on a HomeBase 2 at a remote location on a fast internet connection (100MBs at both ends).

I'm not doing any live streaming, I'm only interested in getting the motion detection to trigger HA automations.

I've been troubleshooting this problem for two days, so I really hope you are able to help me. Please let me know if there is anything I can do to help you. I am an experienced programmer (mostly Delphi and Firebird) but am new to HA and Python.

**Comment by fuatakgun** [comment]
please enable debug logging for integration and check the incoming messages from add-on to integration.
If the eufy servers are not publishing push notifications on these notifications, there is nothing we can do here because we fully rely on push notifications for states.
if we have correct notifications, then we can work together to debug further

**Comment by fuatakgun** [comment]
there is an option in the app, to send notifications in every X minutes, to minimize number of distractions, can you double check and reopen this if needed?

**Comment by bdnstn** [comment]
Sure. I'm sorry I haven't been able to investigate this any further. I have a work-around, which is to get the cameras to trigger the base station alarm and I just monitor the base station. That has been reliable. There are many different types of motion events coming from the cameras it is difficult to know which ones should be used as triggers.

Thanks for this integration.
