### ISSUE TITLE
Geo fence status

### ISSUE THREAD

**Issue by ethicallymad** [fuatakgun/eufy_security#336]
Running a eufy floodlight camera pro 2, which has a very reliable geo fence status. Would be great to be able to access this as a trigger for HA.

**Comment by fuatakgun** [comment]
need clarification, what is exactly needed here?

**Comment by Khaled-Hamad** [comment]
![image](https://user-images.githubusercontent.com/25899572/177003169-9044087f-3de7-4e35-be59-111066c98fb8.png)
in homebase, you can have arm-home, arm-away, but there is no geofencing and schedule for arm, how to add?

**Comment by fuatakgun** [comment]
You need to call services for geofencing, it is not a state of alarm station, it is a rule config.

Check eufy_security services, you will find them there
