### ISSUE TITLE
Can't find Eufy Security Integration

### ISSUE THREAD

**Issue by eagleguts** [fuatakgun/eufy_security#338]
I've gone through the instructions, however I get stuck at adding the Eufy Security Integration after Installing the Eufy Security repository. When I search for the Integration it just isn't there. I've restarted my HA instance after the repository but still nothing.

Thanks!

**Comment by eagleguts** [comment]
Ended up just reinstalling HA since it was a new install anyway and that cleared the issue

**Comment by hans-m-song** [comment]
I realised this is closed but I just encountered this issue and solved it by clearing the cache and hard reloading the dashboard on step 6.3.4
