### ISSUE TITLE
Doorbell Trigger

### ISSUE THREAD

**Issue by ethanllewis** [fuatakgun/eufy_security#34]
I'm having issues with enabling an automation that involves the doorbell.

In Configuration>Integrations>Entities I see the `binary_sensor.doorbell_ringing_sensor` and its attributes. When I manually trigger the doorbell, I see the `ringing` attribute turn from `false` to `true` and the sensor turns from `False` to `True`. The issue is when I go to create an Automation, I cannot get the Trigger for [Device] `Doorbell ringing sensor turned on` or [Entity State] `binary_sensor.doorbell_ringing_sensor = true` to fire. 

I've been experimenting and now I can get the Trigger to fire when I use `binary_sensor.doorbell_ringing_sensor` > `to = *`. This is recognizing any chang in the `binary_sensor.doorbell_ringing_sensor` State. The issue now is that the Automation fires any time the doorbell registers a new event (motion detection, person detection, doorbell pressed). This looks to be related to what the integration defines as "Ringing sensor." I assumed that this was when someone physically pressed the doorbell button but maybe that is not the case. 

Any recommendations?

**Comment by ethanllewis** [comment]
Here's the YAML:
`alias: doorbell
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_ringing_sensor
    to: '*'
condition: []
action:
  - service: notify.mobile_app_ethans_iphone
    data:
      title: Doorbell
      message: Someone is at the gate
      data:
        image: /local/eufy.jpg
        actions:
          - action: URI
            title: Open Camera
            uri: /lovelace/test
          - action: DELIVERY
            title: Delivery - Open Gate
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: DELIVERY
    timeout: '00:01:30'
    continue_on_timeout: false
  - service: script.door_buzzer
mode: single
`

**Comment by ethanllewis** [comment]
Here's the YAML:
alias: doorbell
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_ringing_sensor
    to: '*'
condition: []
action:
  - service: notify.mobile_app_ethans_iphone
    data:
      title: Doorbell
      message: Someone is at the gate
      data:
        image: /local/eufy.jpg
        actions:
          - action: URI
            title: Open Camera
            uri: /lovelace/test
          - action: DELIVERY
            title: Delivery - Open Gate
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: DELIVERY
    timeout: '00:01:30'
    continue_on_timeout: false
  - service: script.door_buzzer
mode: single

**Comment by ethanllewis** [comment]
Doorbell entity attributes and state history: 
<img width="386" alt="Screen Shot 2021-08-03 at 11 38 40 PM" src="https://user-images.githubusercontent.com/16548191/128133908-16ab0af1-e769-4bbc-8be8-d0ed6f382323.png">

**Comment by fuatakgun** [comment]
Thanks for detailed issue. Can you double check the state of sensor on developer tools page? I assume you should use `True` and `False` as states not `true` or `false`.

![IMG_20210804_084030.jpg](https://user-images.githubusercontent.com/11085566/128134313-fce10fb0-ebf3-402a-b416-01c69ed03022.jpg)

There should be another way, use device's states, check screenshot below.

![Screenshot_2021-08-04-08-43-18-395_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/128134288-443b2eca-fb5a-43cc-826f-a822cde56d26.jpg)

**Comment by ethanllewis** [comment]
Ok that first part did it. I corrected `false` to `False` and it looks like the Trigger is working now. I will mark this as closed as it's working the way I was hoping. Thank you for the support!!


Another note on the Device state option; I have the 2k battery doorbell and it looks like it has different options than the Motion sensor you posted above. The Device state that i was trying to use previously was `Doorbell ringing sensor turned on`. See screen shot example. I think the issue is what the integration is recognizing as "doorbell ringing" potentially.

<img width="1097" alt="Screen Shot 2021-08-03 at 11 53 19 PM" src="https://user-images.githubusercontent.com/16548191/128136269-9262dcc5-2ae0-44a3-bf20-ec3494eff948.png">

**Comment by fuatakgun** [comment]
Problem with doorbell ring, I could not find a suitable device class for it. Motion Sensors are created as motion sensor, so they are visible as 'motion detected'. For doorbell ring, it is none so, it is visible as changed to true/false. 

But, i missed this part, can you confirm again that device's event for doorbell ring is not acting correctly?

**Comment by ethanllewis** [comment]
Yep, that makes sense. 

Doorbell ring was being picked up in HA when I view the entity BUT the device trigger was not picking up the change of the sensor. I can post more code snippets tomorrow.

**Comment by atv2016** [comment]
@fuatakgun @ethanllewis Can one also adjust the volume of the doorbell using these or other states?

**Comment by fuatakgun** [comment]
> @fuatakgun @ethanllewis Can one also adjust the volume of the doorbell using these or other states?

No, you need to create a separate request for this.

**Comment by atv2016** [comment]
But it’s possible to do it with this integration?
________________________________
