### ISSUE TITLE
Only single instance allowed

### ISSUE THREAD

**Issue by wormiedk** [fuatakgun/eufy_security#341]
**Describe the bug**
Whenever I try to reauthorize the integration I get the error "Only single instance"
![image](https://user-images.githubusercontent.com/4417857/169516704-fa842fa9-3245-49a2-b702-228dc7c281d3.png)
![image](https://user-images.githubusercontent.com/4417857/169517079-06ad851d-ba56-4fac-b7e1-282fd26ae704.png)

**To Reproduce**
1. Go to settings to reauthorize integration
2. Click on configure
3. Enter catch

**Expected behavior**
A working system

**Screenshots**
see above

**Comment by fuatakgun** [comment]
please retest with latest version and comment back here

**Comment by wolfjank** [comment]
Go exactly the same issue :-/

**Comment by zaqlevenick** [comment]
Im having the same issue

**Comment by sythesigh** [comment]
Same issue here, totally removed from system then added back but same problem

**Comment by vedz91** [comment]
same problem

**Comment by vedz91** [comment]
Solution: https://github.com/fuatakgun/eufy_security/issues/293#issuecomment-1118093661

**Comment by sythesigh** [comment]
> Solution: [#293 (comment)](https://github.com/fuatakgun/eufy_security/issues/293#issuecomment-1118093661)

This does not solve it for me, I am using the docker eufy-ws container, so the details are stored there.
