### ISSUE TITLE
Lock has no control

### ISSUE THREAD

**Issue by 203Null** [fuatakgun/eufy_security#342]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
There’s no way to unlock the smart lock T8510. All I have is global motion sensor.

**To Reproduce**
Link the lock, and check the available entitles 

**![ED701105-41B9-4CFB-9A4C-7177DDD2222A](https://user-images.githubusercontent.com/19933093/169754141-e10cfabf-8dd3-4f27-9dd9-80b37f08035a.jpeg)

**Comment by JustDFB** [comment]
I have the same issue since the update in that the entity has become unavailable.
Thank you

**Comment by laxmiprasad7** [comment]
I have the same issue with the lock. No Lock entity is seen in the integration after the update.

**Comment by tech-byte** [comment]
The 2.2.6 update appears to have fixed the T8520 not having a lock control entity in HA. All working again 👍

**Comment by cdnninja** [comment]
@203Null is it working for you now? If so we will close this case.

**Comment by 203Null** [comment]
> @203Null is it working for you now? If so we will close this case.

Fixed, sorry for the late reply. I wasn't at my place during that time and I completely forgot about it until now.
