### ISSUE TITLE
Can't get URL for camera

### ISSUE THREAD

**Issue by eagleguts** [fuatakgun/eufy_security#348]
Hi,

Forgive me if this is simple or if I leave out information. Very new to HA.
I'm getting the following error when trying to add a card for a Eufy Video Doorbell 2k Battery powered. 
It was working fine last night with this same code. Not sure what happened between now and then.

Edit:
I've gone through the fuatakgun configuration steps multiple times and checked configurations. Even deleted and reinstalled integrations. I get camera feed when I add the card as an entity (however the delay is horrible, about 1fps), but when I try to make a card using webrtc it can't find the camera. The rtsptoweb server is set to my HA address. 

![URL Error](https://user-images.githubusercontent.com/105625753/170111780-c6bdf4ac-56c2-46c2-b7a2-d632d0084db8.PNG)

**Comment by wvalko** [comment]
experiencing same, along with api lockouts.

**Comment by TAS1981** [comment]
Did you manage to solve this? Same issue!

**Comment by eagleguts** [comment]
Haven’t solved it yet. Still hoping someone more knowledgeable will save the day!

**Comment by TAS1981** [comment]
What address does your dashboard resources point to?

**Comment by wvalko** [comment]
I changed from True/False in the Dashboard Camera Yaml to On/Off and it
worked.

**Comment by TAS1981** [comment]
I think that's a check box in webRTC, fix state from True/False to On/Off...

**Comment by TAS1981** [comment]
Hi - I think I just got it working. In the Eufy security integration i changed the seconds to analyse from 1.2 to 2 and the streaming popped up!

**Comment by TAS1981** [comment]
Load an entity card for your camera in the dashboard - add the streaming sensor and sensor address lines. Atleast that way you can see if the RTSP address is appearing there when it does stream.

I used a slightly different set of options and it now works intermittently.

Try this thread - you'll need to add Browser Mod - https://community.home-assistant.io/t/eufy-security-integration/318353/242

**Comment by fuatakgun** [comment]
known issue: https://github.com/fuatakgun/eufy_security/issues/287
please continute from there
