### ISSUE TITLE
indoor cameras stopped updating after installing 0.9.1 add-on 

### ISSUE THREAD

**Issue by zadigre** [fuatakgun/eufy_security#350]
Hello Everyone!

it looks like after installing 0.9.1 add-on, my indoor cameras stopped updating status... whenever I arm/disarm, status is not changing in home assistant. 
if I opened the eufy app on my iPhone, status will update. 
if I restart HA, status will update. 
if I restart the add-on and reload integration, status will also update. 
if I restart the whole OS, like restart HA alone, status will update.
in all case when status has been updated after a restart, it will stop updating thereafter. 
it looks like there's no "push" update. 
there's no error in the add-on or supervisor log. 
all was working fine before... not sure why it stopped working now. may be linked to 0.9.1 I just installed since it was working fine before.

**Comment by cdnninja** [comment]
Did you update the integration too?

**Comment by zadigre** [comment]
yes both

**Comment by zadigre** [comment]
that said, I believe it started after installing the add-on... but I'm not 100% sure. 
I remember installing an update, either the integration or add-on. next day, the other one was available. 
but I do remember after installing the first update, it was still working fine.

**Comment by booz1974** [comment]
i got the same issue, and when i roll back the back up its working fine. 
However i cant force it to change status like you I tried restarts of app /integration/addon but status just stays the same while in the eufyapp the changes are made.

**Comment by zadigre** [comment]
just to add more info on this... 

the arm/disarm services are still working fine even if status is not updated. 

I also have Eufycam 2 Pro... those works as usual (status is updated immediately). 
I've found that as soon as I receive a notification on my Eufucam 2 Pro, no matter what is the notification, status on my indoor cameras will also be updated at the same time. 
For example, the mailman just came to my door. I received a motion notification from my Eufycam 2 Pro. on my indoor cameras, which was still showing as disarmed since 8am this morning, switched to armed away status after I received this notification from eufycam 2 pro.

**Comment by zadigre** [comment]
also fyi, the eufy security force sync does absolutely nothing to "fix" this issue.

**Comment by fuatakgun** [comment]
I am using `indoor camera pan&tilt" and I can see that sync is working fine in two ways;
- if I change the guard mode on HA, it is synced into eufy app after couple of seconds
- if I change the guard mode on eufy app, it is synced to HA after couple of seconds
All these communications are handled by push notifications, 

Can you retest with latest add-on version?
