### ISSUE TITLE
Initial Setup - Failed to request

### ISSUE THREAD

**Issue by dorbiism** [fuatakgun/eufy_security#355]
After installing and configuring the Add-On I get the following:

![Error_01](https://user-images.githubusercontent.com/105241372/171923153-08ea384c-43d6-428a-8b97-8be1fd3abd43.PNG)

**Comment by blfriedman** [comment]
I get the same error - also just after installation.

**Comment by blfriedman** [comment]
> I was having issues using the account I shared the devices to. It works fine with my main account however.

I get that error on both accounts - the main one and the one I shared the device to.

**Comment by Gtt1229** [comment]
> > I was having issues using the account I shared the devices to. It works fine with my main account however.
> 
> I get that error on both accounts - the main one and the one I shared the device to.

Ah, I see, on my side, my integration for my live feed was not so hot with my doorbell, so now I just get `INFO  Eufy Security server listening on host 0.0.0.0, port 3000 ` for the add-on, so.

**Comment by dorbiism** [comment]
> > I was having issues using the account I shared the devices to. It works fine with my main account however.
> 
> I get that error on both accounts - the main one and the one I shared the device to.

Same here. Have tried Admin/View permissions on the accounts as well.

**Comment by Canyonfive** [comment]
Having the same issue.

**Comment by ncary** [comment]
I am having this same issue

**Comment by fuatakgun** [comment]
Please log-in using your new account in respective mobile app to validate that new account has full access to all shared devices. If the issue still persists, creating a new account also solved it many times. If you still have the issue, please create an issue over here: https://github.com/bropat/eufy-security-client.

There is nothing I can help here.

**Comment by blfriedman** [comment]
After I created a new account, the problem disappeared.  Thanks for that tip.
