### ISSUE TITLE
Clarification when running HA under Docker on Synology

### ISSUE THREAD

**Issue by gregf888** [fuatakgun/eufy_security#359]
Just sharing some setup info that took me a while to work out.  I am running HA using Docker on a Synology NAS.  After installing the bropat/eufy-security-ws docker image I had to add three variables for username, password and timezone.  Suggest add this to your excellent documentation.

![image](https://user-images.githubusercontent.com/71629711/172525340-b0eb42e5-00dd-48d5-a02f-b8b930fbdcd9.png)

**Comment by gerardsyd** [comment]
Hi Greg - did you get this to work through docker? Eufy-security-ws doesn't seem to find my home base / eufycam even though I can see the logs and it says it's listening

**Comment by gregf888** [comment]
Yes its working fine for me.

***@***.***

I’m using motion detection to turn on the lights when I come home and that’s working.

**Comment by fuatakgun** [comment]
thanks for your response @gregf888

**Comment by hipsi** [comment]
@gregf888 are you using this with the Eufy security system?  I am running on Synology Docker also and hoping I can find someone else in the same boat as me.

**Comment by gregf888** [comment]
Yes @hipsi running on Synology Docker.  It finds two devices "Doorbell" model T8210 and "Homebase2" model T8010 there are 25 entities.  It has been rock solid since installation.

**Comment by hipsi** [comment]
Ahh but not using the security system. That's cool. I'm looking for some guidance with the events generated by those devices, and having trouble understanding if I'm the only one facing the issues I've had with the latest 2 versions.
