### ISSUE TITLE
HACS takes a long time to startup

### ISSUE THREAD

**Issue by dpomnean** [fuatakgun/eufy_security#36]
I know this has been mentioned before but will put this in an issue to track. When I restart HA, I will tail the logs with 
```docker logs --follow [container_id]``` and am noticing this error is consistent when I start up HA. It seems like it is timing out after this error, which eventually allows HACS to start up.

```
2021-08-05 00:12:15 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up eufy_security platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 47, in async_setup_entry
    entities.append(EufySecurityAlarmControlPanel(hass, coordinator, entry, entity))
  File "/usr/local/lib/python3.8/typing.py", line 873, in __new__
    obj = super().__new__(cls)
TypeError: Can't instantiate abstract class EufySecurityAlarmControlPanel with abstract methods supported_features
2021-08-05 00:17:21 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap - moving forward
```

**Comment by fuatakgun** [comment]
I believe you mean hass or home assistant, rather than hacs

**Comment by dpomnean** [comment]
No I mean HACS. I've noticed the ui will try to load HACS but takes much longer to load. I think this has been an issue for awhile

**Comment by fuatakgun** [comment]
By the way, issue is not specifically impacting HACS, it can impact any other integration which requires initialization at startup time. I have a side effect on my garage door, it is not ready for first one minute.

**Comment by dpomnean** [comment]
Yeah I agree, I noticed it is not impacting HACS from working so this is a low priority issue. Just wanted to open an issue for tracking.

**Comment by fuatakgun** [comment]
thanks for following up, agree on assessment on its severity but if i restart WS addon while startup, it quickly gets resolved.

So, while starting up, integration seems to be communicating with add-on but keeping the connection open (or not able to close gracefully) and HA thinks that startup is taking so long.

On the other hand, I was not able to find the root cause yet.

**Comment by true-bluey** [comment]
I *seem* to have the same issue - not specifically related to HACS, but eufy Integration holding up start up. After 5 mins I get a message:

`Setup timed out for bootstrap - moving forward`

**Comment by true-bluey** [comment]
> I _seem_ to have the same issue - not specifically related to HACS, but eufy Integration holding up start up. After 5 mins I get a message:
> 
> `Setup timed out for bootstrap - moving forward`

This is still happening in the latest release (2021.9.0). Reach out if you want to troubleshoot.

**Comment by fuatakgun** [comment]
I still don't know the underlying root cause for this but if i restart eufy add on while this is happening, it gets resolved immediately. I believe, this is either related to add on configuration or integration initialization. 

Still investigating

**Comment by true-bluey** [comment]
Not sure if it’s related, however I noticed the docker container doesn’t start on HA start like the other addons do. There’s nothing untoward in the logs that I can see but happy to poke around if you’d like.

**Comment by derekoharrow** [comment]
Just to add to this - I also see this behaviour. With the eufy security integration enabled (via HACS), my HASS startup is delayed by 5 minutes! Disabled the eufy security add-on and everything is back to normal, with startup taking just a minute or two.

**Comment by skank01** [comment]
Same here, with the integration enabled , it loads way slower

**Comment by true-bluey** [comment]
With the latest release (59d1424) I get new messaging but same general behaviour. Not sure if this is helpful:

![image](https://user-images.githubusercontent.com/54353376/134258546-ae89e213-97fb-4ed5-b28e-dff159e4832c.png)

**Comment by jonwilliams84** [comment]
+1 - hass takes upwards of 3-5 minutes to start once the integration is enabled.

**Comment by derekoharrow** [comment]
This still seems to be an issue - any idea what the issue is or any sight of a fix?

**Comment by fuatakgun** [comment]
I found the root cause of `overall long HA startup time` but still working on solution.

**Comment by mattstocum** [comment]
The issue seems to be related to EufySecurityWebgSocket.process_messages(). Turning on DEBUG logging on homeassistant.core results in a number of messages like this `2021-09-30 10:53:55 DEBUG (MainThread) [homeassistant.core] Waited 240 seconds for task: <Task pending name='Task-746' coro=<EufySecurityWebSocket.process_messages() running at /config/custom_components/eufy_security/websocket.py:65> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9a5db88b20>()]> cb=[EufySecurityWebSocket.on_close()]>`. Eventually HASS gives up on waiting and proceeds with the startup.

**Comment by fuatakgun** [comment]
yep, you are right @mattstocum , I need to fetch the current state while initialization of integration.

For future processes, I should implement disconnect/reconnect feature so startup can finish in timely manner.

On the other hand, this is not creating any issues other than bugging message, so I did not focus on this a lot.

**Comment by fuatakgun** [comment]
Yep, you are right, there is also that one :-)

Still, i am looking for a good solution rather than a dirty one as disconnect/connect :-)

**Comment by fuatakgun** [comment]
finally, fixed :) https://github.com/fuatakgun/eufy_security/commit/23a3a008d824c3a60775055dffa3f2e647500738
