### ISSUE TITLE
Entry sensors not updating

### ISSUE THREAD

**Issue by Asgorath777** [fuatakgun/eufy_security#360]
Update: When I turn on notifications on the Entry Sensors in the Eufy App the logbook fills again. Before this did not have to be set to see the open/closed status (it was based on whenever to the cloud Interval was set that it saw it).

---

Setting all the notifications to on is imho a bit of a work-around as now the Eufy app send a LOT of notifications.

First ever time reporting an issue, so hope I did it alright. If information is missing or anything please let me know.

A few weeks ago I noticed one or two contact/entry (door/window) sensors no longer updating their status in Home Assistant. The sensor in HA indicated that a windows was open, while it was closed and the Eufy app also indicated that the window was closed. About a week ago all contact sensors stopped updating. All showcasing that they are closed. When checking in the Eufy app they clearly show correct and have a log of their open/close actions.

The Eufy doorbell and Camera also in the system do seem to report correctly (i.e. if someone rings the doorbell HA still gets the update). I can also still arm and disarm the system using HA. The only thing effected seem to be contactsensors.

I checked the logfiles and initially found errors that seemed to indicate connection issues. Solving these issues (Pihole blocking access it seems) resolved the errors in the logfile, but no change to the contact-sensors. They do not update, while camera and doorbel keep working. 

As I did not notice it immediately I do not know from which version onward this started to happen. The Eufy Security Addon is on version 0.9.1. The HACS Addon version 2.2.6. 

Config of the integration:
Cloud Interval is set to 500
IP address to 'localhost'
Port to 8554
Video analyse to 1
Autostream not checked, Fix binary sensors checked, Map custom guardmodes checked and two entered.

Sensors are used in custom Dashboard (mainly using Mushroom cards) and does not update. 
Two template sensors  in the system to count the number of doors and windows open

`
sensor:
  - platform: template
    sensors:
      all_open_windows:
        friendly_name: "All open windows"
        value_template: "{{ states.binary_sensor | rejectattr('attributes.device_class', 'undefined') | selectattr('attributes.device_class', 'eq', 'window') | selectattr('state', 'eq', 'on') | list | count }}"

` 
and
`
sensor:
  - platform: template
    sensors:
      all_open_doors:
        friendly_name: "All open doors"
        value_template: "{{ states.binary_sensor | rejectattr('attributes.device_class', 'undefined') | selectattr('attributes.device_class', 'eq', 'door') | selectattr('state', 'eq', 'on') | list | count }}"
`
Both always return '0'.

Sensors used in various Node-red automatons to check if windows or doors are open. Automations do not trigger anymore (always closed).

No real steps I can describe to cause it. Logbooks are are simply 'empty' and no status changes anymore. 

**Hardware Information about Home Assistant
Raspberry Pi 4 Model B - 8GB - SSD instead of SD card.

**Additional context**
Entry Sensors, Firmware 0.1.0gb, Hardware 0.0.1
Using a secondary account, added to the family group within Eufy, does not have admin rights within Eufy. Account is a gmail account (noticed account got a warning that 2 factor is turned off and it should create app specific passwords when recently logging into it, currently using the actual password of the account, not an app specific password).

Adding two screenshots of one sensor attached to a window that has been open multiple times in the last few weeks. First of last week, second of this weeks entries.

![Screenshot 2022-06-08 at 23 36 27](https://user-images.githubusercontent.com/74931832/172721747-9a51592a-3ed1-46bb-87cf-43ed741c67a3.png)
![Screenshot 2022-06-08 at 23 36 39](https://user-images.githubusercontent.com/74931832/172721778-e38a0da3-1c5d-45c1-9f5a-b44e98768e62.png)

**Comment by mycrouch** [comment]
I'm having the same issue. I can see all my contact and motion sensors. However, they don't update. When I restart HA the status is gathered and then they don't change.

The logs show when the panel is set to armed etc, but no status changes for sensors.

**Comment by fuatakgun** [comment]
you have to enable all notifications, there is no other solution. This integration and add-on fully relies on push notifications and if you want, you can trigger manual cloud updates (it is also happening every 10 minutes based on your integration configuration)

**Comment by Asgorath777** [comment]
The 10 minutes (or 5 in my case) doesnt work anymore however. That was/is the problem.

**Comment by fuatakgun** [comment]
Got it, so you are not interested in notification based solution, right?

**Comment by Asgorath777** [comment]
It means the Eufy app pushes a notification to ones phone for every door and window open/closed in the house unless you turn all notifications off (so also notifications of the alarm and doorbell). Before it would go for the cloud interval. Which isn't instant but it worked well enough. I've installed the new update and the cloud pull doesn't update the entry sensors anymore. Like other things. So in that sense I think this is a duplicate report.

Oh and it would be great to depend on the direct notification/push by Eufy. Sadly not being able to indicate one doesn't want a push notification in the eufy app of every door open/close but you do want one of the doorbell bring pressed or the alarm going off isn't an option. That's of course fully on Eufy. Exceptionally happy this integration existst!

**Comment by Asgorath777** [comment]
It seems Entry sensors do not have that option sadly (on iOS at least). Else it would be a great work around to get direct notifications. Again something on Eufy, not this integration.

Should this issue be closed as it's probably the same as other devices not updating though the cloud interval?

**Comment by fuatakgun** [comment]
Btw, other user reported that add-on version of 0.8.1 was working perfectly for him, can you also validate this on your end?

**Comment by Asgorath777** [comment]
Going to test that tomorrow as its quite late here now.

**Comment by thewolf-oz** [comment]
There was no change after the latest update which appeared overnight here

I'm also using iOS so enabling notifications is a non-starter for me too :(

**Comment by Asgorath777** [comment]
> Btw, other user reported that add-on version of 0.8.1 was working perfectly for him, can you also validate this on your end?

Can I ask a dumb question as I've never actually done that. How do I revert back to 0.8.1 to test? Uninstall the integration and reinstall an older version (if so, would it disrupt any automations or anything? - then I need to run a backup to test).

**Comment by fuatakgun** [comment]
Please update both integration and add-on, inform back us here

**Comment by jouster1974** [comment]
I'm on the latest integration (2.2.6) and add in (0.9.2), still same issue

**Comment by jouster1974** [comment]
this now looks to be working with the latest intergation and add on...some small issues with delays on some alarm status being changed over but continuing to ttest

**Comment by tectaassociates** [comment]
Experiencing the same issue. Had some underlying HA issues so had to reinstall HAOS. I used to have an automation that would turn off the lights, set the thermostat and turn off the TVs when Eufy alarm was set to away, but now the status will not update so HA doesn't know what the status is and the polling doesn't work UNLESS you change the interval and then it will poll the status one time.

**Comment by fuatakgun** [comment]
try with latest version please

**Comment by fliespl** [comment]
I have 0.9.4 and can confirm a few issues:
- cameras are working correctly
- entry sensors are in the state when ha started subsequent changes do not make them change.

I am relying solely on cloud update functionality (no pushes for other things than alarm state - and it's working proprly):

```
2022-08-15 18:56:46.780  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-08-15 18:56:48.472  INFO  Connected to station T8001H2318390905 on host 192.168.88.3 and port 23229 
2022-08-15 18:56:57.062  INFO  Push notification connection successfully established 
2022-08-16 10:09:03.755  INFO  Alarm mode for station T8001H2318390905 changed to: AWAY 
2022-08-16 10:24:14.339  INFO  Push notification token is expiring, renew it. 
2022-08-16 10:24:16.471  INFO  Push notification connection successfully established 
2022-08-16 11:23:58.650  INFO  Alarm mode for station T8001H2318390905 changed to: HOME 
2022-08-16 16:32:29.567  INFO  Alarm mode for station T8001H2318390905 changed to: AWAY 
2022-08-16 16:55:37.122  INFO  Alarm mode for station T8001H2318390905 changed to: HOME 
```

**Comment by fliespl** [comment]
Just did another test. Enabled notifications on one entry sensor. They came properly in eufy app, but fail to show in HA logbook.

If required, I will be happy to share device and do debug session (teams/google/slack/skype or other).

**Comment by hanseandersson** [comment]
I have the same problem.. one sensor is hauling to update is status and getting stuck on open when though eufy is showing it as closed..

**Comment by googanhiem** [comment]
I've got this issue. About 50% of the time the state doesn't change on my entry sensor. tried reinstalling, changing notification settings (android/ios) and changing sync interval. No improvement. 

@fuatakgun any chance for a force sync service command as a temporary fix? or updating the backend library to see if that helps.

**Comment by gboxxx** [comment]
Same issue here, cannot get entry sensors to update even after enabling notifications, force_sync, changing interval, binary sensor fix in configuration, etc.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591

**Comment by googanhiem** [comment]
I actually did a little more digging on this recently. It regularly gets stuck "open", and looking through the code (this and Bropat's client) it looks like it searches for an open state not a closed state via push/http. 

This seems like a small difference but I'm wondering whether this is causing closed states to get missed if there are issues (the sensor in question doesn't always have the best connectivity, and I'm running this on a pi 3b+ which can be a little laggy). In most cases this issue can only be fixed by an open->closed event being triggered.

Then again I don't know what I'm talking about and could be way off.

**Comment by fuatakgun** [comment]
can you please post code pointers?

**Comment by googanhiem** [comment]
So this is what I found in the [bropat's devices.ts](https://github.com/bropat/eufy-security-client/blob/master/src/http/device.ts) line 2178:
`public processPushNotification(message: PushMessage, eventDurationSeconds: number): void {
        super.processPushNotification(message, eventDurationSeconds);
        if (message.type !== undefined && message.event_type !== undefined) {
            if (message.event_type === CusPushEvent.DOOR_SENSOR && message.device_sn === this.getSerial()) {
                try {
                    if (message.sensor_open !== undefined) {
                        this.updateRawProperty(CommandType.CMD_ENTRY_SENSOR_STATUS, message.sensor_open ? "1" : "0");
                    }
                } catch (error) {
                    this.log.debug('CusPushEvent.DOOR_SENSOR - Device: ${message.device_sn} Error:', error);
                }
            }
        }
    }`

while also your code seems to look for this "sensor_open" command in the binary_sensor python.

**Comment by fuatakgun** [comment]
From code perspective, it looks logical.

While you are right on variable naming, sensor can only have 2 states, open and close. Open equals to 1 and close equals to 0.

**Comment by googanhiem** [comment]
Makes sense, again I have no idea what I'm talking about. 
Is there any way to have it poll a second time after a set period of time to avoid possible missed events?
Other smart home services (google home and Alexa seem to be able to reliably track the state.. so I don't think it's a weakness of the sensor/api)
