### ISSUE TITLE
Alarm Delay Event from Latest bropat/eufy-security-client Update

### ISSUE THREAD

**Issue by pldmgg** [fuatakgun/eufy_security#363]
I desperately need an alarm delay event exposed in HA for my Eufy HomeBase2 in Home Assistant. I noticed that in bropat/eufy-security-client Changelog 2.1.0 (https://github.com/bropat/eufy-security-client#210-2022-06-12), they actually created an event for this.

What is the usual timeline for this eufy_security HA add-on to get updated using the latest bropat/eufy-security-client ?

**Comment by fuatakgun** [comment]
I had just updated it, but you also need an event for this, right?

**Comment by pldmgg** [comment]
Yes please :)

**Comment by fuatakgun** [comment]
just updated the integration now, alarm station will be in `delayed` state for 1 sec when the event is received and return to previous state. As delayed event does not change the state, I preferred this way. Test with new version and comment back if you have issues

**Comment by pldmgg** [comment]
Just tested several times by:

- Switching my alarm_control_panel.homebase_2 from armed_home to armed_away 3 different ways: via my keypad, via clicking Away mode in the Eufy App, and via alarm_control_panel.alarm_arm_away. The state always just flips immediately from armed_home to armed_away without the interim "delayed" state
- So then I wanted to test to see if the "delayed" state would appear upon returning home when the alarm is in the armed_away state.
- When I returned home, the 30 seconds of alarm delay started counting down. The state remained armed_away
- I let the alarm actually go off and the state changed to "triggered"

So I never see a state "delayed" in the scenarios I tested. But maybe I'm misunderstanding how you implemented this? Maybe I should be looking at an attribute or something instead of state?

**Comment by hipsi** [comment]
Thank you @fuatakgun, I can't wait to test this. It actually sounds like the perfect implementation to me. I have no need to know if it's in a delayed state, I just need to know when it's in an alarm state so I can sound the siren.  What I'm curious to find out in my testing is whether the triggered state remains until it is reset or disarmed.  If not (eg, if it only shows triggered momentarily), I would need to find a way to know that the alarm has been reset (for example when you reset it from the Eufy app).

**Comment by pldmgg** [comment]
@hipsi In my testing, is only stays "triggered" momentarily. Also, if you switch from armed_away to armed_home while the alarm is actually going off, it momentarily switches to "triggered" again and then settles to armed_home. These are all unrelated to this thread though. This thread is specifically about having something that indicates when the system is in alarm delay either on your way out the door or when you just get home.
