### ISSUE TITLE
muitple eufy products status not changing unless refreshing via Eufy app

### ISSUE THREAD

**Issue by jouster1974** [fuatakgun/eufy_security#364]
since I got my Eufy Homebase I had setup automation to set the state of all my other Eufy products when the Homebase state was changed...ie from Home Arm, Home Away etc.....it all worked fine and was a great way of me getting the system working vai Home Assistant as a whole home alarm/camera system (and better than the Eufy app allowed with wired cameras in the mix)

However, this no longer seems to work as it did...now when changing the status of the Homebase, regardless of doing so on the keypad, the app, or an automation/button on HA, on the Homebase state changes...but once you go into the app and then refresh the security page, then the state of all the other security devices updates and then it updates in HA...so something has changed somewhere

Love to know what I could do to get this back to how it was before

**Comment by cdnninja** [comment]
In your eufy add on config file could you switch the version to 0.9.2?  I am interested if this solves it.

**Comment by cjeri** [comment]
Issues #350 and #347 appear to be the same as this one. Multiple people are reporting the same problem but there’s been no feedback

**Comment by Asgorath777** [comment]
#360 is probably also the same issue.

**Comment by cdnninja** [comment]
I believe this issue is solved in the newer version of the base integration.  I don’t know eufy security products but have merge access to this repo. 

In the eufy security add on a json file exists as mentioned before. It lists a version that needs to be bumped that will automatically pull the new bropat integration which may fix this.  If it does I can get that bumped and deployed but want someone to test first. 

I’m not by a computer to be able to provide better detail.

**Comment by cdnninja** [comment]
This is where I think it is fixed. 

https://github.com/bropat/eufy-security-client/issues/161

**Comment by cdnninja** [comment]
Example of bumping version. https://github.com/fuatakgun/eufy_security_addon/commit/5271f86fd2e75161aabf160163645982d832e78a

**Comment by jouster1974** [comment]
im curring Core, running ion a standalone rig and cant find this file anywhere

**Comment by cdnninja** [comment]
I would think need to browse the file system to edit it. 

Maybe I chance it and bump the version and we can test quickly.

**Comment by jouster1974** [comment]
im in front of PC for next few hours so cant test anything you like

**Comment by jouster1974** [comment]
fyi  changing the version in the config.json on the locally installed addon didn't change anything

**Comment by Asgorath777** [comment]
Willing to test, but not sure where I can find the config.json file (or any files of the addon actuall).

**Comment by fuatakgun** [comment]
I had updated the add-on and released it couple of minutes ago, please re-test after updating your add-on

**Comment by booz1974** [comment]
updated to 0.9.2 restarted everything but still no statusupdate

**Comment by Asgorath777** [comment]
Also updated and restarted. Waited for for the set period to expire but still no update on the Entry sensors anymore. Continue to only happen with push notifications turned on and not through the cloud scan.

**Comment by fuatakgun** [comment]
if you are asking from integration perspective, check readme, if you are interested in add on debug logs, check eufy-security-ws repository to find out enabling debug logs but it is not feasible as an home assistant add-on

**Comment by fuatakgun** [comment]
Hmmm, then we should bring this into eufy-security-ws repository owner, @bropat attention. Can you create a issue and link here?

**Comment by booz1974** [comment]
eueeh... im really new in this github forrest, what i need to do?

**Comment by jouster1974** [comment]
as per #360   with the latest version of integration and add-on, things now seem to be working again...some small niggles but will continue to test
