### ISSUE TITLE
Media library -> Play Media - only opens popup

### ISSUE THREAD

**Issue by fliespl** [fuatakgun/eufy_security#366]
**Describe the bug**
I am pretty positive I have followed instructions properly (but still - lots of stuff :) ) I managed to play stream on dashboard on click, so maybe media screen is not supported yet?
https://ss.codeone.pl/ss-2022-06-17-09-06-55-1655449615-n58n2wAy.png
https://ss.codeone.pl/ss-2022-06-17-09-07-19-1655449639-BPRzlVa5.png

**To Reproduce**
1. Go to 'Media library'
2. Click on random camera play button
3. See popup instead of stream

**Expected behavior**
RTSP Stream to start

**Hardware Information about Cameras
- eufy t8111
- tried both rtsp & p2p

Keep up the great work!

**Comment by fuatakgun** [comment]
this is a known and old issue: https://github.com/fuatakgun/eufy_security/issues/257

I have not used media library, I rely on `WebRTC` for lovelace views but it is not supported by media library. Please track the first issue but it has very low priority.

**Comment by fliespl** [comment]
@fuatakgun thanks! I have used search but totally missed this one :)
