### ISSUE TITLE
RTSP error - 2k Wired Doorbell

### ISSUE THREAD

**Issue by conorlap** [fuatakgun/eufy_security#37]
**Describe the bug**
Errors when trying the ALPHA RTSP Simple Server setup instead of P2P. 

**Hardware Information about Cameras
- Camera Model: T8200
- Live Streaming Protocol: P2P via RTSP server in docker 

**ffmpeg log:**

`ffmpeg started on 2021-08-05 at 10:26:52
Report written to "ffmpeg-20210805-102652.log"
Log level: 48
Command line:
/usr/bin/ffmpeg -y -probesize 128 -analyzeduration 0 -protocol_whitelist pipe,file,tcp -f h264 -i - -vcodec copy -protocol_whitelist pipe,file,tcp,udp,rtsp,rtp -hls_init_time 2 -hls_time 2 -hls_segment_type mpegts -hls_playlist_type event -hls_list_size 5 -preset ultrafast -absf aac_adtstoasc -g 15 -sc_threshold 0 -fflags genpts+nobuffer+flush_packets -loglevel debug -report -f rtsp -rtsp_transport tcp rtsp://192.168.0.22:8554/eufy_security-T8200NXXXXXXXXX
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (Alpine 10.2.1_pre1) 20201203
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --enable-vulkan --enable-libsoxr --enable-libaom --disable-debug
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Splitting the commandline.
Reading option '-y' ... matched as option 'y' (overwrite output files) with argument '1'.
Reading option '-probesize' ... matched as AVOption 'probesize' with argument '128'.
Reading option '-analyzeduration' ... matched as AVOption 'analyzeduration' with argument '0'.
Reading option '-protocol_whitelist' ... matched as AVOption 'protocol_whitelist' with argument 'pipe,file,tcp'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'h264'.
Reading option '-i' ... matched as input url with argument '-'.
Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'copy'.
Reading option '-protocol_whitelist' ... matched as AVOption 'protocol_whitelist' with argument 'pipe,file,tcp,udp,rtsp,rtp'.
Reading option '-hls_init_time' ... matched as AVOption 'hls_init_time' with argument '2'.
Reading option '-hls_time' ... matched as AVOption 'hls_time' with argument '2'.
Reading option '-hls_segment_type' ... matched as AVOption 'hls_segment_type' with argument 'mpegts'.
Reading option '-hls_playlist_type' ... matched as AVOption 'hls_playlist_type' with argument 'event'.
Reading option '-hls_list_size' ... matched as AVOption 'hls_list_size' with argument '5'.
Reading option '-preset' ... matched as AVOption 'preset' with argument 'ultrafast'.
Reading option '-absf' ... matched as option 'absf' (deprecated) with argument 'aac_adtstoasc'.
Reading option '-g' ... matched as AVOption 'g' with argument '15'.
Reading option '-sc_threshold' ... matched as AVOption 'sc_threshold' with argument '0'.
Reading option '-fflags' ... matched as AVOption 'fflags' with argument 'genpts+nobuffer+flush_packets'.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Reading option '-report' ... matched as option 'report' (generate a report) with argument '1'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rtsp'.
Reading option '-rtsp_transport' ... matched as AVOption 'rtsp_transport' with argument 'tcp'.
Reading option 'rtsp://192.168.0.22:8554/eufy_security-T8200NXXXXXXXXX' ... matched as output url.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option y (overwrite output files) with argument 1.
Applying option loglevel (set logging level) with argument debug.
Applying option report (generate a report) with argument 1.
Successfully parsed a group of options.
Parsing a group of options: input url -.
Applying option f (force format) with argument h264.
Successfully parsed a group of options.
Opening an input file: -.
[h264 @ 0x7fae2c279000] Opening 'pipe:' for reading
[h264 @ 0x7fae2c279000] Before avformat_find_stream_info() pos: 0 bytes read:29741 seeks:0 nb_streams:1
[h264 @ 0x7fae2c26aa00] non-existing PPS 0 referenced
[extract_extradata @ 0x7fae2c26f080] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
[h264 @ 0x7fae2c26aa00] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
[h264 @ 0x7fae2c26aa00] non-existing PPS 0 referenced
[h264 @ 0x7fae2c26aa00] decode_slice_header error
[h264 @ 0x7fae2c26aa00] no frame!
[h264 @ 0x7fae2c279000] Probe buffer size limit of 128 bytes reached
[h264 @ 0x7fae2c279000] Stream #0: not enough frames to estimate rate; consider increasing probesize
[h264 @ 0x7fae2c279000] decoding for stream 0 failed
[h264 @ 0x7fae2c279000] Could not find codec parameters for stream 0 (Video: h264, 1 reference frame, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[h264 @ 0x7fae2c279000] After avformat_find_stream_info() pos: 30765 bytes read:62509 seeks:0 frames:1
Input #0, h264, from 'pipe:':
  Duration: N/A, bitrate: N/A
    Stream #0:0, 1, 1/1200000: Video: h264, 1 reference frame, none, 25 tbr, 1200k tbn, 50 tbc
Successfully opened the file.
Parsing a group of options: output url rtsp://192.168.0.22:8554/eufy_security-T8200NXXXXXXXXX.
Applying option vcodec (force video codec ('copy' to copy stream)) with argument copy.
Applying option absf (deprecated) with argument aac_adtstoasc.
Applying option f (force format) with argument rtsp.
Successfully parsed a group of options.
Opening an output file: rtsp://192.168.0.22:8554/eufy_security-T8200NXXXXXXXXX.
Successfully opened the file.
[rtsp @ 0x7fae2c279600] dimensions not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)

[AVIOContext @ 0x7fae2c282000] Statistics: 62509 bytes read, 0 seeks
`

**Simple RTSP Server Log:**

`
2021/08/05 09:27:16 I [0/0] [RTSP] [conn 192.168.0.22:50020] opened
2021/08/05 09:27:16 I [0/0] [RTSP] [conn 192.168.0.22:50020] ERR: no one is publishing to path 'eufy_security-T8200NXXXXXXXXX'
`

**Comment by fuatakgun** [comment]
can you double check your live streaming quality? if it is high, try with medium or low.

**Comment by conorlap** [comment]
It was set to Auto, I changed to Medium and Low but same issues

**Comment by oischinger** [comment]
I have the same issue.
I assume it's a T8200N issue. I have the same one

**Comment by fuatakgun** [comment]
You can follow troubleshooting section and share your camera with one of testing accounts and i can debug

**Comment by conorlap** [comment]
I've shared my doorbell with you, many thanks :)

**Comment by fuatakgun** [comment]
All seems fine when I tested locally. I was able to live stream your doorbell. One major thing, have you tried to stop the live stream and start again?

**Comment by conorlap** [comment]
I restarted home assistant and it seems to be fine now :) Working better than ever!! 
Thank you for your great work!
