### ISSUE TITLE
Indoor Chime switch for Doorbell Slim (T8220-Z) not working

### ISSUE THREAD

**Issue by GMTA** [fuatakgun/eufy_security#373]
The Eufy Doorbell Slim (T8220-Z) is working pretty well with the Eufy Security integration; however, the indoor chime switch is always turned off and will not turn on, regardless of the actual state of the switch in the Eufy app.

Other switches such as Auto Night Vision _do_ work.

**Comment by fuatakgun** [comment]
yes, I remember this issue, you have to bring this to `eufy-security-ws` repository as commands are not acknowledged at that end.

**Comment by GMTA** [comment]
@fuatakgun I'm not a direct user of the `eufy-security-ws` library, would they appreciate an upstream issue as a user of your integration? And can I generate a log of the commands that fail for example?

**Comment by fuatakgun** [comment]
Eufy add-on is just a home assistant wrapper of eufy security ws, @bropat (repository owner) is aware of this :-)

**Comment by fuatakgun** [comment]
did you create this issue on its end?

**Comment by GMTA** [comment]
> did you create this issue on its end?

No I have not yet been able to do so, because the entire `bropat/eufy-security-ws` Docker image stopped being able to connect to Eufy since I reported this issue. I'll close this issue for now and when I get the connection back up and running, I'll create the upstream issue.

Thanks for helping!
