### ISSUE TITLE
Simple alarm-panel card

### ISSUE THREAD

**Issue by alanmilinovic** [fuatakgun/eufy_security#375]
Hi I want to use alarm-panel card with 2 buttons, Schedule and Disarm. I do not understand what needs to be done to have it. 

There are some custom stuff that can be configured but not sure how and where, it is very confusing and not a single example how someone did it with custom service or what ever is needed. So far I only see how to do it with arm home and arm away and night, vacation and bypass that throw error.

**Comment by alanmilinovic** [comment]
Do I need to create custom script to have Schedule in alarm-panel?

**Comment by Khaled-Hamad** [comment]
when adding alarm-panel card, there is only options for home, and away (arm-home, arm-away).
if we need to add another option for geofencing, or schedule
![image](https://user-images.githubusercontent.com/25899572/177001944-67efc33f-fc35-4aac-8a92-9cab7369d360.png)

**Comment by alanmilinovic** [comment]
> I've the same issue when adding alarm-panel card, there is only options for home, and away (arm-home, arm-away). if we need to add another option for geofencing, or schedule ![image](https://user-images.githubusercontent.com/25899572/177001944-67efc33f-fc35-4aac-8a92-9cab7369d360.png)

I guess there is some configuration missing from our side and documentation is not that detailed. Maybe someone reply with some detailed description.

**Comment by fuatakgun** [comment]
Geofencing or schedule are nor actually a valid mode, they are conditions to switch between modes.

When you set geofencing, the mode is either armed, home or disarmed but geofencing is responsible to switch between them. It is similar using automations in home assistant

**Comment by alanmilinovic** [comment]
So it is not possible to have it as a card for schedule or geofencing?

**Comment by fuatakgun** [comment]
Let's ask the question other way around, how would you represent geofencing mode in home assistant?

**Comment by alanmilinovic** [comment]
I just want to have 2 buttons that I can use to switch from disarmed to schedule mode and vice versa.

**Comment by fuatakgun** [comment]
Thennn, just setup 2 buttons on front end and call respective services :-)

```eufy_security.alarm_guard_schedule```

```eufy_security.alarm_guard_geo```

**Comment by fuatakgun** [comment]
But as i described earlier, scheduled is not an actual state, it is a rule config to set the state automatically, so you won't see it here. You can only see real states as disarmed, armed away, armed home and 3 more custom states.

**Comment by fuatakgun** [comment]
I will create a new sensor to expose the rule state as None, Schedule or Geofencing

**Comment by alanmilinovic** [comment]
> I will create a new sensor to expose the rule state as None, Schedule or Geofencing

Hi, any news?
