### ISSUE TITLE
Eufy does not show in the integration list

### ISSUE THREAD

**Issue by macnet1** [fuatakgun/eufy_security#377]
I have the Eufy Security Doorbell Camera and have followed to the letter the instructions for the add on into HA, however all is well until I go to add the integration and Eufy does not show in the integration list. The enclosed screen shot is how it 'should' show in the drop down but it does not - this screenshot was taken from another site

Cheers :)
Mark

![image](https://user-images.githubusercontent.com/44956909/176805334-17974a58-960e-4757-a8f1-89d6d244fa30.png)

**Comment by oliversweb** [comment]
I think now you need to add `eufy_security:` in the `config.yaml`, then restart and it should appear.

**Comment by macnet1** [comment]
@oliversweb Billy you are a true legend my friend I out this in just now and BOM !  It works like a charm - Cheers for your help you made my day :)

**Comment by sindbera** [comment]
@oliversweb - I've run into the same issue, and I think I'm doing this wrong. I open `/config/configuration.yaml` using the file editor. I just added `eufy_security:` - at the end, saved and restarted HA. Still no Eufy to be found.

I bet there is more to this, so I'd love to hear where in the .yaml, I should add this?

**Comment by oliversweb** [comment]
Glad you sorted it, "never underestimate, '_turn it off and on again_'", I live by it 🤣

**Comment by amcoldsarge** [comment]
I too am trying to deploy this integration but it doesn't show up on the integration page. 

<img width="369" alt="image" src="https://user-images.githubusercontent.com/107087855/178163802-bede7aa2-9c8b-4ebb-90f7-db56e614d061.png">

I have added eufy_security: to my HA configuration.yaml file and both restarted HA and rebooted my HA VM.

Any additional recommendations?  Thanks!

**Comment by cdnninja** [comment]
You have installed via HACS?

**Comment by amcoldsarge** [comment]
I do.

**Comment by fuatakgun** [comment]
This is very specific to your setuo, i have just tested this on a fresh installation and all is working fine. Try clearing browser cache (or incognito mode) and you can get help in HA thread from community.
