### ISSUE TITLE
Manually trigger the bell on the Home Base

### ISSUE THREAD

**Issue by elirev4** [fuatakgun/eufy_security#378]
Hey,

I  have the Eufy Doorbell 2K HD Wireless together with the Home Base 2, and I was wondering if it would be possible to have a service that does 2 of the actions that physically clicking the Doorbell ring button does:

1.  Trigger the bell sound on the Home Base 2
2. Initiate the call screen on my phone - currently when the Eufy Security mobile app gets triggered by the doorbell ring, it brings up this call screen where I see a live stream of the doorbell together with the option to talk to whoever rang it the doorbell's built in speakers. Now I'm not asking to build that whole feature in HA xD but I was wondering if it would be possible to trick the app into thinking that the doorbell ring button was physically pressed so it would bring up that same call screen?

Thanks!

**Comment by fuatakgun** [comment]
As far as i know, there is no feature in the app to do so and eufy-security-ws is emulating the app features. In case there is a feature, please reach out to eufy-security-ws repository owner to implement this and let me know to start working on this.
