### ISSUE TITLE
Update Add-on from 0.7 > 0.9.2, Camera Unavailable.

### ISSUE THREAD

**Issue by BillyBobMills** [fuatakgun/eufy_security#380]
I have an installation using 0.7 of the add on which has been working well for months.

Just trying to update everything and when updating the add on to the latest 0.9.2 my doorbell camera become unavailable.

I only now have a doorbell camera and a keypad. The keypad continued to function fine.

I tried setting the add on up again and it listed the camera but no picture was available.

I've restored a backup and i have a working install again.

Anything im missing?

**Comment by cdnninja** [comment]
Did you update both the add on and integration at the same time?

**Comment by BillyFKidney** [comment]
I’m experiencing issues after upgrading.

HACS Eufy Integration v2.2.6
Eufy Security Integration v0.9.2 

Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest


```
Logger: homeassistant.config_entries
Source: config_entries.py:384 
First occurred: 11:28:11 AM (2 occurrences) 
Last logged: 11:28:58 AM

Config entry 'Localhost' for eufy_security integration not ready yet: Start Listening was not completed in timely manner; Retrying in background
```

```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/coordinator.py:187 
Integration: Eufy Security (documentation, issues) 
First occurred: 11:28:11 AM (13 occurrences) 
Last logged: 11:35:35 AM

eufy_security - no devices available yet
```

**Comment by fuatakgun** [comment]
this seems to be related with eufy-security-ws, at least shows problems. please reach out respective repository owner, I have limited knowledge at that end.
