### ISSUE TITLE
Support Snooze

### ISSUE THREAD

**Issue by amosyuen** [fuatakgun/eufy_security#381]
In the app you can snooze a camera for some time. The camera keeps recording but doesn't send notifications during that time. This is useful to reduce notifications but keep recording events.

I would like to be able to see the current snooze duration as well as set the snooze duration.

Dependent on https://github.com/bropat/eufy-security-ws/issues/116 being fixed first.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591

**Comment by fuatakgun** [comment]
snooze is added with alpha release. will be published in couple of minutes
there is a new service called snooze
