### ISSUE TITLE
Home Assistant Core 2022.7, streaming not working

### ISSUE THREAD

**Issue by orochifj** [fuatakgun/eufy_security#383]
**Describe the bug**
streaming not working after update to Home Assistant Core 2022.7.3.
Edit dashboard can see video update once every 10 second.

working fine in 2022.6.7

**To Reproduce**
streaming at dashboard.

**Expected behavior**
video stream instead of update every 10 second.

**Screenshots**

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Camera Model:  eufy doorbell 2k wired, eufy cam 2c
- Live Streaming Protocol: RTSP and P2p

**Additional context**

**Comment by dave-walschot** [comment]
I am probably having the same issue.

I had previously successfully running an Eufy outdoor cam K2 (model T8441321) via rtsp. After upgrade from HA Core 2022.6 to 2022.7.3 the card (custom:webrtc-camera) stays black and after a couple of seconds says "restart Connection". 

additional context
1) tested pretty close before and after upgrade. Haven't done a roll-back yet but my string suspect is that upgrade is causing this.
2) going trough the release notes it mentions to check especially custom integrations for Python 3.10, in case they dont support it yet it "might" break. cant figure out whether this would be the case though.
3) tested with Eufy app (iphone) and validated that cam is still working (iow working around HA cam is fine)

**Comment by fuatakgun** [comment]
It is an issue arising from webrtc and there is already an issue on their end for a solution.

**Comment by dave-walschot** [comment]
thank for the quick answer. will check there :-)

**Comment by fuatakgun** [comment]
https://github.com/AlexxIT/WebRTC/issues/321
