### ISSUE TITLE
Indoor Cam Pan&Tilt doesn't show stream

### ISSUE THREAD

**Issue by kongo09** [fuatakgun/eufy_security#389]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
I followed the setup,
- created and shared the device with an extra user for home assistant,
- confirmed in the Eufy app that this users works
- installed both add-ons
- configured ffmpeg in yaml
- added the integration

The camera is detected and an entity created along with many other entities that all seem to work ok. However, the cam only updates a picture every 10s or so, but doesn't show a live stream. At the bottom it says "streaming - rtsp"

In the configuration options, I have tried both: with or without "use RTSP add-on". The camera has RTSP enabled and I can use that on a DS Surveillance Station, which works well. I've also tried to manually call the start live stream services and the turn_on service. Nothing changes the situation.

**Expected behavior**
Show a live stream

**Screenshots**
not applicable

**Hardware Information about Home Assistant
RPi4

**Hardware Information about Cameras
- Indoor Cam Pan&Tilt
- Live Streaming Protocol: RTSP

**Additional context**

**Comment by kongo09** [comment]
I've installed the WebRTC integration and that shows a smooth stream, so RTSP seems to work.

**Comment by fuatakgun** [comment]
And p2p is not preferred over rtsp, if you don't have any further issues, feel free to resolve

**Comment by kongo09** [comment]
Well, I wouldn't consider this solved. The WebRTC integration is independent of the Eufy Security integration. If it were just for the video feed, I could have saved myself from the complexity of installing two extra add-ons plus this integration.

I wonder why the WebRTC integration shows the feed quite well, while this integration doesn't. Could it be that the data pipeline you've built adds too much burden on a Raspberry Pi 4?

**Comment by fuatakgun** [comment]
This is the current state, this integration requires webrtc to work, so nothing i can help here. If you are into to solve this problem, let's keep this open, otherwise webrtc is required as of now.

**Comment by kongo09** [comment]
Hm, fair enough. But why do you create this camera then if it doesn't work anyhow?

**Comment by fuatakgun** [comment]
1- not all cameras are supporting rtsp, there are many out there which uses p2p (data chunks are received into home assistant and  rtsp stream is generated on the fly)
2- you can definitely stick with basic camera setup with rtsp but you will miss all these sensors without integration.
3- as i said, this is known issue but given that webrtc is good enough, deep diving on this has little return of investment.

**Comment by kongo09** [comment]
Ok, understood. I'll close this here but maybe a few extra words in the documentation would help. If you like, I can suggest something with a PR.

**Comment by fuatakgun** [comment]
yes, it would be great
