### ISSUE TITLE
Eufy Security Add-on not starting in Home Assistant

### ISSUE THREAD

**Issue by plasmaboy** [fuatakgun/eufy_security#393]
Hi,

just installed Eufy Security Add-on following following integration manual for Eufy Security. After installation add-on wont start. Tried reloading Home Assistant few times and that have no effect on add-on. Basically when you hit button to start add-on it stop right away. Log is saying "2022-07-17 07:26:19.776  INFO  Eufy Security server listening on host 0.0.0.0, port 3000" and configuration tab says "This add-on does not expose configuration for you to mess with…"

**Comment by fuatakgun** [comment]
I had a fresh install on my dev environment and all is working fine. I dont think this is related to add-on, looks more related to setup, I suggest you to bring up this topic to HA community forum.
