### ISSUE TITLE
Client disconnected with ip: 172.30.32.1 

### ISSUE THREAD

**Issue by buzurk26** [fuatakgun/eufy_security#394]
Hi

My eufy setup has been working well for some time now on 0.92 until now its stopped

The integration log now shoes this as the last error

`2022-07-18 01:53:59.342  INFO  Client disconnected with ip: 172.30.32.1 port: 47190 code: 1000 reason:  `

Have performed reboots, checked all the config, usernames and passwords etc, nothing has changed that i can tell

**Comment by vrouleau** [comment]
same here . Intergration reports :Retrying setup: Start Listening was not completed in timely manner

**Comment by kobioneil** [comment]
Im having the same issue. could the "prove your not a robot" caption be the cause?

**Comment by edjanssen** [comment]
initial installation here shows the same

**Comment by nin0-dev** [comment]
You use HA core or OS?

**Comment by theinuyasha1999** [comment]
I'm having the same issue, but just started setting up my integration. I'm using OS, and went through the add-on setup. Integration also shows "Retrying setup: Start Listening was not completed in timely manner" for me.

**Comment by theinuyasha1999** [comment]
Well, I left it alone since the time I posted my reply yesterday, and now it's working.

**Comment by fuatakgun** [comment]
please retest with latest version and comment back here

**Comment by kobioneil** [comment]
The problem seemed to fix itself, I think I use both? I have it running on
the home assistant blue, the odroid n2. Thank you for your response

**Comment by fliespl** [comment]
2022-08-20 21:33:51.564  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-08-20 21:33:55.552  INFO  Client disconnected with ip: 172.30.32.1 port: 44370 code: 1000 reason:  
2022-08-20 21:34:35.811  INFO  Client disconnected with ip: 172.30.32.1 port: 49624 code: 1000 reason: 

Started happening on my end on newest version after removing integration, rebooting HA and readding it.
