### ISSUE TITLE
ERROR: Cant get url for camera

### ISSUE THREAD

**Issue by jfbourne** [fuatakgun/eufy_security#396]
Trying to get the conditional card for WebRTC going but I keep getting an error saying `ERROR: Cant get url for camera.XXX`

card look like this 

`type: grid
square: false
cards:
  - type: conditional
    conditions:
      - entity: binary_sensor.patio_streaming_sensor
        state: 'False'
    card:
      type: picture-entity
      entity: camera.patio
      tap_action:
        action: call-service
        service: camera.turn_on
        target:
          entity_id: camera.patio
  - type: conditional
    conditions:
      - entity: binary_sensor.patio_streaming_sensor
        state: 'True'
    card:
      type: vertical-stack
      cards:
        - type: custom:webrtc-camera
          entity: camera.patio
        - type: button
          name: Stop Streaming
          show_state: false
          show_icon: false
          tap_action:
            action: call-service
            service: camera.turn_off
            target:
              entity_id: camera.patio
columns: 1
`

**Comment by fuatakgun** [comment]
are you using RTSP or P2P?
If it is RTSP, URL is supplied by Eufy app itself, not the integration.
If it is P2P, I have just released a new version of integration to improve its stability for P2P, give it a try.

**Comment by fuatakgun** [comment]
merging threads: https://github.com/fuatakgun/eufy_security/issues/287
