### ISSUE TITLE
Addition of state_class=measurement to battery entity attributes

### ISSUE THREAD

**Issue by horriblenoises** [fuatakgun/eufy_security#397]
**Is your feature request related to a problem? Please describe.**
Technically correct and there are tutorials using this as list filter for low battery automations.

**Describe the solution you'd like**
Battery entities have `device_class: battery` attributes. Looking to add `state_class:measurement` to that attribute list.

**Describe alternatives you've considered**
Could be done per user in customizations but I figured it might be better from the dev.

**Additional context**
Using [this](https://github.com/smarthomejunkie/Home-Assistant-Tutorials/tree/master/Low-Battery-Warning-Sensor) automation is my main driver. I'm assume it's an easy fix. (If it's not, sorry.)

**Comment by fuatakgun** [comment]
published with latest commit, test in new revision and report back

**Comment by horriblenoises** [comment]
Updated to 2.5.0
Updated docker container to bropat/eufy-security-ws:latest
restarted home assistant 2022.07.2.

sensor.doorbell_battery attributes:
type: DEVICE_TYPE.BATTERY_DOORBELL
category: DOORBELL
unit_of_measurement: '%'
device_class: battery
friendly_name: Doorbell Battery

I don't remember "type" being in there so I assume it updated. State_class is still not present though. Do you think I need to delete the entity and re-add it for the attribute to show up?
