### ISSUE TITLE
Hass Core - missing some instructions and addons??? please advise

### ISSUE THREAD

**Issue by jboesh** [fuatakgun/eufy_security#398]
Hello.
first; thanks for working on this!

I'm trying to follow your instructions (I'm running HomeAssistant core in Docker) and so I don't have the supervised version, while your instructions are very focused on that. (for example with 6.1. Addon store, is not present in Hass Core for me).

so I can't install the Eufy Security WS addon, it seems? and the same goes for the RTSP simple server addon.

what I did manage is to add HACS, the Eufy Security repository and link it to the Eufy docker image. For example, in the logs I see:
```
2022-07-27 19:34:08.807 INFO Eufy Security server listening on host 0.0.0.0, port 3000
2022-07-27 19:34:11.194 INFO No stations found.
2022-07-27 19:34:11.621 INFO No devices found.
2022-07-27 19:34:19.252 INFO Push notification connection successfully established
2022-07-27 19:35:00.528 INFO No stations found.
```

1 question about that; is the COUNTRY environment variable, for the Netherlands: nl?
I can't find that anywhere. Is it important though?

The RTSP docker image is also running in docker.. btw

On the Integrations page, at the Eufy Security I enter the IP address of the Eufy docker image.
but the integration doesn't seem to work. in the logs I see:

```
Logger: homeassistant.setup
Source: setup.py:298
First occurred: 21:58:08 (2 occurrences)
Last logged: 21:59:45

Unable to prepare setup for platform eufy_security.camera: Platform not found (cannot import name 'CameraEntityFeature' from 'homeassistant.components.camera' (/usr/src/homeassistant/homeassistant/components/camera/__init__.py)).
```

What do I need to do, to make the eufy secutity integration work for my hass core?
thanks in advance!

**Comment by fuatakgun** [comment]
1. There are some docker commands available in readme, use them if you don't have supervisor.
2. Country code should be NL, it matters.
3. Eufy security WS addon should generate a message about connected stations. İn your screen, it says, no devices and stations, which will be a problem.
4. You  need to update your home assistant, you are using an old version.
