### ISSUE TITLE
Inatallation

### ISSUE THREAD

**Issue by ssv5000** [fuatakgun/eufy_security#40]
I have followed the installation to the letter, I get to the last part 

Configuration, Integration's,  + Add Integration

When I search for Eufy Security it is not there. When I check in HACS, Eufy Security is there as a repository.

Thank you for the help

**Comment by fuatakgun** [comment]
Please try with different browser, this is an issue of browser caching. Check tip over here: https://hacs.xyz/docs/categories/integrations/

**Comment by dpomnean** [comment]
For me, since I have the docker instance of HA, I had to restart the HA container.

**Comment by fuatakgun** [comment]
I will resolve this as this issue is not directly related to integration, even more, you can skip HACS (not a pleasant experience) and install this manually.
