### ISSUE TITLE
Detected Person Name always "Unknown"

### ISSUE THREAD

**Issue by ejpenney** [fuatakgun/eufy_security#400]
sensor.doorbell_detected_person_name is always "Unknown" even when the app shows a name attached to a motion event.

**To Reproduce**
1. Go to Eufy Security App Events
2. Click on an event with a successfully identified Human
3. Look up history of Detected Person Name sensor
4. Sensor says "Unknown"

**Expected behavior**
Sensor should be a string of the name of the user as trained in Eufy Security

**Screenshots**
Here we see a screengrab in the Eufy app where it has indicated it recognizes a person, but Home Assistant says "Unknown"
![image](https://user-images.githubusercontent.com/21226768/181367342-795bfc17-a793-451d-aed4-929ca7415508.png)
![image](https://user-images.githubusercontent.com/21226768/181368002-ac5052c7-ff86-48d8-91ee-ea9c1f10be7a.png)

**Hardware Information about Home Assistant
Raspberry Pi 4

**Hardware Information about Cameras
- T8203 (Doorbell Dual Wired)
- RTSP

**Comment by fuatakgun** [comment]
Do you know if this is supported by bropat 's eufy-security-ws repository? Can you check with him?

**Comment by ejpenney** [comment]
Sure thing I can check.

In the interest of tracking: I submitted a question [here](https://github.com/bropat/eufy-security-ws/issues/120)

**Comment by ejpenney** [comment]
Looks like this is working in 0.9.4!

**Comment by fuatakgun** [comment]
Nice, thanks to @bropat
