### ISSUE TITLE
Eufy Wifi door lock status not chahging

### ISSUE THREAD

**Issue by pupadhyay76** [fuatakgun/eufy_security#402]
After receive update this morning status of Eufy Wifi Door Lock status stays Closed. 
However I can open and close from the card but status stays as Closed. 
Model T8520. 
I am using custom integration as below 
https://github.com/fuatakgun/eufy_security

**Comment by fabianluque** [comment]
Same here, T8520 no longer updates status properly. Was working fine before the update.

**Comment by pupadhyay76** [comment]
Hope fully new updates comes out soon. At the moment my dashboard is reporting locked but the device is actually unlocked.

**Comment by fuatakgun** [comment]
Please share entity state attributes for your lock. Use developer tools to do that. I am interested in `locked` and `lockState` attributes and how do they change after each event.

So, first dump existing state attributes here, then lock/unlock your device, wait for 5 seconds, refresh state attributes and dump here again please.

**Comment by fuatakgun** [comment]
Please share entity state attributes for your lock. Use developer tools to do that. I am interested in `locked` and `lockState` attributes and how do they change after each event.

So, first dump existing state attributes here, then lock/unlock your device, wait for 5 seconds, refresh state attributes and dump here again please.

2022-07-27 14:27:36 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_event_for_entity - device / T8510Q10212603EB / lockStatus / False

**Comment by fabianluque** [comment]
@fuatakgun I’ve shared above the relevant attributes for lock state when locking and unlocking. Is there any other attributes you want to see?

**Comment by fuatakgun** [comment]
Yes it is enough, i am trying to find a common base between different locks

**Comment by alexeiw123** [comment]
> Same here, T8520 no longer updates status properly. Was working fine before the update.
> 
> Add-on version 0.9.3 Integration version 2.5.0
> 
> From the attributes when T8520 is unlocked I see this:
> 
> locked: false lockStatus: 3
> 
> When it’s locked I see:
> 
> locked: true lockStatus: 4

I have the same lock (T8520).

I see the same behaviour in the attributes.

when unlocked:
locked: false
lockStatus: 3

when locked:
locked: true
lockStatus: 4

Lock status still doesn't update on device view though.

**Comment by alexeiw123** [comment]
Is there a way using HACS to revert back to an older version that was working fine for my devices?

The oldest available version here is still not updating lock state and it's mucking up some automations that I have but would rather not disable or edit.
![image](https://user-images.githubusercontent.com/77809797/181652642-d3b9f2c2-1370-4b9e-94dd-5b6d0e944987.png)

**Comment by cdnninja** [comment]
Manually download from GitHub and place the files in the correct folder structure.

**Comment by alexeiw123** [comment]
Thanks,

I've done this by overwriting all files in  /config/custom_components/eufy_security/ and the integration is now working again.
HACS still shows the versions as v2.5.0 which I suspect will cause some issue. Any idea how to refresh this?

> Manually download from GitHub and place the files in the correct folder structure.

**Comment by fuatakgun** [comment]
@alexeiw123 this will not cause any issues, don't worry

**Comment by alexeiw123** [comment]
> @alexeiw123 this will not cause any issues, don't worry

Thank you. Hilariously, after doing it the long way, I found this option in the integration configure for HACS:
Might be useful for others that want to roll back temporarily.

![image](https://user-images.githubusercontent.com/77809797/181703125-a06e0cce-c20f-449f-84fb-501a16011b8e.png)

**Comment by fuatakgun** [comment]
On the other hand, i am planning to release a new version today to be inclusive for both type of locks, so, please give it a try.

**Comment by alexeiw123** [comment]
> On the other hand, i am planning to release a new version today to be inclusive for both type of locks, so, please give it a try.

Will do, I'll let you know either way

**Comment by Zeunas** [comment]
> On the other hand, i am planning to release a new version today to be inclusive for both type of locks, so, please give it a try.

Hope it fixes the below issue I am having with the Doorbell, where switch and select entities are not updating. I believe it's related to this issue but if the update doesn't fix it I will open an new issue.

![image](https://user-images.githubusercontent.com/71456261/181708695-b4a0e876-3bc8-48a9-aa33-5a9130948fcf.png)

**Comment by fuatakgun** [comment]
getting help from @bropat https://github.com/bropat/eufy-security-ws/issues/123

**Comment by fuatakgun** [comment]
Please update to integration 2.6.2 and add-on 0.9.4 and test.

**Comment by fabianluque** [comment]
T8520 is back in business! Thanks @fuatakgun!

**Comment by jem** [comment]
Looking good with `2.6.2` and `0.9.4` for T8510. Great work @fuatakgun.

For posterity, now seeing:
```
> diff {un,}locked
11,12c11,12
< locked: false
< lockStatus: 3
---
> locked: true
> lockStatus: 4
29,30c29,30
< lockStatus: 3
< locked: false
---
> lockStatus: 4
> locked: true
```

**Comment by alexeiw123** [comment]
> Please update to integration 2.6.2 and add-on 0.9.4 and test.

Confirmed fixed 👏

**Comment by pupadhyay76** [comment]
Yes.. working after update. thanks for the updated version.

**Comment by alexeiw123** [comment]
This issue seems to be back again, not getting status updates with T8520. V2.6.3
