### ISSUE TITLE
streaming is not working after the first time

### ISSUE THREAD

**Issue by leonardpitzu** [fuatakgun/eufy_security#403]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
After a clean start (restart of HA) streaming works (clicking the camera still image starts the playback). After reloading HA in the browser or starting the app again, streaming does not work.
Streaming ALWAYS works in the eufy app.

**To Reproduce**
1. restart HA
2. click the camera -> streaming starts
3. exist the app or reload the page in the browser
4. click the camera -> streaming is not starting

**Expected behavior**
Streaming shall start every time the camera is clicked.

**Screenshots**
<img width="1102" alt="Screenshot 2022-07-28 at 11 36 54" src="https://user-images.githubusercontent.com/4321813/181462543-21f49ad6-c88f-4da4-a4e4-26fdff0e51a4.png">
<img width="1027" alt="Screenshot 2022-07-28 at 11 37 59" src="https://user-images.githubusercontent.com/4321813/181462561-71aaef30-9bd6-47ad-b095-d3b48b89e9f0.png">
<img width="330" alt="Screenshot 2022-07-28 at 11 48 43" src="https://user-images.githubusercontent.com/4321813/181463655-b277a664-3494-4482-b035-7639f3f9f8bb.png">

**Hardware Information about Home Assistant
Home Assistant OS (8.4) + Home Assistant 2022.7.7 / 2022.08 running on a Raspberry Pi 4

**Hardware Information about Cameras
- Camera Model: eufyCam 2
- Live Streaming Protocol: RTSP

**Additional context**

**Comment by fuatakgun** [comment]
thanks for the issue, the problem seems to be coming from add-on and I just wrapped it from another docker. 
I suggest you to check with @bropat on eufy-security-ws repository as I do not have much knowledge on that end.

**Comment by leonardpitzu** [comment]
OK, thanks.

**Comment by leonardpitzu** [comment]
Update: if i restart the (your) integration streaming resumes working. It seems that the stream is never stopped thus the second time i click the camera image it can't stream. I use the Picture Entity Card with the native HA mechanisms (aka no WebRTC integration).

**Comment by fuatakgun** [comment]
can you give it a try with latest version, I had included some new tweaks

**Comment by leonardpitzu** [comment]
Now with the latest version it seems to work (much better). First and subsequent times I “click” a camera the streaming starts but i do get some errors and it takes a very very long time for the streaming to start. I do have some errors in the integration (no errors at all in the add-on).
![C6360074-BB8E-454B-BC12-9912D7CEDD4F](https://user-images.githubusercontent.com/4321813/182027311-e7d49cfc-759a-453f-8aec-e6af96e09f20.png)
![F24A5B38-904E-471A-9317-437B470C3FFD](https://user-images.githubusercontent.com/4321813/182027317-56a709ef-d066-4061-b25f-73bf59e09c21.png)

**Comment by fuatakgun** [comment]
Hey, these screenshots are showing rtsp based streaming rather than p2p, am i right?

**Comment by leonardpitzu** [comment]
I have the eufycam 2 battery operated cameras. I only have a switch for RTSP on/off in the eufy app. Thus i have no idea how to switch them over to p2p. So yes, they are native RTSP. I you have any way to debug it let me know - I can share my cam. Or tell my what settings to tweak.

**Comment by fuatakgun** [comment]
What i meant, integration is just sending a signal to add-on and add-on is acting as mobile app to initiate rtsp stream. The stream itself is coming from base station, there is no gimmick inside add-on or integration to fix it.

When you have these issues, can you check add-on logs and share it over? As a next step, we might need to go to @bropat via eufy-security-ws repository.

**Comment by leonardpitzu** [comment]
Add-on logs are clean. I have to enable debugging to see more but it takes a bit time, we have a 1 month old baby and she’s a hand full.

**Comment by fuatakgun** [comment]
Congrats and take your time

**Comment by orochifj** [comment]
i think i having the same issue. 
streaming not working.
restart HA and it back to normal.
revisit HA like few hours later and it not working again until restart HA.

I wish to help but i not sure where can get the log.
i already enable debugging but home-assistant.log is too much info i don't know which 1 should capture.

**Comment by akeslo** [comment]
I am having the same issue as well, happy to help in any way that I can:

**Logs:**

```
eufy_security - Exception - process_messages: 'T8210P0dd02033392B' - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 386, in on_message self.devices[serial_number].set_codec( KeyError: 'T8210P002033392B' - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"event","event":{"source":"device","event":"livestream video data","serialNumber":"T8210Pddd002033392B","buffer":{"type":"Buffer","data":[0,0,0,1,65,225,208,147,255,0,94,99,57,176,64,173,152,82,1,117,49,216,242,153,211,159,31,192,26,37,242,55,127,195,137,28,8,198,83,149,224,223,253,38,245,82,153,28,84,24,1,222,26,129,23,124,128,0,0,3,3,64,1,2,29,112,167,112,145,188,144,2,210,92,0,33,32,0,0,176,199,245,255,223,214,186,90,198,133,197,111,222,90,199,103,168,212,230,132,154,51,190,183,157,134,156,55,172,225,212,1,150,58,48,8,66,21,228,195,29,82,204,165,184,168,61,248,42,39,242,67,17,10,160,11,225,225,163,245,105,132,94,119,37,20,128,11,220,32,0,0,3,0,2,240,0,13,152]},"metadata":{"videoCodec":"H264","videoFPS":15,"videoHeight":1200,"videoWidth":1600}}}', extra='')
7:48:57 AM – (ERROR) Eufy Security (custom integration) - message first occurred at August 9, 2022 at 11:31:51 PM and shows up 38223 times
eufy_security - Event received but device is missing, maybe not connected - 'T8420N102ddd0301757'
7:48:47 AM – (ERROR) Eufy Security (custom integration) - message first occurred at August 9, 2022 at 11:39:27 PM and shows up 838 times
```



```
**Ad-On:**
2022-08-10 11:49:06.461  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-08-10 11:49:16.748  INFO  Connected to station T8010P132XXXX on host 192.168.4.94 and port 10774 
2022-08-10 11:49:16.856  INFO  Connected to station T8420N102XXXX on host 192.168.4.20 and port 29284 
2022-08-10 11:49:16.912  INFO  Connected to station T8420N102XXXX1 on host 192.168.4.129 and port 12197 
2022-08-10 11:49:16.946  INFO  Connected to station T8420N10XXXX1757 on host 192.168.4.49 and port 11183 
2022-08-10 11:49:17.035  INFO  Connected to station T8420N1XXXX42 on host 192.168.4.64 and port 10774 
2022-08-10 11:49:26.697  INFO  Push notification connection successfully established 
2022-08-10 11:49:31.619  ERROR P2PClientProtocol.lookup(): station: T8XXXX281A57 - All address lookup tentatives failed. 
2022-08-10 11:49:31.622  INFO  Timeout connecting to station T840XXXX281A57 
```
2022-08-10 11:49:51.717  ERROR P2PClientProtocol.lookup(): station: XXXX - All address lookup tentatives failed. 
2022-08-10 11:49:51.719  INFO  Timeout connecting to station T8XXXX81A57 
2022-08-10 11:50:16.732  ERROR P2PClientProtocol.lookup(): station: T8XXXX020281A57 - All address lookup tentatives failed. 
2022-08-10 11:50:16.734  INFO  Timeout connecting to station T840XXXX20281A57 
2022-08-10 11:50:51.743  ERROR P2PClientProtocol.lookup(): station: T84XXXX7 - All address lookup tentatives failed. 
2022-08-10 11:50:51.744  INFO  Timeout connecting to station T840XXXX57

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/592
