### ISSUE TITLE
Update to 2.5.0 not completing

### ISSUE THREAD

**Issue by MilesAheadToo** [fuatakgun/eufy_security#404]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
When I try to update to v2.5.0 based on the prompt in HA UI, I get to 10%, and nothing further happens.
![image](https://user-images.githubusercontent.com/78782836/181638979-d6c2de01-8e2e-4cc8-9389-cef647847250.png)

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Eufy Security update/Version V2.5.0 is available'
3. Click on 'Install'
4. The progress bar gets to 10% and then nothing happens. I have left  the system running for 10min with the HA page open, and nothing happens.

**Expected behavior**
The progress bar would increase to 100% to show completion of the install.

**Screenshots**
See above.

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Camera Model: Solo Pro
- Live Streaming Protocol: P2P

**Additional context**

**Comment by fuatakgun** [comment]
I cannot help on this, there are many users (including me) just updated it normally, it should be something specific to your setup, please try home assistant forums
