### ISSUE TITLE
video_streaming_quality and several other entities missing from battery doorbel

### ISSUE THREAD

**Issue by EDelsman** [fuatakgun/eufy_security#405]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
For my battery doorbel I used to check if select.voordeur_video_streaming_quality was set to “Low / Low Encoding” to see if streaming would work from HA. Is that entity no longer there, along with several other ones that became unavailable. (deleted those because I thought it was by design).

**To Reproduce**
1. Install version 2.5.0
2.  Go to doorbell device to see unavailable/missing entries

**Expected behavior**
_video_streaming_quality and other entities to be there

**Screenshots**
none

**Hardware Information about Home Assistant
Rpi4
Versie: core-2022.7.7
Type installatie: Home Assistant OS

**Hardware Information about Cameras
- Battery doorbel T8210
- Live Streaming Protocol: P2p

**Additional context**

**Comment by fuatakgun** [comment]
fixed with latest version, sorry for churn, will be released in couple of minutes

![image](https://user-images.githubusercontent.com/11085566/181817793-fbe1e54e-aa06-44e2-9422-d35a7c155c88.png)

**Comment by EDelsman** [comment]
Wow, thats fast! Thanks!

**Comment by fuatakgun** [comment]
it is easy to fix when you break it yourself (unintentionally:-) )

**Comment by EDelsman** [comment]
I installed 2.6.1, and even triued removing the integration and adding it again, but I still miss all the combo's I'm afraid:
![voordeur](https://user-images.githubusercontent.com/81650815/181831036-8d81296f-905b-41f9-8b66-b9bea3d2d03f.jpg)
![achtertuin](https://user-images.githubusercontent.com/81650815/181831065-5d8f3bd6-978c-4517-9a0b-1aa6a184a001.jpg)

**Comment by FermionAlpha** [comment]
I'm also possibly seeing the same issue with my Solocam E20's 

![image](https://user-images.githubusercontent.com/76852495/182132088-ee40c694-f7af-4041-9c59-4dfa595b492a.png)

The dropdowns were working up until a week or two ago.

**Comment by EDelsman** [comment]
Probably to be expected: Going back to 2.4 recreates the items for me, and upgrading to 2.6.2 again disables them like the screenshot above as they are unavailable again.

**Comment by fuatakgun** [comment]
try with latest version

**Comment by EDelsman** [comment]
Yes! Everything is well again. Thank you very very much!
