### ISSUE TITLE
schema_incompatible message in log

### ISSUE THREAD

**Issue by ejpenney** [fuatakgun/eufy_security#406]
For a couple of days I've been seeing this in the logs during startup.  I tried deleting and re-adding the integration, the message appeared again while the component setup.  I'm not exactly sure which release it appeared in, Might have been 2.2.7, since it only happens once during startup I was hoping it might go away on its own, but it persists.  Doesn't _seem_ to be impacting any functionality, but I figured I'd note it anyways...

Thanks for all your great work!

```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/websocket.py:58
Integration: Eufy Security (documentation, issues)
First occurred: 11:12:57 AM (2 occurrences)
Last logged: 11:24:06 AM

eufy_security - Exception - process_messages: 'result' - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 56, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 67, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 297, in on_message message_result = payload[message_type] KeyError: 'result' - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":false,"messageId":"set_api_schema","errorCode":"schema_incompatible"}', extra='')
```

**Comment by fuatakgun** [comment]
Please update add-on to 0.9.3

**Comment by ejpenney** [comment]
Hmm, Home Assistant says 0.9.1 is the latest version.  I uninstalled and re-installed the add-on and got 0.9.1 again.  Looks like the Add-On has never been released on the GitHub page?

**Comment by ejpenney** [comment]
Never mind, removed add-on, removed repository, restarted HASS, added repository, installed Add-On, and I've got the correct version...

**Comment by fuatakgun** [comment]
You need to update manually add on store, it was released yesterday and i personally used supervisor in two instances to update it.

So check internally please

**Comment by fuatakgun** [comment]
![IMG_20220729_212818.jpg](https://user-images.githubusercontent.com/11085566/181830827-b5ce45ca-0a75-4083-9acc-655bc1a56cb5.jpg)
