### ISSUE TITLE
Support for 2FA

### ISSUE THREAD

**Issue by rfnovo** [fuatakgun/eufy_security#407]
Please add support for 2FA

**Comment by fuatakgun** [comment]
Given all these issues, i won't prioritize this, but we can keep it here

**Comment by rtaghawi** [comment]
I need this feature too, pls.

**Comment by elmerdk79** [comment]
Same request here.

**Comment by tossbek** [comment]
Please prioritize this feature in order to increase the security a lot.
Thank you very much

**Comment by sforeman00** [comment]
2FA is an important feature, would appreciate it if you could add it soon. Especially with security systems/cams/etc.
Thanks!

**Comment by Daneish** [comment]
To indicate your support for this request, rather than replying, it might be best just to add a 👍 to the original post.

**Comment by fuatakgun** [comment]
I understand you guys but given that you are creating an account for this integration explicitly and logging your account from different device logs you out from here, there are enough cues to understand if something is wrong. I am not against it but adding captcha was soooo difficult, i dont know when i can do a similar setup for 2fa :-)

**Comment by j-fuentes** [comment]
As a temporary workaround I see two options:

- create an account in eufy just for this integration, don't use 2FA in that one and share the devices you want to see in home-assistant with that account.

- implement a script that sends the 2FA code and add instructions to run that command locally or in the `eufy-security-ws` container.


I am trying to do the latter myself at the moment.

**Comment by j-fuentes** [comment]
I have https://github.com/bropat/eufy-security-ws running as a container and I have managed to completed the 2FA flow. You can do it like this:

- open a terminal with the `eufy-security-ws` client: `docker exec <container name> node ./dist/bin/client.ts`. You should see some events in JSON. 
- then go to home-assistant -> settings -> integrations and "Reconfigure" the eufy-security integration. It will ask to introduce the captcha, do it. That caused the terminal to print some more JSON events.
- Now you will receive an email or SMS with the verification code. Note it down.
- Go to the terminal again, hit Enter to see the prompt `eufy-security>`.
- Now write in the terminal `driver.set_verify_code 000000`, but with your 2FA code instead and hit Enter.
- After some seconds you will see more JSON events and the extension in home-assistant will automatically finalize the auth flow and show your eufy devices.

**Comment by JoryHogeveen** [comment]
@j-fuentes 
I cannot seem to access the container terminal.
`docker exec <container name> node ./dist/bin/client.ts` returns error `Cannot find module`
I did use docker-compose to create the container and have Portainer available for access if needed.
Do you have more info on how I can follow the steps you've mentioned?

**Comment by tossbek** [comment]
I get also "Error: Cannot find module '/usr/src/app/dist/bin/client.ts'"

Do you mean docker exec <container name> node ./dist/bin/client.d.ts ?

If so, the error is 
input: # docker exec "id" node ./dist/bin/client.d.ts
output: 
SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by danielcbaldwin** [comment]
I got that error as well. I had to run `docker exec -it <container name> node ./dist/bin/client.js`. Note the `js` vs the `ts`. I also had to add -it for me or I couldn't get the prompt to be interactive for me.

Thanks @j-fuentes

**Comment by fuatakgun** [comment]
alpha version supports this
