### ISSUE TITLE
Option to save images/video -eufy doorbell

### ISSUE THREAD

**Issue by jboesh** [fuatakgun/eufy_security#408]
is it possible to save the images/video as soon as there is movement or the doorbell rings on the eufy device/doorbell?  then save it in the homeassistant volume/directory?

Thanks

**Comment by fuatakgun** [comment]
If the camera is streaming, you can use save `snapshot` or `record` services of native camera domain. If it is not streaming already, you have to start streaming beforehand and execute respective services.

**Comment by fuatakgun** [comment]
https://www.home-assistant.io/integrations/camera/#services

**Comment by jboesh** [comment]
I have played with some automations but it looks like the record function is not available for the eufy doorbell.

alias: Test1
description: ''
trigger:
  - platform: state
    entity_id:
      - camera.deurbel
      - binary_sensor.deurbel_streaming_sensor
    from: 'False'
    to: 'True'
condition: []
action:
  - service: camera.record
    data:
      filename: Test1
      duration: 3600
    target:
      area_id: 2640dba385f922f292120588cfd58149
mode: single

The error;
Stopped because an error was encountered at 1 augustus 2022 om 23:10:08 (runtime: 0.01 seconds)

camera.deurbel does not support record service


Do you have an example maybe how to set this up?
I have the camera and stream integration in my hass

Thanks

**Comment by fuatakgun** [comment]
I thought this is supported out of box inside home assistant, apparently i am wrong, let me check this

**Comment by fuatakgun** [comment]
I have just tested it, it is working as usual, you need to wait probably 1 second before starting to record. Below snippet worked perfectly and saved the test file.

```
service: camera.record
data:
  duration: 30
  filename: www/test.mp4
target:
  entity_id: camera.garden
```

**Comment by jboesh** [comment]
thanks for the input. hm nothing is happenings at my side

what are you using as trigger?
Iam not sure this is the correct one Iam using


alias: Test1
description: ''
trigger:
  - platform: state
    entity_id:
      - binary_sensor.deurbel_streaming_sensor
condition: []
action:
  - service: camera.record
    data:
      filename: www/test.mp4
      duration: 30
    target:
      entity_id: camera.deurbel

**Comment by fuatakgun** [comment]
I have just tested it, it is working as usual, you need to wait probably 1 second before starting to record. Below snippet worked perfectly and saved the test file.

```
service: camera.record
data:
  duration: 30
  filename: www/test.mp4
target:
  entity_id: camera.garden
```
