### ISSUE TITLE
flood light switch no longer present

### ISSUE THREAD

**Issue by deformedchild** [fuatakgun/eufy_security#409]
the light entity for T8420N10203300B5 flood light is no longer available

**Comment by alexeiw123** [comment]
Came here to log an issue for the same thing.
Multiple sensors unavailable with T8422

integration v2.6.2 and add-on 0.9.4.

![image](https://user-images.githubusercontent.com/77809797/182003415-4900db05-7f6d-4be9-99f4-a18323ecbaa2.png)

![image](https://user-images.githubusercontent.com/77809797/182003456-9029fb71-7db4-48c8-b4be-1b13c5a5d49f.png)

**Comment by deformedchild** [comment]
well at least its not just me

**Comment by droiddavid91** [comment]
Having the same issue, upgraded from 2.2.4 to 2.6.2

**Comment by eufysecurity** [comment]
to fix this issue, in the /[custom_components]/[eufy_security]/coordinator.py file switch line 177 and 179 with each other.

**Comment by eufysecurity** [comment]
[https://github.com/eufysecurity/eufy_security/tree/patch-1](https://github.com/eufysecurity/eufy_security/tree/patch-1)

**Comment by droiddavid91** [comment]
That restored the switch functionality, thank you.

**Comment by fuatakgun** [comment]
can you try with latest version?

**Comment by alexeiw123** [comment]
> can you try with latest version?

All entities are working now, excellent.

Did this device previously have light brightness control like it does in the eufy app? Maybe I am imagining that it used to be there.

**Comment by droiddavid91** [comment]
> can you try with latest version?

Working great. Thank you.

> Did this device previously have light brightness control like it does in the eufy app? Maybe I am imagining that it used to be there.

Brightness control never existed from what I remember. Using T8424 Floodlight cameras.

**Comment by deformedchild** [comment]
thanks that fixed it
