### ISSUE TITLE
select p2p streaming per device or fallback when p2p streaming not possible

### ISSUE THREAD

**Issue by kevinhalpin** [fuatakgun/eufy_security#41]
**Is your feature request related to a problem? Please describe.**
I have a eufy doorbell T8200 (Wired, 2K). This does not use the Homebase as storage.
I have 2 Eufy2C Cameras (Wireless, 1080p). This does stream to homebase

Using RTSP streaming, I can see the Eufycam 2C Cameras where the rtsp streaming link on homebase exists. But I cannot see the Eufycam doorbell stream because that does not have anything to stream from homebase.

I'd like to get the benefits of the p2p streaming with the Eufy 2C cameras but not sacrifice the feed from the doorbell.

**Describe the solution you'd like**
Be able to enable to enable the websocket rtsp streaming per device

**Describe alternatives you've considered**
Have a camera fallback to the file based method automatically when a camera doesnt have a stream being published to homebase or to eufy_security-<device> on the rtsp simple server

**Additional context**

Here are the logs from the RTSP Simple Server Add-on

```
2021/08/10 17:35:03 I [0/0] [RTSP] [conn 172.30.32.1:35800] opened
2021/08/10 17:35:03 I [0/0] [RTSP] [conn 172.30.32.1:35800] ERR: no one is publishing to path 'eufy_security-T8200N0019504188'
2021/08/10 17:35:03 I [0/0] [RTSP] [conn 172.30.32.1:35800] closed
```

Thanks!

**Comment by fuatakgun** [comment]
When you call camera.turn_on service or click on camera image on lovelace, I am expecting that;
- 2c cameras will directly use RTSP streaming, this is not using rtsp addon if camera supports rtsp streaming
- non rtsp cameras like doorbell will use p2p streaming but incoming data will be sent to rtsp addon for faster video generation.


So, when you enable rtsp add on, it will br impacting only p2p streaming, not rtsp streaming. By the way, you can enable p2p streaming for 2c cameras also, but i don't see a point :-)

I have bunch of these (thanks to community they have shared) and they are working as i described. 

Let me know if it is clear to you.

**Comment by timdonovanuk** [comment]
I have a non rtsp cameras like doorbell and installed the rtsp addon, ticked the "ALPHA - Use RTSP Server Add-On instead of File Based Streaming" box but still get:

```
2021/08/18 14:01:53 I [0/0] [RTSP] [conn 172.30.32.1:55970] ERR: no one is publishing to path 'eufy_security-T8200N0020080296'
2021/08/18 14:01:53 I [0/0] [RTSP] [conn 172.30.32.1:55970] closed
```

**Comment by fuatakgun** [comment]
> I have a non rtsp cameras like doorbell and installed the rtsp addon, ticked the "ALPHA - Use RTSP Server Add-On instead of File Based Streaming" box but still get:
> 
> ```
> 2021/08/18 14:01:53 I [0/0] [RTSP] [conn 172.30.32.1:55970] ERR: no one is publishing to path 'eufy_security-T8200N0020080296'
> 2021/08/18 14:01:53 I [0/0] [RTSP] [conn 172.30.32.1:55970] closed
> ```

There is a separate issue regarding to your problem, let me resolve this and you can follow the other one.
