### ISSUE TITLE
Allow to access speaker as media target

### ISSUE THREAD

**Issue by kaystrobach** [fuatakgun/eufy_security#415]
**Is your feature request related to a problem? Please describe.**

It would be awesome to answer doorbell and other activities with a sound message.

Example:

1. package delivery, while I'm at home
2. send sound: 'please leave package at the front door'

When I'm not home, the message should be please ask the neighbours to keep the package.

**Describe the solution you'd like**

Expose speakers as media target like it's done by unifi protect integration.

**Describe alternatives you've considered**

switch camera system

**Additional context**

![grafik](https://user-images.githubusercontent.com/1185776/182782258-e35e99e3-5567-4bdc-8d4a-6b3fff9495d6.png)

**Comment by fuatakgun** [comment]
This is a nice idea, let me think on it, in the mean time, integration supports quick vice answers

**Comment by kaystrobach** [comment]
correct, but quick answers do not necessarily fix the problem i had. As the number of quick responses is limited to my knowledge (hopefully wrong) and this would also split config across different locations.

**Comment by kaystrobach** [comment]
I found another use case for this.

Using the new media service we can use TTS to talk to people. As more an more delivery people are from foreign countries, i would then be able to provide instructions in different languages with TTS.

**Comment by kaystrobach** [comment]
Another one: halloween 👻 playing MP3s for halloween can be endless fun 🤩

**Comment by kaystrobach** [comment]
Do you know any trick to get the IDs of quick responses? 1,2,3 (predefined) work as expected. The also loaded wolf, witch and Christmas sounds, as well as self recorded are not within the range of 1 to 20 🤔

**Comment by kaystrobach** [comment]
Ok, got it.

To find the numbers of the eufy quick responses, you can take the following steps:

1. open HomeAssistent 
2. Open Developer Tools
3. Open the states tab (the one after yaml)
4. Search for your doorbell entity (should have idle -89% or something similar as state)
5. Click it
6. See the resulting yaml file in node `custom.voices`
7. Use the `voice_id`

have fun

**Comment by kaystrobach** [comment]
Somehow this is still not reliable. Have to check, why the App works, logfiles look good, but still no quick response from homeassistant 🤔

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/415
