### ISSUE TITLE
Instalation with docker

### ISSUE THREAD

**Issue by pinanunes** [fuatakgun/eufy_security#418]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Camera Model
- Live Streaming Protocol: RTSP or P2p

**Additional context**

**Comment by pinanunes** [comment]
I'm trying to migrate my HA to docker, after installing I get the following log from portainer:

`2022-08-04 22:41:54.992  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-08-04 22:41:58.687  INFO  Push notification connection closed 
2022-08-04 22:42:05.268  INFO  Connected to station T8010P2321053646 on host 192.168.1.135 and port 26536 
2022-08-04 22:42:05.423  INFO  Push notification connection successfully established 
2022-08-04 22:42:05.427  INFO  Push notification connection successfully established 
`
When I try to add the integration (following 6.2.6 of the installation guide) I try to use either the machine IP or the docker IP and I get after some time the "Host/Port is wrong." message.

I'm new to this docker thing and I might have missed some basic steps, but I'm lost here.

**Comment by fuatakgun** [comment]
I am also not very good at docker. What do you put into Integration Configuration? is it 0.0.0.0 ?

**Comment by fuatakgun** [comment]
but your issue is specific network traffic between docker instances, nothing about integration or add-on. I advise you to look help in HA community forum.

**Comment by pinanunes** [comment]
Thank you!
If I put 0.0.0.0 it gives an immediate "Host/Port is wrong." error, If I put the IP of the machine (192.168.1.235) or the docker IP (172.17.0.3) it gives me a spinning wheel for some second then it gives the error message. That 0.0.0.0 is what got me puzzled if I need to find a way to start eufy server listening on another IP. 
You are right I do think is some error on the implementation from side. I'll try and find someone that managed to get it running on docker.
