### ISSUE TITLE
No stations found

### ISSUE THREAD

**Issue by DM0ore** [fuatakgun/eufy_security#419]
Hi, I've posted on bropat's page with the is query but it seems that it could have been the wrong place to post.  (https://github.com/bropat/eufy-security-client/issues/179)

![Eufy log](https://user-images.githubusercontent.com/107754295/183242877-48e7e6d8-04bb-418e-8691-6c9e093b09e0.JPG)

the config on the security Add-on is as above but i'm getting the following logs:-

2022-08-06 09:07:16.937  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-08-06 09:07:19.523  INFO  No stations found. 
2022-08-06 09:07:20.021  INFO  No devices found. 
2022-08-06 09:07:32.794  INFO  Push notification connection successfully established 
2022-08-06 09:17:21.941  INFO  No stations found. 
2022-08-06 09:17:22.286  INFO  No devices found. 

I'm new to home assistant so any help would be great.

**Comment by jouster1974** [comment]
got similar myself this morning...has been working fine until yesterday for a week or more

**Comment by jouster1974** [comment]
ignore...rebooted HASS OS device and got a captcha request for Eufy, all good  now

**Comment by DM0ore** [comment]
thanks, but tried that and still not working.

**Comment by fuatakgun** [comment]
try to log-in eufy mobile app using this your new account and validate if devices are there.
If multiple cases, creating another account solves these issues.
(double and triple check country code)

**Comment by DM0ore** [comment]
hi, i've made a new account on the app and the devices are all there but not showing as the station has been found. This is with the country code as US. 

If i change the country code as UK the log shows the below:-
![image 1](https://user-images.githubusercontent.com/107754295/188726182-2dfaab6d-2b0c-41fd-bb70-a554abd7a86d.JPG)
![2](https://user-images.githubusercontent.com/107754295/188726222-d5fae789-5d78-4ec2-b876-30510c05e98b.JPG)

**Comment by DM0ore** [comment]
Changed
