### ISSUE TITLE
Stream not working after home assistant start up

### ISSUE THREAD

**Issue by manos2400** [fuatakgun/eufy_security#42]
I followed README step by step and Eufy security doesn't appear in integration search for me to configure it. I have installed the addon and the integration from hacs. Only the addon works.

**Comment by manos2400** [comment]
I finally was able to configure it now there is another issue. Hass is taking too long to start up, but while it starting up all my cameras work perfectly. Once it finishes starting up it throws some errors and cameras stop working.
`2021-08-11 17:27:42 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream:
2021-08-11 17:28:05 ERROR (stream_worker) [libav.rtsp] method DESCRIBE failed: 404 Stream Not Found
2021-08-11 17:28:05 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://192.168.1.230/live0
2021-08-11 17:29:03 ERROR (stream_worker) [libav.rtsp] method DESCRIBE failed: 404 Stream Not Found
2021-08-11 17:29:03 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://****:****@192.168.1.168/live0`

**Comment by manos2400** [comment]
That's the errors when the system finishes starting up. From that moment and on cameras stop working.
`2021-08-13 11:22:15 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream:
2021-08-13 11:23:08 ERROR (stream_worker) [libav.rtsp] method DESCRIBE failed: 404 Stream Not Found
2021-08-13 11:23:08 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://192.168.1.230/live0`

Meanwhile the add-on logs are:
`2021/08/13 08:11:52 I [0/0] rtsp-simple-server v0.16.4
2021/08/13 08:11:52 I [0/0] [RTSP] TCP listener opened on :8554
2021/08/13 08:11:52 I [0/0] [RTMP] listener opened on :1935
2021/08/13 08:11:52 I [0/0] [HLS] listener opened on :8888`

**Comment by fuatakgun** [comment]
I see that this is RTSP stream published by your cameras, not P2P streaming.
When you receive this error, I suggest you try with a VLC player to reach out this address `rtsp://192.168.1.230/live0`

**Comment by manos2400** [comment]
I will try, though Is p2p better ? If yes how can I switch to it.

**Comment by fuatakgun** [comment]
no, RTSP from camera is much more faster and reliable than P2P.

**Comment by manos2400** [comment]
I get this in vlc : `Your input can't be opened:
VLC is unable to open the MRL 'rtsp://192.168.1.230/live0'. Check the log for details.`

**Comment by fuatakgun** [comment]
There is nothing we can do here, be sure that you are on the same network with homebase. If you or home assistant server cannot access homebase over network, you cannot watch rtsp then you have to rely on p2p.

**Comment by fuatakgun** [comment]
resolving due to inactivity
