### ISSUE TITLE
Jam lock status not triggering status change event in Home Assistant

### ISSUE THREAD

**Issue by jcrowegitHu8** [fuatakgun/eufy_security#421]
**Describe the bug**
For the Eufy door lock T8520.  The entity created inside Home Assistant (HA) for the lock status. (ex: 'lock.outside_garage_door').  When the lock detects a jam and the eufy_security integration update the attributes section of the entities state.  HA is not triggering a state change event as it should for any state or attribute modification.

**To Reproduce**
Assumptions:
1) you have a T8520 (or other Eufy door lock)
2) You have the eufy_security integration setup and working
3) Configure door lock to auto lock after 10 seconds

1. Create a sensor to hold only the lock status code in the state value
`
- platform: template
    sensors:
    outside_garage_door_lock_status_code:
        friendly_name: "Outside Garage Door Lock Status Code"
        value_template: '{{ (states.lock.outside_garage_door.attributes.state.lockStatus)}}'
`
2. Validate configuration
3. Reload 'Template Entities'
4. Confirm under dev tools you see the new sensor
5. Manually go to door with lock.
6. Unlock door
7. Open door so that auto locking will hit the door and cause a 'jam'
8. Once jam occurs
9. See that 'lock.outside_garage_door' entity with lockStatus attribute shows a 5 (which is correct)
10. See that the sensor entity show the unlocked status code of '3' (meaning unlocked).  As that's the last status event that HA triggered to update the sensor.

**Expected behavior**
I expect the door jam event to use appropriate HA services calls so that native HA events can be used for other automations.

**Screenshots**
Grafana graph showing that in all of my testing and causing jam errors the native HA template sensor never shows the 5 lock status indicating there was a jam.
![image](https://user-images.githubusercontent.com/17546577/183509187-98270cea-2fbd-4331-b384-7141e984aac3.png)

**Hardware Information about Home Assistant
Home Assistant 2022.8.0
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220802.0 - latest

**Hardware Information about Lock
- Eufy Door Lock with integrated WIFI (T8520S)

**Additional context**
I have a door sensor I use in conjunction here to give myself a notification on when the door is open and in the locked state.  This door jam notification is another edge case I want to be notified on.  But I can't because the lockStatus isn't triggering events.

**Suggestion: Maybe an easier workaround would be to:**
A)allow the lock.outside_garage_door state to have 3 values 'locked', 'unlocked', 'error'
B)Expose the lock status code as a separate entity so that your eufy_security integration just give me the value I want to be aware of anyway.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/595

**Comment by fuatakgun** [comment]
please move into alpha release and share your debug device sensor attributes so I can understand how jammed is working.

or share your device with me but it would be difficult.
