### ISSUE TITLE
Triggering locked using eufy_security integration resulting in a 'jam' does not show correct lockStatus attribute

### ISSUE THREAD

**Issue by jcrowegitHu8** [fuatakgun/eufy_security#422]
**Describe the bug**
When the physicals door is open and setup to cause a jam.  I use HA to tell the door to lock and the jam occurs.  The entity 'lock.outside_garage_door' attribute 'lockStatus' shows as 4 = locked.  When it should show 5 = jam

**To Reproduce**
Assumptions:

1. you have a T8520 (or other Eufy door lock)
2. You have the eufy_security integration setup and working

1. Unlock and physically open your door so that a jam will occur if locked remotly.
2. Confirm in 'Developer Tools' the entity 'lock.outside_garage_door' attribute 'lockStatus' shows as 3 = unlocked
3. Refresh the browser tab as  'Developer Tools' seems to have some caching of state
4. Using HA tell the door to lock
5. Confirm you heard the jam warning from the physical door lock.
6. Confirm in 'Developer Tools' the entity 'lock.outside_garage_door' attribute 'lockStatus' shows as 4 = locked and has status 'locked' too.
7. Refresh the browser tab as  'Developer Tools' seems to have some caching of state

**Expected behavior**
I expect that the entity 'lock.outside_garage_door' attribute 'lockStatus' shows as 5 = 'Mechanical anomaly' and has status of 'unlocked'.  This would be consistent with what happens when the door auto locks and causes a jam.

**Screenshots**
No screen shots the steps are enough to make the issue clean IMHO.

**Hardware Information about Home Assistant
Home Assistant 2022.8.0
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220802.0 - latest

**Hardware Information about Locks
- Eufy Door Lock with integrated WIFI (T8520S)

**Additional context**
This is a different issue than the other one that I raised.
https://github.com/fuatakgun/eufy_security/issues/421

Regardless both of these jam flows should result in the same state for the 'lock.outside_garage_door'  so if you can make note or unit test this that would be great.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/595

**Comment by fuatakgun** [comment]
please move into alpha release and share your debug device sensor attributes so I can understand how jammed is working.

or share your device with me but it would be difficult.

**Comment by jcrowegitHu8** [comment]
You can close the issue.  I'm unable to reproduce.  Everything seems to be working as expected.
