### ISSUE TITLE
Floodlight Camera motion detection stopped working

### ISSUE THREAD

**Issue by eufysecurity** [fuatakgun/eufy_security#425]
**Describe the bug**
T8420X Floodlight Camera motion detection stopped working. It was not working before 2.4.0, it works on 2.4.0, and stopped working on 2.6.0

**To Reproduce**
1. Go to the T8420X Floodlight Camera device info page
2. Trigger motion on the T8420X Floodlight Camera
3. it is not recorded in the log

**Expected behavior**
When motion is triggered on the T8420X Floodlight Camera, the motion sensors should go from "clear" to "detected"

**Hardware Information about Home Assistant
Home Assistant 2022.8.3
eufy_security v2.6.3
eufy_security_addon 0.9.4

**Hardware Information about Cameras
- T8420X Floodlight Camera
- Live Streaming Protocol: P2P

**Comment by alexeiw123** [comment]
Also seeing this with T8422 - although I'm not using the motion for anything yet, so I wouldn't have noticed if it is working under some conditions.

O.T. but I notice your github name - are you affiliated with eufysecurity or just made the name for these contributions?

**Comment by eufysecurity** [comment]
Just made the name for these contributions

**Comment by droiddavid91** [comment]
Using T8424 floodlight cameras and this has never worked for me. I always assumed it was just not supported.

**Comment by fuatakgun** [comment]
can you try with previous add-on versions? there is not a big change in integration itself, but many things are moving in add-on end.

**Comment by epzy** [comment]
> Using T8424 floodlight cameras and this has never worked for me. I always assumed it was just not supported.

Same for me with T8423 and been using this integration for months. Everything else works great but binary sensors never update. I've tried re-adding the camera to the eufy app, deleting and reinstalling various versions of the add-on, integration and the repo. My camera settings are all as described in the notes so  I've just accepted that the feature isn't supported.

Other than that, it's a great add-on.

**Comment by cistym** [comment]
Also having the issue with my T8424. Removed camera from app and re-added, shared to different account, reinstalled everything.  There's a flag blowing in the wind triggering the app over and over and logs say "Push notification connection successfully established" but has never updated a motion sensor.

**Comment by eufysecurity** [comment]
Issue is on bropat side
