### ISSUE TITLE
Cannot control second camera - addon cannot connect to station

### ISSUE THREAD

**Issue by ishioni** [fuatakgun/eufy_security#426]
**Describe the bug**
I added a second Eufy Indoor 2K camera to my setup. The first has worked for many months with this integration, using it for most of the logic control of the camera, such as enabling detections according to schedule and disabling the cameras and whatnot. I'm not really interested in streaming per se, i have my own solution rolled out for that. However, after adding the 2nd one, all the controlls for it showed up, but they don't work at all, and the addon returns

```
2022-08-12 12:07:46.576  INFO  Timeout connecting to station T8410P312210537B 
2022-08-12 12:08:06.584  ERROR P2PClientProtocol.lookup(): station: T8410P312210537B - All address lookup tentatives failed. 
```

It works fine for the first one though

```
2022-08-12 12:07:23.306  INFO  Connected to station T8410P3121384AD1 on host 10.1.3.16 and port 11697 
2022-08-12 12:07:31.791  INFO  Push notification connection successfully established 
```

Both cameras are on the same IOT network, there's no special thing that I do to one or the other. Both have rtsp enabled and working, but again, I don't use that part of the integration itself

**To Reproduce**
1. Add a second camera to eufy app
2. Share it with the HA addon user (the user has admin rights of course)

**Expected behavior**
The camera controls should work

**Hardware Information about Home Assistant
Newest HAOS running under a VM

**Hardware Information about Cameras
- Eufy 2K Indoor pan&tilt
- Live Streaming Protocol: not applicable

**Additional context**

**Comment by leonardpitzu** [comment]
same for me

**Comment by fuatakgun** [comment]
There is a recent release candidate which will fix some of these connection issues  ut it requires a revamp inside integration to be compatible, give me couple of days

**Comment by thomasgeens** [comment]
Same issue here, but also noticed that it tries to resolve the address for P2P instead of RTSP.

`2022-09-12 13:32:54.410  ERROR P2PClientProtocol.lookup(): station: T8410P31221310F9 - All address lookup tentatives failed. 
2022-09-12 13:32:54.416  INFO  Timeout connecting to station T8410P31221310F9 `

**Comment by thomasgeens** [comment]
This issue seems to duplicate #448

**Comment by ishioni** [comment]
> There is a recent release candidate which will fix some of these connection issues but it requires a revamp inside integration to be compatible, give me couple of days

Not pushing, but wanted to know if there's any movement on this?

**Comment by Palmke** [comment]
This seems to be the most populated issue regarding the connection problem.
@fuatakgun I am already on that RC version (`develop` branch) and I still get the error.

I think this is not the fault of any of the Github projects, but rather a problem on eufy's side.
If you open the app, it sometimes (depending on how many times you open it) show the message "network not available".
In certain cases, when trying to view the live footage of the cam, it just times out saying "cannot connect to camera".

**Comment by pataar** [comment]
FWIW: I have the same problem with a double T84003W2

**Comment by pataar** [comment]
Probably fixed in the next release: https://github.com/bropat/eufy-security-ws/issues/135

**Comment by ishioni** [comment]
The newest update not only fixed my problem but made streaming from the cameras work ootb. Thanks, closing this now
