### ISSUE TITLE
devices repeatedly dropping off of system...fine on Eufy app

### ISSUE THREAD

**Issue by jouster1974** [fuatakgun/eufy_security#428]
Im getting daily repeat issues where Eufy security integration is locking up/freezing...but on the Eufy app itself all is good

The only way to fix it is to restart the add-on and then the app, when re-adding the integration I get a captcha request for some unknown reason

below is a copy of the logs from the add on 

![image](https://user-images.githubusercontent.com/15368005/184836656-30ec6c43-5fc0-4a7f-a362-13f2f337213f.png)

adding to add on link as well in case this is more related there

**Comment by sbeukers** [comment]
Maybe this is ralated?
[https://github.com/fuatakgun/eufy_security/issues/438]
Have you found anything useful yet?

**Comment by fuatakgun** [comment]
please create an issue under eufy-security-ws repository
