### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by anoopr** [fuatakgun/eufy_security#429]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
I've seen several other references to this, but my home assistant log is getting spammed with this error:

`home-assistant   | 2022-08-16 03:33:53.776 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/config/custom_components/eufy_security/__init__.py", line 60, in update
home-assistant   |     coordinator.async_set_updated_data(coordinator.data)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in async_set_updated_data
home-assistant   |     self.async_update_listeners()
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
home-assistant   |     update_callback()
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
home-assistant   |     self.async_write_ha_state()
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
home-assistant   |     self._async_write_ha_state()
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
home-assistant   |     state = self._stringify_state(available)
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
home-assistant   |     if (state := self.state) is None:
home-assistant   |   File "/config/custom_components/eufy_security/alarm_control_panel.py", line 240, in state
home-assistant   |     return CODES_TO_STATES[current_mode]
home-assistant   | KeyError: -1
`

**To Reproduce**

**Expected behavior**
I would expect to not see this error
**Screenshots**

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Indoor Cam Pan&Tilt
- Indoor Cam
- T8203 (Doorbell Dual)
- Floodlight Cam
- Live Streaming Protocol: RTSP

**Additional context**

**Comment by fuatakgun** [comment]
i need to debug this after you share this device with me following readme.

If you prefer simultaneous sharing and debugging together, i will try to set a fixed time every weekends, we can work together

**Comment by fuatakgun** [comment]
please test with alpha version v5.x.x
