### ISSUE TITLE
Capture Keypad User

### ISSUE THREAD

**Issue by vaderag** [fuatakgun/eufy_security#430]
The Eufy Keypad allows you to set multiple access codes and assign a name to these users.
Capturing the identity of these users is important for taking role based actions depending on user trust level 
e.g. I may not wish to turn off cameras if a certain contractor is doing work, but if my wife disarms then I would

It would be great for the user who caused the disarm event to be captured as part of the payload so that actions can be taken on this.

**Comment by vaderag** [comment]
FYI I also posted related request over here in Eufy Security WS
https://github.com/bropat/eufy-security-ws/issues/128

**Comment by fuatakgun** [comment]
please update here when it is implemented
