### ISSUE TITLE
Getting error Livestream for device T8200**** could not be stopped, because it is not running in logs

### ISSUE THREAD

**Issue by RemotecUK** [fuatakgun/eufy_security#431]
**Describe the bug**
I receive the following error in the log file of the EUFY Security Add On:

Livestream for device T8200*** could not be stopped, because it is not running

**To Reproduce**
Restart the add on. It seems to start fine. It reports:

```
2022-08-18 09:48:06.917  INFO  Push notification connection closed 
2022-08-18 09:51:07.402  INFO  Push notification connection successfully established 
```

Then some time later I receive:

```
2022-08-18 14:31:50.046  ERROR Message error 
 LivestreamNotRunningError  Livestream for device T8200**** could not be stopped, because it is not running
error stack:
• message_handler.ts:146 handle
    src/lib/device/message_handler.ts:146:31
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• server.ts:103 receiveMessage
    src/lib/server.ts:103:21
```

My door bell card in home assistant no longer updates. 

The ringing sensor no longer changes state when someone presses the door bell.

**Expected behavior**
Would like to know how to stop the error message occuring as I think when it does then I no longer get updates in home assistant.

**Hardware Information about Cameras**
- Camera Model: Video Doorbell 2K (Wired)

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/592
