### ISSUE TITLE
Username obfuscated but password visible in Add On configuration

### ISSUE THREAD

**Issue by RemotecUK** [fuatakgun/eufy_security#432]
**Describe the bug**
In the add on configuration, my username is obfuscated with asterix, however my password is visible.

**To Reproduce**
1. Go to add on configuration

**Expected behavior**
Username should be shown.
Password should be obfuscated.

**Screenshots**

![image](https://user-images.githubusercontent.com/11721074/185440521-16753104-0080-4403-951b-79fa4d43e3aa.png)

**Comment by fuatakgun** [comment]
will be released in next version of add-on
