### ISSUE TITLE
2FA Doesnt work with Eufy

### ISSUE THREAD

**Issue by Jlewie** [fuatakgun/eufy_security#433]
I am unable to use 2fa for my account if I want the integration to work.

**Comment by j-fuentes** [comment]
I am also trying to use 2FA with eufy and this extension.

The underlying service seems to support 2FA and the API has commands to set the code: https://bropat.github.io/eufy-security-ws/#/api_cmds?id=set-2fa-verify-code

But apparently this is done implemented in the auth flow of this extension.

**Comment by fuatakgun** [comment]
Please check existing issues we might have discussed this multiple times :-) , it was unnecessary complex for me to setup captcha, i don't want to spend time on 2fa, but feel free to raise a PR on this

**Comment by j-fuentes** [comment]
I see there is another issue where this is being discussed: https://github.com/fuatakgun/eufy_security/issues/407

Sorry!

You can close this one.

**Comment by fuatakgun** [comment]
Again, i am open to any contributions:-)
