### ISSUE TITLE
Garbage image through webrtc

### ISSUE THREAD

**Issue by Xitro01** [fuatakgun/eufy_security#434]
When I try to stream the camera over WebRTC I get garbage.
Normal streaming through RTSP/P2P works just fine.
I'm trying to use WebRTC for faster streaming, as I want to use the image in a popup.

Any ideas what the cause of this issue is?

**Screenshots**
![Knipsel](https://user-images.githubusercontent.com/19844787/185597976-0878ea0d-eeb5-4e1e-9aaf-316fb50854d2.PNG)

**Hardware Information about Home Assistant
NUC running HASSOS (Proxmox)

**Hardware Information about Cameras
- Eufy Doorbell 2K Wired
- Live Streaming Protocol: RTSP and P2p

**Comment by Xitro01** [comment]
I restarted literally everything, but did not restart the doorbell. After restarting the doorbell, it worked.

**Comment by Xitro01** [comment]
Restarting the doorbell fixes it for ~2 minutes. Any ideas?

**Comment by fuatakgun** [comment]
have you checked if native streaming (not webrtc) is working fine in home assistant?

**Comment by Xitro01** [comment]
> have you checked if native streaming (not webrtc) is working fine in home assistant?

Yes, that works fine. But with a big delay. Actually not seeing a difference using WebRTC, maybe I did not implement this correctly.

**Comment by DrSpaldo** [comment]
I am getting a similar scenario with the SoloCam S40

**Comment by chicknlil** [comment]
Oh good, I thought my total newb ass did something wrong - but seeing this post makes me feel MUCH better.  I am having this exact same problem with this exact same doorbell.  I'm running Home Assistant Blue / Hardkernal Odroid-N2

**Comment by fuatakgun** [comment]
New version of integration allows to be integrated with go2rtc or other rtsp to web providers which might help to remove these codec issues.
