### ISSUE TITLE
Integration No Longer Available

### ISSUE THREAD

**Issue by CameronMcGuffie** [fuatakgun/eufy_security#436]
Searching for the integration and it no longer exists, heading to the project page on the HACS website and it now gives a 404 - https://hacs.xyz/docs/repositories/integration/fuatakgun_eufy_security I'm not sure if this is a geolication issue (I'm in Australia) or if the integration has been pulled.

**Comment by fuatakgun** [comment]
You can manually add repository and continue to installation, i will take a look at this

**Comment by CameronMcGuffie** [comment]
Do you mean via add ons? The WS server is up, I cannot determine how to add the front end other than this method. I can see the HomeBase detected and connected but need the UI to manage I guess.

**Comment by mateszlanka** [comment]
+1, integration is not available. During the installation process after downloading the integration in HACS (and restarting Home Assistant) the Configure -> Integrations -> Add Integration won't list Eufy Security.

**Comment by mateszlanka** [comment]
After several restarts and I left it there overnight and the Integration would appear for me this morning.

**Comment by rgruener** [comment]
I have the same issue, with the integration not available (the add on was installed and looks to be running properly). Will see if anything changes tomorrow.

**Comment by CameronMcGuffie** [comment]
Yea I have had it running for 5 days now and no change, I'm not entirely certain that it can change by itelf @mateszlanka can you confirm that you got the fuatakgun eufy security integration and not the standard eufy one?

**Comment by mateszlanka** [comment]
The integration/documentation redirects to the `fuatakgun`'s github so I can confirm I'm using the correct one.
I'm running it on a Raspberry Pi 4, with Home Assistant OS, and had several restarts and re-download of the repository in HACS, but I'm not sure what helped finally.

**Comment by CameronMcGuffie** [comment]
Ok this is completely my fault as I am new to Home Assistant and didn't read up on HACS. I did not realise that it is an Add-On that must be installed (for others with this issue - https://www.youtube.com/watch?v=zlaJrepZl2E). Now I can find the integration fine as I am doing it the right way.
