### ISSUE TITLE
No Alarm events with eufy-security-ws 0.9.3 or 0.9.4

### ISSUE THREAD

**Issue by hipsi** [fuatakgun/eufy_security#439]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

Since updating eufy-security-ws to 0.9.3 or 0.9.4 I stopped getting homebase alarm events in HA.  When I checked the container terminal I noticed that there were only INFO lines when there was a guard mode change.

![image](https://user-images.githubusercontent.com/14834846/186110896-8ac14f77-5b9d-49f5-aff6-a47a1bb14b9e.png)

This is what it looks like when I set the alarm off with eufy-security-ws 0.9.2

![image](https://user-images.githubusercontent.com/14834846/186112230-c4168943-868a-4b3d-8783-ef0fc46e53db.png)

"alarmType: 8" seems to be the alarm triggering, and "alarmType: 16" I think is me resetting the alarm from the app.

in Bropat's github they're telling me that there's no loss of data in the p2p data in the latest version, but I don't understand what that means.  Only that I see less info in the terminal, and it doesn't seem to pass through to the integration.

**Comment by haggis663** [comment]
Try using bropat/eufy-security-ws:1.0.0-rc.1 as the docker base. So far (a few hours), this has fixed the issue for me.

**Comment by hipsi** [comment]
@haggis663 so you're seeing the alarm trigger notification on 1.0.0-rc.1?  I just tried it and got nothing at all when the alarm triggered.

**Comment by haggis663** [comment]
So far (2 weeks) I haven't had any problems with Eufy integration. I can pick up  all the alarms being set, but I haven't tried detecting the alarm trigger.
