### ISSUE TITLE
When live stream is off, show picture of last event

### ISSUE THREAD

**Issue by conorlap** [fuatakgun/eufy_security#44]
**Describe the solution you'd like**
A small feature request to show a picture of last event when live stream is off. Currently it will show the last capture image from when live stream was running (including timestamps on top right corner) after a live stream has occurred. It will only update to 'last event' when a new event occurs after the live stream. 
My preference would be that this reverts back to the 'last event detected' image i.e.. motion detection or doorbell button press.

**Comment by fuatakgun** [comment]
hey. I have been checking this today and I have seen that whenever RTSP or P2P livestreaming finished, I start getting picture from previous motion triggered event, so livestreaming images will be gone.

**Comment by fuatakgun** [comment]
fixed over here: https://github.com/fuatakgun/eufy_security/commit/19fe9d924358c2b2f0569085167521f202725afb
