### ISSUE TITLE
LivestreamAlreadyRunningError

### ISSUE THREAD

**Issue by jasonwfrancis1** [fuatakgun/eufy_security#440]
Hi,

I have followed the install instructions and cannot get video from my Doorbell to stream. I’m getting snapshots and sensor data, but cannot stream.

The add on reports the below error, every time I stream. And it seems to be connecting to and disconnecting from the Homebase a lot.

The streaming source type and address sensors report they “became unavailable”

2022-08-23 23:00:00.312  INFO  Connected to station T8010P232050271B on host 192.168.11.53 and port 10234 
2022-08-23 23:00:01.241  ERROR Message error 
 LivestreamAlreadyRunningError  Livestream for device T8210P0020500575 is already running
error stack:
• message_handler.ts:139 handle
    src/lib/device/message_handler.ts:139:31
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• server.ts:103 receiveMessage
    src/lib/server.ts:103:21
2022-08-23 23:00:08.990  INFO  Disconnected from station T8010P232050271B 
2022-08-23 23:00:14.027  INFO  Connected to station T8010P232050271B on host 192.168.11.53 and port 14831 
2022-08-23 23:00:21.930  INFO  Disconnected from station T8010P232050271B

**Comment by fuatakgun** [comment]
it is not expected to disconnect and reconnect multiple times, we should first found out why it is dropping.

this might be related: https://github.com/bropat/eufy-security-ws/issues/130

**Comment by jasonwfrancis1** [comment]
Yes, I am also running in Hyper-V. I will try on another platform also and see what the result is.

Thank you I will report back

Sent from my iPhone

On 26 Aug 2022, at 09:16, Fuat Akgün ***@***.***> wrote:

﻿

it is not expected to disconnect and reconnect multiple times, we should first found out why it is dropping.

this might be related: bropat/eufy-security-ws#130<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbropat%2Feufy-security-ws%2Fissues%2F130&data=05%7C01%7C%7C2c72a7613c28478eb20c08da873b4b96%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637970985994037344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=noEN%2BvZ5UMF6jwkhXlZ0gN5Dl8ec6ykDPdsuAA3OA7k%3D&reserved=0>

**Comment by fuatakgun** [comment]
Any updates?

**Comment by jasonwfrancis1** [comment]
Apologies I’ve been on vacation, I’m planning to migrate off of hyper v this weekend so I’ll let you know!

Sent from my iPhone

On 15 Sep 2022, at 21:28, Fuat Akgün ***@***.***> wrote:

﻿

Any updates?

**Comment by beareogaming** [comment]
i also run into this issue, feel free to lmk if you want help duplicating, my stream tends to run for a random period of time, goes idle and will not recover until i reboot the addon several times or turn it off, wait 5 minutes and turn it back on.
![image](https://user-images.githubusercontent.com/17842226/192033602-b586f939-0e3b-4280-ad51-1e4fa99a9780.png)

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/592

**Comment by trouble2** [comment]
I kind of have the same issue:
![image](https://user-images.githubusercontent.com/1827559/222548963-20d5db89-aa3e-4d17-bf9b-4a55b6116bc2.png)

In HA it says: Cannot call service camera/turn_on. ('Camera (%s) does not support RTSP Stream', 'Frontdoor')

When I checked the log it was reporting about every second, so I disabled that:

![image](https://user-images.githubusercontent.com/1827559/222549877-af0d80c5-fb32-4f58-ad9f-8bc6400c6fc5.png)

So what can I do?

**Comment by trouble2** [comment]
Some more logs from the docker container:
![image](https://user-images.githubusercontent.com/1827559/222551280-a414e7e8-d196-4d60-b250-3ca57c443f5b.png)


![image](https://user-images.githubusercontent.com/1827559/222550892-3d9a9ee1-3f8f-40cb-baeb-9467e0ea6d05.png)

**Comment by trouble2** [comment]
And from the rtsp server:
![image](https://user-images.githubusercontent.com/1827559/222551669-1155d950-481e-460d-964c-e9d70189fc17.png)
