### ISSUE TITLE
Support for SoloCam L20 T8122

### ISSUE THREAD

**Issue by epleypa** [fuatakgun/eufy_security#441]
Currently it doesn't appear the SoloCam L20 T8122 is being supported or detected, not seeing any errors in the logs either. Is it possible for this camera to be supported? Happy to test if there is a place in the code to enable - this is a battery powered camera with a spotlight and alarm.

`2022-08-24 19:10:19.483  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 `

**Comment by fuatakgun** [comment]
You should work with @bropat through his eufy-security-ws repository, share your device with him and he is very capable of adding support. I am also very closely tracking issues there

**Comment by epleypa** [comment]
Great thanks! Will open issue over there
