### ISSUE TITLE
Failed to start addon Home Assistant

### ISSUE THREAD

**Issue by donjoe1234567** [fuatakgun/eufy_security#443]
Am using VirtualBox VM with official HA image. Added repository, installed addon and changed username/password. When trying to start addon, get this error:

Failed to start add-on
Image bropat/eufy-security-ws:0.9.4 does not exist for addon_3a26b21d_eufy_security_addon

**Comment by fuatakgun** [comment]
please check supervisor logs, I suggest you to retry to install, seems to be a system issue

**Comment by donjoe1234567** [comment]
Seem to be no errors in the logs, deleted and reinstalled everything, same issue occurs

**Comment by fuatakgun** [comment]
There should be something on supervisor about start request, have you checked it?
