### ISSUE TITLE
Integration updates break stored fingerprints in Smart Lock (T8520N)

### ISSUE THREAD

**Issue by joekingmo** [fuatakgun/eufy_security#445]
When I update the Eufy Security integration in Home Assistant, my smart lock (T8520N) will no longer accept previously working fingerprints. This has happened to me for the last (2) updates, including the most recent update (v2.7.0). So far, I've had to re-enroll everyone's fingerprint every time I updated the integration. The first occurrence I wrote it off as a fluke, however I'm beginning to think I have a real issue this time. 

**Note:** Core functionality of the integration remains un-changed, it just "corrupts" my lock fingerprints (they still show up in the Eufy app, but do not work)

DoI have something mis-configured? I can't imagine this is expected behavior. Happy to provide whatever logs/information you may need. 

I am running:
```
Home Assistant 2022.8.7
Supervisor 2022.08.3
Operating System 8.5
Frontend 20220802.0 - latest
```
```
Eufy Security Add-on 
Current version: 0.9.4 
``` 
```
Eufy Integration
Version: v2.7.0
Author: fuatakgun
```

**Comment by jcrowegitHu8** [comment]
I just updated to the latest version too and am not experiencing this issue.  One difference may be, that I created a separate Eufy account for the HA integration so that I can tell when the integration does something, vs my phone application.

I'll continue my testing and will report back if I do notice the same problem.

**Comment by joekingmo** [comment]
I have a second eufy account for the integration as well. Interested in hearing if this  a re-producible issue.

**Comment by fuatakgun** [comment]
If you think add-on or integration is causing this, let's bring more examples and data points, but i neither have a finger print nor heard any similar problems, i highly doubt it is the case

**Comment by joekingmo** [comment]
@fuatakgun I can confirm that the integration upgrade from 2.7.0 to 2.8.0 did NOT impact my fingerprint smart lock. It must have been a fluke. This upgrade worked without issue.
