### ISSUE TITLE
C24 indoor cameras not working correctly 

### ISSUE THREAD

**Issue by joshmd** [fuatakgun/eufy_security#448]
I just added some C24 indoor cameras to my setup and when I refresh the integration in home assistant they show up as entities fine, but none of the toggle buttons associated with the cameras do anything.

For example trying to toggle the Enable switch turns of for a split second before turning back on. I also cannot change the armed status of these cameras no matter what I do.

I have a battery powered eufy doorbell connected to my hub 2 which works fine with both these use cases.

**Comment by wolfjank** [comment]
I've got exactly the same Problem. 
- **Doorbell is working**. (T8200)
- **Indoor Cam is not**.  (T8410 - P24 - Indoor Cam Pan&Tilt)
 
In Eufy Addon Log the Indoor Cam moreover shows the following Error: 
ERROR P2PClientProtocol.lookup(): station: T8410P31220916BB - All address lookup tentatives failed.

**Comment by joshmd** [comment]
I replaced the C24 indoor cams with C22 outdoors and they are working fine FYI.

**Comment by wolfjank** [comment]
Well I don’t want to replace my indoor cam by another product. So this won’t help me.
