### ISSUE TITLE
Enabled and Motion Detection switches don't update in HA after being updated in EufySecurity app

### ISSUE THREAD

**Issue by oNSXo** [fuatakgun/eufy_security#449]
**Describe the bug**
Reporting of the "Enabled" and "Motion Detection" switches do not update in HA after being updated within the EufySecurity app.

**To Reproduce**
1. Observe Camera Enabled switch set to On in HA
2. Open EufySecurity app and click on Camera
3. Flip the top switch to Off
4. Observe Camera Enabled switch in HA is still on (and continues to be on even after the cloud polling interval)

**Expected behavior**
Switch should eventually match current state within the app

**Additional context**
I've tried triggering the force_sync service and even restarting HA with no avail.  However, if I flip the switch from within HA, that state does get set correctly and if I reopen the EufySecurity app, I do see the result of the action taken within HA.

**Comment by Matt3ra** [comment]
I have the same issue.

I use my Eufy cameras as motion sensor on the outside of my house (global motion sensor) and the motion is not updated in HA.
And due to that the automation has no trigger.

**Comment by SHHA24** [comment]
Similar issue - Eufy Door Bell camera, get Eufy app notification of Person , Motion or Door Bell -> but this doesn't update the HA integration always. 
It seems to require the Integration to be reloaded, and then it works fine for a period of time, but then stops reporting. 

No errors in the logs, push notification says connected....  

2022-09-09 12:46:25.787  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-09-09 12:47:26.104  INFO  Connected to station T.......   on host 192.168.0.20 and port 28959 
2022-09-09 12:49:36.021  INFO  Push notification connection successfully established

**Comment by gerardsyd** [comment]
I'm having the same issue. It was working fine but seems like something is broken in the new version. 
Ringing sensor not working for me although unchecking:
Fix Binary Sensor States (True/False to On/Off)
seems to make the notifications work. So I wonder if it has something to do with the logic of True / False to On/Off that has the issue?

**Comment by LucaBors** [comment]
Hi, can someone look in this case? Even in the last version there’s still the problem.

**Comment by fuatakgun** [comment]
you can give a try on alpha version v5.x.x

**Comment by oNSXo** [comment]
> you can give a try on alpha version v5.x.x

How do you upgrade to the alpha version.
