### ISSUE TITLE
Alarm triggered when switching modes during "leave delay"

### ISSUE THREAD

**Issue by TruffelNL** [fuatakgun/eufy_security#452]
**Describe the bug**
When switching from one mode to another, the HA integration receives a "triggered" event during a "leaving delay". 
To make it more precise: I have an "Away" mode which has a 30 second time to leave the house. All possible triggers are disabled during that time. When I let that mode enter it's state (so after 30 seconds) and then switch back, no "triggered" state is received. But when I switch to another mode during this 30 second delay (for instance, I forgot something and need to go back inside and switch to another mode) the HA integration receives a "triggered" message. 

**To Reproduce**
1. Setup a mode with a 30 second "leave delay".
2. Switch to that mode using the passcode on the keypad or via the app.
3. While the countdown timer sounds/shows switch back to another (lower/less secure) mode. E.g. "off" or "home".
4. See "triggered" status appear in Home Assistant.

**Expected behavior**
I expected that the modes would switch but that the integration would not receive/send/process a "triggered" message.

**Screenshots**
Node-Red debug message of received state. 
<img width="284" alt="Schermafbeelding 2022-09-03 om 11 38 18" src="https://user-images.githubusercontent.com/16107161/188265047-5a6b66d8-ace4-4e11-8f6d-f77149253370.png">

Logging from Eufy security add-on:
```
2022-09-03 09:34:39.066  INFO  Alarm mode for station T8010N23214816C9 changed to: undefined 
2022-09-03 09:34:40.310  INFO  Received push notification for changing guard mode 
{
  guard_mode: 6,
  current_mode: 6,
  stationSN: 'T8010N23214816C9'
}
```

**Hardware Information about Home Assistant
RaspberryPi 4

**Comment by fuatakgun** [comment]
alpha version should fix this (v5.x.x)
