### ISSUE TITLE
RTSP addon integration

### ISSUE THREAD

**Issue by SirLouen** [fuatakgun/eufy_security#457]
Do you know if it's possible to add some extra parameters through YAML to the RTSP add-on integration you have implemented?

For example, a max_muxing_queu_size and some presets?

**Comment by fuatakgun** [comment]
We can update add on and include extra args for this purposes. Would you be interested in raising the PR?

**Comment by SirLouen** [comment]
> Would you be interested in raising the PR?

What do you mean?

I would go like Frigate does
https://github.com/blakeblackshear/frigate-hass-addons/blob/main/frigate/README.md

They simply add a `frigate.yml` in the root
So basically, a YAML like simple_rtsp.yaml or something like that might do the trick.

**Comment by fuatakgun** [comment]
any environment variable `-e RTSP_XYZ=value` will be passed to add-on. that is how I am passing some variables
