### ISSUE TITLE
What is the streaming URL?

### ISSUE THREAD

**Issue by Colorado4Wheeler** [fuatakgun/eufy_security#459]
I can get the RTSP stream to work in HomeAssistant but cannot attach to it via VLC or SecuritySpy.  I had SecuritySpy test every camera profile it knows (which is quite a few) and I can see all the errors in the RTSP log but none of them connect to the stream, so I can see the conversation but nothing streams back.

What is the URL that I should use to access the stream?  I tried rtsp://home_assistant_ip:8554 by itself but it doesn't do the trick so I presume I need a path on it.

**Comment by fuatakgun** [comment]
There is a sensor called streaming_source, you can use it

**Comment by Colorado4Wheeler** [comment]
Thanks for the suggestion @fuatakgun, I had noticed that once before but it hadn't registered with me where to find it again after when I saw it since it is only active when the EUFY streaming has been turned on.
