### ISSUE TITLE
Not getting option for Keypad in Home assistant

### ISSUE THREAD

**Issue by domemshur** [fuatakgun/eufy_security#46]
When I do this intergration, nothing gets created or populates in home assistant for my eufy alarm station. My Motion sensors show up, but not my keypad.

Thanks

**Comment by fuatakgun** [comment]
Hi, let's track this over here: https://github.com/fuatakgun/eufy_security/issues/45

Regarding to having a specific entity for keypad, we need to think more on this. Keypad is just a gateway for homebase alarm system, correct me if i am wrong, i don't own one just guessing.
