### ISSUE TITLE
Read nightvision state of camara

### ISSUE THREAD

**Issue by mauricehofman** [fuatakgun/eufy_security#461]
Is it possible within HA to ask a certain state of a camera?

I want to make an automation based on the state of the nightvision of one of my camera's (on / off). I think to bropat uefy client has an option to request this with the following command: `getPropertyValue(PropertyName.DeviceNightvision)`

How can i do this within HA?

**Comment by dadrij** [comment]
This is a very interesting option. I was looking for the same. But I can not read the state of the nightvision of the camera in HA. This would be very good update.

**Comment by fuatakgun** [comment]
night vision can be enabled or disabled, but it is not telling the exact state of night vision. depending on environment light, device decides to use it or not.

new version of integration is exposing this switch to configure night vision (alpha - v5.x)
