### ISSUE TITLE
Authentication problems

### ISSUE THREAD

**Issue by sythesigh** [fuatakgun/eufy_security#462]
Logger: homeassistant.config_entries
Source: config_entries.py:371 
First occurred: 21:16:34 (1 occurrences) 
Last logged: 21:16:34

Config entry '172.18.0.4' for eufy_security integration could not authenticate: Warning: Captcha required - Go to Configurations page for Eufy Security Integration to enter the code

Doesn’t matter how many times I enter the captcha, or change the password or delete and reload the integration, I keep getting either this message, or ‘only a single instance is allowed’. I do not have this integrated anywhere else 🤷‍♂️

**Comment by kaystrobach** [comment]
Have you setup a second account? Having one for your self and a second one for HA fixed that for me.

**Comment by sythesigh** [comment]
after several attempts i have now managed to get this working again. i am now struggling with calling its services from the frontend lovelace card, so i will close this issue.
