### ISSUE TITLE
Cannot get a working stream

### ISSUE THREAD

**Issue by cryd-s** [fuatakgun/eufy_security#463]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**

**To Reproduce**

**Expected behavior**
want a stream from my camera in HA

**Screenshots**

**Hardware Information about Home Assistant
Raspi4 8gb with HassOS overclocked to 2ghz

**Hardware Information about Cameras
- 2k Dual new model - T8213

**Additional context**
![image](https://user-images.githubusercontent.com/47699362/190890387-362db49b-a208-450a-9c87-a85585d96e7d.png)
![image](https://user-images.githubusercontent.com/47699362/190890400-c1a5f394-7667-4d29-93cc-83cf70f531fe.png)
![image](https://user-images.githubusercontent.com/47699362/190890413-3f92364f-d633-4625-b8f3-baf797114e27.png)
![image](https://user-images.githubusercontent.com/47699362/190890431-275cbf98-5b90-4e3c-a8f0-147847fbdbc3.png)
![image](https://user-images.githubusercontent.com/47699362/190890451-b240a510-8780-4e55-b222-627dfa5c35c0.png)

If starting stream:

![image](https://user-images.githubusercontent.com/47699362/190890464-93bfaebf-7873-4954-8506-9cc6e72b1a57.png)

![image](https://user-images.githubusercontent.com/47699362/190890491-44220d26-364d-4c21-9e1b-2e296ea66378.png)

**Comment by cryd-s** [comment]
And now my eufy Akku is empty in round 24 Hours

**Comment by escapethewormhole** [comment]
Same issue with my 8213 2k dual.

**Comment by cryd-s** [comment]
is there any solution ?

**Comment by lancer73** [comment]
> in Home Assistant i see only a grey image verywhere the stream is used. I think this is a codec issue, what am i missing ?
> 
> ![image](https://user-images.githubusercontent.com/31311307/195443633-569d5d35-a027-4e6c-ac7f-93ff7ec49807.png)

I saw the codec hevc in a couple of screenshots. It started working  for me when I changed the "video encoding format" to low in the Eufy security app. (I have stream quality set to high).

It switches the codec to h264 then. You might need to restart the Eufy security addon and home assistant after that.

**Comment by S7Studio** [comment]
This is still giving issues. I lowered the streaming quality to low on the camera. Restarted HASS and the Homebase, restarted the addons, still grey. Also disappointed in having a 2 or 4k camera and having to use the 'low setting' anyway.. sigh. Any solutions?

**Comment by kalyway101** [comment]
I also have the same issues as mentioned by others in this thread. I have the T8203 (Wired Dualcamera Variant). I have set my compression to low. All the other information from the doorbell is coming in without any problems. It's just trying to live stream that gives me errors.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/592
