### ISSUE TITLE
ptz_360 service missing?

### ISSUE THREAD

**Issue by jeroenterheerdt** [fuatakgun/eufy_security#467]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Looking at https://github.com/fuatakgun/eufy_security/issues/286 it looks like there should be a service called 'ptz_360', but I am not seeing that for my Eufy camera which definition supports this behavior. All other services work fine, I am able to move in all four directions using PTZ and the stream works beautifully. I was just wondering about getting the 360 movement to work as well.

**Comment by fuatakgun** [comment]
you are right, will be fixed in new version
