### ISSUE TITLE
RTSP streams authentication

### ISSUE THREAD

**Issue by haggis663** [fuatakgun/eufy_security#468]
The default Eufy rtsp streams are digest encrypted. It would be very good to be able the RTSP plugin to pick up the security values from a config file / environment variables so that the streams can stay encrypted rather than anonymous.

**Comment by fuatakgun** [comment]
I dont have any knowledge on this, feel free to raise a PR if anyone can contribute

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591
