### ISSUE TITLE
Unable to toggle T8410 motion tracker within HA

### ISSUE THREAD

**Issue by phairplay** [fuatakgun/eufy_security#472]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
unable to control the Indoor 2c camera motion detection within Home Assistant

**To Reproduce**
1. Go to 'Eufy Device'
2. Click on 'click on the T8410 device and turn on Motion detection
4. See error: No error provided, yet it toggles off again

**Expected behavior**
able to turn on and off the motion detection

**Screenshots**

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- T8410
- Live Streaming Protocol: RTSP or P2p

**Additional context**
this doesn't seem to be able error captured when hitting the toggle

**Comment by phairplay** [comment]
Hi
Looking at the add on I see this error keep appearing

```
T8410P4122251709 - All address lookup tentatives failed. 
2022-10-03 17:15:57.271  INFO  Timeout connecting to station T8410P4122251709
```

**Comment by Ascathon** [comment]
I get the same timeout when triggering an alarm for alarm_control_panel.camera-name

**Comment by Ascathon** [comment]
Might be relevant I guess.
https://github.com/bropat/eufy-security-ws/issues/135

@fuatakgun If I may be so curious, how does that work. You have their code in your add-on or did I need to install more?
I think so, description page is saying so, just to verify.

**Comment by Rubl80** [comment]
Did you find a solution for this?
I am experiencing same issue but on a T8210 doorbell. It did work fine before.

![image](https://user-images.githubusercontent.com/39396970/201461795-f7362355-d952-41b4-b79a-f98ddc4c8d06.jpeg)

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591
