### ISSUE TITLE
Eufy Security Addon seems to be running but with an error in the logs repeating

### ISSUE THREAD

**Issue by eodabas** [fuatakgun/eufy_security#474]
**Describe the bug**
The addon was running before, suddenly the integration failed to work. I noticed that the addons is full of errors like:

```
  code: 10000,
  msg: 'Failed to request.'
}
```

I tried to install/uninstall/restart/reboot but to no avail. After removing everything and trying to reinstall. Now the addon starts, but the log file says:

```
2022-10-03 13:44:25.269  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-10-03 13:44:25.489  ERROR Response code not ok 
{
  code: 10000,
  msg: 'Failed to request.'
}
```

**To Reproduce**
1. Install the addon using directives on the readme

**Expected behavior**
According to the readme, I should see a message like this when the addon starts:
```
Connected to station XXX on host YYY and port ZZZZ
```

**Hardware Information about Home Assistant**
Home Assistant installed using supervised-installer (https://github.com/home-assistant/supervised-installer) on an RPi4 with SSD installed.

Home Assistant 2022.9.7
Supervisor 2022.09.1
Frontend 20220907.2 - latest

**Hardware Information about Cameras**
- Camera Model: Indoor Cam pan&Tilt T8410 (https://uk.eufy.com/products/t8410)
- Live Streaming Protocol: RTSP

**Comment by eodabas** [comment]
nope. 2fa is disabled and I am using an account specifically created for the addon

**Comment by ejpenney** [comment]
For what it's worth, if I try to use !secret to set my username/password in the Add-On configuration I also get the same error.  It goes away if I hard-code them directly in the configuration.  Not sure if this is related to your issue.

**Comment by eodabas** [comment]
> For what it's worth, if I try to use !secret to set my username/password in the Add-On configuration I also get the same error. It goes away if I hard-code them directly in the configuration. Not sure if this is related to your issue.

that was it 🤯 putting credentials back directly to the addon configuration instead of `secrets.yaml` fixed the issue. not sure entirely, but getting secrets from the yaml file using `!secret secret_name` works for other addons, so I can assume this is related to something in the addon. 

so I'm leaving the issue open and maybe decide @fuatakgun to decide the final resolution?

**Comment by alwyntn** [comment]
> > For what it's worth, if I try to use !secret to set my username/password in the Add-On configuration I also get the same error. It goes away if I hard-code them directly in the configuration. Not sure if this is related to your issue.
> 
> that was it 🤯 putting credentials back directly to the addon configuration instead of `secrets.yaml` fixed the issue. not sure entirely, but getting secrets from the yaml file using `!secret secret_name` works for other addons, so I can assume this is related to something in the addon.
> 
> so I'm leaving the issue open, and maybe leave @fuatakgun to decide the final resolution?

May I ask where is the Add-On configuration? Im getting the same error but I didnt use secrets.yaml ?

**Comment by ejpenney** [comment]
This should be in the Home Assistant Add-On configuration (Settings -> Add-Ons -> Eufy Security Add-On)  There are three tabs here (Info, Configuration, Logs).  Logs is presumably where you're seeing this error.  The "Configuration" tab is what we mean by Add-On Configuration.

![image](https://user-images.githubusercontent.com/21226768/201229997-c6064e3d-c181-4b27-8417-2f12fef00f2c.png)

If aren't using secrets.yaml I'd just make sure that configuration has your credentials and that they're correct.  No weird quotes or anything.  You can click "Edit in YAML" on the right to see your credentials plain-text:
![image](https://user-images.githubusercontent.com/21226768/201230106-bc02c253-9780-4993-bdd9-360df570184f.png)

**Comment by ajdezigns** [comment]
I have the same issue it just started the other day was working fine until then

**Comment by ejpenney** [comment]
That looks a little like this issue (unrelated) https://github.com/bropat/eufy-security-client/issues/242

You may need to set TRUSTED_DEVICE_NAME to any value.

**Comment by ejpenney** [comment]
How's this work? I'm running add-on 1.3.0 and component 2.10.0 and don't
see this status.

**Comment by fuatakgun** [comment]
What do you mean 'dont see this status'.
With 1.3.0 of add-on and trusted device name, is it fixed or not?

**Comment by ejpenney** [comment]
Sorry, looks like you closed two tickets I'm following close together and I replied to the wrong email.  Disregard this.
