### ISSUE TITLE
Binary Sensor in HA with wrong value

### ISSUE THREAD

**Issue by mtosin** [fuatakgun/eufy_security#475]
Hi,
after using this integration I cannot control other devices with HA automation.
Before I was using a different integration based on MQTT and the status for the eufydoorbell was provided with the "Clear" and "Detected" value if there were are presence.( and I was able to activate a lamp when the motion were triggered because are the standard value for motion)

Now the sensor is returning False and True, so i guess is not working with HA automation.
can you please check?

this is the automation
![Screen Shot 2022-10-04 at 17 45 05](https://user-images.githubusercontent.com/23234738/193865114-be28f143-8a2c-4c2a-92fd-9cdb9745e0dc.png)

this is the device
![Screen Shot 2022-10-04 at 17 47 24](https://user-images.githubusercontent.com/23234738/193865614-e4f70d41-a0b5-43bc-9d64-5682e5675daf.png)

thanks

**Comment by fuatakgun** [comment]
Check configuration options, there is a fix for this

**Comment by mtosin** [comment]
Ok, i found it. Will try and hope this will fix the automation

Thanks a lot

Il Mar 4 Ott 2022, 18:02 Fuat Akgün ***@***.***> ha scritto:

**Comment by mtosin** [comment]
Hi
I confirm. The automation is now working.

Thanks a lot

Il Mar 4 Ott 2022, 18:20 Matteo Tosin ***@***.***> ha scritto:

**Comment by KillaDreams** [comment]
@mtosin please mark this issue as resolved so it's closed

**Comment by mtosin** [comment]
Fixex

**Comment by viseshrp** [comment]
@mtosin I have the same problem with automations not triggering. What did you do to fix this?

**Comment by fuatakgun** [comment]
Configure the integration and set the binary sensor fix.

Fix binary sensor states

**Comment by viseshrp** [comment]
> Configure the integration and set the binary sensor fix.
> 
> Fix binary sensor states

Thank you. Any reason why this is optional and not the default? Thanks!

**Comment by fuatakgun** [comment]
1- unnecessary burden on me to be backward compatible
2- laziness
3- will be default in next major release

**Comment by viseshrp** [comment]
> 1- unnecessary burden on me to be backward compatible 2- laziness 3- will be default in next major release

Understandable. Thank you. This fix works for motion sensors but not for the "Ringing Sensor" that gets triggered when I push the video doorbell button.

**Comment by fuatakgun** [comment]
I don't have a doorbell but can you ask help from community in home assistant forums? Before, check if you have enabled push notifications for ring event on eufy mobile app.

**Comment by viseshrp** [comment]
> I don't have a doorbell but can you ask help from community in home assistant forums? Before, check if you have enabled push notifications for ring event on eufy mobile app.

Sure. I'll try that. I do have push notifications enabled for both Motion and Ringing alerts. Thanks for responding quickly.
