### ISSUE TITLE
Integration partially working and not working with Solo Indoorcam P24, and Dashboard not updating

### ISSUE THREAD

**Issue by Kri72** [fuatakgun/eufy_security#480]
**Describe the bug**
Hello, I have an Homebase 2 with 4 Eufycam 2C, and one Solo indoorcam P24.

Integration with Eufybase works partially. When I click on "Arm home" or "Arm away", **the system is well turned on... however, the dashboard doesn't change**, **and the "Disarm" button will not appear**, unless I manually go to the integration and "reload" it
![image](https://user-images.githubusercontent.com/91803162/194771332-69ee3bfe-2039-462e-aa2f-c57f932d0f89.png)

Additionnally, the newly installed Solo indoorcam integration will not work properly.. I well have all entities appearing, but when I click on "Arm home" or "Arm Away", **nothing will happen at all.** Same is I want to disactivate the motion detection, nothing will happen at all.
![image](https://user-images.githubusercontent.com/91803162/194771626-2a7dec1b-01b9-4ed0-9709-83e171e838da.png)

**Hardware Information about Home Assistant
I'm running HAssio on a Raspberry Pi4.

**Hardware Information about Cameras
- Camera Model : Homebase 2, with 4 Eufycam 2C, and one Solo indoorcam P24

Thanks in advance for your support

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591

**Comment by fuatakgun** [comment]
please let me know if you are still having this issues even under Alpha version.

**Comment by Kri72** [comment]
> please let me know if you are still having these issues even under Alpha version.

Hello. Thanks for the great job done and your support..
I still have the and issue with latest available version.. But is there an alpha version to be tested? How do I install it?

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/610

**Comment by Kri72** [comment]
Hello Fuat,
I just tried to update to Alpha version, but got an "Error setting up entry localhost for eufy_security
17:30:42 – (ERROR) Eufy Security (custom integration)". Please find below the log :
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:345
Integration: Eufy Security (documentation, issues)
First occurred: 17:30:42 (1 occurrences)
Last logged: 17:30:42

Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self.api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 63, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 144, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 345, in _send_message_get_response
    return await future
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.4cf7206de68340fea6a8528a56639156', 'errorCode': 'schema_incompatible'}

**Comment by fuatakgun** [comment]
What is add-on version?

**Comment by Kri72** [comment]
Hello Fuat, 
I reinstalled all again (Add on and integration), and now it seems to be working again perfectly, including the Inddor camera.. I just have 2 comments or questions : 
I ad some automation that were working, calling the Arm or Disarm service... It is not working on the "device" anymore...but only on the "entity". it is ok for me, and I updated my automation...
Secondly, I see in my log, all these udpated... when I was not seeing this before, and there is no movement detected... Any clue on what is the reason for this? I'm afraid it could drain the battery of the cams?
![image](https://user-images.githubusercontent.com/91803162/210631443-8137bf5d-10ec-4d4f-99b9-6418d98348be.png)
![image](https://user-images.githubusercontent.com/91803162/210631538-5da3565a-24bb-44b5-9e26-6fb9180ca3bb.png)

**Comment by fuatakgun** [comment]
thanks for sharing updates.
1- device ids are very long and prone to change but entity ids are more friendlier, but it is a personal choice of course.
2- I do not think, either the integration or the add-on would be able to generate this changes, please check if thumbnails are updated on eufy app?

**Comment by Kri72** [comment]
Hello... In face on my Eufy app, i don't have any changes in the thumbnails...
So i don't understand why these entities can change so frequently.. It does it on my 5 cameras (outdoor 2c, and indoor pan & tilt)
Additionally, i don't see the thumbnails in my dashboard.. Any clue on what could be the reason? 
![Screenshot_20230105-001752_Home Assistant.jpg](https://user-images.githubusercontent.com/91803162/210668750-51f05b4a-577b-4b6e-9b46-c6fcfb6272f2.jpg)

**Comment by Kri72** [comment]
Nothing special.. Just the arm and disarm.. 
![Screenshot_20230105-004301_Home Assistant.jpg](https://user-images.githubusercontent.com/91803162/210670854-61051870-a64f-4c3e-a8c1-51b9a5c91dba.jpg)
What is funny is that these url updates are not random.. They have usually a cycle of 10mn.. 
![Screenshot_20230105-004828_Home Assistant.jpg](https://user-images.githubusercontent.com/91803162/210671278-308e7afa-c6f9-4aaf-91a6-e0f243c746a1.jpg)

**Comment by fuatakgun** [comment]
Hmm, check integration options for cloud syncing, they might be coming from cloud. (Cloud scan interval)

Let's extend the duration to 20 minutes and see

**Comment by Kri72** [comment]
Hello Fuat, I moved to version 6.0. I changed too 1200s 
![Screenshot_20230105-085046_Home Assistant.jpg](https://user-images.githubusercontent.com/91803162/210729227-98f70292-f106-4c67-a581-332b72cf1885.jpg)
However, i continue to have these entities changes every 10mn.. 😳
![Screenshot_20230105-085026_Home Assistant.jpg](https://user-images.githubusercontent.com/91803162/210729352-7e467848-a1de-4fbf-86c5-f8029bcf3469.jpg)

**Comment by fuatakgun** [comment]
I dont know than, this is pushed to us from eufy servers because it is changed.

Let's keep on eye on battery

**Comment by Kri72** [comment]
And is all this activity in the add-on normal? 
![Screenshot_20230105-225953_Home Assistant.jpg](https://user-images.githubusercontent.com/91803162/210888547-b51e5ca7-f6dc-4128-93ba-efb231bdaa17.jpg)

**Comment by fuatakgun** [comment]
You need @bropat a support through eufy-security-ws to understand why dicconnections are happening. I don't have knowledge there.
