### ISSUE TITLE
cant add the integration

### ISSUE THREAD

**Issue by eimarfandino** [fuatakgun/eufy_security#482]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
I cant add the integration after following all the steps. I see i am connected on the logs but when i search Eufy integration i get a link to the default eufy integration, not this one.

**To Reproduce**
1. Install addons and configure
1. Go to integrations
2. Search for Eufy

**Expected behavior**
I expect to get the integration added so that i can configure it to use localhost 3000.

**Screenshots**
<img width="535" alt="Screenshot 2022-10-11 at 22 53 58" src="https://user-images.githubusercontent.com/3019114/195197216-509c1c61-cfe6-4938-bc0b-c3b550435623.png">

**Hardware Information about Home Assistant
Home Assistant 2022.10.3

**Comment by cdnninja** [comment]
Have you added the repository?  You have to do that before searching.

**Comment by eimarfandino** [comment]
Thanks for the reply @cdnninja, I added the repo, installed eufy security ws, configured it, I see in the logs that it is connected, after that installed the rtsp add on, configured it.  I got to the step where it is time to add the integration and I got stuck there

**Comment by eimarfandino** [comment]
ok got it, sorry i am new to this, I had to install HACS and now i got it. I'll close the ticket
