### ISSUE TITLE
Cards not displaying after doorbell lost network

### ISSUE THREAD

**Issue by chicknlil** [fuatakgun/eufy_security#487]
@fuatakgun 

Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Checked.**

**Describe the bug**

**After getting disconnected from my wireless network, my video doorbell (T8200) no longer provides a feed to the cards on my UI.**  

**To Reproduce**

**Go to overview.  Expect to see card with doorbell idle image (which when clicked provides a live image).  Click on 3 dots (edit dashboard menu).  Idle image shows below "Ben's Plug" but the camera provides an error: can't get URL for camera.doorbell.  Leaving this "edit mode" makes that card disappear from view.**

**Expected behavior**
**The card to display and function as expected.**

**Screenshots**

![Overview-–-Home-Assistant (3)](https://user-images.githubusercontent.com/100124187/195954905-094879fd-8a25-403e-87b0-e96b6296e952.png)
![Overview-–-Home-Assistant (2)](https://user-images.githubusercontent.com/100124187/195954907-16a5cb00-b6ca-4f8b-b86c-96f3340569c7.png)

**Hardware Information about Home Assistant
**Home Assistant Blue / Hardkernal Odroid-N2**

**Hardware Information about Cameras
- Camera Model **T8200**
- Live Streaming Protocol: RTSP or **P2p** 

**Additional context**

The IP address definitely changed during this downtime/disconnect, from  .33 to .14. I tried uninstalling just the integration, restarting/clearing cache, and then reinstalling and that seemed to briefly work - but as soon as I tried to duplicate the card and add it to another view, it stopped working.   Have added screenshots of what seems like it should be all relative information.

![Home-Assistant (3)](https://user-images.githubusercontent.com/100124187/195955939-c469a9ca-e0b3-4bc1-95c8-d4727e16a037.png)
![Home-Assistant (2)](https://user-images.githubusercontent.com/100124187/195955942-ca8640a2-71b2-4cc0-b363-6a1bb4000111.png)
![Home-Assistant (1)](https://user-images.githubusercontent.com/100124187/195955944-a7833705-8be6-47ca-ae7a-b75ffc8f3326.png)
![Home-Assistant](https://user-images.githubusercontent.com/100124187/195955945-0b98f0c6-a5d6-46c0-8104-65e0c514dcf0.png)
![Settings-–-Home-Assistant (1)](https://user-images.githubusercontent.com/100124187/195955946-40f79f79-f361-435b-a06f-6e356fe8e4f3.png)

**Comment by chicknlil** [comment]
Since this original post, I've installed HA fresh and installed all the addons/integrations I run one at a time.  Despite that, this error persists. I've now also got a Flood Light Camera from Eufy, and it too isn't usable with this addon.

**Comment by blablazzz** [comment]
same doorbell, same problem for me also.

**Comment by chicknlil** [comment]
@fuatakgun

**Comment by fuatakgun** [comment]
is this still happening after TRUSTED DEVICE fix and 1.3.0 version of add-on?

**Comment by chicknlil** [comment]
> is this still happening after TRUSTED DEVICE fix and 1.3.0 version of add-on?

Oh yes. It's been happening since I first posted about it...3 months ago?

I've long since pretty much given up on the camera aspect of this integration/addon.  At least my keyless entry is usable.

**Comment by chicknlil** [comment]
Just so you're aware, your latest integration update didn't fix this issue.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/592
