### ISSUE TITLE
Eufy Garage Control Cam not supported

### ISSUE THREAD

**Issue by squirtkenyon** [fuatakgun/eufy_security#488]
Hi all, firstly thanks for this awesome intergration.

Have installed the new Eufy Garage control camera, the moment I do the intergration stops working. Have tested without it and sure enough its the installation of this camera https://support.eufylife.com/s/article/Introducing-the-eufy-Garage-Control-Cam

https://support.eufylife.com/s/article/Introducing-the-eufy-Garage-Control-Cam

![image](https://user-images.githubusercontent.com/112627349/196023021-8d1111ec-4819-428d-835a-39a8a102978a.png)

![image](https://user-images.githubusercontent.com/112627349/196023031-aca146f9-0e4a-4316-853e-783d2492c9cb.png)

**Comment by kfelicitn** [comment]
I am also experiencing the same issue, if support could be added for the garage control cam it would be greatly appreciated.

**Comment by cdnninja** [comment]
This will need support in the core library: https://github.com/bropat/eufy-security-client/issues/219

**Comment by fuatakgun** [comment]
Please re-open this, after working with @bropat and this device is added here: https://bropat.github.io/eufy-security-client/#/supported_devices

**Comment by kfelicitn** [comment]
Not sure if this change has been published, but I am still experiencing this issue of the device not being supported. Thanks
