### ISSUE TITLE
Updating entities

### ISSUE THREAD

**Issue by yorickri** [fuatakgun/eufy_security#49]
I am using the wireless doorbell 2K (T8210 - Hardware Version T8210B) and the initial integration appears to be working OK.
However, updating the entities does not seem to work (for me :)) as expected.

I'm experiencing 2 overall 'issues'

1. Even though motion is detected (as I am seeing videos being recorded in the Eufy app), the entities in Home Asssistant don't indicate any motion being detected. 

As a test I have created additional sensors which are showing the specific attrbutes of the entity.

By using the additional sensors I'm able to identify that at least something is working, as the values of the total/recorded/false events does increase, whereas the rest remains on their initial value. Having said that, the battery percentage as well as the doorbell ringing entity do seems to be updating.

I have enabled debug logging and when looking up _motionDetected_ in the log, it is shown as _false_ in every single entry.

To explain what is shown on the screenshot below;
- The entities with their initial value (after setting up the integration again) - the ones showing "40 minuten geleden"
- The additional sensors showing a specific attribute (the ones in the red box). **Note:** The "7 minuten geleden" is from reloading the template entities
- The secondary info contains "last modified"

![image](https://user-images.githubusercontent.com/46721479/131327897-1cddcfdb-3809-461c-b0d2-2320aace507d.png)

2. I seem to have a delay on updating the entities. In the example above, the deurbel_*_events entities are only updated every x minutes, as can be seen on the screenshot below. Maybe this is intentional, but this would possibily clarify on why other entities are not being updated either as they might be in the exact same state on every update and might only show as 'true' in very specific cases where the update takes place in the same matter of seconds as in which the motion is detected.

![image](https://user-images.githubusercontent.com/46721479/131328707-5787c80a-32d0-478a-9fd4-51e468586e46.png)

**Comment by fuatakgun** [comment]
following readme file, please share your cameras with me, I am happy to debug this

**Comment by yorickri** [comment]
Thanks fuatakgun, hope you enjoyed your holiday! I've sent you the request.

**Comment by fuatakgun** [comment]
Thanks for your wishes, i had received the invitation and accepted it. I will investigate issue tonight (based on EU timezone)

**Comment by fuatakgun** [comment]
please send me an email so we can test the events, I am not good at creating motion/person/ring events from remote :)

**Comment by fuatakgun** [comment]
Had a debug session, my findings;
- ringing events are coming
- picture is updated based on event
- motion event did not arrive as push notification.

Next action;
- if you login with your HA account on your mobile phone, are you receiving these push notifications?

Possible paths forward;
- creating a new account and sharing the cameras
- removing all cameras and adding them back to EUFY (yes painful)

**Comment by fuatakgun** [comment]
Please check this: https://github.com/fuatakgun/eufy_security/issues/22#issuecomment-908157691

**Comment by yorickri** [comment]
Removing the devices completely and re-adding the homebase + doorbell seems to have done the trick. I can now see the notifications in Home Assistant!

Only downside is that it won't give any motion notification while the notification on your mobile phone is disabled. It seems that it's not possible to enable the mobile notifications for one account and disable it for the other (or i'm missing something).

**Comment by fuatakgun** [comment]
Yes,  notifications are device based, not account.

**Comment by fuatakgun** [comment]
Please resolve the issue, if nothing left
