### ISSUE TITLE
Solocam S40 Charging Status shown as configuration, not sensor

### ISSUE THREAD

**Issue by Morphy99** [fuatakgun/eufy_security#493]
**Describe the bug**
The charging status is shown as a select in Home Assistant. 

**To Reproduce**

Go to integrations, Eufy Security then the select the camera device to see associated entities

**Expected behavior**
This should be a sensor?

**Screenshots**

![image](https://user-images.githubusercontent.com/5853979/197728985-6cdc3a85-a305-4646-a52d-103422368178.png)

**Hardware Information about Home Assistant**

2022.10 NUC

**Hardware Information about Cameras**
- Camera Model: Solocam S40
- Live Streaming Protocol: P2P

**Additional context**
I have a few issues with this camera so I will post them separately as I do more testing.

**Comment by fuatakgun** [comment]
will be fixed in new version
