### ISSUE TITLE
Cant configure RTSP Add On Port in use

### ISSUE THREAD

**Issue by Menz01** [fuatakgun/eufy_security#494]
Hello,
    I already have the Docker Wyze Bridge installed and it is using port 8554 for RTSP. I added your Eufy Security and while following the install instructions it mentions installing the RTSP Add on. i did that but i cannot start as the port is already in use with the Wyze bridge. is there any options, can i use a different port?

**Comment by fuatakgun** [comment]
you should be able to change the ports of any add-on using configuration panel of home assistant.

![image](https://user-images.githubusercontent.com/11085566/200131855-b66b1fea-3fb4-4e08-ac50-16f01789b467.png)

**Comment by fuatakgun** [comment]
Example changes can be found below, do not forget to re-configure the integration respectively.

![image](https://user-images.githubusercontent.com/11085566/200131890-bab7459d-2bb4-4c4f-b670-6484c99494ac.png)
