### ISSUE TITLE
HomeBase3 Not Arming/Disarming

### ISSUE THREAD

**Issue by Ringo982** [fuatakgun/eufy_security#495]
Hello, I have one HomeBase2 and one HomeBase3, and a lot of automations that are arming_home/ arming_away when I reach/leave home.
The problem is that the automations are working pretty well with HomeBase2 but with HomeBase3 they are not arming home/away. The HomeBase3 is added to the automation at the same way as the HomeBase2. When the automation run nothing happen on HomeBase3. Why it is happening? Is the HomeBase3 still not compatible? 
thanks a lot

**Comment by SmartKoh202x** [comment]
Having the same problem, in autoamtions, und, when you try to arm it over a manually over HA:

![image](https://user-images.githubusercontent.com/79155054/198851585-b8a7c883-ff6b-415e-b5be-04bf9b963fdf.png)

**Comment by SmartKoh202x** [comment]
Looks like Bropat updated the driver / lib to 2.2.0 (2022-11-01). Are his Lib's in this package? If so, could you update them? Kindly :)

**Comment by fuatakgun** [comment]
I am on bumping the version of integration, please wait for it.

**Comment by KyleDoherty1** [comment]
@fuatakgun are you adding support for the homebase 3 and eufycam 3?

**Comment by fuatakgun** [comment]
Yes would do

**Comment by KyleDoherty1** [comment]
Nice! Any time estimate on when? :)

**Comment by fuatakgun** [comment]
Probably latest this weekend. It is taking time because there are some fundamental changes i need to introduce to go with latest schema version

**Comment by KyleDoherty1** [comment]
Hye @fuatakgun, how are you getting on with the above? Let me know if you need a Homebase 3 or Eufycam3 shared to test with.

**Comment by fuatakgun** [comment]
please test with alpha release v5.x.x
