### ISSUE TITLE
Eufy Security Integration and Live stream

### ISSUE THREAD

**Issue by NunoMCMoreira** [fuatakgun/eufy_security#496]
Good Morning,

I took some time to get the cameras integrated, but after I integrated them and after 1 week, they still don't update often. I need to reload the integration myself. when I do it, it updates for the last event, but I can never open the camera to see it live.

Upon integration I realized that I would have to set the cameras as US, as I was not able to use UK, which is where I live.

Can anyone help me with what I should do to have live stream when I open the card, and also for the integration to update more frequently?

thanks

**Comment by SuperLink5g** [comment]
Also interested as I cannot get live stream to work.

**Comment by SuperLink5g** [comment]
> 

I used GB instead of UK and it accepted it.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/592
