### ISSUE TITLE
Docker container for steps 1-8

### ISSUE THREAD

**Issue by jbrukardt** [fuatakgun/eufy_security#5]
Hey, just as a headsup if you didnt want to run a standalone node.js  Bropat's repository automatically generates a docker container

Variables are below to config it right.

docker run -it
-e USERNAME=user
-e PASSWORD=pw
-v "$(PWD)"/data:/data
-p 3000:3000
bropat/eufy-security-ws:latest

**Comment by fuatakgun** [comment]
Thanks for the heads up, i am running everything in an old android phone, docker is not supported here :-) but this is a valid point for majority, will update accordingly

**Comment by fuatakgun** [comment]
updated steps accordingly
