### ISSUE TITLE
pictureUrl Missing for Doorbell Camera

### ISSUE THREAD

**Issue by akeslo** [fuatakgun/eufy_security#50]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md - 

**Describe the bug**
Picture is not displaying for the Wireless Doorbell Cam, Model T8210:

_'name': 'Doorbell',
'model': 'T8210',
'hardwareVersion': 'T8210',
'softwareVersion': '2.2.3.3',_

All other cameras are displaying without an issue.  I am seeing no pictureURL attribute on this camera from within the logs.  I have enabled image notifications within the configuration on the eufy ios app. 

         'name': 'Doorbell',
          'model': 'T8210',
          'serialNumber': 'XXXX',
          'hardwareVersion': 'T8210',
          'softwareVersion': '2.2.3.3',
          'stationSerialNumber': 'XXXX',
          'enabled': True,
          'state': 1,
          'battery': 52,
          'batteryTemperature': 0,
          'lastChargingDays': -1,
          'lastChargingTotalEvents': 3,
          'lastChargingRecordedEvents': 0,
          'lastChargingFalseEvents': 3,
          'batteryUsageLastWeek': 0,
          'motionDetected': False,
          'personDetected': False,
          'personName': '',
          'ringing': False,
          'autoNightvision': True,
          'ledStatus': True,
          'motionDetection': True,
          'watermark': 2,
          'wifiRSSI': -40,
          'motionDetectionType': 0,
          'microphone': True,
          'speakerVolume': 100,
          'ringtoneVolume': 80,
          'audioRecording': True,
          'powerWorkingMode': 1,
          'videoWDR': True,
          'chimeIndoor': False,
          'chimeHomebase': True,
          'chimeHomebaseRingtoneVolume': 26,
          'chimeHomebaseRingtoneType': 0,
          'notificationType': 2,
          'notificationRing': 1,
          'notificationMotion': 1
        },

No " camera_image" is displayed in the logs for this entity either. 

**Expected behavior**
Display image

**Screenshots**

![image](https://user-images.githubusercontent.com/3003773/131765601-832b04ce-bbe7-40d4-998a-f60e38e8a6ba.png)

![image](https://user-images.githubusercontent.com/3003773/131766713-ba58dd4f-b904-4c62-87c2-e2c0a235ff5a.png)

**Comment by fuatakgun** [comment]
I remember one case that, if doorbell doesn't have sd card or local storage to store it, it doesn't generate it.

**Comment by akeslo** [comment]
@fuatakgun it started showing up this morning, makes no sense. I think it was something on the Eufy side, Eufy not sending the picture information.

**Comment by fuatakgun** [comment]
It happens to me rarely and needs another event to be triggered so url is sent. I will keep this in mind.
