### ISSUE TITLE
Error during decryption (probably incorrect key) error crashing integration

### ISSUE THREAD

**Issue by EzzatQ** [fuatakgun/eufy_security#502]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
I have a homebase and a doorbell camera 2k. I'm integrating them in home assistant via this integration.
I've connected the doorbell camera to live power so I don't need to charge it every 6 months and I can have the stream open 24/7. 
Every time I start the add-on and reload the integration, I immediately get a stream and everything works great. However, after I couple hours, the camera becomes unavailable and this is what I see in the logs:
'''

2022-11-03 21:41:11.725  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-11-03 21:41:22.104  INFO  Connected to station T8010P23211415E4 on host 10.0.1.142 and port 27214 
2022-11-03 21:41:22.334  INFO  Push notification connection successfully established 
2022-11-03 23:19:25.441  INFO  Stopping the station stream for the device T8210P3321180114, because we haven't received any data for 5000 seconds 
2022-11-04 00:20:40.403  INFO  Stopping the station stream for the device T8210P3321180114, because we haven't received any data for 5000 seconds 
2022-11-04 01:27:02.102  INFO  Stopping the station stream for the device T8210P3321180114, because we haven't received any data for 5000 seconds 
2022-11-04 02:40:40.915  INFO  Stopping the station stream for the device T8210P3321180114, because we haven't received any data for 5000 seconds 
2022-11-04 03:26:21.907  WARN Station T8010P23211415E4 - AES key could not be decrypted! The entire stream is discarded. - Error: 
 Error  Error during decryption (probably incorrect key). Original error: Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error
error stack:
• NodeRSA.js:301 module.exports.NodeRSA.$$decryptKey
    node_modules/node-rsa/src/NodeRSA.js:301:19
• NodeRSA.js:249 module.exports.NodeRSA.decrypt
    node_modules/node-rsa/src/NodeRSA.js:249:21
• session.ts:1130 handleDataBinaryAndVideo
    node_modules/eufy-security-client/src/p2p/session.ts:1130:63
• session.ts:1065 handleData
    node_modules/eufy-security-client/src/p2p/session.ts:1065:18
• session.ts:979 parseDataMessage
    node_modules/eufy-security-client/src/p2p/session.ts:979:26
• session.ts:801 handleMsg
    node_modules/eufy-security-client/src/p2p/session.ts:801:26
• session.ts:113 <anonymous>
    node_modules/eufy-security-client/src/p2p/session.ts:113:56
• node:events:527 emit
    node:events:527:28
• node:dgram:922 onMessage
    node:dgram:922:8
2022-11-04 06:00:43.478  ERROR Message error 
 LivestreamNotRunningError  Livestream for device T8210P3321180114 could not be stopped, because it is not running
error stack:
• message_handler.ts:146 handle
    src/lib/device/message_handler.ts:146:31
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• server.ts:103 receiveMessage
    src/lib/server.ts:103:21
'''
The decryption error makes the camera unavailable and it will not work until I restart the add-on and reload the integration.
This is very annoying since every time I want to see the camera, it turns out to be unavailable.

**To Reproduce**
1. Use the integration with doorbell camera 2k (battery powered version, connected to 12v), start the stream and wait 

**Expected behavior**
Ability to stream 24/7 with no error. Or if error occured, restart the add-on and reload the integration automatically

**Hardware Information about Home Assistant
Home assistant 2022.10.4
Supervisor 2022.10.2
Operating system 9.3

**Hardware Information about Cameras
- Doorbell Camera 2k(battery powered version). Model: T8210
- Live Streaming Protocol: P2P

**Additional context**
What I now do is automatically start the stream when home assistant comes up and never stop the stream.
Is this the correct way to get a 24/7 stream or is there a better way?

**Comment by fuatakgun** [comment]
I am not sure if this a great way of repurposing the p2p stream functionality. I see that the stream is closed by add-on every couple of hours (23:19 to 00:20 and 01:27 to 02:40)

I do not personally own a device which supports only P2P but can you stop and start the stream every 30 minutes?

**Comment by EzzatQ** [comment]
How do I know if my device support's RTSP? I trying calling the start RTSP service but nothing happned.

**Comment by fuatakgun** [comment]
check eufy app and user manual please.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/597
