### ISSUE TITLE
Username setting hidden, password in plaintext

### ISSUE THREAD

**Issue by EDelsman** [fuatakgun/eufy_security#503]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
In config settings the username is a passwordfield, the password is a plaintext field. Should be the other way around :-)

**To Reproduce**
Open the Home Assistant addon configuration page

**Expected behavior**
Password not readable in UI

**Screenshots**
Rather not show my password here

**Hardware Information about Home Assistant
addon version 0.9.4

**Hardware Information about Cameras
- Camera Model
- Live Streaming Protocol: RTSP or P2p

**Additional context**

**Comment by fuatakgun** [comment]
this has been resolved earlier but I need to release a new revision so you can get update your local one. Resolving it now, expect a new version of add-on in couple of days. Please reopen if it is not resolved (working for me locally)
