### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by alwyntn** [fuatakgun/eufy_security#507]
Anyone having this issue when trying to add integration ?

`Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

**Comment by alwyntn** [comment]
delete both EUFY security and reinstall them resolved issue.

**Comment by 51av0sh** [comment]
I have this same issue. Tried the above and no luck. Any other suggestions?
