### ISSUE TITLE
Cannot trigger alarm on HomeBase 3

### ISSUE THREAD

**Issue by spiralfive** [fuatakgun/eufy_security#508]
I am trying to trigger the alarm event from Home Assistant on my new HomeBase 3. I did with with my HomeBase 2 without issues, I use the alarm event to make all my cameras record for 30 seconds. On the 3, nothing seems to happen except I get this error in the logs:

`eufy_security - Exception - process_messages: 'result' - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 297, in on_message message_result = payload[message_type] KeyError: 'result' - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":false,"messageId":"trigger_alarm","errorCode":"device_not_supported"}', extra='')`

This is what the automation looks like:
![image](https://user-images.githubusercontent.com/26095643/200903511-28517f10-4a87-4bde-a160-7bff98ba7ab2.png)
```
service: eufy_security.alarm_trigger_with_duration
data:
  duration: 30
target:
  entity_id: alarm_control_panel.homebase_3
```

I also tried doing this via the alarm panel service as below, but the same error happens.
```
service: alarm_control_panel.alarm_trigger
data: {}
target:
  entity_id: alarm_control_panel.homebase_3
```

**Comment by fuatakgun** [comment]
please be sure that you are in latest version of add-on.
I believe, this should have been solved in latest version.
