### ISSUE TITLE
Add on failing on startup

### ISSUE THREAD

**Issue by jouster1974** [fuatakgun/eufy_security#509]
Seeing this error on 0.9.4

App access is fine2022-11-09 17:53:01.312  ERROR Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:288 login
    node_modules/eufy-security-client/src/http/api.ts:288:66
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• eufysecurity.ts:600 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:600:9
• server.ts:383 start
    src/lib/server.ts:383:9
• server.ts:66 <anonymous>
    src/bin/server.ts:66:9

For clarity, this was the case before updating to Core 2022.11.2....but have updated since and still getting the same issue, plus also reverted to an earlier backup just in case

**Comment by lolouk44** [comment]
I have the same issue since today. eufy installed via HACS and docker been working flawlessly for several months now.
```
2022-11-09 18:36:15.273  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-11-09 18:36:15.460  ERROR Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:289 login
    node_modules/eufy-security-client/src/http/api.ts:289:66
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• eufysecurity.ts:662 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:662:9
• server.ts:496 start
    src/lib/server.ts:496:9
• server.ts:66 <anonymous>
    src/bin/server.ts:66:9
2022-11-09 18:36:53.329  ERROR Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:289 login
    node_modules/eufy-security-client/src/http/api.ts:289:66
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• eufysecurity.ts:662 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:662:9
• message_handler.ts:80 handle
    src/lib/driver/message_handler.ts:80:21
• server.ts:126 receiveMessage
    src/lib/server.ts:126:21
2022-11-09 18:37:05.970  INFO  Client disconnected with ip: 192.168.9.23 port: 40300 code: 1000 reason: Normal Closure 
```
Tried several versions of bropat's container (0.9.4, 1.0.0, 1.0.1, 1.0.2), same error in the container.
Tried rebooting the doorbell (), same error
Tried to set up on spare instance of HA, fails on both 2022.10 na d 2022.11

Also raised here: https://github.com/bropat/eufy-security-ws/issues/146 as the issue is within the container

**Comment by lolouk44** [comment]
Actually looks related to this: https://github.com/bropat/eufy-security-client/issues/242

**Comment by fuatakgun** [comment]
Yes, thanks @lolouk44 , let's track it over there

**Comment by lolouk44** [comment]
this fixed it for me:
https://github.com/bropat/eufy-security-client/issues/242#issuecomment-1309377631

**Comment by rjing001** [comment]
> this fixed it for me: [bropat/eufy-security-client#242 (comment)](https://github.com/bropat/eufy-security-client/issues/242#issuecomment-1309377631)

But this won't work for HASS Addon will it?

**Comment by lolouk44** [comment]
No not unless @fuatakgun creates a new version

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/511#issuecomment-1310773519

**Comment by jouster1974** [comment]
all working after fix from other logged issue, but to save an extra click

go into the Eufy Security Add-on
Go to configuration
Edit it in YAML
Add the following line

TRUSTED_DEVICE_NAME: DEVICENAME

save and restart add on and you should be up and running
