### ISSUE TITLE
Change temp file location for video files

### ISSUE THREAD

**Issue by raghavrithvik** [fuatakgun/eufy_security#51]
**Is your feature request related to a problem? Please describe.**
The temp video files seem to be filling up the config folder of HA.
**Describe the solution you'd like**
A sub folder to hold all these files would really clean up the config folder
**Describe alternatives you've considered**

**Additional context**

**Comment by fuatakgun** [comment]
I prefer to deprecate file based p2p streaming option and migrate to rtsp add on solution. Do you have any specific reason to stick with file based streaming?

**Comment by raghavrithvik** [comment]
Apologies. I've just started using this 2 days ago and am still catching up on how this works. I use it with the battery doorbell and understand that theres no RTSP option on that yet. 
Will this RTSP addon still work with the P2P stream from the doorbell?

**Comment by fuatakgun** [comment]
If you go through readme file, you can see that there is a rtsp add on which removes file generation process. P2P video data will be converted into rtsp stream via that add on.

**Comment by raghavrithvik** [comment]
Found it. Works. Thanks
