### ISSUE TITLE
Cannot read properties of undefined reading user_id

### ISSUE THREAD

**Issue by cybertai** [fuatakgun/eufy_security#511]
2022-11-10 17:07:21.066  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-11-10 17:07:22.196  ERROR Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:288 login
    node_modules/eufy-security-client/src/http/api.ts:288:66
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• eufysecurity.ts:600 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:600:9
• server.ts:383 start
    src/lib/server.ts:383:9
• server.ts:66 <anonymous>
    src/bin/server.ts:66:9

**Comment by naikn05** [comment]
I have this same issue!

**Comment by Seji64** [comment]
Same here...

```

2022-11-10 18:26:53.483  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-11-10 18:26:53.825  ERROR Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:288 login
    node_modules/eufy-security-client/src/http/api.ts:288:66
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• eufysecurity.ts:600 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:600:9
• server.ts:383 start
    src/lib/server.ts:383:9
• server.ts:66 <anonymous>
    src/bin/server.ts:66:9
2022-11-10 18:27:29.382  ERROR Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:288 login
    node_modules/eufy-security-client/src/http/api.ts:288:66
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• eufysecurity.ts:600 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:600:9
• message_handler.ts:76 handle
    src/lib/driver/message_handler.ts:76:21
• server.ts:103 receiveMessage
    src/lib/server.ts:103:21
2022-11-10 18:27:41.971  INFO  Client disconnected with ip: 172.30.32.1 port: 50860 code: 1000 reason:
```

**Comment by marcbroe** [comment]
Same here....

2022-11-10 18:45:05.007  INFO  Client disconnected with ip: 172.30.32.1 port: 41038 code: 1000 reason:  
2022-11-10 18:45:15.045  ERROR Generic Error: 
 **TypeError  Cannot read properties of undefined (reading 'user_id')**
error stack:
• api.ts:288 login
    node_modules/eufy-security-client/src/http/api.ts:288:66
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• eufysecurity.ts:600 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:600:9
• message_handler.ts:76 handle
    src/lib/driver/message_handler.ts:76:21
• server.ts:103 receiveMessage
    src/lib/server.ts:103:21
2022-11-10 18:45:27.795  INFO  Client disconnected with ip: 172.30.32.1 port: 37320 code: 1000 reason:  
2022-11-10 18:45:47.837  ERROR Generic Error:

**Comment by ibmaster** [comment]
Sounds like Eufy made a server side change that broke everyone. Charming.Ben.Sent from my iPhoneOn Nov 10, 2022, at 10:52 AM, marcbroe ***@***.***> wrote:﻿
Same here....
2022-11-10 18:45:05.007  INFO  Client disconnected with ip: 172.30.32.1 port: 41038 code: 1000 reason:
2022-11-10 18:45:15.045  ERROR Generic Error:
TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:288 login
node_modules/eufy-security-client/src/http/api.ts:288:66
• task_queues:96 processTicksAndRejections
node:internal/process/task_queues:96:5
• eufysecurity.ts:600 connect
node_modules/eufy-security-client/src/eufysecurity.ts:600:9
• message_handler.ts:76 handle
src/lib/driver/message_handler.ts:76:21
• server.ts:103 receiveMessage
src/lib/server.ts:103:21
2022-11-10 18:45:27.795  INFO  Client disconnected with ip: 172.30.32.1 port: 37320 code: 1000 reason:
2022-11-10 18:45:47.837  ERROR Generic Error:

**Comment by naikn05** [comment]
I got it working

To into the Eufy Security Add-ons
Go to configuration
Edit it YAML
Add the following line
TRUSTED_DEVICE_NAME: DEVICENAME

Save it and restart. Please let me know if it works!

**Comment by Seji64** [comment]
> I got it working
> 
> 
> 
> To into the Eufy Security Add-ons
> 
> Go to configuration
> 
> Edit it in YAML
> 
> Add the following line
> 
> TRUSTED_DEVICE_NAME: DEVICENAME
> 
> 
> 
> Save it and restart. Please let me know if it works!

Works! thanks!

**Comment by ibmaster** [comment]
So the Eufy Security Add On default YAML file should uprev to include this additional line, correct?
Anyone check if new server side auth requirement accepts any trusted device name?

**Comment by LastAmerican** [comment]
> I got it working
> 
> To into the Eufy Security Add-ons Go to configuration Edit it in YAML Add the following line TRUSTED_DEVICE_NAME: DEVICENAME
> 
> Save it and restart. Please let me know if it works!

This worked for me as well. Thank you!

**Comment by fuatakgun** [comment]
Great idea, thanks for sharing it :clap:

**Comment by marcbroe** [comment]
TRUSTED_DEVICE_NAME: DEVICENAME
Sorry, I'm not very familiar with Home Assistant, where exactly do I have to enter this? In the configuration.yaml or where exactly? Thanks in advance

**Comment by marcbroe** [comment]
ok, found it and works.TOP Thanks everyone :-)

**Comment by JMP25** [comment]
> I got it working
> 
> To into the Eufy Security Add-ons Go to configuration Edit it in YAML Add the following line TRUSTED_DEVICE_NAME: DEVICENAME
> 
> Save it and restart. Please let me know if it works!

It works, thank you very much!

**Comment by JMP25** [comment]
> TRUSTED_DEVICE_NAME: DEVICENAME Sorry, I'm not very familiar with Home Assistant, where exactly do I have to enter this? In the configuration.yaml or where exactly? Thanks in advance

- Click Settings - 
- Click Addons
-  Click Eufy Security Add- on
- Click Configuration
- Click on the three dots right corner
- Edit in YAML
- Paste Copy this below : TRUSTED_DEVICE_NAME: DEVICENAME

My code:
USERNAME: you-email-address@example.com
PASSWORD: "You Password"
COUNTRY: LU
EVENT_DURATION_SECONDS: 10
TRUSTED_DEVICE_NAME: DEVICENAME

**Comment by protooler** [comment]
> I got it working
> 
> To into the Eufy Security Add-ons Go to configuration Edit it in YAML Add the following line TRUSTED_DEVICE_NAME: DEVICENAME
> 
> Save it and restart. Please let me know if it works!

WORKS! Thanks!

**Comment by cybertai** [comment]
Works for me too !

**Comment by cybertai** [comment]
Thanks naikn05

To into the Eufy Security Add-ons
Go to configuration
Edit it in YAML
Add the following line
TRUSTED_DEVICE_NAME: DEVICENAME

Save it and restart.

**Comment by akuehner** [comment]
I was having the same issue. Adding "DEVICENAME" to TRUSTED_DEVICE_NAME didn't seem to fix the issue. The service temporarily appeared to be working, but my Eufy Security system was still in an error state if I tried to view/change anything. 
Now the service is back to "Retrying setup: Start Listening was not completed in timely manner"
