### ISSUE TITLE
Start Listening was not completed in timely manner

### ISSUE THREAD

**Issue by KennethSmit** [fuatakgun/eufy_security#517]
since this morning eufy can't get started properly in my HA. I'm running on a Raspberry Pi. The message I get is: Start Listening was not completed in timely manner

**Comment by AaronFryer** [comment]
I've been getting the same issue for the past 24 hours, I haven't found any clues yet.

If there's any logs or info I can provide for this issue, please let me know.
My device is a T8520N smart lock

**Comment by jimmyfortinx** [comment]
I was facing the same issue and I followed what is explained here and it worked perfectly fine!

https://github.com/fuatakgun/eufy_security/issues/511#issuecomment-1310773519

**Comment by KennethSmit** [comment]
Thanx!
This works great.
