### ISSUE TITLE
Openhab possible?

### ISSUE THREAD

**Issue by devtos** [fuatakgun/eufy_security#518]
Hello, i would like to use this with Openhab or my NAS. Is it possible to support Openhab or set up some generic service to use with most home auto. systems or NAS systems?

**Comment by fuatakgun** [comment]
Hey, i don't know many things about openhab, but under the hood, this integration is acting as a bridge between eufy-security-ws docker image which acts as android app and home assistant.

This repository fetches all the information from eufy-security-ws, creates devices, entities and services under home assistant.

I am trying to extract the logic into separate library independent of home assistant, which can help other users to consume it.

As far as i can see, openhab is using java as language, so you might need to write a binding for it and bridge the openhab to eufy-security-ws container
