### ISSUE TITLE
Not all cameras are recognized by the HA integration - but they are available in the eufy security app.

### ISSUE THREAD

**Issue by goldnase** [fuatakgun/eufy_security#52]
Hi,

sorry I dont know if its a bug or not.

I am slowly going crazy with the camera integrations of an eufy cam 2 pro in home assistant. In total I have 3 pieces. I have integrated the eufy security home base according to the instructions and the apps from GitHub - fuatakgun/eufy_security . Everything is working fine so far. Thanks for that! 2 cameras are integrated with functioning rtps streams in lovelace. just not the third one. The integration simply does not want to recognize this (the other 2 were automatically detected). However, all 3 are displayed in the eufy phone app in the admin access as well as in the guest access and it works; just not in home assistant. I have already made a backup restore and set up everything again, reinstalled the eufy home base, the apps and accesses, the connections of the cameras. nothing has worked. Does anyone know how I can still integrate the one missing camera in ha? or that this is automatically recognized by the ha integration? Does anyone know the problem?

Sorry for my frustrating writing :)

best greetings from germany, goldnase

**Comment by fuatakgun** [comment]
Hey, i will br back from vacation next week, happy to debug this issue later on, hang on there

**Comment by goldnase** [comment]
Problem solved. It was apparently due to the camera itself. I ordered a new one as a test. This was recognized in HA. I have no idea what the real mistake is.
