### ISSUE TITLE
Invalid Property wifiSignalLevel

### ISSUE THREAD

**Issue by ryangottlieb** [fuatakgun/eufy_security#520]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

After the update of the Eufy Security Addon,  my lock was no longer functional,  I went into the addon, and put a name in the new field,  but I still get an error saying
"ERROR Invalid Property wifiSignalLevel error 
 InvalidPropertyError  Property wifiSignalLevel invalid" 

It does say its connected further down

![image](https://user-images.githubusercontent.com/64741027/201544728-5e7e5905-2a0d-4f9e-8b07-9de71c841955.png)

However the Eufy lock shows as un-available in home assistant, and I am unable to trigger / read any status. 

![image](https://user-images.githubusercontent.com/64741027/201544621-f69e4e8b-5eee-4c35-9e47-eb6131eef5f4.png)

Raspberry Pi 4

**Comment by ryangottlieb** [comment]
Update:  Was able to get the lock to respond after 2-3 reboots of HA;  However that error is still showing up in the log.

**Comment by fliespl** [comment]
@fuatakgun It seems that homebase update to 3.2.3.2 might be responsible and broke this integration.

Having same wifi signal errors since that time and it  causes HA states not to udpate.

**Comment by sidd905** [comment]
I have the same issue.

**Comment by magicvash** [comment]
Got the same error: 

2022-11-24 17:42:59.403  ERROR Invalid Property wifiSignalLevel error 
 InvalidPropertyError  Property wifiSignalLevel invalid
error stack:
• device.ts:507 getPropertyMetadata
    node_modules/eufy-security-client/src/http/device.ts:507:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:48
• device.ts:120 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:120:18
• device.ts:2106 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:2106:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:22
• device.ts:138 updateRawProperty
    node_modules/eufy-security-client/src/http/device.ts:138:30
• device.ts:60 <anonymous>
    node_modules/eufy-security-client/src/http/device.ts:60:22
• device.ts:59 update
    node_modules/eufy-security-client/src/http/device.ts:59:35
• device.ts:37 initializeState
    node_modules/eufy-security-client/src/http/device.ts:37:14
2022-11-24 17:42:59.406  ERROR Invalid Property wifiSignalLevel error 
 InvalidPropertyError  Property wifiSignalLevel invalid
error stack:
• device.ts:507 getPropertyMetadata
    node_modules/eufy-security-client/src/http/device.ts:507:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:48
• device.ts:120 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:120:18
• device.ts:2106 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:2106:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:22
• device.ts:138 updateRawProperty
    node_modules/eufy-security-client/src/http/device.ts:138:30
• device.ts:60 <anonymous>
    node_modules/eufy-security-client/src/http/device.ts:60:22
• device.ts:59 update
    node_modules/eufy-security-client/src/http/device.ts:59:35
• device.ts:37 initializeState
    node_modules/eufy-security-client/src/http/device.ts:37:14
2022-11-24 17:42:59.410  ERROR Invalid Property wifiSignalLevel error 
 InvalidPropertyError  Property wifiSignalLevel invalid
error stack:
• device.ts:507 getPropertyMetadata
    node_modules/eufy-security-client/src/http/device.ts:507:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:48
• device.ts:120 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:120:18
• device.ts:2106 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:2106:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:22
• device.ts:138 updateRawProperty
    node_modules/eufy-security-client/src/http/device.ts:138:30
• device.ts:60 <anonymous>
    node_modules/eufy-security-client/src/http/device.ts:60:22
• device.ts:59 update
    node_modules/eufy-security-client/src/http/device.ts:59:35
• device.ts:37 initializeState
    node_modules/eufy-security-client/src/http/device.ts:37:14
(node:10) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 station talkback start listeners added to [EufySecurity]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 station talkback stop listeners added to [EufySecurity]. Use emitter.setMaxListeners() to increase limit
2022-11-24 17:43:06.362  INFO  Connected to station T8400P20203628FA on host 192.168.123.115 and port 24135 
2022-11-24 17:43:06.446  INFO  Connected to station T8400P312212099B on host 192.168.123.223 and port 20502 
2022-11-24 17:43:06.483  INFO  Connected to station T8400P2020374477 on host 192.168.123.145 and port 26535 
2022-11-24 17:43:06.605  INFO  Connected to station T8010P13211804A3 on host 192.168.123.144 and port 12503

**Comment by fuatakgun** [comment]
this should have been sorted out now
