### ISSUE TITLE
Cannot unlock T7400 Smart Safe (requires PIN)

### ISSUE THREAD

**Issue by didgeriwho** [fuatakgun/eufy_security#521]
**Describe the bug**
Cannot unlock T7400 Smart Safe. When clicking 'Unlock', nothing happens.

**To Reproduce**
1. Go to Smart Safe device
2. Click on 'Unlock'

**Expected behavior**
Device unlocks.

**Add-on Error Log**
2022-11-13 23:10:55.306  ERROR Message error 
 NotSupportedError  This functionality is not implemented or supported by T7400T03222904FA

**HA Core Error Log**
eufy_security - Exception - process_messages: 'result' - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 297, in on_message message_result = payload[message_type] KeyError: 'result' - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":false,"messageId":"lock_device","errorCode":"device_not_supported"}', extra='')

**Additional context**
Add-on version: 1.1.0
Integration version 2.8.1

[bropat's client has added support for it recently. 
](https://github.com/bropat/eufy-security-client/issues/182)

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/595

**Comment by fuatakgun** [comment]
please retest with latest version of add-on and alpha release v5.x.x

**Comment by didgeriwho** [comment]
Lock entity seems to be removed entirely from the device unfortunately.

![image](https://user-images.githubusercontent.com/1590874/209851037-a8c3cc85-1fde-4108-8f14-4aae80ae9d43.png)

**Comment by fuatakgun** [comment]
Please look at Debug device attributes if you see anything about lock.

Moreover, you can share it here after clearing serial no stuff, it would be helpful for me.

**Comment by fuatakgun** [comment]
Furthermore, you can share the device with me and i can take a look at it locally.

**Comment by didgeriwho** [comment]
Thanks @fuatakgun. I'm unable to share the device since Eufy doesn't allow it - but I can link it to a burner account and share the account details with you if absolutely needed. 

See below for the attributes

Properties
name: Home Safe
model: T7400
serialNumber: T7400############
hardwareVersion: 0.0.0.2
softwareVersion: 1.0.3.4
type: 140
stationSerialNumber: T7400###########
battery: 100
wifiRssi: -55
wifiSignalLevel: 4
locked: true
wrongTryProtection: true
wrongTryAttempts: 5
wrongTryLockdownTime: 60
scramblePasscode: false
leftOpenAlarm: true
leftOpenAlarmDuration: 120
dualUnlock: false
powerSave: false
interiorBrightness: 60
interiorBrightnessDuration: 10
tamperAlarm: 2
remoteUnlock: true
remoteUnlockMasterPIN: true
alarmVolume: 2
promptVolume: 1
notificationUnlockByKey: true
notificationUnlockByPIN: true
notificationUnlockByFingerprint: true
notificationUnlockByApp: true
notificationDualUnlock: true
notificationDualLock: true
notificationWrongTryProtect: true
notificationJammed: true
Commands
unlock, verify_p_i_n
Voices

**Comment by fuatakgun** [comment]
Any error logs?

Burner account would be great

**Comment by fuatakgun** [comment]
thanks for sharing, fixed the integration regarding to missing lock entity, but eufy-security-ws is still not supporting locking and unlocking.

Please continue working with him to add this feature.

Error from eufy-security-ws 1.3 version
```
NotSupportedError  This functionality is not implemented or supported by T7400############
error stack:
• station.ts:4063 lockDevice
    node_modules/eufy-security-client/src/http/station.ts:4063:19

• eufysecurity.ts:1056 setDeviceProperty
    node_modules/eufy-security-client/src/eufysecurity.ts:1056:31

• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

• message_handler.ts:209 handle
    src/lib/device/message_handler.ts:209:17

• server.ts:125 receiveMessage
    src/lib/server.ts:125:21


```

**Comment by fuatakgun** [comment]
I think, I understand it now, first I need to send device.verify_pin and later device.unlock

I am still working on this

**Comment by fuatakgun** [comment]
Let's keep this open, I will wait for @bropat's response.

**Comment by fuatakgun** [comment]
I believe i found the culprit, can i continue testing tomorrow (in EU time)? Let me know if you would be interested so i can unlock it. Please double check if the burner account is still up and running.

**Comment by fuatakgun** [comment]
Ping @didgeriwho

**Comment by didgeriwho** [comment]
@fuatakgun Yes - you're clear to go ahead and test it. Burner account is still up and running. If you unlock it - I won't be able to lock the safe until regular EST hours.

**Comment by fuatakgun** [comment]
I believe i have unlocked your safe :)

**Comment by fuatakgun** [comment]
please get v5.3.2

**Comment by didgeriwho** [comment]
@fuatakgun Yes I saw that the device was unlocked this morning. But when I paired it with my regular account and updated to 5.3.3 I get the following error when trying to unlock

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/eufy_security/eufy_security_api/api_client.py:345
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:05:05 AM (1 occurrences)
Last logged: 10:05:05 AM

[140124047130480] {'type': 'result', 'success': False, 'messageId': 'device.set_property.6a8db8bda0e64dfaa28e76f3295970bf', 'errorCode': 'device_not_supported'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/eufy_security/lock.py", line 59, in async_unlock
    await self.product.set_property(self.metadata, False)
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 61, in set_property
    await self.api.set_property(self.product_type, self.serial_no, metadata.name, value)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 253, in set_property
    await self._send_message_get_response(OutgoingMessage(command_type, command=command, serial_no=serial_no, name=name, value=value))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 345, in _send_message_get_response
    return await future
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'device.set_property.6a8db8bda0e64dfaa28e76f3295970bf', 'errorCode': 'device_not_supported'}
`

**Comment by didgeriwho** [comment]
Adding Supervisor Add-On log

2022-12-31 15:05:05.868  ERROR Message error 
 NotSupportedError  This functionality is not implemented or supported by T7400###########
error stack:
• station.ts:4063 lockDevice
    node_modules/eufy-security-client/src/http/station.ts:4063:19
• eufysecurity.ts:1056 setDeviceProperty
    node_modules/eufy-security-client/src/eufysecurity.ts:1056:31
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• message_handler.ts:209 handle
    src/lib/device/message_handler.ts:209:17
• server.ts:125 receiveMessage
    src/lib/server.ts:125:21

**Comment by fuatakgun** [comment]
You cannot use lock function

When you want to unlock, you have to call lock.unlock service with code argument and supply your master pin over it.

So, lock entity on UI is just a state but wouldn't be helpful for you to lock/unlock the safe.

**Comment by didgeriwho** [comment]
> You cannot use lock function
> 
> When you want to unlock, you have to call lock.unlock service with code argument and supply your master pin over it.
> 
> So, lock entity on UI is just a state but wouldn't be helpful for you to lock/unlock the safe.

Ahh got it - I'm an idiot - thanks for clarifying. Finally got it after a couple of tries (kept getting random timeouts). Thank you so much for all the assistance!
