### ISSUE TITLE
Look around (360) button for 2k pan and tilt

### ISSUE THREAD

**Issue by Jezza1232** [fuatakgun/eufy_security#523]
**Is your feature request related to a problem?
 I am unclear at this stage.**

I wish to have a entity or binary for the 360 look around button on the eufy app in home assistant so I can press look around on my card inside home assistant.
 
**Describe the solution you'd like**
When I setup my eufy system to home assistant it was all automatic 😃😃😃 working so well no fault I simply wish to press the look around button from within the home assistant app the 2k pan and tilt has a (look around 360) feature after it completes it will return to the position it was in before)

**finding the scritp/binary/entity file and try and code one into the existing files?

**Additional context**
I am not that smart or I would try and do it my self

**Comment by fuatakgun** [comment]
a new service ptz_360 will be implemented in new version

**Comment by fuatakgun** [comment]
Until then, use this service
```
service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "cmdPanAndTiltUp",
      "command": "device.pan_and_tilt",
      "serialNumber": "T8410PXXXXXXXXXX",
      "direction": 0
    }
```
