### ISSUE TITLE
Update to schema v14

### ISSUE THREAD

**Issue by amosyuen** [fuatakgun/eufy_security#524]
**Is your feature request related to a problem? Please describe.**

Currently the integration uses schema v11, there have been various new features added in latest schemas that I would like to use, particularly the `snooze` command. https://bropat.github.io/eufy-security-ws/#/api_schema_versions?id=schema-14

**Describe the solution you'd like**

Update to schema v14, or at least v13.

**Comment by amosyuen** [comment]
I tried manually updating in my setup and it seems to work fine with my Eufy 2 cameras and 2k doorbell, but not sure if there is other compatbilities that are missing

**Comment by fuatakgun** [comment]
working on re-archutectering, so we will catch up latest schema (probably 15)
