### ISSUE TITLE
2C Pro: Light doesn't stay on after toggling

### ISSUE THREAD

**Issue by marcokitzmann** [fuatakgun/eufy_security#529]
**Describe the bug**
After switching on the cam light flashes briefly and goes out again immediately. However, the switch remains in the "on" state.

**To Reproduce**
1. Open entity switch.CAMNAME_light
2. Toggle switch

**Expected behavior**
light stays on ;)

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Camera Hardware: 2C Pro
- Live Streaming Protocol: RTSP

**Additional context**

**Comment by fuatakgun** [comment]
If I am not mistaken, light (spotlight) will stay on when there is an event happening. That flash is confirming that light will be on when there is a motion.

You cannot keep the light on :) Confirmed with my own 2c cameras.
