### ISSUE TITLE
Websocket port stays on 3000 although it's changed.

### ISSUE THREAD

**Issue by schumi2004** [fuatakgun/eufy_security#532]
**Describe the bug**
Websocket port stays on 3000 although it's changed.

**To Reproduce**
I followed setup instructions from point 6.1
When the Eufy Security Addon is installed and config adjusted I can't launch addon because it complaisn port 3000 is already in use.
So i changed it port 4000 and launched it.
But the log says:

2022-11-17 18:45:52.818  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-11-17 18:45:53.006  ERROR Response data is missing 
{
  code: 0,
  msg: 'Succeed.',
  data: undefined
}

So the port is still 3000 and the output doesn't match what is mentioned in setup instructions.

Then when you come to the steps for the Integration and configure it with correct host and port the integration fails with Incorrect host/port.
The new port (4000) configured in websocket nor the default port 3000 give a succesfull response.

**Expected behavior**
Seeying the websocket port being reflected in logs so we can continue the setup from step 6.3

**Hardware Information about Home Assistant
- Home Assistant 2022.11.2
- Supervisor 2022.10.2
- Operating System 9.3
- Frontend 20221108.0 - latest
- Eufy Security Add-on version: 1.1.0
- HACS Eufy Security version 2.8.1

**Hardware Information about Cameras
- Eufy Homebase 2 with Doorbell
- Live Streaming Protocol: n/a (can't continue setup)

**Comment by schumi2004** [comment]
After checking were port 3000 was used and filling in TRUSTED_DEVICE_NAME the addon started succesfull and I could continue setup. I do still think there are issues with adjusting default port 3000 to something else?

**Comment by LazareffR** [comment]
I filled in the TRUSTED_DEVICE_NAME field. And everything worked.

**Comment by fuatakgun** [comment]
what you see internally on docker logs is about internal port.
what you setup in home assistant add-on page is about external port.
In the logs, you will always see port as 3000.
