### ISSUE TITLE
Adding a T8503 to my Eufy Security account makes the whole integration non-functional

### ISSUE THREAD

**Issue by danielcbaldwin** [fuatakgun/eufy_security#533]
**Describe the bug**
When adding a T8503 to my Eufy Security account the integration stops working and goes into an initialization loop. The add-on seems to handle it just fine.

**To Reproduce**
1. Add T8503 to Eufy Security account
2. Reload the integration in Home Assistant

**Expected behavior**
Either ignore the unsupported device or have the device loaded in as a device in Home Assistant as all the properties appear to be there.

**Information about Home Assistant
Home Assistant 2022.11.3
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

**Eufy Security Add-on Version
1.1.0

** Eufy Security Integration Version
2.8.1

**Hardware Information about Lock
Model: T8503
Firmware Version: 1.0.6.9
Subsystem Version: 1.1.4.7
https://www.amazon.com/gp/product/B09ZV8TKSC/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Additional context**
Logs from Home Assistant:
`eufy_security - Exception - process_messages: 56 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 313, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 258, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 452, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 56 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"***","properties":{"name":"***","model":"T85A3","serialNumber":"***","type":56,"hardwareVersion":"P0","softwareVersion":"1.0.3.0","stationSerialNumber":"***","battery":100}}}', extra='')
eufy_security - Exception - process_messages: 54 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 328, in on_message await self.process_get_station_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 279, in process_get_station_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 452, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 54 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_station_properties","result":{"serialNumber":"***","properties":{"name":"Back Door","model":"T8503","serialNumber":"***","type":54,"hardwareVersion":"P0","softwareVersion":"1.0.6.9"}}}', extra='')
eufy_security - Exception - process_messages: 54 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 313, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 258, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 452, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 54 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"***","properties":{"name":"Back Door","model":"T8503","serialNumber":"***","type":54,"hardwareVersion":"P0","softwareVersion":"1.0.6.9","stationSerialNumber":"***","autoLockTimer":60,"autoLockScheduleStartTime":"23:00","autoLockScheduleEndTime":"06:00","wrongTryAttempts":5,"wrongTryLockdownTime":180,"sound":2,"oneTouchLocking":true,"notification":true,"autoLockSchedule":false,"notificationUnlocked":true,"autoLock":false,"battery":100,"scramblePasscode":false,"notificationLocked":true,"lockStatus":4,"locked":true,"wrongTryProtection":true}}}', extra='')
eufy_security - Exception - process_messages: 54 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 313, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 258, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 452, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 54 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"***","properties":{"name":"Back Door","model":"T8503","serialNumber":"***","type":54,"hardwareVersion":"P0","softwareVersion":"1.0.6.9","stationSerialNumber":"***","autoLockTimer":60,"autoLockScheduleStartTime":"23:00","autoLockScheduleEndTime":"06:00","wrongTryAttempts":5,"wrongTryLockdownTime":180,"sound":2,"oneTouchLocking":true,"notification":true,"autoLockSchedule":false,"notificationUnlocked":true,"autoLock":false,"battery":100,"scramblePasscode":false,"notificationLocked":true,"lockStatus":0,"locked":false,"wrongTryProtection":true}}}', extra='')
eufy_security - Exception - process_messages: 54 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 313, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 258, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 452, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 54 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"***","properties":{"name":"Back Door","model":"T8503","serialNumber":"***","type":54,"hardwareVersion":"P0","softwareVersion":"1.0.6.9","stationSerialNumber":"***","autoLockTimer":60,"autoLockScheduleStartTime":"23:00","autoLockScheduleEndTime":"06:00","wrongTryAttempts":5,"wrongTryLockdownTime":180,"sound":2,"lockStatus":4,"locked":true,"notificationLocked":true,"scramblePasscode":false,"autoLock":false,"notification":true,"autoLockSchedule":false,"notificationUnlocked":true,"battery":100,"wrongTryProtection":true,"oneTouchLocking":true}}}', extra='')`

**Comment by asucrews** [comment]
Hello, 

I get the same issue, here what i am seeing in home assistant logs

2022-11-17 17:05:15.926 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Exception - process_messages: 'connected' - traceback: Traceback (most recent call last):
  File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages
    await self.on_message(msg)
  File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message
    await self.message_callback(message)
  File "/config/custom_components/eufy_security/coordinator.py", line 310, in on_message
    await self.process_start_listening_response(message_result["state"])
  File "/config/custom_components/eufy_security/coordinator.py", line 232, in process_start_listening_response
    self.driver_connected = (states["driver"]["connected"] is True) or (
KeyError: 'connected'

2022-11-17 17:05:15.965 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Exception - process_messages: 'result' - traceback: Traceback (most recent call last):
  File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages
    await self.on_message(msg)
  File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message
    await self.message_callback(message)
  File "/config/custom_components/eufy_security/coordinator.py", line 297, in on_message
    message_result = payload[message_type]
KeyError: 'result'
 - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":false,"messageId":"driver_connect","errorCode":"unknown_command","args":{"command":"driver.connect"}}', extra='')

**Comment by fuatakgun** [comment]
Please give it a try with 1.3.0 version of add-on and alpha release (v5.x.x) of integration

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591
