### ISSUE TITLE
Home Assistant cannot connect to Eufy Security WS after updating to 1.1.0

### ISSUE THREAD

**Issue by YarneThatsMe** [fuatakgun/eufy_security#535]
**Describe the bug**
After updating to the new version of eufy_security web socket, HASS cannot connect to it anymore

**To Reproduce**
1. Go to HASS, integrations, Eufy security
2. Click on reload
3. See error: Start Listening was not completed in timely manner
4. Log file in eufy_secuirty_ws: 
2022-11-18 11:01:41.814  INFO  Client disconnected with ip: xxx.xxx.xxx.xxx port: 54236 code: 1000 reason: Normal Closure 
2022-11-18 11:02:21.927  ERROR Response data is missing 
{
  code: 0,
  msg: 'Succeed.',
  data: undefined
}

**Expected behavior**

**Screenshots**

**Hardware Information about Home Assistant
Docker container in UNRAID, HASS version: 2022.11.3
Eufy Security HACS version: 2.8.1
eufy-security-ws version: 1.1.0

**Hardware Information about Cameras
- HomeBase Gen2
- Eufy 2K wireless doorbell

**Additional context**

**Comment by zuohaot** [comment]
Check out here
#525

**Comment by YarneThatsMe** [comment]
> Check out here #525

Thanks for the tip, i've already looked at that one, but I couldn't find the TRUSTED_DEVICE_NAME in the configuration of the Eufy Security add on. I also don't see the option to change my username and password there, I went to Settings > Devices & Services > Configure Eufy Security.

Is this the correct path? (HASS Core Docker container, not the full OS itself)

**Comment by zuohaot** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/56582980/202817697-405cbc17-1aec-45f3-9a7f-c353af022162.png">
Are you on 1.1.0? You should be able to see this

**Comment by YarneThatsMe** [comment]
No I don't see that, maybe because I don't use the Eufy Security Add-on but the HACS integration

**Comment by zuohaot** [comment]
> No I don't see that, maybe because I don't use the Eufy Security Add-on but the HACS integration

That sounds odd to me cuz I remember we need both addon and HACS integration to make it work.

**Comment by zuohaot** [comment]
> No I don't see that, maybe because I don't use the Eufy Security Add-on but the HACS integration

Unless you run it somewhere else, like Docker I guess?

**Comment by YarneThatsMe** [comment]
I fixed it by adding the TRUSTED_DEVICE_NAME variable to the docker container config. Thanks for the help!
