### ISSUE TITLE
Changing IPs

### ISSUE THREAD

**Issue by wally69tbg** [fuatakgun/eufy_security#539]
I have recently changed my home IP address to 192.168.100.x and now every time I set up Eufy Security I'm faced with this error. I have added "TRUSTED_DEVICE_NAME: DEVICENAME" to the configuration and tried uninstalling and reinstalling through HACs with no luck. Also, have checked the app to confirm the IP is correct and have even rebooted the base station.

Any help or direction on this error is greatly appreciated.
I have a Base station with 2k Doorbell and this was working previously before changing IPs

Please find the logs for HA attached.

This error originated from a custom integration.

Logger: custom_components.eufy_security.config_flow
Source: custom_components/eufy_security/config_flow.py:167
Integration: Eufy Security (documentation, issues)
First occurred: 13:04:55 (1 occurrences)
Last logged: 13:04:55

eufy_security Exception in login : Cannot connect to host 192.168.100.12:3000 ssl:default [Connect call failed ('192.168.100.12', 3000)] - traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection raise exceptions[0] File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection sock = await self._connect_sock( File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock await self.sock_connect(sock, address) File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect return await fut File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb raise OSError(err, f'Connect call failed {address}') ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.100.12', 3000) The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/config_flow.py", line 199, in _test_credentials await eufy_ws.connect() File "/config/custom_components/eufy_security/websocket.py", line 41, in connect self.ws: aiohttp.ClientWebSocketResponse = await self.session.ws_connect( File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 776, in _ws_connect resp = await self.request( File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request conn = await self._connector.connect( File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect proto = await self._create_connection(req, traces, timeout) File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection _, proto = await self._create_direct_connection(req, traces, timeout) File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection raise last_exc File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection transp, proto = await self._wrap_create_connection( File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection raise client_error(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.100.12:3000 ssl:default [Connect call failed ('192.168.100.12', 3000)]

**Comment by fuatakgun** [comment]
if you HA and eufy add-on working on same instance, why dont you point as localhost or 127.0.0.1?

Anyway, if you want to change integration information either remove and add it back or manually update .config_entries file in home assistant folder.
