### ISSUE TITLE
entity basestation is not showing up

### ISSUE THREAD

**Issue by djoenee** [fuatakgun/eufy_security#54]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
the basestation entity is not showing up. 
i have following products: -wireless doorbell. (T8210P3321133286)
                                            -the basestation that came with it. (T8010P2321140373)
                                            -the 360 tilt camera. (T8411P2020390FB8)

the log from eufy security addon:

2021-09-17 08:56:54.051  INFO Eufy Security server listening on port 3000 
2021-09-17 08:57:05.460  INFO Connected to station T8010P2321140373 on host 192.168.0.5 and port 15726 
2021-09-17 08:57:05.508  INFO Connected to station T8411P2020390FB8 on host 192.168.0.40 and port 12104 

(so no error's)

doorbell and tilt camera is working like it should.
image + entity's
![18A562F3-8C76-423B-8166-9BF9158B55B9](https://user-images.githubusercontent.com/76220702/133758028-25f51a25-6123-4dc2-95a1-d988fbd29e25.png)

**Comment by fuatakgun** [comment]
If you can share one of cameras and base station, i can easily debug. Nothing comes to my mind.

**Comment by fuatakgun** [comment]
i had received an invite about home station and wireless doorbell, but not for ptz camera.

**Comment by djoenee** [comment]
Hello, i have added the 360, but that doesn't work with the homebase. 
mvg, j

**Comment by fuatakgun** [comment]
I have a feeling that integration is messing up with ptz as homebase, but failing to continue with actual homebase

**Comment by djoenee** [comment]
Yes, home,away,off,geofence,scheme and custom

**Comment by djoenee** [comment]
![Uploading 92F2090C-024D-453B-B139-D70CDF060BB5.png…]()

**Comment by fuatakgun** [comment]
So, you should have 2 base station through integration then, assuming doorbell base station is not connected with 360. Please re-upload the image.

**Comment by djoenee** [comment]
![DA800D5E-0A4E-48FF-B1FA-9F60BB684DB1](https://user-images.githubusercontent.com/76220702/133879325-ee5859b9-ec78-4bc7-a4c8-9d0f2386e5b5.png)

**Comment by djoenee** [comment]
Yes, the 360 camera act as its own base

**Comment by fuatakgun** [comment]
hey, I see that all devices are created successfully on my local setup. (please ignore my devices, I had pointed out yours with yellow)

![image](https://user-images.githubusercontent.com/11085566/133905524-f77ae5c2-819e-46ec-ae3d-46ac9b12a065.png)

**Comment by fuatakgun** [comment]
moreover, I see that 360 PTZ camera had been created correctly, it includes all sensors as camera and base station.

**Comment by djoenee** [comment]
i think i found the problem:
my Eufy Security WS Addon version was still 0.3.3 -> so i uninstalled it and tried to reinstall it. (installation showed 0.4.3).
but this gave me an error. --> i looked at bropat's github and there the top version is 0.4.2.
if i install with the docker command propat/.../latest then i am back at 0.3.3.
i think that version is from before intergration of the homebase.

**Comment by fuatakgun** [comment]
Please reload repositories list and stick with 0.3.3 version, i am still
testing new add on to release, i had published new version by mistake.

My test results are from 0.3.3

**Comment by djoenee** [comment]
![00FEDDE8-52A0-4A14-A71A-5D89BF8A445C](https://user-images.githubusercontent.com/76220702/133918544-13b03a82-5240-45a7-b4d4-16dc790c4bc3.png)
Strange, homebase is still not visable.

**Comment by fuatakgun** [comment]
Hey, let's create a new account and share your cameras and homebase with it and try again with new account?

**Comment by djoenee** [comment]
> moreover, I see that 360 PTZ camera had been created correctly, it includes all sensors as camera and base station.
> 
> ![image](https://user-images.githubusercontent.com/11085566/133905580-c8690e8a-3f7a-47ad-b725-6a7a8dd6b079.png)
> 
> Please double check everything, maybe delete and add integration back?

![13E6B4FC-0F0A-4874-92B4-D0B63D2A9F1D](https://user-images.githubusercontent.com/76220702/133918690-07914fa9-1a76-4739-8539-1bb1b749f8d8.png) i also don't have the armed entity on the 360 camera

**Comment by djoenee** [comment]
> Hey, let's create a new account and share your cameras and homebase with it and try again with new account?
Hm, i still have the same issues

**Comment by fuatakgun** [comment]
That is strange, let me test my local codebase if it is different then latest version in github.

in the meantime, you are sure that you are in latest version of integration, right?

**Comment by djoenee** [comment]
Fixit it, an update from the xx.5.x to xx.9.x from hassio core did the job.
Thanks for everything fuatakgun!

**Comment by fuatakgun** [comment]
Welcome, do not forget to remove shared cameras
