### ISSUE TITLE
Motion detection of camera only working, when notifications in Eufy app are enabled

### ISSUE THREAD

**Issue by dMopp** [fuatakgun/eufy_security#543]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Motion detection of camera only working, when notifications in Eufy app are enabled. If I disable the motion detection push messages in the app, motion detection is not working at all in Dufy add-on anymore

**To Reproduce**
1. Start Eufy Mobile app
2. Go to security
3. modify any entry there (preferred the active one.. :D)
4. disable "push notifications" for the camera(s)

Now the motion sensor of the camera is not detecting any motion anymore, even if the camera still records and detecting the motion

**Expected behavior**
The motion sensor should work independent of push notifications settings inside the app

**Screenshots**
---

**Hardware Information about Home Assistant
KVM - nothing special

**Hardware Information about Cameras
- EufyCam 2C

**Additional context**
Everything is up2date. Firmware, HA, AddOn, custom component, app, ...

**Comment by crispywisp** [comment]
Same issue with Homebase 3 and EufyCam 3C. Everything, even motion sensors only work when the notification is on in the app.

A quick temporary fix is disabling the notification for Eufy app in the phone settings so you don't get bombarded with notifications.

**Comment by thewolf-oz** [comment]
As per the troubleshooting, this is expected. The integration relies on the push notifications. As annoying as it is, the integration says it has this requirement and this is the way it’s architected. Android allows more granular notifications at the OS level so iOS users are stuck with constant notifications until this is changed or Eufy allow per account notifications 

3. Troubleshooting

1- Create a separate account for HA integration as that account will be logged out automatically from mobile app when HA integration logged in. Do not forget to share your cameras with your new account (preferably with adming rights), enable motion notifications with full picture and enable push notifications. This integration depends on push notifications to catch any updates.

**Comment by fuatakgun** [comment]
Thanks for explanation @thewolf-oz , you put it well

**Comment by dMopp** [comment]
Yeah, thanks for that. So another Anker pitfall by design :(

**Comment by fuatakgun** [comment]
it is not about Anker but the technical solution of this integration is emulating mobile app. You are actually running this mobile app inside add on and integration communicates with it.

If we want instant notifications about motions, mobile app should receive them.

Anker should enable user based notifications so you will not be bloated:-)

**Comment by fuatakgun** [comment]
working as intended
