### ISSUE TITLE
Snapshot showing where ?

### ISSUE THREAD

**Issue by muckie89** [fuatakgun/eufy_security#546]
The Motion Sensor is working. It displays a picture but i cant find it. Like to make a dash board. 

Where i find this image ? 
![faeaegaegaeg](https://user-images.githubusercontent.com/90051427/203618709-87c0f6e2-45f1-400e-ad24-c7a89cdd5dbb.png)

**Comment by BillyBobMills** [comment]
The url is stored in the entity picture attribute.

states.camera.doorbell.attributes.entity_picture

which is something like: 
/api/camera_proxy/camera.doorbell?token=4500xxxxxxxx

To view the imae prefix this with your home assistant url:port
