### ISSUE TITLE
eufy SoloCam: Is there any way to manually trigger the camera to take a photo?

### ISSUE THREAD

**Issue by elirev4** [fuatakgun/eufy_security#549]
Hello,

I'm using the eufy SoloCam E40 together with the eufy_security integration, and I was wondering if there was any way to call service that will make the camera take a photo of what it currently sees?
Context: I find the camera's motion detection events a bit too unreliable, so I'm relying on my doorbell automation in HA to let me know when someone's at the door. I would like the automation to manually take a photo of what the camera currently sees, and send that photo in a notification to my phone.

Thank you!

**Comment by fdellutri** [comment]
Hi,
I'm looking for the same feature

**Comment by fuatakgun** [comment]
you need to use camera.snapshot service of home assistant
