### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by HeinK847** [fuatakgun/eufy_security#550]
Tried an install, and got this on the log.

• device.ts:37 initializeState
    node_modules/eufy-security-client/src/http/device.ts:37:14
2022-11-27 16:15:34.393  ERROR Invalid Property wifiSignalLevel error 
 InvalidPropertyError  Property wifiSignalLevel invalid
error stack:
• device.ts:507 getPropertyMetadata
    node_modules/eufy-security-client/src/http/device.ts:507:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:48
• device.ts:120 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:120:18
• device.ts:2106 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:2106:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:22
• device.ts:138 updateRawProperty
    node_modules/eufy-security-client/src/http/device.ts:138:30
• device.ts:60 <anonymous>
    node_modules/eufy-security-client/src/http/device.ts:60:22
• device.ts:59 update
    node_modules/eufy-security-client/src/http/device.ts:59:35
• device.ts:37 initializeState
    node_modules/eufy-security-client/src/http/device.ts:37:14
2022-11-27 16:15:34.429  ERROR Invalid Property wifiSignalLevel error 
 InvalidPropertyError  Property wifiSignalLevel invalid
error stack:
• device.ts:507 getPropertyMetadata
    node_modules/eufy-security-client/src/http/device.ts:507:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:48
• device.ts:120 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:120:18
• device.ts:2106 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:2106:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:22
• device.ts:138 updateRawProperty
    node_modules/eufy-security-client/src/http/device.ts:138:30
• device.ts:60 <anonymous>
    node_modules/eufy-security-client/src/http/device.ts:60:22
• device.ts:59 update
    node_modules/eufy-security-client/src/http/device.ts:59:35
• device.ts:37 initializeState
    node_modules/eufy-security-client/src/http/device.ts:37:14
2022-11-27 16:15:34.467  ERROR Invalid Property wifiSignalLevel error 
 InvalidPropertyError  Property wifiSignalLevel invalid
error stack:
• device.ts:507 getPropertyMetadata
    node_modules/eufy-security-client/src/http/device.ts:507:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:48
• device.ts:120 handlePropertyChange
    node_modules/eufy-security-client/src/http/device.ts:120:18
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:22
• device.ts:138 updateRawProperty
    node_modules/eufy-security-client/src/http/device.ts:138:30
• device.ts:60 <anonymous>
    node_modules/eufy-security-client/src/http/device.ts:60:22
• device.ts:59 update
    node_modules/eufy-security-client/src/http/device.ts:59:35
• device.ts:37 initializeState
    node_modules/eufy-security-client/src/http/device.ts:37:14
• device.ts:2567 initialize
    node_modules/eufy-security-client/src/http/device.ts:2567:16
2022-11-27 16:15:38.697  INFO  Push notification connection successfully established 
2022-11-27 16:15:38.780  INFO  Connected to station T8010P232012111A on host ZZZ and port ZZZ

There is a red dot and starting does not work.

What did I do wrong?

**Comment by fuatakgun** [comment]
should be fixed by now
