### ISSUE TITLE
person name and vehicle detector sensor

### ISSUE THREAD

**Issue by wystewart** [fuatakgun/eufy_security#552]
with the new homebase3, it shows the person and pet detector binary sensor but not the vehicle binary sensor.   

also sensor person name detector shows unknown, i assume this should show the name of the person by facial recognition with homebase3

much appreciated if this could be fixed, would make for some great automations.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591

**Comment by fuatakgun** [comment]
If person name is not working correctly, please check with @bropat on eufy-security-ws repository, I cannot help there.
I will include vehicle detector sensor.

**Comment by fuatakgun** [comment]
vehicle sensor is added to alpha release
