### ISSUE TITLE
Intallation guide links are not working

### ISSUE THREAD

**Issue by JuhaFIN1** [fuatakgun/eufy_security#557]
At end og guide there is links:
RTSP Experience with WebRTC: https://drive.google.com/file/d/1qIYUx82C0CnpsTycP9dTS0NX6IEqeqHD/view?usp=drivesdk
P2P Experience with WebRTC: https://drive.google.com/file/d/1qCW9XX32vInQgFF7hPqoxp-ssno2Sye9/view?usp=drivesdk

Both of these are not working anymore. Can you fix these?

Thank you!

**Comment by fuatakgun** [comment]
they are not guide links, just showing how they are working locally, I will remove them. Nothing needing, thanks for raising the concern.
