### ISSUE TITLE
Picture Updated Event

### ISSUE THREAD

**Issue by BillyBobMills** [fuatakgun/eufy_security#558]
Is it possible to have an event (or have the doorbell last updated timestamp set again) when the doorbell picture that is within the entity url is updated?

states.camera.doorbell.attributes.entity_picture

There doesn't seem to be a way to know when the image is changed in that property and it can be a while after a doorbell event is raised.

The doorbell last changed and last updated timestamps dont get updated when the image is changed.

For example. My doorbell sees motion. I cast the image that is hosted at states.camera.doorbell.attributes.entity_picture and it can be an image from yesterday. A few seconds a picture card using that image is updated with the fresh image.

**Comment by fuatakgun** [comment]
there will be a specific sensor in new version for latest notification picture

**Comment by fuatakgun** [comment]
![image](https://user-images.githubusercontent.com/11085566/209590686-e3ff24a6-879c-434b-bd39-c62c92cbad78.png)
