### ISSUE TITLE
ERROR Response data is missing  

### ISSUE THREAD

**Issue by mattheeussen** [fuatakgun/eufy_security#560]
Hello,
I am using the Eufy Security Add-on for one year now and it always worked perfect. Today i noticed my automations stopped working so i checked my HA and all the sensors are unavailable. ( i don't use the video steams in HA, only motion sensors ) 

i checked the Eufy Add-on, maybe my account on Eufy was disabled so i tested my credentials on the eufy website and they are still valid.

in the log i only see this returning :
`2022-12-06 18:32:02.293  INFO  Client disconnected with ip: 192.168.0.10 port: 36584 code: 1000 reason: Normal Closure 
2022-12-06 18:33:22.445  ERROR Response data is missing 
{
  code: 0,
  msg: 'Succeed.',
  data: undefined
}
2022-12-06 18:33:35.092  INFO  Client disconnected with ip: 192.168.0.10 port: 42394 code: 1000 reason: Normal Closure 
2022-12-06 18:34:56.058  ERROR Response data is missing 
{
  code: 0,
  msg: 'Succeed.',
  data: undefined
}
2022-12-06 18:35:07.884  INFO  Client disconnected with ip: 192.168.0.10 port: 35618 code: 1000 reason: Normal Closure 
2022-12-06 18:36:28.018  ERROR Response data is missing 
{
  code: 0,
  msg: 'Succeed.',
  data: undefined
}
2022-12-06 18:36:40.681  INFO  Client disconnected with ip: 192.168.0.10 port: 49214 code: 1000 reason: Normal Closure `

i also noticed on the eufy intigration app it gives the error: Retrying setup: Start Listening was not completed in timely manner

version HA: 2022.11.5
version HACS: 1.28.4
version Add-on: 1.1.0

Am i the only person with this issue? i see alot of open issues with connection problems lately but they look different?

on my firewall i did a port test to the ip of my HA and for example port 8123 responded open but port 8554 that is need for the eufy intigration is closed? 
Maybe its a port issue? but its going from the HA ip to the HA ip port 8554 so if its a port issue it could have nothing to do with my network?

Is there anything i can test? 

thanks in advance
best regards
Bart

**Comment by fuatakgun** [comment]
Probably, due to latest security related issues, eufy updated their app and many firmwares on devices. We should wait for a solution, which we don't have at hand now

**Comment by mattheeussen** [comment]
Thank you for the response. Ok clear lets wait a little

**Comment by n1ghtang31** [comment]
Try filling out the trusted device field I just put in Home_assistant and I've at least gotten to the next step. Now getting stuck on getting the integration to talk to the add on.

**Comment by wystewart** [comment]
> Probably, due to latest security related issues, eufy updated their app and many firmwares on devices. We should wait for a solution, which we don't have at hand now

do you mean wait for bropat to update the underlying api?  Has the appropriate issue ticket been raised there?

**Comment by incmve** [comment]
> Try filling out the trusted device field I just put in Home_assistant and I've at least gotten to the next step. Now getting stuck on getting the integration to talk to the add on.

This worked, after putting something in the trusted device field the plugin worked.

**Comment by Fabsgreg** [comment]
> Try filling out the trusted device field I just put in Home_assistant and I've at least gotten to the next step. Now getting stuck on getting the integration to talk to the add on.

Thanks, this worked on my side.
I had exactly the same issue since last night, filling the "trusted device" field with only one of my devices name seems to have solved the issue, now my add-on launches correctly and my commands and automation executed from HA on my cameras work again.

**Comment by Danielson187** [comment]
> Try filling out the trusted device field I just put in Home_assistant and I've at least gotten to the next step. Now getting stuck on getting the integration to talk to the add on.

Where do i configure this? :)

**Comment by mattheeussen** [comment]
Hello, do you mean this https://www.home-assistant.io/docs/authentication/providers/ ? i am also wondering what you mean with trusted device field?

**Comment by fuatakgun** [comment]
![Screenshot_2022-12-07-18-40-20-918_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/206253518-4c90e427-68c0-47f9-8816-6a57187a1f34.jpg)

It is on add on configuration page.

**Comment by ema-dev** [comment]
> > Try filling out the trusted device field I just put in Home_assistant and I've at least gotten to the next step. Now getting stuck on getting the integration to talk to the add on.
> 
> Where do i configure this? :) I'm using Docker...

Add an environment variable called TRUSTED_DEVICE_NAME to the container and try setting its value to something like "Pixel 3a XL" or whatever mobile device you use.

**Comment by schumijo** [comment]
Thanks it works after adding trusted device

**Comment by mmichon** [comment]
If you're running this manually as a docker container, make sure to use `-e TRUSTED_DEVICE_NAME=whatever` or add  
```
environment:
  - 'TRUSTED_DEVICE_NAME=whatever'
```

to your `docker-compose.yml`

**Comment by anthonyrdg42** [comment]
Hello, 
Having the same problem, I just filled in my trusted device in my Docker container : 

```
version: '3'
services:
  eufy-security-ws:
        environment:
            - USERNAME=USERNAME
            - PASSWORD=PASSWORD
            - COUNTRY=FR
            - TRUSTED_DEVICE_NAME=ONEPLUS A6013
        ports:
            - 3000:3000
        restart: always
        image: bropat/eufy-security-ws:latest
```


I now get a Captcha request, and I do get a security code by Mail, but I don't know what to do with it ... Where should I enter this code I get? 

```
2022-12-12 08:51:30.162  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-12-12 08:51:30.490  INFO  Requested verification code for 2FA 
```

**Comment by mgluchgit** [comment]
> Hello, Having the same problem, I just filled in my trusted device in my Docker container :
> 
> ```
> version: '3'
> services:
>   eufy-security-ws:
>         environment:
>             - USERNAME=USERNAME
>             - PASSWORD=PASSWORD
>             - COUNTRY=FR
>             - TRUSTED_DEVICE_NAME=ONEPLUS A6013
>         ports:
>             - 3000:3000
>         restart: always
>         image: bropat/eufy-security-ws:latest
> ```
> 
> I now get a Captcha request, and I do get a security code by Mail, but I don't know what to do with it ... Where should I enter this code I get?
> 
> ```
> 2022-12-12 08:51:30.162  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
> 2022-12-12 08:51:30.490  INFO  Requested verification code for 2FA 
> ```

Try turn off 2FA

**Comment by fuatakgun** [comment]
Currently, email based two factor authentication is not supported, need to be disabled

**Comment by anthonyrdg42** [comment]
Oh no it was just that... When I saw that the TRUSTED_DEVICE_NAME had to be added in the Docker container, I thought that it was mandatory to activate the 2FA authentication to have just this reliable device name ... 
So I just deactivated 2FA, while keeping the TRUSTED_DEVICE_NAME in my Docker container and it works again ! I broke my teeth on it all weekend for not much ahah 

Thanks a lot for your reactivity !
