### ISSUE TITLE
Arming the cameras no longer works

### ISSUE THREAD

**Issue by floow77** [fuatakgun/eufy_security#564]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Arming the cameras no longer works. The service alarm_control_panel.alarm_arm_away running but there is no effect on this status of homebase.

**Expected behavior**
arming the homebase

**Hardware Information about Home Assistant
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Interface utilisateur : 20221108.0 - latest

**Hardware Information about Cameras
- Homebase T8010
- eufy security integration v2.8.1

** eufy addon log **

```
2022-12-07 20:54:38.560  ERROR Station T8010N232112345 - Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'dsk_keys')
error stack:
• session.ts:1996 getDSKKeys
    node_modules/eufy-security-client/src/p2p/session.ts:1996:36
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• session.ts:319 renewDSKKey
    node_modules/eufy-security-client/src/p2p/session.ts:319:13
• session.ts:410 connect
    node_modules/eufy-security-client/src/p2p/session.ts:410:13
2022-12-07 20:54:53.568  ERROR Station T8010N232112345- All address lookup tentatives failed. 
2022-12-07 20:54:53.571  INFO  Timeout connecting to station T8010N232112345 
```

**Comment by renslinden** [comment]
Same issue

**Comment by renslinden** [comment]
After some restarts of both HA and the WS client it stopped working completely. No devices are passed through.

Looks like Eufy did some changes in their backend.

```
Logger: custom_components.eufy_security
Source: custom_components/eufy_security/coordinator.py:90
Integration: Eufy Security (documentation, issues)
First occurred: 09:17:29 (6 occurrences)
Last logged: 09:23:21

eufy_security - no devices available yet
```

**Comment by renslinden** [comment]
Nevermind [this](https://github.com/fuatakgun/eufy_security/issues/525#issuecomment-1315143963) fixed it for me.

**Comment by floow77** [comment]
Thanks @renslinden.
The communication from HA to Eufy is now OK but it's KO from Eufy to HA (the state of the entity alarm_control_panel.eufy is not update)
