### ISSUE TITLE
No longer works after Home Assistant .12 update

### ISSUE THREAD

**Issue by stewmclarke** [fuatakgun/eufy_security#566]
Since upgrading to the .2 update. The HACS integration no longer works. In settings>devices & services, I get this error: `Retrying setup: Start Listening was not completed in timely manner.`

The Addon part, appears to be working fine… Anyone else?

**Comment by WebfinityDesign** [comment]
Same problem here

**Comment by stewmclarke** [comment]
Genius! easy fix, thank you...

**Comment by maypo52** [comment]
> Genius! easy fix, thank you...

Where is this easy fix? I don't see it.

**Comment by ema-dev** [comment]
> > Genius! easy fix, thank you...
> 
> Where is this easy fix? I don't see it.

@maypo52 
https://github.com/fuatakgun/eufy_security/issues/525#issuecomment-1315143963

> Long story short: set the value of TRUSTED_DEVICE_NAME in the configuration of Eufy Security Add-on to any value that you like (e.g. HomeAssistant). Helped me out to fix this.

**Comment by smhogan** [comment]
> Since upgrading to the .2 update. The HACS integration no longer works. In settings>devices & services, I get this error: `Retrying setup: Start Listening was not completed in timely manner.`
> 
> The Addon part, appears to be working fine… Anyone else?

Can Confirm that Changing the TRUSTED_DEVICE_NAME and restarting the Eufy Security Add ON, did actually restore access.

![image](https://user-images.githubusercontent.com/52179688/206766548-df5ba898-4633-488b-a11d-6c987a4d277c.png)

**Comment by andyke1985** [comment]
I had the same problem after the last update. changing the TRUSTED_DEVICE_NAME did help me a little but now i get this in my log. Connected to station (...) on host (ip) and port (...) INFO  Disconnected from station (...) this keeps happening over and over with a different port each time.
