### ISSUE TITLE
No video stream

### ISSUE THREAD

**Issue by Jcsdanny37** [fuatakgun/eufy_security#568]
Hello good afternoon, forgive my English, for several days the camera has stopped working, if I restart it when clicking on the image it goes from streaming to not available, I have touched on the settings where it seems that there is a solution by adding a name to TRUSTED_DEVICE_NAME but it's still the same, I understand that due to the possible update of Eufy, some possible solution.  All the best

**Comment by stewmclarke** [comment]
I have the same problem...

**Comment by Jcsdanny37** [comment]
> I have the same problem...

what model of camera do you have?

**Comment by Jcsdanny37** [comment]
> > > I have the same problem...
> > 
> > 
> > what model of camera do you have?
> 
> I have the 2k video doorbell and several eufy Security Solo OutdoorCam C22... The appear in Home Assistant, with sensors etc, but I'm not able to stream these or see any screenshots as I could before...

then it's time to wait

**Comment by Jcsdanny37** [comment]
> > > I have the same problem...
> > 
> > 
> > what model of camera do you have?
> 
> I have the 2k video doorbell and several eufy Security Solo OutdoorCam C22... The appear in Home Assistant, with sensors etc, but I'm not able to stream these or see any screenshots as I could before...
mate, solved, the problem was in the Rtsp security, I have put the password as basic and copied to the TRUSTED_DEVICE_NAME section

**Comment by Raarrrinator** [comment]
> > > > I have the same problem...
> > > 
> > > 
> > > what model of camera do you have?
> > 
> > 
> > I have the 2k video doorbell and several eufy Security Solo OutdoorCam C22... The appear in Home Assistant, with sensors etc, but I'm not able to stream these or see any screenshots as I could before...
> > mate, solved, the problem was in the Rtsp security, I have put the password as basic and copied to the TRUSTED_DEVICE_NAME section

Hi! Could you please explain a bit more in detail what to do? I tried to find what you're referring too, but without success! TY

**Comment by rafaelmagalhaes** [comment]
I just added the integration today and im having same issue,

Doorbell 2k battery power no video stream
I have 2 eufyCam 2C no video stream
1 Solo OutdoorCam C22 no video stream

the only camera working is SoloCam S40 Wireless

**Comment by rafaelmagalhaes** [comment]
got both the eufyCam 2c working had to enable RTSP Stream in the device
![image](https://user-images.githubusercontent.com/2240343/208244301-3726c1a5-e9b2-43b6-a66b-aed1f7729a69.png)

cant find these settings for doorbell and the outdoorCam c22

**Comment by Jcsdanny37** [comment]
> > > > > I have the same problem...
> > > > 
> > > > 
> > > > what model of camera do you have?
> > > 
> > > 
> > > I have the 2k video doorbell and several eufy Security Solo OutdoorCam C22... The appear in Home Assistant, with sensors etc, but I'm not able to stream these or see any screenshots as I could before...
> > > mate, solved, the problem was in the Rtsp security, I have put the password as basic and copied to the TRUSTED_DEVICE_NAME section
> 
> Hi! Could you please explain a bit more in detail what to do? I tried to find what you're referring too, but without success! TY

Hello, good evening, sorry, I've seen the message now, the issue is that I have security removed from the eufy application and that's how it works, but I've noticed that it doesn't always work, there are times when I have to reset the configuration, so the truth is that doesn't work well.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/593
