### ISSUE TITLE
Thumbnails gone with Home Assistant and "bropat/eufy-security-ws" docker: 1.1.0

### ISSUE THREAD

**Issue by Beer17HWAM** [fuatakgun/eufy_security#569]
Eufy Doorbell T8210
Home assistant docker: 2012-12.1
"bropat/eufy-security-ws" docker: 1.1.0
eufy-security add-on: 2.9.0
So all newest versions.

I always had Thumbnails. Now it's all gone. I strongly suspect that this is a change made by eufy in response to these criticisms https://www.zdnet.com/home-and-office/smart-home/eufy-responds-to-security-concerns/

Is it??

Does the Thumbnail option ever return??

**Comment by martijnpoppen** [comment]
I noticed the same for the Homey integration. See: https://github.com/bropat/eufy-security-client/issues/273

**Comment by Jo-Jo1987** [comment]
same

**Comment by viseshrp** [comment]
Yep. Same here. Thumbnails are broken. I went back to an older version and it still wouldn't show up. 
@fuatakgun Any workarounds for this? Thank you!

**Comment by fuatakgun** [comment]
Please stay tight, i am also expecting a solution from @bropat over eufy-security-ws repository.

This is result of additional security measures from eufy, so all good.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591

**Comment by fuatakgun** [comment]
On alpha release, camera would generate the picture from last started stream.

**Comment by viseshrp** [comment]
> On alpha release, camera would generate the picture from last started stream.

What if streams are not used? I don't use RTSP. Does that mean thumbnails will still be missing unless I manually turn a stream on?

**Comment by fuatakgun** [comment]
then, you dont get the thumbnail, how can you get it with current status? Any suggestion?

**Comment by viseshrp** [comment]
> then, you dont get the thumbnail, how can you get it with current status? Any suggestion?

No worries. I was just curious  :)  I think that is fine and a good workaround for now until bropat or someone figures how to decrypt the thumbnail.

**Comment by fuatakgun** [comment]
I have read that he already found the solution but busy with personal stuff. so, just hang on
