### ISSUE TITLE
Since updating to 2.9.0 can’t arm / disarm cameras

### ISSUE THREAD

**Issue by cjeri** [fuatakgun/eufy_security#570]
Using HA 2022.12.1
Supervisor 2022.11.2

can no longer use the integration to arm or disarm the cameras

**Comment by tvvalbonne** [comment]
same issue

**Comment by dMopp** [comment]
Same here, also schedule service is gone

**Comment by dMopp** [comment]
Fix is mentioned here: https://github.com/fuatakgun/eufy_security/issues/525#issuecomment-1315143963

**Comment by tvvalbonne** [comment]
Fixed using  solution in dMopp comment, thanks
