### ISSUE TITLE
Setting hostname and port of rtsp-simple-server

### ISSUE THREAD

**Issue by shanedabes** [fuatakgun/eufy_security#58]
**Is your feature request related to a problem? Please describe.**
Enabling the use of the rtsp-simple-server for streaming is just a tickbox, which I assume just defaults to connecting on localhost. I run home assistant and these addons in a kubernetes cluster, so the rtsp-simple-server is not accessible on localhost.

**Describe the solution you'd like**
I would need the option to be able to set the hostname and port of the rtsp-simple-server.

**Comment by fuatakgun** [comment]
welcome to the show :) your request is taken into account, we can make it work this week

**Comment by jonwilliams84** [comment]
+1 - great to see this is being worked on!

**Comment by fuatakgun** [comment]
hey, a correction here, I am expecting that RTSP addon should work at the same place with WS Add On, not on localhost. So, if your WS Add On running on host X, RTSP Add On is expected to work on host X. Until I fix it from root, is this good enough for you?

**Comment by shanedabes** [comment]
Hmm, not really unfortunately. I'm running them all in containers so they'll be reachable on different hostnames.

**Comment by fuatakgun** [comment]
Hold on for couple of days, it is coming

**Comment by shanedabes** [comment]
No worries, I won't rush you at all, it's just great to you know you're considering it. You have other things of much higher priority that would be beneficial for more people, including myself :).

**Comment by fuatakgun** [comment]
Name one, just to be sure that if i am doing good with prioritization :-)

Btw, how is the performance with file based streaming?

**Comment by shanedabes** [comment]
Well I was watching the slow startup issue, which you've fixed now! So your prioritization looks pretty good so far :)

It's mixed tbh, I'm looking to compare the performance when I'm able to set up the addon properly. Also hoping it allows for streaming on the doorbell.

**Comment by fuatakgun** [comment]
please get latest codebase, you have now option to override rtsp docker address and tcp port
