### ISSUE TITLE
This is the error in seeing my logs for the add on

### ISSUE THREAD

**Issue by GuenterAnton57** [fuatakgun/eufy_security#582]
This is the error in seeing my logs for the add on
![6A7AE1F1-3EAB-4ECE-8296-A538C95C8E4B](https://user-images.githubusercontent.com/36119320/208768814-7ab9edf6-c716-40d7-8eb8-03325fc5ffce.png)

_Originally posted by @halfcab1981 in https://github.com/fuatakgun/eufy_security/issues/579#issuecomment-1360213771_

**Comment by GuenterAnton57** [comment]
I receive the same error log. I tried eufy and also other words as the trusted device name, but it doesn't work.

**Comment by kombasltd** [comment]
Same error here:

![image](https://user-images.githubusercontent.com/37916435/208897325-933551e7-da96-4cb9-b16d-9e3e5b1ed10b.png)

**Comment by Joostle** [comment]
I have the same issue. Looks like this might have something to do with the recent privacy issues Eufy/Anker have been accused of:
https://community.security.eufy.com/t/to-our-eufy-security-customers-and-partners/3568215

**Comment by multinet33** [comment]
Is an update of the addon possible ?

**Comment by vaderag** [comment]
Same issue - assuming this issue is responsible for error in the integrations page
![Uploading image.png…]()

**Comment by designasaw** [comment]
Looks like i also have this issue. 
error stack:
• index.js:118 <anonymous>
    node_modules/got/dist/source/as-promise/index.js:118:42
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
2022-12-21 15:46:47.444  INFO  No devices found. 
2022-12-21 15:56:48.225  ERROR EufyError - Code: undefined Message: undefined (HTTP Code: 403) - requestUrl: https://security-app-eu.eufylife.com/v1/house/station_list 
2022-12-21 15:56:48.228  ERROR Stations - Generic Error: 
 EufyError  Code: undefined Message: undefined (HTTP Code: 403)

**Comment by designasaw** [comment]
> Same issue - assuming this issue is responsible for error in the integrations page ![image](https://user-images.githubusercontent.com/17175988/208946939-1de8f184-ae75-4ad7-b3c3-9572f4d066a5.png)

i think adding "eufy" to trusted device might fix your issue

**Comment by vaderag** [comment]
> > Same issue - assuming this issue is responsible for error in the integrations page ![image](https://user-images.githubusercontent.com/17175988/208946939-1de8f184-ae75-4ad7-b3c3-9572f4d066a5.png)
> 
> i think adding "eufy" to trusted device might fix your issue

Nah - I did that a few days back (discussed on the other issue) - this is a new issue

**Comment by kauthmbt** [comment]
The problem is due to recent changes on the eufy side and should effect all of us sooner or later. See some recent posts:
https://github.com/bropat/eufy-security-ws/issues/168
https://github.com/bropat/eufy-security-client/issues/283

Some contributors are already on the way for a potential solution.
As soon as this will be approved we will probably also see an add-on update solving the issue.

**Comment by Marsman83** [comment]
Same problem here just after a reboot of HA, before it was working fine.

**Comment by cjeri** [comment]
+1 got the same error today. Was working fine yesterday! Look forward to the solution

**Comment by thewolf-oz** [comment]
> The problem is due to recent changes on the eufy side and should effect all of us sooner or later. See some recent posts: [bropat/eufy-security-ws#168](https://github.com/bropat/eufy-security-ws/issues/168) [bropat/eufy-security-client#283](https://github.com/bropat/eufy-security-client/issues/283)
> 
> Some contributors are already on the way for a potential solution. As soon as this will be approved we will probably also see an add-on update solving the issue.

I suspected this could be the case, great to see people are across it. Happy to assist if testing is required etc

**Comment by jfbourne** [comment]
1+ 👆

**Comment by kloodhu** [comment]
+1

**Comment by TheUncas** [comment]
Same error here, no more clue for now

**Comment by willyhabr** [comment]
+1

**Comment by joekingmo** [comment]
+1

**Comment by gunnm80** [comment]
+1

**Comment by Erikhanm** [comment]
+1

**Comment by krikkel** [comment]
+1

**Comment by gielk** [comment]
+1

**Comment by migueldc73** [comment]
My logs show something somewhat different, but same result, can't connect to the EUFY cloud :  

![EUFY](https://user-images.githubusercontent.com/107763234/209304581-681e1428-7873-48d3-aac5-f3f3eadd240a.png)

Does it matter which country you put in the config ?
I live in Belgium (BE), but all my settings are in English, so (US or UK)

double authentication is off for this account (obviously)

Does it have something to do with the fact that I still have an old instance of this add-on in HACS add-ons that I somehow cannot delete ?

![EUFY2](https://user-images.githubusercontent.com/107763234/209305125-8acdfc73-534c-4d33-90bb-4a2777e1807d.png)

**Comment by radaiko** [comment]
+1

**Comment by robertjanb** [comment]
+1

**Comment by BurningTheSky** [comment]
+1

**Comment by fuatakgun** [comment]
Everyone, please uninstall previous version of addon, install the new version 1.3.0. It is very important to uninstall it because we need to get rid of previous login data which is not compatible anymore.

After installing and starting the add-on with new version, enable the integration. I jave confirmed that p2p, rtsp, motion detection are working fine.

This is about to fix login issues but not about missing thumbnails, so please set your expectations

**Comment by Final-Hawk** [comment]
Works great! Thanks.

**Comment by Ampig** [comment]
Works great. Just had to sure reload the integration after reinstalling the add-on.

> install the new version 1.3.0 

For rookies like me, just a pointer... in order to pickup 1.3.0 rather than my existing 1.1.0 version, I had to remove the repository from the add-on store and re-add it.

Thanks.

**Comment by krikkel** [comment]
Worked perfect for me! Was so happy, thanks Fuatakgun & team!

Make sure you delete integration, reboot and add the integration back again! Super! 👌👌👌👌

**Comment by kloodhu** [comment]
thanks Fuatakgun, works great again!

**Comment by kauthmbt** [comment]
Great Christmas present for the community!
Thanks!

**Comment by TheUncas** [comment]
Hello, It works for me too, it’s a great job you did, very reactive. Thx a lot and have a merry Xmas ! Cheers ! @fuatakgun

**Comment by stanogustafik** [comment]
@fuatakgun really good work! Everything runs again!! Merry Xmas and thank you sooo much! :)

**Comment by kongo09** [comment]
Unfortunately, the camera stream stopped working. Strange enough, it was working while the add-on was not working.

**Comment by FeromonDE** [comment]
```
Logger: homeassistant.components.alarm_control_panel
Source: custom_components/eufy_security/alarm_control_panel.py:240
Integration: Панель сигнализации (documentation, issues)
First occurred: 14:55:11 (6 occurrences)
Last logged: 15:09:11

Error adding entities for domain alarm_control_panel with platform eufy_security
Error while setting up eufy_security platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 240, in state
    return CODES_TO_STATES[current_mode]
KeyError: -1

The Station was set to "Time schedule".
```

**Comment by migueldc73** [comment]
@fuatakgun 

I remove v1.1 from the repository, rebooted, then installed v1.3, but still getting this issue 👍 
2022-12-24 22:12:05.871  ERROR Data decryption error, invalidating session data and reconnecting... 
 TypeError  The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
details:
{
  code: 'ERR_INVALID_ARG_TYPE'
}
error stack:
• errors:387 NodeError
    node:internal/errors:387:5
• cipher:176 update
    node:internal/crypto/cipher:176:11
• utils.ts:175 decryptAPIData
    node_modules/eufy-security-client/src/http/utils.ts:175:16
• api.ts:1027 decryptAPIData
    node_modules/eufy-security-client/src/http/api.ts:1027:43
• api.ts:528 getDeviceList
    node_modules/eufy-security-client/src/http/api.ts:528:49
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• api.ts:574 refreshDeviceData
    node_modules/eufy-security-client/src/http/api.ts:574:25
• api.ts:596 refreshAllData
    node_modules/eufy-security-client/src/http/api.ts:596:9
• eufysecurity.ts:619 refreshCloudData
    node_modules/eufy-security-client/src/eufysecurity.ts:619:9
• message_handler.ts:60 handle
    src/lib/driver/message_handler.ts:60:17
2022-12-24 22:12:05.874  ERROR Tried to re-authenticate to Eufy cloud, but failed in the process. Manual intervention is required! 
2022-12-24 22:12:05.875  INFO  No devices found. 

I just wonder if it really matters what country code you fill in ? I tried US (default), BE (my country), but same error.

**Comment by multinet33** [comment]
Hello

retype email and password 
FR is working on my side

**Comment by fuatakgun** [comment]
you need to remove the whole add-on, install latest version, put your credentials and start it.
If you are managing your own docker instance, I do not know how to help.
