### ISSUE TITLE
cannot install "Eufy Security WS Addon"

### ISSUE THREAD

**Issue by migueldc73** [fuatakgun/eufy_security#583]
my HASS simply does not allow me to install the latest Eufy Security WS Add-on :
1) When I go to the add-on store, I can only see a very old version of the add-on, v0.9.2 :
![1](https://user-images.githubusercontent.com/107763234/209238255-a4328e3e-ec63-4a70-8315-978c04a1bb2a.jpg)

![2](https://user-images.githubusercontent.com/107763234/209238330-38d5f25a-57ed-4346-a738-4bf4f7bdfc65.jpg)

2) It's clearly not installed, but I don't want that, I want to remove it, so I can add the new Add-on v1.1. But I can't remove it, it says there are not repositories :

![2a](https://user-images.githubusercontent.com/107763234/209238703-d71ff784-7cdf-4026-8b01-38d2ad2d84c3.jpg)

3) When I try to add the latest add-on from : https://github.com/fuatakgun/eufy_security_addon : 
![3a](https://user-images.githubusercontent.com/107763234/209239083-985d1913-1c92-4a7d-a00b-b9676876a216.jpg)
![3b](https://user-images.githubusercontent.com/107763234/209239148-5a74c3d0-e2bd-42a6-8515-0624ab4d8aff.jpg)

4) I restart HASS, but still I keep seeing the old  one, not the new : 

![1](https://user-images.githubusercontent.com/107763234/209239295-df466f29-8df9-4049-98a9-34a4f4da9153.jpg)

5) I tried using the old v0.9.2, but it's clearly not accepted by EUFY cloud anymore :
![5](https://user-images.githubusercontent.com/107763234/209239482-ed87fc54-a1eb-4e6a-bba4-9eba8ed86f62.jpg)

I am a quite experienced HASS user, but it seems like I am going in circles. I just cannot get the proper version of the add-on installed.

**Comment by willyhabr** [comment]
Same with me

**Comment by migueldc73** [comment]
by removing the EUFY Security integration in HACS, I was able to re-install v1.1, but the old one still resides next to the new. And I do have problems signing in 👍 

![EUFY2](https://user-images.githubusercontent.com/107763234/209305504-cbf10abc-5501-48e8-8d2f-c99828499fb1.png)

My problems signing in might be related to this or not, as there are several issues after EUFY changed it's cloud access (see other threads)

**Comment by fuatakgun** [comment]
Everyone, please uninstall previous version of addon, install the new version 1.3.0. It is very important to uninstall it because we need to get rid of previous login data which is not compatible anymore.

After installing and starting the add-on with new version, enable the integration. I jave confirmed that p2p, rtsp, motion detection are working fine.

This is about to fix login issues but not about missing thumbnails, so please set your expectations

**Comment by migueldc73** [comment]
> Everyone, please uninstall previous version of addon, install the new version 1.3.0. It is very important to uninstall it because we need to get rid of previous login data which is not compatible anymore.
> 
> After installing and starting the add-on with new version, enable the integration. I jave confirmed that p2p, rtsp, motion detection are working fine.
> 
> This is about to fix login issues but not about missing thumbnails, so please set your expectations

That is exactly the problem. I can uninstall the v1.1, but cannot get rid of the v0.9. It does not show up in the add-on repository. So there must be a way manually delete it, but how ?

**Comment by fuatakgun** [comment]
You somehow have it locally, not from GitHub, but it would not impact do not worry.

Local add-ons are coming from local folder of your home assistant server, i am mot controlling it.

As an experienced user, you can check this: https://developers.home-assistant.io/docs/add-ons/tutorial/
