### ISSUE TITLE
Home Assistant add-on won't start - "Killed"

### ISSUE THREAD

**Issue by jondye** [fuatakgun/eufy_security#584]
I uninstalled the home Assistant add-on v1.1.0 and installed v1.3.0. I entered the configuration and started the add-on. Some CPU and memory usage is shown and after less than a minute the add-on is shown as stopped. The only log message is "Killed".

I don't know how to collect more detailed logs.

**Comment by Burnerface** [comment]
+1

**Comment by werbi64** [comment]
+1

**Comment by Burnerface** [comment]
with my my login I have this log:

2022-12-24 13:00:10.393  INFO  Authentication properties changed, invalidate saved cloud token. 
Killed

**Comment by louiezhu2** [comment]
+1

**Comment by lpequigny** [comment]
Same issue. How to fix this problem?

**Comment by fuatakgun** [comment]
I have read in multiple threads (do not collect them now) that new version of addon requires much high memory to run. So if you are low on memory or you are limiting the memory consumption of add-on, it would be causing this to happen.

Of course, we should not stop investigation on increased memory usage, but until then, check memory restrictions

**Comment by protege323** [comment]
I'll get this message as well, and I'm no more able to install Eufy integration.

Memory could be not the reason cuz SSD drive

**Comment by fuatakgun** [comment]
How memory is related to ssd drive?

**Comment by lpequigny** [comment]
It's strange because I had this problem before updating in 1.3.0 and I haven't changed any memory settings

**Comment by lpequigny** [comment]
> I have read in multiple threads (do not collect them now) that new version of addon requires much high memory to run. So if you are low on memory or you are limiting the memory consumption of add-on, it would be causing this to happen.
> 
> Of course, we should not stop investigation on increased memory usage, but until then, check memory restrictions

It's strange because I had this problem before updating in 1.3.0 and I haven't changed any memory settings

**Comment by bartgabriels** [comment]
+1 ... Also issue here

**Comment by tmbs1988** [comment]
+1 here also.. i don't have any restrictions of memory as i know , and when starting it only uses like 2-3% vram then just killed...

**Comment by hanseandersson** [comment]
same issue here..

**Comment by jfbourne** [comment]
Same here +1

**Comment by vincentqho** [comment]
+1

**Comment by bartgabriels** [comment]
Is there a known way to downgrade the add-on?

**Comment by tmbs1988** [comment]
> I have read in multiple threads (do not collect them now) that new version of addon requires much high memory to run. So if you are low on memory or you are limiting the memory consumption of add-on, it would be causing this to happen.
> 
> Of course, we should not stop investigation on increased memory usage, but until then, check memory restrictions

Looks like more people having this issue, do you have any idea what is causing it? I don't have any restrictions that i know of, and my memory is not full.

**Comment by bartgabriels** [comment]
Me neither. Running it on a Pi3.

**Comment by fuatakgun** [comment]
https://github.com/bropat/eufy-security-ws/issues/170

**Comment by tmbs1988** [comment]
> [bropat/eufy-security-ws#170](https://github.com/bropat/eufy-security-ws/issues/170)

The guy in this post is using a addon limiter, i am not.. I am only using the standard Hass supervisor. 
So is the solution to install an addon limiter?

**Comment by fuatakgun** [comment]
can you create a new issue under eufy-security-ws ?

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/597

**Comment by fuatakgun** [comment]
so, putting aside what you all have already tried, this is the problem;
- 1.3.0 version requires old authentication information to be wiped.
- when you remove the add-on and add it back to home assistant, supervisor should wipe this persistent information.
- for some reason, this persistent information is not removed and when you want to start the add-on with 1.3.0, you are receiving this warning and add-on stops.

So, I am not sure if @bropat can help you on this, seems to be specific to home assistant.
You can definitely change your password and try again, this might remove the old information.

**Comment by werbi64** [comment]
Good evening I changed my password, I got this error message: 2022-12-29 23:06:07.943  INFO  Authentication properties changed, invalidate saved cloud token.
I created another account, the same.

**Comment by hanseandersson** [comment]
Same thing here . The only thing i can see in common is that all people having problem is that they run on rpi3 ?

**Comment by bartgabriels** [comment]
Indeed. Reentering account details didn’t work for me. Still ‘killed’ after
30-60minutes of running.

Op vr 30 dec. 2022 om 08:01 schreef hanseandersson ***@***.***

**Comment by werbi64** [comment]
Hello I completely reinstalled Home Assistant (I started from 0). The addon works again for now.

**Comment by omar10wahab** [comment]
Also having this issue and running rpi3b+ . Was working fine before 1.3 update. I tried resetting password, uninstalling and reinstalling add-on and nothing worked. Please help @bropat

**Comment by bartgabriels** [comment]
Tried reinstall and reconfigure. Seems to work on first try, but then HA crashes and reboots. Then the Killed message in logs reappears

**Comment by mahir1505** [comment]
Same issue
Running HA in a VM with plenty of ram (10gig)
Just installed the addon, and it gets killed at boot
even with 2FA off, and new account

**Comment by fuatakgun** [comment]
I dont have a solution in place for this.

Try to run the add-on in different machine using docker command and see the results.
