### ISSUE TITLE
Captcha issue after thumbnail fix

### ISSUE THREAD

**Issue by Jo-Jo1987** [fuatakgun/eufy_security#585]
I tried to add my account several times again.
Still problems with Captcha.
I am using the supervised Home Assistant latest version
With version 1.3.0 eufy security add-on

I saw bropat fixed some of the schemes.
But still i am not able to re-connect the camera.

I removed persistent.json and options.json.

What am i doing wrong? Getting multiple e-mails everytime but i can't use the one time authentication code at all when i typed in the captcha.

If i use my phone, and register it will tell, it already has something registered.

So please this happens after 2fa is mandatory.
I was able to restore it once, but it took ages to get the Captcha and Eufy connected back in Homeassistant.

Can you please help me get this sorted?

![image](https://user-images.githubusercontent.com/45689992/209447157-9a80d115-b477-454c-9db6-d4d656d202bb.png)
![image](https://user-images.githubusercontent.com/45689992/209447214-c5776614-880e-43b0-9829-844445fe5527.png)

**Comment by Jo-Jo1987** [comment]
I currently fixed it.
I know what i do wrong.

I should turn off the 2 factor in the app completely 
And then.
I can add the captcha from home assistant with enabling the 2 factor at the same time.

Although, thumbnail issue persists. Waiting for future release from FuatAKgun. Thanks in advance.

**Comment by fuatakgun** [comment]
2fa is never supported under this integration, why do you need to enable it?

**Comment by Jo-Jo1987** [comment]
It worked like a charm for a while.
After the TRUSTED_DEVICE option was added.
I needed to fill in something at least.
And it would connect, otherwise it wouldn't.

I found out that it only worked with 2fa enabled that time. But afterwards it stopped working
