### ISSUE TITLE
Eufy security

### ISSUE THREAD

**Issue by GuenterAnton57** [fuatakgun/eufy_security#586]
I have installed now Version 1.3.0 of eufy Security and it runs well again. I receive the following error in the eufy Security log:

error stack:
• node:dns:109 onlookup
    node:dns:109:26
2022-12-25 00:50:42.419  INFO  Push notification connection closed 
2022-12-25 00:51:17.439  ERROR onSocketError: 
 Error  getaddrinfo EAI_AGAIN mtalk.google.com
details:
{
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'mtalk.google.com'
  
What is the problem and how can I solve it.

**Comment by fuatakgun** [comment]
You are probably blocking calls to `mtalk.google.com` endpoint in your network?

**Comment by GuenterAnton57** [comment]
Many thanks for your impediate response. I don‘t what that means and what parameter in my FRITZ!Box causes that. But I assume that this does not affect proper working of the eufy Security add on. Is that right.

**Comment by fuatakgun** [comment]
Not sure how it might effect, please report back us so we can learn :-) but, there is nothing i can do, maybe google endpoint might be down for some reason.

in the meantime, you can ping respective endpoint in docker, if you like a bit advanced stuff
