### ISSUE TITLE
unable to download the add on 

### ISSUE THREAD

**Issue by kibrom631** [fuatakgun/eufy_security#587]
I used previously  this add on and it was working fine. recently, was working on some issues and uninstalled it. when i try to install it it again, I am getting invalid repository. please let me know if you  made changes since last 5 months and send me the link to download it.

**Comment by fuatakgun** [comment]
add-on is here: https://github.com/fuatakgun/eufy_security_addon

**Comment by dylankolson** [comment]
https://github.com/fuatakgun/eufy_security_addon results in the following error https://github.com/fuatakgun/eufy_security is not a valid add-on repository

Home Assistant 2023.2.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
