### ISSUE TITLE
Update Eufy Security WS Add On to 0.5.2 (latest)

### ISSUE THREAD

**Issue by fuatakgun** [fuatakgun/eufy_security#59]
Bugs;
- https://github.com/bropat/eufy-security-ws/issues/27 - Fixed
- https://github.com/bropat/eufy-security-ws/issues/40 - Fixed

Improvements:
- https://github.com/bropat/eufy-security-ws/issues/33 - Discarded
- https://github.com/bropat/eufy-security-client/issues/45 - Implemented

**Comment by skank01** [comment]
> i am not worried about RTSP functionality, at least, it will not contribute to p2p. RTSP has been working steady since beginning, because it is camera's responsibility to generate the stream, not add-on or integration

Yeah mm, well, here and others dont have the rtsp stable either... especially starting/stopping

**Comment by fuatakgun** [comment]
Can you please point some?

**Comment by skank01** [comment]
Sure, ask conorlap :) he's experiencing the same stuff as me
It was good for one hour, then nothing than trouble starting/stopping, streaming...

**Comment by boudicca99** [comment]
good morning, and chance of  how to update/upgrade instructions. Have stable 0.3.3. but nearly broke it trying to guess the how to upgrade....gets very confusing whether this is an upgrade process via cli or can it be done thru the HACS/HA GUI ? Please and Thanks Shaz

**Comment by fuatakgun** [comment]
thread is updated with 0.5.1
open issues;
- https://github.com/bropat/eufy-security-ws/issues/40

**Comment by fuatakgun** [comment]
targeted version number (0.5.2) is update

**Comment by fuatakgun** [comment]
with new version of add-on and integration, I am able to stream over p2p without time limit, I have tested up to 15 minutes

**Comment by skank01** [comment]
Cool wonder how good it is... curious about the loading part :)

**Comment by fuatakgun** [comment]
I hope i will publish it today, i am worried about migration as  new integration version is tightly coupled with new add-on version.

If a user updates their add-on, they should not skip integration update and vice versa.

I will rely on announcing through home assistant forum, let's see how it goes

**Comment by skank01** [comment]
Today, wauw great?
Am i right, a lot changed ? You need to update the readme? I'm not sure if the rtsp server addon is still needed too?
And if webrtc is still needed

**Comment by skank01** [comment]
> I hope i will publish it today, i am worried about migration as new integration version is tightly coupled with new add-on version.
> 
> If a user updates their add-on, they should not skip integration update and vice versa.
> 
> I will rely on announcing through home assistant forum, let's see how it goes

Hey, something went wrong?
Ur ok?

**Comment by fuatakgun** [comment]
updated both add-on and integration, please give it a try, YOU MUST UPDATE BOTH OF THEM.

**Comment by fuatakgun** [comment]
add-on version: 0.5.2
integration version: e7c7f05

![image](https://user-images.githubusercontent.com/11085566/141696249-fd1f22da-4d32-4ae7-a250-14a7c5a37cef.png)

**Comment by auspokey** [comment]
Updated add-on to 0.5.2 and latest integration and now I am getting the following error in the logs of the Add-on:
![image](https://user-images.githubusercontent.com/88024849/141716633-784b2534-7021-4825-a46c-189f63c9ead9.png)

**Comment by Freddan101** [comment]
> Updated add-on to 0.5.2 and latest integration and now I am getting the following error in the logs of the Add-on:
> ![image](https://user-images.githubusercontent.com/88024849/141716633-784b2534-7021-4825-a46c-189f63c9ead9.png)

I'm getting the same error. The push notifications work, but no camera entity is created. The base station device is not created, just the doorbell.

**Comment by skank01** [comment]
I'm not seeing that error.
I'm seeing connection established
And 4 times client disconnected with ip X port: 42018 code: 1006 reason:
All the devices are still there, here

**Comment by fuatakgun** [comment]
please track here about length issue: https://github.com/bropat/eufy-security-ws/issues/44
@Freddan101 @auspokey

**Comment by fuatakgun** [comment]
I will resolve this, you can create separate issues after we have a traction from @bropat about this: https://github.com/bropat/eufy-security-ws/issues/44
