### ISSUE TITLE
INFO  Authentication properties changed, invalidate saved cloud token.  Killed

### ISSUE THREAD

**Issue by kommis** [fuatakgun/eufy_security#590]
Hello, today there is a Problem after updating the Eufy Security Add-on to Current version: 1.3.0.

![grafik](https://user-images.githubusercontent.com/95351671/209712916-d214a86b-4d6f-4ecb-82d4-0fa8bb5328f7.png)

![grafik](https://user-images.githubusercontent.com/95351671/209712847-106a27ae-68aa-4d0f-b60b-19781afbb577.png)

Could you help me to solve the Problem?

**Comment by fuatakgun** [comment]
have you uninstalled and installed back the add-on?

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/584

**Comment by kommis** [comment]
> have you uninstalled and installed back the add-on?

Yes, 5 Times
1. Demeter integration
2. Uninstall Add-on
3. Uninstall Eufy Hacs Integration

**Comment by kommis** [comment]
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 22:49:30 (9 occurrences)
Last logged: 22:59:09

Failed to to call /addons/3a26b21d_eufy_security_addon/stats -

**Comment by kommis** [comment]
Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:473
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 22:49:30 (9 occurrences)
Last logged: 22:59:09

Timeout on /addons/3a26b21d_eufy_security_addon/stats request

**Comment by Paintballer19** [comment]
i am also having this issue as well

**Comment by kommis** [comment]
> #584

do you have a solution for that? I need the integration for my doorbell. It would be very nice, if there is a solution.

thanks

**Comment by thegreatspiros** [comment]
I also have this issue (Authentication properties changed, invalidate saved cloud token. )

I have reinstalled v1.3.0 and problem still persists. I have given my RPI3 a cold boot also.

Any ideas?

**Comment by fuatakgun** [comment]
Please switch to @bropat s version of add on
