### ISSUE TITLE
P2P Streaming Issues

### ISSUE THREAD

**Issue by fuatakgun** [fuatakgun/eufy_security#592]
1. https://github.com/fuatakgun/eufy_security/issues/403
2. https://github.com/fuatakgun/eufy_security/issues/401
3. https://github.com/fuatakgun/eufy_security/issues/440
4. https://github.com/fuatakgun/eufy_security/issues/463
5. https://github.com/fuatakgun/eufy_security/issues/531
6. https://github.com/fuatakgun/eufy_security/issues/134
7. https://github.com/fuatakgun/eufy_security/issues/329
8. https://github.com/fuatakgun/eufy_security/issues/431
9. https://github.com/fuatakgun/eufy_security/issues/496
10. https://github.com/fuatakgun/eufy_security/issues/487
11. https://github.com/fuatakgun/eufy_security/issues/504

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/403

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/401

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/440

**Comment by chicknlil** [comment]
[#608 ](https://github.com/fuatakgun/eufy_security/issues/608)

**Comment by fuatakgun** [comment]
Nope sound is not working with p2p streaming. Sound on rtsp stream is fine.
