### ISSUE TITLE
Alarm Panel Issues

### ISSUE THREAD

**Issue by fuatakgun** [fuatakgun/eufy_security#594]
1. https://github.com/fuatakgun/eufy_security/issues/542
2. https://github.com/fuatakgun/eufy_security/issues/347

**Comment by Jezza1232** [comment]
I am in the same boat however everything updated fine it went spastic for a few mins now it's all fine however I have no alarm control panel state it's now a entity that home assistant cannot use it very well at all and keeps saying unavailable anyway. But saying all that the update did fix my 2k cams states but still no footage in home assistant on 9.4 but it will respond to commands from H/A homebase 2 only listens when it wonts to now :(

**Comment by fuatakgun** [comment]
please try with alpha version
