### ISSUE TITLE
Everything is broken in version 5.0.3.  Integration fails to set up, indicates to check the logs.  Log data as follows:

### ISSUE THREAD

**Issue by fuatakgun** [fuatakgun/eufy_security#598]
**https://github.com/bropat/eufy-security-ws/issues/172**

        Everything is broken in version 5.0.3.  Integration fails to set up, indicates to check the logs.  Log data as follows:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/camera.py:132
Integration: Eufy Security (documentation, issues)
First occurred: 5:05:50 PM (2 occurrences)
Last logged: 5:25:41 PM

Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 45, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self.api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 66, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 123, in _set_products
    self.devices = await self._get_product(ProductType.device, result[MessageField.STATE.value]["devices"])
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 141, in _get_product
    product = Camera(self, serial_no, properties, metadata, commands)
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 35, in __init__
    self.set_stream_prodiver(StreamProvider.P2P)
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 132, in set_stream_prodiver
    url = url.replace("{server_address}", str(self.config.rtsp_server_address))
AttributeError: 'NoneType' object has no attribute 'rtsp_server_address'
```

_Originally posted by @chicknlil in https://github.com/fuatakgun/eufy_security/issues/591#issuecomment-1366221995_

**Comment by fuatakgun** [comment]
@chicknlil please get [v5.1.0](https://github.com/fuatakgun/eufy_security/releases/tag/v5.1.0)

**Comment by chicknlil** [comment]
Got 5.1.0, downloaded it twice, checked and restarted twice. Refreshed several times. Cleared cache etc. Error persists:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/camera.py:132
Integration: Eufy Security (documentation, issues)
First occurred: 5:45:45 PM (1 occurrences)
Last logged: 5:45:45 PM

Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 45, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self.api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 66, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 123, in _set_products
    self.devices = await self._get_product(ProductType.device, result[MessageField.STATE.value]["devices"])
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 141, in _get_product
    product = Camera(self, serial_no, properties, metadata, commands)
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 35, in __init__
    self.set_stream_prodiver(StreamProvider.P2P)
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 132, in set_stream_prodiver
    url = url.replace("{server_address}", str(self.config.rtsp_server_address))
AttributeError: 'NoneType' object has no attribute 'rtsp_server_address'
```

**Comment by fuatakgun** [comment]
I am sorry, juggling with many stuff, forgot to publish local changes to github. 
- released a new version https://github.com/fuatakgun/eufy_security/releases/tag/v5.1.1
- installed my production machine
- removed integration to be sure that there is no residue
- restarted home assistant instance
- added back successfully

**Comment by chicknlil** [comment]
I was poking around in HACS and saw 5.1.1 was available so I grabbed it, and that did the trick.  Side note: I seem to have maybe 2 to 3x more entities now from this integration.  Is that expected behavior?

**Comment by fuatakgun** [comment]
yes, it is expected

**Comment by chicknlil** [comment]
Alright.

Everything is showing as unavailable, and in looking at the 3 devices (backyard floodlight camera, doorbell camera, keyless entry), they all indicate Debug (Device) and Debug (Station) are on, but I don't see a way to turn that off.  I can live without the cameras, but the keyless entry is part of my alarmo arm/disarm setup.

**Comment by fuatakgun** [comment]
these Debug sensors are showing you the state of the device inside their attributes.

please share logs so we can understand why everythins is available.

**Comment by chicknlil** [comment]
I can tell you that the two cameras are now showing as available (I removed the integration, restarted, and readded it) but the keyless entry (T8520) is being difficult.  It doesn't even show a mechanism to lock or unlock the door currently.

Here are the 3 Eufy related logs in my logs:

```
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:520
Integration: Switch (documentation, issues)
First occurred: 6:20:33 PM (2 occurrences)
Last logged: 6:24:17 PM

Platform eufy_security does not generate unique IDs. ID eufy_security_T8422N1021151309_motionDetection already exists - ignoring switch.backyard_motion_detection
```

```
Logger: homeassistant.components.lock
Source: custom_components/eufy_security/lock.py:24
Integration: Lock (documentation, issues)
First occurred: 6:20:33 PM (2 occurrences)
Last logged: 6:24:17 PM

Error while setting up eufy_security platform for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/lock.py", line 24, in async_setup_entry
    product.properties.append(product.metadata[MessageField.LOCKED.value])
AttributeError: 'dict' object has no attribute 'append'
```

```
Logger: homeassistant.components.sensor
Source: core.py:1131
Integration: Sensor (documentation, issues)
First occurred: 6:20:33 PM (4 occurrences)
Last logged: 6:24:17 PM

Error adding entities for domain sensor with platform eufy_security
Error while setting up eufy_security platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 659, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1470, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1131, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.backyard_last_camera_picture_url. State max length is 255 characters.
```

**Comment by fuatakgun** [comment]
please retest with 5.1.2

**Comment by fuatakgun** [comment]
expecting all to be gone.

**Comment by chicknlil** [comment]
No joy.

I tried updating, still had the errors, so I removed the integration, restarted, readded, and checked the logs, and all 3 persist and appear to be identical.  Just for giggles, I restarted one more time, and checked the logs again - still the same.

**Comment by fuatakgun** [comment]
[v5.1.4](https://github.com/fuatakgun/eufy_security/releases/tag/v5.1.4) is released

**Comment by chicknlil** [comment]
Should I be pehaps removing every aspect of your integration + addon, doing the check and restart, and then trying again from fresh?

The cameras still don't display for me (though I'd have been shocked if they did!) and I did try changing the cards to the url path the latest addon provides.

I'm telling it to find my Eufy devices via "localhost" ... is this perhaps problematic? I'd tried with my router's IP, but it wouldn't connect to that.

**Comment by fuatakgun** [comment]
but these logs are saying that, you are not even getting connected to add-on.
if you are using supervised or hass OS, 127.0.0.1 should be enough.
If you are using self managed docker, you need to out its address here.

**Comment by chicknlil** [comment]
That bit of direction might have been helpful to know. 

Regardless, I just removed the integration, restarted, and readded it using 127.0.0.1 ... it set it up pretty much identically to how it was when it was localhost.  Same 3 error logs.

**Comment by fuatakgun** [comment]
would you like to share your devices with me so I can debug them?

**Comment by fuatakgun** [comment]
would you like to share your devices with me so I can debug them?

we can even have a google meet session?

**Comment by chicknlil** [comment]
It sorta fixed the lock. I was able to lock the door once from HA, but it is ignoring subsequent attempts to unlock the door (and as an added bonus, shows that the door is still unlocked).

I'm in the States, so I shared access with the gmail address listed in the repository, and just set up debugging.

Let me know if I can help any other ways.

**Comment by fuatakgun** [comment]
Can i lock and unlock?

Can i watch the stream?

**Comment by chicknlil** [comment]
Have a blast.

**Comment by chicknlil** [comment]
Hahaha, the cat of mine that's down here with me is all sorts of confused.  Usually the door locking or unlocking means I'm coming or going. But he was sitting on my lap when you were using it and he just kept looking back and forth between me and the door.

Truly, the highlight of my day so far.

**Comment by fuatakgun** [comment]
lock is working
camera streams are working (doorbell and backyard)
error is fixed.

I will publish a new version soon, do not forget to install RTSP addon and configure add-on to use it.

**Comment by fuatakgun** [comment]
please get v5.2.0

**Comment by chicknlil** [comment]
Yes, I've had the RTSP Simple Server Addon mentioned in your readme from the getgo.

Lock is definitely working again - yay!

Cameras are not streaming to the cards.

Could you advise how the cards should be set up given these recent changes?

I was using the card code from the readme:

```
type: grid
square: false
cards:
  - type: conditional
    conditions:
      - entity: binary_sensor.front_streaming_sensor
        state: 'False'
    card:
      type: picture-entity
      entity: camera.front
      tap_action:
        action: call-service
        service: camera.turn_on
        target:
          entity_id: camera.front
  - type: conditional
    conditions:
      - entity: binary_sensor.front_streaming_sensor
        state: 'True'
    card:
      type: vertical-stack
      cards:
        - type: custom:webrtc-camera
          entity: camera.front
        - type: button
          name: Stop Streaming
          show_state: false
          show_icon: false
          tap_action:
            action: call-service
            service: camera.turn_off
            target:
              entity_id: camera.front
columns: 1
```

Nothing displays in the regular view, and I get the same error I'd been getting: can't get URL for camera(in my case doorbell or backyard).

Thanks for your time and patience.

**Comment by fuatakgun** [comment]
Please use this and you are welcome. thanks for volunteering for Alpha.

```
square: false
columns: 1
type: grid
cards:
  - type: conditional
    conditions:
      - entity: camera.entrance
        state: idle
    card:
      show_state: true
      show_name: true
      type: picture-entity
      entity: camera.entrance
      camera_image: camera.entrance
      tap_action:
        action: call-service
        service: camera.turn_on
        data: {}
        target:
          entity_id: camera.entrance
  - type: conditional
    conditions:
      - entity: camera.entrance
        state: streaming
    card:
      type: vertical-stack
      cards:
        - show_name: true
          show_icon: false
          type: button
          tap_action:
            action: call-service
            service: camera.turn_off
            data: {}
            target:
              entity_id: camera.entrance
          entity: camera.entrance
          name: Stop
        - type: custom:webrtc-camera
          entity: camera.entrance
```
