### ISSUE TITLE
Alarm control panel state

### ISSUE THREAD

**Issue by Jezza1232** [fuatakgun/eufy_security#599]
**Describe the bug**
A clear and concise description of what the bug is. Alarm control panel state has completely vanished for homebase

**To Reproduce**
After update all states went offline and also doubled then it cleared the disabled ones and left only running states after reboot my home control panel has completely vanished from homebase entity

**Expected behavior**
Alarm control panel state used to show what mode it was in now it is completely vanished

**Screenshots**
![Screenshot_20221228_144716_Home Assistant](https://user-images.githubusercontent.com/97153995/209754416-f8cb2041-e05a-425b-a8a4-f3b564fa7b37.jpg)

**Hardware Information about Home Assistant

**Hardware Information about Cameras
- Camera Model 2k pan and tilt works fine just no streem not about camera just homebase alarm control panel entity missing completely my dashboard has also lost it cam panel still there and working fine

- Live Streaming Protocol: RTSP I believe 

**Additional context**

**Comment by JuhaFIN1** [comment]
Same here, it gone :(
Now there is only entity called: "select.xxxxxx_guard_mode" and its not so easy to use in Automations / Scripts.

**Comment by fuatakgun** [comment]
merged into https://github.com/fuatakgun/eufy_security/issues/599
