### ISSUE TITLE
Errors in log of addon

### ISSUE THREAD

**Issue by skank01** [fuatakgun/eufy_security#60]
I'm seeing these logs in the addon
• events.js:375 emit
    events.js:375:28
• websocket.js:970 receiverOnMessage
    node_modules/ws/lib/websocket.js:970:20
• events.js:375 emit
    events.js:375:28
• receiver.js:517 dataMessage
    node_modules/ws/lib/receiver.js:517:14
• receiver.js:435 getData
    node_modules/ws/lib/receiver.js:435:17
• receiver.js:143 startLoop
    node_modules/ws/lib/receiver.js:143:22
2021-09-20 09:43:40.963  ERROR Message error 
 LivestreamAlreadyRunningError  Livestream for device T8210P00202830FE is already running
details:
{
  name: 'LivestreamAlreadyRunningError'
}
error stack:
• message_handler.ts:116 handle
    src/lib/device/message_handler.ts:116:31
• server.ts:46 device
    src/lib/server.ts:46:34
• server.ts:98 receiveMessage
    src/lib/server.ts:98:58
• server.ts:57 <anonymous>
    src/lib/server.ts:57:53
• events.js:375 emit
    events.js:375:28
• websocket.js:970 receiverOnMessage
    node_modules/ws/lib/websocket.js:970:20
• events.js:375 emit
    events.js:375:28
• receiver.js:517 dataMessage
    node_modules/ws/lib/receiver.js:517:14
• receiver.js:435 getData
    node_modules/ws/lib/receiver.js:435:17
• receiver.js:143 startLoop
    node_modules/ws/lib/receiver.js:143:22
2021-09-20 09:43:58.565  ERROR Message error 
 LivestreamAlreadyRunningError  Livestream for device T8210P00202830FE is already running
details:
{
  name: 'LivestreamAlreadyRunningError'
}
error stack:
• message_handler.ts:116 handle
    src/lib/device/message_handler.ts:116:31
• server.ts:46 device
    src/lib/server.ts:46:34
• server.ts:98 receiveMessage
    src/lib/server.ts:98:58
• server.ts:57 <anonymous>
    src/lib/server.ts:57:53
• events.js:375 emit
    events.js:375:28
• websocket.js:970 receiverOnMessage
    node_modules/ws/lib/websocket.js:970:20
• events.js:375 emit
    events.js:375:28
• receiver.js:517 dataMessage
    node_modules/ws/lib/receiver.js:517:14
• receiver.js:435 getData
    node_modules/ws/lib/receiver.js:435:17
• receiver.js:143 startLoop
    node_modules/ws/lib/receiver.js:143:22

**Comment by skank01** [comment]
Also in HA log, much errors
![fout](https://user-images.githubusercontent.com/53368406/134128197-5e3875b6-baa3-41aa-a632-043cf27082f6.JPG)

**Comment by fuatakgun** [comment]
Please receive how you ended up here?

is problem sticky after restarting home assistant?

**Comment by skank01** [comment]
Yes even after restart, i get loads of errors when trying to play the camera

**Comment by fuatakgun** [comment]
Go ahead and share your camera throughout day, i will debug tonight

**Comment by skank01** [comment]
i did

**Comment by fuatakgun** [comment]
you want to delete the camera? or sharing with me?

**Comment by skank01** [comment]
The sharing :)
I hope you understand i dont like the idea people can look through my cams

**Comment by fuatakgun** [comment]
no, I do not understand, it was clear from beginning that I have to look through your cams.
if you are not comfortable with this, you should not share it from beginning.

**Comment by fuatakgun** [comment]
same reason you did, you should understand that I do not like the idea of solving other people's problem while they are not comfortable on this. I do not have time/energy for this.

**Comment by skank01** [comment]
Yeah i closed it cause you closed it.
I was just asking you..
Yeah i dont like the idea of being the camera open for a long time ..
theres no other way in troubleshooting that?

Op di 21 sep. 2021 om 17:03 schreef fuatakgun ***@***.***>:

**Comment by fuatakgun** [comment]
i do not have any intention/interest/time to fix your issue.

**Comment by skank01** [comment]
Ok nice to know
Anyhow, sometimes it works again but i see loads of errors in ha log
But nevermind it.
Will wait and see for future versions and elaborate where possible

**Comment by liudger** [comment]
I had the same error. restart the add-on and increase this value a bit. 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/4112111/139691842-3579183b-0d35-4fef-9d25-37b408e5e4df.png">

**Comment by skank01** [comment]
Thx will try,
you should turn off auto start stream on click though
