### ISSUE TITLE
Retrying setup: Exception: Host/port is not reachable localhost 3000!

### ISSUE THREAD

**Issue by tcarroll177** [fuatakgun/eufy_security#602]
I have been having this issue for about 3 weeks now. I cannot access live streaming of my camera's anymore. Running version 1.3 and have tried uninstalling/re-installing. Any suggestions on how it can be fixed?

<img width="645" alt="Screen Shot 2022-12-28 at 8 59 05 AM" src="https://user-images.githubusercontent.com/97417397/209823628-d40ca201-f8b1-4680-abb3-0b27dc66d2aa.png">
<img width="258" alt="Screen Shot 2022-12-28 at 8 59 16 AM" src="https://user-images.githubusercontent.com/97417397/209823635-7c11d601-55ca-4481-8b64-9a0dc99630a3.png">

**Comment by fuatakgun** [comment]
Please use alpha version of integration and read its readme.

**Comment by tcarroll177** [comment]
Hi Thank you for putting together this integration. 

Could you please let mw know what the alpha version is? I am struggling to get this working again.

Thanks


Tom
