### ISSUE TITLE
Eufy Security not listed , Setup Step 6.3 

### ISSUE THREAD

**Issue by Liese2007** [fuatakgun/eufy_security#607]
**Describe the bug**
I followed setup guide 6.1 and 6.2.
Both add-ons are up and running.
Logs are ok 
I restarted HA and all add ons and system is updated.

Under 6.3 I expect to check integrations via HACS, but no "Eufy Security" integration is available.
I can add again a repository GitHub link, but acc step 6.3 the integration should be available here ...? 

If I go to 'Integrations' via 'Configuration', there is only an 'Eufy' integration available, which requires setup via configuration.yaml.
But as well no "Eufy Security" integration.

**Hardware Information
HassOS on a Raspberry pi 3B+

**Hardware Information about Cameras
- Camera Model T8210, wired
- Home Base 2,
- Live Streaming add ons installed: RTSP

**Additional context**
None

**Comment by fuatakgun** [comment]
I cannot help on this, it is available on my fresh install.

![image](https://user-images.githubusercontent.com/11085566/210007807-b65ec482-e294-4d6c-a017-6ef39f5f773f.png)
