### ISSUE TITLE
Detect Motion without having push notifications enabled

### ISSUE THREAD

**Issue by RienduPre** [fuatakgun/eufy_security#614]
I want to use the motion sensor in HA as real motion sensor for room occupancy .
The problem is that the Eufy motion sensor need push notification enabled in the security settings to get the motion detected in HA. This is anoying because I receive every motion on my phone.
Is it possible to get the HA motion sensor entity to detect movement without push notification enabled?

In the events(in the app) I can see a motion detected event when the notification are disabled.

Thanks in advance.

**Comment by fuatakgun** [comment]
No, not possible

**Comment by RienduPre** [comment]
HI,

Sorry to ask more details, because the Eufy security client/app is showing motion detection while notification are off (see screenshot (in Dutch)


In which part is the limitation?
- Websocket
- Client
- Custom component/integration

Thanks,
rien

**Comment by fuatakgun** [comment]
Integration just relies on push notifications, so there is no other data source.

You can read the source code of integration and web socket.

**Comment by KillaDreams** [comment]
#638
