### ISSUE TITLE
Trouble getting a working stream

### ISSUE THREAD

**Issue by cryd-s** [fuatakgun/eufy_security#617]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Cannot get a working stream did everything how discribed in the readme

**Expected behavior**
working stream

**Screenshots**
see additional info

**Hardware Information about Home Assistant
Server with HASS OS

**Hardware Information about Cameras
- Camera Model: 
![image](https://user-images.githubusercontent.com/47699362/210163301-c945fd3f-1c27-4681-9dbf-af8519402ae5.png)

- Live Streaming Protocol: RTSP or P2p:  tested both

**Additional context**
![image](https://user-images.githubusercontent.com/47699362/210163269-d95eaf0f-5380-4e41-9bc5-0788713ef3a5.png)
![image](https://user-images.githubusercontent.com/47699362/210163272-6eeb0668-9d5c-45ee-bab7-47b04b5f7b44.png)

**Comment by fuatakgun** [comment]
Please enable debug logs following readme and share them over here or email (fuatakgun@gmail.com)

**Comment by cryd-s** [comment]
cannot get the logs can u help me via discord? Want to publish your addon on my youtube channel if its working.

**Comment by fuatakgun** [comment]
you will find the instruction here: https://github.com/fuatakgun/eufy_security/discussions/624

**Comment by cryd-s** [comment]
`2023-01-04 20:32:22.090  INFO  Connected to station T8010P23221412CD on host 192.168.178.88 and port 27771 
2023-01-04 20:32:56.256  ERROR Message error 
 LivestreamNotRunningError  Livestream for device T8213P1122161282 could not be stopped, because it is not running
error stack:
• message_handler.ts:240 handle
    src/lib/device/message_handler.ts:240:31
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• server.ts:125 receiveMessage
    src/lib/server.ts:125:21`

**Comment by rpartapsing** [comment]
I have the same issue.

Moreover I see some additional logging info:
```
2023-01-04 16:56:16.445  INFO  Stopping the station stream for the device T8210P332118262D, because we haven't received any data for 5000 seconds 
2023-01-04 18:48:27.866  WARN Station T8010N2321260839 - AES key could not be decrypted! The entire stream is discarded. - Error: 
 Error  Error during decryption (probably incorrect key). Original error: Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error
```

**Comment by fuatakgun** [comment]
> However This does not work for the Eufycam 2C Pro cameras which I have outside and the videodoorbel 2k.

They are not supposed to work with RTSP, they are supposed to stream through P2P via RTSP Add-on.

**Comment by cryd-s** [comment]
ok i dont understand what i have to do...

My addons are configured like that:

![image](https://user-images.githubusercontent.com/47699362/210879371-9feed263-3cc7-42e3-bd54-9222c6e34969.png)
![image](https://user-images.githubusercontent.com/47699362/210879431-9b6c85bc-f201-49a4-94a8-22624c130fa2.png)
![image](https://user-images.githubusercontent.com/47699362/210879562-d0843201-6e42-4452-96ac-1aaca0bf1e35.png)

**Comment by fuatakgun** [comment]
Start with upgrading integration :-)

**Comment by cryd-s** [comment]
oh my fault - i have updated the integration but now it lists only a sensor which is inaktiv

![image](https://user-images.githubusercontent.com/47699362/210887458-6af9eb42-41ed-4ca2-9a7c-0ba2d92eeff3.png)

**Comment by fuatakgun** [comment]
Please go through readme, check how this is supposed to work and create a new issue if you face another one.
