### ISSUE TITLE
Add Programmed mode

### ISSUE THREAD

**Issue by MonsieurPoutounours** [fuatakgun/eufy_security#620]
Hi,

My normal (presence) mode is programmed mode, because it helps me in case i forget to arm cameras at night. 

The integration is not compatible with Programmed mode, yet this could be a useful feature. 

Regards.

**Comment by fuatakgun** [comment]
What does programmed mean? Tell me more, probably with a page link describing the feature

**Comment by fuatakgun** [comment]
There is already a service called schedule, it will switch to that mode. Please go through readme or examine existing services.
