### ISSUE TITLE
Lock/Unlock no longer pushes notification to HA showing who's fingerprints unlocked the door 

### ISSUE THREAD

**Issue by jkameldo** [fuatakgun/eufy_security#625]
Thank you Fuatakgun, Happy New Years!

Device info
T8510

Logbook shows door lock and unlock status, but no longer who unlocked it. 
<img width="1145" alt="Screenshot 2023-01-01 at 11 25 34 AM" src="https://user-images.githubusercontent.com/119099380/210182450-676270e1-eab1-4b35-af6a-d21e3f5b70c3.png">

Thank you for your time!!!!!

**Comment by fuatakgun** [comment]
Do you mean, this was working in 2.x version but not working in 5.x versions?

Happy new year to you too

**Comment by jkameldo** [comment]
hmmm, it looks like im on  v2.10, possible it was working on an earlier version of 2.x?

> Do you mean, this was working in 2.x version but not working in 5.x versions?
> 
> Happy new year to you too

**Comment by jkameldo** [comment]
hmmm, it looks like im on  v2.10, possible it was working on an earlier version of 2.x?

**Comment by fuatakgun** [comment]
I would say, move into v5.x version and see.

**Comment by jkameldo** [comment]
thank you for the suggestion! I moved into v5.x. Here is the new device information, there appears to be more entities, however still no notifications on who unlocked the door
<img width="1114" alt="Screenshot 2023-01-01 at 11 48 57 AM" src="https://user-images.githubusercontent.com/119099380/210183059-29fd0aac-4cee-4b22-a1a9-b2de9d4bc72c.png">

**Comment by fuatakgun** [comment]
Are you locking and unlocking these via home assistant or eufy app or physically?

**Comment by jkameldo** [comment]
physically

**Comment by fuatakgun** [comment]
There was no such functionality since beginning of time :-)

**Comment by jkameldo** [comment]
omg loooool!!!! I could have sworn I noticed fingerprint notification in the log book XD I am hoping we can add this to the wishlist then, thank you again!

**Comment by fuatakgun** [comment]
I remember this was asked to bropat over his repository and he mentioned that this is not possible, don't have too much context
