### ISSUE TITLE
Only interested in controlling the base

### ISSUE THREAD

**Issue by agilob** [fuatakgun/eufy_security#629]
Hi, I'm only interested in controlling state of the base Armed/Unarmed statues, don't need streaming and notifications and I'm running hass in docker, where add-ons are not available. Is there a way for me to configure this repo? I can't install the addon, and I dont want streaming so I have no IP to provide in the first step of the configuration.

**Comment by fuatakgun** [comment]
you need integration and eufy security add on.

**Comment by agilob** [comment]
But security addon cannot be installed on containarised hass, therefore it's not possible?

**Comment by fuatakgun** [comment]
You can run as a docker instance, check README file to get examples.
