### ISSUE TITLE
Setup failed for custom integration eufy_security: Requirements for eufy_security not found: ['aiortsp==1.3.6'].

### ISSUE THREAD

**Issue by ahaverty** [fuatakgun/eufy_security#630]
**Describe the bug**
The integration is stuck on "Not loaded" with an error in the logs:
`Setup failed for custom integration eufy_security: Requirements for eufy_security not found: ['aiortsp==1.3.6'].`

**To Reproduce**
I followed the alpha install instructions [here](https://github.com/fuatakgun/eufy_security/issues/610), and have tried both restarting HA, and the HA server (HA blue)

**Hardware Information about Home Assistant**
HA Blue
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

**Comment by fuatakgun** [comment]
it is home assistant's responsibility to install the dependencies, you can try to install this manually but i don't know why this might happen and what might be the resolution.

**Comment by fuatakgun** [comment]
Example issue: https://github.com/home-assistant/core/issues/74700
