### ISSUE TITLE
Eufy quick response not working

### ISSUE THREAD

**Issue by julet85** [fuatakgun/eufy_security#631]
I have a Eufy doorbell wired (T8200).

Does anyone know if this works with device.quick_response commands?

I tried the following script as well as manually running the command in developer console without success.

`alias: Doorbell Response 3
sequence:
  - service: eufy_security.send_message
    data:
      message: |-
        {
          "messageId": "message_id_do_not_add_value_here", 
          "command": "device.quick_response",
          "serialNumber": "your_serial_no",
          "voiceId": 3,
          "value": true
        }
mode: single `

**Comment by fuatakgun** [comment]
instead of using send_message, there is a specific service called quick_response, give it a try, it was tested earlier

**Comment by julet85** [comment]
Thanks @fuatakgun - it is now working.
