### ISSUE TITLE
Eufy Security Add-on - ERROR Response data is missing 

### ISSUE THREAD

**Issue by MrKuenning** [fuatakgun/eufy_security#635]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Starting Yesterday, the addon doesn't login correctly it just throws an error:
```
2023-01-03 17:17:22.602  ERROR Response data is missing 
{
  code: 0,
  msg: 'Succeed.',
  data: undefined
}
```

**To Reproduce**
1. Install Eufy Security Add-on
2. Enter your Email and Password and hit start
3. Check Logs
4. See the error

**Expected behavior**
I expected the logs to say established connection.

**Hardware Information about Home Assistant
HASS is running in an ESXi VM on a Xeon Processor

**Additional context**
The Add-On failing to start is also causing the integration to fail to initialize.

**Comment by fuatakgun** [comment]
Please put on trusted device name

**Comment by Aspyryan** [comment]
Where can I put on the trusted device name?

**Comment by MrKuenning** [comment]
![2023-01-11 13_13_50-Home Assistant](https://user-images.githubusercontent.com/16549268/211929333-7f5529db-e8ea-49ac-b5e7-2f87c24867c2.jpg)
