### ISSUE TITLE
eufy security integration missing

### ISSUE THREAD

**Issue by vegaBot87** [fuatakgun/eufy_security#637]
**Issue**
eufy security integration not showing in HA 'Set up a new integration' (step 6.3.5)

**Reproduce**
1. Ran Docker container bropat/eufy-security-ws
2. Added Eufy Security repo in HACS
3. Restarted HA
4. Selected 'Add Integration' from Devices and Services
5. Integration not shown

**Expected behavior**
eufy security integration to show in 'Set up a new integration' (step 6.3.5)

**Screenshot**
![Capture](https://user-images.githubusercontent.com/42785490/210423228-78434915-e298-47b2-bee2-8df3ac8e0340.PNG)

**Setup**
Docker Home Assistant 2022.8.7

**Additional context**
Eufy Security v5.3.3 also tried other v5.3.X, and non-alpha v2.10.0. This was working couple days ago before changing to alpha v5.3.3 so this is the only change. Also cleared cache in browser with no success.

**Comment by fuatakgun** [comment]
Sorry, there is nothing i can do, please check yours, either a missing dependency issue or cache (you already mentioned this)

**Comment by vegaBot87** [comment]
> Sorry, there is nothing i can do, please check yours, either a missing dependency issue or cache (you already mentioned this)

Ok, will continue to tinker around. Thanks for the prompt reply
