### ISSUE TITLE
Motion sensors not updating in Home assistant

### ISSUE THREAD

**Issue by MathewJH1** [fuatakgun/eufy_security#638]
Noticed recently motion sensors not triggering automations, found when inside EUFY security app if notifications for motion sensor are turned off then home assistant state is not updated 

1. Open Eufy secruity application 
2. click on "security" adjust "XX mode" disable motion sensors notification > save 
3. attempt to trigger automation with notifications turned off
4. when notifications inside of eufy security app are turned off > HA does not change motion sensor state

**Comment by fuatakgun** [comment]
yes, you have to go through README

**Comment by MathewJH1** [comment]
> 

Sorry what did I miss in the Readme section?

**Comment by fuatakgun** [comment]
Old README:
```
**Create a separate account for HA integration as that account will be logged out automatically from mobile app when HA integration logged in. Do not forget to share your cameras with your new account (preferably with adming rights), enable motion notifications with full picture and enable push notifications. This integration depends on push notifications to catch any updates.**
```

New README:
```
**As we already called out earlier, add-on heavily relies on push notifications, so you must enable all kind of push notifications (motion detected, person detected, lock events, alarm events etc) in your mobile app. These notifications are not user based but device based so after enabling all these notifications, your main account will probably bloated with many push notifications. In android, there is a setting to disable specific notifications, please use it. **
```

**Comment by MathewJH1** [comment]
Any future plans to change Push notifications for the HA trigger?

**Comment by fuatakgun** [comment]
there is no option to get the states from sensors without enabling push notifications. do you have any idea in your mind?

**Comment by MathewJH1** [comment]
No not at all, Sorry new just very curious!

**Comment by fuatakgun** [comment]
Or let me put in a different way, there are 2 ways of getting data;
- you can pull it from somewhere regularly. this is very consuming because you have to check it regularly and gets very demanding if you are looking for motion sensor. you have to pull every second maybe? 
- something can push it to you when it has changed. when a notification arrives to add-on, we can react on it and this is very light weight to achive.

**Comment by MathewJH1** [comment]
I guess pulling it from home base directly in out of the question ? 
as it seems to monitor state changes

**Comment by KillaDreams** [comment]
I know for android you can go in and change the notifications on your phone so you don't get spammed for motion alerts on your phone ![Screenshot_20230114_083118_Settings.jpg](https://user-images.githubusercontent.com/53876155/212477072-83824c74-25e4-418f-b7a8-dbb618417969.jpg)
