### ISSUE TITLE
Wrong state reporting binary_sensors

### ISSUE THREAD

**Issue by GNutma** [fuatakgun/eufy_security#639]
**Describe the bug**
The motion sensors and ringing sensors of a device are not reporting the correct states for Home Assistant.

**To Reproduce**
1. Add a device with a binary_sensor.

**Expected behavior**
The binary sensor gives a state conforming to the Home Assistant supported states ( for example y, n, yes, no, on, off, true, false) 

Instead it gives the states True and False. This should, for my understanding, be true and false (lowercase).

**Comment by fuatakgun** [comment]
if you are on v2.x.x version, enable the option in integration configuration
this is default behavior with v5.x.x
