### ISSUE TITLE
Automation based on motion detection Broken

### ISSUE THREAD

**Issue by LucaBors** [fuatakgun/eufy_security#641]
Hi,
this morning i update @ 6.0.0 version. Since then "global motion sensor" entity disappear and, binary_sensor.*****_motion_detected does not get triggered by a motion.

Thank you.

**Comment by therealhalifax** [comment]
I have the same issue, just realized it now :-(

**Comment by lavoy** [comment]
My motion sensors are also not reporting as changed within HA, even though I'm getting notifications directly from the Eufy Security App.

**Comment by lavoy** [comment]
I’m running bropats 1.3.5 and camera motion detection never fires.

**Comment by KillaDreams** [comment]
I don't believe camera motion would trigger anything as it would just be an
event, not the same as a motion sensor, should have specified camera motion
specifically in your first post. My motion sensor automation never broke,
it was just the entry sensor status that was broken for months

**Comment by lavoy** [comment]
Okay, sorry for the noob question, but how would I listen to that event without looking at the state changing?
