### ISSUE TITLE
The `sensor.<name>_last_camera_picture_url` is not working

### ISSUE THREAD

**Issue by ahaverty** [fuatakgun/eufy_security#643]
**Describe the bug**

The `sensor.<name>_last_camera_picture_url` worked for me for a few hours, but has since stopped.
I've tried starting the stream again a few times which works as expected, but it doesn't fix this image.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/2920947/210527098-6f153d54-2750-4d56-bd84-280378c25eae.png">

I can see there's a file path still set, which doesn't seem to ever change (perhaps intentional?)
<img width="547" alt="image" src="https://user-images.githubusercontent.com/2920947/210527531-0f495203-98e0-4b88-99c8-0ea166ea3b72.png">

The path/filename is from a couple of days ago. Perhaps it only wrote the first image once, and hasn't since?
I've since updated eufy via hacs + HA version, and have had multiple reboots, which doesn't seem to fix, even after playing the P2P stream.

**Additional information**

- Eufy: v6.0.0
- Home Assistant Installation Type (OS - Supvervised - Core): Supvervised
- Home Assistant Core Version: 
```Home Assistant 2022.12.9
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest```

Hardware Information;
- Camera Model: t8200


- Live Streaming Protocol (RTSP/P2P): P2P


- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
```Logger: haffmpeg.core
Source: custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py:116
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 09:49:25 (2 occurrences)
Last logged: 09:49:25

Timeout while waiting of FFmpeg
FFmpeg isn't running!```

**Comment by fuatakgun** [comment]
Integration doesn't use last_image_url any more, it us generating the thumbnails if streaming is active.

Thumbnails are encrypted as of now.

**Comment by fuatakgun** [comment]
This sensor (sensor.entrance_last_camera_picture_url) is updated by eufy-security-ws, when a push notification arrives but we are not able to decrypt it as of now.

The only way to generate thumbnails is to start streaming for couple of seconds.

**Comment by fuatakgun** [comment]
Comment back later on if happen again

**Comment by copekyle** [comment]
I'm interested to know how this is going for you. I'm dealing with a similar issue. When I stop my camera, I get a still image for around 5 seconds. Then it goes to a broken link picture. I'm not sure what the difference is between my setup and yours.
