### ISSUE TITLE
Service to reboot a camera

### ISSUE THREAD

**Issue by Cheerpipe** [fuatakgun/eufy_security#646]
**Is your feature request related to a problem? Please describe.**
In v2.10 i was able to reboot my cameras (Indoor 360) using send_message service with this :

service: eufy_security.send_message
data:
  message: |-
    {
      "messageId": "HA reboot", 
      "command": "station.reboot",
      "serialNumber": "MYSERIALNUMBER"
    }

This approach is not working in 6.0. I don't know if this is a bug or a change in send_message  service. No info in logs.

**Describe the solution you'd like**
Would be nice to have a service to reboot cameras.

**Describe alternatives you've considered**
As an alternativa, a working send_message with station. Reboot payload.

**Additional context**
I have an HA automation to restart my cameras every 6 hours. I do this to avoid RTSP image degradation after some hours of use. This is a known bug in eufy RTSP streams from eufy Cameras.

In the meantime, i just downgraded my integration to v2.10 because send_message works well with station.reboot.

Thanks in advance

**Comment by fuatakgun** [comment]
I will create a service for this, have you tried rtsp stream switch to make this work?

**Comment by Cheerpipe** [comment]
> I will create a service for this, have you tried rtsp stream switch to make this work?

Thanks for your incredible fast response.

Yes. I tried stop/start rtsp and enable/disable camera but this actions doesn't fix the stream, only a full reboot.

**Comment by fuatakgun** [comment]
In the meantime, use this (message needs to be in one line, somewhere I break it, needs to fix

```
message: {"messageId": "HA reboot", "command": "station.reboot","serialNumber": "MYSERIALNUMBER"}
```

**Comment by Cheerpipe** [comment]
> In the meantime, use this (message needs to be in one line, somewhere I break it, needs to fix
> 
> ```
> message: {"messageId": "HA reboot", "command": "station.reboot","serialNumber": "MYSERIALNUMBER"}
> ```

Thanks. Will test ASAP

**Comment by fuatakgun** [comment]
added new reboot service, will be released in next version, or you can get latest from master

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/commit/edd3555eab43e13a52113699eda631bdfd0377c4
