### ISSUE TITLE
FFMPEG isn't running + only receiving images + green screen on webrtc

### ISSUE THREAD

**Issue by ahaverty** [fuatakgun/eufy_security#649]
**Describe the bug**

Sometimes after start a stream, I get a mostly green/fuzzy webrtc view for my doorbell camera.
I can see the camera.doorbell view shows recent images, but those images seem to only update a few times every minute.
I can see in my logs, issues with FFMPEG (logs below)

**To reproduce**

1. Start stream
2. Notice issues listed above

**Expected behavior**

Starting stream works consistently and/or FFMPEG doesn't fail or restarts automatically

**Additional information**
Eufy: v6.0.0
Home Assistant Installation Type (OS - Supvervised - Core): Supvervised
Home Assistant Core Version:
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

Hardware Information;

Camera Model: T8200

Live Streaming Protocol (RTSP/P2P): P2P

- Debug Logs from Home Assistant:
```
This error originated from a custom integration.

Logger: haffmpeg.core
Source: custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py:116
Integration: Eufy Security (documentation, issues)
First occurred: 10:06:01 (19 occurrences)
Last logged: 17:12:14

Timeout while waiting of FFmpeg
FFmpeg isn't running!
```

**Additional context**

Picture entity on top, webrtc below:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/2920947/210613726-42d274f2-a433-4997-8bb9-c77f895680f5.png">

**Comment by fuatakgun** [comment]
can you update us @ahaverty ?

**Comment by DerHerzog7** [comment]
I'm getting the same issue with Eufy Cam 3s / Homebase 3, but it doesn't even seem to work after a restart. I WAS about to get RTSP working, but trying to maintain 4k recording, so prefer to use P2P streaming through Home Assistant.

**Comment by fuatakgun** [comment]
Even if you use p2p streaming, integration is not able to handle high resolution

**Comment by fuatakgun** [comment]
P2P stream should be interested in streaming quality.

Storage quality might impact rtsp streaming.

**Comment by DerHerzog7** [comment]
Yeh, low still doesn't work. I was doing some digging and it looks like even on low, the codec is still H265 rather than dropping to 265 as people have suggested on here. It doesn't look like there is a way to force the change (I'm using Homebase 3)

**Comment by DerHerzog7** [comment]
Is there any thoughts on this issue? I simply cannot get an image to show. Everything else works perfectly, I just get either the green distortion or a blank image when streaming.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/discussions/694

**Comment by DerHerzog7** [comment]
> 

Hmmm. I Can't seem to get it to play in h264, which is where the problem lies I think. Pretty much everything works, except I can't get a stream image. If I turn off RTSP SImple Server, I just get the queue increasing error and still no image.
