### ISSUE TITLE
Tried all hosts, no connection could be established

### ISSUE THREAD

**Issue by luka6000** [fuatakgun/eufy_security#650]
**Describe the bug**

Connection to the camera cannot be established

**Additional information**
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: 2022.12.9

Hardware Information;
- Camera Model: 4G Starlight Camera

- Live Streaming Protocol (RTSP/P2P): I don’t know

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
nothing there
- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

>2023-01-04 19:39:38.144  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
>2023-01-04 19:39:48.530  INFO  Push notification connection successfully established 
>2023-01-04 19:40:08.631  WARN Station T8151P3022xxxxxx - Tried all hosts, no connection could be established 
>2023-01-04 19:40:08.635  INFO  Timeout connecting to station T8151P3022xxxxxx 
>2023-01-04 19:40:24.636  WARN Station T8151P3022xxxxxx - Tried all hosts, no connection could be established 
>2023-01-04 19:40:24.638  INFO  Timeout connecting to station T8151P3022xxxxxx  
>2023-01-04 19:40:44.964  WARN Station T8151P3022xxxxxx - Tried all hosts, no connection could be established 
>2023-01-04 19:40:44.965  INFO  Timeout connecting to station T8151P3022xxxxxx 

- Would you share your device with me in case further debugging required? (Yes/No): Not this time

**Comment by fuatakgun** [comment]
I cannnot help here, please reach out to eufy-security-ws repository but owner would help you to share your devices to debug further or share your debug logs with him

**Comment by luka6000** [comment]
> I cannnot help here, please reach out to eufy-security-ws repository but owner would help you to share your devices to debug further or share your debug logs with him

well, there is one proposed solution for disconnections here
https://github.com/bropat/eufy-security-ws/issues/130#issuecomment-1229479950
But if that’s the case than it has a lot to do with add-on networking in HAos so this is issue with add-on not client library, no?

**Comment by fuatakgun** [comment]
it is rather docker and host networking rather than I can manage through add-on. It is either underlying debian (assuming using supervisor) or Home Assistant OS settings. Add-ons cannot configure this.

You can try to run it using docker with host networking and share your experience with us?
