### ISSUE TITLE
After latest update, cameras are showing as not available. The add-on in the log is saying "killed".

### ISSUE THREAD

**Issue by Paintballer19** [fuatakgun/eufy_security#651]
**Describe the bug**

After latest update, cameras are showing as not available. The add-on in the log is saying "killed".

**To reproduce**

1. Updated Integration
2. Restarted Home Assistant
3. Went to logs in the add-on
5. Additional all cameras are unavailable.

**Expected behavior**

Camera's to be available

Hardware Information;
- Camera Model: Multiple Eufy 2Ks

- Live Streaming Protocol (RTSP/P2P): RTSP

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
Killed

**Comment by fuatakgun** [comment]
#597
