### ISSUE TITLE
T8200 Doorbell "current mode" is "unknown"

### ISSUE THREAD

**Issue by sagilo** [fuatakgun/eufy_security#652]
**Description**
View the doorbell device entities, the "Doorbell" & "Current mode" are `unknown`
![image](https://user-images.githubusercontent.com/5019344/210741710-dadea250-74d4-4005-b95a-7d53f98ecc5b.png)

**Expected behavior**
The mode should be updated according to the doorbell mode.
There is no option to enable notification for mode change:
![image](https://user-images.githubusercontent.com/5019344/210742509-0f39dc69-c0f0-46d9-8520-f8e04f27307f.png)

**Additional information**
Version 6.1.0
- Home Assistant Installation Type: Docker Container
- Home Assistant Core Version: 2023.1.0

Hardware Information:
- Camera Model: T8200 Doorbell

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - will add later today

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output) - will add later today

- Would you share your device with me in case further debugging required? (Yes/No): yes

**Comment by fuatakgun** [comment]
1- as an initial starting point, having unknown is the only thing I can do because add-on is not generating the value for station. Instead of making it `unavailable`, I intentionally choose to make it `Unknown` so you can control it.
2- if there are no incoming messages from add-on to integration about mode changes, integration cannot update itself. After reading the logs, we can find out if this is an integration problem, add-on problem or device configuration problem.

**Comment by sagilo** [comment]
> 1- as an initial starting point, having unknown is the only thing I can do because add-on is not generating the value for station. Instead of making it `unavailable`, I intentionally choose to make it `Unknown` so you can control it. 2- if there are no incoming messages from add-on to integration about mode changes, integration cannot update itself. After reading the logs, we can find out if this is an integration problem, add-on problem or device configuration problem.

This has worked perfectly prior to version 6.x.x, any chance of using the old method as a fallback for such devices that dont notify about the mode change?

**Comment by fuatakgun** [comment]
Nothing changed between v2 and v6 in terms of internally handling this. I just improved it with Unknown state

**Comment by sagilo** [comment]
Oh. that's interesting, so how would you explain it worked before and after my upgrade to version 6.x.x it got broken?

**Comment by fuatakgun** [comment]
do you think this discussion is moving into a healthy place? I am trying to be helpful here. Let me know when you share your logs.

**Comment by fuatakgun** [comment]
every time you change your alarm mode, you should see this in logs of add-on. If you do not see this and if you had enabled all the notifications, there is not much I can do.

```
2023-01-05 15:59:45.385  INFO  Alarm mode for station T8010N2320460480 changed to: DISARMED 
2023-01-05 15:59:47.870  INFO  Received push notification for changing guard mode 
{
  guard_mode: 63,
  current_mode: 63,
  stationSN: 'T8010XXX'
}
2023-01-05 15:59:48.181  INFO  Alarm mode for station T8010N2320460480 changed to: HOME 
2023-01-05 15:59:50.802  INFO  Received push notification for changing guard mode 
{
  guard_mode: 1,
  current_mode: 1,
  stationSN: 'T8010XXX'
}
```

**Comment by sagilo** [comment]
Im still working on getting the logs, but I've found the selector is changing correctly when the mode is changed:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/5019344/210839551-5f430ab2-487c-42a6-8db9-e90a63de17c6.png">

So whenever I change the mode via the app or via the add-on, the selector is updated to the correct value
However, the values of `alarm_control_panel.doorbell` & `sensor.doorbell_current_mode` are still `unknown`.
I guess the value from the selector needs to be pushed to the `alarm_control_panel.doorbell` and maybe remove the `sensor.doorbell_current_mode` ?

**Comment by fuatakgun** [comment]
Current mode is different than guard mode. If current mode is not changed, it is a problem. 

Guard mode could be geofencing, current mode could be disarmed or home or away based on geofencing rules. They are connected but not equal.

**Comment by fuatakgun** [comment]
Alarm control panel and current mode sensors are supposed to be showing same thing

**Comment by sagilo** [comment]
The integration is installed via HACS, here are the logs I can see for `guard mode`:
```
homeassistant         | 2023-01-07 22:52:22.623 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'guard mode changed', 'serialNumber': 'T8200N0021051318', 'guardMode': 0}}
homeassistant         | 2023-01-08 08:02:22.780 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'guard mode changed', 'serialNumber': 'T8200N0021051318', 'guardMode': 1}}
```

**Comment by fuatakgun** [comment]
Guard mode is working well for you, what about logs for current mode?

**Comment by sagilo** [comment]
> Guard mode is working well for you, what about logs for current mode?
> 
> Alarm control panel is reacting on current mode, not guard mode

I can't see any mention of `current mode` in the logs. 
I also don't see any mention of "push notification" as you shared above, does it mean I'm looking in the wrong place?
