### ISSUE TITLE
T8210 Battery Doorbell - Battery Status Incorrect

### ISSUE THREAD

**Issue by BadgerLoaf** [fuatakgun/eufy_security#653]
**Describe the bug**

The battery level of my T8210 battery doorbell is not being updated, and appears to remain static. It does not reflect the battery level shown within Eufy phone app. Current the HA battery sensor states 98% for the doorbell, but the phone app states 90%.

I had previously raised this in bropat's eufy-security-ws page (here: https://github.com/bropat/eufy-security-ws/issues/154 ), but not sure if I should have raised it here, as that hasn't yet been picked up.

Have tested it with v6.1.0 and the issue still remains.

**To reproduce**

View state of `sensor.doorbell_battery_percentage`, this shows a different value to that showing in the Eufy phone app. This value doesn't appear to change, or at least changes very infrequently.

**Expected behavior**

`sensor.doorbell_battery_percentage` should have the same value as the battery percentage in the Eufy app. 

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS
- Home Assistant Core Version: core-2022.12.9

Hardware Information;
- Camera Model: T8210 Doorbell

- Live Streaming Protocol (RTSP/P2P): N/A

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624): Can provide if required

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output): Can provide if required

- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Comment by fuatakgun** [comment]
logs are not needed, you just need to reach out to @bropat using eufy-security-ws repository. This has been raised couple of times earlier bropat had solved it for some devices.

https://github.com/bropat/eufy-security-client/issues/183
https://github.com/bropat/eufy-security-ws/issues/154

**Comment by BadgerLoaf** [comment]
Ok thanks @fuatakgun, that's good to confirm its connected to the eufy-security-ws repository rather than this one.

Thanks for all your work on this, its very much appreciated!

**Comment by BadgerLoaf** [comment]
@fuatakgun - Quick question....

Am I correct that the your Add-On is using eufy-security-ws v1.3.0; whereas @bropat's repository is at eufy-security-ws v2.4.0.

If I am correct, I'm now thinking this is why I'm still seeing issues after he thought they were fixed, as we are running an old version of eufy-security-ws?

Apologies if I have misunderstood something

**Comment by fuatakgun** [comment]
https://github.com/bropat/eufy-security-client - 2.4.0
https://github.com/bropat/eufy-security-ws - 1.3.0 - this is consuming
eufy-security-client
add-on is matching with eufy-security-ws
