### ISSUE TITLE
Failed to load P2P Stream within WebRTC - T8131

### ISSUE THREAD

**Issue by chris173972** [fuatakgun/eufy_security#654]
**Describe the bug**

Stream failing to stream to a WebRTC Card upon upgrading to 1.3.0 of the plugin. Camera T8131.
Same config works perfectly fine with my other camera (T8400)

**To reproduce**

WebRTC Config:
type: custom:webrtc-camera
entity: camera.custom_camera_name

Clicking on new button: custom_camera_name Camera Start P2P Stream

**Expected behavior**

Plays the stream within the WebRTC Card

**Hardware Information**
- Camera Model: T8131
- Live Streaming Protocol (RTSP/P2P): P2P

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
2023/01/05 18:31:39 Connected to station A1234B1234567CD on host 192.1.69 and port 22519 

- Logs from RTSP Simple Server:
2023/01/05 18:31:39 I [-4/0] [RTSP] [conn 127.0.0.1:55938] opened
2023/01/05 18:31:39 I [-4/0] [path A1234B1234567CD] created
2023/01/05 18:31:39 I [-4/0] [path A1234B1234567CD] runOnDemand command started
2023/01/05 18:31:44 I [-4/0] [RTSP] [conn 127.0.0.1:55952] opened
2023/01/05 18:31:44 I [-4/0] [RTSP] [session 596049902] opened by 127.0.0.1:55952
2023/01/05 18:31:44 I [-3/0] [RTSP] [session 596049902] is publishing to path 'A1234B1234567CD', 1 track with TCP
2023/01/05 18:31:44 I [-3/0] [RTSP] [session 434238220] opened by 127.0.0.1:55938
2023/01/05 18:31:44 I [-3/1] [RTSP] [session 434238220] is reading from path 'A1234B1234567CD', 1 track with TCP
2023/01/05 18:31:44 I [-3/1] [RTSP] [conn 127.0.0.1:55938] closed
2023/01/05 18:31:44 I [-3/0] [RTSP] [session 434238220] closed

**Additional context**

Camera feed worked once out of 50 attempts and closed within seconds of playing. Worked perfectly fine on previous version of plugin,

**Comment by chris173972** [comment]
Other hardware: Raspberry Pi 4

**Comment by chris173972** [comment]
The card is now showing: 
ERROR: read tcp 127.0.0.1:55938-> 127.0.0.1:9000: i/o timeout

**Comment by fuatakgun** [comment]
I had the same issue with webrtc 3.0 but it is working with vlc or home assistant native streaming or webrtc 2.x versions. So, i suggest to check with webrtc owner, nothing i can help.

**Comment by chris173972** [comment]
I am currently using WebRTC 2.3.1. Does not play with stream provided by T8131.
It does on the other hand work from streams from both models: T8210, T8400.
