### ISSUE TITLE
Floodlight (T8422) missing person detected and motion detected entities

### ISSUE THREAD

**Issue by Mabashi8** [fuatakgun/eufy_security#655]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

The Eufy Floodlight (T8422) is missing the person detected and motion detected entities that all of my other cameras have.

**Expected behavior**

All of the other camera devices have a person detected entity and motion detected entity listed in the sensors section.

**Additional information**

- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: 2013.1.0
- Eufy Security Version: 6.1.0

Hardware Information;
- Camera Model: T8422

- Live Streaming Protocol (RTSP/P2P): P2P

**Additional context**

![Screenshot 2023-01-05 3 06 53 PM](https://user-images.githubusercontent.com/94807272/210870699-a2f112bc-94be-42f8-a48f-79947e705539.png)

**Comment by fuatakgun** [comment]
Please share device debug sensor attributes

**Comment by Mabashi8** [comment]
Here it is, thanks for your help!!!

name: Floodlight
model: T8422
serialNumber: T8422...
hardwareVersion: P1
softwareVersion: 2.0.7.1
type: 37
stationSerialNumber: T8422...
enabled: true
autoNightvision: true
statusLed: true
motionDetection: true
motionDetectionType: 1
motionDetectionSensitivity: 3
motionDetected: false
personDetected: false
personName: ''
watermark: 0
pictureUrl: ....jpg
light: false
microphone: true
speaker: true
speakerVolume: 80
audioRecording: true
recordingEndClipMotionStops: false
recordingClipLength: 60
recordingRetriggerInterval: 0
videoStreamingQuality: 0
videoRecordingQuality: 3
lightSettingsEnable: true
lightSettingsBrightnessManual: 100
lightSettingsBrightnessMotion: 100
lightSettingsBrightnessSchedule: 49
lightSettingsMotionTriggered: true
lightSettingsMotionTriggeredTimer: 60
notificationType: 3
snoozeTime: 0
snoozeStartTime: 0
Commands
start_livestream, stop_livestream, start_download, cancel_download, start_talkback, stop_talkback, snooze
Voices
'8870':
voice_id: 8870
user_id: ...
desc: Hey, what are you doing there?
device_sn: ''
voice_link: >-
key_prefix: /voice/2019/06/24/mobile/.../HeyWhatAreYouDoingThere_EN.aac

**Comment by fuatakgun** [comment]
Enable debug logging, restart HA, and share the logs

**Comment by Mabashi8** [comment]
[3a26b21d_eufy_security_addon_2023-01-05T21-59-14.262Z.log](https://github.com/fuatakgun/eufy_security/files/10355924/3a26b21d_eufy_security_addon_2023-01-05T21-59-14.262Z.log)


Is this what you are looking for?

**Comment by fuatakgun** [comment]
All these connections and disconnections are not normal and i do not know why it is having issues to connect your camera/station.

There are some users mentioning about network issues but nothing i control.

**Comment by Mabashi8** [comment]
The floodlight seems to be connected and i am able to stream video from it. I'm just not able to get the motion and person sensors on just the floodlight. All of my other cameras are working fine with my automations.

**Comment by fuatakgun** [comment]
please use the bug template and follow the instructions
