### ISSUE TITLE
T8213 - Dual Camera Doorbell: Live Stream not working

### ISSUE THREAD

**Issue by superpower10** [fuatakgun/eufy_security#656]
Can‘t get the live video stream to work in Home Assistant.

Tried the rtsp:/ip_of_homebase:8554/T8213SerialOfDoorbell

I even tried to reduce the video quality in the Eufy App.

Always the same Log-Entries:
2023/01/05 19:04:07 I [-3/0] [RTSP] [conn 172.30.32.1:34450] opened
2023/01/05 19:04:07 I [-3/0] [path T8213SerialOfDoorbell] created
2023/01/05 19:04:07 I [-3/0] [path T8213SerialOfDoorbell] runOnDemand command started
2023/01/05 19:04:17 I [-3/0] [path T8213SerialOfDoorbell] runOnDemand command stopped
2023/01/05 19:04:17 I [-3/0] [path T8213SerialOfDoorbell] destroyed
2023/01/05 19:04:17 I [-3/0] [RTSP] [conn 172.30.32.1:34450] ERR: source of path 'T8213SerialOfDoorbell' has timed out
2023/01/05 19:04:17 I [-3/0] [RTSP] [conn 172.30.32.1:34450] closed

Eufy-Security-Add-On-Version: 1.30
Eufy Security Integration: 6.1.0

**Comment by fuatakgun** [comment]
Please use the template, it has a purpose

**Comment by fuatakgun** [comment]
When you are creating a bug, there is a template i had created so you can put valuable information. This keeps my time and your time in optimum way because i don't ask same questions over and over. Create another issue using the template
