### ISSUE TITLE
Unable to load integration after updating to 2023.1.0

### ISSUE THREAD

**Issue by joegmc** [fuatakgun/eufy_security#658]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Since updating to 2023.1.0 im unable to load the integration. getting error Failed to Set Up.

![image](https://user-images.githubusercontent.com/72952993/210886911-c31ad582-38de-4ded-82e1-9d13117dfa5e.png)

This is the error being produced in the add on logs

 Error  
details:
{
  schemaId: 15,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:85 receiveMessage
    src/lib/server.ts:85:27
• server.ts:62 <anonymous>
    src/lib/server.ts:62:53
• node:events:527 emit
    node:events:527:28
• websocket.js:1169 receiverOnMessage
    node_modules/ws/lib/websocket.js:1169:20
• node:events:527 emit
    node:events:527:28
• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14
• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17
• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22
• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10
• writable:389 writeOrBuffer
    node:internal/streams/writable:389:12
2023-01-05 21:40:28.828  INFO  Client disconnected with ip: 172.30.32.1 port: 35108 code: 1006 reason:  
2023-01-05 21:40:40.209  ERROR Message error 

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Supervisor

**Comment by joegmc** [comment]
![image](https://user-images.githubusercontent.com/72952993/210888315-38f90cf2-1fa8-47be-a3e0-3cd33f206abc.png)

**Comment by fuatakgun** [comment]
Update your add-on to latest version 1.3.0

**Comment by twjacobsen** [comment]
I'm seeing the exact same issue, although not on a supervised installation but on a custom docker based one. I've installed bropat/eufy-security-ws:1.3.0 and latest version of rtsp-simple-server running homeassistant 2023.1.2

**Comment by duckpuppy** [comment]
Same here. Docker based install, eufy-security-ws and rtsp-simple-server are current as of today, but I'm getting the `schema_incompatible` error during eufy_security setup.
