### ISSUE TITLE
Unable to load integration after updating to 2023.1.0

### ISSUE THREAD

**Issue by Jupiterbe** [fuatakgun/eufy_security#659]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Since updating to Home Assistant 2023.1.0 the integration won't set up anymore. Add-on Version is 1.3.0

Integration:
![image](https://user-images.githubusercontent.com/43099691/210890737-18936735-086d-4f21-a844-5229a67e2e6e.png)

Integration Logs;
![image](https://user-images.githubusercontent.com/43099691/210891161-2554cb18-a5ff-4dc7-972f-6179019c76dc.png)

Add-on Logs:
![image](https://user-images.githubusercontent.com/43099691/210891361-d291751e-2cc7-474c-b647-a2cbd981d94c.png)

Add-on Version:
![image](https://user-images.githubusercontent.com/43099691/210891426-cd8ba76d-981a-4ff1-8476-289ca0b343f6.png)

**Comment by fuatakgun** [comment]
Read README file please
