### ISSUE TITLE
Cameras are not recognized as camera anymore

### ISSUE THREAD

**Issue by kaystrobach** [fuatakgun/eufy_security#661]
**Describe the bug**

Formerly properly working cameras are not providing a camera stream anymore.

![grafik](https://user-images.githubusercontent.com/1185776/210964360-6081829f-362c-4dca-9752-267a5dc43096.png)

**To reproduce**

* Open Entity
* Try to stream from Dashboard

**Expected behavior**

* be a camery entity and stream cleanly

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 

```
Version | core-2023.1.1
-- | --
Installationstyp | Home Assistant OS
Entwicklung | false
Supervisor | true
Docker | true
Benutzer | root
Virtuelle Umgebung | false
Python-Version | 3.10.7
Betriebssystemfamilie | Linux
Betriebssystem-Version | 5.15.80
CPU-Architektur | aarch64
Zeitzone | Europe/Berlin
Konfigurationsverzeichnis | /config
```

- Home Assistant Core Version: 

Hardware Information;
- Camera Model:

`T8010`

- Live Streaming Protocol (RTSP/P2P): 

`tried both, mainly RTSP`

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

```
2023-01-06 07:01:10.848  INFO  Client disconnected with ip: 172.30.32.1 port: 33512 code: 1006 reason: Abnormal Closure 
2023-01-06 07:19:29.977  INFO  Client disconnected with ip: 172.30.32.1 port: 34924 code: 1006 reason: Abnormal Closure 
2023-01-06 07:29:22.339  INFO  Client disconnected with ip: 172.30.32.1 port: 33330 code: 1006 reason: Abnormal Closure 
```

- Would you share your device with me in case further debugging required? (Yes/No): 
- 
yes

**Additional context**

Add any other context about the problem goes here.

**Comment by fuatakgun** [comment]
first uninstall the integration so all old entities are removed, afterwards install it back so you have only valid new entities and update here

**Comment by rmaia** [comment]
+1

**Comment by nenadmilano** [comment]
Neither the camera stream nur the still image works for me with my T8222 battery door cam and T8020 doorbell.

**Comment by MechEng70** [comment]
can confirm that uninstalling, reinstalling for SoloCam, Eufy 2, and Doorbell are not displaying any cameras.

**Comment by kombasltd** [comment]
Same here

**Comment by fuatakgun** [comment]
follow the bug template and share the logs

**Comment by kaystrobach** [comment]
Works with the current updates
