### ISSUE TITLE
"Eufy Security: Configuration" dialogue box sends error

### ISSUE THREAD

**Issue by KaherdinTristan** [fuatakgun/eufy_security#662]
HA\Settings\Devices and services\ Click 

Eufy Security: Configuration
Gets error message as follows;
User input malformed: expected bool for dictionary value @ data['generate_ffmpeg_logs']
See image below. Unknow why, because I have not changed anything. I just opened the dialogue box to see it there was any cool settings in there. 
 
![image](https://user-images.githubusercontent.com/3398594/210966794-039abb99-6dc9-4b41-a808-e19bcdaa1a8b.png)

**Comment by fuatakgun** [comment]
Can you uninstall the integration, restart HA and install it back again

**Comment by fuatakgun** [comment]
duplicate https://github.com/fuatakgun/eufy_security/issues/642

**Comment by vs6817** [comment]
> HA\Settings\Devices and services\ Click
> 
> Eufy Security: Configuration Gets error message as follows; User input malformed: expected bool for dictionary value @ data['generate_ffmpeg_logs'] See image below. Unknow why, because I have not changed anything. I just opened the dialogue box to see it there was any cool settings in there.
> 
> ![image](https://user-images.githubusercontent.com/3398594/210966794-039abb99-6dc9-4b41-a808-e19bcdaa1a8b.png)

Did you ever get this fixed?
