### ISSUE TITLE
Eufy addon failing to load, SSL error?

### ISSUE THREAD

**Issue by buzurk26** [fuatakgun/eufy_security#663]
Since installing the latest version of home assistant and the latest Eufy addons from HACS, it no longer loads

Logs show this

`**Unable to start driver RequestError: Hostname/IP does not match certificate's altnames: Host: extend.eufylife.com. is not in the cert's altnames: DNS:gg-cluster.com, DNS:*.gg-cluster.com**
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at new NodeError (node:internal/errors:387:5)
    at Object.checkServerIdentity (node:tls:354:12)
    at TLSSocket.onConnectSecure (node:_tls_wrap:1549:27)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:953:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
  code: 'ERR_TLS_CERT_ALTNAME_INVALID',
  timings: {
    start: 167*******197,
    socket: 167*********3,
    lookup: 167*********5,
    connect: 16*********426,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1672997293876,
    abort: undefined,
    phases: {
      wait: 6,
      dns: 2,
      tcp: 221,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 679
    }
  }
}`

**Comment by fuatakgun** [comment]
I can do nothing about this.

It says, ssl certificate of eufy domain (extend.eufylife.com) is not matching with gg-cluster.com.

It could be a local DNS issue or something else, but happening internal to your network.

**Comment by buzurk26** [comment]
> I can do nothing about this.
> 
> It says, ssl certificate of eufy domain (extend.eufylife.com) is not matching with gg-cluster.com.
> 
> It could be a local DNS issue or something else, but happening internal to your network.

Not sure its a local network or DNS issue, all my devices use googles dns and worked without issue

It only started occurring since i upgraded the plugin using HACs, just rolled back to 2.9 version and its all working again so i dont think its a local issue

**Comment by fuatakgun** [comment]
you are saying you have downgraded to 2.9 version of integration, but error is originated from add-on. Downgrading the integration cannot impact add-on version and error should continue independent of integration version.

**Comment by buzurk26** [comment]
> you are saying you have downgraded to 2.9 version of integration, but error is originated from add-on. Downgrading the integration cannot impact add-on version and error should continue independent of integration version.

I was on 2.9, Hacs was asking me to upgrade it to 6.1 which is where it broke

Just went back into hacs and selected 2.9 and re-downloaded it and its all back

**Comment by fuatakgun** [comment]
What i have told in previous message is still valid.

The error you had posted from addon (v1.3.0).

Whatever you upgrade/downgrade using hacs about integration. (V2 to v6).

Downgrading the integration cannot eliminate add-on error.

Anyway, up to you to hear or dismiss

**Comment by buzurk26** [comment]
> What i have told in previous message is still valid.
> 
> The error you had posted from addon (v1.3.0).
> 
> Whatever you upgrade/downgrade using hacs about integration. (V2 to v6).
> 
> Downgrading the integration cannot eliminate add-on error.
> 
> Anyway, up to you to hear or dismiss

I hear you loud and clear, and not trying to argue - i totally get what your saying

i am simply trying to let you know what i am experiencing in my setup, i described the exact changes made, and the outcome of that in my setup, i guess up to you also what youd like to hear/dismiss,

**Comment by fuatakgun** [comment]
You will eventually be forced to move into new version probably for some other upcoming issues, find the root cause while you have time.

This is the domain: https://github.com/bropat/eufy-security-client/blob/7fc2a45a75ee1bf69ced36d351d1ec6d623896f6/src/http/api.ts#L21

And this file is part of add-on, not integration.
