### ISSUE TITLE
Some services no longer available in version 6

### ISSUE THREAD

**Issue by tvvalbonne** [fuatakgun/eufy_security#665]
Hi,

Just upgraded from version 2 to lastest 6 yesterday and got 2 errors calling services in my scripts causing my cam alarm to not arm/desarm when leaving home.
I'm using 3 solo cams model T8441.
Missing services I use are :
- eufy_security.enable
- eufy_security.reset_alarm_for_camera

Did I mist something in the documentation to replace those services calls?
Thanks

**Comment by fuatakgun** [comment]
Yes, you missed that this was a breaking change and you need to go through readme and services list.
