### ISSUE TITLE
Support for T8123 / L40 SoloCam

### ISSUE THREAD

**Issue by franco-101** [fuatakgun/eufy_security#666]
Awesome project, so far most of the options are working from inside HA including Status Light, Arming / Disarming, Motion Status, Person Status...
Does anyone know if the model T8123 L40 Solocam is fully supported?
I am currently struggling to get the live camera feed working, I am also not able to view the last camera Picture URL?

Any guidance would be muchly appreciated.

**Comment by fuatakgun** [comment]
you can check home assistant topic
