### ISSUE TITLE
Doorbell T8210 Microphone and speaker

### ISSUE THREAD

**Issue by MrFl0w** [fuatakgun/eufy_security#667]
Hi,

Do you think it's possible to add microphone and speaker on doorbell T8210?
Those configurations exists on camera like T8113 but not on the doorbell.

Thanks in advance.

**Comment by fuatakgun** [comment]
Do you mean switch to enable and disable these or taking over microphone and hearing from speaker?

Switches should already exist, if not, share your Debug device sensor attributes
