### ISSUE TITLE
Enabled and Motion Detection switches don't update in HA after being updated in EufySecurity app

### ISSUE THREAD

**Issue by oNSXo** [fuatakgun/eufy_security#669]
You closed #449 as completed, but even with the latest v6.1.1, this does not appear fixed.

Triggering force_sync still doesn't pull in the latest data.  However, if I restart the add-on and then restart HA, that does appear to fetch the latest data.  It seems like almost the add-on isn't intermittently refreshing data from the API and only ever using the cache from when it started.

**Describe the bug**

Reporting of the "Enabled" and "Motion Detection" switches do not update in HA after being updated within the EufySecurity app.

**To reproduce**

Observe Camera Enabled switch set to On in HA
Open EufySecurity app and click on Camera
Flip the top switch to Off
Observe Camera Enabled switch in HA is still on (and continues to be on even after the cloud polling interval)

**Expected behavior**

Switch should eventually match current state within the app

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):  OS
- Home Assistant Core Version:  2022.12.8
- Eufy Security Add-on Version:  1.3.0
- Eufy Security Integration Version: 6.1.1

**Additional context**

I've tried triggering the force_sync service and even restarting HA with no avail. However, if I flip the switch from within HA, that state does get set correctly and if I reopen the EufySecurity app, I do see the result of the action taken within HA.

**Comment by fuatakgun** [comment]
ok, let's try this, if you flip the switch from HA and stay on the same page of Eufy, do you see that it is updated? No. Then there is no notification coming from eufy to us.

You can reach out to eufy-security-ws owner and share that you are not notified for `Enabled` and `Motion Detection` flips.
