### ISSUE TITLE
Add talk back in eufy-security as media player

### ISSUE THREAD

**Issue by rwunsch** [fuatakgun/eufy_security#674]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to use microphone and speaker to communicate through cameras or doorbells.

**Describe the solution you'd like**
Implement the option to talk back out of eufy-security-ws as media player in home assistant.

https://www.google.com/url?sa=t&source=web&cd=&ved=2ahUKEwiVwOqZsbn8AhVF87sIHdaOBXMQFnoECBIQAQ&url=https%3A%2F%2Fgithub.com%2Fbropat%2Feufy-security-ws%2Fissues%2F134&usg=AOvVaw2y2Ks-OyFBIZGhjKFASaSS

**Comment by fuatakgun** [comment]
moving into wish list
https://github.com/fuatakgun/eufy_security/issues/591

**Comment by rwunsch** [comment]
Thanks a ton @fuatakgun !!

**Comment by fuatakgun** [comment]
but, I had a quick look earlier, it is way more difficult and fragile.
- Only HTTPS web pages support microphone access. 
- while you are talking, a background thread using ffmpeg should capture microphone and forward it to the camera and apparently, it requires chunking and I am sure it will be chopped on the way (I might be overthinking here)
Streaming should already giving you to access to speaker, right?

**Comment by fuatakgun** [comment]
My initial plan to add Media Browser feature to watch recorded events, so this will follow it
