### ISSUE TITLE
Floodlight Camera T8422 no longer has motion since v6.1.0 upgrade

### ISSUE THREAD

**Issue by kevinfowler** [fuatakgun/eufy_security#677]
**Describe the bug**

Ever since I upgraded to the v6.1.0 I no longer have any motion sensors available.  So I can't create any Automations based on motion.  There is a Person sensor but this camera doesn't support person detection.  But even if tried to use the Person sensor it doesn't show in the list of triggers when creating an automation from the Web UI.

**To reproduce**

Create an automation from the Web UI and select the T8422 device.  Then click the trigger dropdown.  There are no options on motion detection.  Also if I go to the device itself under Sensors there is no longer a motion sensor.  There was in the previous version.

Hardware Information;
- Eufy Floodlight Camera T8422

- Would you share your device with me in case further debugging required? (Yes/No): 

yes

**Comment by awirtz** [comment]
Same here with both my T8142-Z, just noticed it today, as I was playing around with the motion sensor.

It alternates between "off" (clear) and "unavailable", which is not how it should be.

No error messages to share are visible in the log.

**Comment by copekyle** [comment]
I'm also seeing this on my doorbell camera T8201. It looks like the device itself had a firmware update on 12/18/2022... I'm wondering if this is when it died? I have it in an automation to do things when people show up at my door. Noticed last night it wasn't working. (that's how often I have people over)

**Comment by kevinfowler** [comment]
Mine was working until I updated the Home Assistant integration from v2.10.0 to v6.1.0.  I have since tried all the newer versions including the v6.2.0 just released and there is still no longer a motion trigger.

**Comment by fuatakgun** [comment]
And no one bothered to share any logs ..

**Comment by copekyle** [comment]
I can share logs if you tell me what you're looking for? I'm monitoring the logs in docker and can not see any errors on the eufy security side. Sometimes it connects to my device and other times it fails (normal).  Home Assistant logs (in docker) show only this when I attempt to view my camera now:
```
2023-01-11 15:56:46.478 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities camera.front_door or it is/they are currently not available
```
![image](https://user-images.githubusercontent.com/10146057/211935841-b40f6220-edf7-4c13-bce9-cd3d20d12c71.png)


I'm not sure where else to check.

**Comment by awirtz** [comment]
> And no one bothered to share any logs ...

Thing is, there's nothing in the logs that looks funny... I have custom_components.eufy_security on debug and this is what I see when I wave at the camera (that was at 9:44 according to my watch) and the motion sensor was "Clear" throughout the time:

`2023-01-12 09:44:26.813 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'disconnected', 'serialNumber': 'T8010xxx'}}
2023-01-12 09:44:31.855 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'connected', 'serialNumber': 'T8010xxx'}}
2023-01-12 09:44:43.716 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2023-01-12 09:44:43.717 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2023-01-12 09:44:43.717 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 16556
2023-01-12 09:45:35.397 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'disconnected', 'serialNumber': 'T8010xxx'}}
2023-01-12 09:45:40.420 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'connected', 'serialNumber': 'T8010xxx'}}
2023-01-12 09:46:43.944 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'disconnected', 'serialNumber': 'T8010xxx'}}
2023-01-12 09:46:48.979 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'station', 'event': 'connected', 'serialNumber': 'T8010xxx'}}
2023-01-12 09:47:14.276 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'command': 'driver.poll_refresh', 'messageId': 'driver.poll_refresh.35a7dfdb2f15477ca72e3fd31bf0eae4'}
2023-01-12 09:47:14.777 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'property changed', 'serialNumber': 'T8142xxx', 'name': 'lastChargingRecordedEvents', 'value': 55}}
2023-01-12 09:47:14.782 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'property changed', 'serialNumber': 'T8142xxx', 'name': 'lastChargingTotalEvents', 'value': 61}}
2023-01-12 09:47:14.786 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'event', 'event': {'source': 'device', 'event': 'property changed', 'serialNumber': 'T8142xxx', 'name': 'pictureUrl', 'value': 'T8010xxx~/media/mmcblk0p1/video/20230112094515_c00.jpg'}}
2023-01-12 09:47:14.791 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'driver.poll_refresh.35a7dfdb2f15477ca72e3fd31bf0eae4', 'result': {}}
2023-01-12 09:47:14.792 DEBUG (MainThread) [custom_components.eufy_security] Finished fetching eufy_security data in 0.516 seconds (success: True)
2023-01-12 09:47:14.947 DEBUG (MainThread) [custom_components.eufy_security] image 1 - False - None
2023-01-12 09:47:14.947 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 5 - is_empty False
2023-01-12 09:47:14.948 DEBUG (MainThread) [custom_components.eufy_security] async_camera_image 6 - 16556`

**Comment by kevinfowler** [comment]
Log wise there is not really much to show because it's not like the sensor is not detecting the motion because of an error.  The sensor just no longer exists in home assistant after the integration upgrade.  I know the issue is not in eufy-security-ws or eufy-security-client when I manually connect with the ws client i see the notifications of the motion just fine.  Plus I have not upgraded the container which contains the eufy-security-ws.  It lost the sensor when I upgraded the home assistant integration.  

I attached a screenshot of the sensors that now show on this device.  Previously there was a motion sensor there.

![Screenshot from 2023-01-12 17-43-02](https://user-images.githubusercontent.com/82553302/212197139-1403dc69-ea4d-4324-9c57-788a153debb4.png)

Here is an example of my Eufy T8210 doorbell camera that still has the motion sensor after the upgrade:

![Screenshot from 2023-01-12 17-44-50](https://user-images.githubusercontent.com/82553302/212197287-19cc707d-67d8-49e9-8f48-c52e7c97dd56.png)

**Comment by rnhung** [comment]
Same issue for Eufy Floodlight T8423 (Floodlight 2 Pro 360). There doesn't seem to be a Motion/Person detected binary sensor viewable in Home Assistant. 

I did notice my "switch.garage_fl_new_motion_detection_2" does appear to switch from Off to On when motion is detected (and then back to off), but seems like it's only for motion. Nothing seems to be able to track when a person is detected.

Would also love to help troubleshoot. I'm a bit new and still learning, so let me know what you're looking for, and I'll do my best to provide it.

Appreciate all the work on this project.

**Comment by ddp526** [comment]
Hi,

Similar issue here, and I am also not sure what to provide as further information.  I know some python, but not much of hass.  For what its worth, I tried to do some basic logging/debugging, I can see in const.py you create a binary sensor, but in binary_sensory.py for some reason the motion detection is not added (the 4 binary sensors shown below are the only ones I get in hass).

Some hopefully useful info:
from a log in const.py just after you create motionDetecte:
```
motionDetected=EntityDescription(id=<enum.auto object at 0x7fc74c3c2bc0>, icon=None, state_class=None, device_class=<BinarySensorDeviceClass.MOTION: 'motion'>, unit=None, category=None)
```

This is my output of print(entities), placed just the line before the 'async_add_entities(entities)' in binary_sensor.py
```
[custom_components.eufy_security]: entities=[<Entity Front Door Snooze: off>, <Entity Front Door Alarm: off>, <Entity Front Door Debug (device): on>, <Entity Front Door Debug (station): on>]
```

**Comment by fuatakgun** [comment]
@awirtz , you have lots of disconnections and connections happening and we would not receive any events through disconnected time frames.

If integration is not receiving a message like `_on_message property changed motion detection/person detected` we can do nothing here. you should reach out to eufy-security-ws repository to find out why these messages are not sent to integration

**Comment by rnhung** [comment]
I'm not sure whether this helps (or is even related to this situation with the Floodlight not having a motion/person binary sensor on HA, but I found these under the log of the Eufy Security Add-on. 

`2023-01-17 15:21:19.862  ERROR Invalid Property personDetected error 
 InvalidPropertyError  Property personDetected invalid
error stack:
• device.ts:568 getPropertyMetadata
    node_modules/eufy-security-client/src/http/device.ts:568:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:48
• device.ts:2123 <anonymous>
    node_modules/eufy-security-client/src/http/device.ts:2123:38
• timers:559 listOnTimeout
    node:internal/timers:559:17
• timers:502 processTimers
    node:internal/timers:502:7
2023-01-17 23:33:22.947  ERROR Invalid Property personDetected error 
 InvalidPropertyError  Property personDetected invalid
error stack:
• device.ts:568 getPropertyMetadata
    node_modules/eufy-security-client/src/http/device.ts:568:15
• device.ts:76 updateProperty
    node_modules/eufy-security-client/src/http/device.ts:76:48
• device.ts:1587 processPushNotification
    node_modules/eufy-security-client/src/http/device.ts:1587:38
• device.ts:2102 processPushNotification
    node_modules/eufy-security-client/src/http/device.ts:2102:15
• eufysecurity.ts:978 <anonymous>
    node_modules/eufy-security-client/src/eufysecurity.ts:978:32
• eufysecurity.ts:976 <anonymous>
    node_modules/eufy-security-client/src/eufysecurity.ts:976:25
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5`

**Comment by shawn-fletcher** [comment]
I have two -  T8142 that I noticed no longer log global motion and trigger an automation I have.   

Looking at the device settings.  All motion entities say they are unavailable. 
![Screenshot 2023-01-18 123902](https://user-images.githubusercontent.com/92395989/213266382-4a3380f3-8e70-49b6-a66c-1da5fac99b11.png)

**Comment by kevinfowler** [comment]
I too have the Person detection sensor show when viewing the properties of the camera device.  However, I can't setup an automation using the Person detection, at least not from the the Web UI.  

For example, if I got to Settings->Automatons->Create Automation and select to create an empty automation then add a Device trigger and select the camera then I don't have an option under Trigger to select anything related to motion detection.  I used to be able to select a motion detection and a the Global motion detection.  There is also no trigger for Person detection in the list.

Note: there is a trigger available to detect when motion detection is turned off or turned on.  But no trigger to detect when there is actual motion since the v6.1.x upgrade on the T8422 camera.

Also I noticed the _2 entities a while ago and cleaned most of those up by removing the cameras and re-adding them.  But that still doesn't fix the missing motion sensor.

**Comment by fuatakgun** [comment]
it is better to remove the existing integration and install the new version so you wont have this duplicate entries.

**Comment by ddp526** [comment]
First off thanks again for the help, trying to summarise where I am at / what I can clarify.  I removed the integration and all entities and then downgraded (manually) back to v2.10 and the motion detection binary_sensor was created and worked again.  I since went back to the latest version (v.6.20) and there is no binary_sensor for motion detection, but I have noticed 2 switches for motion detection.  My camera is called 'front_door'. and my 2 sensors are:
switch.front_door_motion_detection
switch.front_door_motion_detection_2

If I change my camera to detect all motion not just humans, then the 'switch.front_door_motion_detection_2' changes to True when motion is detected, otherwise when detecting humans only it does not change.   Given I only changed your integration, I assume the eufy-client-ws is working, and its something to do with how the data is being processed on initilisation?

@fuatakgun if you can give me a quick pointer to where in your code you call the API to get the camera properties and process them and what you expect to create the binary_sensor then I can have a look at what data my camera is returning and why it doesn't create the binary_sensor anymore.

Thanks in advance.

**Comment by shawn-fletcher** [comment]
Ok, I finally got it working again!

After the latest update, I noticed that none of my Eufy cameras were logging any events in the log like they used to. It wasn't just my broken automation to turn a light on when motion was activated that broke. After the entities changed names with this past update, it logged nothing for the entities.

I ended up removing the integration, removing the add-on, and removing Eufy Security repository out of HACs.  

I re-downloaded the v6.1.0 upgrade in HACS and followed the instructions to setup the add-on and integration again.  After that, I could see the cameras were once again logging motion events.  Granted the entity names on the events are now different.

In my Automation to turn on my driveway light, I had to use both motion detection entities of "Motion Detected" and "Human Detected" as triggers using the State option. The camera is not very accurate as to whether it is a human or not, but I could tell from the logs it was doing one or the other, so I added both.

![image](https://user-images.githubusercontent.com/92395989/214996274-bf11ccc1-1268-4c6b-b052-2cbbaeec935f.png)

I did notice though, when you are setting up the automation, you select "Detected" in the To dropdown like in the pic below:

![image](https://user-images.githubusercontent.com/92395989/214996638-166e47b6-b259-4f41-9dfe-66854f30ef1a.png)

After you save it, that option changes to ON all by itself.  It still continues to work.

So in the end, the 6.1.0 version does work, but it just doesn't upgrade well.  You're better off just removing it all and starting over.  I hope this helps someone else out.

**Comment by rvmuilekom69** [comment]
@shawn-fletcher 
Followed the same steps as you, but unfortunatly still no motion sensor available / not selecteable in Automation.
Not sure what todo to fix this :-(

**Comment by shawn-fletcher** [comment]
@rvmuilekom69 
I'm not sure if it matters, but I also restarted Home Assistant after I removed the integration from settings, the Add On , and repository from HACs.  I also restarted HA after I redownloaded Eufy Security from HACS.

**Comment by rvmuilekom69** [comment]
@shawn-fletcher 
Did all that too, but still no luck
Thanks for your reply

**Comment by patrickli** [comment]
I installed a new T8422 last week and configured this integration (6.2.0) from scratch. No motion related binary sensors are available.

**Comment by kevinfowler** [comment]
I turned on DEBUG logging for the eufy-security integration in homeassistant.  Then I deleted and re-added the integration.  Attached is the log of the output for my 3 devices being deteced.  The on labeled garage is the one with the missing motion detection sensor.  Another thing I noticed is that "Motion Detection" shows both under Controls and under Configuration when viewing the device in Settings.  The Motion Detection that shows in Controls is always turned off and you can't turn it on.  That is the entity you can see being detected in this log as switch.garage_motion_detection_2.  The real one that shows under Configuration is called switch.garage_motion_detection and it does successfully turn the Motion Detection setting on and off.  But the issue is that there is no sensor to use.

/run/user/1000/gvfs/sftp:host=djkev/home/djkev/homeassistant/eufy-added.txt

**Comment by kevinfowler** [comment]
Since the latest Home assistant update 2023.3.4 I now have a "Person detected" sensor on my T8422 camera and can again setup Automations successfully using this sensor.  Even though the sensors broke when I updated the Eufy Security integration, the latest Home Assistant has it working again with the same v6.2.0 of the integration.
