### ISSUE TITLE
Disarming prevents notifications from being sent and processed

### ISSUE THREAD

**Issue by FHannes** [fuatakgun/eufy_security#678]
With the latest version 9.1.1, when you disarm a homebase from HA, it switches the homebase to the disarmed guardmode. Switching to disarmed seems to as indicated by the description, disable all device triggers, meaning that there's also no notification messages (as opposed to the Off guardmode). As a result, motion sensors and such do not function anymore until the mode is switched to Off manually in the app.

Can the disarm trigger in HA be changed so it switches to the Off guardmode instead? If I understand correctly, it was already implemented in reverse, so Off shows as disarmed in HA?

**Comment by fuatakgun** [comment]
Off mode only exists for keypad users, i personally don't have it, so we cannot generalize it.

**Comment by RienduPre** [comment]
I also like to have the described functionality, this way it's in line with other Alarm integrations with a keypad and more logical.

The off and disarmed mode are both available in the app so you don't need to have a keypad to use it

**Comment by fuatakgun** [comment]
Where is it? And how do you know it? @RienduPre 

![Screenshot_2023-01-10-20-31-15-083_com.oceanwing.battery.cam.jpg](https://user-images.githubusercontent.com/11085566/211644246-5c39bb73-2c8c-4338-b583-b924e0b1637a.jpg)

![Screenshot_2023-01-10-20-31-50-094_com.oceanwing.battery.cam.jpg](https://user-images.githubusercontent.com/11085566/211644389-ca2eb880-aee3-4487-b218-e50a7c5be3b9.jpg)

**Comment by RienduPre** [comment]
![Scherm­afbeelding 2023-01-10 om 20 42 21](https://user-images.githubusercontent.com/9009949/211647166-912167ba-c8e5-4c3f-be2f-2f5ed16f598b.png)
![Scherm­afbeelding 2023-01-10 om 20 41 33](https://user-images.githubusercontent.com/9009949/211647174-81f14f2d-113c-4dc6-8a4c-70dcad3f7094.png)

**Comment by fuatakgun** [comment]
Yes, that is what i have said 2 messages before, off mode only exists for keypad users and you used it is not.

How can we generalize it?

**Comment by fuatakgun** [comment]
and why would we switch to Off when user actually disarms, even though there is one to one mapping to Disarm. this integration is trying to replicate the experience and you are more than capable to create a template alarm panel to manage this.

**Comment by RienduPre** [comment]
Yes templating is a valid option. But users have to be aware of using the default alarm card will disarm the HomeBase, meaning no notifications anymore
