### ISSUE TITLE
failed to setup since January 3rd

### ISSUE THREAD

**Issue by Twanne** [fuatakgun/eufy_security#683]
**Describe the bug**

Since januari 3rd, none of the sensors are available in Home Assistant anymore.
The integration worked as expected up to that point, no changes have been made to the setup or to the Eufy Security App settings.
Devices are in home mode, so all triggers are active and work within the native app.

**To reproduce**

1. Go to 'settings'
2. Click on de 'devices and services'
3. Eufy Security integrations says 2 devices, 25 entities, but shows failed to setup error (see log below).

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: core-2022.12.9
- Eufy Security Add-on Version: Eufy Security Add-on (1.3.0)
- Eufy Security Integration Version: /

Hardware Information;
- Camera Model: T8210

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- 

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

>This error originated from a custom integration.
>
>Logger: custom_components.eufy_security
>Source: custom_components/eufy_security/websocket.py:58
>Integration: Eufy Security (documentation, issues)
>First occurred: January 4, 2023 at 13:28:47 (1 occurrences)
>Last logged: January 4, 2023 at 13:28:47
>
>eufy_security - Exception - process_messages: 'connected' - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 56, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 67, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 287, in on_message await self.process_driver_connect_response(message["connected"]) KeyError: 'connected' - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"driver_connect","result":{"result":true}}', extra='')

>This error originated from a custom integration.
>
>Logger: homeassistant.config_entries
>Source: custom_components/eufy_security/coordinator.py:184
>Integration: Eufy Security (documentation, issues)
>First occurred: January 4, 2023 at 13:29:26 (1 occurrences)
>Last logged: January 4, 2023 at 13:29:26
>
>Error setting up entry localhost for eufy_security
>Traceback (most recent call last):
>  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
>    result = await component.async_setup_entry(hass, self)
>  File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
>    await coordinator.initialize()
>  File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
>    await self.set_devices()
>  File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
>    if await self.async_get_device_properties() is False:
>  File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
>    for device in self.devices.values():
>AttributeError: 'NoneType' object has no attribute 'values'

- Would you share your device with me in case further debugging required? (Yes/No): 

**Additional context**

Add any other context about the problem goes here.

**Comment by SmartDruid** [comment]
Same issue, no sensors available and the integration keeps showing the "Configuration Retry" warning. 
I haven't changed any settings in the webcams and Home Assistant. 
The Official Eufy App continues to function normally.

**Comment by witold-gren** [comment]
try uninstall docker add-on and this plugins, and install it again - it helped me and all devices started working properly 😀

**Comment by fuatakgun** [comment]
please disable 2fa to be sure that it is not the root case

**Comment by SmartDruid** [comment]
> please disable 2fa to be sure that it is not the root cause
> 
> I have noticed that having 2fa and captcha at the same time causes issues

Hi @fuatakgun, hi @witold-gren 

I tried disabling F2A via the Eufy app and uninstalling the Home Assistant integration and add-on.

After uninstalling everything I restarted Home Assistant and first I tried to install the add-on again.

I entered the data, but this error is reported:

<img width="836" alt="Schermata 2023-01-17 alle 12 15 39" src="https://user-images.githubusercontent.com/82620719/212929919-dc305395-cf45-4e19-b5f3-ec38a897183c.png">

I have not changed the username and password to the account and in fact restoring the old Home Assistant backup in the add-on no error is reported, but this message: INFO Eufy Security server listening on host 0.0.0.0, port 3000
but the integration keeps trying to connect showing the exclamation mark and leaving the sensors unknown

**Comment by jcknox** [comment]
Same issue for me. This is the log I'm seeing:

2023-01-17 22:49:36.555 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 172.22.9.22 for eufy_security
File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 148, in _set_schema
File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 345, in _send_message_get_response
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.cb5d0fbb684446af835c757dabc7c5f5', 'errorCode': 'schema_incompatible'}

**Comment by fuatakgun** [comment]
@jcknox please open a new bug and follow the template

**Comment by jcknox** [comment]
Thanks for the note. I thought my problem was the same. Since it looks like
it isn't, I'm going to do some more troubleshooting on my end before I drop
this in your lap.

**Comment by dmhomeautomation** [comment]
Had the same issue.  Was simply unable to get it working properly with the add-on as-is.  I couldn't even get to a config screen to update the IP, user/password.

**WARNING: MAKE BACKUPS BEFORE MAKING CHANGES!!!** 

I installed a separate docker image for the bropat/eufy-security-ws container (I have another VM running Docker for other stuff).  

`docker run -e -d --name eufy-security-ws USERNAME=[myeufylifeusername] -e PASSWORD=[myeufylifepassword] -e COUNTRY=US -e TRUSTED_DEVICE_NAME=eufyclient -v "$(PWD)"/data:/data -p 3000:3000 bropat/eufy-security-ws:1.3.0`

Then I modified the core config file:  /config/.storage/core.config_entries 
Look for the section containing "domain": "eufy_security"

**Update as follows: changing the IP from 127.0.0.1 to whatever docker host you installed to above**
`
      {
        "entry_id": "02d49ffe698069484838b346c1fc1aec",
        "version": 1,
        "domain": "eufy_security",
        "title": "**[dockerhost_ip or whatever name you want]**",
        "data": {
          "host": "**[dockerhost_ip or dns_name]**",
          "port": 3000
        },
        "options": {
          "sync_interval": 600,
          "rtsp_server_address": "**[dockerhost_ip or dns_name]**",
          "rtsp_server_port": 8554,
          "ffmpeg_analyze_duration": 1.2,
          "generate_ffmpeg_logs": false,
          "no_stream_in_hass": false,
          "name_for_custom1": "Custom 1",
          "name_for_custom2": "Custom 2",
          "name_for_custom3": "Custom 3"
        },
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      }
`

**Comment by fuatakgun** [comment]
Now the issue is evolved into `response data is missing` one, i will not spend time to answer.
