### ISSUE TITLE
Card missing?

### ISSUE THREAD

**Issue by alwyntn** [fuatakgun/eufy_security#687]
Since recent update, card on dashboard is now missing.
I can see the camara card on dashboard when Im in edit mode, but once I hit done, card disappear ?
Any idea?

` square: false
columns: 1
type: grid
cards:
  - type: conditional
    conditions:
      - entity: camera.entrance
        state: idle
    card:
      show_state: true
      show_name: true
      type: picture-entity
      entity: camera.entrance
      camera_image: camera.entrance
      tap_action:
        action: call-service
        service: camera.turn_on
        data: {}
        target:
          entity_id: camera.entrance
  - type: conditional
    conditions:
      - entity: camera.entrance
        state: streaming
    card:
      type: vertical-stack
      cards:
        - show_name: true
          show_icon: false
          type: button
          tap_action:
            action: call-service
            service: camera.turn_off
            data: {}
            target:
              entity_id: camera.entrance
          entity: camera.entrance
          name: Stop
        - type: custom:webrtc-camera
          entity: camera.entrance `

**Comment by fuatakgun** [comment]
Please use home assistant post, you will probably find some help.

Assuming that you have already investigated if your camera is actually moving between `idle` and `streaming` states, i hope you are not expecting us to investigate that part.

Lastly, this is supposed to be a breaking change, so it is broken as expected.
