### ISSUE TITLE
All Cams not arming home/away

### ISSUE THREAD

**Issue by Ringo982** [fuatakgun/eufy_security#688]
Hello
I don’t know why but arming home/away from my automations has stopped working for all my cameras and home base.
I have homebase2, homebase3, and a lot of indoor and outdoor cameras, and they have all stopped arming/disarming.
A few weeks ago I opened a similar issue for homebase3, but it was solved. It worked for a few weeks perfectly but now the problem is back and not only on homebase3 but on all my cameras!!

What is going on guys? 

Thank u

**Comment by fuatakgun** [comment]
Follow bug template

**Comment by Ringo982** [comment]
What??Inviato da iPhoneIl giorno 14 gen 2023, alle ore 14:56, Fuat Akgün ***@***.***> ha scritto:﻿
Follow bug template
