### ISSUE TITLE
Persist Thumbnails Across Reloads

### ISSUE THREAD

**Issue by akeslo** [fuatakgun/eufy_security#692]
**Is your feature request related to a problem? Please describe.**
With the new way thumbnails are generated, thumbnails will be blank upon initial load of the integration. 

![image](https://user-images.githubusercontent.com/3003773/212562956-2409762f-15ea-4b9a-acf3-bfd86e34f496.png)

**Describe the solution you'd like**
 It would be nice to have the integration start with the last known images.

**Describe alternatives you've considered**
I'm trying to automate the thumbnails via the motion detected sensors with node red (below).  With the amount of cameras I have, performance of my pi degrages very quickly and I cannot have more than 2 cameras running at a time.  I often need to restart the integration to allow the pi/ha to become responsive, I believe I am experiencing this issue here: [647](https://github.com/fuatakgun/eufy_security/issues/647).  Upon restart all images are lost. I have not yet been able to get thumbnails to load on all cameras before a reload is needed.

![image](https://user-images.githubusercontent.com/3003773/212563187-10bdbc64-a369-411b-aed5-088c907b62ee.png)

**Comment by fuatakgun** [comment]
I would actually prefer this to be fixed by eufy-security-ws library, rathen than spending time here to fix it. And anyone can stream for couple of seconds to generate new pictures, right?

**Comment by akeslo** [comment]
> I would actually prefer this to be fixed by eufy-security-ws library

Gotcha

> And anyone can stream for couple of seconds to generate new pictures, right?

Maybe I should be focusing on this instead...why I can't seem to get my streams stable.

**Comment by akeslo** [comment]
@fuatakgun is there an attribute that I can use to detect that no thumbnail image is available? I see "sensor.entity_name_last_camera_picture_url" will this always hold a path?  I'm seeing it populated even when the camera has no thumb.

Thanks!

**Comment by fuatakgun** [comment]
please check latest release
