### ISSUE TITLE
Eufycam Floodlight showing issue

### ISSUE THREAD

**Issue by jhalak1984** [fuatakgun/eufy_security#693]
Been having issue with floodlight I believe since that Eufy debacle. I think the integration is working fine because I can control floodlight but just the camera won't stream. My Eufy Security Add-on log looks like this 
![Capture](https://user-images.githubusercontent.com/102031850/212700320-01b3871c-d3c9-4f96-ab9a-bd07785ab592.PNG)

HA log looks like this
![Capture](https://user-images.githubusercontent.com/102031850/212700933-3eaede2f-ab2b-44ff-b9da-92c47408326d.PNG)

PS. sorry if my logs have been added incorrectly. This is my first request and brand new to GitHub,

Thank you in advance

**Comment by fuatakgun** [comment]
why dont you use the bug template? It will help you for correct format and how to receive the logs.

**Comment by jhalak1984** [comment]
Thank you for the reply. I couldn't figure out how to but will look into it now. But my issue still remains though? You want me to open new one with the correct template?

**Comment by fuatakgun** [comment]
You might find that there are similar open issues, and just put +1 if they look similar
