### ISSUE TITLE
Card display issue + Lock Not Responding

### ISSUE THREAD

**Issue by chicknlil** [fuatakgun/eufy_security#697]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

Did not see any related issues.

**Describe the bug**

When clicking on a "camera card" in any of my dashboards, no stream is started, and thus I can't stop it and receive a thumbnail.

**To reproduce**

Using the "camera card" setup we discussed previously on a dashboard, click the grey camera image (in this case Doorbell, showing a state of Idle). In the past, this would then start the stream, which after what seems like 5-10 seconds, you could stop and then receive a thumbnail to replace that grey camera image. 

**Expected behavior**

Clicking the grey camera image to start the stream.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):  Supervisor 2022.12.1
- Home Assistant Core Version:  Home Assistant 2023.1.5 // Operating System 9.4
- Eufy Security Add-on Version:  1.3.0
- Eufy Security Integration Version:  6.2.0

Hardware Information;
- Camera Model:
It's applicable to both my T8200 and my T8422

- Live Streaming Protocol (RTSP/P2P): 
I believe P2P?

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
None created.

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
```
2023-01-19 17:09:16.130  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-01-19 17:09:21.247  ERROR MQTT Error 
 Error  Connection refused: Not authorized
details:
{
  code: 5
}
error stack:
• client.js:1388 MqttClient._handleConnack
    node_modules/mqtt/lib/client.js:1388:17
• client.js:549 MqttClient._handlePacket
    node_modules/mqtt/lib/client.js:549:12
• client.js:438 work
    node_modules/mqtt/lib/client.js:438:12
• client.js:452 writable._write
    node_modules/mqtt/lib/client.js:452:5
• _stream_writable.js:409 doWrite
    node_modules/readable-stream/lib/_stream_writable.js:409:139
• _stream_writable.js:398 writeOrBuffer
    node_modules/readable-stream/lib/_stream_writable.js:398:5
• _stream_writable.js:307 Writable.write
    node_modules/readable-stream/lib/_stream_writable.js:307:11
• readable:754 ondata
    node:internal/streams/readable:754:22
• node:events:513 emit
    node:events:513:28
• readable:315 addChunk
    node:internal/streams/readable:315:12
2023-01-19 17:09:21.263  INFO  MQTT connection closed 
2023-01-19 17:09:26.621  INFO  Connected to station T8422N1021151309 on host 174.76.49.154 and port 25359 
2023-01-19 17:09:26.636  INFO  Connected to station T8200N00210315E4 on host 192.168.0.67 and port 13929 
2023-01-19 17:09:28.626  INFO  Connected to station T8520Q202213029F on host 192.168.0.31 and port 10654 
2023-01-19 17:09:36.366  INFO  Push notification connection successfully established 
2023-01-19 17:09:58.859  INFO  Initiated closing of connection to station T8520Q202213029F for saving battery. 
2023-01-19 17:09:58.865  INFO  Disconnected from station T8520Q202213029F 
2023-01-19 17:14:30.946  INFO  Client disconnected with ip: 172.30.32.1 port: 59132 code: 1006 reason: Abnormal Closure  
```

- Would you share your device with me in case further debugging required? (Yes/No): 
Yep - it's still shared to you, actually.

**Additional context**

```
  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout: 
      - height: 350 px
    cards:       
      - type: conditional
        conditions:
          - entity: camera.doorbell
            state: idle
        card:
          show_state: true
          show_name: true
          type: picture-entity
          entity: camera.doorbell
          camera_image: camera.doorbell
          tap_action:
            action: call-service
            service: camera.turn_on
            data: {}
            target:
              entity_id: camera.doorbell
      - type: conditional
        conditions:
          - entity: camera.doorbell
            state: streaming
        card:
          type: vertical-stack
          cards:
            - show_name: true
              show_icon: false
              type: button
              tap_action:
                action: call-service
                service: camera.turn_off
                data: {}
                target:
                  entity_id: camera.doorbell
              entity: camera.doorbell
              name: Stop
            - type: custom:webrtc-camera
              entity: camera.doorbell
```
That's how the cards appear on my dash.  They were working as expected when we initially set them up...2-3 weeks ago.

**Comment by chicknlil** [comment]
Updating this (and changed the title) because I'm now having an issue with Keyless Entry (T8520). Pressing the lock (or unlock) button from either a card or the integration itself is not doing anything (read: the door is not locking or unlocking). That being said, it is seeing when the door is manually locked or unlocked (or I do so through the Eufy app) and in the case where I have automations tied to it being locked, are running those accordingly.

Given that this is the one element that has been working all along, this is a bit distressing, because I've come to rely on it so heavily.

**Comment by fuatakgun** [comment]
which version of webrtc you are using? v3 does not seem to play well, so use 2.3.1 
moreover, add-on is generating `not authorized` error, please reach out to @bropat over eufy-securit-ws , he can help

**Comment by chicknlil** [comment]
I had v3 (I was on the beta), but downgraded to 2.3.1 and it did not make a difference. Perhaps I need to delete the addon entirely, then reinstall at 2.3.1 and see if that helps?

Will reach out to @bropat ...but any thoughts on why my lock is no longer working?

**Comment by chicknlil** [comment]
@fuatakgun ... just saw the following error in my logs tonight:

This error originated from a custom integration.

```
Logger: custom_components.eufy_security.eufy_security_api
Source: custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py:107
Integration: Eufy Security (documentation, issues)
First occurred: 10:49:30 PM (2 occurrences)
Last logged: 10:49:46 PM

Exception [Errno 104] Connection reset by peer - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py", line 103, in setup client_socket.sendall(bytearray(self.camera.video_queue.get())) ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by chicknlil** [comment]
So, my card issue is resolved - believe it or not, it wasn't resolved by WebRTC, but the RTSP Simple Server Add-on.  Somehow, start on boot had gotten turned off. I fixed that and the cards have been behaving since.  The locks also appear to be working.

So I guess I can close this at this point.
