### ISSUE TITLE
Docker run -it - requires at least one argument

### ISSUE THREAD

**Issue by ahamster13** [fuatakgun/eufy_security#7]
Hi All.

Fairly new to Home assistant. I'm trying to get this to work and not sure what i am doing wrong. I am running a basic setup with a Pi 3B.

from an SSH terminal or SSH via putty I have run the commands in the prompt:
~ git clone https://github.com/bropat/eufy-security-ws
~ cd eufy-security-ws

This displays:
➜  eufy-security-ws git:(master)

when i type in docker run -it, i get the follow error message.

"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

This is a simaple user error, but i'm not sure how to fix.

Thx Adam

**Comment by dpomnean** [comment]
@ahamster13 Hey Adam, looks like you are missing part of the command. I would refer you to the readme, where it mentions what parameters you need in your docker command.

`docker run -it
-e USERNAME=email@address.com
-e PASSWORD=password_goes_here
-v "$(pwd)"/data:/data
-p 3000:3000
bropat/eufy-security-ws:latest`

**Comment by ahamster13** [comment]
Awesome Thanks. As i said really new to this and didn't know that all needed to be typed in the one statement.
