### ISSUE TITLE
Timeout connecting to station

### ISSUE THREAD

**Issue by Nusse469** [fuatakgun/eufy_security#700]
PLugin can't seem to talk to the Homebase and the logs are flooded with timeout messages

INFO  Timeout connecting to station (station id)
ERROR Station (station ID) - All address lookup tentatives failed.

**Comment by Nusse469** [comment]
Why is this closed when the problem still exists? If you plan to update this, it would be nice to know instead of just closing something without any sort of communication on my issue.

**Comment by fuatakgun** [comment]
https://community.home-assistant.io/t/eufy-security-integration/318353/1370?u=fuatakgun

**Comment by fuatakgun** [comment]
As you have the right to skip the bug template and go with your own version, i have the right to resolve it.
