### ISSUE TITLE
eufy cam streaming does not work with webrtc camera v3

### ISSUE THREAD

**Issue by lone-cloud** [fuatakgun/eufy_security#702]
I log this bug because the README recommends to use the WebRTC integration.
I updated to v3 this morning and the eufy cam streaming no longer works. I didn't notice any obvious errors in the log; however, the stream is forever stuck in its loading state for me.
v2 continues to work fine as expected.

**Comment by fuatakgun** [comment]
i don't have a solution in place and it is beyond my skills. I had experienced the same with v3 and sticking to v2 as of now

**Comment by haggis663** [comment]
This can be fixed by **installing the gortc addon or docker container**, deleting the webrtc integration and re-adding it pointing the configuration to the gortc URL.  There is no need to change the eufy config or camera cards at all

**Comment by apeeters** [comment]
@haggis663 thank you for pointing this out. Would it be possible to add more detailed configuration (maybe screenshots?). For example, gortc seems deprecated, do you use go2rtc?

**Comment by haggis663** [comment]
Yes, the image used is alexxit/go2rtc. 

I created a docker container based upon this image. The webrtc implementation doesn't have a config button, so it needs to be uninstalled and reinstalled. On reinstall, it asks for a URL  (given you an example) and this needs to point to the go2rtc container IP address and port. As I have set mygo2rtc  container up with an external IP address, there is not clash with the aler9/rtsp-simple-server container.

**Comment by BeHappy2021** [comment]
I can confirm the above fix works. Delete the WebRTC camera integration, then install the  [Go2RTC add-on](https://github.com/AlexxIT/go2rtc). Then reinstall WebRTC Camera. I also had to go to the RTSP Simple Server Add-on and change the port from 8554 as I got a message that it was already in use. I then went to the Eufy Security: Configuration and changed the TCP port there to match. Everything working now.

**Comment by nmeliasp** [comment]
apologize the ignorance here, where do you change the TCP port and do you change it to use 8554?

**Comment by BeHappy2021** [comment]
After you log in, go to Settings->Ad-ons->RTSP Simple Server Add-on and click on the Configuration tab. Scroll down to network and you'll find the place to change the port number. By default it uses 8554.

**Comment by nmeliasp** [comment]
Ok I didn't have that add-on installed. Is it required?
