### ISSUE TITLE
Host/Port is wrong.

### ISSUE THREAD

**Issue by Networkwilliams** [fuatakgun/eufy_security#706]
Installed using HACS on HA running Home Assistant 2023.1.7

Added the integration and on the first page used 127.0.0.1 and port 3000 and get error Host/Port is wrong.

**Comment by cdnninja** [comment]
Did you install the add on as well?

**Comment by xxDznutzxx** [comment]
I get the same thing, installed via hacs, restarted, installed rstp, go to add integration and run into same message which halts moving forward

**Comment by xxDznutzxx** [comment]
NVM somehow skimmed over the other add-on part, got it up and running TY

**Comment by Copper1971** [comment]
I have the same problem?

**Comment by cdnninja** [comment]
@Copper1971 we will need more details.    I assume you read my above question?

**Comment by Copper1971** [comment]
Sorry I am new with Home Assistant..
I installed the addon via the HACS..
Then I add the EUFY interation...
Then I was asked to enter Host and Port...
I used the default and get the error Host/port is wrong

**Comment by cdnninja** [comment]
HACS is the integration.  Not the add on.  Go back and read the install instructions and install the add on.   This should solve your issue.

**Comment by Copper1971** [comment]
Thank you for your feedback.
You are right I only Installed the integration -> Point 3 in the instruction.
I will try to mange also 1 and 2
Sorry for your efforts...

**Comment by Copper1971** [comment]
Now I have the integration running and the camera is integrated in HA.
Thank you.

Only topic is no picture. The state is inactive !?

**Comment by cdnninja** [comment]
I would encourage you to open an issue for that.   This topic was for port errors.
