### ISSUE TITLE
Captcha image is not showing: Translation Error: The intl string context variable "captcha_img" was not provided to the string "{captcha_img}"

### ISSUE THREAD

**Issue by sagilo** [fuatakgun/eufy_security#707]
**Describe the bug**

After HA is starting, Im clicking the "reconfigure" button and get an error about the captcha translation instead of seeing the captcha image I guess?
<img width="299" alt="image" src="https://user-images.githubusercontent.com/5019344/213986929-1deb69c5-5158-4211-96db-b882d9177ff3.png">

<img width="631" alt="image" src="https://user-images.githubusercontent.com/5019344/213987091-4e8976f7-0a70-4abe-9e95-81f61f2c41a8.png">

**To reproduce**

1. Enable MFA
2. Install the addon
3. Configure the addon
4. restart HA
5. Click "reconfigure"

**Expected behavior**

See a catcha image? 

**Additional information**

Relevant log:
```
2023-01-23 13:18:21.667 DEBUG (MainThread) [custom_components.eufy_security.config_flow] eufy_security async_step_reauth_confirm - Config(host='127.0.0.1', port=3000, sync_interval=600, rtsp_server_address='192.168.68.121', rtsp_server_port=8554, ffmpeg_analyze_duration=1.2, generate_ffmpeg_logs=False, no_stream_in_hass=False, name_for_custom1='Custom 1', name_for_custom2='Custom 2', name_for_custom3='Custom 3', captcha_id=None, captcha_img=None, captcha_input=None, mfa_required=True, mfa_input=None)
```

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Core container
- Home Assistant Core Version: 2023.1.1
- Eufy Security Add-on Version: 6.2.0
- Eufy Security Integration Version: 1.3.0

**Comment by denman1991** [comment]
Same here. Also with account without 2FA

**Comment by Eil0** [comment]
I have the same issue

Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
Eufy Security Add-on: 1.3.0

**Comment by patrickli** [comment]
Have the same issue. With MFA turned on the captcha will show but once entered it results in an "Unknown" error. Similar to #719 and #722.

**Comment by indyjonesuk** [comment]
Any updates please? Is this an outcome of Eufy tightening up security ?

**Comment by manumora** [comment]
I have the same issue

**Comment by pdm0** [comment]
Same issue here. Additionaly trying to resubmitt the Integration setup throws an error "User input malformed: expected bool for dictionary value @ data['generate_ffmpeg_logs']"

**Comment by dai80027** [comment]
Translation Error: The intl string context variable "captcha_img" was not provided to the string "{captcha_img}"

Same issue here.

**Comment by Rodeveer** [comment]
Running into the same problem.

@denman1991 you said after some trial and error it worked. What did you do exactly? A reinstall is not working atleast.

**Comment by handle9** [comment]
Same issue for me

**Comment by Sabream** [comment]
got the same problem... did you solve it somehow?

**Comment by beansidhe** [comment]
having 2FA turned on you need to give your email address to EUFY, 
and when you see the captcha error, check your email there should be a code from EUFY.
thats how it worked for me at least

**Comment by pdm0** [comment]
> having 2FA turned on you need to give your email address to EUFY, and when you see the captcha error, check your email there should be a code from EUFY. thats how it worked for me at least

Except when that doesn't work which is about 80% of the time for me... I am solving this by selling all my Eufy kit, I am sick of the issues like this and being lied to about security and the location of my data.

**Comment by mploetner** [comment]
same problem here with 2023.5.0b6

no matter if MFA is activated or not. even reinstalling integration does not help

**Comment by iwilltry42** [comment]
> I saw the same message and just put in the 2FA code a few times... didn't work. Then I did the same via mobile app and it just worked (same error message was showing there). Doesn't really make sense to put the 2FA in the captcha field, but there was no image showing anyway and it worked +1

Just adding to it. Up to this time it always works putting the 2FA code into the text field when seeing this issue.
It's easy to replicate for me right now. Obviously sometimes I just don't get a notification when this is required and then the code already expired in the meantime, that's annoying, but also fixed by restarting the eufy service.

**Comment by mploetner** [comment]
> > I saw the same message and just put in the 2FA code a few times... didn't work. Then I did the same via mobile app and it just worked (same error message was showing there). Doesn't really make sense to put the 2FA in the captcha field, but there was no image showing anyway and it worked +1
> 
> 
> 
> Just adding to it. Up to this time it always works putting the 2FA code into the text field when seeing this issue.
> 
> It's easy to replicate for me right now. Obviously sometimes I just don't get a notification when this is required and then the code already expired in the meantime, that's annoying, but also fixed by restarting the eufy service.

What 2FA code are you referring to? The one you receive when you change something? How do you trigger to get one?

**Comment by fuatakgun** [comment]
this should be fixed
