### ISSUE TITLE
Log Time is not correct

### ISSUE THREAD

**Issue by Ringo982** [fuatakgun/eufy_security#708]
Hi everyone
the problem is simple and i have not any other way to describe it:
The time that the log page of the add-on is showing is not correct, like it is not synchronized with the HA system time.
I'm Italian and it seems it is not taking consideration of the daylight saving... 
I noticed that because i have an automation that every morning at 7am do a specific task on my cameras, but looking into the add-on logs i see that the record about that specific task is marked at 6am.
But i'm sure the task is executed at 7am, i verified today and looking into the entity history the task is executed also at 7am.
I'm sure i set up the automation a lot of time ago, when the time was 1 hour back, so it is like the add-on log is considering the old time and not the actual one... after the daylight time switch
It is possible???

This is a problem when you are doing troubleshooting because you have to keep in mind this and you have to think in which period of the year you are at the moment to understand the correct time.

Thanks
Francesco

**Comment by fuatakgun** [comment]
Log times are usually utc.
