### ISSUE TITLE
Thumbnail / Camera preview is weird

### ISSUE THREAD

**Issue by fredim** [fuatakgun/eufy_security#709]
I have - 
  T8010 Base
  T8210 Doorbell Camera

I've been through the docs and I think the install went pretty well, actually. I used the sample code to enable streaming and I can view the active stream when I click into the camera component.

**Describe the bug**
The "last saved image" that shows up in the camera component is almost entirely grey. And, when streaming is running, that window stays grey (doesn't show the live stream).

**To reproduce**

1. Go to Settings -> Devices -> Eufy -> pick the camera
2. The preview circle is grey (image 1)
3. Click on "Start P2P Streaming"
4. The preview circle remains grey
5. Click on the camera entity
6. The video window pops open, and the video shows! (image 2)
7. Also attached, the image that shows up on preview in a dashboard. It looks entirely grey, but I think there is some slight discoloration, like the image that was processed was just a little off.

**Expected behavior**

The image to show, and the video preview to show in the dashboard without clicking through.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS
- Home Assistant Core Version: core-2023.1.7
- Eufy Security Add-on Version:  1.3.0 
- Eufy Security Integration Version: v6.2.0

Hardware Information;
- Camera Model: 8210

- Live Streaming Protocol (RTSP/P2P): P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- 

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Additional context**
<img width="727" alt="2 - video view" src="https://user-images.githubusercontent.com/431610/214630110-137f3ea3-4116-4adb-b523-a06c3e4607b1.png">
<img width="1035" alt="1 - device settings" src="https://user-images.githubusercontent.com/431610/214630137-fa7ba35c-6490-4fa3-ac70-5a50a6d27a59.png">
<img width="363" alt="3 - preview image" src="https://user-images.githubusercontent.com/431610/214630145-97dac12a-ebd4-447e-8f6b-20cfeec06b5b.png">

**Comment by Sierek** [comment]
Exactly the same is happening to me. Sometimes the image contains some blurry elements.

**Comment by mced76** [comment]
Same issue with Eufy doorbell

**Comment by Sierek** [comment]
I did not write. I also have 
T8010 Base
T8210 Doorbell Camera

**Comment by Sierek** [comment]
This is the view of the figure that passed in front of the gate cameras. What's wrong with image generation from a video fragment.

![image](https://user-images.githubusercontent.com/61333263/216368254-398a8548-4880-4815-ad3d-270618b5bbcb.png)

**Comment by gerardsyd** [comment]
I have the same issue too, looks grey. it was working a few updates ago but seems to have stopped. Anybody got it fixed? Stream seems to be working so appears to be an issue with image capture.

**Comment by stefanlambert** [comment]
I have the same issue, video stream is fine but image capture is grey.

**Comment by fuatakgun** [comment]
please share your cameras following README and I will take a look
