### ISSUE TITLE
Unable to setup via Docker: Response data is missing

### ISSUE THREAD

**Issue by skyler91** [fuatakgun/eufy_security#710]
**Describe the bug**

I'm setting up a new installation using docker-compose, but the Eufy integration fails initialization. In the eufy-security-ws logs, I see a repeating error:

> eufy_1           | 2023-01-26 06:49:44.940  ERROR Response data is missing 
> eufy_1           | {
> eufy_1           |   code: 0,
> eufy_1           |   msg: 'Succeed.',
> eufy_1           |   data: undefined
> eufy_1           | }
> eufy_1           | 2023-01-26 06:49:57.359  INFO  Client disconnected with ip: 172.19.0.1 port: 49110 code: 1000 reason: Normal Closure

**To reproduce**

Configured eufy security container in docker-compose:

>   eufy:
>     image: bropat/eufy-security-ws:1.3.0
>     environment:
>       - USERNAME=MY_USERNAME
>       - PASSWORD=MY_PASSWORD
>       - COUNTRY=US
>     ports:
>       - 3000:3000

**Additional information**

Version | core-2023.1.7
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.7
Operating System Family | Linux
Operating System Version | 5.15.0-58-generic
CPU Architecture | x86_64

- Eufy Security Add-on Version: 1.3.0
- Eufy Security Integration Version:

Hardware Information;
- Camera Model: Multiple doorbell cameras (T8210) + lock

- Live Streaming Protocol (RTSP/P2P): RTSP

- Debug Logs from Home Assistant

> homeassistant    | 2023-01-25 23:00:29.211 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - config class initialized
> homeassistant    | 2023-01-25 23:00:29.211 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - set_ws - connect
> homeassistant    | 2023-01-25 23:00:29.322 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_open - executed
> homeassistant    | 2023-01-25 23:00:29.322 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - WebSocket message sent. {"messageId": "start_listening", "command": "start_listening"}
> homeassistant    | 2023-01-25 23:00:29.322 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - WebSocket message sent. {"messageId": "set_api_schema", "command": "set_api_schema", "schemaVersion": 11}
> homeassistant    | 2023-01-25 23:00:29.322 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - WebSocket message sent. {"messageId": "driver_connect", "command": "driver.connect"}
> homeassistant    | 2023-01-25 23:00:29.322 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - wait start - driver_connected
> homeassistant    | 2023-01-25 23:00:29.322 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - process_messages started
> homeassistant    | 2023-01-25 23:00:29.324 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'result', 'success': True, 'messageId': 'start_listening', 'result': {'state': {'driver': {'version': '2.4.0', 'connected': False, 'pushConnected': False}, 'stations': [], 'devices': []}}}
> homeassistant    | 2023-01-25 23:00:29.326 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'result', 'success': True, 'messageId': 'set_api_schema', 'result': {}}
> homeassistant    | 2023-01-25 23:00:29.573 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - wait finish - driver_connected - return True
> homeassistant    | 2023-01-25 23:00:29.573 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - connect - async_driver_connect True - {'host': '0.0.0.0', 'port': 3000, 'sync_interval': 600, 'use_rtsp_server_addon': False, 'rtsp_server_address': '0.0.0.0', 'rtsp_server_port': 8554, 'ffmpeg_analyze_duration': 1.2, 'auto_start_stream': True, 'fix_binary_sensor_state': False, 'map_extra_alarm_modes': False, 'name_for_custom1': 'Custom 1', 'name_for_custom2': 'Custom 2', 'name_for_custom3': 'Custom 3', 'generate_ffmpeg_logs': False}
> homeassistant    | 2023-01-25 23:00:29.573 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - wait start - required
> eufy_1           | 2023-01-26 07:00:29.659  ERROR Response data is missing 
> eufy_1           | {
> eufy_1           |   code: 0,
> eufy_1           |   msg: 'Succeed.',
> eufy_1           |   data: undefined
> eufy_1           | }
> homeassistant    | 2023-01-25 23:00:29.660 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'result', 'success': True, 'messageId': 'driver_connect', 'result': {}}
> homeassistant    | 2023-01-25 23:00:42.126 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - wait finish - required - return False
> homeassistant    | 2023-01-25 23:00:42.126 WARNING (MainThread) [custom_components.eufy_security] eufy_security - no devices available yet
> homeassistant    | 2023-01-25 23:00:42.127 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - connect - async_start_listening False - {'host': '0.0.0.0', 'port': 3000, 'sync_interval': 600, 'use_rtsp_server_addon': False, 'rtsp_server_address': '0.0.0.0', 'rtsp_server_port': 8554, 'ffmpeg_analyze_duration': 1.2, 'auto_start_stream': True, 'fix_binary_sensor_state': False, 'map_extra_alarm_modes': False, 'name_for_custom1': 'Custom 1', 'name_for_custom2': 'Custom 2', 'name_for_custom3': 'Custom 3', 'generate_ffmpeg_logs': False}
> homeassistant    | 2023-01-25 23:00:42.128 WARNING (MainThread) [homeassistant.config_entries] Config entry '0.0.0.0' for eufy_security integration not ready yet: Start Listening was not completed in timely manner; Retrying in background
> homeassistant    | 2023-01-25 23:00:42.128 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - WebSocket Connection Closed. <Task finished name='Task-2419' coro=<EufySecurityWebSocket.process_messages() done, defined at /config/custom_components/eufy_security/websocket.py:53> result=None>
> eufy_1           | 2023-01-26 07:00:42.131  INFO  Client disconnected with ip: 172.19.0.1 port: 53408 code: 1000 reason: Normal Closure 
> homeassistant    | 2023-01-25 23:00:42.129 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - WebSocket Connection Closed. <bound method EufySecurityDataUpdateCoordinator.on_close of <custom_components.eufy_security.coordinator.EufySecurityDataUpdateCoordinator object at 0x7f5cd83cee00>>
> homeassistant    | 2023-01-25 23:00:42.129 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_close - executed

**Additional context**

This was working with a previous installation of Home Assistant back in December.

**Comment by fuatakgun** [comment]
Trusted device name is s mandatory attribute
