### ISSUE TITLE
Eufy streaming not working

### ISSUE THREAD

**Issue by bjarnekrottje** [fuatakgun/eufy_security#711]
**Describe the bug**

When trying to start the stream, I get an error and the streaming is not started.

**To reproduce**

1. Execute the Camera: Turn On service call
2. See the error in the logs

**Expected behavior**

Expected the streaming to just work

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: core-2023.1.7
- Eufy Security Add-on Version: 1.3.0
- Eufy Security Integration Version: 6.2.0
- RTSP Simple Server Add-on: 0.17.6

Hardware Information;
- Camera Model: T8210

- Live Streaming Protocol (RTSP/P2P): RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
```
Logger: custom_components.eufy_security.eufy_security_api
Source: custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py:107
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 10:46:28 (1 occurrences)
Last logged: 10:46:28

Exception [Errno 32] Broken pipe - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py", line 103, in setup client_socket.sendall(bytearray(self.camera.video_queue.get())) BrokenPipeError: [Errno 32] Broken pipe
```

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
```
2023-01-26 09:42:02.863  WARN Station T*************** - Heartbeat check failed. Connection seems lost. Try to reconnect... 
2023-01-26 09:42:02.865  INFO  Disconnected from station T*************** 
2023-01-26 09:42:23.045  WARN Station T*************** - Tried all hosts, no connection could be established 
2023-01-26 09:42:23.048  INFO  Timeout connecting to station T*************** 
2023-01-26 09:42:33.095  INFO  Connected to station T*************** on host **.**.***.*** and port 18932 
2023-01-26 09:42:57.571  INFO  Client disconnected with ip: 172.30.32.1 port: 40356 code: 1006 reason: Abnormal Closure 
2023-01-26 09:43:36.679  INFO  Disconnected from station T*************** 
2023-01-26 09:43:41.730  INFO  Connected to station T*************** on host **.**.***.*** and port 17811 
2023-01-26 09:44:45.261  INFO  Disconnected from station T***************
2023-01-26 09:44:50.309  INFO  Connected to station T*************** on host **.**.***.*** and port 18054 
2023-01-26 09:45:53.840  INFO  Disconnected from station T***************
2023-01-26 09:45:58.896  INFO  Connected to station T*************** on host **.**.***.*** and port 23542 
```

- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Comment by fuatakgun** [comment]
https://community.home-assistant.io/t/eufy-security-integration/318353/1370?u=fuatakgun

**Comment by bjarnekrottje** [comment]
First of all of course thank you @fuatakgun for your work on this integration. I have loved it thus far very much.
However I can't seem to find this specific issue on the open issues. I found something on a closed issue, however it seems the issue should have been resolved in #580. Could you point me in the right direction as to how to fix this issue?
As far as I know I have followed your issue template, but please let me know if I can clarify something.
Thank you very much in advance.

**Comment by Daneish** [comment]
Are you using the WebRTC integration, and is your RTSP Simple Server Add-on started?

**Comment by bjarnekrottje** [comment]
Hi @Daneish, thanks for your reaction. 

The WebRTC integration is configured and using 'localhost:1984' as its address (as configured by default).

My RTSP Simple Server Add-on is started with a different port (since it otherwise conflicts with the WebRTC integration).
```pwsh
2023/02/07 10:48:28 I [0/0] rtsp-simple-server v0.17.6
2023/02/07 10:48:28 I [0/0] [RTSP] TCP listener opened on :8554
2023/02/07 10:48:28 I [0/0] [RTMP] listener opened on :1935
2023/02/07 10:48:28 I [0/0] [HLS] listener opened on :8888
```

The go2rtc Add-on is also started
```pwsh
11:50:47.132 INF go2rtc version 1.1.1 linux/arm64
11:50:47.134 INF [api] listen addr=:1984
11:50:47.134 INF [rtsp] listen addr=:8554
11:50:47.136 INF [srtp] listen addr=:8443
11:50:47.136 INF [webrtc] listen addr=:8555
```

And lastly I have also configured the RTSPtoWebRTC integration which uses 'http://localhost:1984' as its server url.

**Comment by fuatakgun** [comment]
Did you also configure eufy security integration for correct rtsp add on port?

**Comment by bjarnekrottje** [comment]
Thank you @fuatakgun. It was on some random port (8534) which I don't recognise. That did the trick on the streaming in any case.
