### ISSUE TITLE
Timeout on /addons/3a26b21d_eufy_security_addon/stats request

### ISSUE THREAD

**Issue by zelloxy** [fuatakgun/eufy_security#715]
**Describe the bug**

I can't get setup to work after upgrading HASS.

I get the error in my log:
2023-01-31 08:16:15.313 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/3a26b21d_eufy_security_addon/stats request
2023-01-31 08:16:15.475 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/3a26b21d_eufy_security_addon/stats - 

**To reproduce**

Can't really.

**Expected behavior**

I excpet the integration to fetch my devices and it's entities

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Installation Type	Home Assistant OS
- Home Assistant Core Version: core-2023.1.7
- Eufy Security Add-on Version: 1.3.0
- Eufy Security Integration Version: Can't see this

- Would you share your device with me in case further debugging required? (Yes/No): yes

**Comment by akicker** [comment]
Same Problem after updating HACS to 1.30.1

**Comment by akicker** [comment]
got it working again - dont know if all these steps were necessary - but finally it was succesful!
after updating Home Assistant to 2023.2.1 and MariaDB to 2.5.2 i did remove:
delete Eufy Security Integration
deinstall Eufy Security Add-on
delete Repository: Eufy Security WS Addon
restart Home Assistant
Add Eufy Security Add-On Repository again (https://github.com/fuatakgun/eufy_security_addon)
restart Home Assistant
install Eufy Security Add-on
setup Configuration: Username, Password, Country and Trusted Device Name.
shutdown (System - Hardware - Shutdown System) 
reboot Home Assistant (power off - on)
install Eufy Security Integration
and Eufy Security is working again :-)
