### ISSUE TITLE
 Last Camera Picture URL Unknown

### ISSUE THREAD

**Issue by reecedavies86** [fuatakgun/eufy_security#717]
Hello I cannot see the issue opened here so I thought i'd raise it.

Thumbnail not working for some time. Just a grey error img.

I understand EUFY has changed their back end and a google search suggests streaming and capturing which I have implemented but is it not reliable and misses the subject which triggered the record.

Summary: URL for image missing. HA not displaying.

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security#start-streaming-on-camera-when-there-is-a-motion-this-would-generate-a-new-thumbnail-on-home-assistant

**Comment by fuatakgun** [comment]
But there is no fix
