### ISSUE TITLE
Captcha fails with "unknown error"

### ISSUE THREAD

**Issue by joeinaustin** [fuatakgun/eufy_security#718]
**Describe the bug**

New install of this add on, cannot get past the captcha.  It always fails with "unknown error".  At some point, it fails to offer new attempts unless host is restarted.  This is an endless cycle of failure

**To reproduce**

**Expected behavior**

Enter captcha, finish install

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

- Eufy Security Add-on Version: latest
- Eufy Security Integration Version: latest

Hardware Information;
- Camera Model:  2K doorbell

- Live Streaming Protocol (RTSP/P2P): 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- 

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No): 

**Additional context**

Add any other context about the problem goes here.

**Comment by fuatakgun** [comment]
Closing due to missing logs

**Comment by joeinaustin** [comment]
[3a26b21d_eufy_security_addon_2023-02-02T02-46-49.297Z.log](https://github.com/fuatakgun/eufy_security/files/10564312/3a26b21d_eufy_security_addon_2023-02-02T02-46-49.297Z.log)


Log attached.
