### ISSUE TITLE
"Unknown" captcha error. 

### ISSUE THREAD

**Issue by joeinaustin** [fuatakgun/eufy_security#719]
Closing due to missing logs

_Originally posted by @fuatakgun in https://github.com/fuatakgun/eufy_security/issues/718#issuecomment-1412541544_
            
Can you reopen the old issue?  Logs were uploaded.  I only see something about my "account has not been activated".  Not sure what that means since I am using the same creds that work using the eufy app.

**Comment by joeinaustin** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/11775403/217116268-dc57c373-23c5-4ec7-a94f-b4b343c3e781.png">

**Comment by DUC750** [comment]
same here:
![image](https://user-images.githubusercontent.com/24934253/218431110-6fe24ea9-97a2-40aa-9f72-d8f6d93fdcf3.png)

[FYI] Captcha changed

**Comment by TwitchingAstronaut** [comment]
I'm having this same error, i posted about it on the Homeassistant Forum

https://community.home-assistant.io/t/eufy-security-integration/318353/1447?u=twitchingastronaut

i can repost here if you would like

**Comment by Rubl80** [comment]
Same issue. After a few try I also get this error. 
![Skærmbillede 2023-02-19 kl  18 46 36](https://user-images.githubusercontent.com/39396970/219965604-4e3dc819-4e5f-419a-9956-566ffa1a5a8c.png)

If I restart HA I can try captcha a few times, but will get error "Unknown error occurred", as you have shown on screenshot

**Comment by Rubl80** [comment]
After disabling 2FA in the Eufy app, I got it working. But hope it can work again with 2FA someday.

**Comment by TwitchingAstronaut** [comment]
with or without 2FA enabled, i still get the Unknown Captcha error

**Comment by DUC750** [comment]
The same problem here. It doesn't load the captcha at all, so I can't even enter it. It is not a 2FA problem for me, but a display problem of the captcha. I've already tried it through the app (Android) and with different browsers (Edge + Chrome).

**Comment by batrat78** [comment]
Has anyone found the solution to this… it’s getting frustrating??

**Comment by DUC750** [comment]
Unfortunately, I don't. Unfortunately, there seems to be no interest in fixing the problem either.

**Comment by batrat78** [comment]
Such a shame as I know I can integrate with HomeKit but I don’t want to …

**Comment by DUC750** [comment]
Yesterday my echo told me he found a new device "doorbell". I have no idea what has changed, but my doorbell has integrated itself. It must be magic.

**Comment by JaisalSingh** [comment]
OK, so after hours of troubleshooting. I found a way to make it work. 

Steps:
1. Disable 2FA
2. Restart Home Assistant
3. Go to Settings > Addons > eufy-security-ws
4. In the configuration tab, Enable Debug
5. Go to the integrations menu (Settings > Devices and Services > Integrations)
6. Reconfigure
7. Enter the Captcha
8. If you get the "unknown error" message
9. Restart HA once again
10. Go to Settings > Addons > eufy-security-ws
11. Go to the logs tab, and check if there is anything about Captcha or 2FA (there shouldn't)

If everything went well, you should be seeing logs about "DATA CONTROL - received from host" meaning that the login was successful and the connection has been made. 

To note: I tried enabling 2FA after getting this to work and it didn't cause any issues.

**Comment by beansidhe** [comment]
having 2FA turned on you need to give your email address to EUFY, 
and when you see the captcha error, check your email there should be a code from EUFY.
thats how it worked for me at least

**Comment by shortie292914** [comment]
> OK, so after hours of troubleshooting. I found a way to make it work.
> 
> Steps:
> 
> 1. Disable 2FA
> 2. Restart Home Assistant
> 3. Go to Settings > Addons > eufy-security-ws
> 4. In the configuration tab, Enable Debug
> 5. Go to the integrations menu (Settings > Devices and Services > Integrations)
> 6. Reconfigure
> 7. Enter the Captcha
> 8. If you get the "unknown error" message
> 9. Restart HA once again
> 10. Go to Settings > Addons > eufy-security-ws
> 11. Go to the logs tab, and check if there is anything about Captcha or 2FA (there shouldn't)
> 
> If everything went well, you should be seeing logs about "DATA CONTROL - received from host" meaning that the login was successful and the connection has been made.
> 
> To note: I tried enabling 2FA after getting this to work and it didn't cause any issues.

I’ve tried this but had some issues. I found out that you should create a separate account and link it to your main eufy account. Worked great once I found this out!
