### ISSUE TITLE
State person detect "True" until motion is detected

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#72]
Hi,
yesterday I saw that the person detector in Home Assistant is activated for a few seconds when it detects the passage of a human and then returns to the state of "False".

The second state of "True", on Home Assistant, is shown only about 30 seconds after the cam stops detecting motion.

If the person remains in front of the webcam for several minutes, the home assistant always shows the sensor in the "False" state.

Would it be possible to show the "True" status of the Person Detector sensor on Home Assistant for as long as the person is in the room (or for as long as the video is recorded on the Eufy app)?

Thanks

**Comment by SmartM-ui** [comment]
> Hey, about these sensors, Eufy is just pushing a notification event and i am generating a fake 10 seconds event in home assistant. We actually do not know the duration of event, it is an instantaneous notification about exact time, not interval. So, technically we don't have this data

Hi @fuatakgun 
Is there the sensor that indicates if the cam is recording?
If you managed to create it, you could force the sensor status reading until it returns to false and pair it with the motion sensor

**Comment by SmartM-ui** [comment]
> i have created a sensor when camera is streaming, but there is no way to have a sensor based on `if camera is actively recording`

Can't retrieve the video recording name sensor, with the video recording time, as is the case for photographs?

**Comment by KyriosYuudai** [comment]
Hate to piggy back off the thread but this seemed similiar. I'm having an issue where motion detected and person detected never update. I created an automation that calls browser mod to open the stream as a popup on our central tablet.... but without state change i cant get it to trigger.

FYI, Streams are working great! love the addon

![image](https://user-images.githubusercontent.com/50720985/137008668-abc2702a-0516-4632-b11d-b69723871a98.png)

![image](https://user-images.githubusercontent.com/50720985/137008733-0656ff48-a31d-49b6-8db6-67d84858f586.png)

**Comment by fuatakgun** [comment]
Yes, this is totally unrelated :-) just check this: https://github.com/fuatakgun/eufy_security/issues/22

**Comment by fuatakgun** [comment]
resolving due to inactivity
