### ISSUE TITLE
Configuration wizard not loading

### ISSUE THREAD

**Issue by IeuanK** [fuatakgun/eufy_security#721]
**Describe the bug**

Configuration wizard is stuck on "Please wait, starting configuration wizard for Eufy Security"

![image](https://user-images.githubusercontent.com/1075598/216359436-d9359854-26c9-4ca9-8c08-9e6df1f0313c.png)

**To reproduce**

1. Go to Integration
2. Click on Add Integration
3. Search for & click on Eufy Security

**Expected behavior**

Config wizard should pop up I guess?

**Additional information**

**Version** core-2023.2.0  
**Installation Type** Home Assistant OS  
Eufy Security Add-on (1.3.0), RTSP Simple Server Add-on (v0.17.6)  
**Integration version** v6.2.0  

Eufy Security add-on logs:  
```
2023-02-02 16:28:55.828  INFO  Authentication properties changed, invalidate saved cloud token. 
2023-02-02 16:28:59.804  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-02-02 16:29:09.938  INFO  Connected to station <station ID> on host 192.168.2.63 and port 15948 
2023-02-02 16:29:12.860  INFO  Push notification connection successfully established  
```  

Home Assistant logs show nothing related to Eufy Security  

I have shared my device to a separate account and confirmed it works in the Eufy app  

- Would you share your device with me in case further debugging required? (Yes/No):  
If required, I can, but I don't think we're even at that point yet

**Comment by IeuanK** [comment]
Had to leave it on, took a solid 5 minutes to load the wizard but it eventually did. Then just had to submit (using the add-on, so IP and port were auto filled correctly) and done.

**Comment by ianatha** [comment]
While loading the configuration wizard, the POST to `api/config/config_entries/flow` with `{"handler":"eufy_security","show_advanced_options":true}` seems to be taking forever--more than 15 minutes, spinner is still spinning--on my installation.

(Exact same versions.)

**Comment by dvincentnok** [comment]
I see this too, but it seems to timeout after 20min...
![Screen Shot 2023-02-25 at 4 31 29 PM](https://user-images.githubusercontent.com/48769401/221380545-2bbd107f-9011-4b73-b814-922416e172c0.png)

**Comment by CatHead132** [comment]
![image](https://github.com/user-attachments/assets/1cd6a452-5449-419d-bf87-e6e095b3da96)
