### ISSUE TITLE
Streaming multiple cameras simultaneously doesn't work

### ISSUE THREAD

**Issue by kanzn** [fuatakgun/eufy_security#723]
Hi,
I can stream one camera normally in a home assistant dashboard, but when I call a service to turn on another camera (in the same homebase), the first one stop streaming. I think there are a problem somewhere, because I can stream two cameras in the same time, using eufy app (obviously using two different phones)

I have eufyCam 2C

Thank you

**Comment by fuatakgun** [comment]
Home assistant add-on is acting as one mobile app from one phone, so that is working as it is by design.

I cannot change it

**Comment by kanzn** [comment]
I'll formulate my problem otherwise, I want to display multiple cameras in the same dashboard, it's possible with different model like  Cam pan&tilt and one Cam C2, but no with many Cam C2.

**Comment by fuatakgun** [comment]
Pan and tilt cameras are both acting as station and camera, they don't need homebase, they are streaming using their hardware over rtsp.

if c2 is using p2p streaming, it is limited with one app one streaming.
