### ISSUE TITLE
Eufy cameras Wireless Integrates but without image. 

### ISSUE THREAD

**Issue by NunoMCMoreira** [fuatakgun/eufy_security#724]
Hi everyone, 

I did this integration few months ago, and for some reason it stopped.

yesterday I did it again and the cameras was integrated however won't show me image.

someone could help me please?

![image](https://user-images.githubusercontent.com/113090012/216759781-f41552ac-8e5a-4217-90e1-7057d6cfbcd1.png)

![image](https://user-images.githubusercontent.com/113090012/216759789-fccf111a-fd84-413b-915d-9e1fe1a6ac49.png)

![image](https://user-images.githubusercontent.com/113090012/216759819-145dad2b-f399-4e6d-87f8-fa056d82c689.png)

**Comment by davidjac** [comment]
Same here for around a month

**Comment by oystersoft** [comment]
Same here ...
Model No. T8210 Ver. 1.1.2.3

**Comment by leonardpitzu** [comment]
It's supposed to be like this as a constant stream would kill the battery much faster.
Scroll a bit down - it should look like this:
<img width="329" alt="Screenshot 2023-02-06 at 10 15 43" src="https://user-images.githubusercontent.com/4321813/216919595-ef1d4eb7-7206-4e0c-9a11-c45cdf103d97.png">
You need to manually start (and in the end stop) the stream.
You can add buttons and make it look like this:
<img width="505" alt="Screenshot 2023-02-06 at 10 15 59" src="https://user-images.githubusercontent.com/4321813/216919734-52ddd8e9-c841-4bba-80f3-d06199c658d4.png">

**Comment by NunoMCMoreira** [comment]
I'll have a look this afternoon, thanks for your help,

I was expecting it like showing the last motion detection recorded as before

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by davidjac** [comment]
I'm not looking for constant stream but used to get a snapshot from last trigger. Don't get that anymore.

**Comment by NunoMCMoreira** [comment]
Like I'm looking as well, I want the image updated every time that it detects motion

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jhalak1984** [comment]
I too am looking at this. I have had this integration for more than a year and suddenly now that it stopped, can't make it work. 

I am not looking to stream all the time either, I just want the snapshot of last motion triggered to appear on the card which was the case before.

Been reading up on this issue for a long time and someone pointed out that it might be because of Pi-hole or similar DNS blocker is creating this issue. Eufy basically needs access to google but then my Pi-hole doesn't block anything google related.

**Comment by fuatakgun** [comment]
@NunoMCMoreira https://github.com/fuatakgun/eufy_security#start-streaming-on-camera-when-there-is-a-motion-this-would-generate-a-new-thumbnail-on-home-assistant

**Comment by davidjac** [comment]
I'm a little unclear. Is the original version now not working and its recommended to use the new Alpha?

**Comment by jhalak1984** [comment]
Exactly, so what happened to the original version that was working for so long? Is that not going to come back? 

Also the code that generates the snapshot when motion detects, isn't working for me. I get this 'Error : end of the stream or a document separator is expected'. I am no programmer, so all I am doing is copying and pasting, Could someone answer what might be the issue for me?

**Comment by moishap** [comment]
I followed installation instructions, the README dashboard panels examples and the referenced above automation and I still not getting neither the thumbnails, nor the stream showing up. Originally when I set this up, I had both. Not after the update. Appears to be the same as the OP. What would be the steps to troubleshoot this ?

**Comment by buzurk26** [comment]
Im experiencing the same issue, used to work now stopped

**Comment by Lempomat** [comment]
I tested the automation. But sometimes it hungs. So I see P2P ist running but I cannot stop it. 

So it is not possible to use the screenshot from the eufy app? There I see the last motion on the camera. In a last version of this "eufy" integration it works fine. So why can we used it than before?

**Comment by spubanz** [comment]
Hi,
Same here - everything works, but the last camera picture URL doesn't seem to get updated.
<img width="417" alt="image" src="https://user-images.githubusercontent.com/12239843/219943264-95a6c8af-2259-42e6-bacd-17da4e869507.png">

Model: T8210 2k camera doorbell
Streaming works like a charme by the way.

**Comment by rpitera** [comment]
Add my voice to the chorus.  Worked fine since the initial install way back and then stopped providing thumbnails.  I thought that maybe it was due to the changes in security after the news broke about them and gave up for a while.  Then read in a reddit thread about someone having another issue and the respondent suggested a deletion and reinstall saying that he believed he had old code somewhere.

I did the reinstall and while anything that wasn't working well now worked, it still didn't solve my thumbnail issue.  At least I'm not alone... was planning on replacing a couple of cams with eufy units but holding off for now.

**Comment by Copper1971** [comment]
I have the same problem
No picture camera is idle
All my two cameras are detected, but no preview picture…

**Comment by kalez78** [comment]
the same: my two cameras are detected, but no preview picture…

**Comment by kalez78** [comment]
There is still something wrong. There are all entities and they work, There are all devices visible, but there is no preview from any of the cameras. Restarting the server and HA does not help.

**Comment by buzurk26** [comment]
> Someone mentioned conflicting ports recently, so I edited the integration and add-on with new unused ports, and I've had 3 days of working doorbell camera streams again!
> 
> I changed both the eufy add-on port and the rtsp add-on port. I believe you have to delete and re-add the eufy integration in order to change the main eufy port.

thanks for this, will try it

Was it the port 3000 and the port 8554 you changed? do i need to remove and reinstall?

**Comment by jhalak1984** [comment]
For me, I am able to press stream and then stream, but then after a while it automatically goes to idle and then cannot press stream again. I just get gray screen. And that, idle image issue is still there.

**Comment by chesterflaps** [comment]
I can press to stream but it either says it failed or it says it is streaming but I cannot see a video anywhere.

**Comment by chesterflaps** [comment]
> Add a stop and start button to your lovelace underneath. Next time you have the issue, try each button in different combinations until it works hopefully (triggering the eufy P2P service calls works for me, but the native stop/start camera service doesn't).

Sorry, I'm not sure what you mean by lovelace underneath. I do have a start p2p stream and stop p2p stream button but when i press the start one, the stream status says streaming and then i have to click on the camera at the top of the page, it opens up a video screen but it is blank and i cannot press play.

**Comment by Ascariota** [comment]
Same issue for me with T8210 model

**Comment by jhalak1984** [comment]
> Hi, Same here - everything works, but the last camera picture URL doesn't seem to get updated. <img alt="image" width="417" src="https://user-images.githubusercontent.com/12239843/219943264-95a6c8af-2259-42e6-bacd-17da4e869507.png">
> 
> Model: T8210 2k camera doorbell Streaming works like a charme by the way.
> 
> EDIT: Do I see this correct that it is turned off intentionally at the moment? <img alt="image" width="904" src="https://user-images.githubusercontent.com/12239843/219963408-476c52d1-8329-4347-9a4e-009fd9e14d89.png">

hmm, #709 , here it is mentioned that the preview stills works for them albeit not properly but still works. For me, without this feature, it is useless.

**Comment by jhalak1984** [comment]
#717 Fuatakgun himself has said this is not possible now.
