### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by RienduPre** [fuatakgun/eufy_security#725]
I get this in my log:

`2023-02-05 11:36:27.270  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
(node:10) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 station talkback start listeners added to [EufySecurity]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 station talkback stop listeners added to [EufySecurity]. Use emitter.setMaxListeners() to increase limit
2023-02-05 11:36:37.639  INFO  Connected to station T8010P2322412672 on host 192.168.0.50 and port 22457 
2023-02-05 11:36:41.479  INFO  Push notification connection successfully established 
2023-02-05 11:37:41.100  INFO  Disconnected from station T8010P2322412672 `

The emitter.setMaxListeners seems to be to low. Can I put this in Eufy Security Add-on yaml file?
If yes? Can you give me an example?

One minor point, My host and port are displayed incorrectly. It should be localhost and port 3200

-----------------------------
Eufy Security Add-on
Current version: 1.3.0

Versie | core-2023.2.2
-- | --
Type installatie | Home Assistant OS
Ontwikkeling | false
Supervisor | true
Docker | true
Gebruiker | root
Virtuele omgeving | false
Python-versie | 3.10.7
Besturingssysteem | Linux
Versie van het besturingssysteem | 5.15.90
CPU-architectuur | aarch64
Tijdzone | Europe/Amsterdam
Configuratiemap | /config

![Scherm­afbeelding 2023-02-05 om 12 59 29](https://user-images.githubusercontent.com/9009949/216817410-e22db90c-056d-492d-a64c-7b7e22d69380.png)

**Comment by BillyFKidney** [comment]
I am experiencing the same issue and started a discussion which has not been answered.
[https://github.com/fuatakgun/eufy_security/discussions/698#discussion-4772934](url)
