### ISSUE TITLE
Stream Errors in HA when viewing through HomeKit

### ISSUE THREAD

**Issue by leonardpitzu** [fuatakgun/eufy_security#73]
i have a Homebase2 and 2 Eufy cam 2 (regular, not pro). The cameras work as expected in their app as well as in HA. Whenever i try to view the cameras in HomeKit (exporte there by HA) i get these errors (and the image errors out in the HomeKit app in iOS):

`Logger: homeassistant.components.homekit.type_cameras
Source: components/homekit/type_cameras.py:456 
Integration: HomeKit (documentation, issues) 
First occurred: 9:33:04 AM (2 occurrences) 
Last logged: 9:35:39 AM

[1ec6a3c5-de47-4bf9-aa98-f1123c3ff9bb] Failed to kill stream
[e28ac066-fb39-4950-b7e2-cf8ecde308ab] Failed to kill stream
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_cameras.py", line 456, in stop_stream
    await getattr(stream, shutdown_method)()
  File "/usr/local/lib/python3.9/site-packages/haffmpeg/core.py", line 170, in kill
    self._proc.kill()
AttributeError: 'NoneType' object has no attribute 'kill' `

All versions are the latest stable releases. I have RTSP enabled and the accelerator set up.

**Comment by leonardpitzu** [comment]
OK, i’ll keep checking here for an update. I do noi have Alexa, i only use HomeKit to “get out” of my house and the rest is pretty much “offline”.

**Comment by leonardpitzu** [comment]
around 10 seconds i guess

**Comment by fuatakgun** [comment]
Can you give a try with latest version?

**Comment by fuatakgun** [comment]
resolving due to inactivity

**Comment by fuatakgun** [comment]
@leonardpitzu can you give it a try with latest integration and add-on version?

**Comment by leonardpitzu** [comment]
I have no video stream in HA and i get the following error:
`http://192.168.0.10:8123/api/camera_proxy/camera.living_room_terase?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1ODQwNzMyM2NmZDY0OGJhOTQyOGFjZTE5ZDQ4ODdkNSIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEubGl2aW5nX3Jvb21fdGVyYXNlIiwiaWF0IjoxNjM3MjIwMTg1LCJleHAiOjE2MzcyMjAyMTV9.3jWNLAoiZyfnqAVo0bDhrxYcKkCKLXhN9HBs4qj_4dA&width=1856&height=1044
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
`

**Comment by fuatakgun** [comment]
Can you check integration configuration if `auto start stream on click` is enabled. İt is needed in your case

**Comment by leonardpitzu** [comment]
It is enabled and still not working. I will try to delete the integration and start from scratch to see if it helps.

**Comment by leonardpitzu** [comment]
removed everything from HA, restarted HA and regenerated everything (docker, etc). it does not want to play an image...

**Comment by air720boarder** [comment]
Any updates here? It seems somewhat unusable to have to trigger to start streaming, then view the cam, then remember to turn off the stream.
