### ISSUE TITLE
Missing text in configuration dialog (maybe translation related)

### ISSUE THREAD

**Issue by eikowagenknecht** [fuatakgun/eufy_security#732]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1475672/217498581-b7e96430-1e3d-44ed-a6f0-f7cb91a52702.png)

**To reproduce**

1. (Switch HA to german)
2. Configure integration
3. See missing textbox

**Expected behavior**

Text is shown.

**Additional information**

- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: 2023.2
- Eufy Security Integration Version: 6.2.0

**Comment by fuatakgun** [comment]
Please raise a pr to change this
