### ISSUE TITLE
Starting a recording on the camera's SD card

### ISSUE THREAD

**Issue by Pathen85** [fuatakgun/eufy_security#735]
**Is your feature request related to a problem? Please describe.**
When someone rings my doorbell, I want my Eufy camera to record on its SD card for a certain time. The Eufy App provides a button to start recording. However, this is not accessible from within Home Assistant.

**Describe the solution you'd like**
A button or service within Home Assistant to start a recording on the camera's local storage. 

**Describe alternatives you've considered**
A switch in Home Assistant that toggles the 'continous recording' option of a particular camera in the Eufy App. That way I could just enable continous recording whenever someone rings my doorbell and stop it again after 1 minute or so. 

**Additional context**
I know I can record a video within Home  Assistant, however the playback feature in the eufy App is just way more responsive. 
I also know that if I enable motion detection on the camera, it would save those clips automatically to the SD card but since the camera is pointed towards the sidewalk, I dont want it to record basically all day long. Just when somebody rings the doorbell (which is connected to HASS through a different Integration). 

I appreciate all the work you guys do!

**Comment by fuatakgun** [comment]
can you please check with @bropat if this functionality can be supported by add-on? we can implement it here afterwards
