### ISSUE TITLE
Support "eufy Security WiFi Smart Lock" T8502

### ISSUE THREAD

**Issue by jem** [fuatakgun/eufy_security#738]
I have three of the T8510 locks, and have added a T8502. The T8502 is wifi-only and is very simple. No fingerprint, no camera, etc. I suspect it can be supported with the existing messages, but it looks like it is not being recognized as a lock.

I requested support from bropat here: https://github.com/bropat/eufy-security-client/issues/291, but wonder if his layer even needs any changes or if it can just be done further up.

Debug for device is:
```
name: Door
model: T8502
serialNumber: T8502K102XXXXXXX
hardwareVersion: 1.0.0.1
softwareVersion: 2.1.0.1
type: 180
stationSerialNumber: T8502K102XXXXXXX
```

and station is
```
name: Front Door
model: T8502
serialNumber: T8502K102XXXXXXX
type: 180
hardwareVersion: 1.0.0.1
softwareVersion: 2.1.0.1
macAddress: XXXXXXXX
timeFormat: 0
alarmVolume: 26
alarm: false
alarmType: 0
alarmArmed: false
alarmArmDelay: 0
alarmDelay: 0
alarmDelayType: 0
```

I would be very glad to help in any way, including sharing the device or live debugging, if there is anything I can do. (In the US.) Thanks so much!

**Comment by jem** [comment]
Note: a T8502 device is shared to `eufydeveloper@gmail.com`.

**Comment by camcdavid** [comment]
I would second that.  I am not sure how long this lock has been out, but I bought two for a property that I'm splitting into two rentable spaces.  I've already got Kwikset locks that integrate well with HA.  It would be nice to get this lock integration too.  Not much too the Eufy Security Add-on right now:
![image](https://user-images.githubusercontent.com/66885387/218813091-e69f4b45-4ace-4528-8f2f-6a1d3f9e2d01.png)

**Comment by PizzZak** [comment]
I have 4 of these locks and would like to see them supported as well.  My locks are also draining new batteries in 2 weeks.  I am currently working with eufy to on that issue.

**Comment by sjbarkey** [comment]
> I have 4 of these locks and would like to see them supported as well. My locks are also draining new batteries in 2 weeks. I am currently working with eufy to on that issue.

I'm having the same battery drain issue, so hopefully you are able to get Eufy to resolve it!

**Comment by PizzZak** [comment]
> > I have 4 of these locks and would like to see them supported as well. My locks are also draining new batteries in 2 weeks. I am currently working with eufy to on that issue.
> 
> I'm having the same battery drain issue, so hopefully you are able to get Eufy to resolve it!

Eufy stated it was because they were communicating with a 3rd party software. So I disabled the locks in HA/Eufy Security and the batteries are now keeping a charge longer.

**Comment by rborel** [comment]
Ho

> > > I have 4 of these locks and would like to see them supported as well. My locks are also draining new batteries in 2 weeks. I am currently working with eufy to on that issue.
> > 
> > 
> > I'm having the same battery drain issue, so hopefully you are able to get Eufy to resolve it!
> 
> Eufy stated it was because they were communicating with a 3rd party software. So I disabled the locks in HA/Eufy Security and the batteries are now keeping a charge longer.

How did you disable?  I added 2 of them and now my integration won't run since discovering them.  Thanks...

**Comment by sjbarkey** [comment]
Any updates on the support for the C210/E110/T8502 lock?

**Comment by rborel** [comment]
> Any updates on the support for the C210/E110/T8502 lock?

My whole eufy addon is down because it is picking up the unsupported locks.  I'd really. like to know how to either disable them in the addon some how if possible.  I was using the eufy addon pretty heavily before adding the 2 locks.  I'm not going to go back and change out my cameras and door locks.  I'm sure someone is working on it. 

If needed, I volunteer to test...

**Comment by fuatakgun** [comment]
Why don't you remove the locks from shared account and only keep supported devices?

**Comment by rborel** [comment]
Ok, dropped back to 2.10 and can at least get information on the cameras again.  Guess I'll hang out at this version until the upgrade.  

I did notice that it's trying to pull in a s/n for a device that was RMA'd.  I've deleted it from everywhere I could find it and it still shows up in the error logs.  Not sure where the addon is pulling it from.  it's not in my eufy device list anywhere that I can find, inside HAOS or Eufy's site.

**Comment by tmeuze** [comment]
I would also like to express interest for this model to be supported.  However I can help, please let me know. 

Definitely have noticed frequent connect/disconnects in the logs, prior to disabling the device in HA. Maybe that is what is killing the batteries. 

Thank you.

**Comment by rborel** [comment]
If I drop my version of the HACS download to 2.10 I can at least get the supported cameras to work.  The add-on won't start for me if I go any versions higher.

**Comment by fuatakgun** [comment]
Please report add-on specific issues to bropat's repository, integration cannot control them over here

**Comment by sjbarkey** [comment]
@fuatakgun I don't feel this should have been closed.  The original request was to add support for a new lock model.  The posts related to the add-on we technically unrelated to the original request...

**Comment by fuatakgun** [comment]
So @sjbarkey what is your suggestion?
