### ISSUE TITLE
Send the video to cloud services or Telegram

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#74]
Hi, 
would it be possible to send the video recorded by the cam (on microSD) to cloud services, such as Dopbox, Gooogle Drive or Telegram?

Thanks

**Comment by fuatakgun** [comment]
yes, you can go ahead and start the stream and then save the recording using HA, it should work out of box.

**Comment by SmartM-ui** [comment]
> yes, you can go ahead and start the stream and then save the recording using HA, it should work out of box.

I do some tests and if I have a positive result I report it.

**Comment by MechEng70** [comment]
@SmartM-ui  can you post how you are doing this?  TIA

**Comment by fuatakgun** [comment]
@MechEng70 , what are you interested in specifically?

**Comment by SmartM-ui** [comment]
> > > @SmartM-ui can you post how you are doing this? TIA
> > 
> > 
> > Hi, I'm sorry, not having a sensor that monitors the recording status of the cam, I no longer looked for a solution that would allow the recording of the RTSP stream.
> 
> You can try to use AgentDVR + Folder Watcher + Folder Sensor + FTP + Telegram https://community.home-assistant.io/t/agentdvr-nas-synology-telegram/344520 https://community.home-assistant.io/t/agent-dvr-ftp-delete-files-in-home-assistant/346413

Hi @DivanX10 ,
I see what it is, for the moment I am using Frigate to record videos on HA and send them via Telegram.
The problem is that Frigate sees my dog as 75% human and therefore I have a lot of false positives.

The Eufy native App, on the other hand, manages to understand that my dog is a dog and does not send the notification and does not record the video.
It would be useful to be able to take advantage of the eufy registration on Home Assistant, passing through the integration of @fuatakgun 

PS just for information, since you use TensorFlow, can you understand better if it is an animal or a person?

**Comment by fuatakgun** [comment]
i am resolving this, as this is neither a bug or nor enhancement, please use discussions section.

**Comment by SmartM-ui** [comment]
> i am resolving this, as this is neither a bug or nor enhancement, please use discussions section.

Of course,
I know it's not a bug or an improvement, it was an implementation request and I thought it should always be entered in the github

**Comment by fuatakgun** [comment]
of course, we can rely on `discussions` section: https://github.com/fuatakgun/eufy_security/discussions
