### ISSUE TITLE
Country Code for Add-on

### ISSUE THREAD

**Issue by Frosty2235** [fuatakgun/eufy_security#741]
I've downloaded the add-on and entered my email, password, country code (UK), 15 Secs duration, and trusted named.

When I save and restart I get the following from the log..

**Unable to start driver InvalidCountryCodeError: Invalid ISO 3166-1 Alpha-2 country code**

I've tried US, us, UK, uk and EU, but all return the same log. Any ideas please?

**Comment by kohlzz** [comment]
Your country code should be GB instead of UK
