### ISSUE TITLE
Install in new machine - error 

### ISSUE THREAD

**Issue by NunoMCMoreira** [fuatakgun/eufy_security#742]
Hi, I bought a new machine thin client to run HA, and after I run the backup everything works less the add on eufy, it is showing on the log from add-on :

![Screenshot_2023-02-17-21-12-35-080_io homeassistant companion android](https://user-images.githubusercontent.com/113090012/219804808-611d0ef1-262d-48d5-a4c9-c63ca774db3c.jpg)

Looks strange but I don't know how I can solve this

Someone had the same issue?

**Comment by KillaDreams** [comment]
That's not an error, it's doing exactly what it's supposed to do
