### ISSUE TITLE
sensor.person_name doesn't work

### ISSUE THREAD

**Issue by crispywisp** [fuatakgun/eufy_security#744]
I have a HomeBase 3 with the AI person detector feature. It can detect who is the person captured on camera, if you populated the faces detected on the Eufy app.

On Home Assistant, the sensor.person_name always shows "unknown" in the log, even though in the Eufy app event shows the person's name detected on camera.

I remember several updates ago, this used to work fine, I could see in the Home Assistant log the person names detected by the camera. But now, it always shows unknown.

**Comment by alex-deutsch** [comment]
same for me bro

**Comment by yormedia** [comment]
Same here

**Comment by fuatakgun** [comment]
please check with @bropat's repository if this feature has been tested and working fine. I am not intervening the incoming data, just a pass through
