### ISSUE TITLE
Support for Eufy Security Video smart lock (T8530) and Bridge (T8021).

### ISSUE THREAD

**Issue by pratahsinnetamby** [fuatakgun/eufy_security#747]
The Eufy security video smart lock is a relatively new product and provides a doorbell, video and lock in a single device. There are additional features such as finger print. It some with a wifibridge.

Currently the device gets picked up but whilst many of the alarm related features are recognised the lock is not identified.

Support of this device will be much appreciated.

Lock device information:

![image](https://user-images.githubusercontent.com/75194723/220529721-9422fd2d-8e7b-4cbc-bc0a-2b854fbfd475.png)

Bridge device information:

![image](https://user-images.githubusercontent.com/75194723/220529905-7365ea1c-0dce-43a5-a405-24ebc3e4f9bd.png)

**Comment by pratahsinnetamby** [comment]
Is this queue being monitored?!

**Comment by fuatakgun** [comment]
if the issue still persists and if the device support has been added to add-on, please share the device with me following README

**Comment by pratahsinnetamby** [comment]
Hi fuatakgun,

I've just returned from travelling and noticed your comments. I look at re-installing the add-on to see if it recognises device. 

BTW, what exactly did you mean by "share the device". I have included the model details in the header of this issue.
