### ISSUE TITLE
Hasn't worked since v6+

### ISSUE THREAD

**Issue by akuehner** [fuatakgun/eufy_security#748]
My integration hasn't worked since the latest major update. I've tried completely uninstalling the HACS integration, the add-on, the devices, etc. When I re-install the add-on it let's me configure my credentials, however as soon as I save this configuration it closes the config and doesn't let me edit/add it again. If I try to start the add-on it immediately closes. The add-on shows Eufy Security Add-on
Current version: 1.3.0.

My devices show in HA, however they are consistently unavailable. In the logs they show as having gone inactive, and then do not become active again. Happy to share any logs, or anything else I can share to troubleshoot this.

**Comment by Taraman17** [comment]
Is there any info or even progress on this?

**Comment by Adam-Kay** [comment]
Having the same issue; my add-on crashes pretty much immediately after starting. Log tab isn't showing anything either unfortunately.

**Comment by fuatakgun** [comment]
if add-on is not working, I cannot do any magic from integration side. 

Report the problem over here: https://github.com/bropat/hassio-eufy-security-ws
