### ISSUE TITLE
Slow start-up of the Home Assistant VM with eufy security integration

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#75]
Hi @fuatakgun 
I noticed that the Home Assistant Virtual Machine, since I installed eufy security, when the Host starts it takes about 10 minutes to start, remaining still on the initialization of your integration:

<img width="473" alt="Schermata 2021-10-10 alle 14 05 33" src="https://user-images.githubusercontent.com/63554131/136695370-3b222986-0526-48c3-8fad-d4eed1aae4cd.png">

```
2021-10-10 14:05:27 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: eufy_security
2021-10-10 14:06:27 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: eufy_security
2021-10-10 14:07:27 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: eufy_security
2021-10-10 14:08:27 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: eufy_security
2021-10-10 14:09:25 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward
2021-10-10 14:14:25 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap - moving forward
```

The restart of the Home Assistant Core only (NO entire VM) takes a few seconds.

Is it possible to make the VM startup times return to normal?

Thanks

**Comment by SmartM-ui** [comment]
> I have also the same version and this issue was gone after latest change.
> 
> You need to enable excessive logging following readme file and share the debug logs.

Hi @fuatakgun ,
I installed the latest eufy security integration update (88a9cbd), but the problem when starting the Home Assistant VM remained (600sec).

How do I set up the detailed log for the single eufy component?

**Comment by SmartM-ui** [comment]
Hi @fuatakgun 
This is the detailed log:
https://pastebin.com/PqGMgabS

**Comment by fuatakgun** [comment]
Got it, i am not using hassos, that was one of a bad decision of mine :-) and i am also using Raspbian, which is not supported for supervised installation, another bad decision.

So, i cannot ask HA team to investigate to my add-ons are not starting up.

**Comment by SmartM-ui** [comment]
Hi @fuatakgun ,
I tried a clean install of Home Assistant with only your addon and integration installed. 
Similarly to the reboot the addon does not start, if not after 10 minutes.

Until a solution is found, would it be possible to delay the start of the Eufy Security (HACS) custom component by 60 seconds?

If you were able to start the custom component with a few seconds of delay, to allow Home Assistant to start without your add-on, you could create an automation in the home assistant that forces your addon to start after XXX seconds later. 
   - service: hassio.addon_start
     date:
       addon: xxx_eufy_security_addon

Unfortunately, the automation to force restart your addon does not work if Home Assistant is not started completely

**Comment by fuatakgun** [comment]
I will give this a try, I will focus on this this weekend.

**Comment by SmartM-ui** [comment]
> I will give this a try, I will focus on this this weekend.

Perfect,
I look forward to the release!

**Comment by fuatakgun** [comment]
please get latest version and we will see https://github.com/fuatakgun/eufy_security/issues/59#issuecomment-968352909

**Comment by derekoharrow** [comment]
Still experiencing this issue with version be15a00, running against eufy-security-ws 0.3.3 (as per readme).

Once the startup times-out and carries-on, the eufy entities show as unavailable.

**Comment by fuatakgun** [comment]
This is not an actual slow startup issue, rather add on is not started at all and i don't have a solution in place yet.

**Comment by SmartM-ui** [comment]
> please get latest version and we will see [#59 (comment)](https://github.com/fuatakgun/eufy_security/issues/59#issuecomment-968352909)

Hi,
I cannot give feedback because I was able to update only the custom component as I find an error in updating the addon (I opened issues)

**Comment by DivanX10** [comment]
Tell me, was it possible to solve the problem with downloading the uefi_security addon when the Home Assistant is fully turned on? Now this is a critical problem for me, because when the lights in the house turn off, the UPS sends the NAS Synology command to turn everything off and switch to safe mode. All services, including the virtual machine with Home Assistant, are all turned off. When power is supplied to the UPS, the NAS turns on, all services and Home Assistant are started, but due to the fact that the eufy_security addon does not start, it does not allow the Home Assistant to boot completely, waits for me to turn on the eufy_security addon manually, and after that it starts the rest of the addons and only after that the Home Assistant will be fully loaded.

**Comment by SmartM-ui** [comment]
> 

Hi @DivanX10 
unfortunately this problem has not yet been solved and I also have the problem that when the current home assistant returns it cannot start the automations until after 600 seconds.

I also tried not to start the addon automatically (hoping it would also have an effect on Eufy Hacs), but still you have to wait 600 seconds.

I also tried to install eufy hacs and addon on a clean Home Assistant VM and the problem still occurs.

I hope @fuatakgun  will be able to solve this problem as soon as possible.

Eufy Security Add-on 0.5.5 & Eufy Security HACS d684c85

**Comment by fuatakgun** [comment]
i have latest ha core and supervisor and not experiencing this problem anymore, please share your experience here. 

Core 2021.11.5
Supervisor 2021.10.8
Add-on 0.5.5

**Comment by DivanX10** [comment]
Home Assistant OS 6.6
Core 2021.11.5
Supervisor 2021.10.8
Add-on 0.5.5


I have the same thing. On a combat vehicle, when the Home Assistant is completely turned off, and then the Home Assistant is turned on, the euro security addon does not load. If you just restart the Home Assistant, the eufi security addon is loaded. On the test virtual machine, the addon hijacking security, when the Home Assistant is completely turned off, and then the Home Assistant is turned on, the addon hijacking security is loaded. I noticed that I have 5 addons on the test machine, and 15 addons on the combat machine. Apparently some addon does not allow the hijacking security addon to load when loading Home Assistant. I will put one addon on the virtual machine and turn off and turn on Home Assistant, there may be an addon that does not allow the hijacking security addon to boot

**Comment by SmartM-ui** [comment]
Hi @fuatakgun ,
The problem is present when the host running Home Assistant is completely shut down and restarted.
When restarted, Home Assistant fails to start the eufy security addon until after 600 seconds.
The problem is present both on the Home Assistant VM that I normally use, and on a test VM where I only installed the Eufy Security addon and no other add-ons.

Home Assistant OS 6.6
Core 2021.11.5
Supervisor 2021.10.8
Eufy Security Add-on 0.5.5
HACS Eufy Security d684c85

**Comment by DivanX10** [comment]
I seem to have found a problem why the Ugan Security addon does not start after the Home Assistant is fully enabled. I have checked several times and it looks like this for me. Try it at home. How will you have it?


When I install this Eufy Security integration, then after completely turning off the Home Assistant and turning it on, the addon does not start, and if I remove the Eufy Security integration and turn off the Home Assistant completely, and then turn it on, the Eufy Security addon starts normally.
![image](https://user-images.githubusercontent.com/64090632/144294823-f8c22aea-8c19-43b8-b47c-5b522bc71a4f.png)

**Comment by fuatakgun** [comment]
This should have been improved now. At startup, if add on is not ready, integration will not wait forever, try later on (5 secs, 10 secs, 30 secs, and increasingly)

You will see this information in integrations page.

Please update integration and test

![Screenshot_2021-12-11-08-41-04-916_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/145668775-a0a143b7-dde9-492f-b922-8689d5930a5e.jpg)

**Comment by fuatakgun** [comment]
This solution is about to wait for add on to be ready without blocking home assistant. Add on will start late (1 to 10 minutes delay) but integration will not block home assistant or other integrations to wait.

So, i will not be able to fix late startup of add-on, rather let integration wait for it.

**Comment by fuatakgun** [comment]
> Hi @fuatakgun what if you try to run the startup addon as a service instead of an application? Could it improve?
> 
> https://developers.home-assistant.io/docs/add-ons/configuration/
> 
> startup	string	no	Default application. initialize will start add-on on setup of Home Assistant. system is for things like databases and not dependent on other things. services will start before Home Assistant, while application is started afterwards. Finally once is for applications that don't run as a daemon.
> You could try modifying the config.json:
> 
> "startup": "application", with "startup": "services",

hey @SmartM-ui , changing from application to service will cause home assistant core to wait on add-on. And I feel like this could be more problematic as there will be nothing accessible until eufy add-on is ready. It looks riskier to me, what do you think?

**Comment by fuatakgun** [comment]
Example logs from my setup, you can see that, HA is first starting up SERVICE add-ons as pointed out by @SmartM-ui , than it waits Core to be ready and then continues with APPLICATION add-ons.

SERVICE add-ons are completed at 12:56:25
APPLICATION add-ons are started at 13:03:04 and finished at 13:03:33
I do not know why my HA is waiting 7 minutes until APPLICATION add-ons are being created.

```
21-12-11 12:56:10 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/ftp/armv7 with version 4.3.0
21-12-11 12:56:12 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-ssh with version 9.2.1
21-12-11 12:56:19 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-duckdns with version 1.14.0
21-12-11 12:56:25 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on local/armv7-addon-unifi with version dev
21-12-11 12:56:30 INFO (MainThread) [supervisor.core] Start Home Assistant Core
21-12-11 12:56:30 INFO (SyncWorker_4) [supervisor.docker.interface] Starting homeassistant
21-12-11 12:56:30 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-12-11 12:57:02 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP
21-12-11 12:57:02 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-12-11 12:57:26 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-12-11 13:03:04 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-12-11 13:03:04 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 5 add-ons
21-12-11 13:03:07 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-configurator with version 5.3.3
21-12-11 13:03:15 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-armv7 with version 1.22.1-1
21-12-11 13:03:18 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-armv7 with version 0.105.2
21-12-11 13:03:22 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on bropat/eufy-security-ws with version 0.6.0
21-12-11 13:03:33 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on aler9/rtsp-simple-server with version v0.17.6
```

**Comment by fuatakgun** [comment]
I have published a new fix, please try. sometimes, because of timing of add-on vs integration, camera devices were not picked up correctly, it should be fixed now.

**Comment by SmartM-ui** [comment]
> 
Hi @fuatakgun ,
sorry for the delay in answering, but I'm away from home.

However, even now Home Assistant has to wait for the Eufy_Security add-on to load to start completely. 
This is precisely the problem.
Home Assistant waits 10 minutes (600 seconds) before starting completely because the Eufy addon is not started.

Anyway, if you want, I have Test VM and we can try them if you can create a test branch with this version.

Thanks again for everything you do

**Comment by SmartM-ui** [comment]
> 



> I have published a new fix, please try. sometimes, because of timing of add-on vs integration, camera devices were not picked up correctly, it should be fixed now.

I return home Thursday,
as soon as possible I try and let you know.

THANK YOU!

**Comment by SmartM-ui** [comment]
> I have published a new fix, please try. sometimes, because of timing of add-on vs integration, camera devices were not picked up correctly, it should be fixed now.

GREAT!
It works perfectly, restarting, even from the VM turned off, does not block the Home Assistant from starting!
