### ISSUE TITLE
Integration setup in HA fails at Eufy WS Instance

### ISSUE THREAD

**Issue by DiMilan** [fuatakgun/eufy_security#751]
Setup proposes localhost (127.0.0.1) as default URL and 3000 as port (see instructions for supervised setup) but fails with error Host/port is wrong

Addon installed in HACS 
HA runs in docker on Ubuntu

![image](https://user-images.githubusercontent.com/4007084/220934633-5a658312-2550-41ea-a6bb-de4ed634768c.png)

**Comment by fuatakgun** [comment]
I cannot solve this, you need to find specific ip of eufy security ws docker and use it.

127.0.0.1 means localhost for home assistant docker, you need to reach other container. Ask help in home assistant community.

**Comment by DiMilan** [comment]
Do you mean running the add-n is not enough? Do I need to run https://github.com/bropat/eufy-security-ws in a container also? Is this what the add-on tries to connect to. 
Sorry, I wasn't able to filter that out of the documentation.
