### ISSUE TITLE
 Eufy Floodlight Pro 2 No alarm triggering

### ISSUE THREAD

**Issue by Flow76320** [fuatakgun/eufy_security#752]
Hi!

First of all, thanks for this amazing add-on! I'm adore it.

I recently bought some Eufy Floodlight Pro 2 and was wondering to use them as siren. This feature is display for the devices but seems not implemented yet:

```
 NotSupportedError  This functionality is not implemented or supported by T8423T602233009F
error stack:
• station.ts:3154 triggerDeviceAlarmSound
    node_modules/eufy-security-client/src/http/station.ts:3154:19
• message_handler.ts:284 handle
    src/lib/device/message_handler.ts:284:35
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• server.ts:125 receiveMessage
    src/lib/server.ts:125:21
```

Do you have any plan about implenting it? I may help if needed :-)
Thanks!

**Comment by fuatakgun** [comment]
please inform @bropat over the issue, if it has not been resolved yet

**Comment by MarioThielert** [comment]
@fuatakgun , @bropat : Is the feature to trigger cameras device alarm sound implemented?
