### ISSUE TITLE
enable motionDetectionTypePet switch (and other) for Eufycam3

### ISSUE THREAD

**Issue by bdormael** [fuatakgun/eufy_security#754]
For my EufyCam3 (with Homebase 3) I have the possibility to enable/disable human, pet & vehicle detection separately.

Your plugin in Home Assistant apparently only has motion detection on or off.

Is it possible to enable these switches as well ?

In the debug mode I can see that these switches are called:
motionDetectionTypePet
motionDetectionTypeVehicle
motionDetectionTypeHuman
motionDetectionTypeHumanRecognition
motionDetectionTypeAllOtherMotions

**Comment by bdormael** [comment]
Since this is closed, does it mean it will not be implemented ? (because I cannot see the option yet for the Eufycam 3 cams).
It is possible via the API from Bropat, but then I need to do this via Node-Red, I prefer there is a simple switch (or dropdown selection) from Home Assistant

**Comment by bdormael** [comment]
bump

**Comment by fuatakgun** [comment]
It should be working here, right?
![image](https://github.com/fuatakgun/eufy_security/assets/11085566/0b0bf666-4e2e-4481-a5f9-ed6ad7669956)

**Comment by bdormael** [comment]
This is an option for solocams, eufycam2 and indoor cams, but not for Eufycam3 with Homebase 3.
The only way I can do this now is by creating a script that calls the service but there is no dropdown in the entities.

**Comment by fuatakgun** [comment]
understood, will create the switches then

**Comment by fuatakgun** [comment]
btw, the screenshot above is coming from indoor PTZ camera.

**Comment by fuatakgun** [comment]
fixed it for S100 camera, should be available for all in next release.
![image](https://github.com/fuatakgun/eufy_security/assets/11085566/9ce5113a-424e-4727-839c-ded42e8a9fac)

**Comment by bdormael** [comment]
thx, don't have s100, hope it will be available also for Eufycam3 :-)

just to be sure, you mapped these to : 
motionDetection
motionDetectionSensitivity
motionDetectionTypeHuman
motionDetectionTypeHumanRecognition
motionDetectionTypePet
motionDetectionTypeVehicle
motionDetectionTypeAllOtherMotions

?

**Comment by fuatakgun** [comment]
try with 7.6.0

**Comment by bdormael** [comment]
I tried 7.6.0 for my Eufycam3 cameras.
It's looking good, thx for that :-)

I tried all combinations and found out some possible remaining issues:
- Turning on motionDetectionTypeAllOtherMotions is working fine but I cannot turn it off anymore, it turns off in HA, but not on the actual cam
- Turning on motionDetectionTypeHuman or motionDetectionTypeHumanRecognition also turns on motionDetectionTypePet

Maybe this is related to the ws security add-on because via my scripts I have similar issues.

**Comment by fuatakgun** [comment]
Yes please raise it to add-on repository.
