### ISSUE TITLE
Failed to set up: Captcha code is required, please revalidate on Integrations page

### ISSUE THREAD

**Issue by bartgabriels** [fuatakgun/eufy_security#756]
I just upgraded to this version due to RPi 3 memory issues but I'm getting stuck.

It asks for a Captcha check
<img width="315" alt="Scherm­afbeelding 2023-02-26 om 10 57 42" src="https://user-images.githubusercontent.com/64467015/221403858-bf9bc62e-305c-4b68-8cf5-368c5e664a0b.png">

<img width="327" alt="Scherm­afbeelding 2023-02-26 om 10 58 02" src="https://user-images.githubusercontent.com/64467015/221403867-e853a19b-a548-42e6-9270-586fe3256f51.png">

Whenever I enter the captcha character, things get stuck
<img width="420" alt="Scherm­afbeelding 2023-02-26 om 10 58 18" src="https://user-images.githubusercontent.com/64467015/221403878-2363846b-c605-4a34-bb5c-52f5a86bed89.png">

<img width="417" alt="Scherm­afbeelding 2023-02-26 om 10 59 06" src="https://user-images.githubusercontent.com/64467015/221403912-360c7b21-a5d0-4e70-88ac-fd2e0dcb7523.png">

If I then press again reconfigure, the complete integration gets stuck.
<img width="556" alt="Scherm­afbeelding 2023-02-26 om 11 00 13" src="https://user-images.githubusercontent.com/64467015/221403955-11cc1da9-d17e-4785-adcb-bd07f03ca0b9.png">

**Comment by bartgabriels** [comment]
Issue resolved itself 1 day later after rebooting the system. No Captcha was asked anymore

**Comment by indyjonesuk** [comment]
I am still stuck :(

**Comment by Kruger1981** [comment]
Was stuck on this as well.
Stopped Eufy-security-ws addon and disabled to start on boot and the watchdog.
Reboot Home assistant go into eufy addon and start it and enabled start on boot option, kept watchdog disabled.
captcha was accepted.

**Comment by AlexandreLogist** [comment]
Did the above mentioned steps, no luck ...
2nd attempt I received a new error, but unable to pass the captcha 
![image](https://user-images.githubusercontent.com/5881465/227867280-32061e82-f23e-4cc8-aead-1cc270a0b4f7.png)
![image](https://user-images.githubusercontent.com/5881465/227868977-c26e0395-ca15-4d94-8d57-d9c4d33d94c4.png)

2023-03-27 07:18:32.843  INFO  Authentication properties changed, invalidate saved cloud token. 
2023-03-27 07:19:02.122  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-03-27 07:20:44.026  INFO  Connected to station T8410P3122041EE8 on host 192.168.0.185 and port 24772 
2023-03-27 07:20:44.307  INFO  Connected to station T8010P23220206B0 on host 192.168.0.5 and port 20588 
2023-03-27 07:20:55.834  INFO  Push notification connection successfully established 
2023-03-27 07:21:48.063  INFO  Disconnected from station T8010P23220206B0 
2023-03-27 07:21:53.125  INFO  Connected to station T8010P23220206B0 on host 192.168.0.5 and port 25227 
2023-03-27 07:22:56.953  INFO  Disconnected from station T8010P23220206B0

**Comment by ghostsand** [comment]
> Was stuck on this as well. Stopped Eufy-security-ws addon and disabled to start on boot and the watchdog. Reboot Home assistant go into eufy addon and start it and enabled start on boot option, kept watchdog disabled. captcha was accepted.

Tried this but it didnt work for me.
i have exacly the same issue as bartgabriels reports.
have not used the integration before so it was a clean install for me.

**Comment by indyjonesuk** [comment]
> > Was stuck on this as well. Stopped Eufy-security-ws addon and disabled to start on boot and the watchdog. Reboot Home assistant go into eufy addon and start it and enabled start on boot option, kept watchdog disabled. captcha was accepted.
> 
> Tried this but it didnt work for me. i have exacly the same issue as bartgabriels reports. have not used the integration before so it was a clean install for me.

Still Unknown Error for me despite trying the steps above

**Comment by Kruger1981** [comment]
> > Was stuck on this as well. Stopped Eufy-security-ws addon and disabled to start on boot and the watchdog. Reboot Home assistant go into eufy addon and start it and enabled start on boot option, kept watchdog disabled. captcha was accepted.
> 
> Tried this but it didnt work for me. i have exacly the same issue as bartgabriels reports. have not used the integration before so it was a clean install for me.

Reboot home assistant before doing the steps, and do the steps right after reboot to see if it works.

**Comment by Kruger1981** [comment]
> > > Was stuck on this as well. Stopped Eufy-security-ws addon and disabled to start on boot and the watchdog. Reboot Home assistant go into eufy addon and start it and enabled start on boot option, kept watchdog disabled. captcha was accepted.
> > 
> > 
> > Tried this but it didnt work for me. i have exacly the same issue as bartgabriels reports. have not used the integration before so it was a clean install for me.
> 
> Still Unknown Error for me despite trying the steps above

Reboot home assistant before doing the steps, and do the steps right after reboot to see if it works.

**Comment by MaxLoose** [comment]
I have the same problem. Unfortunately, the solution described did nothing. Does anyone have any other ideas?

**Comment by dnshpe** [comment]
same problem here, tried everything but nothing works

**Comment by Dataninja126** [comment]
same problem here.  Anyone find a solution yet?

**Comment by awwbaker** [comment]
same problem here. Anyone find a solution yet?

**Comment by xlr8c8** [comment]
same issue here!  restarted, rebooted etc several times.  Captcha never works!  Help!

**Comment by ifflanb** [comment]
Same issue for me too

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/795

**Comment by martialllaw** [comment]
this has just happened to me

**Comment by DaniellePashayan** [comment]
> e

This was just happening to me and ended up here to fix. I had to uninstall, restart, re-add. was getting an error with "configure". dont click, click instead on "add hub". it asked for captcha. reload integration. then click again on "add hub" and input 2fa code that went to email. got it back working for me :)

**Comment by steinah6** [comment]
I’m still having this issue and none of the solutions worked.

**Comment by mhouser78** [comment]
Has there been any fix to this issue yet

**Comment by DavidRMyers1** [comment]
> 02-09-25

I couldn't even see the captcha and pasted this in...  Worked.  Thank you.

**Comment by fuatakgun** [comment]
Can someone update the readme file with a warning?
