### ISSUE TITLE
Can't get past Eufy Security: Setup host/port is wrong

### ISSUE THREAD

**Issue by starman2k01** [fuatakgun/eufy_security#757]
**Describe the bug**

I have duckdns external address with secure address. I can't get the integration to setup using 127.0.0.1, localhost, nor my actual IP address.

**To reproduce**

1. Go to Eufy Security: Setup after installing integration
2. Default 127.0.0.1 fails with Host/Port is wrong. Same with trying localhost and 192.168.1.xxx actual IP address.

**Expected behavior**

Can't get beyond install error.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Supervised core-2023.2.5
- Home Assistant Core Version: 
- Eufy Security Add-on Version: 6.2.0
- Eufy Security Integration Version:

Hardware Information; RPI 4

Log:
eufy_security Exception in login : - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", autoclose=False, autoping=True, heartbeat=60) File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 792, in _ws_connect raise WSServerHandshakeError( aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('ws://127.0.0.1:3000') The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/config_flow.py", line 113, in _test_credentials await api_client.ws_connect() File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 67, in ws_connect await self._client.connect() File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect raise WebSocketConnectionError() from exc custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError
eufy_security Exception in login : - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", autoclose=False, autoping=True, heartbeat=60) File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 776, in _ws_connect resp = await self.request( File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request await resp.start(conn) File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start message, payload = await protocol.read() # type: ignore[union-attr] File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read await self._waiter aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/config_flow.py", line 113, in _test_credentials await api_client.ws_connect() File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 67, in ws_connect await self._client.connect() File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect raise WebSocketConnectionError() from exc custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError
eufy_security Exception in login : - traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection hosts = await asyncio.shield(host_resolved) File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host addrs = await self._resolver.resolve(host, port, family=self._family) File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve infos = await self._loop.getaddrinfo( File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo return await self.run_in_executor( File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -2] Name does not resolve The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", autoclose=False, autoping=True, heartbeat=60) File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 776, in _ws_connect resp = await self.request( File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request conn = await self._connector.connect( File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect proto = await self._create_connection(req, traces, timeout) File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection _, proto = await self._create_direct_connection(req, traces, timeout) File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection raise ClientConnectorError(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host https:80 ssl:default [Name does not resolve] The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/config_flow.py", line 113, in _test_credentials await api_client.ws_connect() File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 67, in ws_connect await self._client.connect() File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect raise WebSocketConnectionError() from exc custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError
eufy_security Exception in login : - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", autoclose=False, autoping=True, heartbeat=60) File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 792, in _ws_connect raise WSServerHandshakeError( aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('ws://localhost:3000') The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/config_flow.py", line 113, in _test_credentials await api_client.ws_connect() File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 67, in ws_connect await self._client.connect() File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect raise WebSocketConnectionError() from exc custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError

**Comment by starman2k01** [comment]
Never mind. Wasn't clear I had to add second eufy security add-on via add-on settings. I know, RTFM.

**Comment by Daneish** [comment]
Glad you got it sorted. Please feel free to close off the issue.

**Comment by polderviolin** [comment]
For me the same behavior....and I really don't know how to go further (spend a lot of time on the communities).....I have already a second loging.

Describe the bug
Can't get beyond install error, I can't get the integration to setup using 127.0.0.1, localhost, nor my actual IP address.

To reproduce
Steps to reproduce the behavior:
    Go to Eufy Security: Setup after installing integration
    Default 127.0.0.1 fails with Host/Port is wrong. Same with trying localhost and 192.168.1.xxx    actual IP address.

Expected behavior

Can't get beyond install error.



 Home Assistant 2023.3.3 Supervisor 2023.03.1 Operating System 9.5 Frontend-versie: 20230309.0 - latest 

Logger: custom_components.eufy_security.config_flow
Source: custom_components/eufy_security/config_flow.py:89
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 20:33:21 (12 occurrences)
Last logged: 21:22:51

    eufy_security Exception in login : - traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection raise exceptions[0] File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection sock = await self._connect_sock( File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock await self.sock_connect(sock, address) File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect return await fut File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb raise OSError(err, f'Connect call failed {address}') ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 3000) The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", autoclose=False, autoping=True, heartbeat=60) File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 779, in _ws_connect resp = await self.request( File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request conn = await self._connector.connect( File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect proto = await self._create_connection(req, traces, timeout) File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection _, proto = await self._create_direct_connection(req, traces, timeout) File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection raise last_exc File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection transp, proto = await self._wrap_create_connection( File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection raise client_error(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:3000 ssl:default [Connect call failed ('127.0.0.1', 3000)] The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/eufy_security/config_flow.py", line 113, in _test_credentials await api_client.ws_connect() File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 67, in ws_connect await self._client.connect() File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 44, in connect raise WebSocketConnectionError() from exc custom_components.eufy_security.eufy_security_api.exceptions.WebSocketConnectionError
    eufy_security Exception in login : - traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/aiohttp

**Comment by zelloxy** [comment]
@starman2k01 I have the same error, what did you mean by "second add-on via add-on settings"? I can't get it to work.

**Comment by starman2k01** [comment]
@zelloxy You have to go to settings->addons and install the Eufy Security add-on app.

**Comment by ColtonYYZ** [comment]
> @zelloxy You have to go to settings->addons and install the Eufy Security add-on app.

I have the addon installed, I also even tried the HACS integration too. I can't get past the host/port is wrong error message. I have tried entering in 127.0.0.1, I've tried the IP address for the Chime. I have tried the IP address for HAss. I tried the IP address of my router (10.0.0.1).

What am I missing?

**Comment by Daneish** [comment]
> What am I missing? 

You will need both the Eufy Security Add-on and the Eufy Security HACS integration.

Is the Add on configured and started? Are there any errors showing in the Add-on’s logs tab?

Once it is configured and started: in the integration, the IP address you need will be the local IP of your Home Assistant, so localhost or 127.0.0.1 should work.

**Comment by fuatakgun** [comment]
highly probable; please follow here: https://github.com/fuatakgun/eufy_security/issues/795

**Comment by dadalouis** [comment]
extra addon 
https://github.com/bropat/hassio-eufy-security-ws

**Comment by charly1st** [comment]
Had the same issues, Host/Port is wrong, but got it sorted.

In Add-ons, get eufy-security-we installed, once installed choose at the top reiter-configuration and fill in your username and password of your Eufy account, I have left port at 3000 and cloud at 10, and save. Then go back to reiter-info and click start (red colour)

Next, in Add Integration, get Eufy Security installed. It worked then perfectly with 127.0.0.1 and port 3000 without error message.

**Comment by Mmhaddad** [comment]
But in the add on store the eufy security is not showing

**Comment by appelboom** [comment]
eufy_security_ws is now installed from Home Assistant, settings, Apps. If not it wont listen on tcp/3000 and then give HA a restart
