### ISSUE TITLE
Support for wall Camera Light

### ISSUE THREAD

**Issue by Ditskys** [fuatakgun/eufy_security#759]
Support for the wall light camera please! 

Can help supply details needed

**Comment by rickhuizinga** [comment]
Support has just been added to eufy-security-client. Can the dependancy version be bumped to include/add support, please?

**Comment by fuatakgun** [comment]
Nothing needed from my side, just get latest version of add-on and reload the integration, it would work.

**Comment by fuatakgun** [comment]
I tried locally, all is fine

**Comment by rickhuizinga** [comment]
Did the same, the wall light cams still show as "UNSUPPORTED". Do the devices need to be removed and re-added? I updated eufy-security in HACS, restarted HA, and also did a reload (as was suggested).

**Comment by fuatakgun** [comment]
@rickhuizinga , so you got the latest version of add-on or mixing stuff?

**Comment by rickhuizinga** [comment]
> @rickhuizinga , so you got the latest version of add-on or mixing stuff?

Ahh, I misunderstood the dependency. I haven't updated the add-on yet. That should fix it. Thanks!
