### ISSUE TITLE
Update the integration without restarting the Home Assistant

### ISSUE THREAD

**Issue by DivanX10** [fuatakgun/eufy_security#77]
Please add the ability to update the integration without restarting the Home Assistant. Such integrations exist. For example this [integration](https://github.com/dmitry-k/yandex_smart_home ) can be restarted and does not require a reboot of the Home Assistant

```
reload:
  description: Reload yandex_smart_home yaml configuration.
```

**Comment by flopp999** [comment]
> yep, that is why all HACS installations or updates are suggesting you to restart HA later on. This is also a biggest pain for me while developing the integration, I have to restart running HA instance for any small change even though it is dedicated for development activities. I wish there is a way to make it happen :)

Hi, I know this is a very old post, but have you found any possibility to change python code without a full restart of HA?
Maybe the solution is to make a basic integration and use python package instead.

**Comment by fuatakgun** [comment]
Even though using an external python package wouldn't work because it is all loaded at once and then executed.

The right thing to do is to have proper integration tests in place so I should not rely on actual instances :-)

I am too lazy for that

**Comment by flopp999** [comment]
> Even though using an external python package wouldn't work because it is all loaded at once and then executed.
> 
> The right thing to do is to have proper integration tests in place so I should not rely on actual instances :-)
> 
> I am too lazy for that

Ahh, yes same here, I am more a guy that try-and-error. OK thanks then I may have second HA for develop.

**Comment by fuatakgun** [comment]
Developing in visual studio code works pretty well, if you are not on windows:-)

On windows, you are slowed down because of subsystem, different file formats and docker, but it works

**Comment by fuatakgun** [comment]
yeah, pyscript and appdaemon are very useful for ad-hoc testing, agreed
