### ISSUE TITLE
Nothing is updating since yesterday

### ISSUE THREAD

**Issue by umutcelebi** [fuatakgun/eufy_security#770]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

**To reproduce**

**Expected behavior**

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 
- Home Assistant Core Version: 
- Eufy Security Add-on Version: 
- Eufy Security Integration Version:

Hardware Information;
- Camera Model:

- Live Streaming Protocol (RTSP/P2P): 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- 

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No): 

**Additional context**

I did not change anything or update. Since yesterday the integration is not working. Reloading or deleting and adding back is not helping to solve the issue.

**Comment by KillaDreams** [comment]
Please post properly, copy pasting the bug reporting template and changing nothing helps nobody.

**Comment by umutcelebi** [comment]
Describe the bug

Sensors are not updating.

A clear and concise description of what you expected to happen.

Sensors needs to update when motion is detected or doorbell is pressed.

Additional information

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;

Home Assistant Installation Type (OS - Supvervised - Core): OS
Home Assistant Core Version: core-2023.3.6
Eufy Security Add-on Version: v6.2.0
Eufy Security Integration Version: ?
Hardware Information; Intel Nuc with HA OS

Camera Model: T8213

Live Streaming Protocol (RTSP/P2P): P2P

Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)

Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
See attachment
[3a26b21d_eufy_security_addon_2023-03-23T14-09-58.486Z.log](https://github.com/fuatakgun/eufy_security/files/11051796/3a26b21d_eufy_security_addon_2023-03-23T14-09-58.486Z.log)


Would you share your device with me in case further debugging required? (Yes/No): Yes

Additional context

I did not change anything or update. Since yesterday the integration is not working. Reloading or deleting and adding back is not helping to solve the issue.

**Comment by kennybeu** [comment]
Hi,
Same problem.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/web_socket_client.py:42
Integration: Eufy Security (documentation, issues)
First occurred: 19:18:30 (1 occurrences)
Last logged: 19:18:30

Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 71, in connect
    await self.ws_connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 67, in ws_connect
    await self._client.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py", line 42, in connect
    self.socket = await self.session.ws_connect(f"ws://{self.host}:{self.port}", autoclose=False, autoping=True, heartbeat=60)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

**Comment by onelius** [comment]
Same problem here, nothing works.

**Comment by freeshare** [comment]
Same here, it hasn't worked for a few days. The start-up, the shutdown... no longer work

**Comment by freeshare** [comment]
> Same here, it hasn't worked for a few days. The start-up, the shutdown... no longer work

For information, as far as I am concerned, problem solved by restarting the addon and integration.

**Comment by umutcelebi** [comment]
That solves it for me now too. But that did not work a few days ago...

**Comment by fuatakgun** [comment]
Please report over here: https://github.com/bropat/hassio-eufy-security-ws
