### ISSUE TITLE
Integration doesn't appear in the list

### ISSUE THREAD

**Issue by nickagian** [fuatakgun/eufy_security#771]
I am facing thos weird issue, that the integration isn't showing up in the list, so I can't install it.

I've downloaded the repository through HACS and verified it's in the custom_components folder. I then restarted HA, but when I go to install the integration, it doesn't appear in the list. I've also tried multiple browsers and to first clear the cache, but no luck.

Is there anybody else facing this?

Is it important which version of HA I use? I have, btw, OS 6.4 and core 2022.6.1 and I'm trying to install the latest release, v6.2.0.

Can it be that my  core version is incompatible (too old or sth)?

**Comment by M31Galaxy15287** [comment]
Have you solved this? I'am facing the same issue.
