### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by langebyende25** [fuatakgun/eufy_security#774]
i don't know if this is the way to do this but i need help.

I have completed the installation up to (3rd installation problems, point 5)
what have I done wrong and what do I need to do to move on.
[
![image](https://user-images.githubusercontent.com/20494200/228279690-d868b89c-09c5-484f-a158-1e4f60c186b8.png)
](url)

**Comment by Riiamo** [comment]
I have the same issue

**Comment by mnagovicz** [comment]
me too :-/

**Comment by MaxLoose** [comment]
Same problem. Any ideas?

**Comment by NexVentor** [comment]
Same here

**Comment by Plicerin** [comment]
same

**Comment by rjdalga** [comment]
Try 8554 for the port rather than 3000.  Hope this helps.

**Comment by Plicerin** [comment]
thx for the response, however this is the terminal output from rtsp-simple-server
2023/05/02 14:37:53 INF [RTSP] [conn 172.17.0.1:55402] opened
2023/05/02 14:37:53 INF [RTSP] [conn 172.17.0.1:55402] closed (invalid URL (/))

**Comment by c0nt4x** [comment]
I have the same issue. Eufy Security add-on shows `INFO  Eufy Security server listening on host 0.0.0.0, port 3000` in the logs so I entered both those during set up of this integration but get the 'Host/Port is wrong' error.

I've also entered my HA instance IP along with port 3000 and still get the error.

How do I get past this?

**Comment by Dekru15** [comment]
same issue here. the add on is installed but the integration won't work. I'm stuck at the first page where the ip and port are asked. can somebody help. (0.0.0.0 don't work the ip of the home base don't work. I have no clue what else I can try)

**Comment by fuatakgun** [comment]
you are probably stuck with 2fa or captcha request, please track here: https://github.com/bropat/eufy-security-ws/issues/211

**Comment by Plicerin** [comment]
updating to latest version fixied the issue for me

**Comment by lnaylor13** [comment]
can you clarify which IP address and port we're supposed to be using? Is the IP of home assistant and the port from the RTSP service?

**Comment by bluemax3000** [comment]
Same issue here.

**Comment by Bloch-Boas** [comment]
Dang, I was hoping there were a solution here... I get the same message... 

All is easy till 3.5 ... Then nothing is happening... Well besides what this post is stating...

**Comment by DedicatedF100** [comment]
Having this issue also.

**Comment by fuatakgun** [comment]
Home Assistant needs to communicate with Eufy Security WS add-on (or container).

For supervisor or HASSOS based installations, localhost or 127.0.0.1 should work.

For other installations, you should find the IP address of respective container and this is not the right place to find it. At least, you can try `host.docker.internal` but this is a network question nothing related to this add-on

```
5- Put Eufy Security Add-on IP Address (127.0.0.1 for Supervised installation) and configured port (default 3000) and click Submit.
```
