### ISSUE TITLE
Feature request: support for S100 Wired Wall Light Cam

### ISSUE THREAD

**Issue by JackGilmore** [fuatakgun/eufy_security#777]
Requesting support for the new Eufy S100 wall light cam: https://uk.eufy.com/products/t84a1311

When setting up in HomeAssistant at the moment I get entities related to the alarm but none for the light or camera.

![image](https://user-images.githubusercontent.com/46202639/229901180-934527e1-df89-4d13-87b4-95228627c393.png)

Debug (station):
```
Properties
name: Front door cam
model: T84A1
serialNumber: T84A1P1022510696
type: 151
hardwareVersion: P0
softwareVersion: 1.0.7.4
macAddress: 04:17:B6:24:4C:25
timeFormat: 1
alarmVolume: 26
alarm: false
alarmType: 0
alarmArmed: false
alarmArmDelay: 0
alarmDelay: 0
alarmDelayType: 0
lanIpAddress: 192.168.0.134
guardMode: 1
sdStatus: 0
sdCapacity: 3624
sdCapacityAvailable: 2736
Commands
Voices
—
```
Debug (device)
```
Properties
name: Front door cam
model: T84A1
serialNumber: T84A1P1022510696
hardwareVersion: P0
softwareVersion: 1.0.7.4
type: 151
stationSerialNumber: T84A1P1022510696
Commands
Voices
—
```

**Comment by Ditskys** [comment]
Would love this to work too.

**Comment by nickwerner84** [comment]
I would love to see this included as well. Just recently got this and integration with eufy _security would be aswesome!

**Comment by KillaDreams** [comment]
You guys need to ask in the @bropat repository @fuatakgun only ports it
over they do not implement new features
