### ISSUE TITLE
RTSP problem on eufycam 3

### ISSUE THREAD

**Issue by radeon79** [fuatakgun/eufy_security#781]
Hello, i have this issue on two eufuycam 3.
I have set a rtsp function on my cam (p2p is working) but after push the rtsp button for starting stream rtsp the camera still hold in preparing (StreamStatus.PREPARING message) and not have any buffer video (i have tested on vlc player also)

Disabling and reenabling the rtsp function on my cameras solve this issue but after resuming from the sleep the issue is still present.
How to solve?

**Comment by troyhatchard** [comment]
Same thing. I could get P2P working. I turned off P2P stream on each camera and turned on RTSP stream. After restarting, both cameras showed "stream provider" as RTSP. Great, except that the streams don't show up when I try to open them from my dashboard.

**Comment by djansen1987** [comment]
watching, have the same issue with my home base 3 and doorbell pro dual 2

**Comment by fuatakgun** [comment]
first, try if respective streams are accessible from vlc media player/
second, just enable basic authentication for streams, rather than digest one

**Comment by djansen1987** [comment]
Second chance i give Eufy with a pause of 2 years. But still streaming and integration is a big issue returned the goods again and bought a Reolink doorbell, if some have this option to return your doorbell I would advice you to try Reolink, works amazing! (And out of the box support in HA)

**Comment by sven0833** [comment]
got 1 of my camera working but the other 2 didnt work same problem. status of stream preparing only, any idea what i can do for the other 2 to work? check the motion detection of both camera they are working and updating on the integration, the video is the only problem.
![Screenshot (96)](https://github.com/fuatakgun/eufy_security/assets/109326754/10ff819b-34d0-4f31-8d6f-c2b8b3163ecf)

**Comment by fuatakgun** [comment]
either share your cameras following README or share your debug files following bug template
