### ISSUE TITLE
Increase Polling Frequency (or maybe a user option to self-set it)

### ISSUE THREAD

**Issue by Colorado4Wheeler** [fuatakgun/eufy_security#782]
**Is your feature request related to a problem? Please describe.**
I love how this plugin adds functionality that otherwise wouldn't exist to HA given the closed architecture of Eufy's system.  However, there seems to be quite a lag between when someone rings the doorbell and HA knows someone rang the doorbell, while my Eufy apps (phone and watch) are almost instant.

**Describe the solution you'd like**
This may be a limitation of the Eufy API, but perhaps this can be tweaked by lowering the polling interval or allowing the user to set the polling interval on the device settings so if you are seeing a lag that you can lower the interval a bit and see if that helps until you finally get to a point where HA is updated almost as instantly as the apps.

**Describe alternatives you've considered**
None really.  I've taken my tablet out to the doorbell so I can see when HA detects motion / loitering versus when my apps and watch notify me and it's 10+ seconds.

**Additional context**

**Comment by fuatakgun** [comment]
door ring bell is retrieved via push notifications so be sure that you are receiving these notifications, and getting help from community forum might be easier for this topic
