### ISSUE TITLE
Port change in Config not possible

### ISSUE THREAD

**Issue by thecem** [fuatakgun/eufy_security#785]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Change Port to 8556, addon starts with port 8554.

```
2023/04/15 14:55:13 I [0/0] rtsp-simple-server v0.17.6
2023/04/15 14:55:13 I [0/0] [RTSP] TCP listener opened on :8554
2023/04/15 14:55:13 I [0/0] [RTMP] listener opened on :1935
2023/04/15 14:55:13 I [0/0] [HLS] listener opened on :8888
```

**To reproduce**

**Expected behavior**

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 
- Home Assistant Core Version: 
- Eufy Security Add-on Version: 
- Eufy Security Integration Version:

Hardware Information;
- Camera Model:

- Live Streaming Protocol (RTSP/P2P): 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- 

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No): 

**Additional context**

Add any other context about the problem goes here.

**Comment by bigrizzo** [comment]
I'm having the same issue.

**Comment by MilesAheadToo** [comment]
Me too. Any update?

**Comment by NWTmark** [comment]
My experience from having a port clash is in fact the port _does_ change. But for some reason it does not show as much in the log.

**Comment by fuatakgun** [comment]
whatever is logged inside the add-on would not matter, it is telling about internal port, not the external one.

So, docker is a container system and it will open internal ports (like 8554) but it is exposed as 8556 to external system.
