### ISSUE TITLE
Cannot connect to cameras at remote location

### ISSUE THREAD

**Issue by ancjsd** [fuatakgun/eufy_security#786]
Many thanks for your work on this project!  I successfully installed the Eufy integration in my Home Assitant some months ago, and it reliably connects with, and allows me to control, all Eufy cameras on the LAN that includes my Home Assistant installation.  However, I have never been able to connect to Eufy cameras located on a different network at a remote site.   The log for the security addon simply states "Tried all hosts, no connection could be established," and ultimately  "Timeout connecting to station xxxxxxxxxxxxxx."  Is such a connection possible with the integration?  If it is, do you have any thoughts on what I might try to get a connection?  Thanks!

**Comment by fuatakgun** [comment]
please report over here: https://github.com/bropat/hassio-eufy-security-ws
