### ISSUE TITLE
Unexpected exception importing component homeassistant.components.eufy

### ISSUE THREAD

**Issue by boctok** [fuatakgun/eufy_security#787]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Logs produce error after HA Core update

```
Logger: homeassistant.setup
Source: setup.py:213
First occurred: 6:55:45 AM (1 occurrences)
Last logged: 6:55:45 AM

Setup failed for eufy: Unable to import component: Exception importing homeassistant.components.eufy
```

```
Logger: homeassistant.loader
Source: components/eufy/__init__.py:2
First occurred: 6:55:45 AM (1 occurrences)
Last logged: 6:55:45 AM

Unexpected exception importing component homeassistant.components.eufy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/eufy/__init__.py", line 2, in <module>
    import lakeside
  File "/usr/local/lib/python3.10/site-packages/lakeside/__init__.py", line 25, in <module>
    from . import lakeside_pb2
  File "/usr/local/lib/python3.10/site-packages/lakeside/lakeside_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**To reproduce**

**Expected behavior**

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): 
- Home Assistant Core Version: 
- Eufy Security Add-on Version: 
- Eufy Security Integration Version:

Hardware Information;
- Camera Model:
Various

- Live Streaming Protocol (RTSP/P2P): 
RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- 

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No): 

**Additional context**

Add any other context about the problem goes here.

**Comment by koerbcm** [comment]
+1
Exception: Mine was already working and setup and just started getting this error recently, probably after the last HA update.

**Comment by Morodin8** [comment]
+1
Mine was working, stopped after Core update 2023.4.5

**Comment by RuggyBearLA** [comment]
+1
Everything was working until the update to 10, no other changes were made.  Issue continues after today's update to 2023.4.6

[home-assistant_2023-04-22T04-54-21.460Z.log](https://github.com/fuatakgun/eufy_security/files/11300304/home-assistant_2023-04-22T04-54-21.460Z.log)

**Comment by mattyf** [comment]
+1
Was working, stopped after 2023.4.6 update (updated from 2023.3.X)

**Comment by Heshamhamin** [comment]
+1 
After update error is up.

**Comment by edzards** [comment]
+1 
same issue on my side after the update. cannot even reboot HA - just via ssh

**Comment by bryan292** [comment]
same issue after update

**Comment by Foxhill67** [comment]
+1
Same here

**Comment by iggy** [comment]
Looks like python-lakeside had a release a couple days ago. Fix should hopefully be as easy as bumping lakeside to 0.13

**Comment by boctok** [comment]
Appears to have resolved after last system update, for me.

**Comment by fuatakgun** [comment]
thanks @iggy

**Comment by koerbcm** [comment]
I am still getting this error message even after I updated my Home Assistant. Was that fix only in the docker version of HA? I tired to do a pip show for python-lakeside or just lakeside to see if I could just update the version but it reports that it does not exist. Might anyone have a link documenting on how to update this in the OS version or general troubleshooting steps? Much appreciated.

**Comment by iggy** [comment]
It's an unreleased version as of yet. You'll probably have to wait a week or two for the release and then for the OS packages to be updated. Just keep your eyes peeled for the 2023.5 release.

I'm not sure if there's a way to upgrade OS to beta versions
