### ISSUE TITLE
EUFY Custom alarm settings - what has changed

### ISSUE THREAD

**Issue by jouster1974** [fuatakgun/eufy_security#793]
there seems to be a change to the Front End of the Eufy Add in... particularly when changfing modes from HA itself

Now when I click on any of the devices, I get the following UI

![image](https://user-images.githubusercontent.com/15368005/236182017-c3620d3e-c074-4e00-96c7-b7a5f80f3c70.png)

which looks great BUT the custom models seemed to have been remapped.  

I originally had Custom 1 as Night and Custom 2 as Gardeen but now Custom 1 is Garden and Custom 2 is vacation

All I have done is upgrade from 2023.3 to 2023.5 but wasn't aware of any change to the integration itself unless I am missing something

**Comment by fuatakgun** [comment]
Nothing from integration end, this is coming from home assistant frontend changes

**Comment by jouster1974** [comment]
ah ok... didn't think there had been an integration update...not sure how to fix the different custom modes being totally mixed up...so have reverted back to 2023.3.6 for now as cant be without the alarm working as brilliantly as it was before

**Comment by ripple7511** [comment]
I'm having a similar issue. I see the above UI, but I can no longer change the Mode-- it doesn't seem to do anything.
