### ISSUE TITLE
Unable to trigger base alarm for x duration

### ISSUE THREAD

**Issue by julet85** [fuatakgun/eufy_security#794]
I'm trying to trigger an alarm on my eufy indoor 2k camera using the eufy_security.trigger_base_alarm_with_duration service. It triggers fine but only runs for 5s no matter what duration I set it to.

Is this a bug or am I missing something?

Thanks
Andrew

**Comment by fuatakgun** [comment]
please follow here: https://github.com/fuatakgun/eufy_security/issues/704
