### ISSUE TITLE
Help on Guide Start streaming on camera, when there is a motion, this would generate a new thumbnail on Home Assistant....

### ISSUE THREAD

**Issue by kvanbiesen** [fuatakgun/eufy_security#796]
I copied exact the code from the guide in the help file.
- start the p2p stream
- generate_image.
- stop p2p stream.
Then send the message, the message send correctly but cant find for the love of my life were it stores the screenshot that i generated by the generate_image service .

Always Blank 
/api/camera_proxy/camera.doorbell doesnt return anything. Just send message withouth image included.

Littleraly a copy-passe

```python
action:
  - choose:
      - conditions:
          - condition: trigger
            id: sensor
        sequence:
          - service: eufy_security.start_p2p_livestream
            data: {}
            target:
              entity_id: camera.doorbell
          - service: eufy_security.generate_image
            data: {}
            target:
              entity_id: camera.doorbell
          - service: eufy_security.stop_p2p_livestream
            data: {}
            target:
              entity_id: camera.doorbell
          - service: notify.mobile_app_kris
            data:
              message: Motion detected
              data:
                image: /api/camera_proxy/camera.doorbell

```

**Comment by kdill00** [comment]
Is homeassistant behind a reverse proxy?  Are you using android or ios? Also don’t call the service. I found for some reason if not using camera.turn_on and off, you need to call the “button press” service and then select the start live stream button.

**Comment by fuatakgun** [comment]
the latest version of integration should receive latest notification image without streaming, try it out

**Comment by kvanbiesen** [comment]
Can confirm.

It shows not the latest picture from the lastest even. Like doorbel ring/Motion detection/

Great job @fuatakgun

**Comment by dabm-git** [comment]
> the latest version of integration should receive latest notification image without streaming, try it out

What is the path to the image? this way I can persist it in the NAS and send it by telegram or other notification.

**Comment by fuatakgun** [comment]
There is no path you should save it yourself to disc using camera capture service.

Image is received as bytes from addon and presented directly using these bytes
