### ISSUE TITLE
Assistant TTS over Doorbell

### ISSUE THREAD

**Issue by oOJoshOo** [fuatakgun/eufy_security#797]
Is it planned or possible that you can use the Eufy Doorbell as an output speaker for the home assistant?

You could then automatically give your visit a description when the door is open, etc.

Or the postman where to leave the package.

**Comment by fuatakgun** [comment]
as of now, this is a far fetched ask for my skill set under home assistant.

**Comment by elvenstof** [comment]
Some time has passed and I was wondering if this could now be considered for the future?
