### ISSUE TITLE
Add switches for some of the camera settings

### ISSUE THREAD

**Issue by leonardpitzu** [fuatakgun/eufy_security#80]
use case: the interior cameras are turned off when i am at home though the IR LED (night mode) keeps toggling on/off depending on the light even tough it's useless as the camera is off and no streaming can take place.

solution: add switches for some of the basic camera settings such as night mode, sound detection, etc.

**Comment by bw** [comment]
Just seconding— would love this feature as well. There is no way to turn the camera completely off/on in the Eufy app depending on the security mode (or any other automation), so this would be a big improvement. I tell everyone in the family that the indoor cameras are off when any of us are home, but people still see the IR LEDs turn on at night (and there is a clicking sound too, so it's hard to miss).

Thank you!

**Comment by fuatakgun** [comment]
get latest update and enjoy, please create separate requests if you are interested with additional attributes.

**Comment by fuatakgun** [comment]
Night Vision and Auto Night Vision works but do not update their state, I will create an issue for eufy-security-ws repository.

![image](https://user-images.githubusercontent.com/11085566/145871641-aff66c97-b6ce-48ce-890c-777748ea8745.png)
