### ISSUE TITLE
Motion detection not working anymore

### ISSUE THREAD

**Issue by stranchand** [fuatakgun/eufy_security#803]
**Describe the bug**

Motion detection is not working anymore.
On device information no event is fired, automation do not work, and Alarmo is not firing.

Even if I configure my cameras for motion or person detection. But I can see that cameras are working well because their led indicator are red as they might be on a motion detection.

I think that this integration have a bug.

**Additional information**
- Home Assistant Installation Type : on raspberry pi 4, full mode (not via Docker)
- Eufy security integration : v6.2.0
- Home Assistant Core : 2023.5.2
- Supervisor : 2023.04.1
- Operating system : 10.1
- User interface : 20230503.3 - latest

**Hardware Information**
- 2x Indoor Cam 2k, version 2.1.8.3
- 1x Solocam E20, version 1.2.2.5

**Configuration**

![Screenshot_20230521-172726](https://github.com/fuatakgun/eufy_security/assets/24604334/4049357e-9175-42ae-893d-6f8a1c988402)

**Logs**

[error_log.txt](https://github.com/fuatakgun/eufy_security/files/11524933/error_log.txt)

**Comment by MarshallRDC** [comment]
+ 1 I've reporter the same issue

**Comment by stranchand** [comment]
Oups, i've missed your issue @MarshallRDC 

Can you please comment mine with all the `Additional information` and `Hardware Information` that I've put ? (and your logs) To help them to reproduce/fix this.

**Comment by fuatakgun** [comment]
I believe you are using old version of add-on (eufy_security_addon), it is supposed to be called as (eufy_security_ws), please check instructions from README, add new repository from bropat and install the latest add-on

**Comment by fuatakgun** [comment]
Ok, then, please move with next step and engage with bropat on the issue. He would require some debug logs from add on.

One last thing, be sure that you all had enabled the push notifications on the app (device based, not usee based) as this add-on/integration relies on them.

**Comment by fuatakgun** [comment]
following template, enable debug logs and share them over here, you have only shared error logs, which is not enough.

double check if you have enabled push notifications for motion events

**Comment by stranchand** [comment]
@MarshallRDC Did you managed to make it works ?

**Comment by MarshallRDC** [comment]
> @MarshallRDC Did you managed to make it works ?

It magically started to work again here. Though no update was done.

**Comment by stranchand** [comment]
> > @MarshallRDC Did you managed to make it works ?
> 
> It magically started to work again here. Though no update was done.

Could you please just send me screenshots of your Eufy app configuration please ? 🙏

**Comment by MarshallRDC** [comment]
> > > @MarshallRDC Did you managed to make it works ?
> > 
> > 
> > It magically started to work again here. Though no update was done.
> 
> Could you please just send me screenshots of your Eufy app configuration please ? 🙏

![Screenshot_2023-05-29-21-32-01-58_c3a231c25ed346e59462e84656a70e50~2](https://github.com/fuatakgun/eufy_security/assets/14992567/4e8d140d-289b-4c30-92dc-d0d732311ca6)
![Screenshot_2023-05-29-21-31-51-30_c3a231c25ed346e59462e84656a70e50](https://github.com/fuatakgun/eufy_security/assets/14992567/a770493a-c1c2-42be-aecf-3d1b21c7d57f)

**Comment by stranchand** [comment]
> > > > @MarshallRDC Did you managed to make it works ?
> > > 
> > > 
> > > It magically started to work again here. Though no update was done.
> > 
> > 
> > Could you please just send me screenshots of your Eufy app configuration please ? pray
> 
> [...screenshots...]

Thank's!

And, if that's not too much to ask..., parameters from the eufy app itself ? Motion detection parameters screen and notification parameters screen (both from the camera configuraiton)

It will help me a lot :pray:

**Comment by stranchand** [comment]
Thanks a lot!
