### ISSUE TITLE
Broken UI on Configuration Panel

### ISSUE THREAD

**Issue by oliwarner** [fuatakgun/eufy_security#804]
There are a few screenshots that show a way to specify the host IP. I'm running it on another computer (not the addon) so need to provide an IP but I only have a checkbox that doesn't seem to do anything.

Worse, I've tried to debug what's being shown and when I select the checkbox the RTSP url is something like `rtsp://True:..../....`. It seems broken and I'm not sure how or why.

![image](https://github.com/fuatakgun/eufy_security/assets/113778/26173388-8af4-4a5b-8dc7-95b2709ace73)

If the documentation is just old, that's fine but I do need to be able to override the IP address. Any ideas? Running on 2023.5.3 core, latest HACS build of this. 6.2.0?

**Comment by Lockszmith-GH** [comment]
I think the docs are actually incorrect in stating 127.0.0.1 - it should be
3a26b21d-eufy-security-addon for the Eufy add-on and
75a80a57-rtsp-simple-server for hte RTSP simple server.

These might be specifically my values, to see yours check out the Add ons and see their internal hostname while they are running.

**Comment by oliwarner** [comment]
I worked around this by manually editing `~/.storage/core.config_entries`. Replaced the True/False that the UI lets me set with a string value pointing to the right host.

Leaving this open because the UI is doing something dodgy here

**Comment by stpuk** [comment]
@oliwarner I uninstalled and reinstalled, the new version now asks for the IP address as part of the configuration and it correctly shows in the stream URL

**Comment by fuatakgun** [comment]
this is very weird, I personally do not manage how it will be rendered on the UI, rather set the variable type, which is STRING in this case.

https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/config_flow.py#L31

So, I am not sure how this had happened. keeping this open if we can manage to get more examples around

**Comment by Menz01** [comment]
> @oliwarner I uninstalled and reinstalled, the new version now asks for the IP address as part of the configuration and it correctly shows in the stream URL

i have uninstalled and reinstalled and each time i am onlt seeing "ture" if the box is checked and "false" if the box is unchecked

**Comment by fuatakgun** [comment]
merging into similar one: https://github.com/fuatakgun/eufy_security/issues/798
