### ISSUE TITLE
Websocket client needs updated: Requirements for eufy_security not found: ['websocket-client==1.1.0'].

### ISSUE THREAD

**Issue by barrelltitor** [fuatakgun/eufy_security#808]
**Describe the bug**

The integration attempts to use an older version of websocket-client, causing loading failure on linuxserver's home assistant container.

**To reproduce**

1. Start linuxserver's Home Assistant container
2. Integration immediately fails loading due to attempting to install older dependency
Setup failed for custom integration eufy_security: Requirements for eufy_security not found: ['websocket-client==1.1.0'].

**Expected behavior**

The inteegration should use the same websocket client version HA has to allow this custom integration to properly run

**Additional information**

- Home Assistant Installation Type (OS - Supvervised - Core):  Container
- Home Assistant Core Version:  core-2023.6.1
- Eufy Security Add-on Version: Using container not addon. Latest tag pulled before making this post, though the container itself works perfectly fine and I am using it with go2rtc
- Eufy Security Integration Version:  6.2.0

**Additional context**

I hope I filled everything out correctly, please let me know if I missed anything! Thank you for your time!

**Comment by fuatakgun** [comment]
thanks, done
