### ISSUE TITLE
Schema incompatible

### ISSUE THREAD

**Issue by PutoPunko** [fuatakgun/eufy_security#810]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Updated Eufy security-addon complement to 1.3.0 and Eufy Security to 6.3.0. I am using a doorbell T8200 that was already running and configured. Eufy security Addon log reports schema incompatible error (see logs below). All doorbell entities appear as not available.

**To reproduce**

Update Eufy addon with 

**Expected behavior**

No error

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): HA OS 10.2
- Home Assistant Core Version: 2023.06.1
- Eufy Security Add-on Version: 1.3.0
- Eufy Security Integration Version: 6.3.0
- RSTP Simple server Addon: 0.17.6

Hardware Information;
- Camera Model: T8200

- Live Streaming Protocol (RTSP/P2P): P2p

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- 

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

ADDON LOGS
2023-06-12 09:40:28.863  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-06-12 09:40:33.095  INFO  Push notification connection closed 
2023-06-12 09:40:39.288  INFO  Push notification connection successfully established 
2023-06-12 09:40:39.293  INFO  Push notification connection successfully established 
2023-06-12 09:40:39.368  INFO  Connected to station T8200N00202805AD on host 192.168.1.152 and port 29965 
2023-06-12 09:43:32.582  ERROR Message error 
 Error  
details:
{
  schemaId: 17,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:91 receiveMessage
    src/lib/server.ts:91:27
• server.ts:68 <anonymous>
    src/lib/server.ts:68:53
• node:events:513 emit
    node:events:513:28
• websocket.js:1178 receiverOnMessage
    node_modules/ws/lib/websocket.js:1178:20
• node:events:513 emit
    node:events:513:28
• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14
• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17
• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22
• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10
• writable:391 writeOrBuffer
    node:internal/streams/writable:391:12

INTEGRATION LOGS:
Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:350
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 11 de juny de 2023, a les 21:59:46 (4 occurrences)
Last logged: 11:43:32

Error setting up entry 0.0.0.0 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.6e59e1d75ac64809ad49759e116f146a', 'errorCode': 'schema_incompatible'}

- Would you share your device with me in case further debugging required? (Yes/No): No

**Additional context**

Doorbell was working correctly before update

**Comment by drawgas** [comment]
I can second on this issue using Base station and cameras.
Had to revert to previous version

**Comment by Cl3tus** [comment]
I also have the same issue with a Doorbell and a Base station, had to revert to 6.2.0 as well to get it working again.

**Comment by stewmclarke** [comment]
I too am having the same issue since updating last night...

**Comment by fuatakgun** [comment]
#809
