### ISSUE TITLE
integration failing to start since last update

### ISSUE THREAD

**Issue by pjponymoore** [fuatakgun/eufy_security#811]
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

installed on intel NUC

Integration failing to start since last update(12/6/23)

log file error below

Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:350
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 17:33:23 (1 occurrences)
Last logged: 17:33:23

Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.0e9bfab2204f4cba88817f9aa7ad2508', 'errorCode': 'schema_incompatible'}

tried to re configure but still no luck

should i remove and re install

thanks

paul

**Comment by jacktheseb** [comment]
I have the same Problem. My workaround was a rollback to 6.2.0. After this everything works fine now.

**Comment by b3nnb** [comment]
how do you roll back the version? ive never had to do it

**Comment by DamonNabru** [comment]
I've spent hours testing different versions together and fuatakgun's eufy_security 6.2.0 with bropat's eufy-security-ws 1.3.5 is the latest combination that has ever worked for me with everything in docker containers.

**Comment by calielc** [comment]
Same here. 
Revert back to `6.2.0` and it is working again

**Comment by fuatakgun** [comment]
#809
