### ISSUE TITLE
Getting a schema_incompatible error on v.6.3.0

### ISSUE THREAD

**Issue by yormedia** [fuatakgun/eufy_security#813]
After updating to 6.3.0 I get an initialization error and in the Eufy Add-on an "schema_incompatible" error.
When downgrading to 6.2.0 the error was gone.

`
 Error  
details:
{
  schemaId: 17,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:91 receiveMessage
    src/lib/server.ts:91:27
• server.ts:68 <anonymous>
    src/lib/server.ts:68:53
• node:events:513 emit
    node:events:513:28
• websocket.js:1178 receiverOnMessage
    node_modules/ws/lib/websocket.js:1178:20
• node:events:513 emit
    node:events:513:28
• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14
• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17
• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22
• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10
• writable:391 writeOrBuffer
    node:internal/streams/writable:391:12
`

**Comment by Hagsten** [comment]
Same here

**Comment by Sarnog** [comment]
Same here

**Comment by HunterHuntedHunter** [comment]
Same

**Comment by audun-v** [comment]
Same here.

**Comment by dsh1705** [comment]
Excuse the newbie question, but what is the process to downgrade to 6.2.0?

**Comment by billdwhite** [comment]
same

**Comment by pierre2113** [comment]
i resolved this just yesterday, I noticed the  Eufy Security Add-on   had this message at the bottom of the Info tab.

This repository is deprecated and archived for tracking purposes. Please use this one: https://github.com/bropat/hassio-eufy-security-ws

so I added that url as my new repository, uninstalled the old eufy add on, installed the new add-on 1.5.2  eufy-security-ws.
Trying to configure the new addon I had errors trying to add my info into the options, so i clicked the 3 dots and chose edit yaml  and matched the structure to the one i saw in the Documentation tab of the addon, (copy of structure is pasted below).   
After that I could save and start the addon.    This addon no longer complains schema_incompatible  when I tried to install the Eufy Security Integration.



username: mail@address.com
password: password
country: US
port: 3000
polling_interval: 10
accept_invitations: true
debug: false
event_duration: 10
stations:
  - serial_number: T8010XXXXXXXXXXX
    ip_address: 192.168.0.100

**Comment by birkirb** [comment]
Same here. 
The Security Add On reports

```
2023-06-19 19:21:16.750  ERROR Message error 
 Error  
details:
{
  schemaId: 17,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:91 receiveMessage
    src/lib/server.ts:91:27
• server.ts:68 <anonymous>
    src/lib/server.ts:68:53
• node:events:513 emit
    node:events:513:28
• websocket.js:1178 receiverOnMessage
    node_modules/ws/lib/websocket.js:1178:20
• node:events:513 emit
    node:events:513:28
• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14
• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17
• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22
• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10
• writable:391 writeOrBuffer
    node:internal/streams/writable:391:12
```

And this integration show it like this:

```
Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.06281a7663cc48c2a1afeb006a443bca', 'errorCode': 'schema_incompatible'}
```

Tried downgrading but somehow the HA OS always reverts it, even tried removing and readding but I keep getting the latest version and this error.

**Comment by tekilaguy** [comment]
Same
