### ISSUE TITLE
Failed to setup after update 6.3.0

### ISSUE THREAD

**Issue by sanderhoeppermans** [fuatakgun/eufy_security#819]
After updating to 6.3.0 Home Assistant shows 'Failed to Setup'. I tried to reload the integration and restart Home Assistant. Unfortunately it is still not working.

**Comment by Ditskys** [comment]
same here.
Debug shows me error

2023-06-15 16:34:48.856 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 73, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 106, in _set_products
    self._devices = await self._get_products(ProductType.device, result[MessageField.STATE.value]["devices"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 126, in _get_products
    product = Device(self, serial_no, properties, metadata, commands)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 164, in __init__
    super().__init__(
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 41, in __init__
    self._set_properties(properties)
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 48, in _set_properties
    self.name = properties[MessageField.NAME.value]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'name'

**Comment by hillshome** [comment]
Same problem here failed to start tried everything to sort it. The issue became when I updated the hacs integration.

**Comment by AlanT0803** [comment]
Checking the log, I see:

details:
{
  schemaId: 17,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:91 receiveMessage
    src/lib/server.ts:91:27
• server.ts:68 <anonymous>
    src/lib/server.ts:68:53
• node:events:513 emit
    node:events:513:28
• websocket.js:1178 receiverOnMessage
    node_modules/ws/lib/websocket.js:1178:20
• node:events:513 emit
    node:events:513:28
• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14
• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17
• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22
• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10
• writable:391 writeOrBuffer
    node:internal/streams/writable:391:12

**Comment by sanderhoeppermans** [comment]
> Check pinned issues for schema incompatible one

Sorry, I might not understand this but.. Why was everything working fine before 6.3.0 after the update all the devices are not found. I don't get it.

**Comment by sanderhoeppermans** [comment]
> @sanderhoeppermans what is the context of the question? Are you asking for a technical explanation or will you take action for this to develop it in a better way?

Just a technical explanation. I'm not a developer so maybe I don't get it. In my opinion everything worked fine before the update, after the update I need to insert the bropat (is not working for me because of the 2FA).

**Comment by LukeBH** [comment]
> > @sanderhoeppermans what is the context of the question? Are you asking for a technical explanation or will you take action for this to develop it in a better way?
> 
> Just a technical explanation. I'm not a developer so maybe I don't get it. In my opinion everything worked fine before the update, after the update I need to insert the bropat (is not working for me because of the 2FA).

If you can't replace the eufy add-on for whatever reason, then you can workaround the issue by uninstalling 6.30 of the integration, restarting HA and installing 6.2.0 again instead. I did this before discovering the new add-on and it worked fine for me.

As 6.3.0 has been refactored to work with the add-on maintained by bropat it will no longer work with the old deprecated add-on that fuatakgun previously maintained himself.

**Comment by sanderhoeppermans** [comment]
> > > @sanderhoeppermans what is the context of the question? Are you asking for a technical explanation or will you take action for this to develop it in a better way?
> > 
> > 
> > Just a technical explanation. I'm not a developer so maybe I don't get it. In my opinion everything worked fine before the update, after the update I need to insert the bropat (is not working for me because of the 2FA).
> 
> If you can't replace the eufy add-on for whatever reason, then you can workaround the issue by uninstalling 6.30 of the integration, restarting HA and installing 6.2.0 again instead. I did this before discovering the new add-on and it worked fine for me.
> 
> As 6.3.0 has been refactored to work with the add-on maintained by bropat it will no longer work with the old deprecated add-on that fuatakgun previously maintained himself.

Oke, thanks! I can't find the 6.2.0 version anymore. How did how fixed this? Restore a backup with Eufy 6.2.0 in it?

**Comment by LukeBH** [comment]
@sanderhoeppermans after you have deleted the integration from Devices & Services, go into HACS and delete it there too. Once deleted, restart HA, then go back to HASS and re-install the integration, you can choose 6.2.0 from the version drop down in HACS, then re-add the integration in Devices & Services.

**Comment by fuatakgun** [comment]
If you stick with older versions of add-on or the integration, please do not expect any support.

You can use HACS's redownload functionality to download a specific version without removing

**Comment by simondean** [comment]
@sanderhoeppermans if you have 2 factor authentication (2FA) enabled on the Eufy account you're using with this integration, your issue will probably be the same as issue https://github.com/fuatakgun/eufy_security/issues/795
