### ISSUE TITLE
Entity picture not updating properly in 1.5.2/6.3.0

### ISSUE THREAD

**Issue by jshep321** [fuatakgun/eufy_security#820]
I had implemented a complex automation (node red) to emulate the behavior laid out for updating the entity picture when a motion/person/etc notification is received -- starting the stream(eufy_security.start_p2p_livestream), generate the image (eufy_security.generate.image), and then stopping the stream.

After the update, the entity picture on one of devices (wireless 2k doorbell camera) reverts to an image from the first installation 6 months ago.   The entity picture on the other device (wired 2k doorbell camera) shows a zoomed image of the person detected last.

Same behavior if I manually enter the entity picture URL in a browser (from the entity developer tools details).

When streaming, the streams are up-to-date as expected.

I assume this is not the expected behavior?  

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
-Home assistant OS (rpi 4 hardware)
- Core: 2023.6.2
- Eufy Security Add-on Version: 1.5.2
- Eufy Security Integration Version: 6.3.0

Hardware Information;
Wired 2k doorbell and wireless 2k doorbell (with alarm module)

- Live Streaming Protocol (RTSP/P2P): 
P2P (using addon)

**Comment by fuatakgun** [comment]
Yes, you are right, it is not expected but you should reach out to bropat and get his help to debug the issue. Integration is acting as a gateway between add-on and home assistant user. It is the add-on generating the bytes for the integration

**Comment by robbinonline** [comment]
The release notes of version 6.3 says enable event picture (cd0b2b0)
Has to do something with that, i rollback to 6.2 and everything works.

**Comment by jshep321** [comment]
@bropat should I write an issue for this?

**Comment by fuatakgun** [comment]
Yes, you are right, it is not expected but you should reach out to bropat and get his help to debug the issue. Integration is acting as a gateway between add-on and home assistant user. It is the add-on generating the bytes for the integration

**Comment by sythesigh** [comment]
So, I appear to have the opposite happening. Before the update my doorbell and 2c camera were updating the images and playing video perfectly, now only the doorbell is updating the preview image and the 2c has a preview image from 1 week ago, even after activating streaming for a new image. Both are streaming fine, it’s just the picture image is not updating in the 2c. Have you changed the loacation of the updated image files for the 2c or is this an actual issue?
 Thanks for your time

**Comment by fuatakgun** [comment]
@sythesigh , I had reverted the implementation of preserving images from streaming after streaming is finished as it was implemented as a temporary solution until event images are fixed.

please open a new request for preserving latest image (either from event or stream, whichever comes last), if it makes sense

**Comment by nanard69** [comment]
In the continuity of #847, if i reboot my raspberry the snapshots updates.

**Comment by fuatakgun** [comment]
resolving this, I have separated the camera entity and latest event picture entity. 
latest event picture is received from eufy servers.
camera entity holds latest snapshot event.

**Comment by sythesigh** [comment]
@fuatakgun @bropat thanks guys! That’s sorted both cameras for me. Thank you for your hard work. Much appreciated 👍🏻😁

**Comment by zzricezz** [comment]
@fuatakgun i'm having the same issue, image.**_event_image have an old image but the Camera image show the last capture picture.

How do I get the fix?  Mine was a recent installation so I would assumed the fixed would be part of the new package?
