### ISSUE TITLE
Updating preview image problem with 2c.

### ISSUE THREAD

**Issue by sythesigh** [fuatakgun/eufy_security#823]
I hope I’ve opened this correctly, I am not used to doing this. Anyway, I have linked the issue I am having.             @sythesigh , I had reverted the implementation of preserving images from streaming after streaming is finished as it was implemented as a temporary solution until event images are fixed.

please open a new request for preserving latest image (either from event or stream, whichever comes last), if it makes sense

_Originally posted by @fuatakgun in https://github.com/fuatakgun/eufy_security/issues/820#issuecomment-1594465668_

**Comment by Lempomat** [comment]
Same Problem. After restart new picture available, but updating does not work.

**Comment by fuatakgun** [comment]
@Lempomat , you mean new event images are not being updated or latest snapshot of the latest stream does not stay

**Comment by Lempomat** [comment]
Yes not being updated, when I restart the addon and the integration, the last pictures is coming. Yesterday for example I load the battery from one camera. In the intergartion I saw only the last baatery status, after restart I saw the actual battery load.
Sometimes the addonlog says "normal abort" so after that nothing works.

**Comment by fuatakgun** [comment]
You should reach out to the bropat on add-on issue, integration is acting as an interface between add-on and home assistant.

Moreover, what you are describing is very much different than the first one. There is no benefit of overloading here

**Comment by Lempomat** [comment]
Ok so you mean it is a problem from the addon with the entity updates?
