### ISSUE TITLE
2 of my 13 door/windows sensor do not report the correct state after reboot of HA

### ISSUE THREAD

**Issue by RienduPre** [fuatakgun/eufy_security#824]
Hi,

If have 13 door/windows sensors. The strange ting is that 2 of them allways are in the wrong state after a restart of HA.
They are physically closed and the Eufy app report them correctly, but after the restart they indicate that they are open.
The other 11 sensors do not have this behaviour

When I open and close the 2 faulty sensors after restart they show the correct state immediatally, So they react on the open and close events. But when I close them and restart HA, the indicate open again.

**Additional information**

- Home Assistant Installation Type ( Supvervised ): 
- Home Assistant Core Version: core-2023.6.2
- Eufy Security Add-on Version: 1.5.2
- Eufy Security Integration Version:6.3.0

**Comment by RienduPre** [comment]
Here's my logging

[home-assistant_2023-06-21T13-57-37.583Z.log](https://github.com/fuatakgun/eufy_security/files/11830115/home-assistant_2023-06-21T13-57-37.583Z.log)

**Comment by fuatakgun** [comment]
You know, what I am doing now, reading all logs about all your devices (around 18 different one) with unique serial numbers and trying to figure out all the history here. but why would I spend time on understanding which of your devices are having issues and which of them are working fine? Even you are not bothered to put more context here, but I am supposed to find it myself. 

Sorry, I prefer not to do.

**Comment by RienduPre** [comment]
Sorry you're right.
Below are the 2 sensors with the issue

name': 'Woonkamer Deur Links', 'model': 'T8900', 'serialNumber': 'T8900P0022340A1F
name': 'Bijkeuken Deur', 'model': 'T8900', 'serialNumber': 'T8900P002235084D'

I hope you are still willing to help me

Thanks,
Rien
