### ISSUE TITLE
Motion detected binary sensor created as a switch

### ISSUE THREAD

**Issue by patrickli** [fuatakgun/eufy_security#827]
**Describe the bug**

I have a T8422 that works mostly fine. However I noticed one odd thing. On the device page for HA there is a "Motion Detection" switch that is always off. The entity id for this switch is `switch.floodlight_motion_detection_2`. When toggling this switch, an error pops up:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/config/custom_components/eufy_security/switch.py", line 52, in async_turn_on
    await self.product.set_property(self.metadata, True)
  File "/config/custom_components/eufy_security/eufy_security_api/product.py", line 70, in set_property
    await self.api.set_property(
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 196, in set_property
    await self._send_message_get_response(
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'device.set_property.0a4da975e1fd4d2981b9ef8694d3b02a', 'errorCode': 'device_invalid_property'}
```

<img width="332" alt="image" src="https://github.com/fuatakgun/eufy_security/assets/502326/bf254c0b-ae98-4c8a-972b-bfc86f315c38">

Meanwhile there is another switch `switch.floodlight_motion_detection` in the configuration section that will correctly turn motion detection on/off.

Digging a bit further, in `core.entity_registry` file, the motion detected 2 switch appears as follows:

```
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "<id>",
        "device_class": null,
        "device_id": "<id>",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "switch.floodlight_motion_detection_2",
        "hidden_by": null,
        "icon": null,
        "id": "<id>",
        "has_entity_name": false,
        "name": null,
        "options": {},
        "original_device_class": "motion",
        "original_icon": null,
        "original_name": "Floodlight Motion Detection",
        "platform": "eufy_security",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "eufy_security_T8422N<ID>_device_motionDetected",
        "unit_of_measurement": null
      }
```

While the working motion detection switch is:

```
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "<id>",
        "device_class": null,
        "device_id": "<id>",
        "disabled_by": null,
        "entity_category": "config",
        "entity_id": "switch.floodlight_motion_detection",
        "hidden_by": null,
        "icon": null,
        "id": "<id>",
        "has_entity_name": false,
        "name": null,
        "options": {},
        "original_device_class": null,
        "original_icon": null,
        "original_name": "Floodlight Motion Detection",
        "platform": "eufy_security",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "eufy_security_T8422N<ID>_device_motionDetection",
        "unit_of_measurement": null
      }
```

There are 2 main differences:
* The end of `unique_id` field is `motionDetected` for switch 2 and `motionDetection` for the working switch.
* `original_device_class` is `motion` for switch 2.

The 2 differences above makes the switch 2 looks closer to the person detected binary sensor than a switch.

Based on the information above I believe this switch should be a binary sensor called `Motion detected` with type `motion`, similar to the `Person detected` motion sensor.

Another fact supporting this is there should be 2 binary sensors available, one for motion and one for person, but the motion one is not there.

It is related to #677 but there are too many noises in that ticket. So creating a new one.

**To reproduce**

N/A

**Expected behavior**

A `motion detected` binary sensor is available and no extra `motion detection` switch appears.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Container
- Home Assistant Core Version: 2023.6.2
- Eufy Security Add-on Version: 1.5.2
- Eufy Security Integration Version: 6.3.1

Hardware Information;
- Camera Model:
T8422

- Live Streaming Protocol (RTSP/P2P): P2P

**Comment by fuatakgun** [comment]
can you remove these lines from your own local files and restart home assistant and let me know the results?

https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/eufy_security_api/product.py#L52-L53

you should remove these;

```
            if key == "motionDetected" and metadata.name == "motionDetection":
                metadata.name = key
```

**Comment by patrickli** [comment]
The extra switch has disappeared. But there is no new binary sensor appearing.

**Comment by patrickli** [comment]
BTW there are also 2x "Trigger Alarm" and "Reset Alarm" buttons. Not sure if they are related.

**Comment by patrickli** [comment]
Following up this topic, when the above is done, I get an error message in the logs.

```
Platform eufy_security does not generate unique IDs. ID eufy_security_T8422Nxxxxxxx_device_motionDetection already exists - ignoring switch.floodlight_motion_detection
```

**Comment by fuatakgun** [comment]
I cannot help without debug logs

**Comment by fuatakgun** [comment]
there is nothing wrong on above state, right?

you need to share the debug logs.

**Comment by patrickli** [comment]
> there is nothing wrong on above state, right?
> 
> you need to share the debug logs.

Which exact debug logs are you talking about? Is there any instructions?

**Comment by fuatakgun** [comment]
Yes, in bug template

**Comment by patrickli** [comment]
Alright. Upgraded the module to 7.0.1. Here is the log.
[home-assistant_2023-08-04T03-33-53.923Z.log](https://github.com/fuatakgun/eufy_security/files/12256764/home-assistant_2023-08-04T03-33-53.923Z.log)

**Comment by fuatakgun** [comment]
please follow here, I cannot solve it from library. https://github.com/bropat/eufy-security-client/issues/354
