### ISSUE TITLE
Alarm Control Panel status of HomeBase 3

### ISSUE THREAD

**Issue by z-master42** [fuatakgun/eufy_security#828]
**Describe the bug**

Since the change to the latest version (I think 6.3.1), we have to switch to the addon version of @bropat, since you have now clearly split the development (at least that's what I understood). I have since had the problem that the Alarm Panel status of my HomeBase (T8030) is always Unknown. No matter if I try to change it in Home Assistant or the Eufy App.

**To reproduce**

Check status of alarm_control_panel sensor.

**Expected behavior**

The alarm control panel sensor shows the actual status and this can also be changed using the corresponding buttons in Home Assistant.

**Additional information**

- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: 2023.6.2
- Eufy Security Add-on Version: 1.5.2
- Eufy Security Integration Version: 6.3.1

Hardware Information;
- Camera Model: T8030

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
No errors related to this model.

**Comment by fuatakgun** [comment]
please follow bug template and generate logs from home assistant

**Comment by z-master42** [comment]
Okay...
What I hadn't tried before was simply restarting the addon. Now it works again.

Sorry for the inconvenience.
