### ISSUE TITLE
doorbell video stream will not start if set to any other port other than 8554

### ISSUE THREAD

**Issue by Menz01** [fuatakgun/eufy_security#829]
For me to be able to run the RTSP Simple Server on my HA i need to have it on a port other than the default 8554. so i set it to 9554 and the RTSP Simple server starts without issue. However, if i set the Eufy Security to stream to any other port other than 8554, the stream will not start and hangs at "preparing"

![image](https://github.com/fuatakgun/eufy_security/assets/31291495/e4769794-c7dc-411b-a1c0-746fc791874b)

how can i get it to accept that the simple server is on a different port other than 8554?
![image](https://github.com/fuatakgun/eufy_security/assets/31291495/f678bce4-913e-4489-87fa-b3e2229f9271)

**Comment by cms365** [comment]
following as I can’t seem to get this working either.

**Comment by fuatakgun** [comment]
By the way, follow the issue template and share the home assistant logs

**Comment by Menz01** [comment]
[402f1039_eufy_security_ws_2023-06-20T23-36-17.043Z.log](https://github.com/fuatakgun/eufy_security/files/11809144/402f1039_eufy_security_ws_2023-06-20T23-36-17.043Z.log)

**Comment by Menz01** [comment]
> By the way, follow the issue template and share the home assistant logs

if i did it right, the log should be in the post above

**Comment by fuatakgun** [comment]
@Menz01 did you follow the bug template? these logs are from add-on, not the integration

**Comment by Menz01** [comment]
> @Menz01 did you follow the bug template? these logs are from add-on, not the integration

i did follow the template it says....

![image](https://github.com/fuatakgun/eufy_security/assets/31291495/012f54b4-dc26-4e43-bc22-8b64add0463c)

and that is where i got the logs from... the addon page

**Comment by Menz01** [comment]
is this what you mean?
[homeassistant log.txt](https://github.com/fuatakgun/eufy_security/files/11826029/homeassistant.log.txt)

**Comment by fuatakgun** [comment]
Looks good, can you also send the screenshot from rtsp addon config page and logs?

**Comment by Menz01** [comment]
i replied to the email with the screenshot and the log file... i dont see that here does that mean it did not send?

**Comment by CaseyRo** [comment]
I've created a "workaround" since I drilled down the issue to the following:

1. I use WebRTC for the display of the videocard. Apparantly [they have moved from RTSPtoWebRTC to go2rtc](https://github.com/AlexxIT/WebRTC). 
2. This change broke my mediaitx (really simple RTSP server) config. (same ports used)
3. fine, I changed the port - running it on 8556 now.
4. I see dead people again, but the stream state was still _PREPARING_ as many here had as well.

So I updated the conditional card, instead of using the camera state (this doesn't change from idle) I'm using the 'stream server' sensor (kitchen in my case, change accordingly):

<img width="644" alt="image" src="https://github.com/fuatakgun/eufy_security/assets/6368490/97b16941-1521-4278-b4e1-f65cbcb3a726">

**Comment by Menz01** [comment]
> I've created a "workaround" since I drilled down the issue to the following:
> 
> 1. I use WebRTC for the display of the videocard. Apparantly [they have moved from RTSPtoWebRTC to go2rtc](https://github.com/AlexxIT/WebRTC).
> 2. This change broke my mediaitx (really simple RTSP server) config. (same ports used)
> 3. fine, I changed the port - running it on 8556 now.
> 4. I see dead people again, but the stream state was still _PREPARING_ as many here had as well.
> 
> So I updated the conditional card, instead of using the camera state (this doesn't change from idle) I'm using the 'stream server' sensor (kitchen in my case, change accordingly):
> 
> <img alt="image" width="644" src="https://user-images.githubusercontent.com/6368490/249574547-97b16941-1521-4278-b4e1-f65cbcb3a726.png">

i would like to use WebRTC but everytime i install it, the eufy Security Addon that requires the RTSP Simple Server addon would stop working. i tries changing the port (see pics above) but the if i change the port on the RTSP Simple Server my doorbell camera will not start the stream and remains on "preparing" i have sent everything that @fuatakgun asked for so i am waiting on his reply. i would rather use the WebRTC since it works for all my other cameras but i also want my only security camera (my doorbell camera) to work too
