### ISSUE TITLE
Support for SmartDrop - T8790

### ISSUE THREAD

**Issue by Tomcatter31** [fuatakgun/eufy_security#830]
Are there any plans for the T8790 to be supported with this addon?

I am mainly looking for an alert if the lock is opened and the ability to open the smartdrop

**Comment by ebroder** [comment]
It looks like `eufy-security-ws` just added support for the T8790 (https://github.com/bropat/eufy-security-ws/releases/tag/1.8.0), which includes a handful of new properties and commands. It looks like that mostly worked with this integration out of the box, but is still missing support for the new properties and commands that were introduced - does it make sense to re-open this ticket to include support for those?

**Comment by Tomcatter31** [comment]
I'll be happy to test it.

**Comment by Briadark** [comment]
@fuatakgun , like @ebroder shared some time ago the T8790 is now supported with a lot of new properties and commands, is this anything you would be able to look into?

If it helps I would love to share access to my device with you and help with some debugging.

I also discovered a small issue regarding the Package Delivered sensor, this only updates when I restart the eufy-security-ws addon, I'm not completely sure where to report this.

Hope you can help :)

**Comment by ZaeGitHub** [comment]
I have the same issue as @Briadark above. Package Delivered never seems to update without restarting the addon.
