### ISSUE TITLE
Upgraded to 6.3.1 caused integration to fail

### ISSUE THREAD

**Issue by andypburke** [fuatakgun/eufy_security#831]
After upgrading to 6.3.1 the Eufy Security integration fails to setup

<img width="264" alt="image" src="https://github.com/fuatakgun/eufy_security/assets/4771045/89c16a3a-1420-4adb-974b-ff954b4cd2da">

<img width="595" alt="image" src="https://github.com/fuatakgun/eufy_security/assets/4771045/fe25c526-ca4d-4b2e-845b-1d2e5838eda8">

Hardware Information;
- Camera Model: 2K Wireless Doorbell

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:350 
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues)) 
First occurred: 09:57:31 (5 occurrences) 
Last logged: 11:31:21

Error setting up entry Eufy Security for eufy_security
Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.ff03b0a4f7114ee58660dff0d31d296e', 'errorCode': 'schema_incompatible'}
- Home Assistant Installation Type (OS - Supvervised - Core): 
- Home Assistant Core Version: 
- Eufy Security Add-on Version: 
- Eufy Security Integration Version:

**Comment by hanksteen** [comment]
I have the same issue.
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.b5f7a1817c614f0cb30bcef3b9e81df5', 'errorCode': 'schema_incompatible'}

**Comment by Eyeanman** [comment]
not sure "closed this as not planned" means... but can see others have had the same issue (and issue closed with same response) - however they found that whilst the addon was showing that it was up-to-date, if you went into it there was a comment to say its now depreciated, 

Removing that repository from the addons and adding https://github.com/bropat/hassio-eufy-security-ws worked for me

**Comment by fuatakgun** [comment]
@Eyeanman it means, all should check for existing issues before creating a new one. I have also pinned one issue and writing a response is becoming tiring.
