### ISSUE TITLE
image: /api/camera_proxy/camera.entrance Doesn't Work for me

### ISSUE THREAD

**Issue by run99nerff** [fuatakgun/eufy_security#834]
image: /api/camera_proxy/camera.entrance
This doesn't seem to work for me .. based on the source code, I believe that it should be in this format:
image: /api/camera_proxy_stream/camera.doorbell?token=71a11c170d67a4314c535c8bdec997fb36a60e4f3e23394919a5e10b10394ce7
If this isn't an issue, please let me know how to get the token value that is used within Home Assistant.
Thank you for your program .. I love my doorbell camera with Home Assistant!
-Jason

**Comment by fuatakgun** [comment]
It should work, check here: https://companion.home-assistant.io/docs/notifications/dynamic-content/#camera-stream

It is working fine locally for me.

**Comment by fuatakgun** [comment]
I think you are right, Android and iOS seem to be acting differently.

https://companion.home-assistant.io/docs/notifications/notification-attachments/#automatic-snapshots

Please check, find the correct way and raise a change request to fix the documentation

**Comment by kvanbiesen** [comment]
it works fine for me.....when using the companion app to send a notification.

there i can use /api/camera_proxy/camera.doorbell

but when i want to use telegram, for some reason it doesnt work and i have to use the token. or use the full url to my homasssiant + camera.doorbell --> "https: //<my own domain<:8123"+camera.door"


But for now i am using the companion appwhich seems to do what i want for now.

**Comment by kvanbiesen** [comment]
While this was working 2 weeks ago, and still is working; it has some 2 weeks old picture. it doesnt update the snapshot anymore?

**Comment by fuatakgun** [comment]
@kvanbiesen : https://github.com/fuatakgun/eufy_security/issues/847
