### ISSUE TITLE
Problem with T8213 - IP for stream is wrong (boolean)

### ISSUE THREAD

**Issue by DodoTheDuck** [fuatakgun/eufy_security#837]
**Describe the bug**

I installed eufy_security for HomeAssistant using HACS. Everything works great but I seem to not be able to get a camera stream. I suspect the URL to be faulty, for logging shows:

2023-06-30 11:58:14.127 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtspt://False:8554/T8213P21230322C6

False probably comes from the configuration page of the integration, show only a checkbox. 
<img width="464" alt="image" src="https://github.com/fuatakgun/eufy_security/assets/30998176/c5bb815f-96d2-4133-b5ed-a3abc04265ff">

Is there a configuration.yaml where I can enter the IP? And if there is, where can I find it?

**To reproduce**

Install eufy-security integration using HACS.

**Expected behavior**

I except an IP instead of a boolean.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Container
- Home Assistant Core Version: core-2023.6.1
- Eufy Security Add-on Version: -> Container, so no Addon
- Eufy Security Integration Version: -> no idea, but i installed it just two weeks ago

Hardware Information;
- Camera Model: T8213 (dual doorbell)

- Live Streaming Protocol (RTSP/P2P): 
none yet, but the camera entity allwos for "start p2p stream" (not working because of IP)
(edit: see description url, the protocol rtspt:// seems like RTSP)

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
see description

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
see description

- Would you share your device with me in case further debugging required? (Yes/No): 
Yes

**Additional context**

If you need more logs, I can post the whole bunch. Let me know. It's a lot.

**Comment by kvanbiesen** [comment]
Looks like you skipped point 2 of the installation guide:
https://github.com/fuatakgun/eufy_security#installation

I am running latest verison of the addon and i have indeed a box for entering and ip (should be 127.0.0.1), so in my op

i run hassos

**Comment by DodoTheDuck** [comment]
I do not have the addon. I am using HA from a container. I installed the Eufy-Security-Integration using HACS. 

I did not skip step 2, and I got the RTSP (also as a container) running with logs looking like they should (basically mirroring the logs from step 2)

**Comment by DarkAllMan** [comment]
I have the same issue.
I installed the Eufy-Security-Integration using HACS.
I installed the RTSP Simple Server via then Add-on Store
The RTSP Simple Server is running.
But I have no video stream and I have no new log entries on teh RTSP Simple Server

**Comment by DodoTheDuck** [comment]
My issues is the log entry 

 2023-06-30 11:58:14.127 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtspt://False:8554/T8213P21230322C6

More specifically the wrong URL -> rtspt://False:8554/T8213P21230322C6 containing the boolean value "False", which should be an IP-adress. 

Could someone tell me, where the config for the Eufy-Security Integration is located? Then I could probably figure it out for myself 😄

**Comment by DarkAllMan** [comment]
Where did you find this log entry?
BTW, my other camera's work just fine. Only 2 T8210 are not showing stream.
![image](https://github.com/fuatakgun/eufy_security/assets/1582343/a4b93ed5-babe-4e35-b3f6-91c8b3b7ce1c)

**Comment by DodoTheDuck** [comment]
In the default/normal HomeAssistant Log on the :8123 page. 

Can anyone help me?

**Comment by DodoTheDuck** [comment]
Reinstalled it multiple times. Restarted HA (complete container) after removal and after download. Checked the "custom_components" folder, everything was as expected. 

Still I can't enter an URL ->
![image](https://github.com/fuatakgun/eufy_security/assets/30998176/a6cb8e69-1ce0-4be7-b1e6-c34919ff8e68)
