### ISSUE TITLE
Camera images have small resolution

### ISSUE THREAD

**Issue by benjani85** [fuatakgun/eufy_security#839]
I have 2 Eufy Cam 2C Pros running the latest version of the integration and the entity_picture attribute URL seems to retrieve the "Dectected by Local AI" image from the Eufy app if its available rather than the larger resolution still image above it in the app.

Is it possible to choose the larger better quality image rather than the "Dectected by Local AI" one as that is zoomed in pixelated.

**Comment by kvanbiesen** [comment]
Wondering the same thing on the doorbell.

The thumbnail is working and showing. but its very low quality and it crops kinda weird. Is there a way to overrule the cropping downscaling and keep full screen picture?

In the Eufy app the picture is 'full quality', is it possible to keep this picture as the thumbnail in stead of the generated image.

Or just disable the crop somewhere in the code. Have skimmed tru code and cant really find something or is this a bropat or home assisstant thing?

**Comment by fuatakgun** [comment]
integration just relies on add-on generated image bytes, it is not processing anything here, let's resolve this in eufy-security-ws
