### ISSUE TITLE
Guard Mode 6 (Wall Panel Off not working)

### ISSUE THREAD

**Issue by WvanWaas** [fuatakgun/eufy_security#840]
Off (6) and Disarmed (63) are two different states. 

```
2023-07-04 06:18:55.666  INFO  Alarm mode for station T8010P2320502556 changed to: undefined
2023-07-04 06:19:03.349  INFO  Received push notification for changing guard mode 
{
  guard_mode: 6,
  current_mode: 6,
  stationSN: 'T8010P2320502556'
}
2023-07-04 06:46:40.460  INFO  Alarm mode for station T8010P2320502556 changed to: HOME 
2023-07-04 06:46:42.815  INFO  Alarm mode for station T8010P2320502556 changed to: undefined 
2023-07-04 06:46:46.107  INFO  Received push notification for changing guard mode 
{
  guard_mode: 1,
  current_mode: 1,
  stationSN: 'T8010P2320502556'
}
2023-07-04 06:52:50.155  INFO  Alarm mode for station T8010P2320502556 changed to: DISARMED 
2023-07-04 06:52:53.599  INFO  Received push notification for changing guard mode 
{
  guard_mode: 63,
  current_mode: 63,
  stationSN: 'T8010P2320502556'
}
```
Current logs show a cycle from:
Off (Panel Button) = 6
Armed Home = 1
Home Assisant Disarmed = 63

As soon as you change the panel by hand or app to 6 (Off) the status get's undefined for Home Assistant.

The other way around dissarm gives a full led on on the panel for all day this looks like an error state to the user.

Error State:
![Alarm Disarmed](https://github.com/fuatakgun/eufy_security/assets/1444457/361b0f64-2224-4b13-a1a3-c4df82f60ab2)

**Expected behavior**
Off should be an added state or I need a way to send the 6 signal myself. And create an alternative alarm panel manually. 

Correct expected State:
![Alarm Off](https://github.com/fuatakgun/eufy_security/assets/1444457/ba376504-7c86-4099-ad43-c58897604097)

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Installation Type: Home Assistant OS
- Home Assistant Core: core-2023.6.3
- Eufy Security Add-on Version: eufy-security-ws (1.5.2)
- Eufy Security Integration Version: v6.3.1

Thanks for running this integration I love it but I want my off button back (it was working earlier when we had fixed an issue alike before)

**Comment by WvanWaas** [comment]
Back in the day we had and fixed this issue it's the same sensor state / guard state again. 
https://github.com/fuatakgun/eufy_security/issues/645

**Comment by fuatakgun** [comment]
Are you sure you can send Off state from mobile app? or, is it specific to physical device?

I do not remember adding an Off button to integration rather I had mapped the Off state to Disarmed inside Home Assistant.

If you use keypad and set it off, Home Assistant would present it as Disarmed.

Also, share the attributes from alarm_control_panel and share the debug logs

**Comment by kvanbiesen** [comment]
Same here,

There is a guard mode "Off" in the attributes of the control panel. It follows the settings from the app.
I can change it from the control panel device to "AWAY" and "OFF" and vice versa. Works

The attribute state of the panel is disarmed in HA states.

Using the alarm_control_panel -> alarm disable sets it to disarmed instead to off. 
use the app to change the settings to change the state to off -> in the log you get

"2023-08-08 15:06:01.715  INFO  Alarm mode for station T8010P2322044049 changed to: undefined "

But if you look at the device itself, it changes it to off in the properties.... and in the app.

Home Assistant state says disarmed. cause it catches this in line 

```
if current_mode == KEYPAD_OFF_CODE:
            return CurrentModeToStateValue[CurrentModeToState.DISARMED.name].value
```

it seems like it used to be in there.....but now its gone.

https://github.com/fuatakgun/eufy_security/issues/199

But the lines of adding the actual state to off gone missing, ofcourse, this option is only available for people with a keypad.


**_CURRENT WORKAROUND if you use node red or whatever:_** 

**dont use alarm_control_panel - alarm_disarm.**

Domain: select
service= select_option
entity= select.xxx_guard_modes

data = {"option":"Off"}


//fo the moment no access to decent logs, at phone and clumpsy to type/debug logs

**Comment by kvanbiesen** [comment]
Should be fixed in latest update. Pushed a PR yesterday to fix it.

IT should handle it automaticly, for scripting use alarm_off under eufy_security domain.

**Comment by WvanWaas** [comment]
Thanks @kvanbiesen I will try tonight and report back

**Comment by WvanWaas** [comment]
> Also, share the attributes from alarm_control_panel and share the debug logs I will do this 

tonight just for reference

**Comment by WvanWaas** [comment]
All good it's even possible to set this state from notifications and widgets now I am so happy thanks for the fix.
