### ISSUE TITLE
Support for T84A1 (S100 Wall Light Cam)

### ISSUE THREAD

**Issue by lethyro85** [fuatakgun/eufy_security#842]
Support for T84A1 (S100 Wall Light Cam) does not exist.
I want support for this cam :)
![image](https://github.com/fuatakgun/eufy_security/assets/100494260/a92e3adc-4c0b-4eec-b197-0ee56a5dc75a)

**Comment by tne7laa** [comment]
After finally installed everything I did see UNSUPPORTED message.  :-(
So +1 for this

**Comment by fuatakgun** [comment]
There is nothing i can help here, please get support from @bropat
