### ISSUE TITLE
Support for S300 SmartDrop

### ISSUE THREAD

**Issue by julianrinaldi** [fuatakgun/eufy_security#844]
It would be great to have support for the S300 SmartDrop in the form of a camera feed and two way audio and the ability to open the box. While the camera is battery powered, it can be plugged in so you can stream it without worrying about battery life. But because of this it doesn't provide the ability to get an RTSP stream. At the minimum it  would be great if we were able to open the package box door remotely, which would be extremely useful.

**Comment by fuatakgun** [comment]
it needs to be supported here: https://bropat.github.io/eufy-security-client/#/supported_devices

**Comment by ZaeGitHub** [comment]
The SmartDrop S300 is now listed on there, and the camera feed does work, but... The "Package Delivered" sensor doesn't ever seem to work. How is this pulled in? In the Eufy app, I show a package delivered at 11:10 AM but it didn't update the sensor until 6PM. Before today, it's never updated the sensor ever (my recorder history even shows it never changing).
