### ISSUE TITLE
Unable to update snapshots in Lovelace card

### ISSUE THREAD

**Issue by andypburke** [fuatakgun/eufy_security#847]
Hi - I have looked around previous issues but can't find a solution to my problem, so hope it is appropriate to raise here.

I have created the Lovelace card for my Eufy cameras and all works well, apart from the image never updates.  What code do I need to insert to refresh the image?  Code is below.

`square: false
columns: 1
type: grid
cards:
  - type: conditional
    conditions:
      - entity: camera.kitchen_camera
        state: idle
    card:
      show_state: true
      show_name: true
      type: picture-entity
      entity: camera.kitchen_camera
      camera_image: camera.kitchen_camera
      tap_action:
        action: call-service
        service: camera.turn_on
        data: {}
        target:
          entity_id: camera.kitchen_camera
  - type: conditional
    conditions:
      - entity: camera.kitchen_camera
        state: streaming
    card:
      type: vertical-stack
      cards:
        - show_name: true
          show_icon: false
          type: button
          tap_action:
            action: call-service
            service: camera.turn_off
            data: {}
            target:
              entity_id: camera.kitchen_camera
          entity: camera.kitchen_camera
          name: Stop
        - type: custom:webrtc-camera
          entity: camera.kitchen_camera
`

Thanks for any help

**Comment by marcokitzmann** [comment]
Same here.

**Comment by Ulli2k** [comment]
Same here

**Comment by alruallm** [comment]
Same here

**Comment by nanard69** [comment]
I have the same issue. But if i restart Home Assistant, the image refresh.

**Comment by andypburke** [comment]
That didn't work for me.  Still seems to have the snapshot from the initial
setup.  Anyone got any ideas on what setting to change to fix?

**Comment by fuatakgun** [comment]
I have 5 different eufy cameras at home.
4 pieces of 2c cameras.
1 piece of indoor ptz camera.
3 of 2c cameras are working perfectly to update the snapshots, except one and I do not know why?
indoor ptz camera is also working fine even though without a sd card.

integration is acting as pass-through between add-on and home assistant, it is not doing any image generation, please work with bropat to find out the root cause, it would help many people.

**Comment by fuatakgun** [comment]
thanks @golles

**Comment by fuatakgun** [comment]
merging into here: https://github.com/fuatakgun/eufy_security/issues/820
