### ISSUE TITLE
Support for T84A1 (S100 Wall Light Cam) 

### ISSUE THREAD

**Issue by lethyro85** [fuatakgun/eufy_security#849]
Support for T84A1 (S100 Wall Light Cam) does not exist.
I want support for this cam :)
![image](https://github.com/fuatakgun/eufy_security/assets/100494260/76af8b6f-6732-451e-beb6-aa78821b2209)

**Comment by lethyro85** [comment]
.

**Comment by lethyro85** [comment]
.

**Comment by rickhuizinga** [comment]
Same

**Comment by fuatakgun** [comment]
wait for this to be completed: https://github.com/bropat/eufy-security-client/issues/318
nothing required from integration side, it needs support from add-on
