### ISSUE TITLE
Download video at the same time of the picture

### ISSUE THREAD

**Issue by Caez83** [fuatakgun/eufy_security#853]
Is it possible to add an option to download a video instead of just an image?

This could make it possible to add automations to externalise the video stream captured on other servers.

Thank you

**Comment by fuatakgun** [comment]
When motion/person type events are triggered, camera starts recording but video would not be available until recording is finished, which depends on the event duration. So, in short, we cannot download the image in parallel but we might have an option to download latest video event (after recording is over) and it could be accessible over home assistant.

**Comment by Caez83** [comment]
Hello,

Thanks for your feedback. 

Yes, it could be a trigger that runs every X minutes to check if a new video is available, or even to run automatically X minutes after the event is triggered.

I'm using wireless models and the video record lasts 30s, the time being known.

The main aim is to be able to archive videos outside the local network.

**Comment by fuatakgun** [comment]
it is not feasible as of now, given that add-on does not support accessing to stored video files
