### ISSUE TITLE
HA 2023.8 Beta 0 break integration

### ISSUE THREAD

**Issue by m7r** [fuatakgun/eufy_security#855]
**Describe the bug**

Integration will not load. Error in Log:

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:619
Integration: Schalter (documentation, issues)
First occurred: 27. Juli 2023 um 16:13:19 (2 occurrences)
Last logged: 27. Juli 2023 um 16:13:19

Error adding entities for domain switch with platform eufy_security
Error while setting up eufy_security platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'hardware'

**To reproduce**

1. Update to HA 2023.8 beta
2. check the log
3. See error

**Expected behavior*

Integration will add all entities

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: 2023.8 beta 0
- Eufy Security Add-on Version:  1.5.2-1
- Eufy Security Integration Version: 6.3.1

Hardware Information;
- Camera Model: Eufycam 2c
- Live Streaming Protocol (RTSP/P2P): RTSP
- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No): 

**Additional context**

Add any other context about the problem goes here.

**Comment by Cheerpipe** [comment]
As a workaround, remove the following lines until a better or official fix.

https://github.com/fuatakgun/eufy_security/blob/82092da65ee13ea996705cc7b48b7da1de5c5382/custom_components/eufy_security/util.py#L63-L64

**Comment by m7r** [comment]
Workaround work on my side too 👍🏻

**Comment by Prash1407** [comment]
This workaround worked from me too! Thanks

**Comment by fuatakgun** [comment]
let me keep this open until someone confirms

**Comment by buzurk26** [comment]
Work around fixed it for me too

**Comment by adam-cobb** [comment]
I don't appear to have a util.py in that folder to try the workaround, am I missing something?

**Comment by fuatakgun** [comment]
Having the latest version of integration and home assistant should fix it automatically, no need to play with files manually.

**Comment by MarshallRDC** [comment]
> Having the latest version of integration and home assistant should fix it automatically, no need to play with files manually.

Hello @fuatakgun ,
Just as An fyi, I  had this issue since latest HA update as well (don't know if it was OS or HA version since I did them right achter each other). After Modifying the util.py file everything worked again. I had latest integration and add-on installed.

BR,
Robin

**Comment by fuatakgun** [comment]
Which line did you remove exactly?

**Comment by MarshallRDC** [comment]
> As a workaround, remove the following lines until a better or official fix.
> 
> https://github.com/fuatakgun/eufy_security/blob/82092da65ee13ea996705cc7b48b7da1de5c5382/custom_components/eufy_security/util.py#L63-L64

@fuatakgun like in this post.

**Comment by fuatakgun** [comment]
These lines do not exist anymore on the latest version of integration. How can you remove non-existent lines from code???

**Comment by MarshallRDC** [comment]
OH wow, I've just noticed eufy security was not Listed in HACS anymore, so probably didn't update for a while 🙈 my bad... Good I found out now 😅 sorry for the inconvenience and thanks for your support.
