### ISSUE TITLE
Eufy Security Wont Load

### ISSUE THREAD

**Issue by ifflanb** [fuatakgun/eufy_security#856]
Getting the below in my logs and Eufy Security won't load after restarting my Eufy Dual wired Doorbell and HA.

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:619
Integration: Binary sensor (documentation, issues)
First occurred: 1:22:46 PM (4 occurrences)
Last logged: 1:25:20 PM

Error adding entities for domain binary_sensor with platform eufy_security
Error while setting up eufy_security platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'hardware'

**Comment by m7r** [comment]
For a workaround see issue #855
