### ISSUE TITLE
Integration stuck on initialising

### ISSUE THREAD

**Issue by Mrdjg** [fuatakgun/eufy_security#857]
Hi,

I'm trying to set the sup. The integration keeps getting stuck on initialising. 

I have made sure that the 'trusted_device_name' field is populated (fix for other similar reported bugs) but this has not resolved the problem.

Thanks! 

Have found the following in logs: 

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:350 
Integration: Eufy Security (documentation, issues) 
First occurred: 15:11:39 (1 occurrences) 
Last logged: 15:11:39

Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 73, in connect
    await self._set_products()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 100, in _set_products
    result = await self._start_listening()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 147, in _start_listening
    return await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.start_listening))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

Logs from add-on:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-07-28 14:15:10.046  DEBUG [EufySecurity._initializeInternals] No stored data from last exit found 
2023-07-28 14:15:10.055  DEBUG [EufySecurity._initializeInternals] Handling of driver update 
{
  currentVersion: 2.62,
  previousVersion: 0
}
2023-07-28 14:15:10.787  DEBUG [undefined.constructor] Loaded API_BASE: https://security-app-eu.eufylife.com 
2023-07-28 14:15:10.804  DEBUG [EufySecurity._initializeInternals] Load previous login_hash: 6abf0d836383829777aa85f83aa4a548 
2023-07-28 14:15:10.808  DEBUG [EufySecurity._initializeInternals] Generated new openudid: 5b01be82f15e8767 
2023-07-28 14:15:10.811  DEBUG [EufySecurity._initializeInternals] Generated new serial_number: d336568b3a13 
2023-07-28 14:15:10.948  DEBUG [EufySecurityServer.start] Starting server on host 0.0.0.0, port 3000 
2023-07-28 14:15:10.956  INFO  [EufySecurityServer.start] Eufy Security server listening on host 0.0.0.0, port 3000 
2023-07-28 14:15:10.962  DEBUG [HTTPApi.login] Login and get an access token 
{
  token: null,
  tokenExpiration: null
}
2023-07-28 14:15:10.969  DEBUG [HTTPApi.request] Request: 
{
  method: 'post',
  endpoint: 'v2/passport/login_sec',
  responseType: undefined,
  token: null,
  data: {
    ab: 'GB',
    client_secret_info: {
      public_key: '048272d884cca009b764d79a1c7cf4e91221c8852dd451f3cd6ed53c24ead4a8d164f18af69794a245236376fba6ac2588a8421c7de0e28d40aafd54b9cd60c1e7'
    },
    enc: 0,
    email: 'darrensspam@live.co.uk',
    password: '[***]',
    time_zone: 3600000,
    transaction: '1690553710967'
  }
}
2023-07-28 14:15:11.125  DEBUG [HTTPApi.request] Response: 
{
  token: null,
  request: {
    method: 'post',
    endpoint: 'v2/passport/login_sec',
    data: {
      ab: 'GB',
      client_secret_info: {
        public_key: '048272d884cca009b764d79a1c7cf4e91221c8852dd451f3cd6ed53c24ead4a8d164f18af69794a245236376fba6ac2588a8421c7de0e28d40aafd54b9cd60c1e7'
      },
      enc: 0,
      email: 'darrensspam@live.co.uk',
      password: '[***]',
      time_zone: 3600000,
      transaction: '1690553710967'
    }
  },
  response: {
    code: 100032,
    msg: 'Failed to request.',
    data: {
      captcha_id: '0118ead5-4569-47e7-ac2e-cebd62f7a098',
      item: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAArCAIAAACGv1O8AAAK1UlEQVR4nOyaa1Ab5ffHdzfZzYbdlBCgIVzCZdpamxigFdKLIkWHUoap2tqpaXWGojiOjEx9oTMdX9Q3TnXUSu04VemLVjuOMkzBogWmo1akgympgIVQ+BsabiGBXM1ld7Ps7n9kZzL5JRDSWO2vv/p5mX3Onud7nmfPOc9uhBzHAXEAgmA8w8KJ887/POFahHHaJCAmgZD981GLV38C/NeufzjQ3Z7AXSB8YYT8Rr0n1uoOEtILRv90XwHxsu9F8Ynl1wige1r8Xw/BvZr/7tS2vVf1h4fgr0Qhwfrv9/tJkpRIJAiCJOw7Go7jQBBkGMbr9ZIkiSDImjVrhMJYk/T7/deuXTMajQcOHEhPT79dj7eh3+Px/N8Ss7OzFEUFl9ixY0dNTc3tel0WjuMGBwePHz9+69YtGIalUqlcLlepVNu3b9doNDiOL2tlNBqPHj3qdrtxHK+trb1dp6voZ1mW4ziLxXL9+vWrV68ajcbp6Wmr1bqwsPDnwwNBu3fvLi4uzsrKul3H0VAU1dPT097ezjAMy7J8epNKpdu2bXv++ecrKytlMlm0lcvlCgQCFEX5/f4EnMbS7/P5zGbz77//3tbW1tPTYzabBQIBDMM0TSMIolKp0tPTd+3alZSUlIDjaAiCmJ6epmm6sLCwrKwMgqCJiYnBwcGuri6z2UwQxLPPPisWi6OtIOjPLCYSiRJwuqJ+juOOHTv2ySefgCBIkiTDMAiCPP744+Xl5VqtVqVSzc3N+f3+nJwcqVSagONoSJK02WwAAJSUlNTV1clkMqvV2tvb++WXX964caO5uTk3N3fnzp0RNc/n89E0DYLgSg9IbFbUzzCMWCwOBAIIgqjV6meeeUan0ymVShiG+QFpaWkJ+IsBSZJ2ux0AgMzMzKysrPT0dKVSqVKpkpOT33nnHb1ebzAYtFothmHhVh6PhyAIFEVTU1MTcLpi/YMg6LHHHhOLxSKRaMuWLXV1dQUFBSHxfwd+v5/Xr1AoQpsZw7C9e/euW7cOAACz2cwPCMflchEEkZSUFJEdSJK0WCwEQcSujrH0l5WVKZVKn8/HsiyO43ek34yB1+t1OBwAAGRnZ4c/zDiOkyQJQRDDMAKBIMLKbrfz+lNSUsJvdfHixQ8//NBgMNA0HcNprPwnEom0Wu3MzIzVajWZTMXFxeFXOY4jCIJhGAzD+AwUg4WFhZmZGQzDcnNzBQLBsiXd4XA4nU4AAHJycsIHDAwMjI+PLy4uFhQUrFmzJsLK6XRSFIVhWEj/H3/8cfbs2aampsnJSYqi1Gp1jCblP+YRfRAuKirq6Oiw2+1TU1MR+i0WS2dnZ319/bL35dsym83W09Pz008/TUxM8D9iGPbGG29otdro8XNzcx6PBwCAgoICfp1Jkvzll19Onjxps9kkEklVVVVEkuM4bn5+nqIoiUSSnJwMAIDb7T5x4sTp06cdDsf69eurqqqiQ7aifr79Cu+rN2/eDADA3BJ8aIeGhvr6+r7//vsff/yR31pFRUVdXV1yuTwilCu5vHDhQoRTAAACgcD09DQAACiKvvnmm1lZWcFg0OFw9Pf39/X1SSSSQ4cOFRYWRtzK7XYHAgGRSMQv/vj4+LvvvnvhwgWfz1dSUnL06NHq6uoY4pfZ//xsQhtBq9USBOFyufR6PUEQv/322+jo6NTUlNPpZFl23bp1arV6//790THmOO6LL744cuQICIIVFRUajQbDsNnZ2c7OTovF8tlnn+3fv3/ZSJEkeerUKYVCQdO02+1eXFwUi8UVFRVvvfVW9OxdLlcwGERRFIbhrq6u999/X6/XgyBYXV39yiuv7Nq1K7Z4ILRRVyIYDG7fvp3PyXK5HARBDMPy8vLKy8sbGhrOnj2r1+udTme04djY2BNPPIFhWF1d3dDQEMMw8/Pzb7/9tlwuLygoaG1tjRg/Ojq6Z88eCIJwHJfL5cnJyaEUKJPJjhw5Mj4+TtN0hJXBYCguLkZRNH8JoVAoEokqKir6+/tj6wqxin6r1VpXVxdaKIlEotPpPv3004GBgWAwuJIVwzBtbW1yuXzTpk1dXV0sy1IUde7cOZVKJRKJ9u3b5/V6I+cBAI8++qhMJmtsbBwaGrp8+fKZM2deffXV0tJSiUSComh1dfXg4GCEVXd394YNG/hqxe8jBEH27NljMpnujH6Xy3Xq1CkAAFJTU0+cOMGX01UhCOLcuXMwDGu12kAgsLCwcOzYMQzDpFJpQ0ODzWaLFv/tt9/ynU9TUxP/I03TMzMz7e3tL774olKpRBDk4MGDEbaff/65QqHg98ihQ4cOHz6ckpKSk5PT1NTk9/vjmeoq5x8cxzUaDV+cNBpN7KNoCBRFTSaTSCQqLCz8+eef29vbv/76axRFDxw48NJLL0U3anzefeCBB4LBYKiNEQqFWUuUlpZiGNbc3Dw6OtrX1/fkk0+GDC0WSyAQ2LhxY2NjY01NjdVqtdvtnZ2dHR0dpaWlWq121cK8ymWhUIiiqFqtBgBgbGwsEAjEo58HQRC3293c3Nza2ioQCOrr619//XWNRiMQCBYXF8fGxi5fvsyf8wAA+PjjjymKgmE4vI3h0+H8/DxBEDAMcxwXoWdqaoogiPXr1z/88MM5OTkajeapp57Ky8vT6/UdHR18N7WKwFVH4Di+adOm4eHhX3/9dd++fSuVU5Zlwyf34IMPsizb0tICw3BRUdFrr72m0+lCV71e7+nTp3/44Yfz58+rVCqBQODxeCiKwnE8JSWFIAin02mz2WZnZ81mc3d3d29vL03T5eXl/EqE4M+LaWlpfNREIlFVVdXVq1dbWlouXrz4yCOPVFZWxt6zq+tPTU196KGHWlpaDAaD1+sNr/PBYNBms01OThqNxi1btqhUKhRF+Uvbtm3juy65XN7Y2Lh79+6QFUEQX331FR8au93OR83n81EUNTY29txzz8nlcgzDQBB0Op0mk8nr9a5du7ampubll1/Oz88Pj/j8/DzHcVKpNNQXZWZm6nS6/v7+kZGRS5cuFRcX8wkicf0ymay0tBQAgKGhoZs3byoUCp/P53A4eOUjIyPDw8M3b95cu3btyZMnt27dylvxZ9VLly5lZ2fz64nj+MjIiMFgaGtr6+7uTktL0+l0arWaz9uZmZkgCNI0PTk5aTab+ZskJSVlZ2eXlJRUVlbW1tZGvN6CICglJUUsFufn54f3hWVlZTt37pyYmGhtbW1oaMjIyIjRjK2uH4bhjRs3bt269dq1ax988MHAwADLskajcXh42Gg0hqYSfTqsra11u91Xrlw5fvz4mTNnPB6PVCp1Op2zs7MwDO/du/fgwYMhSS+88ILf7zebzSzLoiiKIIhEIhGLxRkZGTt27MjNzV02k3300UfDw8OVlZXh72AQBDl8+PCNGzfcbnfEYXkZ4ikSDMO89957SqUy+h2LRqOpr68/f/68y+WKsPL5fD09PU8//fSGDRtgGAZBUKFQaLXahoaGK1euMAwT7YgvlrNLeDyeeOa2LCzL9vb2Xr9+fdWR8X75u3Xr1jfffPPdd98NDAzk5eUVLrF58+aMjIzk5GS+RVk2uDRNd3R0eDweCIJomuabory8vDhL6d/NbXz5pCjKZDIplUqO4/iX0xiGxSmDpmmGYZaN0d3lvvvyG8E9/P3njvCv/vubWK8074fUEO//3/5Xud/3/7/672/+PwAA//8UaCnePgyxzQAAAABJRU5ErkJggg=='
    }
  }
}
2023-07-28 14:15:11.131  DEBUG [HTTPApi.login] Captcha verification received 
{
  captchaId: '0118ead5-4569-47e7-ac2e-cebd62f7a098',
  item: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAArCAIAAACGv1O8AAAK1UlEQVR4nOyaa1Ab5ffHdzfZzYbdlBCgIVzCZdpamxigFdKLIkWHUoap2tqpaXWGojiOjEx9oTMdX9Q3TnXUSu04VemLVjuOMkzBogWmo1akgympgIVQ+BsabiGBXM1ld7Ps7n9kZzL5JRDSWO2vv/p5mX3Onud7nmfPOc9uhBzHAXEAgmA8w8KJ887/POFahHHaJCAmgZD981GLV38C/NeufzjQ3Z7AXSB8YYT8Rr0n1uoOEtILRv90XwHxsu9F8Ynl1wige1r8Xw/BvZr/7tS2vVf1h4fgr0Qhwfrv9/tJkpRIJAiCJOw7Go7jQBBkGMbr9ZIkiSDImjVrhMJYk/T7/deuXTMajQcOHEhPT79dj7eh3+Px/N8Ss7OzFEUFl9ixY0dNTc3tel0WjuMGBwePHz9+69YtGIalUqlcLlepVNu3b9doNDiOL2tlNBqPHj3qdrtxHK+trb1dp6voZ1mW4ziLxXL9+vWrV68ajcbp6Wmr1bqwsPDnwwNBu3fvLi4uzsrKul3H0VAU1dPT097ezjAMy7J8epNKpdu2bXv++ecrKytlMlm0lcvlCgQCFEX5/f4EnMbS7/P5zGbz77//3tbW1tPTYzabBQIBDMM0TSMIolKp0tPTd+3alZSUlIDjaAiCmJ6epmm6sLCwrKwMgqCJiYnBwcGuri6z2UwQxLPPPisWi6OtIOjPLCYSiRJwuqJ+juOOHTv2ySefgCBIkiTDMAiCPP744+Xl5VqtVqVSzc3N+f3+nJwcqVSagONoSJK02WwAAJSUlNTV1clkMqvV2tvb++WXX964caO5uTk3N3fnzp0RNc/n89E0DYLgSg9IbFbUzzCMWCwOBAIIgqjV6meeeUan0ymVShiG+QFpaWkJ+IsBSZJ2ux0AgMzMzKysrPT0dKVSqVKpkpOT33nnHb1ebzAYtFothmHhVh6PhyAIFEVTU1MTcLpi/YMg6LHHHhOLxSKRaMuWLXV1dQUFBSHxfwd+v5/Xr1AoQpsZw7C9e/euW7cOAACz2cwPCMflchEEkZSUFJEdSJK0WCwEQcSujrH0l5WVKZVKn8/HsiyO43ek34yB1+t1OBwAAGRnZ4c/zDiOkyQJQRDDMAKBIMLKbrfz+lNSUsJvdfHixQ8//NBgMNA0HcNprPwnEom0Wu3MzIzVajWZTMXFxeFXOY4jCIJhGAzD+AwUg4WFhZmZGQzDcnNzBQLBsiXd4XA4nU4AAHJycsIHDAwMjI+PLy4uFhQUrFmzJsLK6XRSFIVhWEj/H3/8cfbs2aampsnJSYqi1Gp1jCblP+YRfRAuKirq6Oiw2+1TU1MR+i0WS2dnZ319/bL35dsym83W09Pz008/TUxM8D9iGPbGG29otdro8XNzcx6PBwCAgoICfp1Jkvzll19Onjxps9kkEklVVVVEkuM4bn5+nqIoiUSSnJwMAIDb7T5x4sTp06cdDsf69eurqqqiQ7aifr79Cu+rN2/eDADA3BJ8aIeGhvr6+r7//vsff/yR31pFRUVdXV1yuTwilCu5vHDhQoRTAAACgcD09DQAACiKvvnmm1lZWcFg0OFw9Pf39/X1SSSSQ4cOFRYWRtzK7XYHAgGRSMQv/vj4+LvvvnvhwgWfz1dSUnL06NHq6uoY4pfZ//xsQhtBq9USBOFyufR6PUEQv/322+jo6NTUlNPpZFl23bp1arV6//790THmOO6LL744cuQICIIVFRUajQbDsNnZ2c7OTovF8tlnn+3fv3/ZSJEkeerUKYVCQdO02+1eXFwUi8UVFRVvvfVW9OxdLlcwGERRFIbhrq6u999/X6/XgyBYXV39yiuv7Nq1K7Z4ILRRVyIYDG7fvp3PyXK5HARBDMPy8vLKy8sbGhrOnj2r1+udTme04djY2BNPPIFhWF1d3dDQEMMw8/Pzb7/9tlwuLygoaG1tjRg/Ojq6Z88eCIJwHJfL5cnJyaEUKJPJjhw5Mj4+TtN0hJXBYCguLkZRNH8JoVAoEokqKir6+/tj6wqxin6r1VpXVxdaKIlEotPpPv3004GBgWAwuJIVwzBtbW1yuXzTpk1dXV0sy1IUde7cOZVKJRKJ9u3b5/V6I+cBAI8++qhMJmtsbBwaGrp8+fKZM2deffXV0tJSiUSComh1dfXg4GCEVXd394YNG/hqxe8jBEH27NljMpnujH6Xy3Xq1CkAAFJTU0+cOMGX01UhCOLcuXMwDGu12kAgsLCwcOzYMQzDpFJpQ0ODzWaLFv/tt9/ynU9TUxP/I03TMzMz7e3tL774olKpRBDk4MGDEbaff/65QqHg98ihQ4cOHz6ckpKSk5PT1NTk9/vjmeoq5x8cxzUaDV+cNBpN7KNoCBRFTSaTSCQqLCz8+eef29vbv/76axRFDxw48NJLL0U3anzefeCBB4LBYKiNEQqFWUuUlpZiGNbc3Dw6OtrX1/fkk0+GDC0WSyAQ2LhxY2NjY01NjdVqtdvtnZ2dHR0dpaWlWq121cK8ymWhUIiiqFqtBgBgbGwsEAjEo58HQRC3293c3Nza2ioQCOrr619//XWNRiMQCBYXF8fGxi5fvsyf8wAA+PjjjymKgmE4vI3h0+H8/DxBEDAMcxwXoWdqaoogiPXr1z/88MM5OTkajeapp57Ky8vT6/UdHR18N7WKwFVH4Di+adOm4eHhX3/9dd++fSuVU5Zlwyf34IMPsizb0tICw3BRUdFrr72m0+lCV71e7+nTp3/44Yfz58+rVCqBQODxeCiKwnE8JSWFIAin02mz2WZnZ81mc3d3d29vL03T5eXl/EqE4M+LaWlpfNREIlFVVdXVq1dbWlouXrz4yCOPVFZWxt6zq+tPTU196KGHWlpaDAaD1+sNr/PBYNBms01OThqNxi1btqhUKhRF+Uvbtm3juy65XN7Y2Lh79+6QFUEQX331FR8au93OR83n81EUNTY29txzz8nlcgzDQBB0Op0mk8nr9a5du7ampubll1/Oz88Pj/j8/DzHcVKpNNQXZWZm6nS6/v7+kZGRS5cuFRcX8wkicf0ymay0tBQAgKGhoZs3byoUCp/P53A4eOUjIyPDw8M3b95cu3btyZMnt27dylvxZ9VLly5lZ2fz64nj+MjIiMFgaGtr6+7uTktL0+l0arWaz9uZmZkgCNI0PTk5aTab+ZskJSVlZ2eXlJRUVlbW1tZGvN6CICglJUUsFufn54f3hWVlZTt37pyYmGhtbW1oaMjIyIjRjK2uH4bhjRs3bt269dq1ax988MHAwADLskajcXh42Gg0hqYSfTqsra11u91Xrlw5fvz4mTNnPB6PVCp1Op2zs7MwDO/du/fgwYMhSS+88ILf7zebzSzLoiiKIIhEIhGLxRkZGTt27MjNzV02k3300UfDw8OVlZXh72AQBDl8+PCNGzfcbnfEYXkZ4ikSDMO89957SqUy+h2LRqOpr68/f/68y+WKsPL5fD09PU8//fSGDRtgGAZBUKFQaLXahoaGK1euMAwT7YgvlrNLeDyeeOa2LCzL9vb2Xr9+fdWR8X75u3Xr1jfffPPdd98NDAzk5eUVLrF58+aMjIzk5GS+RVk2uDRNd3R0eDweCIJomuabory8vDhL6d/NbXz5pCjKZDIplUqO4/iX0xiGxSmDpmmGYZaN0d3lvvvyG8E9/P3njvCv/vubWK8074fUEO//3/5Xud/3/7/672/+PwAA//8UaCnePgyxzQAAAABJRU5ErkJggg=='
}
2023-07-28 14:15:25.596  DEBUG [ClientsController.addSocket] New client with ip: 127.0.0.1 port: 44742 
2023-07-28 14:15:25.618  INFO  [WebSocket.<anonymous>] Client disconnected with ip: 127.0.0.1 port: 44742 code: 1000 reason: Normal Closure 
2023-07-28 14:15:25.625  DEBUG [ClientsController.addSocket] New client with ip: 127.0.0.1 port: 44754

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/795
