### ISSUE TITLE
Simple rtsp server addon does not use non default port

### ISSUE THREAD

**Issue by relighted** [fuatakgun/eufy_security#859]
Ive set the port of simple rtsp server add on to 8556 due to errors reported the default was taken/occupied. 
The service however keeps starting on 8554, seemingly ignoring the port setting in the UI config. 
(Editing in yaml does not show options to set the port btw.)

**To reproduce**

1. Go to addons, simple rtsp server 
2. Click on 'network port.'
3. Set to 8556
4. Restart. And check log

2023/07/29 05:16:03 I [0/0] rtsp-simple-server v0.17.6
2023/07/29 05:16:04 I [0/0] [RTSP] TCP listener opened on :8554
2023/07/29 05:16:04 I [0/0] [RTMP] listener opened on :1935
2023/07/29 05:16:04 I [0/0] [HLS] listener opened on :8888

**Expected behavior**
I'd expect the addon to start on the indicated port

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): os
- Home Assistant Core Version: 2023.07.3
- Eufy Security Add-on Version: 1.5.2.1
- Eufy Security Integration Version: latest alpha
- simple rtsp add. On version: v0.17.6
- 
Hardware Information;
- Camera Model:
Eufy 2c pro

- Live Streaming Protocol (RTSP/P2P): 
Rtsp

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- 

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (yes): 

**Additional context**

Add any other context about the problem goes here.

**Comment by fuatakgun** [comment]
Logs mention the internal port inside the container, not the external one.

**Comment by relighted** [comment]
Thanks.
Could not find that as hint in the documents.

**Comment by fuatakgun** [comment]
If you think this would be useful, go ahead and raise a PR, it would be appreciated.

On the other hand, this is how containers work all around, nothing specific to this integration. They do not know what is external port.
