### ISSUE TITLE
2 Factor Authentication

### ISSUE THREAD

**Issue by jonahgcarpenter** [fuatakgun/eufy_security#86]
When you install this integration and link it to a Eufy account with 2 factor authentication enabled it will not work and will spam email you codes. It is not a huge deal breaker as disabling 2 factor fixed this, but I would like to see the implementation of 2 factor as a safety feature.

**Comment by skank01** [comment]
2nd that.
Would love to see 2FA but there are some major issues first with P2P and stability

**Comment by jameshhood** [comment]
I feel like this needs to be added to the setup documentation in the meantime. I've been troubleshooting reasons why I can't log in and totally forgot that I had set this up

**Comment by dMopp** [comment]
Had the same issue, now iam blocked by eufy temporary due to login spam  :(

**Comment by fuatakgun** [comment]
resolving this, if someone can spare time on this, happy to assist
