### ISSUE TITLE
Eufy Security - Error in Notifications

### ISSUE THREAD

**Issue by Prash1407** [fuatakgun/eufy_security#863]
I have a notification since the latest update to 6.3.2, however it seems like everything is working alright, apart from the [streaming issue](https://github.com/fuatakgun/eufy_security/issues/841) I have been experiencing:

### Eufy Security - Error
Error: <Task finished name='Task-4127' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Hassio
Operating System 10.4
Supervisor 2023.07.2
Frontend 20230725.0 - latest

- Home Assistant Core Version: Home Assistant 2023.8.0b1
- Eufy Security Add-on Version:  1.5.2-1
- Eufy Security Integration Version: 6.3.2

Hardware Information;
- Camera Model: T8210 2K Doorbell + T8020 Chime
- Live Streaming Protocol (RTSP/P2P): P2P
- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624): n/a
- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output): n/a
- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Comment by RienduPre** [comment]
Same error here, since I upgraded to 6.3.2 (from 6.3.1)

**Comment by alexeiw123** [comment]
I get the same thing.

/config/custom_components/eufy_security/eufy_security_api/web_socket_client.py from line 62 is:

```
    async def _process_messages(self):
        async for msg in self.socket:
            await self._on_message(msg)
```

That's about where my contribution ends, back to previous version for me :)

**Comment by Prash1407** [comment]
Still existing:

Eufy Security - Error
Error: <Task finished name='Task-4282' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

@fuatakgun

**Comment by fuatakgun** [comment]
Follow the bug template and share the logs as requested

**Comment by alexeiw123** [comment]
> Follow the bug template and share the logs as requested

I've done this here:
https://github.com/fuatakgun/eufy_security/issues/866

**Comment by johnjoemorgan** [comment]
s reported in  #866 
I had a similar error after upgrade:

Error: <Task finished name='Task-4465' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

This cleared after a second reboot.
