### ISSUE TITLE
I see my cam T8122 in the list of devices, but I can not change any settings.

### ISSUE THREAD

**Issue by danymexi** [fuatakgun/eufy_security#867]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

I can see my cam T8122 in the list of device, but I can not change any settings.
When I change some parameter such as the guard mode, nothing happened.
If I check the status current mode I have Unknown.

All the other cameras work perfectly.

**To reproduce**

1. Go to eufy security
2. Click on 'T8122.'
3. Scroll down to 'guard mode.'
4. See error after clicking it

**Expected behavior**

I can not change any parameter.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230705.1 - latest
- Eufy Security Add-on Version:  1.6.0
- Eufy Security Integration Version: 6.3.3

Hardware Information;
- Camera Model: T8122

- Live Streaming Protocol (RTSP/P2P): p2p

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/eufy_security/eufy_security_api/api_client.py:320
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:24:31 (2 occurrences)
Last logged: 12:24:49

[140399228054544] {'type': 'result', 'success': False, 'messageId': 'device.stop_livestream.7b58d85f4fb144a99cf0ae12e45f47ae', 'errorCode': 'device_livestream_not_running'}
[140399228054544] {'type': 'result', 'success': False, 'messageId': 'device.stop_livestream.06a8c115451b4054a983850d4cc5e360', 'errorCode': 'device_livestream_not_running'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 124, in _async_press_action
    await self.async_press()
  File "/config/custom_components/eufy_security/button.py", line 51, in async_press
    await handler_func()
  File "/config/custom_components/eufy_security/eufy_security_api/camera.py", line 155, in stop_livestream
    await self.api.stop_livestream(self.product_type, self.serial_no)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 218, in stop_livestream
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.stop_livestream, serial_no=serial_no))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 320, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'device.stop_livestream.7b58d85f4fb144a99cf0ae12e45f47ae', 'errorCode': 'device_livestream_not_running'}

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No):

Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by fuatakgun** [comment]
Are you going to share debug logs?
```
Without this, I will automatically resolve this issue
```

**Comment by danymexi** [comment]
I activated the debug from config, where can I find the log?

Let me know and of course, I will share it.

Thanks and sorry for the inconvenience.

**Comment by fuatakgun** [comment]
there is link, next to log question, please follow it

**Comment by danymexi** [comment]
Let me know if you can see it! 

[home-assistant.log](https://github.com/fuatakgun/eufy_security/files/12251633/home-assistant.log)

**Comment by fuatakgun** [comment]
I do not see any issue on these logs, you mentioned about changing the guard mode, please get latest version (newer than 7.0.0), start logging, do some actions which are not working, share the logs.

**Comment by danymexi** [comment]
I can share with you also a video of what happens when I use that device: https://share.icloud.com/photos/0abUKy-STykXUaklfnWs3ebng

And attached a log after doing the same thing shared in the video.
[home-assistant (2).log](https://github.com/fuatakgun/eufy_security/files/12259255/home-assistant.2.log)

**Comment by fuatakgun** [comment]
@danymexi , get latest version 7.0.3 and let me know the results

**Comment by danymexi** [comment]
Still the same. No changes.

**Comment by fuatakgun** [comment]
share the logs

**Comment by fuatakgun** [comment]
I am really tired of trying to extract information from you, is it really so hard to mention what you have tried and what went wrong. You are sending me all the logs with zero information. Feel free to ask help over discussions and home assistant forums.

There is nothing wrong on the logs and I am done with trying to solve the puzzle.

**Comment by danymexi** [comment]
@fuatakgun have you watched the video I shared?!? There it is quite clear what is the problem! 

I’m not a developer and I’m trying to give you the info you need to find a way to solve the issue… 

if I was able to solve the issue I would not ask for your help ;)

Your way of supporting is controversial 😊 but hey… you have the power here… so I will survive without fixing the problem! 

Anyway thanks for trying to understand what is the issue! 

Buonanotte 😊

**Comment by fuatakgun** [comment]
https://community.home-assistant.io/t/how-to-help-us-help-you-or-how-to-ask-a-good-question/114371

**Comment by danymexi** [comment]
Thanks a lot for sharing, @fuatakgun !

One question: Have you watched the video I shared with you here: https://share.icloud.com/photos/0abUKy-STykXUaklfnWs3ebng ?

Because You reply saying You don't understand what is the problem... and I didn't explain to you what's the problem but to me is quite easy to understand watching the video. And the problem is still there as I shared after uploading to 7.0.3 as requested.

You said you need a log, and I shared the log as requested... but it seems this is not what you need.

I understand you are helping for free, and I appreciate a lot your support! But this doesn't allow you to be "aggressive/rude".
I have no clue of what you need and I have no clue of what I should share on the log... if the entire file or just something specific... again I'm not a dev. 

Again, thanks for your support. I will survive with one camera not properly working in home assistant, it is not the end of the world. I was just trying to support you with info and file needed to solve the issue :)

Have a good day :)
