### ISSUE TITLE
Used to work now says 'Failed to set up'

### ISSUE THREAD

**Issue by VAFS001** [fuatakgun/eufy_security#869]
I had this system working perfectly a few months back and when I checked it this weekend it stopped working or initializing.

I have not changed anything with the system except for updated.

I tried to reinstall everything and I still receive this message: Failed to set up

Here is the log entry:

Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/eufy_security/eufy_security_api/api_client.py:320
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 7:09:58 PM (3 occurrences)
Last logged: 7:24:07 PM

Error setting up entry 127.0.0.1 for eufy_security
Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 37, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 71, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 147, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 320, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.9b9383988a8f45808734f84527175050', 'errorCode': 'schema_incompatible'}

**Comment by fuatakgun** [comment]
What is the point of creating a bug without following the bug template?

**Comment by VAFS001** [comment]
Your right, I was very tired and was working on this for at least 12 hours trying everything to get it to work and was about as frustrated as you were most likely when you saw the report without following the template. I will repost and follow the template.
