### ISSUE TITLE
Error fetching eufy_security data: Error communicating with Add-on: Connection to add-on was broken. please reload the integration!

### ISSUE THREAD

**Issue by codyc1515** [fuatakgun/eufy_security#872]
**Describe the bug**

Sometimes the integration will load before the add-on or the add-on will be restarted, e.g. when the add-on is updated. The integration does not gracefully restart.

**To reproduce**

1. Restart the integration
2. Check HA logs

Notice integration is disconnected.

**Expected behavior**

Integation should resume connectivity gracefully.

**Additional information**

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
```
This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: helpers/update_coordinator.py:262
Integration: Eufy Security (documentation, issues)
First occurred: 10:58:37 (1 occurrences)
Last logged: 10:58:37

Error fetching eufy_security data: Error communicating with Add-on: Connection to add-on was broken. please reload the integration!
```

**Comment by kvanbiesen** [comment]
Tru updating the bropat WS addon, he just uploaded a new version.

**Comment by guitarwiz09** [comment]
i am now expeiencing this same issue as well.

**Comment by leonardpitzu** [comment]
I have had the same issue intermittently for quite some time. I have solved it with an automation - once the alarm_panel entity goes unavailable I just restart the integration. Yes, this is a bug and should not happen but I solved the issue. Have not reported it yet as the integration has gone through major changes and I am waiting for it to stabilise a bit...

**Comment by kvanbiesen** [comment]
What versions are you running of the bropat en fuatakgun addons?
Do you have an alarm panel.

Cause here i m running latest versions of everything and no issues at all regarding this

**Comment by leonardpitzu** [comment]
Latest version of the integration + bropat container. Yes, I have an alarm panel.

**Comment by fuatakgun** [comment]
the connection between integration and add-on might be broken for any reason and I am working on recovery strategies, until then, please reload your integration based on any entities state as Unavailable

**Comment by codyc1515** [comment]
Should be fixed by https://github.com/fuatakgun/eufy_security/commit/3bca9d36fe9ff0871ae9dfb23b8935bde6c49201

**Comment by fuatakgun** [comment]
Thanks 🙏
