### ISSUE TITLE
Recover connection to add-on

### ISSUE THREAD

**Issue by fuatakgun** [fuatakgun/eufy_security#877]
https://github.com/fuatakgun/eufy_security/issues/866

When the connection is broken between integration and add-on, the connection should be recovered gracefully

**Comment by JustDFB** [comment]
Hi there,
I have the same locks and same issue in 1.6.3.
Many thanks,
Dane

**Comment by fuatakgun** [comment]
broken connection between add-on and integration should be recovered automatically with 7.5.0 version.
