### ISSUE TITLE
All address lookup tentatives failed. 

### ISSUE THREAD

**Issue by akeslo** [fuatakgun/eufy_security#88]
I'm getting the following error when attempting to use camera.turn_on / camera.turn_off.

Thanks!

```
INFO Connected to station T84XXXXX on host 192.168.4.64 and port 29801 
2021-10-18 22:05:08.626  ERROR P2PClientProtocol.lookup(): station: T84XXXXX - All address lookup tentatives failed. 
2021-10-18 22:05:08.628  INFO Timeout connecting to station T84XXXXX 
2021-10-18 22:05:18.219  ERROR Message error 
 NotConnectedError  No p2p connection to station T84XXXXX
details:
{
  name: 'NotConnectedError'
}
```

**Comment by fuatakgun** [comment]
your WS add-on is not able to connect to your base station at `192.168.4.64`
do you have any restrictions or VLAN setup?

**Comment by fuatakgun** [comment]
can you share your cameras following README file. I have setup local version for new add on version, let's see if we can resolve this with new version.

**Comment by fuatakgun** [comment]
can you update this thread? did you share your cameras?

**Comment by fuatakgun** [comment]
resolving due to inactivity
