### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by Sarnog** [fuatakgun/eufy_security#882]
I use the latest integration and also the latest add-on. Now my picture enity doesn't update and i get this error message:
```
Error: <Task finished name='Task-1290397' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>
```

**Comment by kvanbiesen** [comment]
Nothing to do with the picture entity. Happens to most of us, this error is harmless...Only when starting the integration

**Comment by Sarnog** [comment]
I know that the error has nothing to do with the picture entity, was just commiting 2 error's maybe i should do it seperately...

**Comment by multinet33** [comment]
Same error here. On my side if I switch the status security on the eufy app, I get updated on home assistant BUT if i switch it on home assistant nothing happen on eufy the security status is not changed

**Comment by VenimK** [comment]
Same here

Error: <Task finished name='Task-5678' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

**Comment by relighted** [comment]
Same here. All. Updated.
At integration reload directly the error notify, the eufy doorbell. Cam. Image refreshes once, then not any more.

```python
Error: <Task finished name='Task-37321' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>
```

**Comment by fuatakgun** [comment]
Resolving. Follow bug template
