### ISSUE TITLE
Can't control homebase anymore

### ISSUE THREAD

**Issue by HP-Basarab** [fuatakgun/eufy_security#893]
Hello!

Yesterday the plugin was still working perfectly, but since this morning, I can no longer control my Homebase 2 and my two eufycam 2Cs. For example, I can click on the button to change the Guard mode, but nothing really happens.
However, I have another Eufy wifi camera which does not use the Homebase and it is perfectly controllable.
I didn't touch anything at all so I don't really understand what could have happened.
I tried to restart Home Assistant, my homebase, I uninstalled and reinstalled hassio-eufy-security-ws as well as the HACS client but nothing works. I'm out of ideas, can you help me please?

Hardware Information;
- Camera Model:

Homebase 2 with 2 eufycam 2c

- Debug Logs from Home Assistant:

CF the log file
[home-assistant.log](https://github.com/fuatakgun/eufy_security/files/12365650/home-assistant.log)

Sometimes I get this message appearing in my notifications:
`Error: <Task finished name='Task-3355' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>`

Thanks in advance

**Comment by EnterTheMaelstrom** [comment]
Yep same for me, same error. Also using Homebase 2 with 2 eufycam 2C

Also restarted everything multiple times and checked if everything is updated...

**Comment by kvanbiesen** [comment]
Just tested it, can still change guard modes on the base....T8010 version.

How did you try chaning it, true automation or nodered or with the device in HA?

**Comment by HP-Basarab** [comment]
Through automation, device page and dashboard

**Comment by kauthmbt** [comment]
This sounds very similar: [https://github.com/bropat/eufy-security-ws/issues/250](url)
If it is related, it is due to a firmware update on HomeBase 2..

**Comment by EnterTheMaelstrom** [comment]
Yep can confirm a recent update of my HomeBase 2 to 3.3.0.1h
Nice try from eufy to push me towards HomeBase 3...

**Comment by kvanbiesen** [comment]
aaah that could be why its still working for me, my homebase is still
running at  Firmware: 3.2.9.5h

**Comment by mrlerif** [comment]
I'm also having problem with my Eufy security add-on. Last night around 3am local time both of my door sensors changed state from Closed to Open and has been in that state ever since. No matter what I do they won't change state in Home Assistant. However i can see in the Eufy app that they are in Closed state whenever doors are closed. This causes the issue that i can't activate the alarm on my Homebase through Home Assistant.
I didn't change anything on my Home Assistant yesterday and the frimware on Homebase 2 is 3.2.9.5h

**Comment by clanic70** [comment]
Hi, I've encountered the sane issue reported. 
The error displayed trying to switch home-base from HA is: 

"Eufy Security - Error"

Error: <Task finished name='Task-6166' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

Do you think any fix will be released soon? 

Cheers

**Comment by kusmierz** [comment]
not sure if the same issue, but it looks I have exception info

```
Error: <Task finished name='Task-7336' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> exception=TypeError("'async for' requires an object with aiter method, got NoneType")>
```

**Comment by kvanbiesen** [comment]
I have this error also but just when starting the plugin, click it away, everything is still working fine here.

EU REgion account, even my homebase doesnt say there isnt an update

**Comment by Jazza159** [comment]
My Homebase V2 also looks to have updated on the 17th of August at 3 am to 3.3.0.1h.
Since then I have had the same issue as others here. It is almost like the home base is 'read only' as changes made on the Eufy app reflect in HA but nothing changed in HA makes it to Eufy,

There is nothing unusual in the add on logs.

As others have, I sometimes receive this notification.

Error: <Task finished name='Task-16262' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

Cheers.

**Comment by kauthmbt** [comment]
See [here](https://github.com/bropat/eufy-security-ws/issues/250#issuecomment-1685023339) for an explanation why commands from HA are ignored.
Issue will be fixed in the next **addon** release.

**Comment by clanic70** [comment]
Yes, update released right now and Eufy control is fully back to HA. Well done! 👍💪👏👏👏

**Comment by Jazza159** [comment]
The update has fixed it, thanks for your hard work! 💪💪🙏🙏

**Comment by HP-Basarab** [comment]
Sadly after 3.3.0.4h homebase update, the problem has returned 😔

**Comment by clanic70** [comment]
Exactly the same....back in trouble again! No way to get a robust fix for every homebase update?

**Comment by fuatakgun** [comment]
@clanic70 , you cannot be serious right? You are buying products from a brand with a full closed eco system and some people out there are reverse engineering and implementing this unsupported layer and you are asking us to have a proper fix???

**Comment by clanic70** [comment]
All devices connected in HA are coming from a specific brand and I've never encountered so many boring issues as for Eufy cams....I guess also other brands are doing periodic update, isn't it?

**Comment by HP-Basarab** [comment]
It is an unofficial plugin, sadly there is a risk that a definitive fix will never exist... Thank you for your work and take your time.

**Comment by kvanbiesen** [comment]
Closed eco system vs open API. I switched the doorbell to a reolink and
couldn't be more happy. Etsy stream for continuous recording.

The closed ecosystem makes it cheaper I guess. Cause you stuck with them.

Ps here everything works fine, days no updates for my home base 2 and gonna
keep it that way lol

**Comment by clanic70** [comment]
Yes, make sense, thanks for your kind explanation. Hopefully in the next, no more frequently updates from Eufy Homebase....even because, I don't see any evident improvement 😁

**Comment by MaxCere** [comment]
Issue is still present also for me even if I have upgraded to 1.6.3

Any news on the issue or fix?

**Comment by mennovanhout** [comment]
still having this issue with a homebase 3
