### ISSUE TITLE
Entry of information

### ISSUE THREAD

**Issue by ahamster13** [fuatakgun/eufy_security#9]
Being a beginner, i wanted to ask a simple question.

With these steps, git clone and the docker run it commands, where do i enter these?

I have just been going into Terminal (Supervisor SSH & Web Terminal)

At the moment i ran the docker run and it is now just staying open. 

Am I doing it correct?

**Comment by fuatakgun** [comment]
yes, if docker is up and running and not generating any error, you are on correct path, now you can start setting up the integration on home assistant. When integration asks you to put host and port, please put ip address of your docker instance (probably same ip address with host machine) and port of WS (probabaly 3000 if you didn't change it).
This integration will try to communicate with your software running on docker.

**Comment by ahamster13** [comment]
Thanks. But i'm still a little lost. If i run this instance in a terminal prompt, the session stays active and i cannot use terminal again.

**Comment by dpomnean** [comment]
if you add the '-d' flag to your docker command it will run in detached mode and you can continue to use your terminal
