### ISSUE TITLE
Password leaked into logs

### ISSUE THREAD

**Issue by eikowagenknecht** [fuatakgun/eufy_security#900]
**Describe the bug**

Since I quite often check my logs and sometimes make them public (i.e. GitHub Issues), I noticed that this integration leaks passwords when they are contained in the URL of a stream, e.g.

```
2023-08-23 08:11:03.342 INFO (MainThread) [aiortsp.rtsp.reader] try loading stream rtspt://user12345:password12345@192.168.40.85/live4
```

Since they *need* to be included there for some cameras to work, I see no obvious workaround.

**Expected behavior**

I think it would be prudent to redact the password part of the url to avoid unknowingly leaking them to the internet.

**Comment by fuatakgun** [comment]
would you be interested on raising a PR to fix this?

**Comment by eikowagenknecht** [comment]
I'll have a look at it.

**Comment by eikowagenknecht** [comment]
Actually it looks like the source is the aiortsp library:

https://github.com/marss/aiortsp/blob/c15c23119e5516e06eae08bfb1f51a72a1c06268/aiortsp/rtsp/reader.py#L87C17-L87C17

So it seems like this would have to be fixed upstream.

Workaround is to set the logging level for that library to something higher that INFO.

**Comment by eikowagenknecht** [comment]
The upstream library has been fixed. So switching to version 1.3.7 should close this issue.
