### ISSUE TITLE
Save Images/Camera Entity Update/Person Name

### ISSUE THREAD

**Issue by Xllr8ing** [fuatakgun/eufy_security#903]
Hello, I've been trying unsuccessfully to save the image event entity as a png or jpeg file with no success as camera snapshots dont seem to support non canera entities. Been trying to convert the entity to a camera device with no success as well. Is the image cached somewhere that I can get to it? If you have suggestions to save the image eufy event image please send any suggestions. The person name is hit or miss, it shows on the eufy device but most times home assistant doesn't update it, working on HAS announcing who is at the door or if it's an unknown face. Any suggestions to get Home Assistant to catch up please share. 
Thanks in advance!

**Comment by fuatakgun** [comment]
There is an entity picture attribute of the image entity and you can use this to link it to anywhere for a short period of time. (https://mydomain.duckdns.org/api/image_proxy/image.entrance_event_image?token=example_token_goes_here)

If you must save the image locally to the disk, then you can use the downloader integration. (https://www.home-assistant.io/integrations/downloader/)
