### ISSUE TITLE
"Please wait, starting configuration wizard for eufy_security" spin forever

### ISSUE THREAD

**Issue by sulliwane** [fuatakgun/eufy_security#905]
**Describe the bug**
After upgrading HA to 2023.8.4 and eufy camera integration to latest version, I had an error with the integration. So I deleted the hub, clicked + button in integration, selected "Eufy Security" and no way to get to the configuration wizard:

"Please wait, starting configuration wizard for eufy_security" spin forever (until show an error after 10 to 20 minutes):

![Screenshot from 2023-08-25 23-46-57](https://github.com/fuatakgun/eufy_security/assets/1733686/fa99357a-d4c3-4ac3-a652-0eb0761e05f4)
Config flow could not be loaded: Unknown error
![Screenshot from 2023-08-26 00-06-59](https://github.com/fuatakgun/eufy_security/assets/1733686/e5aa866c-c3d9-40f2-b03f-53f6196d56b4)

Thanks for your help!

**Additional information**

Version | core-2023.8.4
Installation Type | Home Assistant Supervised
- Eufy Security Add-on Version:  1.6.3
- Eufy Security Integration Version: latest (7.0.4?)

Hardware Information;
- Camera Model:
![Screenshot_2023-08-25-23-50-19-50_ff785028b59b747d09873fc0674450df](https://github.com/fuatakgun/eufy_security/assets/1733686/cc8b082f-98a9-41e9-a4a9-6d614da2b2f6)
  

- Logs from Eufy Security Add-on :
![image](https://github.com/fuatakgun/eufy_security/assets/1733686/5e292d64-ec59-4b7e-8388-3db871069a16)

EDIT
Tried to restore to 1.6.0 (using HA backup), but still same loading indefinitely when adding the integration

**Comment by fuatakgun** [comment]
share the logs

**Comment by michaelmior** [comment]
I'm seeing this too and I don't see anything related to eufy_security in the logs.

**Comment by michaelmior** [comment]
I uninstalled and reinstalled via HACS and now everything seems to be working fine :)

**Comment by waterdrop01** [comment]
Same issue here: 
![Screenshot from 2023-09-15 09-56-57](https://github.com/fuatakgun/eufy_security/assets/47316824/7c31f9f0-c945-4f4d-8fcb-0c9168e47f5f)
no specific error about Eufy in the logs. Uninstalled reinstalled addon, then tried adding the integration...still same loading popup :( also tried to restart HA.

It seems to correlate with HA OS updates, but not really sure.

**Comment by waterdrop01** [comment]
Finally after doing not a "restart" but a "reboot" (equal to hardware reboot), then the add-on logs showed a successfull connection to the camera, and then the integration successfully connected to the add-on...

**Comment by codyc1515** [comment]
Also facing this issue after newly installing the integration.
