### ISSUE TITLE
Slider motion / person detector to set the seconds of the event

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#91]
Hi @fuatakgun ,
would it be possible to implement a slider, as you did for the synchronization with the eufy servers, to vary the duration of the fake motion / person detector which is now set to 10 seconds?

<img width="313" alt="Schermata 2021-10-21 alle 01 07 08" src="https://user-images.githubusercontent.com/63554131/138185107-bc54cf4e-11e0-4698-bfeb-a951e5be23ce.png">

Thanks

**Comment by fuatakgun** [comment]
i will work on this

**Comment by SmartM-ui** [comment]
> i will work on this

Thanks!
Let me know if you need to run some tests :-)

**Comment by fuatakgun** [comment]
done with latest version of add-on.

![image](https://user-images.githubusercontent.com/11085566/147977483-4077a17d-a3eb-4aa7-a870-53d270cb2355.png)
