### ISSUE TITLE
People are not recognized with Base 3 in combination with this integration.

### ISSUE THREAD

**Issue by trinksrichard** [fuatakgun/eufy_security#913]
People are not recognized with Base 3 in combination with this integration.

I always used the Base 2 with doorbell dual. Doorbell Dual has its own facial recognition. When recognizing a person, it checked that that person is also at home in Home Assistant and controls the door lock to open the door.
That works perfectly. But now I have replaced the Base 2 and now use a Base 3. Because Base 3 has its own person recognition, it is switched off from the doorbell and you only see 'unknown' with this integration.

That's because Base 3 has its own facial recognition and we can't indulge that with this integration.
How can we get that option available again?

**Comment by fuatakgun** [comment]
you can check the logs if add-on is sending the `person name` information to integration. If not, you need to work with bropat to help him to implement this.

**Comment by fuatakgun** [comment]
please share your debug logs following readme over here, I will take a look at details
