### ISSUE TITLE
Step 5 dont work - Home Base 2

### ISSUE THREAD

**Issue by DavidFFerreira** [fuatakgun/eufy_security#914]
5- Put Eufy Security Add-on IP Address (127.0.0.1 for Supervised installation) and configured port (default 3000) and click Submit.

It dont recognizes the IP 127.0.0.1 or 0.0.0.0
My Home Assistant is a supervisor in a docker

![image](https://github.com/fuatakgun/eufy_security/assets/32928749/78a41b61-6ec6-42b3-a337-9295e9b65c52)

**Comment by flybevo** [comment]
I've had the same issue - also have a Home Base 2

<img width="447" alt="Screenshot 2023-09-02 at 1 59 07 pm" src="https://github.com/fuatakgun/eufy_security/assets/143308691/74320e2b-d008-45c6-bb65-aa266732492d">

**Comment by DavidFFerreira** [comment]
Restart eufy Add-On? Buts its an Hacs addon, how to restart????

> Eufy Security Add-On

**Comment by DavidFFerreira** [comment]
ok Solved with flybevo explanation

but, now i want to get into step 7
dont know exactly what integration need to have that IP and what IP
![image](https://github.com/fuatakgun/eufy_security/assets/32928749/3211ce12-70a7-45ef-bfb5-8abec014ad27)

**Comment by flybevo** [comment]
Happy to have helped!

Did you have any issues with the reconfigure / captcha stage? I've been getting an 'unknown error' code, which is followed by a 'Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble' note if I try to reconfigure again. I can reload the integration to get another Captcha - but keeps cycling the same error code. 

<img width="391" alt="Screenshot 2023-09-03 at 11 36 52 pm" src="https://github.com/fuatakgun/eufy_security/assets/143308691/eb873522-e293-4a9f-8335-364edea7f932">

**Comment by flybevo** [comment]
With step 5? Did you go back to the Add-On and log into your account in the configure tab?

**Comment by benjani85** [comment]
Not with step 5, in the guide it would be step 6. I'm setting this up from scratch so set my additional account in the configure tab of the add-on, setup the integration then get stuck at the reconfigure step like in your screenshot.

**Comment by flybevo** [comment]
Ah gotcha - yep, I'm still stuck there as well. Haven't had any luck bypassing it yet. 

Might need to raise as a separate issue? I've seen it come up a couple times on the home assistant community group, but doesn't look like there's a specific solve for it - https://community.home-assistant.io/t/eufy-security-integration/318353/335

**Comment by fuatakgun** [comment]
Solutions to all problems :-)
- generate proper logs
- create an issue and share the logs
- you can optionally share your device with me
You can achieve this following readme

**Comment by Milchbeck** [comment]
Today in the morning works perfectly but now not.. working I don't understand why I'm restart nothing

**Comment by Milchbeck** [comment]
Error: <Task finished name='Task-36710' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

**Comment by theseriouscyclist** [comment]
> not an issue with app, already solve all problemes. its a issue with step by step tutorial missing some steps and explanations =)

and what is the solution? What steps were taken in the instructions ?
