### ISSUE TITLE
Integration won't work after Update.

### ISSUE THREAD

**Issue by tmbs1988** [fuatakgun/eufy_security#917]
**Suddenly lost connection to all devices, worked for a very long time before. Updated addon, and HA and now it don't want to connect anymore **

Restarting the Add-On and then going back to the integration to put in the configure just to move back to the Add-On and seeing this error in the log file 

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-09-06 20:41:03.442  INFO  Eufy Security server listening on host 0.0.0.0, port 3002 
2023-09-06 20:41:05.313  INFO  Connected to station T8410P3122094E5E on host 192.168.1.127 and port 26407 
2023-09-06 20:41:05.499  INFO  Connected to station T8010T2322090471 on host 192.168.1.108 and port 19961 
2023-09-06 20:41:07.395  INFO  Push notification connection successfully established 
2023-09-06 20:41:54.511  INFO  Client disconnected with ip: 127.0.0.1 port: 58132 code: 1000 reason: Normal Closure

I searched for the error here and found some relations to trusted device, but trying to follow those steps and nothing changes. 

What should I do?

**Comment by chesterflaps** [comment]
Same here. It seems to be happening every few weeks

**Comment by tmbs1988** [comment]
Nothing is working still.. several weeks gone by

**Comment by tmbs1988** [comment]
Still not working after several weeks

**Comment by petekhome2k** [comment]
It’s been around 8 weeks now I’ve been unable to get this integration working. I’ve exhausted all avenues.

**Comment by fuatakgun** [comment]
Still no-one is bothering to follow the bug template but everyone is complaining!
