### ISSUE TITLE
Dual Doorbell Loitering Detection Toggle

### ISSUE THREAD

**Issue by Colorado4Wheeler** [fuatakgun/eufy_security#919]
**Is your feature request related to a problem? Please describe.**
First off, I really love this integration, it's really quite comprehensive and extremely useful!  I would love to see the ability to turn loitering detection on and off as needed from the integration.  I don't know if the API supports it, but you can do this in the device settings.  I toggle the motion detection regularly when I'm working near the doorbell to stop alerts, but the loitering detection is always still going unless I change the settings in the app.

**Describe the solution you'd like**
A toggle just like motion detection.

**Comment by fuatakgun** [comment]
try with 7.3.0 version and let me know.

Also, if it doesn't work, generate debug logs and share with me.
