### ISSUE TITLE
Be able to change the colour of my Wall Light Cam Light (currently only on/off for light and need to change colour in eufy app)

### ISSUE THREAD

**Issue by nugget200** [fuatakgun/eufy_security#924]
**Is your feature request related to a problem? Please describe.**
I cannot change the colour of the light of the Wall Light Cam within HA

**Describe the solution you'd like**
Be able to change the colour of the light as well as just on/off

Device:
T84A1
by Eufy Security
Firmware: 1.0.8.8

**Comment by amatt09** [comment]
+1

**Comment by fuatakgun** [comment]
![image](https://github.com/fuatakgun/eufy_security/assets/11085566/879e43bd-cd71-4964-817a-8787be763e8f)

**Comment by nugget200** [comment]
Works really well thank you!Implementing colour choice would be great at somepoint if possible but this is very useful!One issue is since updating it now seems that the start P2P won’t go past preparing and therefore can’t view the live video feed, any ideas?On 16 Oct 2023, at 21:56, Fuat Akgün ***@***.***> wrote:﻿
I just implemented these;

brightness adjustment
switching between active modes (daily, activity and dynamic)
switching between daily lighting modes (cold, warm. very warm)
switching between dynamic lighting modes

Implementing RGB color selected requires a new approach, postponing it for now. Let me know what you think.
get version 7.4.0 please

**Comment by fuatakgun** [comment]
I had a s100 camera and p2p streaming is working fine for me.

You can create a separate issue to track this but please follow the bug template

**Comment by ToyNBoys** [comment]
Hi ! @nugget200 ligth switch on/off is still working for you ?

**Comment by nugget200** [comment]
@fuatakgun @ToyNBoys It has stopped working for me too

**Comment by ToyNBoys** [comment]
> @fuatakgun @ToyNBoys It has stopped working for me too

just restarted the devices and looks like its back to OK !

lets see...

**Comment by nugget200** [comment]
Strange! I have two of the lights, both on 1.1.0.2 and it’s working fine on one, and not at all on the other. Have tried restarting through eufy app and by cutting power a few times and still no luck. Works okay if using eufy app to turn light on or off

**Comment by ToyNBoys** [comment]
> Strange! I have two of the lights, both on 1.1.0.2 and it’s working fine on one, and not at all on the other. Have tried restarting through eufy app and by cutting power a few times and still no luck. Works okay if using eufy app to turn light on or off

yeah strange... I also restarted HA, you can try as well

I also have two of them ;)
