### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by multinet33** [fuatakgun/eufy_security#926]
I've a 4 camera Euf cam e 

The integration with home assistant works well but since few week I've one camera (entity camera.name) that does not provide image 

All another entity of this camera are working and 
All other camera are ok

![image](https://github.com/fuatakgun/eufy_security/assets/17277695/372e54dc-93a1-4e68-a9d8-1239bfa1bdf2)

**Comment by fuatakgun** [comment]
I can do nothing on that end, sorry, all the images are coming from encrypted cloud and it needs to be pushed to integration by add-on.

You can check with bropat but there are many issues on that his end too.

**Comment by fuatakgun** [comment]
I would check where events are stored and if there is space left.
