### ISSUE TITLE
Motion detected always clear from motion sensors

### ISSUE THREAD

**Issue by GavinEke** [fuatakgun/eufy_security#927]
**Describe the bug**

The binary sensor of motion detected for all my Eufy motion sensors are always clear in HA showing no motion meaning I cannot create automations based on that trigger. This is also the case for my Eufy Doorbell but I see existing issues regarding that in #764 

**To reproduce**

1. Make motion in front of motion sensor
2. Check motion sensor history and see it clear always

Alternatively create an automation based on motion detected, perform a motion in front of sensor and see it never trigger.

**Expected behavior**

When motion is detected from the motion sensor it is detected in HA

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version:  core-2023.9.1
- Eufy Security Add-on Version: 1.6.4
- Eufy Security Integration Version: 7.0.4

Hardware Information;
- Eufy Security Motion Sensor (T8910C21)
Also happens with Dual Camera Doorbell Add-On (T8213G11)

- Live Streaming Protocol (RTSP/P2P): 
N/A

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
I have added the logger config to my configuration yaml, let me know what you need if you need info

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
No errors have been reported

- Would you share your device with me in case further debugging required? (Yes/No):
No

**Comment by fuatakgun** [comment]
you need to enable all motion specific push notifications for your camera. without them, integration would not function.
can you confirm?

**Comment by GavinEke** [comment]
I did not realise that. By enabling the notification, the problem is now fixed. Thanks for your help and your awesome project 😊
