### ISSUE TITLE
Last event not updating

### ISSUE THREAD

**Issue by geidorei** [fuatakgun/eufy_security#929]
Stopped working after recent core update, and only updates after either a restart or reloading integration.

Or, am I being thick? lol

Using camera.name and tried camera.event but that works intermittently, usually just an empty card.

**Comment by HdH-666** [comment]
+1

**Comment by rogerthn2019** [comment]
My issue might be related?
Motion ~16:30 seen by HA ~17:02
Motion detection Type changed to Person only ~17:07 seen by HA ~17:16

Running HA Core 2023.8.4

**Comment by HdH-666** [comment]
no, that would be normal. As soon as I restart the websoket, I see the last event displayed. After that, nothing changes in the status.Home Assistant 2023.9.3Supervisor 2023.09.2Operating System 10.5Frontend 20230911.0 - latestMit freundlichen GrüßenChristian HuhnVon meinem iPhone gesendetAm 04.10.2023 um 17:34 schrieb rogerthn2019 ***@***.***>:﻿
My issue might be related?
Motion ~16:30 seen by HA ~17:02
Motion detection Type changed to Person only ~17:07 seen by HA ~17:16
Running HA Core 2023.8.4

**Comment by amatt09** [comment]
have the same issue

**Comment by xNUTx** [comment]
Same here, on a clean installation. Which is probably why the developers don't experience the same issue...

Every time I reboot the whole VM containing HA the image updates to the last time my doorbell was rang. It so far never updated when it should.

**Comment by fuatakgun** [comment]
did you configure all motion notifications with picture using mobile app? event image will be updated based on incoming push notifications, there is no other way around.

**Comment by fuatakgun** [comment]
BTW, I have a development environment which I setup every time on a clean installation and I am not facing this issue there too. Please do not make premature conclusions/assumptions.

**Comment by xNUTx** [comment]
> did you configure all motion notifications with picture using mobile app? event image will be updated based on incoming push notifications, there is no other way around.

You mean the Eufy app itself, or?

**Comment by fuatakgun** [comment]
quoting: https://github.com/fuatakgun/eufy_security#how-is-this-working

```
As we already called out earlier, add-on heavily relies on push notifications, so you must enable all kind of push notifications (motion detected, person detected, lock events, alarm events etc) in your mobile app. These notifications are not user based but device based so after enabling all these notifications, your main account will probably bloated with many push notifications. In android, there is a setting to disable specific notifications, please use it.
```

**Comment by xNUTx** [comment]
> BTW, I have a development environment which I setup every time on a clean installation and I am not facing this issue there too. Please do not make premature conclusions/assumptions.

I stand corrected... my appologies.

> yes

I actually need to check that...

**Comment by fuatakgun** [comment]
you can also enable debug logs following bug template/readme and generate a motion event and validate that you are receiving the motion event on home assistant. Through the logs, I can see what is happening on logs

**Comment by xNUTx** [comment]
Interesting. I tested that before and it did not matter. Now there have been some updates on HA and on the intergations it seems to be working, but I was only able to test motion detection right now. I am currently not at home. I will try and ring the doorbell once I am and see if the image is updated.

**Comment by xNUTx** [comment]
By absolute chance a delivery driver tried to drop something off, which confirmed the doorbell ringing actually updated that picture. Interesting... I am 100% sure I did test this all before and it refused to update...

**Comment by fuatakgun** [comment]
So, it is all working?

**Comment by xNUTx** [comment]
For me, yes. Finally 💯

**Comment by geidorei** [comment]
Thanks for update, will have a look at this tomorrow.
