### ISSUE TITLE
Door Lock Support

### ISSUE THREAD

**Issue by rstuke82** [fuatakgun/eufy_security#93]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to be able to at least view my door lock status within home assistant

**Describe alternatives you've considered**
Tried other Eufy apps

**Additional context**
My lock shows up with this integration and I can see a battery status, tho I am not sure if its accurate.  And it does show my model number and serial number but locking and unlocking my smart lock does not seem to change the status at all.  Is it possible for this to be implemented?  I don't need control, but viewing status would be great.

**Comment by bropat** [comment]
Good news: I was able to decrypt the communication. I can now close and open the lock.
I still have to decipher and implement a few small things so that everything runs smoothly, but the hardest part is now behind me.
In the next few days I will publish the new version with support for the device.

**Comment by FlouHappy** [comment]
![image](https://user-images.githubusercontent.com/42975832/182985524-343e3a24-d172-45e7-8a55-4657c3410d47.png)

**Comment by FlouHappy** [comment]
I don't know if its me but I looked everywhere for answers and still nothing works. I have a T8520 and followed all the instructions from @fuatakgun  [installation steps](https://github.com/fuatakgun/eufy_security#6-installation). Here is my log from Eufy Security add-on
![image](https://user-images.githubusercontent.com/42975832/182986230-9502eaa4-b710-4321-950d-88786d761d0e.png)
