### ISSUE TITLE
I see only images.... :(

### ISSUE THREAD

**Issue by JaySpec1488** [fuatakgun/eufy_security#931]
Hello.

How can i enable live stream? I only get fixed pictures. 🙃

**Comment by tebib91** [comment]
me too

**Comment by geidorei** [comment]
Hi - did you follow all the instruction for install & setup? You should have following within a card (substitute your own entities):

https://github.com/fuatakgun/eufy_security - see Part 4

Just click once on the picture (last event) and it should start streaming. Bear with it as it can take a few seconds to start. I'd check the issues as well, as there are some problems at the moment, with me the streaming can cause HA to reboot and/or throw errors up.

**Comment by tebib91** [comment]
yes i follow  the instractiion and i think the probleme with RTSP  
it work some time only when i press in conf of device : start  stream  and it's too slow   to start video

**Comment by JaySpec1488** [comment]
> yes i follow the instractiion and i think the probleme with RTSP it work some time only when i press in conf of device : start stream and it's too slow to start video

Exactly Same here.....

**Comment by geidorei** [comment]
FYI that's now happening with me as well now... Looking at the other issues this is probably related, just give them a bit of time for a fix.

**Comment by JaySpec1488** [comment]
Any news here what we can do? 😁

**Comment by JaySpec1488** [comment]
Does this help? I got this meassage every time:
![Screenshot_20230923_050930_Home Assistant](https://github.com/fuatakgun/eufy_security/assets/145002206/367a5ccc-c171-404b-911a-f34d4433b38f)

**Comment by geidorei** [comment]
Same here....

**Comment by 4webat** [comment]
Same here

**Comment by smartmatic** [comment]
I have the same issue and i get also this error

`Logger: homeassistant.components.stream.stream.camera.vordertur
Source: components/stream/__init__.py:431
Integration: Stream (documentation, issues)
First occurred: 21:47:59 (7 occurrences)
Last logged: 21:51:29

Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsp://****:****@192.168.xxx.xx/live0 `

**Comment by fuatakgun** [comment]
please follow the bug template, share the logs and required information
