### ISSUE TITLE
Possible to export rtsp stream to frigate?

### ISSUE THREAD

**Issue by Austin1** [fuatakgun/eufy_security#934]
I have an 8201 doorbell camera. I believe it's all working but I can use the rtsp link in the device configuration with VLC? I'm testing to see if it's possible to use with VLC before putting into frigate. 

After configuring eufy-ws, I used this integration and also installed RTSP simple server. I had to change the port to 3002 in simple server. Not sure why but kept saying 3000 is taken when starting the server. 

I then tried the link showing in device configuration under RTSP but changed localhost to the server IP 192.168.1.4 in my case. 

rtsp://localhost:8554/T8201N0020240368
I get no stream found with this url

However I noticed 8554 is port on RTSP simple server. So I tried changing above to 3001 from 8554 and it appears to open a blank stream. 

All that said is using the rtsp stream in frigate even possible?

**Comment by fuatakgun** [comment]
Rtsp would be published when you call start_livestream service on the camera until that moment rtsp doesn't receive any frames.

Use the initial rtsp address, it is calculated and generated internally.

To sum up;
1- call turn_on or start_livestrram service call on the camera
2- wait for stream_status to move from IDLE, PREPARING and hopefully STREAMING
3- At this moment, you can try rtsp url on vlc
