### ISSUE TITLE
Add calibrate button/service

### ISSUE THREAD

**Issue by Cheerpipe** [fuatakgun/eufy_security#936]
**Is your feature request related to a problem? Please describe.**
Eufy cameras supports a calibrate command. I tested it and is working well using this:

service: eufy_security.send_message
data:
  message: {"messageId": "calibrate","command": "device.calibrate","serialNumber": "T8410PZZZZZZZZZZ"}

This command is usefull to ensure camera fov is OK and to fix len position after a external/phisical manupulation of the camera

**Describe the solution you'd like**
Would be nice to have a button and/or service to call calibrate without need of a script.

**Describe alternatives you've considered**
Create a calibrate button and/or service

**Additional context**
Tested on a Indoor Cam 2K Pan & Tilt

**Comment by fuatakgun** [comment]
hey, I do not see calibrate command here: https://bropat.github.io/eufy-security-ws/#/api_cmds?id=station-level-commands

**Comment by fuatakgun** [comment]
get 7.2.0 and you will have it

**Comment by Cheerpipe** [comment]
Working well on my eufy 2k pan tilt.

Thanks!
