### ISSUE TITLE
Motion Sensor switch not working

### ISSUE THREAD

**Issue by muckie89** [fuatakgun/eufy_security#937]
its not possible to deactivate/activate the motion dectection. If i click the switch in homeassistant it switches to off and after 1 second back to on 

**To reproduce**

1. Go to 'Integration'
2. choose your camera 
3. hit the motion dectection switch to disable / enable it 
4. see that the switch is not working

**Expected behavior**

Disable /enable the motion dectection in homeassistant 

**Additional information**

core-2023.9.3
eufy security 7.0.4
eufy-security-ws 1.6.4
![Screenshot 2023-09-28 111625](https://github.com/fuatakgun/eufy_security/assets/90051427/9de24726-8fc1-4fd0-baa0-142b20180293)

**Comment by fuatakgun** [comment]
create an issue with logs
