### ISSUE TITLE
Lock not responding to unlock/lock commands

### ISSUE THREAD

**Issue by marcelrees** [fuatakgun/eufy_security#940]
**Describe the bug**
The log shows the status & other sensors correctly, but when I click on the lock or unlock button, nothing happens.

**To reproduce**
Either when I go to a dashboard or to the device itself and click the unlock/lock button, nothing happens at all. The Eufy app actions immediately.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: core-2023.9.3
- Eufy Security Add-on Version: 1.6.4
- Eufy Security Integration Version: v7.0.4

Hardware Information;
- Lock Model: T8520N

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
Below are the logs that appear whenever I try trigger the lock/unlock command. 
 
`2023-10-02 11:50:52.816 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] domain - device - EventSourceType.product - device.set_property - {'domain': 'device', 'serial_no': 'T8520Q2523070BF4', 'name': 'locked', 'value': False} - {'name': 'locked', 'value': False, 'serialNumber': 'T8520Q2523070BF4'}
2023-10-02 11:50:52.816 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] {'name': 'locked', 'value': False, 'serialNumber': 'T8520Q2523070BF4', 'command': 'device.set_property', 'messageId': 'device.set_property.f1f646964531405caecf526d589cc060'}
2023-10-02 11:50:52.817 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] send_message - {'name': 'locked', 'value': False, 'serialNumber': 'T8520Q2523070BF4', 'command': 'device.set_property', 'messageId': 'device.set_property.f1f646964531405caecf526d589cc060'}
2023-10-02 11:50:52.821 DEBUG (MainThread) [custom_components.eufy_security.eufy_security_api] _on_message - {'type': 'result', 'success': True, 'messageId': 'device.set_property.f1f646964531405caecf526d589cc060', 'result': {'async': True}}`

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
I don't believe the below logs are relevant as the timestamp is very different. Though you may find them useful:
`  },
  data: '{"r'
}
2023-10-02 00:45:26.881  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2707,
  value: '{"r'
}
2023-10-02 00:45:26.882  ERROR JSON parse error 
{
  error: {
    message: 'SyntaxError: Unexpected end of JSON input',
    stacktrace: 'SyntaxError: Unexpected end of JSON input\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:154:21)\n' +
      '    at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n' +
      '    at Camera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at Camera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)\n' +
      '    at EufySecurity.updateDevice (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:344:44)\n' +
      '    at EufySecurity.handleDevices (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:560:22)\n' +
      '    at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:167:50)'
  },
  data: '{"r'
}
2023-10-02 00:45:26.883  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2707,
  value: '{"r'
}
2023-10-02 00:45:26.884  ERROR JSON parse error 
{
  error: {
    message: 'SyntaxError: Unexpected end of JSON input',
    stacktrace: 'SyntaxError: Unexpected end of JSON input\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:154:21)\n' +
      '    at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n' +
      '    at Camera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at Camera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)\n' +
      '    at EufySecurity.updateDevice (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:344:44)\n' +
      '    at EufySecurity.handleDevices (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:560:22)\n' +
      '    at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:167:50)'
  },
  data: '{"r'
}
2023-10-02 00:45:26.884  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2708,
  value: '{"r'
}
2023-10-02 00:45:26.885  ERROR JSON parse error 
{
  error: {
    message: 'SyntaxError: Unexpected end of JSON input',
    stacktrace: 'SyntaxError: Unexpected end of JSON input\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:154:21)\n' +
      '    at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n' +
      '    at BatteryDoorbellCamera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at BatteryDoorbellCamera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)\n' +
      '    at EufySecurity.updateDevice (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:344:44)\n' +
      '    at EufySecurity.handleDevices (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:560:22)\n' +
      '    at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:167:50)'
  },
  data: '{"r'
}
2023-10-02 00:45:26.886  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2708,
  value: '{"r'
}
2023-10-02 00:45:26.887  ERROR JSON parse error 
{
  error: {
    message: 'SyntaxError: Unexpected end of JSON input',
    stacktrace: 'SyntaxError: Unexpected end of JSON input\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:154:21)\n' +
      '    at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n' +
      '    at BatteryDoorbellCamera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at BatteryDoorbellCamera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)\n' +
      '    at EufySecurity.updateDevice (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:344:44)\n' +
      '    at EufySecurity.handleDevices (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:560:22)\n' +
      '    at HTTPApi.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:167:50)'
  },
  data: '{"r'
}
2023-10-02 00:45:26.887  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2707,
  value: '{"r'
}`

- Would you share your device with me in case further debugging required? (Yes/No):
Yes

**Additional context**
Interestingly, I never had this problem in the past. It was only when I had to make the big changes lately to the new integration that this issue has emerged. The integration seems to work perfectly, except for the ability to trigger lock or unlock.

**Comment by fuatakgun** [comment]
please reach out to bropat to find out what might be the issue on add-on.

integration is successfully calling add-on to initiate lock/unlock, receiving a success response about the command but not receiving a response about new state.
