### ISSUE TITLE
Error while restarting home assistant 

### ISSUE THREAD

**Issue by sanderhoeppermans** [fuatakgun/eufy_security#948]
Hi,

Since yesterday the Eufy integration is not responding in home assistant. When I restart home assistant, there is the following error:

Eufy Security - Error
Error: <Task finished name='Task-3482' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

Do some of you guys know what is going wrong? Thanks!

**Comment by YLynx32** [comment]
Similar issue for me. Started happening a few days ago. My error message is:

Error: <Task finished name='Task-7474' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

**Comment by MechEng70** [comment]
Same issue here.  Went from 2023.9.x to 2023.10.1

Error: <Task finished name='Task-347086' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

**Comment by YLynx32** [comment]
> Similar issue for me. Started happening a few days ago. My error message is:
> 
> Error: <Task finished name='Task-7474' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

It fixed itself now

**Comment by sanderhoeppermans** [comment]
> > Similar issue for me. Started happening a few days ago. My error message is:
> > Error: <Task finished name='Task-7474' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>
> 
> It fixed itself now

Yes, strange.. For me aswel. It works again

**Comment by MechEng70** [comment]
This is still happening.  Rebooted and reloaded. 

Error: <Task finished name='Task-3620' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

**Comment by stijnb1234** [comment]
Same error:

Error: <Task finished name='Task-5053' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

**Comment by sanderhoeppermans** [comment]
> This is still happening. Rebooted and reloaded.
> 
> Error: <Task finished name='Task-3620' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

I completely deleted the integration in HACS (the repo aswel). Then I restarted home assistant, replaced the repo again via HACS and set the configuration tab again. Then restarted home assistant for the second time, after that it worked for me.

**Comment by stijnb1234** [comment]
> > This is still happening. Rebooted and reloaded.
> > Error: <Task finished name='Task-3620' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>
> 
> I completely deleted the integration in HACS (the repo aswel). Then I restarted home assistant, replaced the repo again via HACS and set the configuration tab again. Then restarted home assistant for the second time, after that it worked for me.

Full reinstall seems to fix it indeed.
