### ISSUE TITLE
CARD management - Creation of further ATTRIBUTES - Insertion of sensors in binary_sensor.py

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#95]
Hi,
I created a card with the ability to control the cam in 4 directions, with motion / audio alert sensors, the various security modes, the refresh for manual synchronization and the ability to manage settings as per the official Eufy App, which are synchronized bidirectionally.

At the moment, the status LED and Automatic Night Vision are not synchronized bi-directionally. It is possible to send the command from Home Assistant (and see it on the official App), but it is not possible to see the real status on Home Assistant when the command is sent from the official Eufy App. If you have any advice, they are welcome!

@fuatakgun  I proceeded to create three other binary sensors in the binary_sensor.py file, you can integrate them in the addon as you did for the ones I had previously inserted:

```
        ("motion_detection_enabled", "Motion Detection", "state.motionDetection", None, DEVICE_CLASS_MOTION),
        ("sound_detection_enabled", "Sound Detection", "state.soundDetection", "mdi: account-voice", None),
        ("pet_detection_enabled", "Pet Detection", "state.petDetection", "mdi: dog", None),
```

Also, **could you create the missing attributes** for **Person Detection** and **All Other Detection**? I couldn't find them and I'd like to finish the card and make it complete.

@bropat 
The Pet Detection sensor attribute does not seem to work as it does not send the command to enable or disable such detection. I tried in the following ways:

```
              - service: eufy_security.send_message
                date:
                  message: | -
                    {
                      "messageId": "petDetection",
                      "command": "device.set_property",
                      "serialNumber": "T8410Pxxx",
                      "name": "petDetection",
                      "value": true (or false)
                    }
  ``` 
                 
   ```                 
              - service: eufy_security.send_message
                date:
                  message: | -
                    {
                      "messageId": "message_id_do_not_add_value_here",
                      "command": "device.set_pet_detection",
                      "serialNumber": "T8410Pxxx",
                      "value": true (or false)
   ```            

Could you kindly tell me what is the right command to activate animal detection? Thanks

@DivanX10 did you manage to create the slider to change the speaker volume?
In case you could share the code so I put it on the card? Thanks

When the card is tested and fully functional, if anyone cares, I'll be happy to share it

<img width="252" alt="Schermata 2021-10-26 alle 16 47 18" src="https://user-images.githubusercontent.com/63554131/138903803-9e606a40-fb83-4408-bad6-2d50cd4b7853.png">

Just for info, the card provides an image when the cam is off, another when the cam is starting up and finally the stream in real time with webrtc.

**Comment by fuatakgun** [comment]
I have added 3 specific more sensor you had asked in the main issue. if you need more please specify them.

**Comment by SmartM-ui** [comment]
> I have added 3 specific more sensor you had asked in the main issue. if you need more please specify them. they will be available in next version.

Hi @fuatakgun 
thank you for accommodating my requests!
I went ahead with the Card, if possible and if you like to share, could you also insert this sensor in sensor.py please?

```
("speakervolume", "speakerVolume", "state.speakerVolume", PERCENTAGE, None, None),
("motionDetectiontype", "motionDetectionType", "state.motionDetectionType", None, None, None),
```

In binary sensor, compared to what is reported in the first post, there are the following sensors (I eliminated the Pet Detection sensor as it is not recognized by the eufy app and I added the LED status)

```
         ("motion_detection_enabled", "Motion Detection", "state.motionDetection", None, DEVICE_CLASS_MOTION),
         ("sound_detection_enabled", "Sound Detection", "state.soundDetection", "mdi: account-voice", None),
         ("led_status_enabled", "Led Status", "state.ledStatus", "mdi: led-on", None),
```

This is the progress of the card:

<img width="253" alt="Schermata 2021-11-10 alle 12 35 39" src="https://user-images.githubusercontent.com/63554131/141107353-5ac74dd8-a1be-4b68-bcc6-5c1e535ab97e.png">

**Comment by SmartM-ui** [comment]
> I have added 3 specific more sensor you had asked in the main issue. if you need more please specify them. they will be available in next version.

Hi @fuatakgun ,
I made the update proposed yesterday for your HACS integration, but there are no new sensors, (not even the binary sensors of the first post)

Just for information, do you think you put them in for everyone or do you prefer me to package the sensors just for me (for the card)? The sensors I added are:

binary_sensor.py
```
        ("motion_detection_enabled", "Motion Detection", "state.motionDetection", None, DEVICE_CLASS_MOTION),
        ("sound_detection_enabled", "Sound Detection", "state.soundDetection", "mdi: account-voice", None),
        ("led_status_enabled", "Led Status", "state.ledStatus", "mdi: led-on", None),
```

sensor.py:
```
		("speakervolume", "speakerVolume", "state.speakerVolume", PERCENTAGE, None, None),
		("motionDetectiontype", "motionDetectionType", "state.motionDetectionType", None, None, None),
```

Thanks

**Comment by fuatakgun** [comment]
please get latest version: https://github.com/fuatakgun/eufy_security/issues/59#issuecomment-968352909

**Comment by SmartM-ui** [comment]
> please get latest version: [#59 (comment)](https://github.com/fuatakgun/eufy_security/issues/59#issuecomment-968352909)

Hi @fuatakgun ,
i just updated Eufy HACS (3ddbb3e) and noticed these two sensors are missing in sensor.py:
```
		("speakervolume", "speakerVolume", "state.speakerVolume", PERCENTAGE, None, None),
		("motionDetectiontype", "motionDetectionType", "state.motionDetectionType", None, None, None),
```

and the ledStatus sensor in binary_sensor.py
```
("led_status_enabled", "Led Status", "state.ledStatus", "mdi: led-on", None),
```

Could you add them please?
If it's not possible, I put them in my packages so I don't have to manually put them back on every update.

Thanks

**Comment by fuatakgun** [comment]
added

**Comment by SmartM-ui** [comment]
> added

Hi,
thanks, sensors are missing in sensor.py:
```
("speakervolume", "speakerVolume", "state.speakerVolume", PERCENTAGE, None, None),
("motionDetectiontype", "motionDetectionType", "state.motionDetectionType", None, None, None),
```
