### ISSUE TITLE
RTSP stream does not start using WebRTC and example code

### ISSUE THREAD

**Issue by smartmatic** [fuatakgun/eufy_security#950]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

I've switched from Homebase 2 and eufy 2 und 2c camera to Homebase 3 and S300 cameras. Intgegration of the Homebase and cameras works like a charm. Thank you for that!

Then i've used the yaml code from point 4 of the docu[https://github.com/fuatakgun/eufy_security#4-setting-up-your-dashboard-for-camera](url)

I can see a image in the dashboard but the stream does not start with error message "Can't get URL for camera.garten

![Bildschirmfoto 2023-10-12 um 14 05 48](https://github.com/fuatakgun/eufy_security/assets/74932663/9471e66b-9c33-41ab-8a6d-cbd7ef5d8455)

**To reproduce**

**Expected behavior**

Start and stop of the stream should be possible

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):  OS
- Home Assistant Core Version: 2023.10.1
- Eufy Security Add-on Version: 1.6.4
- Eufy Security Integration Version: v7.0.4

Hardware Information;
- Camera Model: S300

- Live Streaming Protocol (RTSP/P2P): 
-RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue

I've removed the Debug log as i have seen that my RTSP user and password is visible in that log!!!

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

```
reconnect... 
2023-10-11 21:42:45.881  INFO  Disconnected from station xx 
2023-10-11 21:43:06.006  WARN Tried all hosts, no connection could be established to station xxx. 
2023-10-11 21:43:06.009  INFO  Timeout connecting to station xx 
2023-10-11 21:43:16.327  INFO  Connected to station xxxx on host 192.168.178.10 and port 14867 
2023-10-11 23:18:00.626  ERROR Push client - Socket Error 
{
  error: {
    message: 'Error: read ECONNRESET',
    stacktrace: 'Error: read ECONNRESET\n' +
      '    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)'
  }
}
2023-10-11 23:18:00.649  INFO  Push notification connection closed 
2023-10-11 23:18:05.869  INFO  Push notification connection successfully established 
2023-10-12 09:33:01.712  INFO  Push notification connection closed 
2023-10-12 09:33:07.366  INFO  Push notification connection successfully established 
2023-10-12 09:56:21.323  INFO  Push notification connection closed 
2023-10-12 09:56:26.543  INFO  Push notification connection successfully established 
```

- Would you share your device with me in case further debugging required? (Yes/No):

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by Nodezero1** [comment]
Hello,
I have a similar problem, I upgraded to the Base 3 and now streaming my 2C cameras are spotty.  I found if I restart RTSP in the Eufy app it will stream one time and then fail.

**Comment by marcokitzmann** [comment]
> Hello, I have a similar problem, I upgraded to the Base 3 and now streaming my 2C cameras are spotty. I found if I restart RTSP in the Eufy app it will stream one time and then fail.

Similar here, 2C Pro with Upgrade to HomeBase 3. Each cam can be turned on once for streaming. After that I have to reload integrations.

**Comment by fuatakgun** [comment]
please reach out to bropat, add-on is disconnecting with the homebase.

Integration sends the command to add-on and waits for respond, if it fails, you wont have the response.
