### ISSUE TITLE
T8021 doorbell and T8530 lock

### ISSUE THREAD

**Issue by rlippmann** [fuatakgun/eufy_security#951]
**Is your feature request related to a problem? Please describe.**
This is sold as a combo as the S330 Video Smart Lock.  Using this with Home Assistant kind of works.

**Describe the solution you'd like**
Alarm and some general controls work, however, the camera and things like lock/unlock don't work.

**Describe alternatives you've considered**

**Additional context**
I don't know whether the issue is on this HA integration side, or the websocket server side.  And whether since this isn't a supported device if the camera/locks aren't being exposed to the home assistant client.

I'll gladly run tests to help/look at the code.  I can do python, but I can't really help on the websocket side (javascript)

**Comment by fuatakgun** [comment]
please work with bropat.

https://bropat.github.io/eufy-security-client/#/supported_devices
