### ISSUE TITLE
Nice with new 7.2.0 but not solving all things

### ISSUE THREAD

**Issue by AseKarlsson** [fuatakgun/eufy_security#953]
Great to get a new version 7.2.0 and now the integration can start on HA 2023.10.3 with OS 11.0. without errors.

The integration now start without errors, but still not able to start P2P stream that worked fine with HA 2023.9.x

WebRTC also got updated to 3.4.0 during this time.

Any ideas?

Thanks,
Ase

**Comment by fuatakgun** [comment]
sharing the device with me or sharing the logs :)

**Comment by AseKarlsson** [comment]
Do you have their T8220-Z doorbell with Homebase T8020 and it works for You?
Please advice how to activate proper log levels for you to troubleshoot and how to deliver those to you,
Don’t want to share all logs to openly here, they can include secrets that I missed to sanitised.

Thanks,
Ase

**Comment by fuatakgun** [comment]
I have;
- 2C
- indoor pan tilt
- S100

follow the readme file and you can post them to fuatakgun@gmail.com
Your password is part of add-on and integration would not fetch it, so it should be safe to share over email.

**Comment by AseKarlsson** [comment]
Checked the readme file now several times. Cannot see the log level you want and what exact logs.

**Comment by fuatakgun** [comment]
> Event image is not updating either whenever there is motion or person detected. I have an S100.

I have S100 camera at home and event image is working fine. So, it is a specific thing probably missing on your setup we need to find out. @amatt09 , what do you want me say here, I do not now. 

```
Garden Event Image changed to October 16, 2023 at 17:46
17:46:22 - 4 hours ago

Garden Event Image changed to October 16, 2023 at 17:41
17:41:40 - 4 hours ago
```

![image](https://github.com/fuatakgun/eufy_security/assets/11085566/a544c118-0074-4a2f-b4c8-4dc6b8193d8c)

**Comment by fuatakgun** [comment]
@AseKarlsson , sorry, I meant, debug template, not readme.

**Comment by AseKarlsson** [comment]
@fuatakgun , it was pa art of the readme. But no info there on log level or what files to send.

**Comment by fuatakgun** [comment]
you know, the issue is that, this bug was not created properly. Instead of deleting the bug template with all the contents and replacing whatever you want to write, we would not be having this discussion right now.

But, interestingly, I have been having this conversation many times. I have explicitly called out in the bug template that, without logs, I will resolve the issue, so I must do it and you should follow the template.

```
Without this, I will automatically resolve this issue
```

**Comment by AseKarlsson** [comment]
> I have;
> 
> * 2C
> * indoor pan tilt
> * S100
> 
> follow the readme file and you can post them to [fuatakgun@gmail.com](mailto:fuatakgun@gmail.com) Your password is part of add-on and integration would not fetch it, so it should be safe to share over email.

If you do not have more devices from them I understand that the support for this integration is hard :(

**Comment by fuatakgun** [comment]
Eufy would not give us devices, this is an unofficial integration and I am sure they even do not like us.

**Comment by AseKarlsson** [comment]
I know your integration is an unofficial and thankful for your wok. Let’s hope you get this working again!
