### ISSUE TITLE
EufyCam E: one camera out of 4 does not have event image and camera recognize

### ISSUE THREAD

**Issue by multinet33** [fuatakgun/eufy_security#956]
Hello

I've using eufycam integration to access all my 4 camera systems.

Since few week one camera out of 4 does not provide this entity :
   - image.<name_of_camera>_event_image
   - camera.<name_of_camera>

![Capture d’écran 2023-10-19 à 12 28 37](https://github.com/fuatakgun/eufy_security/assets/17277695/fe365206-57f2-4bca-862f-60492733613f)

![Capture d’écran 2023-10-19 à 12 30 47](https://github.com/fuatakgun/eufy_security/assets/17277695/c1cfb8c5-1374-47f7-8747-21c3eed3425e)

![Capture d’écran 2023-10-19 à 12 33 25](https://github.com/fuatakgun/eufy_security/assets/17277695/8089eb21-747e-4125-8027-968d54e11ee6)

I do a ton of things : 
   - update all eufy addon and integration 
   - delete and readd the camera on smartphone app
   - reboot homebase

Please note that streaming using RTSP and go2rtc is working

Thank you for your help

**Comment by fuatakgun** [comment]
please use the proper bug template and share all the information asked over it.
