### ISSUE TITLE
HomeBase connection error

### ISSUE THREAD

**Issue by joselaya** [fuatakgun/eufy_security#957]
Hi everyone!

I have been using this integration for a long time and without any issues. Since a week ago, I have found that it has stopped working. 

I have uninstalled everything and reinstalled with no good result. 

The error is displayed just when adding the Eufy integration. 

![eufy2](https://github.com/fuatakgun/eufy_security/assets/97765793/b0bd46f2-3d3e-4ed0-a33d-bf69250f5bb9)

The integration perfectly recognizes the HomeBase and Cameras, but they do not show any entity. 

![Eufy2_2](https://github.com/fuatakgun/eufy_security/assets/97765793/171412f4-9c1b-46d1-bf1c-37bb1fffdfdf)

The integration recognizes perfectly the HomeBase and Cameras, but they do not show any entity in the HomeBase.

Anyone else have this happen or any solution?
Thanks!

**Comment by joselaya** [comment]
Testing and running version 7.0.4 works perfectly. 

![Eufy2_3](https://github.com/fuatakgun/eufy_security/assets/97765793/3fc47ec5-98f9-4330-a765-b4cd6091e689)

**Comment by fuatakgun** [comment]
so, it is one of the nice issues which are being resolved by itself :) good to resolve this?

**Comment by joselaya** [comment]
> so, it is one of the nice issues which are being resolved by itself :) good to resolve this?

For now version 7.0.4 works fine for me! Waiting for a new version and do new tests. 
Thank you for your help! :-)
