### ISSUE TITLE
Quick response error

### ISSUE THREAD

**Issue by kooijman599** [fuatakgun/eufy_security#966]
I've problems with the service to send Quick Responses to my Eufy doorbell. Sometimes it works, sometimes it doesn't. I checked the log and see this error message. What does it mean and what can I do to fix it?

![Screenshot_2023-10-28-20-20-19-642_io homeassistant companion android](https://github.com/fuatakgun/eufy_security/assets/145869596/57dc6b00-6e8e-49b2-b9cc-5a1507ed4889)

**Comment by fuatakgun** [comment]
Use the bug template
