### ISSUE TITLE
Setting the mode of multiple Homebase units. Stops working and then needs to be reloaded to make it work again.

### ISSUE THREAD

**Issue by RonnieRocket2** [fuatakgun/eufy_security#974]
I am usinf the eufy_security integration together with the eufy-security-ws add on.

I have three Homebase Units 1,2 and 3.

I have one Eufy Keypad connected to Homebase 1 and have written automation rountines to set two other Homebase units (2 and 3) to whatever mode Homebase 1 is set to with the keypad (Home, Away, Off) 

This all works fine but for some reason stops working on a daily basis (one thing to note is that my Homeassisant PC automatically reboots every day just after midnight) which might be connected?

I do not know the cause of what makes it stop working but restarting eufy-security-ws and reloading the eufy_security integration fixes it. 

Anyone have any ideas?
- Home Assistant Installation Type (OS): 
- Home Assistant Core Version: core-2023.11.0
- Eufy Security Add-on Version: 1.6.4
- Eufy Security Integration Version: I do not know where to find this?

Hardware Information;
- Camera Model:n/a

- Live Streaming Protocol (RTSP/P2P): n/a 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No):

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by fuatakgun** [comment]
Duplicate
