### ISSUE TITLE
Doorbell motion/person detection not working

### ISSUE THREAD

**Issue by pkarumugam** [fuatakgun/eufy_security#977]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)
Similar issue identified (#927 - https://github.com/fuatakgun/eufy_security/issues/927)

The motion detection sensors are not changing state (both motion and person detection).  I have enabled push notifications and receive notifications on my phone.

Walk in front of the doorbell camera
Monitor Doorbell Motion Sensor state
Doorbell Motion Sensor remains at Clear 
Doorbell Person Sensor remains at Clear

**Expected behavior**
Doorbell Motion Sensor changes from Clear to Detected
Doorbell Person Sensor changes from Clear to Detected

- Home Assistant Installation Type (OS - Supvervised - Core):  Home Assistant OS
- Home Assistant Core Version: core-2023.11.0
- Eufy Security Add-on Version: 1.6.4
- Eufy Security Integration Version: 7.7.2

Hardware Information;
- Camera Model: Wired Doorbell T8200X
  

- Would you share your device with me in case further debugging required? (Yes/No):
Yes

**Comment by fuatakgun** [comment]
Please update to the newest version of add-on, if the issue persists, create a proper bug following the template.

**Comment by pkarumugam** [comment]
Hi,

What is the latest version of the integration?  Also what is wrong with my original submission?  I copied your template and filled in all the information requested.  Before I submit again, I want to make sure I get you the complete information you need.

Prem
