### ISSUE TITLE
Camera Stream only starts once since change from Homebase 2 to 3

### ISSUE THREAD

**Issue by marcokitzmann** [fuatakgun/eufy_security#978]
I dare to try again, as previous attempts seem to have failed primarily for formal reasons.

In https://github.com/fuatakgun/eufy_security/issues/950 issue was reassigned to Bropat, he denied a relation with his add-on in https://github.com/bropat/eufy-security-ws/issues/270. Both issues were closed without a solution.

**Describe the bug**

After upgrading from Homebase 2 to 3, each camera stream can only be started once. After that, eufy-security-ws and eufy_security have to be restarted to work again.

**To reproduce**

1. Start RTSP-Stream via turn.on camera
2. Watch Camera Stream
3. Stop Stream via turn.off camera
4. Start Stream again via turn.on camera
5. Video-Player says "streams: wrong response on DESCRIBE" an stops

**Expected behavior**

Streams can be started more than once.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;

Version | core-2023.10.5
Installationstyp | Home Assistant OS

- Eufy Security Add-on Version: 1.6.4 
- Eufy Security Integration Version: 7.7.2

Hardware Information;
- Camera Model:

2C Pro
Homebase 3 (S380)

- Live Streaming Protocol (RTSP/P2P): 

RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  
[debug_log_eufy_security.log](https://github.com/fuatakgun/eufy_security/files/13252821/debug_log_eufy_security.log)

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

[eufy_security_ws.log](https://github.com/fuatakgun/eufy_security/files/13252847/eufy_security_ws.log)

- Would you share your device with me in case further debugging required? (Yes/No):

Yes

**Additional context**

GO2RTC-Add-on in use.

Go2RTC-Log says:

"17:23:39.393 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.107.92:52540->192.168.107.144:554: i/o timeout" url=rtsp://****.*****@192.168.107.144/live0"

**Comment by fuatakgun** [comment]
But I have summarized my findings to you, right?

You didn't put this information to bropat.

You were supposed to share the logs from add-on with him.

He owns add-on specific issues and he is good at it.

I know integration specific issues but if add-on doesn't respond to our commands, i cannot help

**Comment by fuatakgun** [comment]
But I have summarized my findings to you, right?

You didn't put this information to bropat.

You were supposed to share the logs from add-on with him.

He owns add-on specific issues and he is good at it.

I know integration specific issues but if add-on doesn't respond to our commands, i cannot help

**Comment by marcokitzmann** [comment]
No, I didn't start that thread. But, sure, I can reach out to Bropat and give him logs also. For me, it is not easy to tell whether one or the other component is responsible for the problems I and some other are experiencing.

**Comment by fuatakgun** [comment]
Yes, it is hard to tell who owns what, but i assumed that you would share add-on logs but not the integration, because he is not a home assistant user but he knows all the stuff about add-on.

I am also actively keeping an eye on his repositories too

**Comment by fuatakgun** [comment]
There is nothing i can do, please work with bropat.

I will propose to him, i might have some support for eufy-security-client library but i am not very good in nodejs.
