### ISSUE TITLE
T8134 (S220 Solo) not well supported : Stream and alarm not working

### ISSUE THREAD

**Issue by kibohely** [fuatakgun/eufy_security#981]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

The T8134 (S220 Solo) have many entities not responding, like :
- "Start P2P Stream"  : --> Stream Status stuck on "PREPARING"
- "Reset Alarm" : {'type': 'result', 'success': False, 'messageId': 'device.reset_alarm.d8c681692dee4af1a1d2efd57e1e62b0', 'errorCode': 'device_not_supported'}
- "Trigger Alarm" : {'type': 'result', 'success': False, 'messageId': 'device.trigger_alarm.bae540fe66834e609b6113b44518e2d9', 'errorCode': 'device_not_supported'}

**To reproduce**

1. Go to 'Parameters / Devices & Services / Eufy Security / 1 device'
2. Click on entities in Diagnostic

**Expected behavior**

Camera should respond to the commands

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core):  OS ( under Qemu / Ubuntu 22.04 host)
- Home Assistant Core Version: 2023.11.1
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: not sure, it's the last one.

Hardware Information;
- Camera Model: T8134 (S220 Solo) 

- Live Streaming Protocol (RTSP/P2P): P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
`[140427724074048] {'type': 'result', 'success': False, 'messageId': 'device.reset_alarm.c984ebcf365c4b449b8e832da33cea06', 'errorCode': 'device_not_supported'}
19:12:16 – (ERREUR) Home Assistant WebSocket API - message survenu pour la première fois à 17:50:25 et apparu 8 fois.
Error doing job: Task exception was never retrieved
18:18:37 – (ERREUR) /usr/src/homeassistant/homeassistant/runner.py - message survenu pour la première fois à 18:05:53 et apparu 5 fois.
Error doing job: Task exception was never retrieved
18:18:15 – (ERREUR) Eufy Security (intégration personnalisée) - message survenu pour la première fois à 18:18:15 et apparu 5 fois.
Error doing job: Exception in callback WebSocketClient._on_close(<Task finishe...not allowed')>)
18:18:15 – (ERREUR) Eufy Security (intégration personnalisée) - message survenu pour la première fois à 18:18:15 et apparu 2 fois.
Error unloading entry 127.0.0.1 for alarm_control_panel
18:18:15 – (ERREUR) config_entries.py - message survenu pour la première fois à 18:18:15 et apparu 50 fois.
Setup xiaomi cloud for user: jerome@diniho.net failed: Login to xiaomi error: &&&START&&&{"qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","code":70016,"description":"登录验证失败","securityStatus":0,"_sign":"0psXfr43eNI0IX6q9Suk3qWbRqU=","sid":"xiaomiio","result":"error","captchaUrl":null,"callback":"https://sts.api.io.mi.com/sts","location":"","pwd":0,"child":0,"desc":"登录验证失败"}
17:45:59 – (ERREUR) Xiaomi Miot Auto (intégration personnalisée)
Xiaomi serviceLoginAuth2: ['https://account.xiaomi.com/pass/serviceLoginAuth2', {'_json': 'true'}, {'user': 'jerome@diniho.net', 'hash': '09185DA4B1D21E6742CC1E169D2166BD', 'callback': 'https://sts.api.io.mi.com/sts', 'sid': 'xiaomiio', 'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU='}, {'User-Agent': 'Android-7.1.1-1.0.0-ONEPLUS A3010-136-HFZAFNCXKOQ97K4I APP/xiaomi.smarthome APPV/62830'}, {'sdkVersion': '3.8.6', 'deviceId': 'HFZAFNCXKOQ97K4I'}]
17:45:59 – (ERREUR) Xiaomi Miot Auto (intégration personnalisée)
Can't connect to ESPHome API for atom-888770 @ 192.168.1.183: Error connecting to ('192.168.1.183', 6053): [Errno 113] Connect call failed ('192.168.1.183', 6053) (SocketAPIError)
17:45:50 – (AVERTISSEMENT) runner.py - message survenu pour la première fois à 17:45:50 et apparu 2 fois.
Unauthorized while executing request to v2/message/v2/check_new_msg, logged out.
17:45:50 – (AVERTISSEMENT) Xiaomi Miot Auto (intégration personnalisée)
TemplateError('UndefinedError: 'sensor' is undefined') while processing template 'Template<template=({{sensor.water_tank_raw | int }}) renders=4>' in entity 'None'
17:45:48 – (ERREUR) openHASP (intégration personnalisée) - message survenu pour la première fois à 17:45:48 et apparu 2 fois.
Error while processing template: Template<template=({{sensor.water_tank_raw | int }}) renders=2>
17:45:48 – (ERREUR) helpers/template.py - message survenu pour la première fois à 17:45:48 et apparu 2 fois.
Template variable error: 'sensor' is undefined when rendering '{{sensor.water_tank_raw | int }}'
17:45:48 – (ERREUR) helpers/template.py - message survenu pour la première fois à 17:45:48 et apparu 2 fois.
The 'cast' option near /config/configuration.yaml:1 has been removed, please remove it from your configuration
17:45:47 – (ERREUR) Google Cast`  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
2023-11-06 16:13:18.196  DEBUG [P2PClientProtocol.handleMsg] Received message - LOOKUP_ADDR - Got response 
```
{
  stationSN: 'T8134P2023294115',
  remoteAddress: '54.254.90.185',
  remotePort: 32100,
  response: {
    ip: '0.0.0.0',
    port: 12200
  }
}
2023-11-06 16:13:18.197  DEBUG [P2PClientProtocol.handleMsg] Received message - LOOKUP_ADDR - Got invalid ip address 0.0.0.0, ignoring response... 
{
  stationSN: 'T8134P2023294115',
  remoteAddress: '54.254.90.185',
  remotePort: 32100,
  response: {
    ip: '0.0.0.0',
    port: 12200
  }
}
2023-11-06 16:13:18.304  DEBUG [P2PClientProtocol.handleMsg] Received message - LOOKUP_ADDR - Got response 
{
  stationSN: 'T8134P2023294115',
  remoteAddress: '54.254.90.185',
  remotePort: 32100,
  response: {
    ip: '102.16.84.154',
    port: 12200
  }
}
2023-11-06 16:13:18.304  DEBUG [P2PClientProtocol.handleMsg] Trying to connect in QUICKEST mode... 
{
  stationSN: 'T8134P2023294115',
  ip: '102.16.84.154',
  port: 12200
}
2023-11-06 16:13:18.304  DEBUG [P2PClientProtocol._connect] Connecting to host 102.16.84.154 on port 12200 (CHECK_CAM) 
{
  stationSN: 'T8134P2023294115',
  address: {
    host: '102.16.84.154',
    port: 12200
  },
  p2pDid: 'EUPRCAM-235179-MNGRJ'
}
2023-11-06 16:13:18.304  DEBUG [P2PClientProtocol.handleMsg] Received message - LOOKUP_ADDR - Got response 
{
  stationSN: 'T8134P2023294115',
  remoteAddress: '54.254.90.185',
  remotePort: 32100,
  response: {
    ip: '0.0.0.0',
    port: 12200
  }
}
2023-11-06 16:13:18.305  DEBUG [P2PClientProtocol.handleMsg] Received message - LOOKUP_ADDR - Got invalid ip address 0.0.0.0, ignoring response... 
{
  stationSN: 'T8134P2023294115',
  remoteAddress: '54.254.90.185',
  remotePort: 32100,
  response: {
    ip: '0.0.0.0',
    port: 12200
  }
}
2023-11-06 16:13:33.059  WARN [Timeout._onTimeout] Tried all hosts, no connection could be established to station T8134P2023294115. 
2023-11-06 16:13:33.059  INFO  [Station.onTimeout] Timeout connecting to station T8134P2023294115 
2023-11-06 16:13:33.059  DEBUG [Station.scheduleReconnect] Station schedule reconnect 
{
  stationSN: 'T8134P2023294115',
  delay: 20000
}
2023-11-06 16:13:53.061  DEBUG [Station.connect] Connecting to station T8134P2023294115... 
{
  stationSN: 'T8134P2023294115',
  p2pConnectionType: 'QUICKEST'
}
2023-11-06 16:13:53.061  DEBUG [P2PClientProtocol.localLookup] Trying to local lookup address for station T8134P2023294115 with host 192.168.1.224 
2023-11-06 16:14:08.072  ERROR [Timeout._onTimeout] All address lookup tentatives failed. 
{
  stationSN: 'T8134P2023294115'
}
2023-11-06 16:14:08.072  INFO  [Station.onTimeout] Timeout connecting to station T8134P2023294115 
2023-11-06 16:14:08.073  DEBUG [Station.scheduleReconnect] Station schedule reconnect 
{
  stationSN: 'T8134P2023294115',
  delay: 30000
}
2023-11-06 16:14:38.089  DEBUG [Station.connect] Connecting to station T8134P2023294115... 
{
  stationSN: 'T8134P2023294115',
  p2pConnectionType: 'QUICKEST'
}
2023-11-06 16:14:38.089  DEBUG [P2PClientProtocol.localLookup] Trying to local lookup address for station T8134P2023294115 with host 192.168.1.224 

```
- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Additional context**

According to eufy_security_ws, I'm not sure that this add-on use the local adress to connect to the camera

**Comment by fuatakgun** [comment]
for unsupported actions, you need to work with bropat, they are managed with addons.

for p2p livestream, your logs do not include any commands about them. retry and share your logs including start_livestream command

**Comment by kibohely** [comment]
After rebooting the camera with Eufy official app, it's now working without issue.

Thanks you very much for this great integration, I will check with bropat for the unsupported action
