### ISSUE TITLE
After upgrading to 7.7.2, entities in integration are no longer available

### ISSUE THREAD

**Issue by twister36** [fuatakgun/eufy_security#984]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

After upgrading to 7.7.2 the entities that I had for my door lock (model: T8520) are no longer available. I reloaded and reinstalled the integration with no luck on restoring. When re-installing the integration setup successfully identifies my model T8520. I also check the Add-on and there are no errors.   

**Expected behavior**

See battery and lock status entities in the HA integration.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Version:	core-2023.11.1
- Installation Type:	Home Assistant OS
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: 7.7.2

Hardware Information;
- Door Lock Model: T8520

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
[home-assistant.log](https://github.com/fuatakgun/eufy_security/files/13276138/home-assistant.log)

 
- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
[eufy-security-ws-addon.log](https://github.com/fuatakgun/eufy_security/files/13276146/eufy-security-ws-addon.log)

- Would you share your device with me in case further debugging required? (Yes/No):
maybe.

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by fuatakgun** [comment]
Thanks for creating a proper bug.

I don't see any error on the logs interestingly.

Can you downgrade to previous version of add-on (not integration as there are not many changes) and try again?

**Comment by twister36** [comment]
> Thanks for creating a proper bug.
> 
> I don't see any error on the logs interestingly.
> 
> Can you downgrade to previous version of add-on (not integration as there are not many changes) and try again?

How do I downgrade. I was actually trying to do that earlier, but i couldn't figure it out.

**Comment by fuatakgun** [comment]
While upgrading the add-on, home assistant os is automatically creating a backup for it, you can try to downgrade via settings, system, backups.

Find more information for the process from home assistant documentation as this is a standard process.

**Comment by twister36** [comment]
Ah, unfortunately I have no backups for the addon upgrade. I only have full backups of HA.

**Comment by twister36** [comment]
I do see in the addon log the following:
2023-11-07 05:19:52.557  INFO  Client disconnected with ip: 127.0.0.1 port: 57118 code: 1000 reason: Normal Closure 
2023-11-07 05:20:01.497  INFO  Client disconnected with ip: 127.0.0.1 port: 50322 code: 1000 reason: Normal Closure 
2023-11-07 05:39:13.125  INFO  Client disconnected with ip: 127.0.0.1 port: 50338 code: 1006 reason: Abnormal Closure 
2023-11-07 05:48:29.463  INFO  Client disconnected with ip: 127.0.0.1 port: 33868 code: 1006 reason: Abnormal Closure

**Comment by fuatakgun** [comment]
You can use the previous full backup but just recover the add-on. You should just read the documentation to do so as I don't have a solution in place.

**Comment by twister36** [comment]
> You can use the previous full backup but just recover the add-on. You should just read the documentation to do so as I don't have a solution in place.

I'm not willing to risk it... my last restore from a backup ruined my HA installation and I had to rebuild from scratch. If there is anything other logs or data I can give you please let me know.

**Comment by fuatakgun** [comment]
I don't have any other suggestions for you then and I don't see any issue on the logs you have shared.

**Comment by twister36** [comment]
I did start getting this error this morning... I'm looking around trying to find more details
![image](https://github.com/fuatakgun/eufy_security/assets/114322877/cb9740c7-6c34-4bef-8d0c-04a6d490ed5d)

**Comment by twister36** [comment]
Per the above screen-shot, I do see the following error in the HA Log, if I remember correctly the add-on creates a websocket:

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:145
First occurred: 7:39:54 AM (1 occurrences)
Last logged: 7:39:54 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

**Comment by fuatakgun** [comment]
This happens when home assistant core has lost websocket connection with add-on and trying to set up a new connection.

I cannot comment why connection is dropped/broken in first hand.

**Comment by twister36** [comment]
Ok, I was able to use my backup to restore the add-on to my previous version of 1.6.4. Same result no entities.... 

However, after digging more I noticed that my entity lock.front_door was disabled, so I've enabled as you can see from the screen shoot attached and the entity is now working. For the other entities, you can see it says that the entity is disabled by "Integration"

![image](https://github.com/fuatakgun/eufy_security/assets/114322877/d28c4f22-ce97-4c42-bbbd-dcc4f3cef8ca)

After enabling all the entities, waiting a few minutes all entities are now working. I'm still on 1.6.4 for the add-on and 7.7.0 for the integration. Any major reason I need to upgrade again?

**Comment by fuatakgun** [comment]
It is up to you to decide to upgrade or not, check release notes to assess this

**Comment by DrSpaldo** [comment]
I've also started getting similar errors since the last update or so. Here is one of the log messages I am getting:

```
Logger: homeassistant.setup
Source: setup.py:288
First occurred: 11:09:37 (1 occurrences)
Last logged: 11:09:37

Error during setup of component eufy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/eufy/__init__.py", line 61, in setup
    data = lakeside.get_devices(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lakeside/__init__.py", line 39, in get_devices
    token = r.json()['access_token']
            ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'
```

**Comment by fuatakgun** [comment]
@DrSpaldo you issue is coming from eufy component of core not eufy security custom component

**Comment by karllogue** [comment]
I'm getting nearly the exactly same error as DrSpaldo:

Logger: homeassistant.setup
Source: setup.py:333
First occurred: 2:32:57 AM (1 occurrences)
Last logged: 2:32:57 AM

Error during setup of component eufy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/eufy/__init__.py", line 61, in setup
    data = lakeside.get_devices(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lakeside/__init__.py", line 39, in get_devices
    token = r.json()['access_token']
            ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'


I've seen that approximately every other HA update causes all of my Eufy devices to no longer be recognized. I'm constantly restoring previous versions of HA and awaiting a version that doesn't break Eufy.  This particular error seems to be consistent regardless of whether the HA version is currently working or not.
