### ISSUE TITLE
Failed to Set up Eufy - It worked earlier 

### ISSUE THREAD

**Issue by SusKahl** [fuatakgun/eufy_security#985]
Hi 
I have ad Eufy running for quit some time on my HA. but this summer it stopped working. I found out if I roled back to an old version (6.1 I think) it all started working again. Then I would just not update until winter when it was time to sit inside again. Perhaps the problem was fixed in one of the next updates.
Now I've updated, uninstalled, reinstalled and I'm probably worse of now than when I started :D  Before the integration knew my Cameras (4) and the HomeBase. Now it knows nothing... It just says "Faild to Set up". 
When I look into the Log it says

2023-11-07 15:50:39.090  ERROR Message error 
 Error  
details:
{
  schemaId: 19,
  errorCode: 'schema_incompatible'
}
error stack:
• server.ts:91 receiveMessage
    src/lib/server.ts:91:27

• server.ts:68 <anonymous>
    src/lib/server.ts:68:53

• node:events:513 emit
    node:events:513:28

• websocket.js:1178 receiverOnMessage
    node_modules/ws/lib/websocket.js:1178:20

• node:events:513 emit
    node:events:513:28

• receiver.js:528 dataMessage
    node_modules/ws/lib/receiver.js:528:14

• receiver.js:446 getData
    node_modules/ws/lib/receiver.js:446:17

• receiver.js:148 startLoop
    node_modules/ws/lib/receiver.js:148:22

• receiver.js:83 _write
    node_modules/ws/lib/receiver.js:83:10

• writable:391 writeOrBuffer
    node:internal/streams/writable:391:12

Where am I off? or where shall I start to look?

**Comment by fuatakgun** [comment]
update the addon (eufy-security-ws - 1.7.1) and integration (v7.7.2) to latest version.

**Comment by fuatakgun** [comment]
check readme.
