### ISSUE TITLE
Doorbell Motion Detected / Person detected not working

### ISSUE THREAD

**Issue by pkarumugam** [fuatakgun/eufy_security#986]
** Description of bug**
Doorbell motion detected and Doorbell Person detected always showing Clear.  Noted that Doorbell Event Image does get updated.
Similar issue identified (https://github.com/fuatakgun/eufy_security/issues/927).  In that instance, the person had not switched on notifications. I receive notifications on my phone when the event occurs.

**To reproduce**
Walk in front of the doorbell.
Review the Logbook or History for the Doorbell entity.
Notice that the Doorbell Motion detected or Doorbell Person detected does not change.

**Expected behavior**
Doorbell Motion detected or Doorbell Person detected both change to Detected

**Additional information**

Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS
Home Assistant Core Version: core-2023.11.0
Eufy Security Add-on Version: 1.7.1
Eufy Security Integration Version: 7.7.3

Hardware Information;
- Camera Model: T8200X
- Live Streaming Protocol (RTSP/P2P):  Not using currently but plan to use RTSP if I can get the doorbell person detection to work.

- Debug Logs from Home Assistant
[home-assistant.log.110723.log](https://github.com/fuatakgun/eufy_security/files/13291095/home-assistant.log.110723.log)

  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
[402f1039_eufy_security_ws_2023-11-08T01-40-00.924Z.log](https://github.com/fuatakgun/eufy_security/files/13291123/402f1039_eufy_security_ws_2023-11-08T01-40-00.924Z.log)

- Would you share your device with me in case further debugging required? Yes

**Additional context**

I have re-installed the add-on and integration to the most recent version. I've also checked the Eufy app to ensure notifications are turned on for the doorbell.

<img width="910" alt="Screenshot 2023-11-07 205758" src="https://github.com/fuatakgun/eufy_security/assets/96394856/87c66716-d1e9-45a2-9dca-3b3be33fd4ad">

**Comment by fuatakgun** [comment]
Integration expects a message from add-on whenever there is a motion detected, person detected etc events are happening and I do not see any messages are coming from add-on to integration. 

As you already cleared out notifications setup on mobile app, I suggest you to work with bropat as this is beyond my skills.
