### ISSUE TITLE
Recently migrated from Add-on to WS - t8520 door lock unavailable

### ISSUE THREAD

**Issue by shieldmaiden95** [fuatakgun/eufy_security#987]
**Describe the bug**

My integration quit working months ago. 2 days ago I found out about Eufy Security WS and migrated hoping that would fix the issue. When I went to my integrations an instance of the Eufy Security integration was automatically discovered and popped up at the top of the list requiring configuration. When I tried to configure it it kept asking for a captcha and giving me this error:

_Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble_

Today I saw there was an update for Eufy Security WS so I tried updating it hoping that would fix the problem. I'm no longer being asked for a captcha and my device is discovered but all the entities are unavailable. I don't know what to make of the logs.

**To reproduce**

1. Go to 'integrations'
2. Set up Eufy Security integration, click submit
3. Click finish on the pop up "Success!" dialog box
4. Click on entities under the newly added device, see that they're all unavailable

**Expected behavior**

I expected the entities to populate with data after clicking finish.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): **Home Assistant OS**
- Home Assistant Core Version: **core-2023.11.0**
- Eufy Security Add-on Version: **eufy-security-ws 1.7.1**
- Eufy Security Integration Version: **v7.7.3**

Hardware Information;
- Camera Model: 
N/A device is door lock t8520

- Live Streaming Protocol (RTSP/P2P): 
N/A

- Debug Logs from Home Assistant 
[home-assistant-FULL-log_2023-11-08.txt](https://github.com/fuatakgun/eufy_security/files/13294597/home-assistant-FULL-log_2023-11-08.txt)

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
[eufy-sec-ws-log.txt](https://github.com/fuatakgun/eufy_security/files/13294610/eufy-sec-ws-log.txt)

- Would you share your device with me in case further debugging required? (Yes/No):
Possibly, I don't really know what that means.

**Additional context**
None

**Comment by fuatakgun** [comment]
Please check #984 but we have to close it without finding a solution.

**Comment by fuatakgun** [comment]
if you can, please share your device with me?

and mention about your timezone and what specific times of the day, I can tinker with it?

**Comment by fuatakgun** [comment]
#973
