### ISSUE TITLE
Snapshot service doesn't work

### ISSUE THREAD

**Issue by floow77** [fuatakgun/eufy_security#992]
**Describe the bug**

Service camera.snapshot doesn't work. The service execute without error but image generated  is not up to date.

**Additional information**

- Home Assistant OS: 211.1
- Home Assistant Core Version: 2023.11.2
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: 7.7.4

Hardware Information;
- Camera Model: Eufy cam 2C

**Comment by fuatakgun** [comment]
Please follow the bug template
