### ISSUE TITLE
Cannot stream video of camera in Eufy security doorbell 

### ISSUE THREAD

**Issue by eruisi** [fuatakgun/eufy_security#996]
**Describe the bug**

1. No video stream when click on entity camera.doorbell, just a static picture
2. Static picture is updated irregularly
3. RTSP URL not playable in other video player

**To reproduce**

Click on the camera icon in HA either in floorplan or dashboard, I expect to see live stream from the camera, but I only see a static image that was shot a while ago (no clue how long before). If I click "Start P2P stream", Logbooks start rolling but still no video stream visible for camera.

**Expected behavior**

I expect to see live stream when I click the icon, and live stream will stop when I close the window. I expect to see static picture on dashboard every time the camera detects human motion.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS
- Home Assistant Core Version: core-2023.11.2
- Eufy Security Add-on Version:  eufy-security-ws (1.7.1)
- Eufy Security Integration Version: v7.7.4

Hardware Information;
- Camera Model: T8221-Z

- Live Streaming Protocol (RTSP/P2P): P2P

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  attach in file

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-11-11 11:13:16.844  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-11-11 11:13:25.370  INFO  Connected to station T8010P1321241488 on host 192.168.0.50 and port 19895 
2023-11-11 11:13:26.746  INFO  MQTT connection successfully established 
2023-11-11 11:13:26.885  INFO  Successfully registered to MQTT notifications for lock T8520Q10212500AF 
2023-11-11 11:13:30.196  INFO  Connected to station T8520Q10212500AF on host 192.168.0.62 and port 28406 
2023-11-11 11:13:30.427  INFO  Push notification connection successfully established 
2023-11-11 11:14:00.467  INFO  Initiated closing of connection to station T8520Q10212500AF for saving battery. 
2023-11-11 11:14:00.472  INFO  Disconnected from station T8520Q10212500AF 

- Would you share your device with me in case further debugging required? (Yes/No): Yes

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by eruisi** [comment]
It turns out that my Host IP Address was somehow set to "true" by mistake. After I set it to "127.0.0.1" everything works perfectly. Thank fuatakgun for debugging the issue with me live time. Really appreciate it!

**Comment by fuatakgun** [comment]
welcome, happy to see that it is working.

**Comment by eruisi** [comment]
Please wait. I restarted HA then see static image again.

**Comment by fuatakgun** [comment]
as you need to use start p2p livestream service to see the live image.

**Comment by eruisi** [comment]
Can I start streaming service automatically when I click the camera and
stop the service when I close the camera?

**Comment by fuatakgun** [comment]
no, I cannot distinguish clicking on camera image vs home assistant is trying to fetch snapshot every 10 seconds and it will start streaming of your camera and drain the battery

**Comment by eruisi** [comment]
Ok. not 100% prefect but I can live with it. Thank you so much for your time.

**Comment by eruisi** [comment]
Tried to Start/Stop Stream Service when HA starts, but it doesn't help.

Start Doorbell Stream Service when HA Restart triggered by Home Assistant
starting
6:06:08 AM - 9 minutes ago
Doorbell Start P2P Stream changed to November 11, 2023 at 6:06 AM triggered
by automation Start Doorbell Stream Service when HA Restart triggered by
Home Assistant starting
6:06:08 AM - 9 minutes ago
Doorbell Stop P2P Stream changed to November 11, 2023 at 6:07 AM triggered
by automation Start Doorbell Stream Service when HA Restart triggered by
Home Assistant starting
6:07:01 AM - 8 minutes ago

**Comment by fuatakgun** [comment]
Logs are needed :-)

**Comment by eruisi** [comment]
I found original issues I tried to fix in the ticket. I can see live video only when click the "Start P2P Stream" button in Doorbell Configuration. and I need to click "Stop P2P Stream" after watching video.
Is it expected way of handling it? If not, can I request a new appointment to debug?

**Comment by fuatakgun** [comment]
Please read README.

Lastly, your camera would not start streaming magically by itself, you have to call turn_on or turn_off services of respective camera entities. So, when you first install everything, you would not have any video until you call these functions. Moreover, P2P streaming might stop randomly because of low level issues, you can restart it again with turn_off and turn_on. You can trigger your automation's on camera states (idle, preparing, streaming).

**Comment by eruisi** [comment]
Thank you for all the help. For the complexity I decided to switch to Aqara U100 + G4 doorbell (on sale for Thanksgiving).
Stay away from Eufy till it supports HomeKit better.
