### ISSUE TITLE
Feature Request: Add Connectivity Sensor

### ISSUE THREAD

**Issue by benjani85** [fuatakgun/eufy_security#999]
**Is your feature request related to a problem? Please describe.**
Cameras sometimes go offline in the official Eufy app (lost connection to Homebase or worst case stolen) and there is no way of telling without opening and checking the app.

**Describe the solution you'd like**
A new sensor that can detect when connectivity to a device has gone offline which can then be linked to Home Assistant automations for notifications.

TIA

**Comment by fuatakgun** [comment]
connected sensor is added

**Comment by benjani85** [comment]
Thanks for implementing this. I couldn't find the new sensor - would you be able to advise where I can find it please?

**Comment by fuatakgun** [comment]
It is under the diagnostic category and disabled by default.

**Comment by fuatakgun** [comment]
![Screenshot_2024-01-26-07-09-40-083_io.homeassistant.companion.android-edit.jpg](https://github.com/fuatakgun/eufy_security/assets/11085566/f2f2efba-5b2e-43d4-a738-992993483bfa)

**Comment by benjani85** [comment]
Great found it. How does it work? If 1 or more cameras go offline does the state change from on to off?

**Comment by benjani85** [comment]
Will there be any update to the documentation on what 'Connected' actually means?
